Repository openshift/origin, pull requests merged in 2018-03, with the labels that each got.

#17420 Make updating status on the router optional
  pkg/cmd/infra/router/f5.go
  pkg/cmd/infra/router/router.go
  pkg/cmd/infra/router/template.go
  pkg/router/controller/status.go
  pkg/router/controller/unique_host.go
  test/extended/router/headers.go
  test/extended/router/metrics.go
  test/extended/router/scoped.go
  test/extended/router/unprivileged.go
  test/extended/router/weighted.go
  test/extended/testdata/bindata.go
  test/extended/testdata/scoped-router.yaml
Labels: approved, lgtm, size/L

#18745 Add an error text check for project validation
  pkg/project/apis/project/validation/validation_test.go
Labels: approved, lgtm, size/S

#18637 UPSTREAM: 59170: Fix kubelet PVC stale metrics
  vendor/k8s.io/kubernetes/pkg/kubelet/BUILD
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go
  vendor/k8s.io/kubernetes/pkg/kubelet/metrics/BUILD
  vendor/k8s.io/kubernetes/pkg/kubelet/metrics/collectors/BUILD
  vendor/k8s.io/kubernetes/pkg/kubelet/metrics/collectors/helper_test.go
  vendor/k8s.io/kubernetes/pkg/kubelet/metrics/collectors/volume_stats.go
  vendor/k8s.io/kubernetes/pkg/kubelet/metrics/collectors/volume_stats_test.go
  vendor/k8s.io/kubernetes/pkg/kubelet/metrics/metrics.go
  vendor/k8s.io/kubernetes/pkg/kubelet/server/stats/BUILD
  vendor/k8s.io/kubernetes/pkg/kubelet/server/stats/volume_stat_calculator.go
Labels: approved, lgtm, size/XL, vendor-update

#18766 UPSTREAM: 60342: Fix nested volume mounts for read-only API data volumes
  vendor/k8s.io/kubernetes/pkg/volume/configmap/configmap.go
  vendor/k8s.io/kubernetes/pkg/volume/downwardapi/downwardapi.go
  vendor/k8s.io/kubernetes/pkg/volume/projected/projected.go
  vendor/k8s.io/kubernetes/pkg/volume/secret/secret.go
  vendor/k8s.io/kubernetes/pkg/volume/util/BUILD
  vendor/k8s.io/kubernetes/pkg/volume/util/nested_volumes.go
  vendor/k8s.io/kubernetes/pkg/volume/util/nested_volumes_test.go
Labels: approved, kind/bug, lgtm, size/L, vendor-update

#18785 Fix initContainer name lookup for ImageChange trigger
  pkg/image/trigger/deploymentconfigs/deploymentconfigs.go
Labels: approved, cherrypick-candidate, lgtm, size/XS

#15409 Support for DNS names in egress routes
  hack/lib/constants.sh
  images/egress/dns-proxy/.cccp.yml
  images/egress/dns-proxy/Dockerfile
  images/egress/dns-proxy/egress-dns-proxy.sh
  images/egress/dns-proxy/egress_dns_proxy_test.go
  images/egress/router/egress-router.sh
Labels: approved, component/networking, lgtm, sig/networking, size/L

#18763 Wipe off registry cache
  test/extended/images/hardprune.go
  test/extended/images/prune.go
Labels: approved, lgtm, size/L

#18781 Fixes: cannot prune builds on buildConfig change
  pkg/cmd/server/bootstrappolicy/controller_policy.go
  test/extended/builds/build_pruning.go
  test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml
  test/testdata/bootstrappolicy/bootstrap_policy_file.yaml
Labels: approved, lgtm, sig/developer-experience, size/M

#18769 add ext test for pipeline bc deletion behavior
  test/extended/builds/pipeline.go
Labels: approved, lgtm, sig/developer-experience, size/M

#18601 Run cluster-up using separate processes
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  hack/test-end-to-end-docker.sh
  install/etcd/etcd.yaml
  install/kube-apiserver/apiserver.yaml
  install/kube-controller-manager/kube-controller-manager.yaml
  install/kube-dns/install.yaml
  install/kube-proxy/install.yaml
  install/kube-scheduler/kube-scheduler.yaml
  install/openshift-controller-manager/install.yaml
  pkg/oc/bootstrap/bindata.go
  pkg/oc/bootstrap/clusterup/kubeapiserver/config.go
  pkg/oc/bootstrap/clusterup/kubelet/config.go
  pkg/oc/bootstrap/clusterup/kubelet/dns.go
  pkg/oc/bootstrap/clusterup/kubelet/flags.go
  pkg/oc/bootstrap/clusterup/kubelet/run_kubelet.go
  pkg/oc/bootstrap/clusterup/staticpods/load.go
  pkg/oc/bootstrap/clusterup/tmpformac/tmp_for_mac_snowflakes.go
  pkg/oc/bootstrap/docker/fileutils_unix.go
  pkg/oc/bootstrap/docker/fileutils_windows.go
  pkg/oc/bootstrap/docker/host/host.go
  pkg/oc/bootstrap/docker/openshift/admin.go
  pkg/oc/bootstrap/docker/openshift/ansible.go
  pkg/oc/bootstrap/docker/openshift/helper.go
  pkg/oc/bootstrap/docker/openshift/helper_unix.go
  pkg/oc/bootstrap/docker/openshift/helper_windows.go
  pkg/oc/bootstrap/docker/run_self_hosted.go
  pkg/oc/bootstrap/docker/up.go
  test/end-to-end/core.sh
  test/extended/clusterup.sh
  test/extended/testdata/bindata.go
Labels: approved, lgtm, size/XXL

#18751 audit doesn't respect embedded config
  pkg/cmd/server/kubernetes/master/master_config.go
Labels: approved, lgtm, size/XS

#18540 change how extended network tests are selected/skipped
  test/extended/cni_vendor_test.sh
  test/extended/networking.sh
  test/extended/networking/isolation.go
  test/extended/networking/multicast.go
  test/extended/networking/services.go
  test/extended/networking/util.go
  test/extended/util/test.go
Labels: approved, area/tests, lgtm, sig/networking, size/L

#18767 UPSTREAM: 60289: fix freespace for image GC
  vendor/k8s.io/kubernetes/pkg/kubelet/images/image_gc_manager.go
Labels: approved, kind/bug, lgtm, size/XS, vendor-update

#18801 Fix handleDeleteSubnet() to release network from subnet allocator
  pkg/network/master/subnets.go
Labels: approved, component/networking, lgtm, sig/networking, size/XS

#18245 Preserve router metrics across restarts
  pkg/cmd/infra/router/template.go
  pkg/router/metrics/haproxy/haproxy.go
  test/extended/router/metrics.go
Labels: approved, lgtm, sig/networking, size/L

#18782 Fixes: cannot prune builds on buildConfig change
  pkg/cmd/server/bootstrappolicy/controller_policy.go
  test/extended/builds/build_pruning.go
  test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml
  test/testdata/bootstrappolicy/bootstrap_policy_file.yaml
Labels: approved, lgtm, size/M

#18792 [3.9] UPSTREAM: 54530: api: validate container phase transitions
  vendor/k8s.io/kubernetes/pkg/apis/core/validation/validation.go
Labels: approved, kind/bug, lgtm, size/M, vendor-update

#18813 Add enj to completions OWNERS
  contrib/completions/OWNERS
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#18797 UPSTREAM: 59365: Fix StatefulSet set-based selector bug
  vendor/k8s.io/kubernetes/pkg/controller/history/controller_history.go
  vendor/k8s.io/kubernetes/pkg/controller/history/controller_history_test.go
  vendor/k8s.io/kubernetes/pkg/controller/statefulset/stateful_set_utils.go
Labels: approved, lgtm, size/L, vendor-update

#18842 Allow all nodes to run upstream kube tests
  test/extended/util/test.go
Labels: approved, lgtm, queue/critical-fix, size/XS

#18843 Allow all nodes to run upstream kube tests
  test/extended/util/test.go
Labels: approved, lgtm, queue/critical-fix, size/XS

#18666 exclude some namespaces in run levels based on name
  pkg/admission/namespaceconditions/decorator.go
  pkg/admission/namespaceconditions/namecondition.go
Labels: approved, lgtm, size/M

#18810 UPSTREAM: 57202: Fix format string in describers
  vendor/k8s.io/kubernetes/pkg/printers/internalversion/describe.go
Labels: approved, lgtm, size/XS, vendor-update

#18430 UPSTREAM: 59316: Exit if no client cert is available for 5m
  vendor/k8s.io/kubernetes/cmd/kubelet/app/server.go
  vendor/k8s.io/kubernetes/pkg/kubelet/certificate/transport.go
  vendor/k8s.io/kubernetes/pkg/kubelet/certificate/transport_test.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/util/certificate/certificate_manager.go
Labels: approved, lgtm, size/M, vendor-update

#18517 Add migrate command for legacy HPAs
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  docs/man/man1/.files_generated_oc
  docs/man/man1/oc-adm-migrate-legacy-hpa.1
  pkg/oc/admin/admin.go
  pkg/oc/admin/migrate/legacyhpa/hpa.go
  pkg/oc/admin/migrate/legacyhpa/hpa_test.go
  test/cmd/migrate.sh
  test/testdata/hpa/legacy-and-normal-hpa.yaml
Labels: approved, kind/bug, lgtm, size/L

#18653 Use ^uint32(0) instead of 0XFFFFFFFF
  pkg/oc/bootstrap/docker/dockerhelper/ipv4range.go
Labels: approved, lgtm, size/XS

#18774 pin dependencies for 3.9
  glide.lock
  glide.yaml
  vendor/github.com/openshift/client-go/glide.lock
  vendor/github.com/openshift/client-go/glide.yaml
Labels: approved, lgtm, sig/master, size/L, vendor-update

#18793 Remove Service Catalog Controller Manager service & fix port
  examples/service-catalog/service-catalog.yaml
  pkg/oc/bootstrap/bindata.go
Labels: approved, lgtm, size/M

#18839 adjust jenkins template setting to account for effects of constrained…
  examples/jenkins/jenkins-ephemeral-template.json
  examples/jenkins/jenkins-persistent-template.json
  pkg/oc/bootstrap/bindata.go
  test/extended/testdata/bindata.go
Labels: approved, lgtm, size/M

#18829 Update path to registries file
  docs/cluster_up_down.md
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#18714 diagnostics: missing logging project shouldn't be fatal error
  pkg/oc/admin/diagnostics/diagnostics/cluster/aggregated_logging/diagnostic.go
Labels: approved, component/diagnostics, lgtm, size/XS

#15972 Updating CONTRIBUTING.adoc
  CONTRIBUTING.adoc
Labels: approved, lgtm, lifecycle/stale, retest-not-required, size/XS

#18587 Fix router reload errors for deleted certificates
  pkg/router/template/certmanager.go
  pkg/router/template/certmanager_test.go
  pkg/router/template/router.go
  pkg/router/template/types.go
Labels: approved, component/routing, kind/bug, lgtm, size/M

#18296 Label the projects created by cluster-loader
  test/extended/cluster/cl.go
  test/extended/cluster/context.go
  test/extended/cluster/utils.go
Labels: approved, lgtm, size/S

#18667 add hypershift kube-apiserver and openshift-apiserver
  cmd/hypershift/main.go
  hack/build-local-images.py
  hack/lib/constants.sh
  origin.spec
  pkg/cmd/openshift-apiserver/cmd.go
  pkg/cmd/openshift-apiserver/server.go
  pkg/cmd/openshift-kube-apiserver/cmd.go
  pkg/cmd/openshift-kube-apiserver/server.go
  pkg/cmd/server/origin/aggregator.go
  pkg/cmd/server/origin/handlers.go
  pkg/cmd/server/origin/informers.go
  pkg/cmd/server/origin/master.go
  pkg/cmd/server/origin/master_config.go
  pkg/cmd/server/origin/openshift_apiserver.go
  pkg/cmd/server/origin/profiler.go
  pkg/cmd/server/start/controllers.go
  pkg/cmd/server/start/start_allinone.go
  pkg/cmd/server/start/start_api.go
  pkg/cmd/server/start/start_controllers.go
  pkg/cmd/server/start/start_etcd.go
  pkg/cmd/server/start/start_master.go
  pkg/cmd/server/start/start_node.go
  pkg/oauthserver/oauthserver/oauth_apiserver.go
  test/integration/buildcontroller_test.go
  test/integration/master_routes_test.go
Labels: approved, lgtm, sig/master, size/XL

#18665 use the correct loopback connection
  pkg/apps/apiserver/apiserver.go
  pkg/authorization/apiserver/apiserver.go
  pkg/build/apiserver/apiserver.go
  pkg/cmd/server/origin/master.go
  pkg/cmd/server/origin/openshift_apiserver.go
  pkg/image/apiserver/apiserver.go
  pkg/oauth/apiserver/apiserver.go
  pkg/project/apiserver/apiserver.go
  pkg/route/apiserver/apiserver.go
  pkg/security/apiserver/apiserver.go
  pkg/template/apiserver/apiserver.go
Labels: approved, lgtm, sig/master, size/M

#18532 explicitly prohibit updates to imagestream tags that are not spec tags
  pkg/image/registry/imagestreamtag/rest.go
Labels: approved, lgtm, size/XS

#18807 Fix golang check so that it performs arithemtic comparison
  hack/lib/util/golang.sh
Labels: approved, lgtm, size/XS

#18791 UPSTREAM: 54530: api: validate container phase transitions
  vendor/k8s.io/kubernetes/pkg/apis/core/validation/validation.go
Labels: approved, kind/bug, lgtm, queue/fix, size/M, vendor-update

#18677 Grab the sa token per namespace.
  examples/grafana/setup-grafana.sh
Labels: approved, area/examples, lgtm, size/S

#18820 UPSTREAM: 58977: Fix pod sandbox privilege.
  vendor/k8s.io/kubernetes/pkg/kubelet/container/helpers.go
  vendor/k8s.io/kubernetes/pkg/kubelet/container/helpers_test.go
Labels: approved, kind/bug, lgtm, queue/fix, size/S, vendor-update

#18882 UPSTREAM: <carry>: ensure hijackedConn implements CloseWrite function
  vendor/github.com/docker/docker/client/hijack.go
Labels: approved, lgtm, queue/critical-fix, retest-not-required, size/XS, vendor-update

#18883 UPSTREAM: <carry>: ensure hijackedConn implements CloseWrite function
  vendor/github.com/docker/docker/client/hijack.go
Labels: approved, lgtm, retest-not-required, size/XS, vendor-update

#18835 Allow all node scheduling for more tests
  test/extended/util/test.go
Labels: approved, lgtm, size/XS

#18857 Warn when AuditFilePath is relative
  pkg/cmd/server/apis/config/serialization_test.go
  pkg/cmd/server/apis/config/types.go
  pkg/cmd/server/apis/config/v1/conversions.go
  pkg/cmd/server/apis/config/validation/master.go
Labels: approved, lgtm, needs-api-review, size/S

#18641 diagnostics: AggregatedLogging ClusterRoleBindings false negative fix
  pkg/oc/admin/diagnostics/diagnostics/cluster/aggregated_logging/clusterrolebindings.go
  pkg/oc/admin/diagnostics/diagnostics/cluster/aggregated_logging/clusterrolebindings_test.go
  pkg/oc/admin/diagnostics/diagnostics/cluster/aggregated_logging/diagnostic.go
  pkg/oc/admin/diagnostics/diagnostics/cluster/aggregated_logging/interfaces.go
Labels: approved, component/diagnostics, lgtm, size/M

#18656 Remove invalid SuggestFor from prune deployments
  pkg/oc/admin/prune/deployments.go
Labels: approved, lgtm, size/XS

#18837 Reorder groups in cert Subjects
  pkg/cmd/server/crypto/crypto.go
Labels: approved, lgtm, size/M

#18780 fix manifestlist mirroring
  pkg/oc/cli/cmd/image/mirror/mirror.go
Labels: approved, lgtm, size/XS

#18802 examples/prometheus: fix some prometheus service discovery scraping
  examples/prometheus/prometheus.yaml
  pkg/oc/bootstrap/bindata.go
  test/extended/testdata/bindata.go
Labels: approved, lgtm, size/M

#18391 Prometheus config reload livenessprobe
  examples/prometheus/prometheus.yaml
  pkg/oc/bootstrap/bindata.go
  test/extended/testdata/bindata.go
Labels: approved, lgtm, size/M

#18832 adjust jenkins template setting to account for effects of constrained…
  examples/jenkins/jenkins-ephemeral-template.json
  examples/jenkins/jenkins-persistent-template.json
  pkg/oc/bootstrap/bindata.go
  test/extended/testdata/bindata.go
Labels: approved, lgtm, sig/developer-experience, size/M

#18808 Multiple auto-egress-IP fixes
  pkg/network/node/egressip.go
  pkg/network/node/egressip_test.go
  pkg/network/node/ovscontroller.go
Labels: approved, component/networking, kind/bug, lgtm, sig/networking, size/XL

#18836 misc cluster up fixes
  pkg/oc/bootstrap/clusterup/tmpformac/copy.go
  pkg/oc/bootstrap/docker/fileutils_unix.go
  pkg/oc/bootstrap/docker/run/run.go
  pkg/oc/bootstrap/docker/run_self_hosted.go
  test/extended/clusterup.sh
Labels: approved, lgtm, size/L

#18865 add some debug to old jenkins plugin tests
  test/extended/image_ecosystem/jenkins_plugin.go
Labels: approved, lgtm, sig/developer-experience, size/M

#18466 Adds trace cmd
  tools/depcheck/examples/origin_excludes.json
  tools/depcheck/examples/origin_filters.json
  tools/depcheck/pkg/cmd/cmd.go
  tools/depcheck/pkg/cmd/trace.go
  tools/depcheck/pkg/graph/filter.go
  tools/depcheck/pkg/graph/filter_test.go
  tools/depcheck/pkg/graph/flags.go
  tools/depcheck/pkg/graph/graph.go
  tools/depcheck/pkg/graph/openshift.go
  tools/depcheck/pkg/graph/pkg.go
  tools/depcheck/pkg/graph/pkg_test.go
Labels: approved, lgtm, size/XXL

#18869 clip more dependencies from oauthserver
  hack/import-restrictions.json
  pkg/cmd/server/origin/oauth_apiserver_adapter.go
  pkg/cmd/util/net.go
  pkg/oauth/apiserver/apiserver.go
  pkg/oauthserver/oauthserver/auth.go
  pkg/oauthserver/oauthserver/oauth_apiserver.go
  pkg/oauthserver/oauthserver/oauth_apiserver_test.go
  pkg/oc/bootstrap/docker/openshift/helper.go
  pkg/serviceaccounts/oauthclient/oauthclientregistry.go
  pkg/serviceaccounts/oauthclient/oauthclientregistry_test.go
Labels: approved, lgtm, sig/security, size/L

#18494 add negative checking for new-app
  pkg/oc/cli/cmd/newapp_test.go
Labels: approved, lgtm, size/M

#18879 Don't try to delete (nonexistent) OVS flows for headless/external services
  pkg/network/node/node.go
Labels: approved, component/networking, kind/bug, lgtm, sig/networking, size/XS

#18844 Etcdhelper improvements
  test/cmd/etcdhelper.sh
  tools/etcdhelper/README.md
  tools/etcdhelper/etcdhelper.go
Labels: approved, lgtm, size/M

#18886 UPSTREAM: 60654: notify systemd on kubelet start
  vendor/k8s.io/kubernetes/cmd/kubelet/app/server.go
Labels: approved, lgtm, size/XS, vendor-update

#18811 Register audit/v1beta1 for master config
  pkg/cmd/server/apis/config/install/install.go
  pkg/cmd/server/apis/config/validation/master.go
  test/integration/audit_test.go
Labels: approved, lgtm, size/M

#18805 Expose --v in oc
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cmd/flagtypes/glog.go
  pkg/oc/cli/cmd/process.go
  pkg/oc/cli/cmd/set/deploymenthook.go
  pkg/oc/cli/cmd/status.go
  test/cmd/admin.sh
  test/cmd/debug.sh
  test/cmd/get.sh
  test/cmd/services.sh
  test/cmd/set-liveness-probe.sh
  test/cmd/templates.sh
  test/end-to-end/core.sh
Labels: approved, lgtm, size/M

#18848 nest daemonsets under their services
  pkg/oc/cli/describe/projectstatus.go
  pkg/oc/graph/genericgraph/graphview/service_group.go
Labels: approved, lgtm, size/S

#18734 Upgrade Prometheus AlertManager to v0.14.0
  examples/prometheus/prometheus-standalone.yaml
  examples/prometheus/prometheus.yaml
  pkg/oc/bootstrap/bindata.go
  test/extended/testdata/bindata.go
Labels: approved, lgtm, size/XS

#18850 sdn: wait until container runtime is actually ready before using it
  pkg/network/node/runtime.go
Labels: approved, component/networking, lgtm, size/XS

#18877 [3.9] UPSTREAM: opencontainers/runc: 1754: Add timeout while waiting for StartTransinetUnit completion signal
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/apply_systemd.go
Labels: approved, kind/bug, lgtm, size/XS, vendor-update

#18898 Add OWNERS for cluster loader
  test/extended/cluster/OWNERS
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#18778 apply build defaults to init containers
  pkg/build/controller/build/defaults/defaults.go
  pkg/build/controller/build/defaults/defaults_test.go
Labels: approved, lgtm, size/M

#18709 diagnostic reorg and NetworkCheck fix
  pkg/oc/admin/diagnostics/client.go
  pkg/oc/admin/diagnostics/cluster.go
  pkg/oc/admin/diagnostics/diagnostics.go
  pkg/oc/admin/diagnostics/diagnostics/client/pod/in_pod/auth.go
  pkg/oc/admin/diagnostics/diagnostics/client/pod/in_pod/cmd.go
  pkg/oc/admin/diagnostics/diagnostics/client/pod/in_pod/dns.go
  pkg/oc/admin/diagnostics/diagnostics/client/pod/in_pod/util.go
  pkg/oc/admin/diagnostics/diagnostics/client/pod/run_diagnostics_pod.go
  pkg/oc/admin/diagnostics/diagnostics/cluster/network/in_pod/cmd.go
  pkg/oc/admin/diagnostics/diagnostics/cluster/network/in_pod/collect.go
  pkg/oc/admin/diagnostics/diagnostics/cluster/network/in_pod/external.go
  pkg/oc/admin/diagnostics/diagnostics/cluster/network/in_pod/node.go
  pkg/oc/admin/diagnostics/diagnostics/cluster/network/in_pod/pod.go
  pkg/oc/admin/diagnostics/diagnostics/cluster/network/in_pod/service.go
  pkg/oc/admin/diagnostics/diagnostics/cluster/network/in_pod/util/log.go
  pkg/oc/admin/diagnostics/diagnostics/cluster/network/in_pod/util/util.go
  pkg/oc/admin/diagnostics/diagnostics/cluster/network/in_pod/util/util_test.go
  pkg/oc/admin/diagnostics/diagnostics/cluster/network/objects.go
  pkg/oc/admin/diagnostics/diagnostics/cluster/network/results.go
  pkg/oc/admin/diagnostics/diagnostics/cluster/network/run_pod.go
  pkg/oc/admin/diagnostics/diagnostics/cluster/network/setup.go
  pkg/oc/admin/diagnostics/diagnostics/log/text.go
  pkg/oc/admin/diagnostics/util/util.go
Labels: approved, component/diagnostics, lgtm, size/L

#18876 UPSTREAM: opencontainers/runc: 1754: Add timeout while waiting for StartTransinetUnit completion signal
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/apply_systemd.go
Labels: approved, kind/bug, lgtm, size/XS, vendor-update

#18652 Run openshift aggregated behind kube
  install/kube-apiserver/apiserver.yaml
  install/openshift-apiserver/install.yaml
  install/openshift-controller-manager/install.yaml
  pkg/oc/bootstrap/bindata.go
  pkg/oc/bootstrap/clusterup/componentinstall/readiness_apigroup.go
  pkg/oc/bootstrap/clusterup/kubeapiserver/config.go
  pkg/oc/bootstrap/clusterup/kubeapiserver/openshift_apiserver.go
  pkg/oc/bootstrap/clusterup/kubelet/config.go
  pkg/oc/bootstrap/clusterup/kubelet/dns.go
  pkg/oc/bootstrap/clusterup/kubelet/flags.go
  pkg/oc/bootstrap/clusterup/kubelet/run_kubelet.go
  pkg/oc/bootstrap/clusterup/tmpformac/tmp_for_mac_snowflakes.go
  pkg/oc/bootstrap/docker/host/host.go
  pkg/oc/bootstrap/docker/openshift/pvsetup.go
  pkg/oc/bootstrap/docker/openshift/servicecatalog.go
  pkg/oc/bootstrap/docker/openshift/util.go
  pkg/oc/bootstrap/docker/run_self_hosted.go
  pkg/oc/bootstrap/docker/up.go
  test/end-to-end/core.sh
  test/extended/testdata/bindata.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/apiserver/apiserver.go
Labels: approved, lgtm, size/XXL, vendor-update

#18908 Remove 2000 lines of oc cluster up cruft
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  docs/man/man1/.files_generated_oc
  docs/man/man1/oc-cluster-join.1
  examples/logging/OWNERS
  examples/logging/logging-deployer.yaml
  hack/import-restrictions.json
  hack/update-generated-bindata.sh
  install/templateservicebroker/previous/apiserver-template.yaml
  pkg/oc/bootstrap/bindata.go
  pkg/oc/bootstrap/docker/dockermachine/errors.go
  pkg/oc/bootstrap/docker/dockermachine/helper.go
  pkg/oc/bootstrap/docker/host/host.go
  pkg/oc/bootstrap/docker/join.go
  pkg/oc/bootstrap/docker/openshift/admin.go
  pkg/oc/bootstrap/docker/openshift/ansible.go
  pkg/oc/bootstrap/docker/openshift/helper.go
  pkg/oc/bootstrap/docker/openshift/import.go
  pkg/oc/bootstrap/docker/openshift/logging.go
  pkg/oc/bootstrap/docker/openshift/metrics.go
  pkg/oc/bootstrap/docker/openshift/servicecatalog.go
  pkg/oc/bootstrap/docker/run_self_hosted.go
  pkg/oc/bootstrap/docker/up.go
  pkg/oc/cli/cmd/cluster/cluster.go
  test/extended/testdata/bindata.go
Labels: approved, lgtm, sig/master, size/XXL

#18919 UPSTREAM: 60978: Fix use of "-w" flag to iptables-restore
  vendor/k8s.io/kubernetes/pkg/util/iptables/iptables.go
  vendor/k8s.io/kubernetes/pkg/util/iptables/iptables_test.go
Labels: approved, component/networking, kind/bug, lgtm, sig/networking, size/M, vendor-update

#18887 create hypershift openshift-controller-manager
  cmd/hypershift/main.go
  pkg/cmd/openshift-controller-manager/cmd.go
  pkg/cmd/openshift-controller-manager/controller/apiserver_authenticator.go
  pkg/cmd/openshift-controller-manager/controller/apiserver_handlers.go
  pkg/cmd/openshift-controller-manager/controller/apps.go
  pkg/cmd/openshift-controller-manager/controller/autoscaling.go
  pkg/cmd/openshift-controller-manager/controller/build.go
  pkg/cmd/openshift-controller-manager/controller/config.go
  pkg/cmd/openshift-controller-manager/controller/image.go
  pkg/cmd/openshift-controller-manager/controller/interfaces.go
  pkg/cmd/openshift-controller-manager/controller/network.go
  pkg/cmd/openshift-controller-manager/controller/network_sdn.go
  pkg/cmd/openshift-controller-manager/controller/project.go
  pkg/cmd/openshift-controller-manager/controller/quota.go
  pkg/cmd/openshift-controller-manager/controller/service.go
  pkg/cmd/openshift-controller-manager/controller/serviceaccount.go
  pkg/cmd/openshift-controller-manager/controller/standalone_apiserver.go
  pkg/cmd/openshift-controller-manager/controller/template.go
  pkg/cmd/openshift-controller-manager/controller/unidling.go
  pkg/cmd/openshift-controller-manager/controller_manager.go
  pkg/cmd/server/start/controllers.go
  pkg/cmd/server/start/start_master.go
  test/integration/buildcontroller_test.go
  vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go
  vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/patch_recycler.go
Labels: approved, lgtm, sig/master, size/XL, vendor-update

#18910 segfault with invalid template
  pkg/util/labels.go
Labels: approved, lgtm, sig/developer-experience, size/XS

#18901 add better logging for oc cluster up component install
  pkg/oc/bootstrap/clusterup/componentinstall/apply_list.go
  pkg/oc/bootstrap/clusterup/componentinstall/apply_template.go
  pkg/oc/bootstrap/clusterup/componentinstall/interface.go
  pkg/oc/bootstrap/clusterup/componentinstall/log.go
  pkg/oc/bootstrap/clusterup/kubeapiserver/config.go
  pkg/oc/bootstrap/clusterup/kubeapiserver/openshift_apiserver.go
  pkg/oc/bootstrap/clusterup/kubelet/config.go
  pkg/oc/bootstrap/clusterup/kubelet/dns.go
  pkg/oc/bootstrap/clusterup/kubelet/flags.go
  pkg/oc/bootstrap/clusterup/kubelet/run_kubelet.go
  pkg/oc/bootstrap/docker/openshift/admin.go
  pkg/oc/bootstrap/docker/openshift/templateservicebroker.go
  pkg/oc/bootstrap/docker/run/errors.go
  pkg/oc/bootstrap/docker/run_self_hosted.go
  pkg/oc/bootstrap/docker/up.go
Labels: approved, lgtm, size/L

#18759 dind: update for latest ovn-kubernetes config changes
  images/dind/master/ovn-kubernetes-master.sh
  images/dind/node/ovn-kubernetes-node.sh
Labels: approved, lgtm, size/S

#18735 use owner references instead of timestamps to determine build/build pod ownership
  pkg/build/controller/build/build_controller.go
  pkg/build/controller/build/build_controller_test.go
  pkg/build/controller/strategy/util.go
Labels: approved, lgtm, size/L

#18746 One tiny suggest to separate oc debug info and yaml output
  pkg/oc/cli/cmd/debug.go
Labels: approved, lgtm, size/XS

#18680 Bug 1538006 - Improve error page when console not installed
  pkg/cmd/server/origin/master.go
  pkg/cmd/server/origin/service_proxy_handler.go
Labels: approved, lgtm, size/M

#18464 Allow configurable CNI bin dir in openshift SDN
  pkg/cmd/server/kubernetes/network/sdn_linux.go
  pkg/network/node/node.go
  pkg/network/node/pod.go
Labels: approved, component/networking, kind/bug, lgtm, sig/networking, size/M

#18756 Log test duration with json format for cluster-loader
  test/extended/cluster/cl.go
  test/extended/cluster/context.go
  test/extended/cluster/metrics.go
  test/extended/cluster/utils.go
Labels: approved, lgtm, size/M

#18945 Allow a new OS_PUSH_BASE_REPO flag to push-release
  hack/lib/constants.sh
  hack/push-release.sh
Labels: approved, lgtm, size/M

#18896 bootstrap: minor cluster up fixes (part 2)
  pkg/oc/bootstrap/clusterup/kubelet/run_kubelet.go
  pkg/oc/bootstrap/docker/dockerhelper/helper.go
  pkg/oc/bootstrap/docker/host/host.go
  pkg/oc/bootstrap/docker/openshift/helper.go
  pkg/oc/bootstrap/docker/up.go
Labels: approved, lgtm, size/L

#15559 Adds pod-concurrent-connections annotation.
  images/router/haproxy/conf/haproxy-config.template
Labels: approved, lgtm, size/XS

#18907 use the major.minor version as default for cluster up
  pkg/cmd/util/variable/variable.go
  pkg/oc/bootstrap/docker/up.go
Labels: approved, lgtm, sig/master, size/S

#18947 require templateinstance delete, not update, on unbind
  pkg/templateservicebroker/servicebroker/unbind.go
Labels: approved, lgtm, size/XS

#18949 Fix SDN startup log messages
  pkg/network/node/sdn_controller.go
Labels: approved, component/networking, lgtm, sig/networking, size/XS

#18943 switch kubedns to be copy of node config, not fresh creation
  pkg/oc/bootstrap/clusterup/kubelet/config.go
  pkg/oc/bootstrap/clusterup/kubelet/dns.go
  pkg/oc/bootstrap/docker/run_self_hosted.go
Labels: approved, lgtm, size/M

#18795 add controller to maintain default SA permissions
  pkg/authorization/controller/defaultrolebindings/defaultrolebindings.go
  pkg/authorization/controller/defaultrolebindings/defaultrolebindings_test.go
  pkg/cmd/openshift-controller-manager/controller/authorization.go
  pkg/cmd/openshift-controller-manager/controller/config.go
  pkg/cmd/server/bootstrappolicy/controller_policy.go
  pkg/cmd/server/bootstrappolicy/project_policy.go
  pkg/cmd/server/origin/ensure.go
  pkg/cmd/server/origin/master.go
  pkg/cmd/server/origin/openshift_apiserver.go
  pkg/project/registry/projectrequest/delegated/delegated.go
  pkg/project/registry/projectrequest/delegated/sample_template.go
  test/integration/authorization_test.go
  test/integration/master_routes_test.go
  test/testdata/bootstrappolicy/bootstrap_cluster_role_bindings.yaml
  test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml
  test/testdata/bootstrappolicy/bootstrap_policy_file.yaml
  test/testdata/bootstrappolicy/bootstrap_service_account_project_role_bindings.yaml
Labels: approved, lgtm, sig/master, size/XL

#18621 update origin to pull all imagestream+template content from library
  Makefile
  examples/db-templates/README.md
  examples/db-templates/mariadb-ephemeral-template.json
  examples/db-templates/mariadb-persistent-template.json
  examples/db-templates/mongodb-ephemeral-template.json
  examples/db-templates/mongodb-persistent-template.json
  examples/db-templates/mysql-ephemeral-template.json
  examples/db-templates/mysql-persistent-template.json
  examples/db-templates/postgresql-ephemeral-template.json
  examples/db-templates/postgresql-persistent-template.json
  examples/db-templates/redis-ephemeral-template.json
  examples/db-templates/redis-persistent-template.json
  examples/image-streams/README.md
  examples/image-streams/image-streams-centos7.json
  examples/image-streams/image-streams-rhel7.json
  examples/jenkins/jenkins-ephemeral-template.json
  examples/jenkins/jenkins-persistent-template.json
  examples/quickstarts/README.md
  examples/quickstarts/cakephp-mysql-persistent.json
  examples/quickstarts/cakephp-mysql.json
  examples/quickstarts/dancer-mysql-persistent.json
  examples/quickstarts/dancer-mysql.json
  examples/quickstarts/django-postgresql-persistent.json
  examples/quickstarts/django-postgresql.json
  examples/quickstarts/httpd.json
  examples/quickstarts/nginx.json
  examples/quickstarts/nodejs-mongodb-persistent.json
  examples/quickstarts/nodejs-mongodb.json
  examples/quickstarts/rails-postgresql-persistent.json
  examples/quickstarts/rails-postgresql.json
  hack/update-external-examples.sh
  pkg/oc/bootstrap/bindata.go
  test/cmd/debug.sh
  test/cmd/images.sh
  test/cmd/newapp.sh
  test/extended/testdata/bindata.go
Labels: approved, lgtm, size/XXL

#18948 require templateinstance delete, not update, on unbind
  pkg/templateservicebroker/servicebroker/unbind.go
Labels: approved, lgtm, size/XS

#18967 client plugin multinamespace test part 1: create template in repo tha…
  test/extended/testdata/bindata.go
  test/extended/testdata/multi-namespace-template.yaml
Labels: approved, lgtm, sig/developer-experience, size/L

#18970 Updating external examples
  examples/image-streams/image-streams-centos7.json
  examples/image-streams/image-streams-rhel7.json
  examples/quickstarts/django-postgresql-persistent.json
  examples/quickstarts/django-postgresql.json
  examples/quickstarts/rails-postgresql-persistent.json
  examples/quickstarts/rails-postgresql.json
  pkg/oc/bootstrap/bindata.go
  test/extended/testdata/bindata.go
Labels: approved, lgtm, size/L

#18809 Fix DC selectors for autoscaling
  pkg/apps/registry/deployconfig/etcd/etcd.go
Labels: approved, kind/bug, lgtm, size/S

#18971 UPSTREAM: <carry>: Remove write permissions on daemonsets from Kubernetes bootstrap policy
  test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml
  test/testdata/bootstrappolicy/bootstrap_policy_file.yaml
  vendor/k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go
  vendor/k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/cluster-roles.yaml
Labels: approved, kind/bug, lgtm, sig/security, size/L, vendor-update

#18957 [3.9] UPSTREAM: 61045: subpath fixes
  vendor/k8s.io/kubernetes/pkg/apis/core/validation/validation.go
  vendor/k8s.io/kubernetes/pkg/apis/core/validation/validation_test.go
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/pkg/kubelet/cm/container_manager_linux_test.go
  vendor/k8s.io/kubernetes/pkg/kubelet/container/helpers.go
  vendor/k8s.io/kubernetes/pkg/kubelet/container/testing/fake_runtime_helper.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_pods.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_pods_test.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_container.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_container_test.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_manager_test.go
  vendor/k8s.io/kubernetes/pkg/kubelet/rkt/rkt.go
  vendor/k8s.io/kubernetes/pkg/kubelet/util/util_unsupported.go
  vendor/k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler/reconciler.go
  vendor/k8s.io/kubernetes/pkg/util/mount/BUILD
  vendor/k8s.io/kubernetes/pkg/util/mount/exec_mount.go
  vendor/k8s.io/kubernetes/pkg/util/mount/exec_mount_test.go
  vendor/k8s.io/kubernetes/pkg/util/mount/exec_mount_unsupported.go
  vendor/k8s.io/kubernetes/pkg/util/mount/fake.go
  vendor/k8s.io/kubernetes/pkg/util/mount/mount.go
  vendor/k8s.io/kubernetes/pkg/util/mount/mount_linux.go
  vendor/k8s.io/kubernetes/pkg/util/mount/mount_linux_test.go
  vendor/k8s.io/kubernetes/pkg/util/mount/mount_unsupported.go
  vendor/k8s.io/kubernetes/pkg/util/mount/mount_windows.go
  vendor/k8s.io/kubernetes/pkg/util/mount/mount_windows_test.go
  vendor/k8s.io/kubernetes/pkg/util/mount/nsenter_mount.go
  vendor/k8s.io/kubernetes/pkg/util/mount/nsenter_mount_test.go
  vendor/k8s.io/kubernetes/pkg/util/mount/nsenter_mount_unsupported.go
  vendor/k8s.io/kubernetes/pkg/util/removeall/removeall_test.go
  vendor/k8s.io/kubernetes/pkg/volume/host_path/host_path_test.go
  vendor/k8s.io/kubernetes/pkg/volume/util/operationexecutor/operation_executor.go
  vendor/k8s.io/kubernetes/pkg/volume/util/operationexecutor/operation_executor_test.go
  vendor/k8s.io/kubernetes/pkg/volume/util/operationexecutor/operation_generator.go
  vendor/k8s.io/kubernetes/test/e2e/framework/util.go
  vendor/k8s.io/kubernetes/test/e2e/storage/BUILD
  vendor/k8s.io/kubernetes/test/e2e/storage/subpath.go
Labels: approved, lgtm, size/XXL, vendor-update

#18980 Add timestamps to bash log output
  hack/lib/log/output.sh
Labels: approved, lgtm, retest-not-required, size/S

#18985 UPSTREAM: 61193: bugfix(mount): lstat with abs path of parent instead of '/..'
  vendor/k8s.io/kubernetes/pkg/util/mount/mount_linux.go
Labels: approved, size/XS, vendor-update

#18954 [3.7] subpath/atomic writer fixes
  vendor/k8s.io/kubernetes/pkg/api/validation/validation.go
  vendor/k8s.io/kubernetes/pkg/api/validation/validation_test.go
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/pkg/kubelet/BUILD
  vendor/k8s.io/kubernetes/pkg/kubelet/cm/container_manager_linux_test.go
  vendor/k8s.io/kubernetes/pkg/kubelet/container/helpers.go
  vendor/k8s.io/kubernetes/pkg/kubelet/container/testing/fake_runtime_helper.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_pods.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_pods_test.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_container.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_container_test.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_manager_test.go
  vendor/k8s.io/kubernetes/pkg/kubelet/rkt/rkt.go
  vendor/k8s.io/kubernetes/pkg/kubelet/util/util_unsupported.go
  vendor/k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler/reconciler.go
  vendor/k8s.io/kubernetes/pkg/util/io/BUILD
  vendor/k8s.io/kubernetes/pkg/util/io/consistentread.go
  vendor/k8s.io/kubernetes/pkg/util/mount/BUILD
  vendor/k8s.io/kubernetes/pkg/util/mount/fake.go
  vendor/k8s.io/kubernetes/pkg/util/mount/mount.go
  vendor/k8s.io/kubernetes/pkg/util/mount/mount_linux.go
  vendor/k8s.io/kubernetes/pkg/util/mount/mount_linux_test.go
  vendor/k8s.io/kubernetes/pkg/util/mount/mount_unsupported.go
  vendor/k8s.io/kubernetes/pkg/util/mount/nsenter_mount.go
  vendor/k8s.io/kubernetes/pkg/util/mount/nsenter_mount_unsupported.go
  vendor/k8s.io/kubernetes/pkg/util/removeall/removeall_test.go
  vendor/k8s.io/kubernetes/pkg/volume/configmap/configmap.go
  vendor/k8s.io/kubernetes/pkg/volume/downwardapi/downwardapi.go
  vendor/k8s.io/kubernetes/pkg/volume/nfs/nfs.go
  vendor/k8s.io/kubernetes/pkg/volume/projected/projected.go
  vendor/k8s.io/kubernetes/pkg/volume/secret/secret.go
  vendor/k8s.io/kubernetes/pkg/volume/util/BUILD
  vendor/k8s.io/kubernetes/pkg/volume/util/nested_volumes.go
  vendor/k8s.io/kubernetes/pkg/volume/util/nested_volumes_test.go
  vendor/k8s.io/kubernetes/pkg/volume/util/operationexecutor/operation_executor.go
  vendor/k8s.io/kubernetes/pkg/volume/util/operationexecutor/operation_executor_test.go
  vendor/k8s.io/kubernetes/pkg/volume/util/operationexecutor/operation_generator.go
  vendor/k8s.io/kubernetes/test/e2e/common/downwardapi_volume.go
  vendor/k8s.io/kubernetes/test/e2e/common/projected.go
Labels: approved, size/XXL, vendor-update

#18951 remove the concept of tasks from cluster up and move installation log to start
  pkg/oc/bootstrap/docker/run_self_hosted.go
  pkg/oc/bootstrap/docker/up.go
Labels: approved, lgtm, size/L

#18978 Fix multicast test to run under ovs-networkpolicy plugin
  test/extended/networking/multicast.go
  test/extended/networking/util.go
Labels: approved, area/tests, component/networking, lgtm, sig/networking, size/M

#19000 Revert "Fix multicast test to run under ovs-networkpolicy plugin"
  test/extended/networking/multicast.go
  test/extended/networking/util.go
Labels: approved

#18995 Handle role binding AlreadyExists errors on project creation
  pkg/authorization/controller/defaultrolebindings/defaultrolebindings.go
  pkg/cmd/server/bootstrappolicy/project_policy.go
  pkg/project/registry/projectrequest/delegated/delegated.go
Labels: approved, kind/bug, lgtm, queue/fix, sig/master, size/M

#18758 Bug 1550266 - Fix clearInitialNodeNetworkUnavailableCondition() in sdn master
  pkg/network/master/subnets.go
Labels: approved, component/networking, kind/bug, lgtm, sig/networking, size/M

#18868 Wire in WebhookTokenAutenticators support
  pkg/cmd/server/apis/config/helpers.go
  pkg/cmd/server/apis/config/serialization_test.go
  pkg/cmd/server/apis/config/types.go
  pkg/cmd/server/apis/config/v1/conversions.go
  pkg/cmd/server/apis/config/v1/testdata/master-config.yaml
  pkg/cmd/server/apis/config/v1/types.go
  pkg/cmd/server/apis/config/v1/zz_generated.deepcopy.go
  pkg/cmd/server/apis/config/validation/master.go
  pkg/cmd/server/apis/config/validation/master_test.go
  pkg/cmd/server/apis/config/zz_generated.deepcopy.go
  pkg/cmd/server/kubernetes/master/master_config.go
  pkg/cmd/server/origin/authenticator.go
  pkg/user/registry/user/etcd/etcd.go
  test/integration/webhook_token_auth_test.go
Labels: api-approved, approved, lgtm, needs-api-review, size/L

#19006 Add networking team members to pkg/cmd/OWNERS
  pkg/cmd/OWNERS
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#18821 Enable router metrics preservation test
  test/extended/router/metrics.go
Labels: approved, lgtm, size/S

#19007 clarify where jenkins templates come from
  examples/jenkins/README.md
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#18708 Tests for delete job runs when associated builds are deleted
  test/extended/builds/pipeline.go
  test/extended/idling/idling.go
  test/extended/image_ecosystem/helper.go
  test/extended/image_ecosystem/mongodb_replica_statefulset.go
  test/extended/image_ecosystem/mysql_replica.go
  test/extended/image_ecosystem/postgresql_replica.go
  test/extended/util/endpoints.go
  test/extended/util/framework.go
  test/extended/util/nfs.go
  test/extended/util/pods.go
  test/extended/util/volumes.go
Labels: approved, lgtm, sig/developer-experience, size/XL

#18686 Perform real backoff when contending for writes from the router
  pkg/cmd/infra/router/f5.go
  pkg/cmd/infra/router/router.go
  pkg/cmd/infra/router/template.go
  pkg/router/controller/router_controller.go
  pkg/router/controller/status.go
  pkg/router/controller/status_test.go
  pkg/util/writerlease/writerlease.go
  pkg/util/writerlease/writerlease_test.go
  test/extended/router/stress.go
  test/extended/util/cli.go
  test/extended/util/framework.go
  test/extended/util/url/url.go
  test/extended/util/url/url_test.go
  test/integration/router_without_haproxy_test.go
Labels: approved, lgtm, sig/networking, size/XXL

#18998 Use existing network informers from openshift controller context in SDN master controller
  pkg/cmd/openshift-controller-manager/controller/interfaces.go
  pkg/cmd/openshift-controller-manager/controller/network_sdn.go
  pkg/cmd/openshift-controller-manager/controller_manager.go
  pkg/cmd/server/origin/informers.go
  pkg/cmd/server/origin/master_config.go
Labels: approved, lgtm, sig/networking, size/S

#17683 Limit Prometheus discovery to relevant namespaces
  examples/prometheus/prometheus.yaml
  pkg/oc/bootstrap/bindata.go
  test/extended/testdata/bindata.go
Labels: approved, lgtm, needs-ok-to-test, size/M

#19019 Wait longer for router stress test replicas to start
  test/extended/router/stress.go
Labels: approved, kind/test-flake, lgtm, size/S

#19020 Print correct router metrics output to test on failure
  test/extended/router/metrics.go
Labels: approved, kind/test-flake, lgtm, size/XS

#18939 bootstrap: minor cluster up fixes
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/oc/admin/registry/registry.go
  pkg/oc/bootstrap/clusterup/kubelet/flags.go
  pkg/oc/bootstrap/docker/dockerhelper/helper.go
  pkg/oc/bootstrap/docker/down.go
  pkg/oc/bootstrap/docker/errors/docker.go
  pkg/oc/bootstrap/docker/errors/errors.go
  pkg/oc/bootstrap/docker/openshift/admin.go
  pkg/oc/bootstrap/docker/openshift/errors.go
  pkg/oc/bootstrap/docker/openshift/helper.go
  pkg/oc/bootstrap/docker/openshift/logging.go
  pkg/oc/bootstrap/docker/openshift/metrics.go
  pkg/oc/bootstrap/docker/openshift/servicecatalog.go
  pkg/oc/bootstrap/docker/openshift/webconsole.go
  pkg/oc/bootstrap/docker/printer.go
  pkg/oc/bootstrap/docker/run/run.go
  pkg/oc/bootstrap/docker/status.go
  pkg/oc/bootstrap/docker/up.go
  pkg/oc/cli/cmd/cluster/cluster.go
Labels: approved, lgtm, size/L

#19014 Replace loop index with generation number in addImageStreamsToGraph()
  pkg/oc/admin/prune/imageprune/prune.go
Labels: approved, lgtm, size/XS

#18953 group services w same selectors in `oc status`
  pkg/oc/cli/describe/projectstatus.go
Labels: approved, lgtm, size/M

#18992 ignore wait4 errs in observe max-err-count
  pkg/oc/cli/cmd/observe/observe.go
Labels: approved, lgtm, size/S

#18999 Allow subnet allocator to mark assigned subnet dynamically
  pkg/network/master/master.go
  pkg/network/master/subnet_allocator.go
  pkg/network/master/subnet_allocator_test.go
  pkg/network/master/subnets.go
  pkg/util/netutils/common.go
  pkg/util/netutils/common_test.go
Labels: approved, lgtm, sig/networking, size/L

#18543 adds dependency analysis
  tools/depcheck/pkg/analyze/analyze.go
  tools/depcheck/pkg/cmd/analyze.go
  tools/depcheck/pkg/cmd/analyze_test.go
  tools/depcheck/pkg/cmd/cmd.go
Labels: approved, lgtm, size/L

#19018 Some route status updates were being lost
  pkg/util/writerlease/writerlease.go
  pkg/util/writerlease/writerlease_test.go
  test/extended/router/stress.go
Labels: approved, component/networking, component/routing, kind/test-flake, lgtm, sig/networking, size/L

#18425 UPSTREAM: 59301: dockershim: don't check pod IP in StopPodSandbox
  vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/docker_sandbox.go
  vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/docker_sandbox_test.go
Labels: approved, lgtm, size/M, vendor-update

#19043 Revert runc picks
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/apply_systemd.go
Labels: approved, kind/bug, lgtm, priority/critical-urgent, size/S, vendor-update

#19042 [3.7] Fix golang version check
  hack/lib/build/binaries.sh
  hack/lib/util/golang.sh
Labels: size/XS

#19008 allow for bypass of not proceeding deployment check jenkins extended tests given update center sync delay is now on startup
  test/extended/builds/contextdir.go
  test/extended/builds/gitauth.go
  test/extended/builds/new_app.go
  test/extended/builds/pipeline.go
  test/extended/cluster/cl.go
  test/extended/image_ecosystem/jenkins_plugin.go
  test/extended/image_ecosystem/mariadb_ephemeral.go
  test/extended/image_ecosystem/mongodb_ephemeral.go
  test/extended/image_ecosystem/mysql_ephemeral.go
  test/extended/image_ecosystem/mysql_replica.go
  test/extended/image_ecosystem/postgresql_replica.go
  test/extended/image_ecosystem/s2i_perl.go
  test/extended/image_ecosystem/s2i_php.go
  test/extended/image_ecosystem/s2i_python.go
  test/extended/image_ecosystem/s2i_ruby.go
  test/extended/image_ecosystem/sample_repos.go
  test/extended/util/framework.go
Labels: approved, lgtm, sig/developer-experience, size/M

#18727 upgrade prometheus v2.0.0 -> v2.1.0
  examples/prometheus/prometheus-standalone.yaml
  examples/prometheus/prometheus.yaml
  pkg/oc/bootstrap/bindata.go
  test/extended/testdata/bindata.go
Labels: approved, lgtm, size/XS

#19038 UPSTREAM: 59931: do not delete node in openstack, if those still exist in cloudprovider
  vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/openstack/openstack.go
  vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/openstack/openstack_instances.go
  vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
  vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/openstack/openstack_routes.go
  vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/openstack/openstack_volumes.go
Labels: approved, kind/bug, lgtm, size/S, vendor-update

#19005 Default the kubelet IPTablesMasqueradeBit to the same value as the kube-proxy IPTablesMasqueradeBit
  pkg/cmd/server/kubernetes/node/options/options.go
Labels: approved, lgtm, sig/pod, size/XS

#19032 pull in recent jenkins template, imagestream updates
  examples/image-streams/image-streams-centos7.json
  examples/image-streams/image-streams-rhel7.json
  examples/jenkins/jenkins-ephemeral-template.json
  examples/jenkins/jenkins-persistent-template.json
  pkg/oc/bootstrap/bindata.go
  test/extended/testdata/bindata.go
Labels: approved, lgtm, sig/developer-experience, size/L

#19054 turn off jenkins update center sync in extended tests, save cpu/mem, …
  test/extended/builds/pipeline.go
  test/extended/image_ecosystem/jenkins_plugin.go
Labels: approved, lgtm

#18964 Bug 1452162 - oc new-app eval ENV/ARG and ranges in dockerfile EXPOSE
  pkg/oc/generate/cmd/newapp_test.go
  pkg/util/docker/dockerfile/dockerfile.go
  pkg/util/docker/dockerfile/dockerfile_test.go
  pkg/util/docker/dockerfile/shell_parser.go
Labels: approved, component/cli, kind/bug, lgtm, sig/developer-experience, size/XL

#18905 rewire the routing suffix for oc cluster up
  pkg/oc/bootstrap/clusterup/kubeapiserver/openshift_apiserver.go
  pkg/oc/bootstrap/docker/openshift/logging.go
  pkg/oc/bootstrap/docker/openshift/metrics.go
  pkg/oc/bootstrap/docker/openshift/servicecatalog.go
  pkg/oc/bootstrap/docker/run_self_hosted.go
  pkg/oc/bootstrap/docker/up.go
Labels: approved, lgtm, sig/master, size/M

#18968 Add virtual resource for SAR checks
  examples/prometheus/prometheus.yaml
  pkg/oc/bootstrap/bindata.go
  test/extended/testdata/bindata.go
Labels: approved, lgtm, size/S

#19016 Clean up mirror and support quay.io pushing
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  hack/import-restrictions.json
  pkg/oc/cli/cmd/image/mirror/mirror.go
Labels: approved, lgtm, size/L

#19037 Drop image signature annotations
  pkg/image/controller/signature/container_image_downloader.go
  pkg/image/controller/signature/signature_import_controller.go
  pkg/image/registry/image/strategy.go
  pkg/image/registry/image/strategy_test.go
Labels: approved, lgtm, size/L

#19056 Prevent a race in writer lease tests
  pkg/util/writerlease/writerlease.go
  pkg/util/writerlease/writerlease_test.go
Labels: approved, kind/test-flake, lgtm, size/S

#19057 Add debug to find out why reencrypt routes are failing occasionally
  test/extended/router/reencrypt.go
Labels: approved, lgtm, size/S

#19033 Updates db replica extended tests to use nfs backed persistent volumes
  test/extended/builds/pipeline.go
  test/extended/image_ecosystem/mongodb_replica_statefulset.go
  test/extended/image_ecosystem/mysql_replica.go
  test/extended/image_ecosystem/postgresql_replica.go
  test/extended/util/deploymentconfigs.go
  test/extended/util/framework.go
  test/extended/util/nfs.go
  test/extended/util/pods.go
  test/extended/util/statefulsets.go
  test/extended/util/volumes.go
Labels: approved, lgtm, sig/developer-experience, size/XL

#19064 UPSTREAM: 61373: Fix subpath reconstruction
  vendor/k8s.io/kubernetes/pkg/kubelet/container/runtime.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_pods.go
  vendor/k8s.io/kubernetes/pkg/kubelet/volumemanager/volume_manager.go
  vendor/k8s.io/kubernetes/pkg/util/mount/mount_linux.go
  vendor/k8s.io/kubernetes/pkg/volume/util/operationexecutor/operation_generator.go
  vendor/k8s.io/kubernetes/test/e2e/storage/subpath.go
Labels: vendor-update

#18965 Check namespace when follow tag reference
  pkg/image/apis/image/helper.go
  pkg/image/apis/image/helper_test.go
Labels: approved, lgtm, size/S

#19065 http port should not be configured for ssl
  images/router/nginx/conf/nginx-config.template
Labels: approved, lgtm, size/XS

#19059 Pick build container for logs with istio auto-inject - fixes #18997
  pkg/build/controller/strategy/custom.go
  pkg/build/controller/strategy/custom_test.go
  pkg/build/controller/strategy/docker.go
  pkg/build/controller/strategy/docker_test.go
  pkg/build/controller/strategy/sti.go
  pkg/build/controller/strategy/sti_test.go
  pkg/build/controller/strategy/util.go
  pkg/build/registry/buildlog/rest.go
Labels: approved, component/logging, kind/bug, lgtm, sig/developer-experience, size/M

#19066 Enable async binding in service-catalog
  examples/OWNERS
  examples/service-catalog/service-catalog.yaml
  pkg/oc/bootstrap/bindata.go
Labels: approved, lgtm, size/XS

#18956 make registry installation a component
  pkg/oc/bootstrap/clusterup/components/registry/registry_install.go
  pkg/oc/bootstrap/docker/openshift/admin.go
  pkg/oc/bootstrap/docker/up.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/clientcmd/client_config.go
Labels: approved, lgtm, size/L, vendor-update

#19067 replaceing ginkgolog with e2e.Logf
  test/extended/image_ecosystem/jenkins_plugin.go
  test/extended/util/jenkins/monitor.go
  test/extended/util/jenkins/ref.go
Labels: approved, lgtm, sig/developer-experience, size/L

#18938 Remove --version from oc cluster up and replace it with hidden --tag flag
  CONTRIBUTING.adoc
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  docs/cluster_up_down.md
  hack/test-end-to-end-docker.sh
  pkg/oc/bootstrap/docker/up.go
  test/extended/clusterup.sh
Labels: approved, lgtm, size/M

#19075 Change remaining --version flags to --tag for oc cluster up calls
  test/extended/clusterup.sh
Labels: approved, lgtm, priority/failing-test, size/S

#19079 setup gateway by default for dind-ovn
  hack/dind-cluster.sh
  images/dind/node/ovn-kubernetes-node.sh
Labels: approved, lgtm, size/XS
