Repository openshift/origin, pull requests merged in 2018-02, with the labels that each got.

#18545 update oc in build local images
  hack/build-local-images.py
Labels: approved, lgtm, retest-not-required, size/XS

#18498 Parametrize local-storage template with image name
  examples/storage-examples/local-examples/README.md
  examples/storage-examples/local-examples/local-storage-provisioner-template.yaml
Labels: approved, lgtm, size/S

#18544 UPSTREAM: 59569: Do not ignore errors from EC2::DescribeVolume
  vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws.go
Labels: approved, lgtm, size/XS, vendor-update

#18479 do initialization steps for cluster up during initialization
  pkg/oc/bootstrap/docker/join.go
  pkg/oc/bootstrap/docker/up.go
Labels: approved, lgtm, size/L

#18547 Fix cleanup of auto egress IPs when deleting a NetNamespace
  pkg/network/node/egressip.go
  pkg/network/node/egressip_test.go
Labels: approved, component/networking, kind/bug, lgtm, sig/networking, size/M

#18549 cli: fix status for standalone deployment
  pkg/oc/cli/describe/projectstatus.go
  pkg/oc/graph/kubegraph/nodes/nodes.go
Labels: approved, lgtm, size/M

#18529 UPSTREAM: 58439: fix loading structured admission plugin config
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/admission/config.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/options/admission.go
Labels: approved, lgtm, size/S, vendor-update

#18214 Update web console template labels
  install/origin-web-console/OWNERS
  install/origin-web-console/console-template.yaml
  pkg/oc/bootstrap/bindata.go
  test/extended/testdata/bindata.go
Labels: approved, lgtm, size/S

#18383 remove-role-from-user outputs error when target was not found
  pkg/oc/admin/policy/modify_roles.go
  pkg/oc/admin/policy/remove_from_project.go
  test/cmd/admin.sh
  test/cmd/policy.sh
Labels: approved, lgtm, size/M

#18551 Make it clear deprecation apply also for later servers
  pkg/oc/admin/migrate/authorization/authorization.go
  pkg/oc/cli/cmd/create/policy_binding.go
Labels: approved, lgtm, size/XS

#17866 Never evict pods on dind nodes
  images/dind/node/openshift-generate-node-config.sh
Labels: approved, component/networking, lgtm, sig/networking, size/XS

#18518 fix the front proxy CA name
  pkg/cmd/server/admin/create_mastercerts.go
  pkg/cmd/server/admin/default_certs.go
Labels: approved, lgtm, size/S

#18554 UPSTREAM: 58177: Redesign and implement volume reconstruction work
  vendor/k8s.io/kubernetes/pkg/kubelet/config/config.go
  vendor/k8s.io/kubernetes/pkg/kubelet/volumemanager/cache/actual_state_of_world.go
  vendor/k8s.io/kubernetes/pkg/kubelet/volumemanager/cache/actual_state_of_world_test.go
  vendor/k8s.io/kubernetes/pkg/kubelet/volumemanager/cache/desired_state_of_world.go
  vendor/k8s.io/kubernetes/pkg/kubelet/volumemanager/cache/desired_state_of_world_test.go
  vendor/k8s.io/kubernetes/pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go
  vendor/k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler/reconciler.go
  vendor/k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler/reconciler_test.go
  vendor/k8s.io/kubernetes/pkg/util/mount/mount.go
  vendor/k8s.io/kubernetes/pkg/volume/util/operationexecutor/operation_executor.go
  vendor/k8s.io/kubernetes/pkg/volume/util/operationexecutor/operation_generator.go
Labels: approved, lgtm, size/L, vendor-update

#18534 Multiple template creation for Cluster Loader
  test/extended/cluster/cl.go
  test/extended/cluster/utils.go
Labels: approved, lgtm, size/M

#17759 Fix networking tests after 1.9 rebase
  test/extended/util/test.go
Labels: approved, lgtm, size/S

#18552 UPSTREAM: 59350: Do not recycle volumes that are used by pods
  vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/core.go
  vendor/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/BUILD
  vendor/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/binder_test.go
  vendor/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/delete_test.go
  vendor/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/framework_test.go
  vendor/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/provision_test.go
  vendor/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/pv_controller.go
  vendor/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/pv_controller_base.go
  vendor/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/recycle_test.go
  vendor/k8s.io/kubernetes/test/integration/scheduler/volume_binding_test.go
  vendor/k8s.io/kubernetes/test/integration/volume/persistent_volumes_test.go
Labels: approved, lgtm, size/L, vendor-update

#18570 Make image pruner tolerate since to empty docker image reference
  pkg/oc/admin/prune/imageprune/prune.go
Labels: approved, lgtm, size/S

#18561 JenkinsPipelineStrategy builds should not be pruned on BuildConfig save
  pkg/build/controller/common/util.go
Labels: approved, lgtm, sig/developer-experience, size/XS

#18514 UPSTREAM: 59506: fix watch on multiple reqs
  test/cmd/get.sh
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/resource/get.go
Labels: approved, lgtm, size/S, vendor-update

#18585 UPSTREAM: 59767: kubelet: check for illegal phase transition
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_pods.go
Labels: approved, kind/bug, lgtm, size/XS, vendor-update

#18559 Pull image stream changes back from ose/enterprise-3.7
  examples/image-streams/image-streams-centos7.json
  examples/image-streams/image-streams-rhel7.json
  pkg/oc/bootstrap/bindata.go
  test/extended/testdata/bindata.go
Labels: approved, lgtm, size/S

#18572 add publishing rules
  publishing-rules.yaml
Labels: approved, lgtm, size/M

#18237 UPSTREAM: 58685: Fill size attribute for the OpenStack V3 API volumes
  vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/openstack/openstack_volumes.go
Labels: approved, lgtm, size/XS, vendor-update

#18586 Replace loop index with generation number of istag
  pkg/oc/admin/prune/imageprune/prune.go
Labels: approved, lgtm, size/XS

#18578 return containerID from completed pod
  pkg/oc/bootstrap/docker/host/host.go
  pkg/oc/bootstrap/docker/openshift/cnetwork.go
  pkg/oc/bootstrap/docker/openshift/helper.go
  pkg/oc/bootstrap/docker/run/run.go
Labels: approved, lgtm, size/M

#18437 Bug 1538922 - Fix diagnostics for AggregatedLogging
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/oc/admin/diagnostics/cluster.go
  pkg/oc/admin/diagnostics/diagnostics/cluster/aggregated_logging/diagnostic.go
  pkg/oc/admin/diagnostics/diagnostics/cluster/aggregated_logging/kibana.go
Labels: approved, component/diagnostics, lgtm, size/L

#18546 make oadm router and registry resiliant to missing client
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/oc/admin/registry/registry.go
  pkg/oc/admin/router/router.go
Labels: approved, lgtm, size/L

#18550 Fix oc policy remove-user to remove rolebindings too
  pkg/oc/admin/policy/modify_roles.go
  pkg/oc/admin/policy/remove_from_project.go
  test/integration/policy_commands_test.go
Labels: approved, lgtm, size/S

#18579 Deployment updates in status graph
  pkg/oc/cli/describe/projectstatus.go
  pkg/oc/graph/kubegraph/nodes/nodes.go
  pkg/oc/graph/kubegraph/nodes/types.go
Labels: approved, lgtm, size/S

#18576 complete the cluster up struct in the Complete method
  pkg/oc/bootstrap/docker/up.go
Labels: approved, lgtm, size/L

#18553 CRO admission plugin: never mutate below namespace minimums
  pkg/quota/admission/clusterresourceoverride/admission.go
  pkg/quota/admission/clusterresourceoverride/admission_test.go
  test/integration/clusterresourceoverride_admission_test.go
Labels: approved, lgtm, size/L

#18592 move pkg/build/{prune,cmd} into pkg/oc/cli/builds
  hack/import-restrictions.json
  pkg/oc/admin/prune/builds.go
  pkg/oc/cli/builds/OWNERS
  pkg/oc/cli/builds/doc.go
  pkg/oc/cli/builds/prune/data.go
  pkg/oc/cli/builds/prune/data_test.go
  pkg/oc/cli/builds/prune/prune.go
  pkg/oc/cli/builds/prune/prune_test.go
  pkg/oc/cli/builds/prune/resolvers.go
  pkg/oc/cli/builds/prune/resolvers_test.go
  pkg/oc/cli/builds/reaper.go
  pkg/oc/cli/builds/reaper_test.go
  pkg/oc/cli/util/clientcmd/factory_object_mapping.go
Labels: approved, lgtm, size/S

#18524 [3.7] Backport dc trigger reconciliation on image change release
  pkg/apps/controller/deployer/deployer_controller.go
  pkg/apps/controller/deployer/deployer_controller_test.go
  pkg/apps/controller/deploymentconfig/deploymentconfig_controller.go
  pkg/apps/controller/deploymentconfig/deploymentconfig_controller_test.go
  pkg/image/trigger/deploymentconfigs/deploymentconfigs.go
  test/extended/deployments/deployments.go
  test/extended/deployments/util.go
  test/extended/testdata/bindata.go
  test/extended/testdata/deployments/deployment-trigger.yaml
Labels: approved, lgtm, size/XXL

#18508 use the upstream SA token controller
  pkg/cmd/server/origin/controller/config.go
  pkg/cmd/server/origin/controller/serviceaccount.go
  pkg/cmd/server/start/start_kube_controller_manager.go
  pkg/cmd/server/start/start_master.go
  test/util/server/server.go
  vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go
  vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/patch.go
  vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/patch_satoken.go
Labels: approved, lgtm, size/L, vendor-update

#18598 fix typo in HACKING.md
  HACKING.md
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#18597 add registry.centos.org to default whitelist
  pkg/cmd/server/apis/config/types.go
Labels: approved, lgtm, needs-api-review, size/XS

#18348 Add .NET Core CentOS ImageStreams
  examples/image-streams/image-streams-centos7.json
  pkg/oc/bootstrap/bindata.go
  test/extended/testdata/bindata.go
Labels: approved, lgtm, size/L

#18602 Add tests for remove-user with a rolebinding name
  test/cmd/policy.sh
Labels: approved, lgtm, size/S

#18505 Enable osin internal error logging
  glide.lock
  glide.yaml
  pkg/oauthserver/osinserver/osinserver.go
  vendor/github.com/RangelReale/osin/access.go
  vendor/github.com/RangelReale/osin/access_test.go
  vendor/github.com/RangelReale/osin/authorize.go
  vendor/github.com/RangelReale/osin/authorize_test.go
  vendor/github.com/RangelReale/osin/info.go
  vendor/github.com/RangelReale/osin/log.go
  vendor/github.com/RangelReale/osin/log_test.go
  vendor/github.com/RangelReale/osin/server.go
  vendor/github.com/RangelReale/osin/util.go
  vendor/github.com/RangelReale/osin/util_test.go
  vendor/k8s.io/kubernetes/origin.sha
Labels: approved, lgtm, sig/security, size/L, vendor-update

#18604 stop scheduler from advancing through empty buckets without accept from ratelimiter
  pkg/image/controller/factory.go
  pkg/image/controller/scheduled_image_controller.go
  pkg/image/controller/scheduled_image_controller_test.go
  pkg/image/controller/scheduler.go
  pkg/image/controller/scheduler_test.go
Labels: approved, lgtm, size/L

#18624 allow a panic to crash the server after a delay
  pkg/cmd/util/serviceability/panic.go
  pkg/cmd/util/serviceability/panic_test.go
Labels: approved, lgtm, sig/master, size/M

#18605 Revert "Admission plugin: openshift.io/ImageQualify"
  contrib/migration/unqualified-images.sh
  hack/update-generated-deep-copies.sh
  pkg/cmd/server/apis/config/install/install.go
  pkg/cmd/server/origin/admission/chain_builder.go
  pkg/cmd/server/origin/admission/register.go
  pkg/image/admission/apis/imagequalify/doc.go
  pkg/image/admission/apis/imagequalify/install/install.go
  pkg/image/admission/apis/imagequalify/name.go
  pkg/image/admission/apis/imagequalify/register.go
  pkg/image/admission/apis/imagequalify/types.go
  pkg/image/admission/apis/imagequalify/v1/doc.go
  pkg/image/admission/apis/imagequalify/v1/register.go
  pkg/image/admission/apis/imagequalify/v1/types.go
  pkg/image/admission/apis/imagequalify/v1/zz_generated.deepcopy.go
  pkg/image/admission/apis/imagequalify/validation/domain.go
  pkg/image/admission/apis/imagequalify/validation/domain_test.go
  pkg/image/admission/apis/imagequalify/validation/image.go
  pkg/image/admission/apis/imagequalify/validation/image_test.go
  pkg/image/admission/apis/imagequalify/validation/validation.go
  pkg/image/admission/apis/imagequalify/validation/validation_test.go
  pkg/image/admission/apis/imagequalify/zz_generated.deepcopy.go
  pkg/image/admission/imagequalify/admission.go
  pkg/image/admission/imagequalify/admission_test.go
  pkg/image/admission/imagequalify/config.go
  pkg/image/admission/imagequalify/config_test.go
  pkg/image/admission/imagequalify/doc.go
  pkg/image/admission/imagequalify/export_test.go
  pkg/image/admission/imagequalify/pattern.go
  pkg/image/admission/imagequalify/pattern_test.go
  pkg/image/admission/imagequalify/qualify.go
  pkg/image/admission/imagequalify/qualify_test.go
  pkg/image/admission/imagequalify/sort.go
  pkg/image/admission/imagequalify/sort_test.go
  test/integration/imagequalify_admission_test.go
Labels: approved, lgtm, needs-api-review, size/XXL

#18353 Grafna deployment update.
  examples/grafana/README.md
  examples/grafana/setup-grafana.sh
Labels: approved, area/examples, component/metrics, lgtm, retest-not-required-docs-only, size/M

#18563 Fix invalid SuggestFor for oc image
  pkg/oc/cli/cmd/importimage.go
  pkg/oc/cli/cmd/wrappers.go
Labels: approved, lgtm, size/S

#18622 use the normal loopback connection for loopback to the apiserver
  pkg/cmd/server/kubernetes/master/master_config.go
  pkg/cmd/server/origin/master_config.go
  tools/testdebug/cmd/load_etcd.go
Labels: approved, lgtm, size/S

#18608 Allow passing -gcflags during build
  Makefile
  hack/lib/build/binaries.sh
Labels: approved, lgtm, size/XS

#17546 [release-3.7] setup selinux labels for build containers
  pkg/build/builder/docker.go
  pkg/build/builder/sti.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_logs.go
Labels: approved, lgtm, size/M, vendor-update

#18487 Preserve namespace on imagestreams server-side export
  pkg/image/registry/imagestream/strategy.go
  pkg/image/registry/imagestream/strategy_test.go
Labels: approved, lgtm, size/S

#18537 make TSB conformant with respect to multiple parallel operations
  pkg/templateservicebroker/openservicebroker/api/types.go
  pkg/templateservicebroker/openservicebroker/server/route_test.go
  pkg/templateservicebroker/servicebroker/bind.go
  pkg/templateservicebroker/servicebroker/bind_test.go
  pkg/templateservicebroker/servicebroker/provision.go
  pkg/templateservicebroker/servicebroker/provision_test.go
  pkg/templateservicebroker/servicebroker/unbind.go
  pkg/templateservicebroker/servicebroker/unbind_test.go
Labels: approved, lgtm, needs-api-review, size/L

#18630 Revert "Allow insecure path Allow routes to override Redirect routes …
  images/router/haproxy/Dockerfile
  images/router/haproxy/conf/haproxy-config.template
Labels: approved, lgtm, size/M

#18482 automatically remove hostsubnets with no nodes on startup
  pkg/network/apis/network/plugin.go
  pkg/network/master/subnets.go
Labels: approved, component/networking, lgtm, size/M

#18620 Change rejected routes error message to verbose logging
  pkg/router/controller/host_admitter.go
Labels: approved, component/networking, lgtm, sig/networking, size/XS

#18636 Picks for volume manager
  vendor/k8s.io/kubernetes/pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go
  vendor/k8s.io/kubernetes/pkg/kubelet/volumemanager/populator/desired_state_of_world_populator_test.go
  vendor/k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler/reconciler.go
  vendor/k8s.io/kubernetes/pkg/kubelet/volumemanager/volume_manager.go
  vendor/k8s.io/kubernetes/pkg/volume/util/operationexecutor/operation_executor.go
  vendor/k8s.io/kubernetes/pkg/volume/util/operationexecutor/operation_generator.go
Labels: approved, kind/bug, lgtm, size/M, vendor-update

#18639 add publishing rules for openshift/kubernetes repo
  publishing-kube-rules.yaml
Labels: approved, lgtm, size/M

#18629 auto-panic and become unhealthy on too many grpc connections
  pkg/cmd/server/origin/health_grpc.go
  pkg/cmd/server/origin/healthy_gprc_test.go
  pkg/cmd/server/origin/master.go
Labels: approved, lgtm, sig/master, size/L

#18619 Bld reason count all phases
  pkg/build/apis/build/types.go
  pkg/build/metrics/prometheus/metrics.go
  pkg/build/metrics/prometheus/metrics_test.go
  test/extended/prometheus/prometheus_builds.go
  test/integration/metrics_test.go
Labels: api-approved, approved, lgtm, needs-api-review, sig/developer-experience, size/L

#16658 AppCreate diagnostic
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  docs/man/man1/.files_generated_oc
  docs/man/man1/oc-adm-diagnostics-appcreate.1
  docs/man/man1/oc-ex-diagnostics-appcreate.1
  pkg/oc/admin/diagnostics/cluster.go
  pkg/oc/admin/diagnostics/diagnostics.go
  pkg/oc/admin/diagnostics/diagnostics/cluster/app_create/app.go
  pkg/oc/admin/diagnostics/diagnostics/cluster/app_create/main.go
  pkg/oc/admin/diagnostics/diagnostics/cluster/app_create/result.go
  pkg/oc/admin/diagnostics/diagnostics/cluster/app_create/route.go
  pkg/oc/admin/diagnostics/diagnostics/cluster/app_create/service.go
  pkg/oc/admin/diagnostics/diagnostics/cluster/app_create/setup_cleanup.go
  pkg/oc/admin/diagnostics/diagnostics/cluster/master_node.go
  pkg/oc/admin/diagnostics/diagnostics/cluster/node_definitions.go
  pkg/oc/admin/diagnostics/diagnostics/cluster/registry.go
  pkg/oc/admin/diagnostics/diagnostics/cluster/rolebindings.go
  pkg/oc/admin/diagnostics/diagnostics/cluster/roles.go
  pkg/oc/admin/diagnostics/diagnostics/cluster/route_validation.go
  pkg/oc/admin/diagnostics/diagnostics/cluster/router.go
  pkg/oc/admin/diagnostics/diagnostics/cluster/util.go
  pkg/oc/admin/diagnostics/diagnostics/util/util.go
  pkg/oc/admin/project/new_project.go
Labels: approved, lgtm, size/XXL

#18643 Fix periodic reconciliation for DCs
  pkg/apps/controller/deployer/factory.go
  pkg/apps/controller/deploymentconfig/factory.go
Labels: approved, kind/bug, lgtm, priority/P1, size/S

#18647 Update custom tito tagger for new version
  .tito/lib/origin/tagger/__init__.py
Labels: approved, lgtm, size/XS

#18631 --source-image should count as a source input
  pkg/oc/generate/cmd/resolve.go
  test/cmd/newapp.sh
Labels: approved, lgtm, sig/developer-experience, size/M

#18613 add an admission decorator that allows skipping some admission checks…
  pkg/admission/namespaceconditions/decorator.go
  pkg/admission/namespaceconditions/labelcondition.go
  pkg/admission/namespaceconditions/labelcondition_test.go
  pkg/cmd/server/origin/admission/chain_builder.go
  pkg/cmd/server/origin/admission/config_test.go
  pkg/cmd/server/origin/master_config.go
Labels: approved, lgtm, sig/master, size/L

#18530 UPSTREAM: 58375: Recheck if transformed data is stale when doing live lookup during update
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/storage/etcd3/store.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/storage/etcd3/store_test.go
Labels: approved, lgtm, size/M, vendor-update

#18661 restore qps and burst for scheduler and kbue-controller-manager
  pkg/cmd/server/start/start_kube_controller_manager.go
  pkg/cmd/server/start/start_kube_scheduler.go
  pkg/cmd/server/start/start_master.go
Labels: approved, lgtm, queue/critical-fix, sig/master, size/M

#18662 masterPublicURL must be both internally and externally accessible
  pkg/cmd/server/apis/config/v1/swagger_doc.go
  pkg/cmd/server/apis/config/v1/types.go
Labels: api-approved, approved, lgtm, needs-api-review, retest-not-required-docs-only, size/XS

#18623 Added dcbw to pkg/cmd/OWNERS
  pkg/cmd/OWNERS
Labels: retest-not-required-docs-only, size/XS

#18646 Store pod IP in OVS external-ids and use that on teardown
  pkg/network/node/ovscontroller.go
  pkg/util/ovs/fake_ovs.go
  pkg/util/ovs/ovs.go
  pkg/util/ovs/parse.go
  pkg/util/ovs/parse_test.go
Labels: approved, component/networking, kind/bug, lgtm, sig/networking, size/L

#17146 Fix BuildConfigInstantiateFailed warning when lastVersion == 0
  pkg/build/controller/buildconfig/buildconfig_controller.go
  pkg/build/generator/generator.go
  test/cmd/newapp.sh
Labels: approved, lgtm, sig/developer-experience, size/S

#18676 Fix panic in error printing in DC controller
  pkg/apps/controller/deploymentconfig/deploymentconfig_controller.go
Labels: approved, kind/bug, lgtm, size/XS

#18453 upgrade prometheus alertmanager v0.9.1 -> v0.13.0
  examples/prometheus/prometheus-standalone.yaml
  examples/prometheus/prometheus.yaml
  pkg/oc/bootstrap/bindata.go
  test/extended/testdata/bindata.go
Labels: approved, lgtm, size/S

#18404 SDN options and CNI directory cleanup
  pkg/cmd/server/kubernetes/network/sdn_linux.go
  pkg/cmd/server/kubernetes/node/options/options.go
  pkg/network/node/metrics.go
  pkg/network/node/node.go
  pkg/network/node/pod.go
Labels: approved, component/networking, kind/bug, lgtm, size/M

#18405 Correctly handle newlines in serial files
  pkg/cmd/server/crypto/crypto.go
  test/cmd/certs.sh
Labels: approved, kind/bug, lgtm, sig/security, size/M

#18692 The prometheus e2e isn't checking for its pods correctly
  test/extended/prometheus/prometheus.go
Labels: approved, lgtm, size/XS

#18654 [Diagnostics] Fix AnalyzeLogs to provide more clear debug message
  pkg/oc/admin/diagnostics/diagnostics/cluster/master_node.go
  pkg/oc/admin/diagnostics/diagnostics/systemd/analyze_logs.go
  pkg/oc/admin/diagnostics/diagnostics/systemd/locate_units.go
Labels: approved, lgtm, size/S

#18700 Add a containerized node script for bootstrap equivalent
  images/node/scripts/openshift-node
Labels: approved, lgtm, retest-not-required, size/S

#18688 Fixes index out of range error on oc new-app --template foo
  pkg/oc/cli/cmd/newapp.go
  test/cmd/newapp.sh
Labels: approved, lgtm, sig/developer-experience, size/XS

#18707 Fixes new-app segmentation fault on invalid build strategy
  pkg/build/util/util.go
  test/cmd/newapp.sh
  test/testdata/invalid-build-strategy.yaml
Labels: approved, lgtm, sig/developer-experience, size/S

#18711 Fix govet error - formatting in glog.V(0).Info() call
  pkg/image/apis/image/validation/whitelist/whitelister.go
Labels: approved, lgtm, retest-not-required, size/XS

#18697 Limit logging to provider name
  pkg/oauthserver/oauth/external/handler.go
Labels: approved, lgtm, sig/security, size/XS

#18706 Surpress project list on login if you have access to greater than 50 projects
  pkg/oc/cli/cmd/login/loginoptions.go
Labels: approved, lgtm, size/S

#18625 add more graph methods
  tools/depcheck/pkg/cmd/cmd.go
  tools/depcheck/pkg/graph/filter.go
  tools/depcheck/pkg/graph/filter_test.go
  tools/depcheck/pkg/graph/graph.go
  tools/depcheck/pkg/graph/graph_test.go
  tools/depcheck/pkg/graph/pkg.go
  tools/depcheck/pkg/graph/pkg_test.go
Labels: approved, lgtm, size/L

#18704 Add enj to generated man page OWNERS
  docs/man/OWNERS
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#17565 Add networking team members to OWNERS file
  pkg/cmd/server/kubernetes/network/OWNERS
Labels: approved, lgtm, retest-not-required-docs-only, size/S

#18720 Fix reassignment of egress IP after removal
  pkg/network/node/egressip.go
  pkg/network/node/egressip_test.go
Labels: approved, component/networking, kind/bug, lgtm, sig/networking, size/M

#18713 Guarantee that SerialFileGenerator starts at 2
  pkg/cmd/server/crypto/crypto.go
  test/cmd/certs.sh
Labels: approved, kind/bug, lgtm, queue/critical-fix, sig/security, size/M

#18733 Skip managed images when importing signatures
  pkg/image/controller/signature/signature_import_controller.go
Labels: approved, lgtm, size/XS

#18687 Bug 1547284 - Do not allow 'default' project to be isolated using 'oc adm pod-network'
  pkg/network/common/dns.go
  pkg/network/master/subnets.go
  pkg/network/master/vnids.go
  pkg/network/node/runtime.go
  pkg/oc/admin/network/isolate_projects.go
  pkg/oc/admin/network/join_projects.go
  pkg/oc/admin/network/make_projects_global.go
  pkg/oc/admin/network/project_options.go
Labels: approved, component/networking, kind/bug, lgtm, sig/networking, size/M

#18685 add configmap volume description
  pkg/oc/cli/cmd/set/volume.go
  test/cmd/volumes.sh
Labels: approved, lgtm, size/S

#18634 Correctly flush stale ovs rules on Node startup
  pkg/network/node/ovscontroller.go
  pkg/util/ovs/fake_ovs.go
  pkg/util/ovs/ovs.go
Labels: approved, component/networking, lgtm, size/S

#18736 relax aggressive timeouts in declarative pipeline example
  examples/jenkins/pipeline/nodejs-sample-pipeline.yaml
  pkg/oc/bootstrap/bindata.go
  test/extended/testdata/bindata.go
Labels: approved, lgtm, sig/developer-experience, size/M

#18531 UPSTREAM: 58375: Recheck if transformed data is stale when doing live lookup during update
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/storage/etcd3/store.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/storage/etcd3/store_test.go
Labels: approved, lgtm, size/M, vendor-update

#18703 Bld metrics path to alerts part 2
  examples/prometheus/README.md
  pkg/build/metrics/prometheus/metrics.go
  pkg/build/metrics/prometheus/metrics_test.go
Labels: approved, lgtm, sig/developer-experience, size/M

#18737 dind: switch images to Fedora 27
  images/dind/Dockerfile
  images/dind/Dockerfile.centos7
  images/dind/node/Dockerfile
Labels: approved, lgtm, size/L

#18418 Minor cleanups to sdn-cni-plugin
  pkg/network/node/cniserver/cniserver.go
  pkg/network/node/cniserver/cniserver_test.go
  pkg/network/sdn-cni-plugin/openshift-sdn.go
Labels: approved, component/networking, lgtm, sig/networking, size/M

#18475 UPSTREAM: 59386: Scheduler - not able to read from config file if configmap not found
  vendor/k8s.io/kubernetes/plugin/cmd/kube-scheduler/app/server.go
Labels: approved, lgtm, size/XS, vendor-update

#18723 tags existing deployment nodes as "found"
  pkg/oc/cli/describe/projectstatus.go
  pkg/oc/cli/describe/projectstatus_test.go
  pkg/oc/graph/genericgraph/graphview/daemonset.go
  pkg/oc/graph/genericgraph/test/hpa-with-scale-ref.yaml
  pkg/oc/graph/genericgraph/test/rollingupdate-daemonset.yaml
  pkg/oc/graph/kubegraph/edges.go
  pkg/oc/graph/kubegraph/nodes/nodes.go
Labels: approved, lgtm, size/L

#17342 update nginx-config.template
  images/router/nginx/conf/nginx-config.template
Labels: approved, lgtm, needs-ok-to-test, size/M

#18760 UPSTREAM: 60301: Fix Deployment with Recreate strategy not to wait on pods in terminal phase
  vendor/k8s.io/kubernetes/pkg/controller/deployment/recreate.go
  vendor/k8s.io/kubernetes/pkg/controller/deployment/recreate_test.go
Labels: approved, kind/delivery-blocker, lgtm, queue/critical-fix, sig/master, size/L, vendor-update

#18755 UPSTREAM: 60457: tests: e2e: empty msg from channel other than stdout should be non-fatal
  vendor/k8s.io/kubernetes/test/e2e/common/pods.go
Labels: approved, lgtm, size/XS, vendor-update

#18764 Workaround for #18762
  test/end-to-end/core.sh
Labels: approved, lgtm, priority/critical-urgent, retest-not-required, size/S

#18754 kube-proxy iptables performance fixes
  vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go
  vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier_test.go
Labels: approved, component/networking, lgtm, sig/networking, size/L, vendor-update

#18761 apps: stop dc cancellation flake
  test/extended/deployments/deployments.go
Labels: approved, lgtm, size/XS

#18779 sdn: fix CNI IPAM data dir
  pkg/network/node/metrics.go
  pkg/network/node/node.go
Labels: approved, component/networking, lgtm, size/XS
