Repository openshift/origin, pull requests merged in 2018-10, with the labels that each got.

#21080 Bug 1632155 - Accept logFormat when passed to audit config
  pkg/cmd/openshift-apiserver/openshiftapiserver/configprocessing/audit.go
Labels: approved, lgtm, size/XS

#21136 Remove Simo Sorce from OWNERS
  images/openldap/OWNERS
  pkg/apiserver/authentication/OWNERS
  pkg/authorization/OWNERS
  pkg/cmd/OWNERS
  pkg/oauth/OWNERS
  pkg/oauthserver/OWNERS
  pkg/security/OWNERS
  pkg/serviceaccounts/OWNERS
  pkg/user/OWNERS
  test/OWNERS
  test/testdata/OWNERS
Labels: approved, lgtm, retest-not-required, size/S

#20959 UPSTREAM: 68023: Replace git volume with configmap in emptydir wrapper conflict test
  vendor/k8s.io/kubernetes/test/e2e/storage/empty_dir_wrapper.go
Labels: approved, lgtm, sig/storage, size/M

#21077 UPSTREAM: 68980: kubelet should not create pod sandbox
  vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_manager.go
Labels: approved, lgtm, size/XS

#21143 UPSTREAM: 69300: test: Wait for pod event to show up
  vendor/k8s.io/kubernetes/test/e2e/framework/util.go
  vendor/k8s.io/kubernetes/test/e2e/storage/subpath.go
Labels: approved, lgtm, size/M

#21146 cluster-up: add locks for controller manager
  pkg/oc/clusterup/coreinstall/controlplane-operator/run_render.go
  pkg/oc/clusterup/docker/util/client.go
  pkg/oc/clusterup/docker/util/helper.go
  pkg/oc/clusterup/required_images.go
  pkg/oc/clusterup/run_self_hosted.go
  pkg/oc/clusterup/up.go
Labels: approved, lgtm, size/L

#21151 use common storage for image extraction in docker builds
  pkg/build/controller/strategy/docker.go
  pkg/build/controller/strategy/sti.go
Labels: approved, lgtm, retest-not-required, size/XS

#21150 switch kube-apiserver port to 6443
  pkg/cmd/openshift-kube-apiserver/configdefault/kubecontrolplane_default.go
  pkg/oc/clusterup/coreinstall/assets/render.go
  pkg/oc/clusterup/docker/openshift/helper.go
  pkg/oc/clusterup/docker/openshift/helper_unix.go
  pkg/oc/clusterup/run_self_hosted.go
  pkg/oc/clusterup/up.go
Labels: approved, lgtm, size/S

#21159 remove unnecessary force pull in test
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/test-imagesource-buildconfig.yaml
Labels: approved, lgtm, size/XS

#21152 make oc logs function
  pkg/oc/clusterup/coreinstall/assets/apiserver.go
  pkg/oc/clusterup/coreinstall/assets/render.go
Labels: approved, lgtm, size/XS

#21141 Remove reconcile-cluster-roles and reconcile-cluster-role-bindings
  hack/import-restrictions.json
  hack/test-cmd.sh
  pkg/cmd/server/bootstrappolicy/policy.go
  pkg/network/node/networkpolicy.go
  pkg/oc/cli/admin/policy/policy.go
  pkg/oc/cli/admin/policy/reconcile_clusterrolebindings.go
  pkg/oc/cli/admin/policy/reconcile_clusterrolebindings_test.go
  pkg/oc/cli/admin/policy/reconcile_clusterroles.go
  pkg/oc/cli/admin/policy/reconcile_clusterroles_test.go
  pkg/oc/cli/admin/policy/reconcile_sccs.go
  test/cmd/admin.sh
  test/cmd/policy.sh
Labels: approved, lgtm, sig/security, size/XXL

#21175 switch to using upstream reconcile for all RBAC resources
  pkg/cmd/server/bootstrappolicy/all.go
  pkg/cmd/server/bootstrappolicy/all_test.go
  pkg/cmd/server/bootstrappolicy/policy.go
  pkg/cmd/server/bootstrappolicy/policy_test.go
  pkg/cmd/server/bootstrappolicy/web_console_role_test.go
  test/testdata/bootstrappolicy/bootstrap_cluster_role_bindings.yaml
  test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml
  test/testdata/bootstrappolicy/bootstrap_namespace_role_bindings.yaml
  test/testdata/bootstrappolicy/bootstrap_namespace_roles.yaml
  test/testdata/bootstrappolicy/bootstrap_policy_file.yaml
Labels: approved, lgtm, size/XXL

#21164 Infra nodes shouldn't be cordoned in conformance-k8s
  test/extended/conformance-k8s.sh
Labels: approved, size/XS

#21165 Disable a local storage serial test
  test/extended/util/test.go
Labels: approved, lgtm, size/XS

#21166 do not mount host certificates into build pod
  pkg/build/controller/strategy/custom.go
  pkg/build/controller/strategy/custom_test.go
  pkg/build/controller/strategy/docker.go
  pkg/build/controller/strategy/docker_test.go
  pkg/build/controller/strategy/sti.go
  pkg/build/controller/strategy/sti_test.go
Labels: approved, lgtm, retest-not-required, size/M

#21149 Drop pkg/cmd/util/print
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  hack/import-restrictions.json
  pkg/cmd/util/print/print.go
  pkg/oc/cli/admin/router/router.go
  pkg/oc/cli/newapp/newapp.go
Labels: approved, lgtm, size/XL

#21134 update-external-examples to include .NET Core 2.1
  examples/db-templates/mariadb-ephemeral-template.json
  examples/db-templates/mariadb-persistent-template.json
  examples/db-templates/mongodb-ephemeral-template.json
  examples/db-templates/mongodb-persistent-template.json
  examples/db-templates/mysql-ephemeral-template.json
  examples/db-templates/mysql-persistent-template.json
  examples/db-templates/postgresql-ephemeral-template.json
  examples/db-templates/postgresql-persistent-template.json
  examples/image-streams/image-streams-centos7.json
  examples/image-streams/image-streams-rhel7.json
  examples/jenkins/jenkins-ephemeral-template.json
  examples/jenkins/jenkins-persistent-template.json
  examples/quickstarts/cakephp-mysql-persistent.json
  examples/quickstarts/cakephp-mysql.json
  examples/quickstarts/dancer-mysql-persistent.json
  examples/quickstarts/dancer-mysql.json
  examples/quickstarts/django-postgresql-persistent.json
  examples/quickstarts/django-postgresql.json
  examples/quickstarts/httpd.json
  examples/quickstarts/nodejs-mongodb-persistent.json
  examples/quickstarts/nodejs-mongodb.json
  examples/quickstarts/rails-postgresql-persistent.json
  examples/quickstarts/rails-postgresql.json
  pkg/oc/clusterup/manifests/bindata.go
  test/cmd/debug.sh
  test/cmd/images.sh
  test/cmd/newapp.sh
  test/extended/testdata/bindata.go
Labels: approved, lgtm, size/XL

#21178 disable remaining git auth test
  test/extended/builds/gitauth.go
Labels: approved, lgtm, retest-not-required, size/L

#21186 Wire missing set commands
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/oc/cli/set/set.go
Labels: approved, lgtm, size/XL

#21167 fix projects when watching with selector
  pkg/project/apiserver/registry/project/proxy/proxy.go
  pkg/project/auth/watch.go
  pkg/project/auth/watch_test.go
  pkg/project/util/util.go
  test/integration/project_test.go
Labels: approved, lgtm, sig/security, size/L

#21184 remove networking apiserver from hypershift openshift-apiserver
  pkg/cmd/openshift-apiserver/cmd.go
  pkg/cmd/openshift-apiserver/openshiftapiserver/openshift_apiserver.go
  pkg/cmd/openshift-apiserver/server.go
  pkg/cmd/server/origin/master.go
Labels: approved, lgtm, sig/networking, size/S

#21189 increase timeouts because tests on gcp run slow
  test/extended/builds/contextdir.go
  test/extended/builds/image_source.go
Labels: approved, lgtm, retest-not-required, size/S

#21183 use namespace labels to prevent SCC usage
  test/extended/util/test.go
Labels: approved, lgtm, size/M

#21179 UPSTREAM: 68563 : fix scheduler crash when Prioritize Map function failed
  vendor/k8s.io/kubernetes/pkg/scheduler/core/generic_scheduler.go
  vendor/k8s.io/kubernetes/pkg/scheduler/core/generic_scheduler_test.go
Labels: approved, lgtm, size/M

#21162 Upd jenkins samples old plugin
  examples/jenkins/pipeline/README.md
  examples/jenkins/pipeline/bluegreen-pipeline.yaml
  examples/jenkins/pipeline/mapsapp-pipeline.yaml
  examples/jenkins/pipeline/maven-pipeline.yaml
  examples/jenkins/pipeline/samplepipeline.yaml
  pkg/oc/clusterup/manifests/bindata.go
  test/extended/testdata/bindata.go
Labels: approved, lgtm, sig/developer-experience, size/L

#21182 cluster-up: no --manifest-lock-host-path for controller manager
  pkg/oc/clusterup/coreinstall/controlplane-operator/run_render.go
  pkg/oc/clusterup/run_self_hosted.go
Labels: approved, lgtm, size/S

#21198 cluster-up: add scheduler operator
  pkg/oc/clusterup/required_images.go
  pkg/oc/clusterup/run_self_hosted.go
  test/extended/clusterup.sh
Labels: approved, lgtm, size/S

#19103 add rsync include,exclude support
  pkg/oc/cli/rsync/copytar.go
  pkg/oc/cli/rsync/util.go
  test/cmd/rsync.sh
Labels: approved, lgtm, size/L

#21197 4.0: iSCSI multipath issues
  vendor/k8s.io/kubernetes/pkg/volume/iscsi/BUILD
  vendor/k8s.io/kubernetes/pkg/volume/iscsi/attacher.go
  vendor/k8s.io/kubernetes/pkg/volume/iscsi/iscsi.go
  vendor/k8s.io/kubernetes/pkg/volume/iscsi/iscsi_util.go
  vendor/k8s.io/kubernetes/pkg/volume/util/device_util.go
  vendor/k8s.io/kubernetes/pkg/volume/util/device_util_linux.go
  vendor/k8s.io/kubernetes/pkg/volume/util/device_util_linux_test.go
  vendor/k8s.io/kubernetes/pkg/volume/util/device_util_unsupported.go
  vendor/k8s.io/kubernetes/pkg/volume/util/io_util.go
Labels: approved, lgtm, size/XL

#21208 disable extended tests that are currently broken for buildah
  test/extended/builds/build_timing.go
  test/extended/builds/digest.go
  test/extended/builds/docker_quota.go
  test/extended/builds/failure_status.go
  test/extended/builds/forcepull.go
  test/extended/builds/gitauth.go
  test/extended/builds/hooks.go
  test/extended/builds/multistage.go
  test/extended/builds/optimized.go
  test/extended/builds/proxy.go
  test/extended/builds/s2i_quota.go
  test/extended/builds/s2i_root.go
  test/extended/builds/secrets.go
  test/extended/builds/start.go
  test/extended/builds/valuefrom.go
Labels: approved, lgtm, retest-not-required, size/L

#21086 fixed typo in README.md
  test/extended/cluster/README.md
Labels: approved, lgtm, size/XS

#21124 Updating postCommit tests to cover docker and s2i
  test/extended/builds/hooks.go
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/build-postcommit/docker.yaml
  test/extended/testdata/builds/build-postcommit/imagestreams.yaml
  test/extended/testdata/builds/build-postcommit/sti.yaml
  test/extended/testdata/builds/test-build-postcommit.json
Labels: approved, lgtm, retest-not-required, size/XL

#21214 reworking/disabling more tests in anticipation of buildah switchover
  test/extended/builds/build_timing.go
  test/extended/builds/digest.go
  test/extended/images/layers.go
Labels: approved, lgtm, retest-not-required, size/S

#21213 3.11: UPSTREAM: 58646: Change the portworx volume attribute SupportsSELinux…
  vendor/k8s.io/kubernetes/pkg/volume/portworx/portworx.go
Labels: approved, lgtm, size/XS

#20443 RequestInfoResolver: restrict special project logic to project API groups
  pkg/authorization/authorizer/project_request_info_resolver.go
Labels: approved, lgtm, size/XS

#21225 fix defaults for openshift-controller-manager
  pkg/cmd/openshift-controller-manager/configdefault/openshiftcontrolplane_default.go
Labels: approved, lgtm, size/S

#21212 3.10: UPSTREAM: 58646: Change the portworx volume attribute SupportsSELinux…
  vendor/k8s.io/kubernetes/pkg/volume/portworx/portworx.go
Labels: approved, lgtm, size/XS

#21222 Use kubernetes prefix for its API server
  pkg/configconversion/legacyconfig_conversion.go
Labels: approved, lgtm, size/XS

#21191 Fix #20203 for release-3.10 branch
  pkg/oc/clusteradd/components/web-console-operator/web_console_operator.go
Labels: approved, lgtm, size/M

#21221 add local-up-master for running a controller manager without a kubelet
  hack/local-up-master/etcd.sh
  hack/local-up-master/kube-apiserver.yaml
  hack/local-up-master/lib.sh
  hack/local-up-master/logging.sh
  hack/local-up-master/master.sh
  hack/local-up-master/openshift-apiserver-manifests/01_service.yaml
  hack/local-up-master/openshift-apiserver-manifests/02_endpoint.yaml
  hack/local-up-master/openshift-apiserver-manifests/03_apiservice.yaml
  hack/local-up-master/openshift-apiserver.yaml
  hack/local-up-master/openshift-controller-manager.yaml
  hack/local-up-master/util.sh
Labels: approved, lgtm, size/XXL

#21227 remove refs to old plugin in base jenkins readme
  examples/jenkins/README.md
Labels: approved, lgtm, sig/developer-experience, size/M

#21223 More prune old jenkins plugin
  examples/jenkins/pipeline/README.md
  examples/jenkins/pipeline/mapsapp-pipeline.yaml
  pkg/oc/clusterup/manifests/bindata.go
  test/extended/builds/jenkins_plugin.go
  test/extended/builds/pipeline.go
  test/extended/testdata/bindata.go
Labels: approved, lgtm, retest-not-required, sig/developer-experience, size/XXL

#21217 Filter kubernetes admission plugins
  pkg/configconversion/simple.go
Labels: approved, lgtm, size/S

#21215 3.10: Fix iSCSI multipath issues
  vendor/k8s.io/kubernetes/pkg/volume/iscsi/BUILD
  vendor/k8s.io/kubernetes/pkg/volume/iscsi/attacher.go
  vendor/k8s.io/kubernetes/pkg/volume/iscsi/iscsi.go
  vendor/k8s.io/kubernetes/pkg/volume/iscsi/iscsi_util.go
  vendor/k8s.io/kubernetes/pkg/volume/util/device_util.go
  vendor/k8s.io/kubernetes/pkg/volume/util/device_util_linux.go
  vendor/k8s.io/kubernetes/pkg/volume/util/device_util_linux_test.go
  vendor/k8s.io/kubernetes/pkg/volume/util/device_util_unsupported.go
  vendor/k8s.io/kubernetes/pkg/volume/util/io_util.go
Labels: approved, lgtm, size/XL

#21216 3.11: Fix iSCSI multipath issues
  vendor/k8s.io/kubernetes/pkg/volume/iscsi/BUILD
  vendor/k8s.io/kubernetes/pkg/volume/iscsi/attacher.go
  vendor/k8s.io/kubernetes/pkg/volume/iscsi/iscsi.go
  vendor/k8s.io/kubernetes/pkg/volume/iscsi/iscsi_util.go
  vendor/k8s.io/kubernetes/pkg/volume/util/device_util.go
  vendor/k8s.io/kubernetes/pkg/volume/util/device_util_linux.go
  vendor/k8s.io/kubernetes/pkg/volume/util/device_util_linux_test.go
  vendor/k8s.io/kubernetes/pkg/volume/util/device_util_unsupported.go
  vendor/k8s.io/kubernetes/pkg/volume/util/io_util.go
Labels: approved, lgtm, sig/storage, size/XL

#21211 Explicitly disable admission plugins that we have off in the legacy path
  pkg/apiserver/admission/chain_builder.go
  pkg/apiserver/admission/config_test.go
  pkg/apiserver/admission/register.go
  pkg/cmd/openshift-kube-apiserver/server.go
  pkg/cmd/server/origin/legacyadmission/register.go
  pkg/cmd/server/start/start_master.go
Labels: approved, lgtm, size/S

#21122 Fix up "should not auto-assign egress IPs" cases
  pkg/network/common/egressip.go
  pkg/network/common/egressip_test.go
Labels: approved, component/networking, kind/bug, lgtm, sig/networking, size/M

#21251 re-enable postcommithook tests
  test/extended/builds/hooks.go
Labels: approved, lgtm

#21081 Bug 1632155 - Accept logFormat when passed to audit config
  pkg/cmd/openshift-apiserver/openshiftapiserver/configprocessing/audit.go
Labels: approved, lgtm, size/XS

#21257 fix expected output for buildah pushes
  test/extended/images/helper.go
Labels: approved, lgtm, size/XS

#21262 cgroup quota tests are irrelevant with docker, deleting
  test/extended/builds/docker_quota.go
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/test-docker-build-quota-optimized.json
  test/extended/testdata/builds/test-docker-build-quota.json
Labels: approved, lgtm, size/L

#21268 Move openshift.io/RestrictSubjectBindings to kube admissions
  pkg/apiserver/admission/chain_builder.go
Labels: approved, lgtm, size/XS

#21271 CI Fixes
  vendor/k8s.io/kubernetes/test/e2e/framework/util.go
  vendor/k8s.io/kubernetes/test/e2e/storage/subpath.go
Labels: approved, lgtm, size/M

#21234 Issue #21153 update the console URI not to redirect 127.0.0.1
  pkg/oc/clusterup/up.go
Labels: approved, lgtm, size/XS

#21270 make sure that the openshift apiserver includes namespace lifecycle admission
  pkg/apiserver/admission/chain_builder.go
Labels: approved, lgtm, sig/master, size/XS

#21276 `oc adm release new --from-release` should honor mappings
  pkg/oc/cli/admin/release/image_mapper.go
  pkg/oc/cli/admin/release/new.go
Labels: approved, lgtm, size/S

#21273 Adding OS_IMAGE_TAG env var
  hack/build-local-images.py
Labels: approved, lgtm, size/XS

#21248 Fix help examples for image append/extract
  pkg/oc/cli/image/append/append.go
  pkg/oc/cli/image/extract/extract.go
Labels: approved, lgtm, size/XS

#21279 pkg/oc/cli/admin/release/new: Document SRC=DST positional args
  pkg/oc/cli/admin/release/new.go
Labels: approved, lgtm, size/S

#21286 remove aggressive default for kubelet
  pkg/cmd/openshift-kube-apiserver/configdefault/kubecontrolplane_default.go
Labels: approved, lgtm, size/XS

#21267 Wire tls-sni-cert-key flag
  pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/flags.go
Labels: approved, lgtm, size/S

#21294 Bug 1632154 - Accept logFormat when passed to audit config
  pkg/cmd/server/kubernetes/master/master_config.go
Labels: approved, lgtm, size/XS

#21196 Added support of Namespace and Pod selector for networkpolicy
  pkg/network/node/networkpolicy.go
  test/extended/networking/networkpolicy.go
Labels: approved, lgtm, size/L

#21177 Don't regenerate apps and build files
  hack/update-generated-informers.sh
  hack/update-generated-listers.sh
Labels: approved, lgtm, size/XS

#21321 skip broken test for now
  test/extended/builds/start.go
Labels: approved, lgtm, size/XS

#21307 re-enable proxy redacting build tests
  test/extended/builds/proxy.go
Labels: approved, lgtm, size/XS

#21263 don't mount the docker/crio sockets into build pods
  pkg/build/controller/strategy/custom.go
  pkg/build/controller/strategy/docker.go
  pkg/build/controller/strategy/docker_test.go
  pkg/build/controller/strategy/sti.go
  pkg/build/controller/strategy/sti_test.go
  pkg/build/controller/strategy/util.go
Labels: approved, lgtm, size/M

#21261 re-enable various builder e2es now that dockerless has landed
  test/extended/builds/build_timing.go
  test/extended/builds/failure_status.go
  test/extended/builds/secrets.go
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/build-secrets/s2i-binary-dir/.s2i/bin/run
Labels: approved, lgtm, retest-not-required, size/M

#21324 Filter kubernetes plugins but only when building kubernetes config
  pkg/apiserver/admission/chain_builder.go
  pkg/apiserver/admission/config_test.go
  pkg/configconversion/legacyconfig_conversion.go
  pkg/configconversion/simple.go
Labels: approved, lgtm, size/M

#21232 Revert "use namespace labels to prevent SCC usage"
  test/extended/util/test.go
Labels: approved, lgtm, size/M

#21333 re-enable symlink tests
  test/extended/builds/start.go
Labels: approved, lgtm, retest-not-required, size/XS

#21290 Add ConfigMap for CAs to build pods
  pkg/api/apihelpers/namer.go
  pkg/build/buildapihelpers/util.go
  pkg/build/controller/build/build_controller.go
  pkg/build/controller/build/build_controller_test.go
  pkg/build/controller/strategy/custom.go
  pkg/build/controller/strategy/custom_test.go
  pkg/build/controller/strategy/docker.go
  pkg/build/controller/strategy/docker_test.go
  pkg/build/controller/strategy/sti.go
  pkg/build/controller/strategy/sti_test.go
  pkg/build/controller/strategy/util.go
  pkg/build/controller/strategy/util_test.go
  pkg/build/util/consts.go
  pkg/cmd/server/bootstrappolicy/controller_policy.go
  test/extended/builds/build_pruning.go
  test/extended/builds/build_timing.go
  test/extended/builds/completiondeadlineseconds.go
  test/extended/builds/contextdir.go
  test/extended/builds/digest.go
  test/extended/builds/docker_pullsecret.go
  test/extended/builds/dockerfile.go
  test/extended/builds/failure_status.go
  test/extended/builds/forcepull.go
  test/extended/builds/gitauth.go
  test/extended/builds/hooks.go
  test/extended/builds/image_source.go
  test/extended/builds/imagechangetriggers.go
  test/extended/builds/labels.go
  test/extended/builds/long_names.go
  test/extended/builds/multistage.go
  test/extended/builds/new_app.go
  test/extended/builds/no_outputname.go
  test/extended/builds/nosrc.go
  test/extended/builds/optimized.go
  test/extended/builds/proxy.go
  test/extended/builds/remove_buildconfig.go
  test/extended/builds/revision.go
  test/extended/builds/run_policy.go
  test/extended/builds/s2i_dropcaps.go
  test/extended/builds/s2i_env.go
  test/extended/builds/s2i_incremental.go
  test/extended/builds/s2i_quota.go
  test/extended/builds/s2i_root.go
  test/extended/builds/secrets.go
  test/extended/builds/valuefrom.go
  test/extended/templates/templateinstance_readiness.go
  test/extended/util/framework.go
  test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml
  test/testdata/bootstrappolicy/bootstrap_policy_file.yaml
Labels: approved, lgtm, size/XL

#21328 fix service name for new registry
  pkg/serviceaccounts/OWNERS
  pkg/serviceaccounts/controllers/docker_registry_service.go
Labels: approved, lgtm, retest-not-required, size/XS

#21340 add test for builds accessing cluster services
  test/extended/builds/dockerfile.go
  test/extended/builds/service.go
Labels: approved, lgtm, size/M

#21337 Updating tests for new S2I postCommit code
  test/extended/builds/failure_status.go
Labels: approved, lgtm, retest-not-required, size/XS

#21327 Disable admission's DefaultOffPlugins unless they are explicitly enabled
  pkg/apiserver/admission/chain_builder.go
  pkg/apiserver/admission/config_test.go
  pkg/apiserver/admission/register.go
  pkg/cmd/openshift-apiserver/openshiftapiserver/config.go
Labels: approved, lgtm, size/M

#21349 Update checked for error for post commit hook test
  test/extended/builds/failure_status.go
Labels: approved, lgtm, retest-not-required, size/XS

#21346 Create new testdata/cluster OWNERS file
  test/extended/testdata/cluster/OWNERS
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#21301 UPSTREAM: 67825: fix vsphere multiattach issue
  vendor/k8s.io/kubernetes/pkg/controller/volume/attachdetach/reconciler/reconciler.go
Labels: approved, lgtm

#21283 3.11 Fixed subpath cleanup when /var/lib/kubelet is a symlink
  vendor/k8s.io/kubernetes/pkg/util/mount/mount.go
  vendor/k8s.io/kubernetes/pkg/util/mount/nsenter_mount.go
Labels: approved, lgtm, size/S

#21343 fix unbound var check in localup temp dir cleanup
  hack/local-up-master/util.sh
Labels: approved, lgtm, size/XS

#21295 allow oc to behave as a kubectl plugin based on filename
  pkg/oc/cli/cli.go
Labels: approved, lgtm, size/M

#21357 [release-1.11] Backport cronjobs fixes
  vendor/k8s.io/kubernetes/test/e2e/apps/cronjob.go
Labels: approved, lgtm, size/M

#21289 Generate cincinnati metadata when building a release
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  hack/import-restrictions.json
  pkg/oc/cli/admin/release/mirror.go
  pkg/oc/cli/admin/release/new.go
Labels: approved, lgtm, size/L

#21313 remove default behavior of selecting all resources
  pkg/oc/cli/set/imagelookup.go
Labels: approved, lgtm, size/XS

#21332 Remove CombinedAdmissionControlPlugins from kube-api startup and enable only kube-specific ones
  pkg/apiserver/admission/chain_builder.go
  pkg/apiserver/admission/config_test.go
  pkg/apiserver/admission/register.go
  pkg/apiserver/admission/sync_test.go
  pkg/cmd/openshift-kube-apiserver/server.go
Labels: approved, lgtm, size/L

#21356 UPSTREAM: 70206: test/e2e/apps: fix race in cronjob test
  vendor/k8s.io/kubernetes/test/e2e/apps/cronjob.go
Labels: approved, lgtm, size/S

#21364 Bump conformance test to use 1.11 branch for master
  test/extended/conformance-k8s.sh
Labels: approved, lgtm, size/XS

#21367 handle appsv1.DeploymenConfigs in AttachablePodForObject helper
  pkg/oc/originpolymorphichelpers/attachablepodforobject.go
Labels: approved, lgtm, size/S

#21365 Update k8s conformance test for 3.11 to point to 1.11
  test/extended/conformance-k8s.sh
Labels: approved, lgtm, size/XS

#21304 fix formatString describe helper
  pkg/oc/lib/describe/helpers.go
Labels: approved, lgtm

#21350 cli: Extracting image as non-root fails on directory permissions
  pkg/oc/cli/image/extract/extract.go
Labels: approved, lgtm, size/S

#20518 Add new ifexists field to CL config
  test/extended/testdata/bindata.go
  test/extended/testdata/cluster/master-vert.yaml
Labels: approved, lgtm, size/S

#21363 Don't allow pods to send VXLAN packets out of the SDN
  pkg/network/node/ovscontroller.go
Labels: approved, lgtm, sig/networking, size/XS

#21274 UPSTREAM: 69890: Run static pods before bootstrap
  vendor/k8s.io/kubernetes/cmd/kubelet/app/server.go
  vendor/k8s.io/kubernetes/pkg/kubelet/certificate/bootstrap/bootstrap.go
  vendor/k8s.io/kubernetes/pkg/kubelet/certificate/kubelet.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/util/certificate/certificate_manager.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/util/certificate/certificate_manager_test.go
Labels: approved, lgtm, size/L

#21096 Split API servers from integration tests
  hack/test-integration.sh
  hack/update-generated-deep-copies.sh
  pkg/cmd/openshift-apiserver/openshiftapiserver/config.go
  pkg/configconversion/simple.go
  test/integration/admissionconfig_test.go
  test/integration/api_paths_test.go
  test/integration/audit_test.go
  test/integration/auth_proxy_test.go
  test/integration/buildcontroller_test.go
  test/integration/clusterquota_test.go
  test/integration/discovery_test.go
  test/integration/dns_test.go
  test/integration/etcd_storage_path_test.go
  test/integration/front_proxy_test.go
  test/integration/master_routes_test.go
  test/integration/oauth_basicauth_test.go
  test/integration/oauth_oidc_test.go
  test/integration/oauth_request_header_test.go
  test/integration/runner/runner_test.go
  test/integration/sdn_test.go
  test/integration/testing/admissionconfig.go
  test/integration/testing/doc.go
  test/integration/testing/zz_generated.deepcopy.go
  test/integration/webhook_token_auth_test.go
  test/util/policy.go
  test/util/server/server.go
Labels: approved, lgtm, sig/security, size/XXL

#21372 wait for deployment before waiting for endpoint
  test/extended/builds/service.go
Labels: approved, lgtm, retest-not-required, size/XS

#21284 3.10 Fixed subpath cleanup when /var/lib/kubelet is a symlink
  vendor/k8s.io/kubernetes/pkg/kubelet/cm/container_manager_linux_test.go
  vendor/k8s.io/kubernetes/pkg/util/mount/exec_mount.go
  vendor/k8s.io/kubernetes/pkg/util/mount/exec_mount_test.go
  vendor/k8s.io/kubernetes/pkg/util/mount/exec_mount_unsupported.go
  vendor/k8s.io/kubernetes/pkg/util/mount/fake.go
  vendor/k8s.io/kubernetes/pkg/util/mount/mount.go
  vendor/k8s.io/kubernetes/pkg/util/mount/mount_linux.go
  vendor/k8s.io/kubernetes/pkg/util/mount/mount_unsupported.go
  vendor/k8s.io/kubernetes/pkg/util/mount/mount_windows.go
  vendor/k8s.io/kubernetes/pkg/util/mount/nsenter_mount.go
  vendor/k8s.io/kubernetes/pkg/util/mount/nsenter_mount_unsupported.go
  vendor/k8s.io/kubernetes/pkg/util/nsenter/nsenter.go
  vendor/k8s.io/kubernetes/pkg/util/removeall/removeall_test.go
  vendor/k8s.io/kubernetes/pkg/volume/host_path/host_path_test.go
Labels: approved, lgtm, size/L

#21376 [3.11] Don't allow pods to send VXLAN packets out of the SDN
  pkg/network/node/ovscontroller.go
Labels: approved, component/networking, kind/bug, lgtm, sig/networking, size/XS

#21348 remove jenkins autoprovision logic+config
  pkg/apiserver/admission/chain_builder.go
  pkg/apiserver/admission/config_test.go
  pkg/apiserver/admission/plugin_initializer.go
  pkg/apiserver/admission/register.go
  pkg/apiserver/admission/sync_test.go
  pkg/build/apiserver/admission/jenkinsbootstrapper/admission.go
  pkg/build/apiserver/admission/jenkinsbootstrapper/admission_test.go
  pkg/build/apiserver/admission/jenkinsbootstrapper/initializer.go
  pkg/build/apiserver/admission/jenkinsbootstrapper/jenkins/jenkins.go
  pkg/build/apiserver/admission/jenkinsbootstrapper/jenkins/jenkins_test.go
  pkg/cmd/openshift-apiserver/openshiftapiserver/config.go
  pkg/cmd/server/origin/legacyadmission/chain_builder.go
  pkg/cmd/server/origin/legacyadmission/plugin_initializer.go
  pkg/cmd/server/origin/legacyadmission/register.go
  pkg/cmd/server/origin/master_config.go
  test/extended/builds/jenkins_autoprovision.go
Labels: approved, lgtm, size/XL

#21345 bump(*)
  glide.yaml
  test/extended/builds/start.go
  vendor/github.com/openshift/source-to-image/.travis.yml
  vendor/github.com/openshift/source-to-image/hack/install-tools.sh
  vendor/github.com/openshift/source-to-image/pkg/build/strategies/sti/sti.go
  vendor/github.com/openshift/source-to-image/pkg/tar/tar.go
Labels: approved, lgtm, size/S

#21377 [3.10] Don't allow pods to send VXLAN packets out of the SDN
  pkg/network/node/ovscontroller.go
Labels: approved, component/networking, kind/bug, lgtm, sig/networking, size/XS

#21369 UPSTREAM: 70311: fix ContinueOnError visitor
  vendor/k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource/builder.go
Labels: approved, lgtm, size/XS

#21383 UPSTREAM: 70286: Use pvc uid instead of pvc name in glusterfs endpoint name
  vendor/k8s.io/kubernetes/pkg/volume/glusterfs/glusterfs.go
Labels: approved, lgtm, size/XS

#21389 Updating postcommit hooks to use correct options
  examples/sample-app/application-template-custombuild.json
  examples/sample-app/application-template-dockerbuild.json
  examples/sample-app/application-template-pullspecbuild.json
  examples/sample-app/application-template-stibuild.json
  test/extended/testdata/bindata.go
Labels: approved, lgtm, size/S

#21287 [3.11] Fix up "should not auto-assign egress IPs" cases
  pkg/network/common/egressip.go
  pkg/network/common/egressip_test.go
Labels: approved, component/networking, kind/bug, lgtm, sig/networking, size/M

#21299 Drop master-config.yaml support from openshift-network-controller
  images/dind/master/openshift-generate-master-config.sh
  images/dind/master/openshift-sdn-master.service
  pkg/cmd/openshift-network-controller/cmd.go
Labels: approved, lgtm, size/M

#21209 dind - add default --service-cluster-ip-range
  images/dind/master/ovn-kubernetes-master.sh
  images/dind/node/ovn-kubernetes-node.sh
Labels: approved, lgtm, size/XS

#21385 Switch integration test to manually starting kube & openshift controller managers
  pkg/configconversion/simple.go
  test/integration/clusterquota_test.go
  test/util/server/server.go
Labels: approved, lgtm, size/L

#21250 Change file permissions on console serving cert
  install/openshift-web-console-operator/install.yaml
  pkg/oc/clusterup/manifests/bindata.go
  test/extended/testdata/bindata.go
Labels: approved, lgtm, size/XS
