Repository openshift/origin, pull requests merged in 2018-05, with the labels that each got.

#19542 Correctly handle legacy ungroupified PSP review resources
  pkg/api/legacygroupification/groupification.go
  test/cmd/policy.sh
  test/testdata/legacy_ungroupified_psp_review.yaml
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/discovery/patch_restmapper_kind.go
Labels: approved, kind/bug, lgtm, sig/master, sig/security, size/M

#19565 Fix UpdateEgressNetworkPolicyRules() to return both input and ovs transaction errors
  pkg/network/node/ovscontroller.go
Labels: approved, lgtm, sig/networking, size/S

#19566 up: consolidate usage of out and remove tasks
  pkg/oc/bootstrap/docker/error_printer.go
  pkg/oc/bootstrap/docker/openshift/project.go
  pkg/oc/bootstrap/docker/printer.go
  pkg/oc/bootstrap/docker/up.go
Labels: approved, lgtm, size/L

#19555 Pause the work queue when following, instead of retrying
  pkg/util/writerlease/writerlease.go
Labels: approved, lgtm, size/XS

#19364 UPSTREAM: 62462: Private mount propagation
  vendor/k8s.io/kubernetes/pkg/apis/core/types.go
  vendor/k8s.io/kubernetes/pkg/apis/core/validation/validation.go
  vendor/k8s.io/kubernetes/pkg/apis/core/validation/validation_test.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_pods.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_pods_test.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/api/core/v1/types.go
  vendor/k8s.io/kubernetes/test/e2e/node/mount_propagation.go
Labels: approved, lgtm, size/M

#19444 UPSTREAM: 62668: add metrics to cinder volume
  vendor/k8s.io/kubernetes/pkg/volume/cinder/cinder.go
Labels: approved, lgtm, size/M

#19315 Remove the DROP_SYN_DURING_RESTART iptables rules
  hack/lib/start.sh
  images/router/haproxy/reload-haproxy
  test/extended/setup.sh
Labels: approved, component/routing, kind/bug, lgtm, size/M

#19584 ext_tests: make mongodb check tolerate any non zero pagecount
  test/extended/image_ecosystem/sample_repos.go
Labels: approved, area/tests, lgtm, sig/developer-experience, size/L

#19510 router - add "option tcplog" to frontend public_ssl
  images/router/haproxy/conf/haproxy-config.template
Labels: approved, component/routing, kind/bug, lgtm, size/XS

#19570 add declarative pipeline example to readme
  examples/jenkins/pipeline/README.md
Labels: approved, lgtm, retest-not-required-docs-only, sig/developer-experience, size/S

#19601 UPSTREAM: google/cadvisor: 1903: fix #1902 bug with retryDockerStatus
  vendor/github.com/google/cadvisor/manager/manager.go
Labels: approved, lgtm, size/XS

#19602 UPSTREAM: 63349: Decorate function not called on Create
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/registry/generic/registry/store.go
Labels: approved, lgtm, size/XS

#19457 run SCC in default
  pkg/admission/namespaceconditions/decorator.go
  pkg/oc/bootstrap/clusteradd/componentinstall/apply_template.go
  pkg/quota/admission/clusterresourcequota/admission.go
Labels: approved, lgtm, sig/master, size/S

#19561 up: fix mount-path for docker registry
  pkg/oc/bootstrap/clusteradd/components/registry/registry_install.go
  pkg/oc/bootstrap/docker/down.go
  pkg/oc/cli/cli.go
  pkg/oc/cli/cmd/cluster/cluster.go
Labels: approved, lgtm, size/M

#19607 Ensure Continue token is proxied for openshift RBAC list calls
  pkg/authorization/registry/clusterrole/proxy.go
  pkg/authorization/registry/clusterrolebinding/proxy.go
  pkg/authorization/registry/role/proxy.go
  pkg/authorization/registry/rolebinding/proxy.go
Labels: approved, lgtm, size/S

#19532 Fix BuildConfig Environment Variable Modification
  pkg/build/util/util.go
  pkg/build/util/util_test.go
Labels: approved, lgtm, size/L

#19396 allow template instance controller to create CRDs
  pkg/cmd/openshift-controller-manager/controller/interfaces.go
  pkg/cmd/openshift-controller-manager/controller/template.go
  pkg/cmd/openshift-controller-manager/controller_manager.go
  pkg/template/controller/templateinstance_controller.go
  pkg/template/controller/templateinstance_controller_test.go
  test/extended/testdata/bindata.go
  test/extended/testdata/templates/templateservicebroker_bind.yaml
Labels: approved, lgtm, sig/security, size/L

#19404 don't block creation on lack of delete powers
  test/integration/ownerrefs_test.go
  vendor/k8s.io/kubernetes/plugin/pkg/admission/gc/gc_admission.go
  vendor/k8s.io/kubernetes/plugin/pkg/admission/gc/gc_admission_test.go
Labels: approved, lgtm, sig/master, sig/security, size/M

#19571 Egress DNS proxy: prefer IPv4 addr during DNS resolution
  images/egress/dns-proxy/egress-dns-proxy.sh
Labels: approved, lgtm, sig/networking, size/XS

#19572 Bug 1572179 - Remove openvswitch check from UnitStatus diagnostic
  pkg/oc/admin/diagnostics/diagnostics/README.md
  pkg/oc/admin/diagnostics/diagnostics/systemd/unit_status.go
Labels: approved, component/diagnostics, lgtm, size/S

#19393 OpenShift SDN: Changed ovs.Transaction from pseudo to real atomic transaction
  pkg/network/node/multitenant.go
  pkg/network/node/networkpolicy.go
  pkg/network/node/ovscontroller.go
  pkg/network/node/ovscontroller_test.go
  pkg/network/node/singletenant.go
  pkg/util/ovs/fake_ovs.go
  pkg/util/ovs/fake_ovs_test.go
  pkg/util/ovs/ovs.go
  pkg/util/ovs/ovs_test.go
Labels: approved, component/networking, lgtm, sig/networking, size/L

#19613 Fix ruby version skew in imagestream extended tests
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/test-imageresolution-custom-build.yaml
  test/extended/testdata/builds/test-imageresolution-docker-build.yaml
  test/extended/testdata/builds/test-imageresolution-s2i-build.yaml
  test/extended/testdata/builds/test-imagesource-buildconfig.yaml
Labels: approved, lgtm, size/S

#19388 Handle project existence in cluster-loader
  test/extended/cluster/cl.go
  test/extended/cluster/context.go
  test/extended/cluster/utils.go
Labels: approved, lgtm, size/M

#19627 bump(*): source-to-image and k8s
  glide.lock
  vendor/github.com/emicklei/go-restful-swagger12/origin.sha
  vendor/github.com/openshift/source-to-image/hack/test-stirunimage.sh
  vendor/github.com/openshift/source-to-image/pkg/api/types.go
  vendor/github.com/openshift/source-to-image/pkg/api/types_test.go
  vendor/github.com/openshift/source-to-image/pkg/build/strategies/sti/sti.go
  vendor/github.com/openshift/source-to-image/pkg/tar/tar_test.go
  vendor/github.com/openshift/source-to-image/pkg/util/env.go
  vendor/github.com/openshift/source-to-image/pkg/util/env_test.go
  vendor/github.com/openshift/source-to-image/pkg/util/injection.go
  vendor/github.com/openshift/source-to-image/pkg/util/injection_test.go
  vendor/github.com/openshift/source-to-image/test/integration/integration_test.go
Labels: approved, lgtm, size/L

#19615 Ignore writes on router stress test from other routes
  pkg/router/controller/status.go
  test/extended/router/stress.go
Labels: approved, kind/test-flake, lgtm, size/S

#19625 UPSTREAM: 63339: kubelet: volume: do not create event on mount success
  vendor/k8s.io/kubernetes/pkg/volume/util/operationexecutor/operation_generator.go
Labels: approved, lgtm, size/XS

#19617 Prevent accidental binary size regressions
  hack/lib/build/binaries.sh
  hack/lib/constants.sh
Labels: approved, lgtm, size/S

#19104 UPSTREAM: <carry>: pods in openshift-* namespace can be marked critical
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/pkg/kubelet/types/pod_update.go
  vendor/k8s.io/kubernetes/pkg/kubelet/types/pod_update_test.go
Labels: approved, lgtm, size/S, vendor-update

#19576 UPSTREAM: 62874: dockershim/sandbox: clean up pod network even if SetUpPod() failed
  vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/docker_sandbox.go
  vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/docker_sandbox_test.go
Labels: approved, lgtm, size/S

#19603 Auto egress IP code reorg in prep for future features
  pkg/network/node/egressip.go
  pkg/network/node/egressip_test.go
Labels: approved, component/networking, lgtm, sig/networking, size/L

#19492 Second version of helper code for sorting map files.
  images/router/haproxy/conf/haproxy-config.template
  pkg/router/template/plugin.go
  pkg/router/template/template_helper.go
  pkg/router/template/template_helper_test.go
  pkg/router/template/util/haproxy/map_entry.go
  pkg/router/template/util/haproxy/map_entry_test.go
  pkg/router/template/util/haproxy/types.go
  pkg/router/template/util/util.go
  pkg/router/template/util/util_test.go
Labels: approved, lgtm, size/XXL

#19620 UPSTREAM: 63417: Panic when map string bool flag has no value
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/util/flag/map_string_bool.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/util/flag/map_string_string.go
Labels: approved, lgtm, size/XS

#19616 remove old reapers
  pkg/oc/admin/diagnostics/diagnostics/cluster/app_create/setup_cleanup.go
  pkg/oc/cli/builds/doc.go
  pkg/oc/cli/builds/reaper.go
  pkg/oc/cli/builds/reaper_test.go
  pkg/oc/cli/deploymentconfigs/delete.go
  pkg/oc/cli/deploymentconfigs/delete_test.go
  pkg/oc/cli/util/clientcmd/factory_builder.go
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/delete.go
Labels: approved, lgtm, size/XL

#19630 Drop myself from owners files
  examples/deployment/OWNERS
  hack/lib/OWNERS
  images/base/OWNERS
  images/builder/OWNERS
  images/deployer/OWNERS
  images/egress/OWNERS
  images/ipfailover/OWNERS
  images/node/OWNERS
  images/origin/OWNERS
  images/pod/OWNERS
  images/recycler/OWNERS
  images/source/OWNERS
  pkg/api/OWNERS
  pkg/apps/OWNERS
  pkg/cmd/OWNERS
  pkg/controller/OWNERS
  pkg/oc/cli/deploymentconfigs/OWNERS
  test/end-to-end/OWNERS
  test/extended/OWNERS
  test/integration/OWNERS
  tools/genman/OWNERS
Labels: approved, lgtm, size/M

#19612 Fix jenkins plugin hang
  test/extended/builds/jenkins_plugin.go
  test/extended/testdata/bindata.go
  test/extended/testdata/jenkins-plugin/shared-resources-template.json
Labels: approved, lgtm, sig/developer-experience, size/M

#19611 Add option to ignore image reference errors
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/oc/admin/prune/imageprune/prune.go
  pkg/oc/admin/prune/imageprune/prune_test.go
  pkg/oc/admin/prune/images.go
Labels: approved, component/image, kind/bug, lgtm, size/L

#19629 Relaxing docker image source extended test
  test/extended/builds/contextdir.go
  test/extended/builds/image_source.go
  test/extended/builds/pipeline.go
  test/extended/builds/start.go
  test/extended/cluster/utils.go
  test/extended/image_ecosystem/helper.go
  test/extended/image_ecosystem/mongodb_ephemeral.go
  test/extended/image_ecosystem/mongodb_replica_statefulset.go
  test/extended/image_ecosystem/mysql_replica.go
  test/extended/image_ecosystem/postgresql_replica.go
  test/extended/image_ecosystem/s2i_perl.go
  test/extended/image_ecosystem/s2i_php.go
  test/extended/image_ecosystem/s2i_python.go
  test/extended/image_ecosystem/s2i_ruby.go
  test/extended/jobs/jobs.go
  test/extended/util/framework.go
  test/extended/util/jenkins/ref.go
Labels: approved, lgtm, size/L

#19514 update docker config secret to include image-registry.openshift-image…
  pkg/cmd/openshift-controller-manager/controller/serviceaccount.go
  pkg/serviceaccounts/controllers/docker_registry_service.go
  pkg/serviceaccounts/controllers/docker_registry_service_test.go
Labels: approved, lgtm, sig/master, size/L

#19029 Apps: Fix DC recreate strategy to wait only for running pods
  pkg/apps/strategy/recreate/recreate.go
Labels: approved, lgtm, size/M

#19595 Add pmorie to approvers for pkg/oc/bootstrap
  pkg/oc/bootstrap/OWNERS
Labels: approved, lgtm, size/XS

#19564 up: remove logDir argument
  hack/lib/constants.sh
  pkg/oc/bootstrap/clusteradd/cmd.go
  pkg/oc/bootstrap/clusteradd/componentinstall/apply_list.go
  pkg/oc/bootstrap/clusteradd/componentinstall/apply_template.go
  pkg/oc/bootstrap/clusteradd/componentinstall/interface.go
  pkg/oc/bootstrap/clusteradd/componentinstall/union_component.go
  pkg/oc/bootstrap/clusteradd/components/default-imagestreams/default_imagestreams.go
  pkg/oc/bootstrap/clusteradd/components/register-template-service-broker/register_tsb.go
  pkg/oc/bootstrap/clusteradd/components/registry/registry_install.go
  pkg/oc/bootstrap/clusteradd/components/router/router_install.go
  pkg/oc/bootstrap/clusteradd/components/sample-templates/sample_templates.go
  pkg/oc/bootstrap/clusteradd/components/service-catalog/service_catalog.go
  pkg/oc/bootstrap/clusteradd/components/template-service-broker/template_service_broker.go
  pkg/oc/bootstrap/clusteradd/components/web-console-operator/web_console_operator.go
  pkg/oc/bootstrap/clusteradd/components/web-console/web_console.go
  pkg/oc/bootstrap/clusterup/components/persistent-volumes/setup_persistent_volumes.go
  pkg/oc/bootstrap/docker/run_self_hosted.go
  pkg/oc/bootstrap/docker/up.go
  pkg/oc/cli/cmd/login/loginoptions.go
  pkg/oc/errors/errors.go
  pkg/oc/errors/printer.go
Labels: approved, lgtm, sig/master, size/L

#19658 dind: bump up journald ratelimiting to ensure messages get logged
  images/dind/node/Dockerfile
  images/dind/node/journald.conf
Labels: approved, component/networking, lgtm, sig/networking, size/XS

#19546 use a finalizer instead of GC to clean up templateinstances
  pkg/cmd/openshift-controller-manager/controller/config.go
  pkg/cmd/openshift-controller-manager/controller/template.go
  pkg/cmd/server/bootstrappolicy/controller_policy.go
  pkg/template/apis/template/constants.go
  pkg/template/controller/templateinstance_controller.go
  pkg/template/controller/templateinstance_finalizer.go
  test/extended/templates/templateinstance_objectkinds.go
  test/extended/templates/templateservicebroker_e2e.go
  test/extended/testdata/bindata.go
  test/extended/testdata/templates/templateinstance_objectkinds.yaml
  test/extended/testdata/templates/templateservicebroker_bind.yaml
  test/integration/authorization_test.go
  test/testdata/bootstrappolicy/bootstrap_cluster_role_bindings.yaml
  test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml
  test/testdata/bootstrappolicy/bootstrap_policy_file.yaml
Labels: approved, lgtm, size/XL

#19654 disable recently problematic mongo/mysql replica tests (will diagnose…
  test/extended/image_ecosystem/mongodb_replica_statefulset.go
  test/extended/image_ecosystem/mysql_replica.go
Labels: approved, lgtm, sig/developer-experience, size/XS

#19637 catalog: remove OS_GIT_CATALOG_VERSION
  hack/lib/build/version.sh
Labels: approved, lgtm, retest-not-required, size/XS

#19665 UPSTREAM: 62874: dockershim/sandbox: clean up pod network even if SetUpPod() failed
  vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/docker_sandbox.go
  vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/docker_sandbox_test.go
Labels: component/networking, lgtm, sig/networking, size/S

#19668 deflake TSB deprovision test
  test/extended/templates/templateservicebroker_e2e.go
Labels: approved, lgtm, size/M

#19653 update external examples
  examples/image-streams/image-streams-centos7.json
  examples/image-streams/image-streams-rhel7.json
  examples/quickstarts/cakephp-mysql-persistent.json
  examples/quickstarts/cakephp-mysql.json
  examples/quickstarts/django-postgresql-persistent.json
  examples/quickstarts/django-postgresql.json
  examples/quickstarts/nodejs-mongodb-persistent.json
  examples/quickstarts/nodejs-mongodb.json
  pkg/oc/bootstrap/bindata.go
  test/cmd/images.sh
  test/cmd/newapp.sh
  test/extended/testdata/bindata.go
Labels: approved, lgtm, sig/developer-experience, size/XL

#19498 add logic for openshift webconsole operator
  install/openshift-web-console-operator/install.yaml
  pkg/cmd/openshift-operators/apis/operators/v1alpha1/types.go
  pkg/cmd/openshift-operators/apis/operators/v1alpha1/zz_generated.deepcopy.go
  pkg/cmd/openshift-operators/util/resourceapply/apps.go
  pkg/cmd/openshift-operators/util/resourceapply/core.go
  pkg/cmd/openshift-operators/util/resourcemerge/object_merger.go
  pkg/cmd/openshift-operators/util/resourceread/apiextensions.go
  pkg/cmd/openshift-operators/util/resourceread/apps.go
  pkg/cmd/openshift-operators/util/resourceread/core.go
  pkg/cmd/openshift-operators/util/resourceread/operators.go
  pkg/cmd/openshift-operators/util/resourceread/rbac.go
  pkg/cmd/openshift-operators/webconsole-operator/config_v1.go
  pkg/cmd/openshift-operators/webconsole-operator/sync_v310_00.go
  pkg/cmd/openshift-operators/webconsole-operator/v310_00/cm.go
  pkg/cmd/openshift-operators/webconsole-operator/v310_00/deployment.go
  pkg/cmd/openshift-operators/webconsole-operator/v310_00/ns.go
  pkg/cmd/openshift-operators/webconsole-operator/v310_00/sa.go
  pkg/cmd/openshift-operators/webconsole-operator/v310_00/svc.go
  pkg/cmd/openshift-operators/webconsole-operator/v310_00/webconsole_config.go
  pkg/cmd/openshift-operators/webconsole-operator/webconsole_operator_trigger.go
  pkg/oc/bootstrap/bindata.go
  pkg/oc/bootstrap/clusteradd/cmd.go
  pkg/oc/bootstrap/clusteradd/componentinstall/context.go
  pkg/oc/bootstrap/clusteradd/components/web-console-operator/web_console_operator.go
  pkg/oc/bootstrap/clusterup/kubeapiserver/config.go
  pkg/oc/bootstrap/docker/run_self_hosted.go
  pkg/oc/bootstrap/docker/up.go
  test/extended/testdata/bindata.go
Labels: approved, lgtm, size/XXL

#19676 start collapsing onto upstream env vars
  pkg/oc/cli/util/clientcmd/factory_client_access.go
Labels: approved, lgtm, size/XS

#19680 snip links to libraries that cannot be included in library-go
  pkg/cmd/server/crypto/crypto.go
  pkg/cmd/util/crypto.go
  pkg/route/apis/route/validation/validation.go
  pkg/service/controller/servingcert/cryptoextensions/doc.go
  pkg/service/controller/servingcert/cryptoextensions/extensions.go
  pkg/service/controller/servingcert/cryptoextensions/serversigning.go
  pkg/service/controller/servingcert/secret_creating_controller.go
  pkg/service/controller/servingcert/secret_creating_controller_test.go
  pkg/service/controller/servingcert/secret_updating_controller.go
Labels: approved, lgtm, size/M

#19657 remove legacy resource and kind checks from the CLI
  pkg/api/meta/pods.go
  pkg/apps/apis/apps/register.go
  pkg/authorization/apis/authorization/register.go
  pkg/build/admission/jenkinsbootstrapper/admission.go
  pkg/build/admission/strategyrestrictions/admission.go
  pkg/build/apis/build/register.go
  pkg/build/registry/buildconfig/webhook.go
  pkg/build/registry/buildconfig/webhook_test.go
  pkg/image/admission/admission.go
  pkg/image/apis/image/register.go
  pkg/network/apis/network/register.go
  pkg/oauth/apis/oauth/register.go
  pkg/oc/admin/policy/reconcile_clusterroles.go
  pkg/oc/cli/cmd/cancelbuild.go
  pkg/oc/cli/cmd/logs.go
  pkg/oc/cli/cmd/newapp.go
  pkg/oc/cli/cmd/startbuild.go
  pkg/oc/cli/describe/deployments.go
  pkg/oc/cli/util/clientcmd/factory.go
  pkg/oc/cli/util/clientcmd/factory_builder.go
  pkg/oc/cli/util/clientcmd/factory_client_access.go
  pkg/oc/cli/util/clientcmd/factory_object_mapping.go
  pkg/oc/experimental/buildchain/buildchain.go
  pkg/oc/generate/app/pipeline.go
  pkg/oc/graph/kubegraph/edges.go
  pkg/project/admission/requestlimit/admission.go
  pkg/project/apis/project/register.go
  pkg/quota/apis/quota/register.go
  pkg/route/apis/route/register.go
  pkg/scheduler/admission/podnodeconstraints/admission_test.go
  pkg/security/apis/security/register.go
  pkg/template/apis/template/register.go
  pkg/template/controller/readiness.go
  pkg/template/controller/readiness_test.go
  pkg/template/registry/template/rest_test.go
  pkg/templateservicebroker/servicebroker/bind.go
  pkg/user/apis/user/register.go
  test/integration/authorization_test.go
Labels: approved, lgtm, size/L

#19677 update external examples
  examples/image-streams/image-streams-centos7.json
  examples/image-streams/image-streams-rhel7.json
  pkg/oc/bootstrap/bindata.go
  test/extended/testdata/bindata.go
Labels: approved, lgtm, size/S

#19687 image: use deletion handling metanamespace key in import scheduler
  pkg/image/controller/scheduled_image_controller.go
Labels: approved, lgtm, size/S

#19689 update publishing rules for 1.10.2
  publishing-kube-rules.yaml
  publishing-rules.yaml
Labels: approved, lgtm, size/M

#19694 Remove old service dependencies from node system container
  images/node/system-container/manifest.json
  images/node/system-container/service.template
Labels: approved, lgtm, size/XS

#19697 Add git to the test image for build tests
  images/tests/Dockerfile
Labels: approved, lgtm, size/XS

#19674 up: use YAML instead of JSON for configs
  pkg/oc/bootstrap/clusterup/kubeapiserver/openshift_apiserver.go
  pkg/oc/bootstrap/clusterup/kubeapiserver/openshift_controller.go
  pkg/oc/bootstrap/clusterup/kubelet/dns.go
Labels: approved, lgtm, size/XS

#19691 Parallelize storage migration
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/oc/admin/migrate/images/imagerefs.go
  pkg/oc/admin/migrate/legacyhpa/hpa.go
  pkg/oc/admin/migrate/migrator.go
  pkg/oc/admin/migrate/migrator_test.go
  pkg/oc/admin/migrate/storage/storage.go
  pkg/oc/admin/migrate/storage/storage_test.go
  pkg/oc/admin/migrate/templateinstances/templateinstances.go
  test/cmd/migrate.sh
Labels: approved, kind/bug, lgtm, sig/security, size/XL

#19675 up: add pull policy to context and pass it properly to cluster add
  pkg/oc/bootstrap/docker/run_self_hosted.go
  pkg/oc/bootstrap/docker/up.go
Labels: approved, lgtm, needs-rebase, size/S

#19686 apps: use api calls when creating dc in extended tests
  test/extended/deployments/deployments.go
  test/extended/deployments/util.go
  test/extended/testdata/bindata.go
  test/extended/testdata/deployments/custom-deployment.yaml
  test/extended/testdata/deployments/deployment-example.yaml
  test/extended/testdata/deployments/deployment-history-limit.yaml
  test/extended/testdata/deployments/deployment-ignores-deployer.yaml
  test/extended/testdata/deployments/deployment-image-resolution-is.yaml
  test/extended/testdata/deployments/deployment-image-resolution.yaml
  test/extended/testdata/deployments/deployment-min-ready-seconds.yaml
  test/extended/testdata/deployments/deployment-simple.yaml
  test/extended/testdata/deployments/deployment-trigger.yaml
  test/extended/testdata/deployments/deployment-with-ref-env.yaml
  test/extended/testdata/deployments/failing-pre-hook.yaml
  test/extended/testdata/deployments/generation-test.yaml
  test/extended/testdata/deployments/multi-ict-deployment.yaml
  test/extended/testdata/deployments/paused-deployment.yaml
  test/extended/testdata/deployments/readiness-test.yaml
  test/extended/testdata/deployments/tag-images-deployment.yaml
  test/extended/testdata/deployments/test-deployment-broken.yaml
  test/extended/testdata/deployments/test-deployment-test.yaml
Labels: approved, lgtm, size/XXL

#19683 Rip policy ojects
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/api/install/install.go
  pkg/api/legacy/apigroups.go
  pkg/api/serialization_test.go
  pkg/api/validation/register.go
  pkg/api/validation/validation_test.go
  pkg/authorization/apis/authorization/casts.go
  pkg/authorization/apis/authorization/fields.go
  pkg/authorization/apis/authorization/helpers.go
  pkg/authorization/apis/authorization/install/install.go
  pkg/authorization/apis/authorization/register.go
  pkg/authorization/apis/authorization/types.go
  pkg/authorization/apis/authorization/v1/conversion.go
  pkg/authorization/apis/authorization/v1/conversion_test.go
  pkg/authorization/apis/authorization/v1/register.go
  pkg/authorization/apis/authorization/v1/zz_generated.conversion.go
  pkg/authorization/apis/authorization/validation/validation.go
  pkg/authorization/apis/authorization/validation/validation_test.go
  pkg/authorization/apis/authorization/zz_generated.deepcopy.go
  pkg/authorization/generated/informers/internalversion/authorization/internalversion/clusterpolicy.go
  pkg/authorization/generated/informers/internalversion/authorization/internalversion/clusterpolicybinding.go
  pkg/authorization/generated/informers/internalversion/authorization/internalversion/interface.go
  pkg/authorization/generated/informers/internalversion/authorization/internalversion/policy.go
  pkg/authorization/generated/informers/internalversion/authorization/internalversion/policybinding.go
  pkg/authorization/generated/informers/internalversion/generic.go
  pkg/authorization/generated/internalclientset/typed/authorization/internalversion/authorization_client.go
  pkg/authorization/generated/internalclientset/typed/authorization/internalversion/clusterpolicy.go
  pkg/authorization/generated/internalclientset/typed/authorization/internalversion/clusterpolicybinding.go
  pkg/authorization/generated/internalclientset/typed/authorization/internalversion/fake/fake_authorization_client.go
  pkg/authorization/generated/internalclientset/typed/authorization/internalversion/fake/fake_clusterpolicy.go
  pkg/authorization/generated/internalclientset/typed/authorization/internalversion/fake/fake_clusterpolicybinding.go
  pkg/authorization/generated/internalclientset/typed/authorization/internalversion/fake/fake_policy.go
  pkg/authorization/generated/internalclientset/typed/authorization/internalversion/fake/fake_policybinding.go
  pkg/authorization/generated/internalclientset/typed/authorization/internalversion/generated_expansion.go
  pkg/authorization/generated/internalclientset/typed/authorization/internalversion/policy.go
  pkg/authorization/generated/internalclientset/typed/authorization/internalversion/policybinding.go
  pkg/authorization/generated/listers/authorization/internalversion/clusterpolicy.go
  pkg/authorization/generated/listers/authorization/internalversion/clusterpolicybinding.go
  pkg/authorization/generated/listers/authorization/internalversion/expansion_generated.go
  pkg/authorization/generated/listers/authorization/internalversion/policy.go
  pkg/authorization/generated/listers/authorization/internalversion/policybinding.go
  pkg/authorization/rulevalidation/find_rules.go
  pkg/authorization/rulevalidation/policy_comparator_test.go
  pkg/oc/cli/describe/describer.go
  pkg/oc/cli/describe/printer.go
  test/integration/authorization_test.go
Labels: approved, lgtm, size/XXL

#19432 router - depricate -expose-metrics --metrics-image
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/oc/admin/router/router.go
Labels: approved, component/routing, lgtm, size/S

#19698 Set git configuration for test image
  images/tests/Dockerfile
Labels: approved, lgtm, size/XS

#19702 switch to using vendored version of SSCS and library-go
  glide.lock
  glide.yaml
  hack/import-restrictions.json
  pkg/cmd/infra/router/template.go
  pkg/cmd/openshift-controller-manager/controller/service.go
  pkg/cmd/openshift-controller-manager/controller/standalone_apiserver.go
  pkg/cmd/server/admin/create_client.go
  pkg/cmd/server/admin/create_clientcert.go
  pkg/cmd/server/admin/create_kubeconfig.go
  pkg/cmd/server/admin/create_mastercerts.go
  pkg/cmd/server/admin/create_nodeconfig.go
  pkg/cmd/server/admin/create_servercert.go
  pkg/cmd/server/admin/create_signercert.go
  pkg/cmd/server/admin/signer_cert_args.go
  pkg/cmd/server/apis/config/validation/validation.go
  pkg/cmd/server/kubernetes/master/master_config.go
  pkg/cmd/server/kubernetes/node/options/options.go
  pkg/cmd/server/origin/oauth_apiserver_adapter.go
  pkg/cmd/server/start/start_allinone.go
  pkg/cmd/server/start/start_master.go
  pkg/cmd/server/start/start_node.go
  pkg/controller/OWNERS
  pkg/controller/doc.go
  test/integration/front_proxy_test.go
  test/integration/node_authorizer_test.go
  test/integration/oauth_basicauth_test.go
  test/integration/service_serving_cert_signer_test.go
  test/integration/tls_test.go
  test/util/server/server.go
  vendor/github.com/openshift/library-go/.gitignore
  vendor/github.com/openshift/library-go/.travis.yml
  vendor/github.com/openshift/library-go/LICENSE
  vendor/github.com/openshift/library-go/Makefile
  vendor/github.com/openshift/library-go/OWNERS
  vendor/github.com/openshift/library-go/README.md
  vendor/github.com/openshift/library-go/glide.lock
  vendor/github.com/openshift/library-go/glide.yaml
  vendor/github.com/openshift/library-go/hack/update-deps.sh
  vendor/github.com/openshift/library-go/pkg/controller/ownerref.go
  vendor/github.com/openshift/library-go/pkg/controller/ownerref_test.go
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/github.com/openshift/library-go/pkg/crypto/crypto_test.go
  vendor/github.com/openshift/service-serving-cert-signer/.gitignore
  vendor/github.com/openshift/service-serving-cert-signer/.travis.yml
  vendor/github.com/openshift/service-serving-cert-signer/LICENSE
  vendor/github.com/openshift/service-serving-cert-signer/Makefile
  vendor/github.com/openshift/service-serving-cert-signer/OWNERS
  vendor/github.com/openshift/service-serving-cert-signer/README.md
  vendor/github.com/openshift/service-serving-cert-signer/glide.lock
  vendor/github.com/openshift/service-serving-cert-signer/glide.yaml
  vendor/github.com/openshift/service-serving-cert-signer/hack/update-deps.sh
  vendor/github.com/openshift/service-serving-cert-signer/pkg/controller/servingcert/cryptoextensions/doc.go
  vendor/github.com/openshift/service-serving-cert-signer/pkg/controller/servingcert/cryptoextensions/extensions.go
  vendor/github.com/openshift/service-serving-cert-signer/pkg/controller/servingcert/cryptoextensions/serversigning.go
  vendor/github.com/openshift/service-serving-cert-signer/pkg/controller/servingcert/secret_creating_controller.go
  vendor/github.com/openshift/service-serving-cert-signer/pkg/controller/servingcert/secret_creating_controller_test.go
  vendor/github.com/openshift/service-serving-cert-signer/pkg/controller/servingcert/secret_updating_controller.go
  vendor/github.com/openshift/service-serving-cert-signer/pkg/controller/servingcert/secret_updating_controller_test.go
Labels: approved, lgtm, size/XXL

#19533 UPSTREAM: <carry>: XFS quota for emptyDir volumes
  pkg/cmd/server/kubernetes/node/node.go
  pkg/cmd/server/start/start_node.go
  test/extended/localquota/local_fsgroup_quota.go
  vendor/k8s.io/kubernetes/cmd/kubelet/app/patch_volumequota.go
  vendor/k8s.io/kubernetes/cmd/kubelet/app/patch_volumes.go
  vendor/k8s.io/kubernetes/cmd/kubelet/app/plugins.go
  vendor/k8s.io/kubernetes/cmd/kubelet/app/server.go
  vendor/k8s.io/kubernetes/pkg/volume/emptydirquota/empty_dir_quota.go
  vendor/k8s.io/kubernetes/pkg/volume/emptydirquota/quota.go
  vendor/k8s.io/kubernetes/pkg/volume/emptydirquota/quota_test.go
Labels: approved, lgtm, size/L

#19710 skip publishing BUILD files to forks
  publishing-kube-rules.yaml
Labels: approved, lgtm, size/XS

#19714 UPSTREAM: 63848: Deflake discovery timeout test
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/discovery/discovery_client_test.go
Labels: approved, lgtm, size/S

#19712 Fix incorrect oc run default option
  pkg/oc/cli/cmd/wrappers.go
Labels: approved, lgtm, size/XS

#19723 UPSTREAM: 63875: make TestGetServerGroupsWithTimeout more reliable
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/discovery/discovery_client_test.go
Labels: approved, size/S

#19725 Remove --extended-test-output-dir and use --report-dir in e2e
  test/extended/builds/contextdir.go
  test/extended/builds/docker_pullsecret.go
  test/extended/builds/docker_quota.go
  test/extended/builds/dockerfile.go
  test/extended/builds/gitauth.go
  test/extended/builds/labels.go
  test/extended/builds/long_names.go
  test/extended/builds/multistage.go
  test/extended/builds/no_outputname.go
  test/extended/builds/optimized.go
  test/extended/builds/s2i_env.go
  test/extended/builds/s2i_incremental.go
  test/extended/builds/s2i_quota.go
  test/extended/builds/secrets.go
  test/extended/cli/rsync.go
  test/extended/image_ecosystem/mariadb_ephemeral.go
  test/extended/image_ecosystem/mongodb_replica_statefulset.go
  test/extended/image_ecosystem/mysql_ephemeral.go
  test/extended/image_ecosystem/mysql_replica.go
  test/extended/image_ecosystem/postgresql_replica.go
  test/extended/image_ecosystem/s2i_perl.go
  test/extended/image_ecosystem/s2i_php.go
  test/extended/image_ecosystem/s2i_python.go
  test/extended/image_ecosystem/s2i_ruby.go
  test/extended/image_ecosystem/sample_repos.go
  test/extended/imageapis/limitrange_admission.go
  test/extended/imageapis/quota_admission.go
  test/extended/images/hardprune.go
  test/extended/images/prune.go
  test/extended/jobs/jobs.go
  test/extended/localquota/local_fsgroup_quota.go
  test/extended/router/headers.go
  test/extended/router/scoped.go
  test/extended/router/unprivileged.go
  test/extended/router/weighted.go
  test/extended/util/cli.go
  test/extended/util/test.go
Labels: approved, lgtm, size/M

#19711 RIP Policy Objects - Part 2
  api/protobuf-spec/github_com_openshift_api_authorization_v1.proto
  api/protobuf-spec/github_com_openshift_api_config_v1.proto
  api/protobuf-spec/github_com_openshift_api_webconsole_v1.proto
  glide.lock
  pkg/authorization/apis/authorization/v1/zz_generated.defaults.go
  pkg/cmd/openshift-operators/webconsole-operator/config_v1.go
  pkg/cmd/server/origin/legacy.go
  pkg/openapi/zz_generated.openapi.go
  test/integration/etcd_storage_path_test.go
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/authorization/v1/codec.go
  vendor/github.com/openshift/api/authorization/v1/generated.pb.go
  vendor/github.com/openshift/api/authorization/v1/generated.proto
  vendor/github.com/openshift/api/authorization/v1/register.go
  vendor/github.com/openshift/api/authorization/v1/types.go
  vendor/github.com/openshift/api/authorization/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/authorization/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/doc.go
  vendor/github.com/openshift/api/config/v1/generated.pb.go
  vendor/github.com/openshift/api/config/v1/generated.proto
  vendor/github.com/openshift/api/config/v1/register.go
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/hack/lib/init.sh
  vendor/github.com/openshift/api/hack/update-deepcopy.sh
  vendor/github.com/openshift/api/webconsole/v1/generated.pb.go
  vendor/github.com/openshift/api/webconsole/v1/generated.proto
  vendor/github.com/openshift/api/webconsole/v1/types.go
  vendor/github.com/openshift/api/webconsole/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/webconsole/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/client-go/authorization/clientset/versioned/typed/authorization/v1/authorization_client.go
  vendor/github.com/openshift/client-go/authorization/clientset/versioned/typed/authorization/v1/clusterpolicy.go
  vendor/github.com/openshift/client-go/authorization/clientset/versioned/typed/authorization/v1/clusterpolicybinding.go
  vendor/github.com/openshift/client-go/authorization/clientset/versioned/typed/authorization/v1/fake/fake_authorization_client.go
  vendor/github.com/openshift/client-go/authorization/clientset/versioned/typed/authorization/v1/fake/fake_clusterpolicy.go
  vendor/github.com/openshift/client-go/authorization/clientset/versioned/typed/authorization/v1/fake/fake_clusterpolicybinding.go
  vendor/github.com/openshift/client-go/authorization/clientset/versioned/typed/authorization/v1/fake/fake_policy.go
  vendor/github.com/openshift/client-go/authorization/clientset/versioned/typed/authorization/v1/fake/fake_policybinding.go
  vendor/github.com/openshift/client-go/authorization/clientset/versioned/typed/authorization/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/authorization/clientset/versioned/typed/authorization/v1/policy.go
  vendor/github.com/openshift/client-go/authorization/clientset/versioned/typed/authorization/v1/policybinding.go
  vendor/github.com/openshift/client-go/authorization/informers/externalversions/authorization/v1/clusterpolicy.go
  vendor/github.com/openshift/client-go/authorization/informers/externalversions/authorization/v1/clusterpolicybinding.go
  vendor/github.com/openshift/client-go/authorization/informers/externalversions/authorization/v1/interface.go
  vendor/github.com/openshift/client-go/authorization/informers/externalversions/authorization/v1/policy.go
  vendor/github.com/openshift/client-go/authorization/informers/externalversions/authorization/v1/policybinding.go
  vendor/github.com/openshift/client-go/authorization/informers/externalversions/generic.go
  vendor/github.com/openshift/client-go/authorization/listers/authorization/v1/clusterpolicy.go
  vendor/github.com/openshift/client-go/authorization/listers/authorization/v1/clusterpolicybinding.go
  vendor/github.com/openshift/client-go/authorization/listers/authorization/v1/expansion_generated.go
  vendor/github.com/openshift/client-go/authorization/listers/authorization/v1/policy.go
  vendor/github.com/openshift/client-go/authorization/listers/authorization/v1/policybinding.go
  vendor/github.com/openshift/client-go/glide.lock
Labels: approved, lgtm, size/XXL

#19409 Add --enable=automation-service-broker
  install/automationservicebroker/install-rbac.yaml
  install/automationservicebroker/install.yaml
  pkg/oc/bootstrap/bindata.go
  pkg/oc/bootstrap/clusteradd/cmd.go
  pkg/oc/bootstrap/clusteradd/components/automation-service-broker/OWNERS
  pkg/oc/bootstrap/clusteradd/components/automation-service-broker/automation_service_broker.go
  pkg/oc/bootstrap/docker/up.go
  test/extended/testdata/bindata.go
Labels: approved, lgtm, size/L

#19692 remove internal openshift refs from oauthserver
  hack/import-restrictions.json
  pkg/oauthserver/userregistry/identitymapper/lookup_test.go
  pkg/oauthserver/userregistry/identitymapper/provision_test.go
  pkg/oauthserver/userregistry/identitymapper/strategy_add_test.go
  pkg/oauthserver/userregistry/identitymapper/strategy_claim_test.go
  pkg/oauthserver/userregistry/identitymapper/strategy_generate_test.go
  pkg/oauthserver/userregistry/identitymapper/strategy_test.go
Labels: approved, lgtm, sig/security, size/XL

#19688 oc new-app: allow 'dot' in ENV variable names
  pkg/oc/generate/app/env.go
  pkg/oc/util/env/env.go
  test/cmd/env.sh
  test/cmd/images.sh
Labels: approved, component/cli, lgtm, sig/developer-experience, size/M

#19709 unwind the version packages
  pkg/build/controller/strategy/util.go
  pkg/cmd/openshift/openshift.go
  pkg/cmd/util/variable/variable.go
  pkg/cmd/util/variable/variable_test.go
  pkg/cmd/version/version.go
  pkg/oc/admin/prune/images.go
  pkg/oc/admin/prune/images_test.go
  pkg/oc/cli/cmd/version.go
  pkg/version/openshift/version.go
  pkg/version/version.go
  test/cmd/basicresources.sh
Labels: approved, lgtm, sig/master, size/L

#19722 allow cluster up to produce a non-openshift cluster
  pkg/oc/bootstrap/docker/run_self_hosted.go
  pkg/oc/bootstrap/docker/up.go
Labels: approved, lgtm, size/S

#19730 Restore pre-1.10 openstack cloud provider node name behavior
  vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/openstack/metadata.go
  vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/openstack/metadata_test.go
  vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/openstack/openstack.go
  vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/openstack/openstack_instances.go
Labels: approved, lgtm, size/S

#19731 The kube major/minor version is missing from /version in 3.9
  hack/lib/constants.sh
  test/cmd/newapp.sh
  test/extended/router/headers.go
  test/extended/util/framework.go
Labels: approved, size/S

#19553 Move image stream tag and image columns to -o wide
  pkg/oc/cli/describe/printer.go
Labels: approved, lgtm, size/M

#19733 UPSTREAM: 62543: Timeout on instances.NodeAddresses cloud provider request
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_node_status.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_node_status_test.go
Labels: approved, lgtm, size/M

#19734 openshift-node-config: resolve cluster-ip when 0.0.0.0 is specified
  cmd/openshift-node-config/openshift-node-config.go
  pkg/cmd/server/origin/node/node.go
  pkg/cmd/server/start/start_node.go
Labels: approved, lgtm, sig/pod, size/M

#19737 stop adding controller version to build pod
  pkg/build/apis/build/types.go
  pkg/build/builder/cmd/builder.go
  pkg/build/builder/util/consts.go
  pkg/build/controller/strategy/custom.go
  pkg/build/controller/strategy/custom_test.go
  pkg/build/controller/strategy/docker.go
  pkg/build/controller/strategy/docker_test.go
  pkg/build/controller/strategy/sti.go
  pkg/build/controller/strategy/sti_test.go
  pkg/build/controller/strategy/util.go
Labels: approved, lgtm, size/M

#19738 Remove jpeeler from cmd/OWNERS
  cmd/OWNERS
Labels: approved, lgtm, size/XS

#19741 plumb the values for the webconsole to the operator
  hack/import-restrictions.json
  pkg/cmd/openshift-operators/util/resourceapply/core.go
  pkg/cmd/openshift-operators/util/resourceapply/core_test.go
  pkg/oc/bootstrap/clusteradd/components/web-console-operator/web_console_operator.go
  pkg/oc/bootstrap/clusteradd/components/web-console/OWNERS
  pkg/oc/bootstrap/clusteradd/components/web-console/web_console.go
Labels: approved, lgtm, size/L

#19732 up: fix tsb image template parameter
  pkg/oc/bootstrap/clusteradd/components/template-service-broker/template_service_broker.go
Labels: approved, lgtm, size/XS

#19318 Allow Prometheus to get metrics from the router
  pkg/cmd/server/bootstrappolicy/policy.go
  pkg/oc/admin/router/router.go
  test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml
  test/testdata/bootstrappolicy/bootstrap_policy_file.yaml
Labels: approved, lgtm, size/S

#19747 UPSTREAM: 63966: kubectl: fix Flatten() when used without Latest()
  vendor/k8s.io/kubernetes/pkg/kubectl/resource/builder.go
Labels: approved, lgtm, sig/master, size/XS

#19750 snip dependencies in a future library-go package
  pkg/serviceaccounts/oauthclient/oauthclientregistry.go
  pkg/serviceaccounts/oauthclient/oauthclientregistry_test.go
Labels: approved, lgtm, sig/security, size/M

#19749 Add legacy rbac endpoint integration tests
  test/integration/authorization_test.go
Labels: approved, lgtm, sig/security, size/XL

#19706 Make router conflict detection work even during initial informer sync
  pkg/cmd/infra/router/f5.go
  pkg/cmd/infra/router/template.go
  pkg/router/controller/contention.go
  pkg/router/controller/router_controller.go
  pkg/router/controller/status.go
  pkg/router/controller/status_test.go
  test/extended/router/stress.go
  test/integration/router_without_haproxy_test.go
Labels: approved, lgtm, size/XL

#19662 images: remove duplicate packages
  images/node/Dockerfile
Labels: approved, component/image, lgtm, size/XS

#19752 Set the default kubeconfig when empty
  hack/dind-cluster.sh
Labels: approved, lgtm, size/M

#19772 Ignore node created self targeting mirror pods in PodNodeConstraints
  pkg/scheduler/admission/podnodeconstraints/admission.go
  pkg/scheduler/admission/podnodeconstraints/admission_test.go
Labels: approved, kind/bug, lgtm, sig/master, sig/security, size/M

#19773 UPSTREAM: <carry>: change config file location and restore perFSGroup to Quantity
  vendor/k8s.io/kubernetes/cmd/kubelet/app/patch_volumequota.go
Labels: approved, kind/bug, lgtm, size/S

#19757 catalog: start controller with --cluster-id-configmap-namespace
  examples/service-catalog/service-catalog.yaml
  pkg/oc/clusterup/manifests/bindata.go
Labels: approved, lgtm, size/XS

#19774 UPSTREAM: 63977: pkg: kubelet: remote: increase grpc client default size
  vendor/k8s.io/kubernetes/pkg/kubelet/remote/remote_image.go
  vendor/k8s.io/kubernetes/pkg/kubelet/remote/remote_runtime.go
  vendor/k8s.io/kubernetes/pkg/kubelet/remote/utils.go
Labels: approved, lgtm, size/XS

#19787 Initialize defaultImageStreams
  hack/lib/constants.sh
Labels: approved, lgtm, queue/blocks-others, queue/critical-fix, size/XS

#19770 UPSTREAM: 63416: Retry certificate approval on conflict errors
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/certificates.go
Labels: approved, lgtm, size/S

#19765 UPSTREAM: 64028: Tolarate negative values when calculating job scale progress
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/scalejob/scalejob.go
Labels: approved, lgtm, size/XS

#19581 Remove deprecated envvar-based credential support from images
  pkg/cmd/infra/router/clientcmd.go
  pkg/cmd/infra/router/f5.go
  pkg/cmd/infra/router/template.go
  pkg/cmd/openshift-controller-manager/controller/apps.go
  pkg/cmd/openshift/openshift_test.go
Labels: approved, lgtm, size/L

#19645 CL skip config write by default
  test/extended/cluster/cl.go
Labels: approved, lgtm, size/XS

#19756 Update bootstrap policy file encoding
  pkg/cmd/server/admin/create_bootstrappolicy_file.go
  pkg/cmd/server/bootstrappolicy/policy_test.go
  test/testdata/bootstrappolicy/bootstrap_policy_file.yaml
Labels: approved, lgtm, sig/security, size/XXL

#19776 switch over to k8s nfs image extension for image_eco, build extended …
  test/extended/builds/pipeline.go
  test/extended/image_ecosystem/mongodb_replica_statefulset.go
  test/extended/image_ecosystem/mysql_replica.go
  test/extended/image_ecosystem/postgresql_replica.go
  test/extended/util/nfs.go
  test/extended/util/volumes.go
Labels: approved, lgtm, sig/developer-experience, size/XL

#19778 Remove unnecessary output files
  test/extended/builds/no_outputname.go
  test/extended/idling/idling.go
  test/extended/util/cli.go
Labels: approved, lgtm, size/XS

#19801 Added namespaces to log messages in the hybid proxy
  pkg/proxy/hybrid/proxy.go
Labels: approved, kind/bug, lgtm, size/M

#19009 Differentiate liveness and readiness probes for router pods
  pkg/cmd/infra/router/template.go
  pkg/oc/admin/router/router.go
  pkg/router/metrics/health.go
  pkg/router/metrics/metrics.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/healthz/healthz.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/healthz/healthz_test.go
Labels: approved, component/routing, kind/bug, lgtm, size/L

#19810 Generate temporary test user kubeconfig into temp
  test/extended/util/cli.go
Labels: approved, size/XS

#19754 Remove containerized openshift handling in network diagnostics
  pkg/oc/admin/diagnostics/diagnostics/cluster/network/objects.go
Labels: approved, component/diagnostics, lgtm, size/M

#19695 Retrying when attempting to stream build logs
  pkg/build/registry/buildlog/rest.go
  pkg/oc/cli/cmd/startbuild.go
  pkg/oc/cli/cmd/startbuild_test.go
  test/extended/gssapi.sh
  test/extended/ldap_groups.sh
Labels: approved, lgtm, size/L

#19713 support dns resolution
  images/dind/node/openshift-generate-node-config.sh
Labels: approved, lgtm, size/XS

#19795 Cleanup prune groups command to align with other commands
  pkg/oc/admin/groups/sync/cli/prune.go
Labels: approved, lgtm, size/S

#19807 move cakephp ext test count check to greater than zero
  test/extended/image_ecosystem/helper.go
  test/extended/image_ecosystem/s2i_php.go
Labels: approved, lgtm, sig/developer-experience, size/M

#19812 Add test to dependency graph
  hack/lib/constants.sh
Labels: approved, lgtm, size/XS

#19788 sa: make docker registry service controller check all secrets
  pkg/serviceaccounts/controllers/docker_registry_service.go
  pkg/serviceaccounts/controllers/docker_registry_service_test.go
Labels: approved, lgtm, size/M

#19763 apps: add sleep to test hook fixture so logs can catch up
  test/extended/testdata/bindata.go
  test/extended/testdata/deployments/test-deployment-test.yaml
Labels: approved, lgtm, size/S

#19808 Fix TSB Registration
  pkg/oc/clusteradd/components/template-service-broker/template_service_broker.go
Labels: approved, lgtm, size/XS

#19822 ensure nothing in kubernetes depends on origin
  hack/verify-imports.sh
Labels: approved, lgtm, size/XS

#19805 Use dns go bindings instead of dig command for dns resolution in egress network policy
  images/node/Dockerfile
  origin.spec
  pkg/network/common/dns.go
  pkg/network/common/dns_test.go
  pkg/network/common/egress_dns.go
  pkg/network/node/ovscontroller.go
  pkg/network/proxy/proxy.go
Labels: approved, component/networking, lgtm, sig/networking, size/L

#19742 UPSTREAM: 63926: Avoid unnecessary calls to the cloud provider
  vendor/k8s.io/kubernetes/pkg/controller/service/service_controller.go
Labels: approved, lgtm, size/XS

#19790 tests: allow `watch` to timeout
  test/common/build/controllers.go
Labels: approved, area/tests, kind/test-flake, lgtm, sig/developer-experience, size/M

#19814 Prune tests panicked when log writer was nil
  test/extended/images/helper.go
  test/extended/util/cli.go
Labels: approved, lgtm, size/S

#19129 HACKING.md: fix/update broken links
  HACKING.md
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#19828 re-enable mysql replica but disable slave restart because of regressi…
  test/extended/image_ecosystem/mysql_replica.go
Labels: approved, lgtm, sig/developer-experience, size/S

#19835 enable rerunning cluster add automation-service-broker
  pkg/oc/clusteradd/components/automation-service-broker/automation_service_broker.go
Labels: approved, lgtm, size/XS

#19826 UPSTREAM: opencontainers/runc: 1805: fix systemd cpu quota for -1
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/apply_systemd.go
Labels: approved, lgtm, size/S

#19829 Default config no longer sets a whitelist
  pkg/cmd/server/apis/config/types.go
  pkg/cmd/server/start/master_args.go
  test/integration/imageimporter_test.go
  test/util/server/server.go
Labels: approved, lgtm, size/M

#19802 UPSTREAM: 61459: etcd client add dial timeout
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3.go
Labels: approved, lgtm, size/XS

#19853 Revert "UPSTREAM: 61459: etcd client add dial timeout"
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3.go
Labels: approved, queue/critical-fix, retest-not-required, size/XS

#19846 Prevent rolebinding deletion if it is protected
  pkg/oc/admin/policy/modify_roles.go
  pkg/oc/admin/policy/modify_roles_test.go
Labels: approved, lgtm, size/S

#19855 Fix Idling extended test resource name for DC
  test/extended/idling/idling.go
Labels: approved, lgtm, size/XS

#19764 Various storage migration bug fixes
  pkg/oc/admin/migrate/migrator.go
  pkg/oc/admin/migrate/migrator_test.go
  pkg/oc/admin/migrate/storage/storage.go
Labels: approved, kind/bug, lgtm, size/L

#19842 UPSTREAM: 60632: Add volumemetrics for ISCSI Plugin
  vendor/k8s.io/kubernetes/pkg/volume/iscsi/iscsi.go
Labels: approved, lgtm, size/S

#19816 CSI fixes
  vendor/k8s.io/kubernetes/pkg/kubelet/cm/container_manager_linux_test.go
  vendor/k8s.io/kubernetes/pkg/util/mount/exec_mount.go
  vendor/k8s.io/kubernetes/pkg/util/mount/exec_mount_test.go
  vendor/k8s.io/kubernetes/pkg/util/mount/exec_mount_unsupported.go
  vendor/k8s.io/kubernetes/pkg/util/mount/fake.go
  vendor/k8s.io/kubernetes/pkg/util/mount/mount.go
  vendor/k8s.io/kubernetes/pkg/util/mount/mount_linux.go
  vendor/k8s.io/kubernetes/pkg/util/mount/mount_linux_test.go
  vendor/k8s.io/kubernetes/pkg/util/mount/mount_unsupported.go
  vendor/k8s.io/kubernetes/pkg/util/mount/mount_windows.go
  vendor/k8s.io/kubernetes/pkg/util/mount/nsenter_mount.go
  vendor/k8s.io/kubernetes/pkg/util/mount/nsenter_mount_unsupported.go
  vendor/k8s.io/kubernetes/pkg/util/removeall/removeall_test.go
  vendor/k8s.io/kubernetes/pkg/volume/csi/BUILD
  vendor/k8s.io/kubernetes/pkg/volume/csi/csi_attacher.go
  vendor/k8s.io/kubernetes/pkg/volume/csi/csi_attacher_test.go
  vendor/k8s.io/kubernetes/pkg/volume/csi/csi_mounter.go
  vendor/k8s.io/kubernetes/pkg/volume/host_path/host_path_test.go
  vendor/k8s.io/kubernetes/pkg/volume/volume.go
Labels: approved, lgtm, size/L

#19845 Allow local provisioner see new mounts.
  examples/storage-examples/local-examples/local-storage-provisioner-template.yaml
Labels: approved, lgtm, size/XS

#19854 set the dns suffix for docker config secrets
  pkg/cmd/openshift-controller-manager/controller/serviceaccount.go
  pkg/serviceaccounts/controllers/docker_registry_service.go
  pkg/serviceaccounts/controllers/docker_registry_service_test.go
Labels: approved, lgtm, size/S

#19866 UPSTREAM: 64443: services must listen on port 443 for aggregation
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/controllers/status/available_controller.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/controllers/status/available_controller_test.go
Labels: approved, lgtm, size/M

#19824 Add an event poll for TestOAuthServiceAccountClientEvent
  test/integration/oauth_serviceaccount_client_events_test.go
Labels: approved, kind/test-flake, lgtm, sig/security, size/S

#19838 add internal and external URL handling for the docker pull secret
  pkg/cmd/openshift-controller-manager/controller/serviceaccount.go
  pkg/cmd/openshift-controller-manager/conversion.go
  pkg/cmd/server/apis/config/types.go
  pkg/cmd/server/apis/config/zz_generated.deepcopy.go
  pkg/serviceaccounts/controllers/create_dockercfg_secrets.go
  pkg/serviceaccounts/controllers/deleted_dockercfg_secrets.go
  pkg/serviceaccounts/controllers/deleted_token_secrets.go
  pkg/serviceaccounts/controllers/docker_registry_service.go
  pkg/serviceaccounts/controllers/docker_registry_service_test.go
  test/integration/service_account_test.go
Labels: approved, lgtm, size/L

#19875 up: remove support for remote docker host
  pkg/oc/clusteradd/components/registry/registry_install.go
  pkg/oc/clusteradd/components/router/router_install.go
  pkg/oc/clusterup/coreinstall/components/persistent-volumes/setup_persistent_volumes.go
  pkg/oc/clusterup/docker/host/host.go
  pkg/oc/clusterup/run_self_hosted.go
  pkg/oc/clusterup/up.go
Labels: approved, lgtm, size/L

#16850 Turn off client rate limiting in integration tests
  test/integration/imageimporter_test.go
  test/util/client.go
Labels: approved, lgtm, lifecycle/frozen, size/M

#19886 ovn-k8s-overlay executable is deprecated
  hack/dind-cluster.sh
  images/dind/master/ovn-kubernetes-master-setup.sh
  images/dind/node/ovn-kubernetes-node-setup.sh
Labels: approved, lgtm, size/XS

#19857 UPSTREAM: 62152: Keep node.kubeconfig correct during rotation
  vendor/k8s.io/kubernetes/pkg/kubelet/certificate/bootstrap/BUILD
  vendor/k8s.io/kubernetes/pkg/kubelet/certificate/bootstrap/bootstrap.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/util/cert/io.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/util/certificate/certificate_store.go
Labels: approved, lgtm, size/L

#19884 Expose api-versions and api-resources in oc
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  docs/man/man1/.files_generated_oc
  docs/man/man1/oc-api-resources.1
  docs/man/man1/oc-api-versions.1
  pkg/oc/cli/cli.go
  pkg/oc/cli/cmd/wrappers.go
  pkg/oc/cli/kubectl_compat_test.go
  test/cmd/apiresources.sh
  vendor/k8s.io/kubernetes/docs/.generated_docs
  vendor/k8s.io/kubernetes/docs/man/man1/kubectl-api-resources.1
  vendor/k8s.io/kubernetes/docs/user-guide/kubectl/kubectl_api-resources.md
  vendor/k8s.io/kubernetes/docs/yaml/kubectl/kubectl_api-resources.yaml
  vendor/k8s.io/kubernetes/hack/make-rules/test-cmd-util.sh
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/BUILD
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/apiresources.go
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cmd.go
Labels: approved, lgtm, size/XL

#19847 Drop template wrapping from bootstrap policy file
  pkg/cmd/server/admin/create_bootstrappolicy_file.go
  pkg/cmd/server/bootstrappolicy/policy_test.go
Labels: approved, lgtm, sig/security, size/S

#19885 Allow egress-router to connect to its own node IP, for DNS, etc
  images/egress/router/egress-router.sh
  images/egress/router/egress_router_test.go
  pkg/network/sdn-cni-plugin/openshift-sdn.go
Labels: approved, component/networking, kind/bug, lgtm, sig/networking, size/M

#19888 update fork bump
  glide.lock
  glide.yaml
  vendor/github.com/openshift/api/servicecertsigner/v1alpha1/register.go
  vendor/github.com/openshift/library-go/glide.lock
  vendor/github.com/openshift/library-go/glide.yaml
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcecread/core.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1helpers/helper_test.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1helpers/helpers.go
  vendor/github.com/openshift/library-go/pkg/operator/versioning/compare.go
  vendor/github.com/openshift/library-go/pkg/operator/versioning/compare_test.go
  vendor/github.com/openshift/source-to-image/hack/build-test-images.sh
  vendor/github.com/openshift/source-to-image/hack/test-integration.sh
  vendor/github.com/openshift/source-to-image/pkg/api/describe/describer.go
  vendor/github.com/openshift/source-to-image/pkg/build/strategies/sti/sti.go
  vendor/github.com/openshift/source-to-image/pkg/build/strategies/strategies.go
  vendor/github.com/openshift/source-to-image/pkg/cmd/cli/cmd/rebuild.go
  vendor/github.com/openshift/source-to-image/pkg/docker/util.go
  vendor/github.com/openshift/source-to-image/pkg/docker/util_test.go
  vendor/github.com/openshift/source-to-image/pkg/errors/errors.go
  vendor/github.com/openshift/source-to-image/test/integration/images/sti-fake-assemble-root/Dockerfile
  vendor/github.com/openshift/source-to-image/test/integration/images/sti-fake-assemble-user/Dockerfile
  vendor/github.com/openshift/source-to-image/test/integration/integration_test.go
Labels: approved, lgtm, size/XL

#19890 Fix VRRP check script
  images/ipfailover/keepalived/lib/config-generators.sh
Labels: approved, component/networking, lgtm, sig/networking, size/XS
