Repository openshift/origin, pull requests merged in 2018-09, with the labels that each got.

#20641 Add warnings when bootstrap rolebindings are modified
  pkg/oc/cli/admin/policy/modify_roles.go
  pkg/oc/cli/admin/policy/policy.go
  test/cmd/admin.sh
Labels: approved, lgtm, size/S

#20824 Switch prometheus tests to use cluster monitoring operator
  test/extended/prometheus/prometheus.go
  test/extended/prometheus/prometheus_builds.go
Labels: approved, lgtm, size/M

#20736 git: move to external and lose s2i dep
  pkg/gitserver/autobuild/autobuild.go
  pkg/gitserver/gitserver.go
  pkg/gitserver/initializer.go
  pkg/gitserver/url.go
Labels: approved, lgtm, size/L

#20835 hack/cherry-pick.sh: use dead simple selector for PR merge
  hack/cherry-pick.sh
Labels: approved, lgtm, size/XS

#20772 Make build generator use external clients
  pkg/build/apiserver/apiserver.go
  pkg/build/apiserver/registry/buildclone/rest.go
  pkg/build/apiserver/registry/buildclone/rest_test.go
  pkg/build/apiserver/registry/buildconfiginstantiate/rest.go
  pkg/build/apiserver/registry/buildconfiginstantiate/rest_test.go
  pkg/build/generator/generator.go
  pkg/build/generator/generator_test.go
  pkg/build/generator/test/mocks.go
  pkg/build/generator/testing_client.go
  pkg/image/controller/trigger/image_trigger_controller_test.go
  test/extended/builds/start.go
Labels: approved, lgtm, size/XXL

#20840 If layer is missing, retry the test
  test/extended/images/layers.go
Labels: approved, kind/test-flake, lgtm, size/S

#20839 Master replica can also contend and cause us to exceed our hard limit
  test/extended/router/stress.go
Labels: approved, kind/test-flake, lgtm, size/XS

#20488 Add an experimental set of commands for working with the new 4.0 update payloads
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  docs/man/man1/.files_generated_oc
  docs/man/man1/oc-adm-release-extract.1
  docs/man/man1/oc-adm-release-new.1
  docs/man/man1/oc-adm-release.1
  pkg/image/dockerlayer/add/add.go
  pkg/oc/cli/admin/admin.go
  pkg/oc/cli/admin/release/extract.go
  pkg/oc/cli/admin/release/image_mapper.go
  pkg/oc/cli/admin/release/image_mapper_test.go
  pkg/oc/cli/admin/release/new.go
  pkg/oc/cli/admin/release/release.go
  pkg/oc/cli/admin/release/test/main.go
  pkg/oc/cli/image/append/append.go
  pkg/oc/cli/image/extract/extract.go
  pkg/oc/cli/image/mirror/mirror.go
  test/extended/testdata/bindata.go
  test/extended/testdata/releases/payload-1/etcd-operator/image-references
  test/extended/testdata/releases/payload-1/etcd-operator/manifest.yaml
  test/extended/testdata/releases/payload-1/image-registry/10_image-registry_crd.yaml
  test/extended/testdata/releases/payload-1/image-registry/image-references
  test/extended/testdata/releases/payload-1/image-registry/manifest.yaml
Labels: approved, lgtm, size/XXL

#20843 ImageLayers test should loop until image is missing
  test/extended/images/layers.go
Labels: approved, kind/test-flake, lgtm, size/XS

#20844 Filter out non-participating images from the payload list
  pkg/oc/cli/admin/release/new.go
Labels: approved, lgtm, size/XS

#20688 Fix DNS in oc cluster up for user having DNS on localhost
  pkg/oc/clusterup/coreinstall/kubelet/dns.go
  pkg/oc/clusterup/run_self_hosted.go
Labels: approved, kind/bug, lgtm, priority/P0, priority/P2, sig/network-edge, sig/networking, size/XS

#20849 Fix up logic in TestEgressCIDRAllocationOffline
  pkg/network/common/egressip_test.go
Labels: approved, component/networking, kind/test-flake, lgtm, sig/networking, size/S

#20413 ServiceCatalog: update owners
  examples/service-catalog/OWNERS
Labels: approved, lgtm, size/XS

#20858 Strip permissions when extracting a release, and create the directory
  pkg/oc/cli/admin/release/extract.go
  pkg/oc/cli/image/extract/extract.go
Labels: approved, lgtm, size/S

#20852 Add namespaced servicebrokers, serviceclasses and serviceplans to adm…
  pkg/oc/clusteradd/components/service-catalog/service_catalog.go
Labels: approved, lgtm, size/XS

#20859 Release command should allow a base image to be specified
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/oc/cli/admin/release/new.go
Labels: approved, lgtm, size/S

#20863 Set empty source type after we switched to versioned build client
  pkg/build/generator/generator.go
  test/extended/builds/start.go
Labels: approved, lgtm, size/S

#20855 Mount docker auth config into kubelet
  pkg/oc/clusterup/run_self_hosted.go
Labels: approved, lgtm, size/XS

#20868 cluster up: create the service-ca operator signing secret
  pkg/oc/clusterup/run_self_hosted.go
  pkg/oc/clusterup/signing_secret.go
Labels: approved, lgtm, sig/master, size/M

#20866 UPSTREAM: 67097: Ignore EIO error in unmount path
  vendor/k8s.io/kubernetes/pkg/volume/flexvolume/detacher.go
  vendor/k8s.io/kubernetes/pkg/volume/flexvolume/unmounter.go
  vendor/k8s.io/kubernetes/pkg/volume/util/util.go
Labels: approved, kind/bug, lgtm, size/M

#20608 UPSTREAM: 66397: Update scheduler to use different limits for m5/c5
  vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/predicates/predicates.go
  vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/predicates/predicates_test.go
Labels: approved, lgtm, sig/storage, size/M

#20847 Externalize oc tag
  pkg/image/util/helpers.go
  pkg/oc/cli/tag/tag.go
  pkg/oc/cli/tag/tag_test.go
Labels: approved, lgtm, size/L

#20856 UPSTREAM: 68009: apiserver: forward panic in WithTimeout filter
  hack/cherry-pick.sh
  vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/azure/azure_loadbalancer.go
  vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/azure/azure_wrap.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/filters/BUILD
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/filters/timeout.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/filters/timeout_test.go
Labels: approved, lgtm, size/M

#20873 Router metrics change to use http1 cockroach db matcher
  pkg/router/metrics/metrics.go
Labels: approved, lgtm, sig/network-edge, size/XS

#20877 Print better debug info about release creation
  pkg/oc/cli/admin/release/extract.go
  pkg/oc/cli/admin/release/new.go
  pkg/oc/cli/admin/release/release.go
  pkg/oc/cli/image/append/append.go
  test/extended/images/append.go
Labels: approved, lgtm, size/L

#20890 hack: add kubectl to release tars and zip
  hack/lib/constants.sh
  origin.spec
Labels: approved, lgtm, size/XS

#20896 switch oc scheme installation to avoid installing custom resources for apply
  cmd/oc/oc.go
Labels: approved, cherrypick-approved, lgtm, size/M

#20743 admission: split plugins into validating-only and mutating+validating
  pkg/admission/namespaceconditions/labelcondition.go
  pkg/admission/namespaceconditions/namecondition.go
  pkg/authorization/apiserver/admission/restrictusers/restrictusers.go
  pkg/authorization/apiserver/admission/restrictusers/restrictusers_test.go
  pkg/build/apiserver/admission/jenkinsbootstrapper/admission.go
  pkg/build/apiserver/admission/jenkinsbootstrapper/admission_test.go
  pkg/build/apiserver/admission/secretinjector/admission.go
  pkg/build/apiserver/admission/strategyrestrictions/admission.go
  pkg/build/apiserver/admission/strategyrestrictions/admission_test.go
  pkg/image/apiserver/admission/imagepolicy/imagepolicy.go
  pkg/image/apiserver/admission/limitrange/admission.go
  pkg/network/apiserver/admission/ingress_admission.go
  pkg/network/apiserver/admission/ingress_admission_test.go
  pkg/project/apiserver/admission/nodeenv/admission.go
  pkg/project/apiserver/admission/nodeenv/admission_test.go
  pkg/project/apiserver/admission/requestlimit/admission.go
  pkg/project/apiserver/admission/requestlimit/admission_test.go
  pkg/quota/apiserver/admission/clusterresourceoverride/admission.go
  pkg/quota/apiserver/admission/clusterresourceoverride/admission_test.go
  pkg/quota/apiserver/admission/clusterresourcequota/admission.go
  pkg/quota/apiserver/admission/runonceduration/admission_test.go
  pkg/scheduler/admission/podnodeconstraints/admission.go
  pkg/scheduler/admission/podnodeconstraints/admission_test.go
  pkg/security/apiserver/admission/sccadmission/admission.go
  pkg/security/apiserver/admission/sccadmission/admission_test.go
  pkg/security/apiserver/admission/sccadmission/scc_exec.go
  pkg/security/apiserver/admission/sccadmission/scc_exec_test.go
  pkg/service/admission/externalipranger/externalip_admission.go
  pkg/service/admission/externalipranger/externalip_admission_test.go
  pkg/service/admission/restrictedendpoints/endpoint_admission.go
  test/integration/build_admission_test.go
  test/integration/scc_test.go
Labels: approved, area/security, lgtm, size/L

#20645 Externalize newapp / newbuild
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  hack/import-restrictions.json
  pkg/image/util/helpers.go
  pkg/oc/cli/admin/ipfailover/keepalived/generator.go
  pkg/oc/cli/admin/migrate/images/imagerefs.go
  pkg/oc/cli/admin/registry/registry.go
  pkg/oc/cli/admin/router/router.go
  pkg/oc/cli/debug/debug.go
  pkg/oc/cli/importer/appjson/appjson.go
  pkg/oc/cli/newapp/newapp.go
  pkg/oc/cli/newapp/newapp_test.go
  pkg/oc/cli/newbuild/newbuild.go
  pkg/oc/cli/newbuild/newbuild_test.go
  pkg/oc/cli/set/deploymenthook.go
  pkg/oc/cli/set/env.go
  pkg/oc/cli/set/helper.go
  pkg/oc/cli/set/probe.go
  pkg/oc/cli/set/volume.go
  pkg/oc/cli/startbuild/startbuild.go
  pkg/oc/lib/newapp/app/app.go
  pkg/oc/lib/newapp/app/app_test.go
  pkg/oc/lib/newapp/app/builder.go
  pkg/oc/lib/newapp/app/builder_test.go
  pkg/oc/lib/newapp/app/componentmatch.go
  pkg/oc/lib/newapp/app/dockerimagelookup.go
  pkg/oc/lib/newapp/app/env.go
  pkg/oc/lib/newapp/app/imageref.go
  pkg/oc/lib/newapp/app/imageref_test.go
  pkg/oc/lib/newapp/app/imagestreamlookup.go
  pkg/oc/lib/newapp/app/imagestreamlookup_test.go
  pkg/oc/lib/newapp/app/pipeline.go
  pkg/oc/lib/newapp/app/pipeline_test.go
  pkg/oc/lib/newapp/app/scorers.go
  pkg/oc/lib/newapp/app/sourcelookup.go
  pkg/oc/lib/newapp/app/templatelookup.go
  pkg/oc/lib/newapp/app/templatelookup_test.go
  pkg/oc/lib/newapp/appjson/appjson.go
  pkg/oc/lib/newapp/cmd/describe.go
  pkg/oc/lib/newapp/cmd/newapp.go
  pkg/oc/lib/newapp/cmd/newapp_test.go
  pkg/oc/lib/newapp/cmd/template.go
  pkg/oc/lib/newapp/cmd/template_test.go
  pkg/oc/util/clientcmd/helpers.go
  pkg/oc/util/env/env.go
  pkg/pod/envresolve/internal_version/env.go
  pkg/util/labels.go
  pkg/util/labels_test.go
  test/integration/newapp_test.go
  test/testdata/template_multiple_resource_gvs.yaml
Labels: approved, lgtm, size/XXL

#20905 [] bump(github.com/evanphx/json-patch): f195058310bd062ea7c754a834f0f…
  glide.lock
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/github.com/evanphx/json-patch/patch_test.go
Labels: approved, lgtm, queue/critical-fix, size/M

#20744 admission: enable webhooks by default
  pkg/cmd/server/origin/admission/chain_builder.go
  pkg/cmd/server/origin/admission/register.go
Labels: approved, lgtm, size/S

#20916 Remove --routing-suffix since it's not supported anymore
  docs/cluster_up_down.md
  pkg/oc/cli/cluster/cluster.go
  pkg/oc/clusterup/up.go
Labels: approved, lgtm, sig/master, size/XS

#20917 Drop export
  docs/cli.md
  docs/man/man1/.files_generated_oc
  docs/man/man1/oc-export.1
  hack/import-restrictions.json
  pkg/oc/cli/cli.go
  pkg/oc/cli/export/export.go
  pkg/oc/cli/export/exporter.go
  pkg/oc/cli/export/exporter_test.go
  test/cmd/export.sh
Labels: approved, lgtm, size/XL

#20904 [3.11] bump(github.com/evanphx/json-patch): f195058310bd062ea7c754a83…
  glide.lock
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/github.com/evanphx/json-patch/patch_test.go
Labels: approved, lgtm, queue/critical-fix, size/M

#20889 Support setting storageClassName: "" when "" is specified by claim-class
  pkg/oc/cli/set/volume.go
  pkg/oc/cli/set/volume_test.go
Labels: approved, lgtm, size/M

#20912 externalize admin node commands
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/oc/cli/admin/node/evacuate.go
  pkg/oc/cli/admin/node/listpods.go
  pkg/oc/cli/admin/node/node.go
  pkg/oc/cli/admin/node/node_options.go
  pkg/oc/cli/admin/node/schedulable.go
  test/cmd/admin.sh
Labels: approved, lgtm, size/L

#20940 Release was not correctly replacing strings due to a bad regex rule
  pkg/oc/cli/admin/release/image_mapper.go
  pkg/oc/cli/admin/release/image_mapper_test.go
  pkg/oc/cli/admin/release/new.go
Labels: approved, size/L

#20924 add default values for kubeapiserverconfig to make it easier to use
  install/etcd/install.yaml
  pkg/cmd/openshift-kube-apiserver/cmd.go
  pkg/cmd/openshift-kube-apiserver/configdefault/config_default.go
  pkg/cmd/openshift-kube-apiserver/configdefault/kubecontrolplane_default.go
  pkg/oc/clusterup/manifests/bindata.go
  pkg/oc/clusterup/run_self_hosted.go
  test/extended/testdata/bindata.go
Labels: approved, lgtm, size/XL

#20944 Add more logging to deployment tests and waiting for tests to set up
  test/extended/deployments/deployments.go
  test/extended/deployments/util.go
  test/extended/testdata/bindata.go
  test/extended/testdata/deployments/custom-deployment.yaml
  test/extended/testdata/deployments/test-deployment-test.yaml
Labels: approved, lgtm, size/M

#20954 UPSTREAM: <carry>: simplify kube-controller-manager patches
  vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/patch.go
  vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/patch_recycler.go
Labels: approved, lgtm, size/L

#20935 hack: copy oc to kubectl
  hack/build-cross.sh
  hack/lib/build/binaries.sh
Labels: approved, lgtm, size/S

#20955 treat missing .docker/config.json as a warning, not an error
  pkg/oc/clusteradd/components/default-imagestreams/create_secret.go
Labels: approved, lgtm, retest-not-required, size/XS

#20936 add kube-apiserver-operator to cluster up
  install/cluster-kube-apiserver-operator/install.yaml
  pkg/cmd/openshift-kube-apiserver/configdefault/kubecontrolplane_default.go
  pkg/cmd/server/start/master_args.go
  pkg/oc/clusterup/coreinstall/components/pivot/initialconfig.go
  pkg/oc/clusterup/manifests/bindata.go
  pkg/oc/clusterup/run_self_hosted.go
  test/extended/testdata/bindata.go
Labels: approved, lgtm, size/XL

#20922 [oc cluster up] fix bootstrap surfacing errors
  pkg/oc/clusterup/up.go
Labels: approved, lgtm, size/S

#20848 UPSTREAM: 68008: apiserver: forward panic in WithTimeout filter
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/filters/BUILD
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/filters/timeout.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/filters/timeout_test.go
Labels: approved, lgtm, size/M

#20970 Print less gorp when builds fail
  hack/lib/log/stacktrace.sh
Labels: approved, lgtm, size/XS

#20914 Remove openshift-sdn from the openshift binary
  Makefile
  cmd/openshift-sdn/openshift-sdn.go
  docs/man/man1/.files_generated_openshift
  docs/man/man1/openshift-start-network.1
  hack/build-go.sh
  hack/lib/constants.sh
  images/dind/node/openshift-sdn-node.sh
  images/node/Dockerfile
  images/node/Dockerfile.no_rpm
  images/node/system-container/config.json.template
  images/node/system-container/manifest.json
  images/node/system-container/service.template
  images/node/system-container/system-container-wrapper.sh
  images/node/system-container/tmpfiles.template
  install/kube-dns/install.yaml
  install/kube-proxy/install.yaml
  install/openshift-service-cert-signer-operator/install.yaml
  origin.spec
  pkg/cmd/openshift-apiserver/cmd.go
  pkg/cmd/openshift-controller-manager/cmd.go
  pkg/cmd/openshift-etcd/start_etcd.go
  pkg/cmd/openshift-kube-apiserver/cmd.go
  pkg/cmd/server/apis/config/validation/common/serving.go
  pkg/cmd/server/apis/config/validation/common/serving_test.go
  pkg/cmd/server/apis/config/validation/etcd.go
  pkg/cmd/server/apis/config/validation/master.go
  pkg/cmd/server/apis/config/validation/network/network.go
  pkg/cmd/server/apis/config/validation/node.go
  pkg/cmd/server/apis/config/validation/validation.go
  pkg/cmd/server/apis/config/validation/validation_test.go
  pkg/cmd/server/origin/profiler.go
  pkg/cmd/server/start/master_args.go
  pkg/cmd/server/start/network/node_args.go
  pkg/cmd/server/start/network/start_network.go
  pkg/cmd/server/start/options/image_args.go
  pkg/cmd/server/start/options/kube_connection_args.go
  pkg/cmd/server/start/options/listen_arg.go
  pkg/cmd/server/start/options/network_args.go
  pkg/cmd/server/start/start.go
  pkg/cmd/server/start/start_api.go
  pkg/cmd/server/start/start_controllers.go
  pkg/cmd/server/start/start_master.go
  pkg/oc/clusterup/manifests/bindata.go
  pkg/oc/clusterup/run_self_hosted.go
  pkg/oc/clusterup/up.go
  test/cmd/admin.sh
  test/cmd/help.sh
  test/extended/alternate_launches.sh
  test/extended/testdata/bindata.go
  test/util/server/server.go
Labels: approved, lgtm, size/XXL

#20987 Skip the disruptive suite for now
  test/extended/util/test.go
Labels: approved, lgtm, size/XS

#20911 Ignore errors caused by unkonwn scopes where it makes sense to do so.
  pkg/authorization/apis/authorization/rbacconversion/conversion.go
  pkg/authorization/apiserver/registry/subjectrulesreview/storage.go
  pkg/authorization/authorizer/scope/authorizer.go
  pkg/authorization/authorizer/scope/authorizer_test.go
  pkg/authorization/authorizer/scope/converter.go
  pkg/authorization/authorizer/scope/converter_test.go
  pkg/project/apiserver/registry/project/proxy/proxy.go
  pkg/project/auth/cache.go
  test/integration/scopes_test.go
Labels: approved, lgtm, sig/security, size/L

#20977 Add a new `oc adm release mirror` command
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/oc/cli/admin/release/extract.go
  pkg/oc/cli/admin/release/mirror.go
  pkg/oc/cli/admin/release/new.go
  pkg/oc/cli/admin/release/release.go
  pkg/oc/cli/image/extract/extract.go
  pkg/oc/cli/image/mirror/mirror.go
  pkg/oc/cli/image/mirror/plan.go
Labels: approved, lgtm, size/XL

#20596 UPSTREAM: 66617: Do not set cgroup parent when --cgroups-per-qos is disabled
  vendor/k8s.io/kubernetes/pkg/kubelet/cm/pod_container_manager_linux.go
Labels: approved, lgtm, size/XS

#20962 externalize ipfailover command
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/oc/cli/admin/ipfailover/ipfailover.go
  pkg/oc/cli/admin/ipfailover/ipfailover/interfaces.go
  pkg/oc/cli/admin/ipfailover/ipfailover/options.go
  pkg/oc/cli/admin/ipfailover/ipfailover/types.go
  pkg/oc/cli/admin/ipfailover/keepalived/generator.go
  pkg/oc/cli/admin/ipfailover/keepalived/generator_test.go
  pkg/oc/cli/admin/ipfailover/keepalived/plugin.go
  pkg/oc/cli/admin/ipfailover/keepalived/plugin_test.go
  pkg/oc/cli/admin/ipfailover/validation.go
  pkg/oc/cli/admin/ipfailover/validation_test.go
  test/cmd/router.sh
Labels: approved, lgtm, size/XL

#20885 remove builder image dependencies on origin
  glide.lock
  pkg/build/builder/cmd/builder.go
  pkg/build/builder/cmd/dockercfg/cfg.go
  pkg/build/builder/cmd/scmauth/cacert.go
  pkg/build/builder/cmd/scmauth/gitconfig.go
  pkg/build/builder/cmd/scmauth/password.go
  pkg/build/builder/cmd/scmauth/scmauth_test.go
  pkg/build/builder/cmd/scmauth/scmauths.go
  pkg/build/builder/cmd/scmauth/sshkey.go
  pkg/build/builder/cmd/scmauth/util.go
  pkg/build/builder/common.go
  pkg/build/builder/docker.go
  pkg/build/builder/dockerutil.go
  pkg/build/builder/source.go
  pkg/build/builder/sti.go
  pkg/build/builder/timing/context.go
  pkg/build/builder/util.go
  pkg/build/builder/util/glog/glog.go
  pkg/build/util/util.go
  vendor/github.com/openshift/library-go/pkg/image/internal/digest/digest.go
  vendor/github.com/openshift/library-go/pkg/image/internal/digest/digester.go
  vendor/github.com/openshift/library-go/pkg/image/internal/digest/doc.go
  vendor/github.com/openshift/library-go/pkg/image/internal/reference/doc.go
  vendor/github.com/openshift/library-go/pkg/image/internal/reference/reference.go
  vendor/github.com/openshift/library-go/pkg/image/internal/reference/regexp.go
  vendor/github.com/openshift/library-go/pkg/image/reference/reference.go
  vendor/github.com/openshift/library-go/pkg/image/reference/reference_test.go
Labels: approved, lgtm, sig/developer-experience, size/XXL

#21000 Deprecate oc types
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/oc/cli/types/types.go
Labels: approved, lgtm, size/M

#20969 External admin groups
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/oc/cli/admin/groups/changemembership.go
  pkg/oc/cli/admin/groups/groups.go
  pkg/oc/cli/admin/groups/new/new.go
  pkg/oc/cli/admin/groups/sync/prune.go
  pkg/oc/cli/admin/groups/sync/sync.go
  pkg/oc/cli/admin/groups/users/add.go
  pkg/oc/cli/admin/groups/users/remove.go
  test/integration/groups_test.go
Labels: approved, lgtm, sig/security, size/XL

#20999 UPSTREAM: 68678: tighten maximum retry loop for aggregate api availability
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/controllers/status/available_controller.go
Labels: approved, lgtm, size/XS

#21009 Restore graceful shutdown of DNS server
  pkg/cmd/server/start/network/start_network.go
Labels: approved, lgtm, size/M

#21024 Fix image quota evaluators to support both internal and external resources
  pkg/quota/image/imagestreamimport_evaluator.go
  pkg/quota/image/imagestreamtag_evaluator.go
  test/cmd/quota.sh
Labels: approved, lgtm, size/S

#21021 [release-3.11] Restore graceful shutdown of DNS server
  pkg/cmd/server/start/start_network.go
Labels: approved, lgtm, size/M

#21028 fix template finalizer godoc
  pkg/template/controller/templateinstance_finalizer.go
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#21003 switch cluster up to using openshift apiserver config
  install/openshift-apiserver/install.yaml
  install/openshift-apiserver/static-config.json
  pkg/cmd/openshift-apiserver/cmd.go
  pkg/cmd/openshift-kube-apiserver/configdefault/kubecontrolplane_default.go
  pkg/oc/clusterup/coreinstall/kubeapiserver/config.go
  pkg/oc/clusterup/coreinstall/kubeapiserver/openshift_apiserver.go
  pkg/oc/clusterup/manifests/bindata.go
  pkg/oc/clusterup/run_self_hosted.go
  pkg/oc/clusterup/signing_secret.go
  test/extended/testdata/bindata.go
Labels: approved, lgtm, size/L

#21019 Issue #20985 Don't mount the docker/config.json if file doesn't exist
  pkg/oc/clusterup/run_self_hosted.go
Labels: approved, lgtm, size/XS

#21026 Use 0000_ as the "ordering" prefix for now
  pkg/oc/cli/admin/release/new.go
Labels: approved, lgtm, size/S

#21020 Use standard node roles for conformance isolation
  test/extended/conformance-k8s.sh
Labels: approved, lgtm, size/XS

#21036 Extract the etcd start from intetration - step 1
  test/util/server/server.go
Labels: approved, lgtm, size/S

#21018 Drop oc types command
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/oc/cli/cli.go
  pkg/oc/cli/types/types.go
  test/cmd/basicresources.sh
  test/cmd/help.sh
Labels: approved, lgtm, size/L

#21033 Update nodeenv plugin and DS controller to not process openshift.io/node-selector if scheduler.alpha.kubernetes.io/node-selector is set on pods namespace
  pkg/project/apiserver/admission/nodeenv/admission.go
  vendor/k8s.io/kubernetes/pkg/controller/daemon/patch_nodeselector.go
  vendor/k8s.io/kubernetes/pkg/controller/daemon/patch_nodeselector_test.go
Labels: approved, lgtm, size/M

#21050 Issue #20985 Don't mount the docker/config.json if file doesn't exist
  pkg/oc/clusterup/run_self_hosted.go
Labels: approved, lgtm, size/XS

#20950 Improve egress IP node-offline-tracking error checking
  pkg/network/common/egressip.go
Labels: approved, component/networking, kind/bug, lgtm, sig/networking, size/S

#20998 Cluster loader: Link to latest OKD docs instead of 3.9 OCP docs
  test/extended/cluster/README.md
Labels: approved, lgtm, size/XS

#21046 remove cluster up cruft
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  hack/import-restrictions.json
  install/automationservicebroker/OWNERS
  install/automationservicebroker/install-rbac.yaml
  install/automationservicebroker/install.yaml
  install/openshift-web-console-operator/install-rbac.yaml
  install/openshift-web-console-operator/install.yaml
  install/origin-web-console/OWNERS
  install/origin-web-console/console-config.yaml
  install/origin-web-console/console-template.yaml
  install/service-catalog-broker-resources/template-service-broker-registration.yaml
  install/templateservicebroker/apiserver-config.yaml
  install/templateservicebroker/apiserver-template.yaml
  install/templateservicebroker/rbac-template.yaml
  pkg/oc/cli/cluster/cluster.go
  pkg/oc/clusterup/coreinstall/fileutil/copy.go
  pkg/oc/clusterup/coreinstall/kubeapiserver/openshift_apiserver.go
  pkg/oc/clusterup/coreinstall/kubeapiserver/openshift_controller.go
  pkg/oc/clusterup/coreinstall/kubelet/dns.go
  pkg/oc/clusterup/coreinstall/tmpformac/tmp_for_mac_snowflakes.go
  pkg/oc/clusterup/docker/dockerhelper/helper.go
  pkg/oc/clusterup/docker/dockerhelper/registryconfig.go
  pkg/oc/clusterup/docker/dockerhelper/registryconfig_test.go
  pkg/oc/clusterup/docker/errors/docker.go
  pkg/oc/clusterup/docker/exec/doc.go
  pkg/oc/clusterup/docker/exec/errors.go
  pkg/oc/clusterup/docker/exec/exec.go
  pkg/oc/clusterup/docker/host/host.go
  pkg/oc/clusterup/docker/openshift/helper.go
  pkg/oc/clusterup/docker/run/errors.go
  pkg/oc/clusterup/docker/run/run.go
  pkg/oc/clusterup/manifests/bindata.go
  pkg/oc/clusterup/run_self_hosted.go
  pkg/oc/clusterup/status.go
  pkg/oc/clusterup/up.go
  test/extended/testdata/bindata.go
Labels: approved, lgtm, size/XXL

#21023 Update glide to tolerate osin moving into openshift org
  glide.lock
  glide.yaml
  vendor/github.com/openshift/library-go/pkg/assets/assets.go
  vendor/github.com/openshift/library-go/pkg/assets/template.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
Labels: approved, lgtm, sig/security, size/L

#21058 Update nodeenv plugin and DS controller to not process openshift.io/node-selector if scheduler.alpha.kubernetes.io/node-selector is set on pods namespace
  pkg/project/apiserver/admission/nodeenv/admission.go
  vendor/k8s.io/kubernetes/pkg/controller/daemon/patch_nodeselector.go
  vendor/k8s.io/kubernetes/pkg/controller/daemon/patch_nodeselector_test.go
Labels: approved, lgtm, size/M

#20968 make ext test need for existing cluster painfully obvious
  test/extended/setup.sh
Labels: approved, lgtm, sig/developer-experience, size/XS

#21025 UPSTREAM: 67825: disable multiattach in vSphere
  vendor/k8s.io/kubernetes/pkg/controller/volume/attachdetach/reconciler/reconciler.go
Labels: approved, lgtm, sig/storage, size/XS

#21008 Remove internalclientset usage from oc helpers
  hack/import-restrictions.json
  pkg/oc/cli/admin/prune/imageprune/helper.go
  pkg/oc/cli/admin/prune/imageprune/prune.go
  pkg/oc/cli/admin/top/graph.go
  pkg/oc/cli/admin/verifyimagesignature/verify-signature.go
  pkg/oc/cli/create/imagestreamtag.go
  pkg/oc/cli/debug/debug.go
  pkg/oc/cli/importimage/importimage.go
  pkg/oc/cli/logs/logs.go
  pkg/oc/cli/registry/info/info.go
  pkg/oc/cli/registry/login/login.go
  pkg/oc/cli/set/triggers.go
  pkg/oc/cli/startbuild/startbuild_test.go
  pkg/oc/cli/whoami/whoami.go
  pkg/oc/clusterup/up.go
  pkg/oc/lib/buildapihelpers/helpers.go
  pkg/oc/lib/describe/helpers.go
  pkg/oc/lib/graph/buildgraph/analysis/bc.go
  pkg/oc/lib/graph/buildgraph/edges.go
  pkg/oc/lib/graph/imagegraph/edges.go
  pkg/oc/lib/kubeconfig/smart_merge.go
  pkg/oc/lib/newapp/cmd/newapp.go
  pkg/oc/originpolymorphichelpers/logsforobject.go
  pkg/oc/util/clientcmd/resolve.go
  pkg/oc/util/clientcmd/resolve_test.go
  pkg/oc/util/project/util.go
  test/integration/login_test.go
  test/integration/oauth_oidc_test.go
  test/integration/webhook_token_auth_test.go
Labels: approved, lgtm, size/L

#21051 cluster-up: fix condition on bind mount
  pkg/oc/clusterup/run_self_hosted.go
Labels: approved, lgtm, size/XS

#21049 use default route hostname to access internal git server
  test/extended/builds/gitauth.go
  test/extended/testdata/bindata.go
  test/extended/testdata/test-gitserver-tokenauth.yaml
  test/extended/testdata/test-gitserver.yaml
Labels: approved, lgtm, retest-not-required, size/M

#21059 fix dind
  hack/dind-cluster.sh
  images/dind/node/Dockerfile
  images/dind/node/openshift-sdn-node.sh
Labels: approved, lgtm, sig/networking, size/XS

#21057 UPSTREAM: <drop>: comment out componentconfig registration for kube controller manager
  vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go
Labels: approved, lgtm, size/XS

#21044 perform url fetches via an execpod
  test/extended/image_ecosystem/helper.go
  test/extended/image_ecosystem/sample_repos.go
  test/extended/util/framework.go
Labels: approved, lgtm, sig/developer-experience, size/M

#21071 migrate: ignore resources that cannot be listed and updated
  pkg/oc/cli/admin/migrate/migrator.go
Labels: approved, kind/bug, lgtm, size/M

#21072 pin to v4.0 so that the latest image problem can be bypassed for now
  install/cluster-kube-apiserver-operator/install.yaml
  install/cluster-openshift-apiserver-operator/install.yaml
  install/cluster-openshift-controller-manager-operator/install.yaml
  pkg/oc/clusterup/manifests/bindata.go
  test/extended/testdata/bindata.go
Labels: approved, lgtm, size/M

#21076 Adjusting oc cluster up help text
  pkg/oc/clusterup/up.go
Labels: approved, lgtm, size/XS

#21085 egress IP fixes for 3.11
  pkg/network/common/egressip.go
  pkg/network/common/egressip_test.go
Labels: approved, component/networking, lgtm, sig/networking, size/M

#21087 Minor fixup to egress IP monitoring
  pkg/network/node/vxlan_monitor.go
  pkg/network/node/vxlan_monitor_test.go
Labels: approved, component/networking, lgtm, sig/networking, size/L

#21065 Fix a few small bugs in image stream describe and printers
  pkg/image/apis/image/sort.go
  pkg/oc/lib/describe/describer.go
  pkg/printers/internalversion/printer.go
  pkg/printers/internalversion/printer_test.go
Labels: approved, lgtm, size/L

#21060 UPSTREAM: 68626: Fix mount options for netdev
  vendor/k8s.io/kubernetes/pkg/util/mount/BUILD
  vendor/k8s.io/kubernetes/pkg/util/mount/exec_mount.go
  vendor/k8s.io/kubernetes/pkg/util/mount/mount.go
  vendor/k8s.io/kubernetes/pkg/util/mount/mount_linux.go
  vendor/k8s.io/kubernetes/pkg/util/mount/mount_test.go
  vendor/k8s.io/kubernetes/pkg/util/mount/mount_windows.go
  vendor/k8s.io/kubernetes/pkg/util/mount/nsenter_mount.go
Labels: approved, lgtm, sig/storage, size/L

#21089 OS constant in `oc adm release new` was invalid
  pkg/oc/cli/admin/release/new.go
Labels: approved, lgtm, size/XS

#21074 dockerless build controller updates
  pkg/build/apis/build/validation/validation.go
  pkg/build/controller/strategy/custom.go
  pkg/build/controller/strategy/custom_test.go
  pkg/build/controller/strategy/docker.go
  pkg/build/controller/strategy/docker_test.go
  pkg/build/controller/strategy/sti.go
  pkg/build/controller/strategy/sti_test.go
  pkg/build/controller/strategy/util.go
Labels: approved, lgtm, size/L

#21093 Image sort is flaky because of order
  pkg/image/apis/image/sort.go
  pkg/image/apis/image/sort_test.go
Labels: approved, kind/test-flake, lgtm, size/M

#21073 Add job to oc status
  pkg/oc/lib/describe/projectstatus.go
  pkg/oc/lib/describe/projectstatus_test.go
  pkg/oc/lib/graph/genericgraph/graphview/job.go
  pkg/oc/lib/graph/genericgraph/graphview/statefulset.go
  pkg/oc/lib/graph/genericgraph/test/job.yaml
  pkg/oc/lib/graph/kubegraph/edges.go
  pkg/oc/lib/graph/kubegraph/nodes/nodes.go
  pkg/oc/lib/graph/kubegraph/nodes/nodes_test.go
  pkg/oc/lib/graph/kubegraph/nodes/types.go
Labels: approved, lgtm, size/L

#21084 oc cluster add
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/oc/cli/cluster/cluster.go
  pkg/oc/clusterup/clusteradd/add_cmd.go
  pkg/oc/clusterup/clusteradd/apply_image.go
Labels: approved, lgtm, size/L

#21099 Use group resource in migrate reporting
  pkg/oc/cli/admin/migrate/migrator.go
  test/cmd/migrate.sh
Labels: approved, lgtm, size/S

#21101 accept new controller manager config.
  vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/patch_flags.go
  vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/patch_imagetemplate.go
  vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/patch_satoken.go
Labels: approved, lgtm, size/L

#21088 UPSTREAM: <carry>: remove dead controller-manager carry
  vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/patch_imagetemplate.go
Labels: approved, size/L

#21102 use service-ca.crt for git auth
  test/extended/builds/gitauth.go
Labels: approved, lgtm, size/XS

#21070 UPSTREAM: 68680: Fix chown on distributed flex volumes (like gluster)
  vendor/k8s.io/kubernetes/pkg/volume/flexvolume/driver-call.go
  vendor/k8s.io/kubernetes/pkg/volume/flexvolume/mounter.go
Labels: approved, lgtm, sig/storage, size/XS

#21100 Require confirmation before extracting into directories
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/oc/cli/image/extract/extract.go
  test/extended/images/extract.go
Labels: approved, lgtm, size/M

#20137 Update CONTRIBUTING.adoc
  CONTRIBUTING.adoc
Labels: approved, lgtm, lifecycle/stale, size/XS

#21117 Fix JobSpecNode flake
  pkg/oc/lib/graph/kubegraph/nodes/nodes_test.go
Labels: approved, lgtm, size/M

#21110 disable service token gitauth test
  test/extended/builds/gitauth.go
  test/extended/testdata/bindata.go
  test/extended/testdata/test-gitserver-tokenauth.yaml
  test/extended/testdata/test-gitserver.yaml
Labels: approved, lgtm, retest-not-required, size/M

#21115 Deprecate output-version in import app.json
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/oc/cli/importer/appjson/appjson.go
Labels: approved, lgtm, size/XS

#21109 test: Set custom deployment template app to sleep infinity
  test/extended/testdata/bindata.go
  test/extended/testdata/deployments/custom-deployment.yaml
Labels: approved, lgtm, size/XS

#21118 Add a new simple start-local server option for quick iteration
  hack/start-local.sh
Labels: approved, lgtm, retest-not-required, sig/developer-experience, size/M

#21104 Support `--to-dir` on release to make local iteration easier
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/oc/cli/admin/release/new.go
Labels: approved, lgtm, size/M

#21035 UPSTREAM: 68820: Wait for events instead of just checking them in cronjob e2e
  vendor/k8s.io/kubernetes/test/e2e/apps/cronjob.go
Labels: approved, lgtm, size/M

#21119 oc image extract should be able to print which layer files come from
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/oc/cli/admin/release/extract.go
  pkg/oc/cli/image/extract/extract.go
Labels: approved, lgtm, size/M

#21113 Add job test for oc status
  test/cmd/status.sh
Labels: approved, lgtm, size/XS

#21116 Drop ocscheme
  pkg/oc/cli/cli.go
  pkg/oc/cli/create/create.go
  pkg/oc/cli/create/route.go
  pkg/oc/cli/idle/idle.go
  pkg/oc/cli/importer/appjson/appjson.go
  pkg/oc/cli/process/process.go
  pkg/oc/cli/rollback/rollback.go
  pkg/oc/cli/rollout/latest.go
  pkg/oc/cli/startbuild/startbuild.go
  pkg/oc/cli/startbuild/startbuild_test.go
  pkg/oc/util/ocscheme/printing.go
  pkg/oc/util/ocscheme/read_internal.go
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/util/conversion.go
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/util/patch_versioning_scheme.go
Labels: approved, lgtm, size/L

#21128 use common storage for image content extraction
  pkg/build/controller/strategy/sti.go
Labels: approved, lgtm, size/XS

#21129 use overlay for buildah storage
  pkg/build/controller/strategy/util.go
Labels: approved, lgtm, size/XS
