Repository openshift/origin, pull requests merged in 2018-08, with the labels that each got.

#20478 Use `--apparent-size` in size check
  hack/lib/constants.sh
Labels: approved, lgtm, size/S

#20481 Bug 1608254 - update help messages
  pkg/oc/cli/set/deploymenthook.go
  pkg/oc/cli/status/status.go
  pkg/oc/lib/describe/projectstatus.go
Labels: approved, lgtm, size/S

#20490 bump(*) and s2i symlink fix
  glide.lock
  glide.yaml
  pkg/build/builder/sti.go
  test/extended/builds/s2i_env.go
  test/extended/builds/start.go
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/s2i-environment-build-app/.s2i/environment
  test/extended/testdata/builds/s2i-environment-build-app/Gemfile
  test/extended/testdata/builds/s2i-environment-build-app/config.ru
  test/extended/testdata/builds/test-symlink-build.yaml
  vendor/github.com/openshift/source-to-image/.gitignore
  vendor/github.com/openshift/source-to-image/contrib/completions/bash/s2i
  vendor/github.com/openshift/source-to-image/contrib/completions/zsh/s2i
  vendor/github.com/openshift/source-to-image/docs/cli.md
  vendor/github.com/openshift/source-to-image/examples/nginx-centos7/s2i/bin/assemble
  vendor/github.com/openshift/source-to-image/examples/nginx-centos7/s2i/bin/save-artifacts
  vendor/github.com/openshift/source-to-image/examples/nginx-centos7/test/run
  vendor/github.com/openshift/source-to-image/hack/test-stirunimage.sh
  vendor/github.com/openshift/source-to-image/pkg/api/constants/doc.go
  vendor/github.com/openshift/source-to-image/pkg/api/constants/env.go
  vendor/github.com/openshift/source-to-image/pkg/api/constants/labels.go
  vendor/github.com/openshift/source-to-image/pkg/api/constants/scripts.go
  vendor/github.com/openshift/source-to-image/pkg/api/describe/describer.go
  vendor/github.com/openshift/source-to-image/pkg/api/types.go
  vendor/github.com/openshift/source-to-image/pkg/build/config.go
  vendor/github.com/openshift/source-to-image/pkg/build/strategies/dockerfile/dockerfile.go
  vendor/github.com/openshift/source-to-image/pkg/build/strategies/layered/layered.go
  vendor/github.com/openshift/source-to-image/pkg/build/strategies/layered/layered_test.go
  vendor/github.com/openshift/source-to-image/pkg/build/strategies/onbuild/onbuild.go
  vendor/github.com/openshift/source-to-image/pkg/build/strategies/sti/postexecutorstep.go
  vendor/github.com/openshift/source-to-image/pkg/build/strategies/sti/sti.go
  vendor/github.com/openshift/source-to-image/pkg/build/strategies/sti/sti_test.go
  vendor/github.com/openshift/source-to-image/pkg/build/strategies/sti/usage.go
  vendor/github.com/openshift/source-to-image/pkg/build/strategies/sti/usage_test.go
  vendor/github.com/openshift/source-to-image/pkg/build/strategies/strategies.go
  vendor/github.com/openshift/source-to-image/pkg/cmd/cli/cmd/build.go
  vendor/github.com/openshift/source-to-image/pkg/create/templates/test.go
  vendor/github.com/openshift/source-to-image/pkg/docker/docker.go
  vendor/github.com/openshift/source-to-image/pkg/docker/docker_test.go
  vendor/github.com/openshift/source-to-image/pkg/docker/util.go
  vendor/github.com/openshift/source-to-image/pkg/docker/util_test.go
  vendor/github.com/openshift/source-to-image/pkg/errors/errors.go
  vendor/github.com/openshift/source-to-image/pkg/ignore/ignore.go
  vendor/github.com/openshift/source-to-image/pkg/ignore/ignore_test.go
  vendor/github.com/openshift/source-to-image/pkg/scm/downloaders/file/download.go
  vendor/github.com/openshift/source-to-image/pkg/scm/downloaders/file/download_test.go
  vendor/github.com/openshift/source-to-image/pkg/scm/downloaders/git/clone.go
  vendor/github.com/openshift/source-to-image/pkg/scripts/environment.go
  vendor/github.com/openshift/source-to-image/pkg/scripts/install.go
  vendor/github.com/openshift/source-to-image/pkg/scripts/install_test.go
  vendor/github.com/openshift/source-to-image/pkg/test/fs/fs.go
  vendor/github.com/openshift/source-to-image/pkg/util/fs/fs.go
  vendor/github.com/openshift/source-to-image/pkg/util/fs/fs_test.go
  vendor/github.com/openshift/source-to-image/pkg/util/injection.go
  vendor/github.com/openshift/source-to-image/pkg/util/injection_test.go
  vendor/github.com/openshift/source-to-image/pkg/util/labels.go
  vendor/github.com/openshift/source-to-image/pkg/util/strings.go
  vendor/github.com/openshift/source-to-image/pkg/util/user/rangelist.go
  vendor/github.com/openshift/source-to-image/test/integration/integration_test.go
Labels: approved, lgtm, size/XXL

#20357 HAProxy router fix for ip whitelist exceeding max config arguments that haproxy allows.
  images/router/haproxy/Dockerfile
  images/router/haproxy/conf/haproxy-config.template
  pkg/router/template/template_helper.go
  pkg/router/template/util/haproxy/whitelist.go
  pkg/router/template/util/haproxy/whitelist_test.go
Labels: approved, lgtm, sig/network-edge, size/L

#20495 hack: fix usage of du in osx
  hack/lib/constants.sh
Labels: approved, lgtm, size/S

#20484 apps: moves extended test helper and some registries to external types
  pkg/apps/apiserver/apiserver.go
  pkg/apps/apiserver/registry/deploylog/rest.go
  pkg/apps/apiserver/registry/deploylog/rest_test.go
  pkg/apps/apiserver/registry/rollback/rest.go
  pkg/apps/apiserver/registry/rollback/rest_test.go
  test/extended/builds/contextdir.go
  test/extended/builds/gitauth.go
  test/extended/builds/jenkins_plugin.go
  test/extended/builds/new_app.go
  test/extended/builds/pipeline.go
  test/extended/cluster/cl.go
  test/extended/image_ecosystem/mariadb_ephemeral.go
  test/extended/image_ecosystem/mongodb_ephemeral.go
  test/extended/image_ecosystem/mysql_ephemeral.go
  test/extended/image_ecosystem/mysql_replica.go
  test/extended/image_ecosystem/postgresql_replica.go
  test/extended/image_ecosystem/s2i_perl.go
  test/extended/image_ecosystem/s2i_php.go
  test/extended/image_ecosystem/s2i_python.go
  test/extended/image_ecosystem/s2i_ruby.go
  test/extended/image_ecosystem/sample_repos.go
  test/extended/templates/templateinstance_readiness.go
  test/extended/util/framework.go
Labels: approved, lgtm, size/L

#18828 Clean go vet
  hack/jsonformat/main.go
  hack/lib/constants.sh
  hack/listtests/main.go
  hack/verify-govet.sh
  hack/verify-jsonformat.sh
  pkg/apps/controller/deployer/deployer_controller_test.go
  pkg/build/controller/build/build_controller_test.go
  pkg/cmd/infra/deployer/deployer_test.go
  pkg/network/node/egressip.go
  pkg/oauth/generated/clientset/clientset.go
  pkg/oauth/generated/clientset/doc.go
  pkg/oauth/generated/clientset/fake/clientset_generated.go
  pkg/oauth/generated/clientset/fake/doc.go
  pkg/oauth/generated/clientset/fake/register.go
  pkg/oauth/generated/clientset/scheme/doc.go
  pkg/oauth/generated/clientset/scheme/register.go
  pkg/oauth/generated/clientset/typed/oauth/v1/doc.go
  pkg/oauth/generated/clientset/typed/oauth/v1/fake/doc.go
  pkg/oauth/generated/clientset/typed/oauth/v1/fake/fake_oauth_client.go
  pkg/oauth/generated/clientset/typed/oauth/v1/fake/fake_oauthaccesstoken.go
  pkg/oauth/generated/clientset/typed/oauth/v1/fake/fake_oauthauthorizetoken.go
  pkg/oauth/generated/clientset/typed/oauth/v1/fake/fake_oauthclient.go
  pkg/oauth/generated/clientset/typed/oauth/v1/fake/fake_oauthclientauthorization.go
  pkg/oauth/generated/clientset/typed/oauth/v1/generated_expansion.go
  pkg/oauth/generated/clientset/typed/oauth/v1/oauth_client.go
  pkg/oauth/generated/clientset/typed/oauth/v1/oauthaccesstoken.go
  pkg/oauth/generated/clientset/typed/oauth/v1/oauthauthorizetoken.go
  pkg/oauth/generated/clientset/typed/oauth/v1/oauthclient.go
  pkg/oauth/generated/clientset/typed/oauth/v1/oauthclientauthorization.go
  pkg/oc/cli/admin/diagnostics/diagnostics/client/pod/run_diagnostics_pod.go
  pkg/oc/cli/admin/diagnostics/diagnostics/cluster/aggregated_logging/diagnostic.go
  pkg/oc/cli/admin/diagnostics/diagnostics/cluster/app_create/main.go
  pkg/oc/cli/admin/diagnostics/diagnostics/cluster/network/run_pod.go
  pkg/oc/cli/admin/diagnostics/diagnostics/host/etcd.go
  pkg/oc/cli/startbuild/startbuild_test.go
  pkg/router/f5/plugin_test.go
  test/extended/builds/pipeline.go
  test/extended/router/headers.go
  test/extended/router/router.go
  test/extended/util/url/url_test.go
  test/integration/unprivileged_newproject_test.go
  tools/testdebug/cmd/load_etcd.go
Labels: approved, lgtm, needs-api-review, queue/multiple-rebases, size/XXL

#20456 UPSTREAM: 66725: update exit code to 0 if patch not needed
  test/cmd/basicresources.sh
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/patch.go
Labels: approved, lgtm, size/S

#20491 avoid unnecessary admission plugin initializers
  pkg/authorization/apiserver/admission/restrictusers/restrictusers.go
  pkg/authorization/apiserver/admission/restrictusers/restrictusers_test.go
  pkg/authorization/util/util.go
  pkg/build/apiserver/admission/strategyrestrictions/admission.go
  pkg/build/apiserver/admission/strategyrestrictions/admission_test.go
  pkg/cmd/openshift-apiserver/server.go
  pkg/cmd/openshift-controller-manager/controller/template.go
  pkg/cmd/openshift-controller-manager/controller_manager.go
  pkg/cmd/server/admission/init.go
  pkg/cmd/server/admission/types.go
  pkg/cmd/server/origin/admission/plugin_initializer.go
  pkg/cmd/server/origin/authenticator.go
  pkg/cmd/server/origin/informers.go
  pkg/cmd/server/origin/master_config.go
  pkg/cmd/server/start/start_master.go
  pkg/image/apiserver/admission/imagepolicy/imagepolicy.go
  pkg/image/apiserver/admission/imagepolicy/imagepolicy_test.go
  pkg/image/apiserver/apiserver.go
  pkg/image/apiserver/registry/imagestream/etcd/etcd.go
  pkg/image/apiserver/registry/imagestream/etcd/etcd_test.go
  pkg/image/apiserver/registry/imagestream/strategy.go
  pkg/image/apiserver/registry/imagestream/strategy_test.go
  pkg/image/apiserver/registry/imagestreamimage/rest_test.go
  pkg/image/apiserver/registry/imagestreamimport/rest.go
  pkg/image/apiserver/registry/imagestreammapping/rest_test.go
  pkg/image/apiserver/registry/imagestreamtag/rest_test.go
  pkg/project/apiserver/admission/requestlimit/admission.go
  pkg/project/apiserver/admission/requestlimit/admission_test.go
  pkg/project/apiserver/apiserver.go
  pkg/project/apiserver/registry/projectrequest/delegated/delegated.go
  pkg/quota/apiserver/admission/clusterresourcequota/admission.go
  pkg/route/apiserver/apiserver.go
  pkg/route/apiserver/registry/route/etcd/etcd_test.go
  pkg/route/apiserver/registry/route/strategy.go
  pkg/route/apiserver/registry/route/strategy_test.go
  pkg/template/apiserver/apiserver.go
  pkg/template/apiserver/registry/templateinstance/etcd/etcd.go
  pkg/template/apiserver/registry/templateinstance/strategy.go
  pkg/template/controller/templateinstance_controller.go
  pkg/template/controller/templateinstance_controller_test.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/kubernetes/typed/authorization/v1/fake/fake_subjectaccessreview_expansion.go
Labels: approved, lgtm, size/L

#19216 Use CRI interface instead of docker calls in network diagnostics
  images/dind/node/Dockerfile
  pkg/oc/cli/admin/diagnostics/diagnostics/cluster/network/in_pod/cmd.go
  pkg/oc/cli/admin/diagnostics/diagnostics/cluster/network/in_pod/collect.go
  pkg/oc/cli/admin/diagnostics/diagnostics/cluster/network/in_pod/node.go
  pkg/oc/cli/admin/diagnostics/diagnostics/cluster/network/in_pod/pod.go
  pkg/oc/cli/admin/diagnostics/diagnostics/cluster/network/in_pod/service.go
  pkg/oc/cli/admin/diagnostics/diagnostics/cluster/network/in_pod/util/log.go
  pkg/oc/cli/admin/diagnostics/diagnostics/cluster/network/in_pod/util/runtime.go
  pkg/oc/cli/admin/diagnostics/diagnostics/cluster/network/results.go
  pkg/oc/cli/admin/diagnostics/diagnostics/cluster/network/run_pod.go
Labels: approved, component/diagnostics, lgtm, sig/network-edge, size/L

#20386 Update cancelbuild cmd to use external versions
  hack/import-restrictions.json
  pkg/oc/cli/cancelbuild/cancelbuild.go
  pkg/oc/cli/cancelbuild/cancelbuild_test.go
Labels: approved, lgtm, size/M

#20505 set full user info for SAR check on template readiness checks
  pkg/template/controller/templateinstance_controller.go
  test/extended/templates/templateinstance_security.go
Labels: approved, lgtm, size/M

#20489 divorce the build overrides and defaults from the main configapi scheme
  pkg/build/controller/build/defaults/defaults.go
  pkg/build/controller/build/overrides/overrides.go
  pkg/build/controller/build/pluginconfig/config.go
Labels: approved, lgtm, size/L

#20503 Injecting new required vars into origin.spec file
  .tito/lib/origin/common.py
Labels: approved, lgtm, size/XS

#20482 sanitize some cluster up imports
  pkg/oc/cli/admin/policy/authz_helpers.go
  pkg/oc/cli/admin/policy/modify_scc.go
  pkg/oc/cli/admin/policy/modify_scc_test.go
  pkg/oc/clusteradd/componentinstall/privileged.go
  pkg/oc/clusteradd/components/router/router_install.go
  pkg/oc/clusteradd/components/template-service-broker/template_service_broker.go
  pkg/oc/clusterup/coreinstall/components/persistent-volumes/setup_persistent_volumes.go
  pkg/oc/clusterup/docker/openshift/helper.go
  pkg/oc/clusterup/run_self_hosted.go
  pkg/oc/clusterup/up.go
Labels: approved, lgtm, size/L

#20459 When images are not found in the cache, delay slightly and retry
  pkg/image/apiserver/registry/imagestream/etcd/etcd.go
Labels: approved, lgtm, size/M

#20509 UPSTREAM: 64971: Cherry pick of #64255 fix field removal in mutating admission webhooks
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/admission/plugin/webhook/mutating/BUILD
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/admission/plugin/webhook/mutating/admission.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/admission/plugin/webhook/mutating/admission_test.go
Labels: approved, lgtm, size/L

#20527 Change logo, favicon, name on login page
  pkg/oauthserver/server/errorpage/templates.go
  pkg/oauthserver/server/login/templates.go
  pkg/oauthserver/server/selectprovider/templates.go
Labels: approved, lgtm, queue/critical-fix, retest-not-required, size/L

#20528 [release-3.10] Change logo, favicon, name on login page
  pkg/oauthserver/server/errorpage/templates.go
  pkg/oauthserver/server/login/templates.go
  pkg/oauthserver/server/selectprovider/templates.go
Labels: approved, lgtm, queue/critical-fix, retest-not-required, size/L

#20504 move build controller configapi to configapi
  hack/lib/constants.sh
  hack/update-generated-conversions.sh
  hack/update-generated-deep-copies.sh
  pkg/build/controller/build/apis/defaults/doc.go
  pkg/build/controller/build/apis/defaults/install/install.go
  pkg/build/controller/build/apis/defaults/register.go
  pkg/build/controller/build/apis/defaults/types.go
  pkg/build/controller/build/apis/defaults/v1/doc.go
  pkg/build/controller/build/apis/defaults/v1/register.go
  pkg/build/controller/build/apis/defaults/v1/swagger_doc.go
  pkg/build/controller/build/apis/defaults/v1/types.go
  pkg/build/controller/build/apis/defaults/v1/zz_generated.conversion.go
  pkg/build/controller/build/apis/defaults/v1/zz_generated.deepcopy.go
  pkg/build/controller/build/apis/defaults/zz_generated.deepcopy.go
  pkg/build/controller/build/apis/overrides/doc.go
  pkg/build/controller/build/apis/overrides/install/install.go
  pkg/build/controller/build/apis/overrides/register.go
  pkg/build/controller/build/apis/overrides/types.go
  pkg/build/controller/build/apis/overrides/v1/doc.go
  pkg/build/controller/build/apis/overrides/v1/register.go
  pkg/build/controller/build/apis/overrides/v1/swagger_doc.go
  pkg/build/controller/build/apis/overrides/v1/types.go
  pkg/build/controller/build/apis/overrides/v1/zz_generated.deepcopy.go
  pkg/build/controller/build/apis/overrides/zz_generated.deepcopy.go
  pkg/build/controller/build/defaults/defaults.go
  pkg/build/controller/build/defaults/defaults_test.go
  pkg/build/controller/build/overrides/overrides.go
  pkg/build/controller/build/overrides/overrides_test.go
  pkg/build/controller/build/pluginconfig/config.go
  pkg/cmd/openshift-controller-manager/controller/build.go
  pkg/cmd/openshift-controller-manager/conversion.go
  pkg/cmd/server/apis/config/install/install.go
  pkg/cmd/server/apis/config/register.go
  pkg/cmd/server/apis/config/serialization_test.go
  pkg/cmd/server/apis/config/types.go
  pkg/cmd/server/apis/config/v1/register.go
  pkg/cmd/server/apis/config/v1/types.go
  pkg/cmd/server/apis/config/v1/zz_generated.deepcopy.go
  pkg/cmd/server/apis/config/v1/zz_generated.defaults.go
  pkg/cmd/server/apis/config/validation/build_defaults.go
  pkg/cmd/server/apis/config/validation/build_defaults_test.go
  pkg/cmd/server/apis/config/validation/build_overrides.go
  pkg/cmd/server/apis/config/validation/build_overrides_test.go
  pkg/cmd/server/apis/config/zz_generated.deepcopy.go
  test/integration/buildpod_admission_test.go
Labels: approved, lgtm, size/XXL

#20514 Update commands with resource builders to use external versions
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  hack/import-restrictions.json
  pkg/image/util/helpers.go
  pkg/oc/cli/admin/diagnostics/diagnostics/client/pod/run_diagnostics_pod.go
  pkg/oc/cli/admin/diagnostics/diagnostics/cluster/network/results.go
  pkg/oc/cli/admin/diagnostics/diagnostics/cluster/network/setup.go
  pkg/oc/cli/debug/debug.go
  pkg/oc/cli/extract/extract.go
  pkg/oc/cli/logs/logs.go
  pkg/oc/cli/rsh/rsh.go
  pkg/oc/cli/rsync/pathspec.go
  pkg/oc/cli/rsync/rsync.go
  pkg/oc/cli/secrets/basicauth.go
  pkg/oc/cli/secrets/basicauth_test.go
  pkg/oc/cli/secrets/dockercfg.go
  pkg/oc/cli/secrets/known_secret_types.go
  pkg/oc/cli/secrets/link_secret_to_obj.go
  pkg/oc/cli/secrets/new.go
  pkg/oc/cli/secrets/new_test.go
  pkg/oc/cli/secrets/options.go
  pkg/oc/cli/secrets/sshauth.go
  pkg/oc/cli/secrets/sshauth_test.go
  pkg/oc/cli/secrets/unlink_secret_from_object.go
  pkg/oc/originpolymorphichelpers/attachablepodforobject.go
  pkg/oc/originpolymorphichelpers/logsforobject.go
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/BUILD
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/attach.go
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/attach_test.go
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/clusterinfo_dump.go
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/logs.go
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/logs_test.go
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/portforward.go
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/run.go
  vendor/k8s.io/kubernetes/pkg/kubectl/conditions.go
  vendor/k8s.io/kubernetes/pkg/kubectl/polymorphichelpers/BUILD
  vendor/k8s.io/kubernetes/pkg/kubectl/polymorphichelpers/attachablepodforobject.go
  vendor/k8s.io/kubernetes/pkg/kubectl/polymorphichelpers/helpers.go
  vendor/k8s.io/kubernetes/pkg/kubectl/polymorphichelpers/helpers_test.go
  vendor/k8s.io/kubernetes/pkg/kubectl/polymorphichelpers/interface.go
  vendor/k8s.io/kubernetes/pkg/kubectl/polymorphichelpers/logsforobject.go
  vendor/k8s.io/kubernetes/pkg/kubectl/polymorphichelpers/logsforobject_test.go
  vendor/k8s.io/kubernetes/test/e2e/kubectl/kubectl.go
Labels: approved, lgtm, size/XXL

#20441 UPSTREAM: 64860:checkLimitsForResolvConf for the pod create and update events instead of checking periodically
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_test.go
  vendor/k8s.io/kubernetes/pkg/kubelet/network/dns/dns.go
Labels: approved, lgtm, size/M

#20521 check for tag before proceeding with new-app test
  test/cmd/newapp.sh
Labels: approved, lgtm, size/XS

#20529 UPSTREAM: 66931: Use the passed-in streams in kubectl top
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/top_node.go
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/top_pod.go
Labels: approved, lgtm, size/S

#20525 only print each webhook once.
  pkg/oc/lib/describe/describer.go
Labels: approved, lgtm, size/XS

#20112 Make ReconcileSCCOptions.ChangedSCCs return separate constraints slices
  pkg/oc/cli/admin/diagnostics/diagnostics/cluster/scc.go
  pkg/oc/cli/admin/policy/reconcile_sccs.go
Labels: approved, lgtm, sig/security, size/M

#20492 update jenkins test to use pod/curl util for rest calls; add header s…
  test/extended/builds/jenkins_plugin.go
  test/extended/builds/pipeline.go
  test/extended/testdata/bindata.go
  test/extended/testdata/jenkins-plugin/imagestream-scm-dsl-job.xml
  test/extended/util/framework.go
  test/extended/util/jenkins/ref.go
  test/extended/util/url/url.go
Labels: approved, lgtm, sig/developer-experience, size/L

#20423 make hack/build-local-images.py runnable with py3
  hack/build-local-images.py
Labels: approved, lgtm, sig/developer-experience, size/S

#20533 Update README.md to reflect OKD rebranding
  README.md
Labels: approved, lgtm, size/M

#20333 update import-image cmd to use external versions
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  hack/import-restrictions.json
  pkg/oc/cli/importimage/importimage.go
  pkg/oc/cli/importimage/importimage_test.go
  test/cmd/images.sh
Labels: approved, lgtm, size/XL

#20535 fix set build-hook panic on empty file
  pkg/oc/cli/set/buildhook.go
  test/cmd/setbuildhook.sh
Labels: approved, lgtm, size/XS

#20511 Update SCC-related commands' descriptions
  pkg/oc/cli/admin/policy/modify_scc.go
Labels: approved, lgtm, size/S

#20520 Move project-related commands to external client
  hack/import-restrictions.json
  pkg/oc/cli/cli.go
  pkg/oc/cli/project/project.go
  pkg/oc/cli/projects/projects.go
  pkg/oc/cli/requestproject/request_project.go
  pkg/oc/cli/requestproject/request_project_test.go
  pkg/oc/clusterup/docker/openshift/project.go
  pkg/oc/lib/describe/projectstatus.go
  pkg/project/apis/project/helpers/helpers.go
  test/integration/authorization_test.go
  test/integration/unprivileged_newproject_test.go
Labels: approved, lgtm, size/L

#19797 Bump grafana version.
  examples/grafana/grafana.yaml
  examples/grafana/setup-grafana.sh
Labels: approved, component/metrics, lgtm, size/S

#20542 build/controller/build: simplify bool exprs
  pkg/build/controller/build/build_controller_test.go
Labels: approved, lgtm, size/XS

#20540 cmd/server: replace raw literals with named constants
  pkg/cmd/server/apis/config/v1/conversions.go
  pkg/cmd/server/start/master_args.go
Labels: approved, lgtm, size/XS

#20536 allow versions to be specified for bc logs
  pkg/oc/originpolymorphichelpers/logsforobject.go
  test/cmd/builds.sh
Labels: approved, lgtm, size/XS

#20545 apps: fix extended flake
  test/extended/builds/gitauth.go
  test/extended/builds/jenkins_plugin.go
  test/extended/builds/new_app.go
  test/extended/builds/pipeline.go
  test/extended/cluster/cm.go
  test/extended/deployments/deployments.go
  test/extended/image_ecosystem/mariadb_ephemeral.go
  test/extended/image_ecosystem/mongodb_ephemeral.go
  test/extended/image_ecosystem/mysql_ephemeral.go
  test/extended/image_ecosystem/mysql_replica.go
  test/extended/image_ecosystem/postgresql_replica.go
  test/extended/image_ecosystem/s2i_perl.go
  test/extended/image_ecosystem/s2i_php.go
  test/extended/image_ecosystem/s2i_python.go
  test/extended/image_ecosystem/s2i_ruby.go
  test/extended/image_ecosystem/sample_repos.go
  test/extended/images/append.go
  test/extended/router/config_manager.go
  test/extended/router/metrics.go
  test/extended/router/router.go
  test/extended/router/scoped.go
  test/extended/router/stress.go
  test/extended/util/deploymentconfigs.go
Labels: approved, lgtm, size/M

#20548 Show builds history limit settings with oc describe bc/foo
  pkg/oc/lib/describe/describer.go
Labels: approved, lgtm, sig/developer-experience, size/S

#20551 switch authenticators to external clients
  pkg/apiserver/authentication/oauth/expirationvalidator.go
  pkg/apiserver/authentication/oauth/expirationvalidator_test.go
  pkg/apiserver/authentication/oauth/interfaces.go
  pkg/apiserver/authentication/oauth/timeoutvalidator.go
  pkg/apiserver/authentication/oauth/tokenauthenticator.go
  pkg/apiserver/authentication/oauth/tokenauthenticator_test.go
  pkg/apiserver/authentication/oauth/uidvalidator.go
  pkg/cmd/server/origin/authenticator.go
  pkg/cmd/server/origin/informers.go
  pkg/cmd/server/origin/master_config.go
Labels: approved, lgtm, sig/security, size/L

#20537 log scheme error for custom resources
  pkg/oc/cli/newapp/newapp.go
Labels: approved, lgtm, size/S

#20553 ensure req'ed env vars are availave for e2e style direct ginkgo invoc…
  test/extended/util/cli.go
Labels: approved, lgtm, sig/developer-experience, size/S

#20546 clean up image registry hostname retrieval
  pkg/cmd/server/admission/init.go
  pkg/cmd/server/origin/admission/plugin_initializer.go
  pkg/cmd/server/origin/master.go
  pkg/cmd/server/origin/master_config.go
  pkg/cmd/server/origin/openshift_apiserver.go
  pkg/image/apis/image/helper.go
  pkg/image/apis/image/validation/validation_test.go
  pkg/image/apis/image/validation/whitelist/whitelister.go
  pkg/image/apiserver/apiserver.go
  pkg/image/apiserver/registry/imagestream/etcd/etcd.go
  pkg/image/apiserver/registry/imagestream/etcd/etcd_test.go
  pkg/image/apiserver/registry/imagestream/strategy.go
  pkg/image/apiserver/registry/imagestream/strategy_test.go
  pkg/image/apiserver/registry/imagestreamimage/rest_test.go
  pkg/image/apiserver/registry/imagestreammapping/rest.go
  pkg/image/apiserver/registry/imagestreammapping/rest_test.go
  pkg/image/apiserver/registry/imagestreammapping/strategy.go
  pkg/image/apiserver/registry/imagestreamtag/rest_test.go
  pkg/image/apiserver/registryhostname/environmentresolvercache.go
  pkg/image/apiserver/registryhostname/environmentresolvercache_test.go
  pkg/image/apiserver/registryhostname/retriever.go
Labels: approved, lgtm, size/L

#20554 UPSTREAM: 67024: add CancelRequest to discovery round-tripper
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/discovery/round_tripper.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/transport/round_trippers.go
Labels: approved, lgtm, size/S

#20379 Drop authorizer wrapper
  pkg/authorization/authorizer/authorizer.go
  pkg/authorization/authorizer/browsersafe/authorizer.go
  pkg/authorization/authorizer/browsersafe/authorizer_test.go
  pkg/authorization/authorizer/interfaces.go
  pkg/authorization/authorizer/messages.go
  pkg/authorization/authorizer/messages_test.go
  pkg/authorization/authorizer/scope/authorizer.go
  pkg/authorization/authorizer/scope/authorizer_test.go
  pkg/cmd/server/origin/authorizer.go
  test/cmd/authentication.sh
  test/cmd/basicresources.sh
  test/cmd/policy.sh
  test/integration/authorization_test.go
  test/integration/bootstrap_policy_test.go
  test/integration/oauth_cert_fallback_test.go
  vendor/k8s.io/kubernetes/pkg/auth/authorizer/abac/abac.go
  vendor/k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac/rbac.go
Labels: approved, lgtm, sig/security, size/XL

#20559 Fix for router with dynamic config changes not reloading
  pkg/router/template/configmanager/haproxy/manager.go
Labels: approved, lgtm, sig/network-edge, size/XS

#20563 info/diag for direct ext test invocation on gcp/prow
  test/extended/builds/pipeline.go
  test/extended/util/cli.go
  test/extended/util/jenkins/ref.go
Labels: approved, lgtm, sig/developer-experience, size/M

#20523 Injecting new required vars into origin.spec file
  .tito/lib/origin/common.py
Labels: approved, lgtm, size/XS

#20452 UPSTREAM 64896: kubectl: wait for all errors and successes on podEviction
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/drain.go
Labels: approved, lgtm, size/M

#20591 Increasing allowed openshift-node-config size
  hack/lib/constants.sh
Labels: approved, lgtm, priority/P0, size/XS

#20575 enable override of agent pod template images during prow/gcp invocati…
  test/extended/builds/jenkins_plugin.go
  test/extended/builds/pipeline.go
  test/extended/util/jenkins/ref.go
Labels: approved, lgtm, sig/developer-experience, size/S

#20592 Revert "Provide feedback on progression for extracting of binary build"
  pkg/build/builder/source.go
Labels: approved, lgtm, size/M

#20565 separate controller manager and apiserver informers
  pkg/client/genericinformers/interface.go
  pkg/cmd/openshift-controller-manager/controller/apps.go
  pkg/cmd/openshift-controller-manager/controller/authorization.go
  pkg/cmd/openshift-controller-manager/controller/build.go
  pkg/cmd/openshift-controller-manager/controller/image.go
  pkg/cmd/openshift-controller-manager/controller/ingress.go
  pkg/cmd/openshift-controller-manager/controller/interfaces.go
  pkg/cmd/openshift-controller-manager/controller/network.go
  pkg/cmd/openshift-controller-manager/controller/network_sdn.go
  pkg/cmd/openshift-controller-manager/controller/project.go
  pkg/cmd/openshift-controller-manager/controller/quota.go
  pkg/cmd/openshift-controller-manager/controller/security.go
  pkg/cmd/openshift-controller-manager/controller/service.go
  pkg/cmd/openshift-controller-manager/controller/serviceaccount.go
  pkg/cmd/openshift-controller-manager/controller/template.go
  pkg/cmd/openshift-controller-manager/controller/unidling.go
  pkg/cmd/openshift-controller-manager/controller_manager.go
  pkg/cmd/server/origin/informers.go
  pkg/cmd/server/origin/master_config.go
  test/integration/buildcontroller_test.go
Labels: approved, lgtm, sig/master, size/XL

#20582 Bug 1608254 - update help messages
  pkg/oc/cli/set/deploymenthook.go
  pkg/oc/cli/status/status.go
Labels: approved, lgtm

#20500 Don't auto-assign egress IPs that are no longer in use
  pkg/network/common/egressip.go
  pkg/network/common/egressip_test.go
Labels: approved, component/networking, kind/bug, lgtm, sig/networking, size/M

#20603 UPSTREAM: 67094: Fix incorrect reporting of cpu,memory and also output volumes when BalanceAttachedNodeVolumes is enabled.
  vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/priorities/resource_allocation.go
Labels: approved, lgtm, size/S

#20622 Add debugging to templateinstance gc test
  test/extended/templates/templateinstance_cross_namespace.go
Labels: approved, lgtm, size/XS

#20550 Fix debug panic
  pkg/oc/cli/admin/diagnostics/diagnostics/cluster/app_create/app.go
  pkg/oc/cli/debug/debug.go
  pkg/oc/cli/newapp/newapp.go
  pkg/oc/lib/conditions/conditions.go
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/logs.go
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/run.go
Labels: approved, lgtm, size/L

#20558 update serviceaccount cmds to use externals
  hack/import-restrictions.json
  pkg/oc/cli/export/exporter.go
  pkg/oc/cli/export/exporter_test.go
  pkg/oc/cli/serviceaccounts/create_kubeconfig.go
  pkg/oc/cli/serviceaccounts/gettoken.go
  pkg/oc/cli/serviceaccounts/newtoken.go
  pkg/oc/cli/serviceaccounts/subcommand.go
  pkg/oc/lib/serviceaccount/helpers.go
  pkg/serviceaccounts/client.go
  pkg/serviceaccounts/controllers/create_dockercfg_secrets.go
  pkg/serviceaccounts/util/helpers.go
  test/util/client.go
Labels: approved, lgtm, size/L

#20616 UPSTREAM: <drop>: increase loglevel for health check
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/healthz/healthz.go
Labels: approved, lgtm, size/M

#20619 Wire factory to DiagnosticsOptions
  pkg/oc/cli/admin/diagnostics/diagnostics.go
Labels: approved, lgtm, size/XS

#20466 Add `oc image extract` to support release tooling
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  docs/man/man1/.files_generated_oc
  docs/man/man1/oc-image-extract.1
  pkg/oc/cli/image/append/append.go
  pkg/oc/cli/image/append/manifest.go
  pkg/oc/cli/image/append/workqueue.go
  pkg/oc/cli/image/archive/archive.go
  pkg/oc/cli/image/archive/archive_linux.go
  pkg/oc/cli/image/archive/archive_other.go
  pkg/oc/cli/image/archive/archive_unix.go
  pkg/oc/cli/image/archive/archive_windows.go
  pkg/oc/cli/image/archive/time_linux.go
  pkg/oc/cli/image/archive/time_unsupported.go
  pkg/oc/cli/image/extract/extract.go
  pkg/oc/cli/image/image.go
  pkg/oc/cli/image/manifest/manifest.go
  pkg/oc/cli/image/mirror/manifest.go
  pkg/oc/cli/image/mirror/mirror.go
  pkg/oc/cli/image/workqueue/workqueue.go
  test/extended/images/extract.go
Labels: approved, lgtm, size/XXL

#20620 Basic high availability for auto egress IPs
  pkg/network/node/egressip.go
  pkg/network/node/egressip_test.go
  pkg/network/node/vxlan_monitor.go
  pkg/network/node/vxlan_monitor_test.go
  pkg/util/ovs/ovs.go
Labels: approved, component/networking, lgtm, sig/networking, size/XL

#20344 Remove `openshift start node` and cut kubelet dependencies
  contrib/completions/bash/openshift
  contrib/completions/zsh/openshift
  contrib/systemd/atomic-openshift-node.service
  contrib/systemd/origin-node.service
  contrib/systemd/origin-node.sysconfig
  contrib/vagrant/provision-master.sh
  contrib/vagrant/provision-node.sh
  contrib/vagrant/provision-util.sh
  docs/man/man1/.files_generated_openshift
  docs/man/man1/openshift-start-node.1
  docs/man/man1/openshift-start-template-service-broker.1
  hack/lib/start.sh
  hack/lib/util/environment.sh
  images/node/scripts/origin-node-run.sh
  origin.spec
  pkg/cmd/openshift/openshift.go
  pkg/cmd/server/kubernetes/node/doc.go
  pkg/cmd/server/kubernetes/node/node.go
  pkg/cmd/server/kubernetes/node/options/options.go
  pkg/cmd/server/start/bootstrap_node.go
  pkg/cmd/server/start/command_test.go
  pkg/cmd/server/start/config_test.go
  pkg/cmd/server/start/master_args.go
  pkg/cmd/server/start/network_args.go
  pkg/cmd/server/start/node_args.go
  pkg/cmd/server/start/start.go
  pkg/cmd/server/start/start_allinone.go
  pkg/cmd/server/start/start_master.go
  pkg/cmd/server/start/start_network.go
  pkg/cmd/server/start/start_node.go
  pkg/oc/clusterup/coreinstall/kubelet/flags.go
  test/cmd/admin.sh
  test/cmd/help.sh
  test/extended/alternate_launches.sh
  test/integration/diag_nodes_test.go
  test/integration/tls_test.go
  test/util/server/server.go
Labels: approved, lgtm, size/XXL

#20636 UPSTREAM: 63146: Remove patch retry conflict detection
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/patch.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/rest_test.go
Labels: approved, lgtm, size/S

#20567 switch more commands to external versions
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  hack/import-restrictions.json
  pkg/oc/cli/create/route.go
  pkg/oc/cli/create/route/route.go
  pkg/oc/cli/create/routeedge.go
  pkg/oc/cli/create/routepassthrough.go
  pkg/oc/cli/create/routereenecrypt.go
  pkg/oc/cli/expose/expose.go
  pkg/oc/cli/importer/appjson/appjson.go
  pkg/oc/lib/newapp/cmd/newapp.go
  pkg/oc/lib/newapp/cmd/template.go
  pkg/oc/lib/newapp/cmd/template_test.go
  pkg/template/client/v1/templateconfig.go
  pkg/template/templateprocessing/template.go
Labels: approved, lgtm, size/L

#20601 sdn: don't fail when adding a duplicate route
  cmd/sdn-cni-plugin/openshift-sdn_linux.go
Labels: approved, lgtm, size/XS

#20566 UPSTREAM: 67093: improve config file modification time
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/clientcmd/client_config_test.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/clientcmd/config.go
Labels: approved, lgtm, size/M

#20564 UPSTREAM: <carry>: ensure perFSGroup quantity is positive
  vendor/k8s.io/kubernetes/cmd/kubelet/app/patch_volumequota.go
Labels: approved, kind/bug, lgtm, sig/pod, size/XS

#20630 router dynamic config manager fix to use the cloned blueprint
  pkg/router/template/configmanager/haproxy/manager.go
Labels: approved, lgtm, sig/network-edge, size/XS

#20647 Bug 1614660 - Network diagnostic will auto detect runtime
  pkg/oc/cli/admin/diagnostics/diagnostics/cluster/network/in_pod/cmd.go
  pkg/oc/cli/admin/diagnostics/diagnostics/cluster/network/in_pod/util/runtime.go
  pkg/oc/cli/admin/diagnostics/diagnostics/cluster/network/results.go
Labels: approved, lgtm, sig/network-edge, size/M

#20623 skip import call when there is nothing to import
  pkg/image/controller/imagestream_controller.go
  pkg/image/controller/imagestream_controller_test.go
Labels: approved, lgtm, sig/developer-experience, size/S

#20646 Fix haproxy router config manager issue where sanitize pems cause a blueprint route to not be selected
  pkg/cmd/infra/router/template.go
  pkg/router/template/configmanager/haproxy/manager.go
  pkg/router/template/types.go
Labels: approved, lgtm, sig/network-edge, size/M

#20605 split scc admission into mutating and validating
  pkg/security/apiserver/admission/sccadmission/admission.go
Labels: approved, lgtm, sig/master, sig/security, size/L

#20658 Network diags: Determine runtime based on local node object
  pkg/oc/cli/admin/diagnostics/diagnostics/cluster/network/in_pod/collect.go
  pkg/oc/cli/admin/diagnostics/diagnostics/cluster/network/in_pod/util/runtime.go
  pkg/oc/cli/admin/diagnostics/diagnostics/cluster/network/in_pod/util/util.go
Labels: approved, lgtm, sig/network-edge, size/M

#20635 UPSTREAM: 66932: Include unavailable apiservices in discovery response
  vendor/k8s.io/kubernetes/pkg/controller/resourcequota/resource_quota_controller.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/apiserver/handler_apis.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/apiserver/handler_apis_test.go
  vendor/k8s.io/kubernetes/test/integration/examples/apiserver_test.go
Labels: approved, lgtm, sig/master, size/M

#20595 Update more commands to use external versions
  pkg/oc/cli/buildlogs/buildlogs.go
  pkg/oc/cli/export/export.go
  pkg/oc/cli/logout/logout.go
  pkg/oc/cli/process/process.go
  pkg/oc/cli/process/process_test.go
  pkg/template/client/v1/templateconfig.go
Labels: approved, lgtm, size/L

#20670 Clean up bad OVS ports
  pkg/network/node/ovscontroller.go
Labels: approved, component/networking, kind/bug, lgtm, sig/networking, size/XS

#20590 move the handlers, servers, etc needed for a kubeapiserver to the kubeapiserver
  hack/import-restrictions.json
  pkg/client/genericinformers/interface.go
  pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/handlers.go
  pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/handlers_test.go
  pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/nonapiserver.go
  pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/patch.go
  pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/patch_authenticator.go
  pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/patch_authorizer.go
  pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/patch_handlerchain.go
  pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/patch_oauthserver.go
  pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/service_proxy_handler.go
  pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/webconsole_proxy.go
  pkg/cmd/server/origin/admission/plugin_initializer.go
  pkg/cmd/server/origin/master.go
  pkg/cmd/server/origin/master_config.go
  pkg/cmd/server/origin/oauth_apiserver_adapter.go
  test/integration/master_routes_test.go
Labels: approved, lgtm, size/XL

#20625 remove "does not alter the object" text
  pkg/oc/cli/set/env.go
Labels: approved, lgtm

#20580 Add Rust detector
  pkg/oc/lib/newapp/source/detector.go
Labels: approved, lgtm, sig/developer-experience, size/XS

#20358 UPSTREAM: 65549: Fix flexvolume in containerized kubelets
  vendor/k8s.io/kubernetes/cluster/get-kube-local.sh
  vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/BUILD
  vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/plugins.go
  vendor/k8s.io/kubernetes/cmd/kubelet/app/plugins.go
  vendor/k8s.io/kubernetes/cmd/kubelet/app/server.go
  vendor/k8s.io/kubernetes/hack/local-up-cluster.sh
  vendor/k8s.io/kubernetes/pkg/util/nsenter/BUILD
  vendor/k8s.io/kubernetes/pkg/util/nsenter/exec.go
  vendor/k8s.io/kubernetes/pkg/util/nsenter/exec_unsupported.go
  vendor/k8s.io/kubernetes/pkg/volume/flexvolume/flexvolume_test.go
  vendor/k8s.io/kubernetes/pkg/volume/flexvolume/plugin.go
  vendor/k8s.io/kubernetes/pkg/volume/flexvolume/probe.go
  vendor/k8s.io/kubernetes/pkg/volume/flexvolume/probe_test.go
Labels: approved, lgtm, sig/storage, size/L

#20673 service-catalog: use K8s NamespaceLifecycle admission controller
  examples/service-catalog/service-catalog.yaml
  pkg/oc/clusterup/manifests/bindata.go
Labels: approved, lgtm, size/XS

#20615 Backport retrieve node address logic from upstream
  vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/fake/fake.go
  vendor/k8s.io/kubernetes/pkg/kubelet/BUILD
  vendor/k8s.io/kubernetes/pkg/kubelet/cloud_request_manager.go
  vendor/k8s.io/kubernetes/pkg/kubelet/cloud_request_manager_test.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_node_status.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_node_status_test.go
Labels: approved, lgtm, size/L

#20637 use local dockerconfig for auth when pulling images
  pkg/oc/clusterup/docker/dockerhelper/helper.go
Labels: approved, lgtm, size/M

#20681 bump(*):
  glide.lock
  vendor/github.com/openshift/api/image/v1/types.go
  vendor/github.com/openshift/source-to-image/pkg/build/strategies/dockerfile/dockerfile.go
  vendor/github.com/openshift/source-to-image/pkg/util/injection_test.go
  vendor/github.com/openshift/source-to-image/pkg/util/status/build_status.go
  vendor/github.com/openshift/source-to-image/test/integration/integration_test.go
Labels: approved, lgtm, size/L

#20682 Fix dnsmasq/node dependency
  images/node/system-container/service.template
Labels: approved, lgtm, size/XS

#20674 add import restrictions for internal clients
  hack/import-restrictions.json
  pkg/build/controller/strategy/sti.go
  pkg/build/controller/strategy/sti_test.go
  pkg/cmd/infra/router/f5.go
  pkg/cmd/infra/router/router.go
  pkg/cmd/infra/router/template.go
  pkg/cmd/openshift-controller-manager/controller/build.go
  pkg/cmd/openshift-controller-manager/controller/interfaces.go
  pkg/cmd/openshift-controller-manager/controller/template.go
  pkg/cmd/server/bootstrappolicy/securitycontextconstraints_test.go
  pkg/oc/cli/admin/router/router.go
  pkg/router/controller/factory/factory.go
  pkg/router/controller/router_controller.go
  pkg/security/apiserver/admission/sccadmission/admission.go
  pkg/security/apiserver/admission/sccadmission/admission_test.go
  pkg/security/apiserver/apiserver.go
  pkg/security/apiserver/registry/podsecuritypolicyreview/rest.go
  pkg/security/apiserver/registry/podsecuritypolicyreview/rest_test.go
  pkg/security/apiserver/registry/podsecuritypolicyselfsubjectreview/rest.go
  pkg/security/apiserver/registry/podsecuritypolicyselfsubjectreview/rest_test.go
  pkg/security/apiserver/registry/podsecuritypolicysubjectreview/rest.go
  pkg/security/apiserver/registry/podsecuritypolicysubjectreview/rest_test.go
  pkg/security/apiserver/securitycontextconstraints/bypriority.go
  pkg/security/apiserver/securitycontextconstraints/bypriority_test.go
  pkg/security/apiserver/securitycontextconstraints/byrestrictions.go
  pkg/security/apiserver/securitycontextconstraints/byrestrictions_test.go
  pkg/security/apiserver/securitycontextconstraints/matcher.go
  pkg/security/apiserver/securitycontextconstraints/matcher_test.go
  pkg/security/apiserver/securitycontextconstraints/provider.go
  pkg/security/apiserver/securitycontextconstraints/provider_test.go
  pkg/security/apiserver/securitycontextconstraints/types.go
  pkg/template/controller/metrics.go
  pkg/template/controller/metrics_test.go
  pkg/template/controller/readiness.go
  pkg/template/controller/readiness_test.go
  pkg/template/controller/templateinstance_controller.go
  pkg/template/controller/templateinstance_controller_test.go
  pkg/template/controller/templateinstance_finalizer.go
  test/extended/templates/helpers.go
  test/extended/templates/templateinstance_cross_namespace.go
  test/extended/templates/templateinstance_impersonation.go
  test/extended/templates/templateinstance_objectkinds.go
  test/extended/templates/templateinstance_readiness.go
  test/extended/templates/templateinstance_security.go
  test/extended/templates/templateservicebroker_bind.go
  test/extended/templates/templateservicebroker_e2e.go
  test/extended/templates/templateservicebroker_security.go
  test/extended/util/cli.go
  test/integration/router_without_haproxy_test.go
Labels: approved, lgtm, sig/security, size/XL

#20643 React to imagelayers API changes
  pkg/image/apiserver/registry/imagestream/etcd/etcd.go
  test/extended/images/layers.go
Labels: approved, lgtm, size/M

#20687 in e2e wait for istag creation after the import, before the pull
  test/end-to-end/core.sh
Labels: approved, lgtm, sig/developer-experience, size/XS

#20642 allow patching configapi using oc patch
  pkg/cmd/server/apis/config/v1/register.go
  vendor/k8s.io/kubernetes/cluster/clientbin.sh
Labels: approved, lgtm, size/S

#20638 use the upstream RBAC roles for reconciliation
  pkg/cmd/server/bootstrappolicy/constants.go
  pkg/cmd/server/bootstrappolicy/dead.go
  pkg/cmd/server/bootstrappolicy/policy.go
  pkg/cmd/server/bootstrappolicy/web_console_role_test.go
  pkg/cmd/server/kubernetes/master/master_config.go
  test/integration/master_routes_test.go
  test/testdata/bootstrappolicy/bootstrap_cluster_role_bindings.yaml
  test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml
  test/testdata/bootstrappolicy/bootstrap_policy_file.yaml
Labels: approved, lgtm, size/XXL

#20677 Bug 1600741 - Provide better help for network diagnostic flags
  pkg/oc/cli/admin/diagnostics/diagnostics/cluster/network/run_pod.go
Labels: approved, lgtm, sig/network-edge, size/S

#20695 Revert "Provide feedback on progression for extracting of binary build"
  pkg/build/builder/source.go
Labels: approved, lgtm, size/M

#20666 Fix imagestream bugs
  pkg/oc/lib/newapp/app/imageref.go
  pkg/oc/lib/newapp/cmd/newapp.go
  test/cmd/newapp.sh
Labels: approved, lgtm, size/L

#20675 switch routes to external clients
  hack/import-restrictions.json
  pkg/cmd/infra/router/f5.go
  pkg/cmd/infra/router/router.go
  pkg/cmd/infra/router/template.go
  pkg/oc/cli/admin/diagnostics/diagnostics/cluster/route_validation.go
  pkg/oc/lib/describe/describer.go
  pkg/oc/lib/describe/projectstatus.go
  pkg/oc/lib/graph/routegraph/analysis/analysis.go
  pkg/oc/lib/routedisplayhelpers/status.go
  pkg/printers/internalversion/printer.go
  pkg/route/apis/route/helper.go
  pkg/route/apis/route/validation/validation.go
  pkg/route/apis/route/validation/validation_test.go
  pkg/route/controller/routeapihelpers/helper.go
  pkg/route/controller/routeapihelpers/helper_test.go
  pkg/route/controller/routeapihelpers/validation.go
  pkg/route/controller/routeapihelpers/validation_test.go
  pkg/router/controller/contention.go
  pkg/router/controller/extended_validator.go
  pkg/router/controller/factory/factory.go
  pkg/router/controller/host_admitter.go
  pkg/router/controller/host_admitter_test.go
  pkg/router/controller/hostindex/activation.go
  pkg/router/controller/hostindex/activation_test.go
  pkg/router/controller/hostindex/hostindex.go
  pkg/router/controller/hostindex/hostindex_test.go
  pkg/router/controller/router_controller.go
  pkg/router/controller/status.go
  pkg/router/controller/status_test.go
  pkg/router/controller/unique_host.go
  pkg/router/controller/unique_host_test.go
  pkg/router/f5/plugin.go
  pkg/router/f5/plugin_test.go
  pkg/router/interfaces.go
  pkg/router/template/certmanager.go
  pkg/router/template/certmanager_test.go
  pkg/router/template/configmanager/haproxy/blueprint_plugin.go
  pkg/router/template/configmanager/haproxy/blueprint_plugin_test.go
  pkg/router/template/configmanager/haproxy/manager.go
  pkg/router/template/plugin.go
  pkg/router/template/plugin_test.go
  pkg/router/template/router.go
  pkg/router/template/router_test.go
  pkg/router/template/template_helper.go
  pkg/router/template/template_helper_test.go
  pkg/router/template/types.go
  pkg/router/template/util/haproxy/map_entry.go
  pkg/router/template/util/haproxy/map_entry_test.go
  pkg/router/template/util/haproxy/types.go
  pkg/router/template/util/util.go
  pkg/router/template/util/util_test.go
  test/extended/router/scoped.go
  test/integration/router_without_haproxy_test.go
Labels: approved, lgtm, sig/network-edge, size/XXL

#20629 update CLI Hacking Guide
  docs/cli_hacking_guide.adoc
Labels: approved, lgtm, retest-not-required-docs-only, size/L

#20702 Fix router issue to use tcp balance scheme if configured
  images/router/haproxy/conf/haproxy-config.template
Labels: approved, lgtm, sig/network-edge, size/XS

#20709 move git server to external build client
  pkg/gitserver/autobuild/autobuild.go
  pkg/gitserver/getbuildconfigs.go
  pkg/gitserver/getbuildconfigs_test.go
Labels: approved, lgtm, size/M

#20667 Add forwarded header instead of replacing it
  images/router/haproxy/conf/haproxy-config.template
Labels: approved, lgtm, sig/network-edge, size/XS

#20694 remove the ability to limit secret refs based on service account
  pkg/cmd/server/apis/config/validation/master.go
  pkg/cmd/server/origin/admission/chain_builder.go
  test/integration/node_authorizer_test.go
  test/integration/service_account_test.go
  test/util/server/server.go
Labels: approved, lgtm, sig/master, size/S

#20703 Make the router tests tolerate multiple namespaces
  test/extended/images/append.go
  test/extended/router/config_manager.go
  test/extended/router/headers.go
  test/extended/router/metrics.go
  test/extended/router/reencrypt.go
  test/extended/router/router.go
  test/extended/router/scoped.go
  test/extended/router/stress.go
  test/extended/router/unprivileged.go
  test/extended/router/weighted.go
  test/extended/util/framework.go
Labels: approved, lgtm, size/L

#20710 allow substitution of legacy api kinds in templates
  pkg/template/templateprocessing/template.go
Labels: approved, lgtm, size/S

#20693 make cluster quota controller tolerate inaccessible api resources
  pkg/quota/controller/clusterquotareconciliation/reconciliation_controller.go
  vendor/k8s.io/kubernetes/pkg/controller/resourcequota/resource_quota_controller.go
Labels: approved, lgtm, size/M

#20699 switch our last two special cased admission plugins to config
  hack/import-restrictions.json
  hack/update-generated-deep-copies.sh
  pkg/cmd/openshift-kube-apiserver/cmd.go
  pkg/cmd/openshift-kube-apiserver/conversion.go
  pkg/cmd/server/apis/config/install/install.go
  pkg/cmd/server/origin/admission/chain_builder.go
  pkg/cmd/server/origin/admission/config_test.go
  pkg/cmd/server/origin/admission/register.go
  pkg/cmd/server/start/start_master.go
  pkg/oc/cli/admin/diagnostics/diagnostics/cluster/service_externalip.go
  pkg/service/admission/apis/externalipranger/doc.go
  pkg/service/admission/apis/externalipranger/install/install.go
  pkg/service/admission/apis/externalipranger/register.go
  pkg/service/admission/apis/externalipranger/types.go
  pkg/service/admission/apis/externalipranger/v1/doc.go
  pkg/service/admission/apis/externalipranger/v1/register.go
  pkg/service/admission/apis/externalipranger/v1/types.go
  pkg/service/admission/apis/externalipranger/v1/zz_generated.deepcopy.go
  pkg/service/admission/apis/externalipranger/zz_generated.deepcopy.go
  pkg/service/admission/apis/restrictedendpoints/doc.go
  pkg/service/admission/apis/restrictedendpoints/install/install.go
  pkg/service/admission/apis/restrictedendpoints/register.go
  pkg/service/admission/apis/restrictedendpoints/types.go
  pkg/service/admission/apis/restrictedendpoints/v1/doc.go
  pkg/service/admission/apis/restrictedendpoints/v1/register.go
  pkg/service/admission/apis/restrictedendpoints/v1/types.go
  pkg/service/admission/apis/restrictedendpoints/v1/zz_generated.deepcopy.go
  pkg/service/admission/apis/restrictedendpoints/zz_generated.deepcopy.go
  pkg/service/admission/externalipranger/externalip_admission.go
  pkg/service/admission/externalipranger/externalip_admission_test.go
  pkg/service/admission/restrictedendpoints/endpoint_admission.go
  test/integration/endpoint_admission_test.go
Labels: approved, lgtm, sig/master, size/XL

#20713 Add Automation Service Broker Owners
  install/automationservicebroker/OWNERS
Labels: approved, lgtm, size/XS

#20715 Update OWNERS for automation service broker oc cluster component
  pkg/oc/clusteradd/components/automation-service-broker/OWNERS
Labels: approved, lgtm, size/XS

#20665 switch to using upstream patch cmd
  hack/lib/start.sh
  test/extended/gssapi.sh
  test/extended/setup.sh
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/patch.go
Labels: approved, lgtm, size/M

#20720 always pull image before rebuilding local images
  hack/build-local-images.py
Labels: approved, lgtm, size/XS

#20662 UPSTREAM: 67236: fix azure disk create failure due to sdk upgrade
  vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/azure/azure_blobDiskController.go
Labels: approved, lgtm, sig/storage, size/XS

#20711 switch template controller to external
  pkg/api/legacy/install.go
  pkg/cmd/openshift-controller-manager/controller/template.go
  pkg/template/controller/metrics.go
  pkg/template/controller/readiness.go
  pkg/template/controller/readiness_test.go
  pkg/template/controller/templateinstance_controller.go
  pkg/template/controller/templateinstance_controller_test.go
  pkg/template/controller/templateinstance_finalizer.go
  test/extended/templates/helpers.go
Labels: approved, lgtm, size/XL

#20583 Update the Automation Broker APB command
  install/automationservicebroker/install.yaml
  pkg/oc/clusteradd/components/automation-service-broker/automation_service_broker.go
  pkg/oc/clusterup/manifests/bindata.go
  test/extended/testdata/bindata.go
Labels: approved, lgtm, size/M

#20717 RPMS - Add stub /etc/sysconfig/origin-node
  contrib/systemd/origin-node.sysconfig
  origin.spec
Labels: approved, lgtm, size/XS

#20735 git: copy struct fields and lose the s2i dependency
  pkg/git/repository.go
Labels: approved, lgtm, size/M

#20588 OAuth server (osin/sally) refactors
  hack/import-restrictions.json
  pkg/oauthserver/authenticator/identitymapper/identitymapper.go
  pkg/oauthserver/authenticator/password/allowanypassword/anyauthpassword.go
  pkg/oauthserver/authenticator/password/basicauthpassword/basicauthpassword.go
  pkg/oauthserver/authenticator/password/htpasswd/htpasswd.go
  pkg/oauthserver/authenticator/password/keystonepassword/keystonepassword.go
  pkg/oauthserver/authenticator/password/ldappassword/ldap.go
  pkg/oauthserver/authenticator/request/headerrequest/requestheader.go
  pkg/oauthserver/doc.go
  pkg/oauthserver/mux.go
  pkg/oauthserver/oauth/external/handler.go
  pkg/oauthserver/oauth/external/handler_test.go
  pkg/oauthserver/oauth/registry/registry_test.go
  pkg/oauthserver/oauth/registry/userconversion.go
  pkg/oauthserver/oauthserver/auth.go
  pkg/oauthserver/oauthserver/handler_wrapper.go
  pkg/oauthserver/oauthserver/mux.go
  pkg/oauthserver/oauthserver/oauth_apiserver.go
  pkg/oauthserver/oauthserver/oauth_apiserver_test.go
  pkg/oauthserver/osinserver/interfaces.go
  pkg/oauthserver/osinserver/osinserver.go
  pkg/oauthserver/osinserver/registrystorage/storage.go
  pkg/oauthserver/osinserver/tokengen.go
  pkg/oauthserver/server/crypto/compare.go
  pkg/oauthserver/server/crypto/random.go
  pkg/oauthserver/server/csrf/cookie.go
  pkg/oauthserver/server/csrf/cookie_test.go
  pkg/oauthserver/server/csrf/empty.go
  pkg/oauthserver/server/csrf/fake.go
  pkg/oauthserver/server/csrf/interfaces.go
  pkg/oauthserver/server/csrf/session.go
  pkg/oauthserver/server/grant/grant.go
  pkg/oauthserver/server/grant/interfaces.go
  pkg/oauthserver/server/headers/headers.go
  pkg/oauthserver/server/login/helper.go
  pkg/oauthserver/server/login/login.go
  pkg/oauthserver/server/redirect/redirect.go
  pkg/oauthserver/server/session/authenticator.go
  pkg/oauthserver/server/session/interfaces.go
  pkg/oauthserver/server/session/session.go
  pkg/oauthserver/server/session/types.go
  pkg/oauthserver/server/tokenrequest/endpoints.go
  pkg/oauthserver/userregistry/identitymapper/lookup.go
  pkg/oauthserver/userregistry/identitymapper/provision.go
  pkg/oauthserver/userregistry/identitymapper/user.go
  pkg/oc/lib/newapp/app/app.go
  pkg/user/apiserver/registry/user/etcd/etcd.go
  test/integration/groups_test.go
  test/integration/oauthstorage_test.go
  test/integration/scopes_test.go
  test/integration/webhook_token_auth_test.go
Labels: approved, lgtm, size/XXL

#20578 add kube-apiserver wiring
  hack/import-restrictions.json
  install/kube-dns/install.yaml
  install/kube-proxy/install.yaml
  pkg/cmd/openshift-apiserver/openshiftapiserver/openshift_apiserver.go
  pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/flags.go
  pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/patch.go
  pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/patch_handlerchain.go
  pkg/cmd/openshift-kube-apiserver/server.go
  pkg/cmd/server/origin/admission/chain_builder.go
  pkg/cmd/server/origin/admission/config_test.go
  pkg/cmd/server/origin/admission/register.go
  pkg/cmd/server/origin/admission/sync_test.go
  pkg/cmd/server/origin/master.go
  pkg/oc/clusterup/manifests/bindata.go
  test/extended/testdata/bindata.go
  test/integration/master_routes_test.go
  vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/aggregator.go
  vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/patch_openshift.go
  vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go
  vendor/k8s.io/kubernetes/pkg/kubeapiserver/options/patch.go
  vendor/k8s.io/kubernetes/pkg/kubeapiserver/options/plugins.go
  vendor/k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/patch_policy.go
  vendor/k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/options/admission.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/options/patch_admission.go
Labels: approved, lgtm, size/XL

#20697 oc debug: fix crash on attach
  pkg/oc/cli/debug/debug.go
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/attach.go
Labels: approved, lgtm, size/S

#20721 accept --kubeconfig like kubectl
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  hack/test-cmd.sh
  test/cmd/login.sh
  test/cmd/policy.sh
  test/cmd/status.sh
  test/extended/alternate_certs.sh
  vendor/k8s.io/kubernetes/pkg/kubectl/genericclioptions/config_flags.go
Labels: approved, lgtm, size/XL

#20730 Fix NameFromCommandArgs when passing command after --
  pkg/oc/cli/create/create.go
  test/cmd/create.sh
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/create/create.go
Labels: approved, lgtm, size/S

#20621 Restore test for image signature workflow
  test/extended/images/hardprune.go
  test/extended/images/signatures.go
  test/extended/util/framework.go
Labels: approved, lgtm, size/L

#20734 use upstream install function
  cmd/oc/oc.go
  glide.lock
  vendor/github.com/openshift/api/install.go
  vendor/github.com/openshift/api/template/v1/consts.go
Labels: approved, lgtm, size/M

#20117 UPSTREAM: 65447: Resolve potential devicePath symlink when MapVolume
  vendor/k8s.io/kubernetes/pkg/kubelet/cm/container_manager_linux_test.go
  vendor/k8s.io/kubernetes/pkg/util/mount/exec_mount.go
  vendor/k8s.io/kubernetes/pkg/util/mount/exec_mount_test.go
  vendor/k8s.io/kubernetes/pkg/util/mount/exec_mount_unsupported.go
  vendor/k8s.io/kubernetes/pkg/util/mount/fake.go
  vendor/k8s.io/kubernetes/pkg/util/mount/mount.go
  vendor/k8s.io/kubernetes/pkg/util/mount/mount_linux.go
  vendor/k8s.io/kubernetes/pkg/util/mount/mount_unsupported.go
  vendor/k8s.io/kubernetes/pkg/util/mount/mount_windows.go
  vendor/k8s.io/kubernetes/pkg/util/mount/nsenter_mount.go
  vendor/k8s.io/kubernetes/pkg/util/mount/nsenter_mount_unsupported.go
  vendor/k8s.io/kubernetes/pkg/util/removeall/removeall_test.go
  vendor/k8s.io/kubernetes/pkg/volume/host_path/host_path_test.go
  vendor/k8s.io/kubernetes/pkg/volume/util/operationexecutor/operation_generator.go
Labels: approved, lgtm, sig/storage, size/L

#20439 UPSTREAM: 66397: Fix upper limit on m5/c5 instance typesn
  vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/predicates/max_attachable_volume_predicate_test.go
  vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/predicates/predicates.go
  vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/predicates/predicates_test.go
Labels: approved, lgtm, sig/storage, size/M

#20663 UPSTREAM: 66835: cloudprovider: aws: return true on existence check for stopped instances
  vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws.go
  vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws_test.go
Labels: approved, lgtm, sig/storage, size/M

#20475 Egress DNS proxy router: Allow load distribution when domain resolves to multiple IP addrs
  images/egress/dns-proxy/egress-dns-proxy.sh
  images/egress/dns-proxy/egress_dns_proxy_test.go
Labels: approved, lgtm, sig/network-edge, size/L

#20756 UPSTREAM: 67822: Remove provisioner config from log message.
  vendor/k8s.io/kubernetes/pkg/volume/glusterfs/glusterfs.go
Labels: approved, lgtm, size/XS

#20765 wait longer for the builder service account
  test/extended/util/framework.go
Labels: approved, lgtm, retest-not-required, size/XS

#20762 Some build pushes can take less than a second
  test/extended/builds/build_timing.go
Labels: approved, lgtm, retest-not-required, size/XS

#20774 Bug 1609676 - Fix missing bind values regression
  pkg/templateservicebroker/servicebroker/bind.go
  pkg/templateservicebroker/servicebroker/bind_test.go
Labels: approved, lgtm, size/S

#20778 Remove count from new-build/new-app error message
  pkg/oc/lib/newapp/app/errors.go
  test/cmd/newapp.sh
Labels: approved, lgtm, size/XS

#20485 HA for fully-automatic egress IPs
  pkg/network/common/egressip.go
  pkg/network/common/egressip_test.go
  pkg/network/master/egressip.go
Labels: approved, component/networking, lgtm, sig/networking, size/L

#20733 Minor fixup to egress IP monitoring
  pkg/network/node/vxlan_monitor.go
  pkg/network/node/vxlan_monitor_test.go
Labels: approved, component/networking, kind/bug, lgtm, sig/networking, size/L

#20785 use v3.10 version of Service Catalog
  test/extended/clusterup.sh
Labels: approved, lgtm, size/XS

#20486 Show EgressCIDRs in "oc get hostsubnets"
  pkg/oc/lib/describe/describer.go
  pkg/printers/internalversion/printer.go
Labels: approved, component/cli, component/networking, kind/bug, lgtm, sig/networking, size/XS

#20781 Revert "new-app: verify if API has required resources enabled"
  pkg/oc/cli/newapp/newapp.go
  pkg/oc/lib/newapp/cmd/newapp.go
Labels: approved, lgtm, size/M

#20409 Fix ovn script so that apiserver can be fetched correctly
  images/dind/master/ovn-kubernetes-master.sh
Labels: approved, lgtm, size/XS

#20791 remove jim-minter from OWNERS files
  examples/db-templates/OWNERS
  examples/gitserver/OWNERS
  examples/jenkins/OWNERS
  pkg/git/OWNERS
  pkg/gitserver/OWNERS
  pkg/oc/clusteradd/components/register-template-service-broker/OWNERS
  pkg/oc/clusteradd/components/template-service-broker/OWNERS
  pkg/oc/clusterup/OWNERS
  pkg/oc/clusterup/docker/openshift/OWNERS
  pkg/oc/lib/newapp/OWNERS
  pkg/openapi/OWNERS
  pkg/template/OWNERS
  pkg/templateservicebroker/openservicebroker/OWNERS
  test/extended/OWNERS
  test/testdata/OWNERS
Labels: size/S

#20777 clean up construction to make creating types more obvious
  pkg/apps/apiserver/registry/deployconfig/etcd/etcd.go
  pkg/authorization/apiserver/registry/rolebindingrestriction/etcd/etcd.go
  pkg/build/apiserver/registry/build/etcd/etcd.go
  pkg/build/apiserver/registry/buildconfig/etcd/etcd.go
  pkg/cmd/openshift-apiserver/openshiftapiserver/config.go
  pkg/cmd/openshift-apiserver/openshiftapiserver/configprocessing/cloud.go
  pkg/cmd/openshift-apiserver/openshiftapiserver/configprocessing/etcd.go
  pkg/cmd/openshift-apiserver/openshiftapiserver/restoptionsgetter.go
  pkg/cmd/openshift-apiserver/server.go
  pkg/cmd/openshift-controller-manager/controller_manager.go
  pkg/cmd/server/kubernetes/master/master_config.go
  pkg/cmd/server/origin/admission/plugin_initializer.go
  pkg/cmd/server/origin/master.go
  pkg/cmd/server/origin/master_config.go
  pkg/cmd/server/origin/rest/storage_options.go
  pkg/cmd/server/start/master_args.go
  pkg/cmd/util/flags/flags.go
  pkg/image/apiserver/registry/image/etcd/etcd.go
  pkg/image/apiserver/registry/image/etcd/etcd_test.go
  pkg/image/apiserver/registry/imagestream/etcd/etcd.go
  pkg/image/apiserver/registry/imagestream/etcd/etcd_test.go
  pkg/image/apiserver/registry/imagestreamimage/rest_test.go
  pkg/image/apiserver/registry/imagestreammapping/rest_test.go
  pkg/image/apiserver/registry/imagestreamtag/rest_test.go
  pkg/network/apiserver/registry/clusternetwork/etcd/etcd.go
  pkg/network/apiserver/registry/egressnetworkpolicy/etcd/etcd.go
  pkg/network/apiserver/registry/hostsubnet/etcd/etcd.go
  pkg/network/apiserver/registry/netnamespace/etcd/etcd.go
  pkg/oauth/apiserver/registry/oauthaccesstoken/etcd/etcd.go
  pkg/oauth/apiserver/registry/oauthauthorizetoken/etcd/etcd.go
  pkg/oauth/apiserver/registry/oauthclient/etcd/etcd.go
  pkg/oauth/apiserver/registry/oauthclientauthorization/etcd/etcd.go
  pkg/oc/clusterup/coreinstall/kubeapiserver/config.go
  pkg/quota/apiserver/registry/clusterresourcequota/etcd/etcd.go
  pkg/route/apiserver/registry/route/etcd/etcd.go
  pkg/route/apiserver/registry/route/etcd/etcd_test.go
  pkg/template/apiserver/registry/brokertemplateinstance/etcd/etcd.go
  pkg/template/apiserver/registry/template/etcd/etcd.go
  pkg/template/apiserver/registry/templateinstance/etcd/etcd.go
  pkg/user/apiserver/registry/group/etcd/etcd.go
  pkg/user/apiserver/registry/identity/etcd/etcd.go
  pkg/user/apiserver/registry/user/etcd/etcd.go
  pkg/util/restoptions/configgetter.go
  pkg/util/restoptions/interfaces.go
  pkg/util/restoptions/simplegetter.go
  test/integration/etcd_storage_path_test.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/options/etcd.go
Labels: approved, lgtm, size/XL

#20797 use version specific component images w/ cluster up tests
  test/extended/clusterup.sh
Labels: approved, lgtm, size/XS

#20790 add skip-tags to publishing kube rules
  publishing-kube-rules.yaml
Labels: approved, lgtm, size/XS

#20779 tighten admission to avoid unnecessary pieces of config
  pkg/build/apiserver/admission/jenkinsbootstrapper/admission.go
  pkg/build/apiserver/admission/jenkinsbootstrapper/initializer.go
  pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/patch.go
  pkg/cmd/server/admission/init.go
  pkg/cmd/server/admission/types.go
  pkg/cmd/server/origin/admission/plugin_initializer.go
Labels: approved, lgtm, size/M

#20725 remove alternate platforms from cluster up documentation
  docs/cluster_up_down.md
Labels: approved, lgtm, retest-not-required-docs-only, size/L

#20783 UPSTREAM: 67957: Size http2 buffers to allow concurrent streams
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/serve.go
Labels: approved, lgtm, size/S

#20799 apps: raise trigger timeout for slow servers
  test/extended/deployments/deployments.go
  test/extended/deployments/util.go
Labels: approved, lgtm, size/XS

#20130 [3.10] Allow configuration of ResourceGroup in Azure StorageClass
  vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/azure/azure_managedDiskController.go
  vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/azure/azure_test.go
  vendor/k8s.io/kubernetes/pkg/volume/azure_dd/azure_dd.go
  vendor/k8s.io/kubernetes/pkg/volume/azure_dd/azure_provision.go
Labels: approved, lgtm, sig/storage, size/M

#20793 UPSTREAM: 68007: Orphan DaemonSet when deleting with --cascade option set
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/delete.go
Labels: approved, lgtm, size/XS

#20769 External image controller
  hack/import-restrictions.json
  pkg/build/controller/build/build_controller.go
  pkg/build/controller/build/build_controller_test.go
  pkg/cmd/openshift-apiserver/openshiftapiserver/informers.go
  pkg/cmd/openshift-controller-manager/controller/build.go
  pkg/cmd/openshift-controller-manager/controller/image.go
  pkg/cmd/openshift-controller-manager/controller/interfaces.go
  pkg/cmd/openshift-controller-manager/controller/quota.go
  pkg/cmd/server/origin/admission/plugin_initializer.go
  pkg/cmd/server/origin/informers.go
  pkg/cmd/server/origin/master_config.go
  pkg/image/apis/image/helper.go
  pkg/image/apis/image/reference/reference.go
  pkg/image/apis/image/v1/helpers.go
  pkg/image/controller/factory.go
  pkg/image/controller/imagestream_controller.go
  pkg/image/controller/imagestream_controller_test.go
  pkg/image/controller/metrics.go
  pkg/image/controller/scheduled_image_controller.go
  pkg/image/controller/scheduled_image_controller_test.go
  pkg/image/controller/signature/container_image_downloader.go
  pkg/image/controller/signature/signature_import_controller.go
  pkg/image/controller/signature/signature_import_controller_test.go
  pkg/image/controller/trigger/image_trigger_controller.go
  pkg/image/controller/trigger/image_trigger_controller_test.go
  pkg/image/generated/internalclientset/typed/image/internalversion/generated_expansion.go
  pkg/image/generated/internalclientset/typed/image/internalversion/imagestreamimport_expansion.go
  pkg/image/internal/digest/digest.go
  pkg/image/internal/digest/digester.go
  pkg/image/internal/digest/doc.go
  pkg/image/internal/reference/doc.go
  pkg/image/internal/reference/reference.go
  pkg/image/internal/reference/regexp.go
  pkg/image/util/helpers.go
  pkg/image/util/testutil/util.go
  pkg/oc/cli/admin/prune/imageprune/prune.go
  pkg/oc/lib/graph/buildgraph/analysis/bc.go
  pkg/quota/image/imagestreamimport_evaluator.go
  pkg/quota/image/imagestreamimport_evaluator_test.go
  pkg/quota/image/imagestreamtag_evaluator.go
  pkg/quota/image/imagestreamtag_evaluator_test.go
  pkg/quota/image/registry.go
Labels: approved, lgtm, size/XXL

#20803 UPSTREAM: 67822: Remove provisioner config from log message
  vendor/k8s.io/kubernetes/pkg/volume/glusterfs/glusterfs.go
Labels: approved, lgtm, size/XS

#20787 make a kube-apiserver config struct
  pkg/cmd/openshift-apiserver/cmd.go
  pkg/cmd/openshift-apiserver/conversion.go
  pkg/cmd/openshift-apiserver/openshiftapiserver/config.go
  pkg/cmd/openshift-apiserver/openshiftapiserver/configprocessing/openapi.go
  pkg/cmd/openshift-apiserver/openshiftapiserver/configprocessing/routeallocator.go
  pkg/cmd/openshift-apiserver/openshiftapiserver/restoptionsgetter.go
  pkg/cmd/openshift-apiserver/server.go
  pkg/cmd/openshift-kube-apiserver/cmd.go
  pkg/cmd/openshift-kube-apiserver/conversion.go
  pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/flags.go
  pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/handlers.go
  pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/handlers_test.go
  pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/nonapiserver.go
  pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/patch.go
  pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/patch_authenticator.go
  pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/patch_handlerchain.go
  pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/patch_oauthserver.go
  pkg/cmd/openshift-kube-apiserver/server.go
  pkg/cmd/server/apis/config/helpers.go
  pkg/cmd/server/apis/config/types.go
  pkg/cmd/server/apis/config/zz_generated.deepcopy.go
  pkg/cmd/server/kubernetes/master/master_config.go
  pkg/cmd/server/kubernetes/master/master_config_test.go
  pkg/cmd/server/origin/admission/chain_builder.go
  pkg/cmd/server/origin/admission/config_test.go
  pkg/cmd/server/origin/admission/plugin_initializer.go
  pkg/cmd/server/origin/master.go
  pkg/cmd/server/origin/master_config.go
  pkg/oauth/util/discovery.go
Labels: approved, lgtm, size/XL

#20795 clean up owners
  OWNERS
  cmd/OWNERS
  cmd/gitserver/OWNERS
  cmd/oc/OWNERS
  cmd/openshift/OWNERS
  examples/image-streams/OWNERS
  examples/jenkins/OWNERS
  examples/sample-app/OWNERS
  hack/OWNERS
  hack/lib/OWNERS
  images/recycler/OWNERS
  pkg/OWNERS
  pkg/api/OWNERS
  pkg/authorization/OWNERS
  pkg/bulk/OWNERS
  pkg/cmd/OWNERS
  pkg/dns/OWNERS
  pkg/gitserver/OWNERS
  pkg/image/OWNERS
  pkg/oauth/OWNERS
  pkg/oauthserver/OWNERS
  pkg/oc/cli/admin/diagnostics/diagnostics/OWNERS
  pkg/oc/cli/admin/ipfailover/ipfailover/OWNERS
  pkg/oc/cli/admin/prune/imageprune/OWNERS
  pkg/openapi/OWNERS
  pkg/project/OWNERS
  pkg/quota/OWNERS
  pkg/route/OWNERS
  pkg/scheduler/OWNERS
  pkg/serviceaccounts/OWNERS
  pkg/unidling/OWNERS
  pkg/user/OWNERS
  pkg/util/OWNERS
  pkg/version/OWNERS
  test/OWNERS
  test/end-to-end/OWNERS
  test/integration/OWNERS
  test/old-start-configs/OWNERS
  test/testdata/OWNERS
  test/util/OWNERS
  tools/OWNERS
  tools/gendocs/OWNERS
  tools/junitreport/OWNERS
  tools/rebasehelpers/OWNERS
Labels: approved, size/M
