Repository openshift/origin, pull requests merged in 2018-06, with the labels that each got.

#19908 up: default openshift imagepolicy admission
  pkg/oc/clusterup/coreinstall/kubeapiserver/openshift_apiserver.go
Labels: approved, lgtm, size/S

#19898 UPSTREAM: 64573: remove extra "../" when copying from pod to local
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cp.go
Labels: approved, lgtm, size/S

#19912 build: handle empty commits in bitbucket webhook payload
  pkg/build/webhook/bitbucket/bitbucket.go
Labels: approved, lgtm, size/XS

#19917 add support to build different tags in hack script
  hack/build-local-images.py
Labels: approved, lgtm, size/S

#19672 UPSTREAM: 63650: Never clean backoff in job controller
  vendor/k8s.io/kubernetes/pkg/controller/job/job_controller.go
  vendor/k8s.io/kubernetes/pkg/controller/job/job_controller_test.go
  vendor/k8s.io/kubernetes/test/e2e/apps/job.go
Labels: approved, lgtm, size/L

#19916 Make API storage migration less sensitive to conflicts
  pkg/oc/admin/migrate/storage/storage.go
Labels: approved, kind/bug, lgtm, size/S

#19915 Hide deprecated commands
  pkg/oc/cli/cmd/buildlogs.go
  pkg/oc/cli/cmd/deploy.go
  pkg/oc/cli/cmd/export.go
  pkg/oc/cli/secrets/basicauth.go
  pkg/oc/cli/secrets/dockercfg.go
  pkg/oc/cli/secrets/new.go
  pkg/oc/cli/secrets/sshauth.go
Labels: approved, lgtm, size/S

#19867 support the --output flag in 'oc create route'
  pkg/oc/cli/cmd/create/route.go
Labels: approved, lgtm, size/S

#19923 Add Dan Mace (ironcladlou) to relevant OWNERS
  images/dind/OWNERS
  images/egress/OWNERS
  images/ipfailover/OWNERS
  images/router/OWNERS
  pkg/cmd/infra/router/OWNERS
  pkg/oc/admin/router/OWNERS
  pkg/route/OWNERS
  pkg/router/OWNERS
  test/cmd/OWNERS
  test/end-to-end/OWNERS
  test/extended/OWNERS
  test/integration/OWNERS
  test/testdata/OWNERS
Labels: approved, lgtm, size/S

#19927 UPSTREAM: 64797: Handle deleted DaemonSet properly
  vendor/k8s.io/kubernetes/pkg/controller/daemon/daemon_controller.go
Labels: approved, lgtm, size/S

#19901 Use fully qualified pod test image names in network diagnostics
  pkg/oc/admin/diagnostics/diagnostics/cluster/network/in_pod/util/util.go
  pkg/oc/admin/diagnostics/diagnostics/cluster/network/in_pod/util/util_test.go
  pkg/oc/admin/diagnostics/diagnostics/cluster/network/objects.go
Labels: approved, component/diagnostics, kind/bug, lgtm, size/M

#19574 [diagnostics] Catch error from NewForConfig() as a new assigned error value
  pkg/oc/admin/diagnostics/diagnostics/client/config_contexts.go
Labels: approved, lgtm, size/XS

#19834 Add extended tests for oc image mirror
  test/extended/images/mirror.go
  test/extended/util/test.go
Labels: approved, area/tests, component/cli, lgtm, size/L

#19918 add support to build different tags in hack script
  hack/build-local-images.py
Labels: approved, lgtm, size/S

#19935 Poll metrics for openshift resources
  pkg/util/restoptions/configgetter.go
Labels: approved, lgtm, size/XS

#19934 Add server-side column printer support for openshift objects
  hack/import-restrictions.json
  pkg/apps/registry/deployconfig/etcd/etcd.go
  pkg/authorization/registry/clusterrole/proxy.go
  pkg/authorization/registry/clusterrolebinding/proxy.go
  pkg/authorization/registry/role/proxy.go
  pkg/authorization/registry/rolebinding/proxy.go
  pkg/authorization/registry/rolebindingrestriction/etcd/etcd.go
  pkg/build/registry/build/etcd/etcd.go
  pkg/build/registry/buildconfig/etcd/etcd.go
  pkg/cmd/server/origin/master_config.go
  pkg/image/registry/image/etcd/etcd.go
  pkg/image/registry/imagestream/etcd/etcd.go
  pkg/image/registry/imagestreamimage/rest.go
  pkg/image/registry/imagestreamtag/rest.go
  pkg/network/registry/clusternetwork/etcd/etcd.go
  pkg/network/registry/egressnetworkpolicy/etcd/etcd.go
  pkg/network/registry/hostsubnet/etcd/etcd.go
  pkg/network/registry/netnamespace/etcd/etcd.go
  pkg/oauth/registry/oauthaccesstoken/etcd/etcd.go
  pkg/oauth/registry/oauthauthorizetoken/etcd/etcd.go
  pkg/oauth/registry/oauthclient/etcd/etcd.go
  pkg/oauth/registry/oauthclientauthorization/etcd/etcd.go
  pkg/oc/cli/describe/helpers.go
  pkg/oc/cli/describe/imports.go
  pkg/printers/internalversion/helpers.go
  pkg/printers/internalversion/printer.go
  pkg/printers/internalversion/printer_test.go
  pkg/project/registry/project/proxy/proxy.go
  pkg/quota/registry/appliedclusterresourcequota/filter.go
  pkg/quota/registry/clusterresourcequota/etcd/etcd.go
  pkg/route/registry/route/etcd/etcd.go
  pkg/security/registry/rangeallocations/etcd.go
  pkg/security/registry/securitycontextconstraints/etcd/etcd.go
  pkg/template/registry/brokertemplateinstance/etcd/etcd.go
  pkg/template/registry/template/etcd/etcd.go
  pkg/template/registry/templateinstance/etcd/etcd.go
  pkg/user/registry/group/etcd/etcd.go
  pkg/user/registry/identity/etcd/etcd.go
  pkg/user/registry/user/etcd/etcd.go
  pkg/util/registry/wrapper.go
  vendor/k8s.io/kubernetes/pkg/printers/humanreadable.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/registry/rest/resttest/resttest.go
Labels: approved, component/cli, component/restapi, lgtm, sig/master, size/L

#19939 UPSTREAM: 64855: Fix setup of ephemeral storage
  vendor/k8s.io/kubernetes/pkg/volume/configmap/configmap.go
  vendor/k8s.io/kubernetes/pkg/volume/downwardapi/downwardapi.go
  vendor/k8s.io/kubernetes/pkg/volume/projected/projected.go
  vendor/k8s.io/kubernetes/pkg/volume/secret/secret.go
  vendor/k8s.io/kubernetes/test/e2e/storage/BUILD
  vendor/k8s.io/kubernetes/test/e2e/storage/ephemeral_volume.go
Labels: approved, lgtm, sig/storage, size/L

#19950 Do not throw spurious error when minTTL=0 for the domain in egress network policy
  pkg/network/common/dns.go
Labels: approved, component/networking, lgtm, sig/networking, size/S

#19924 Add Casey Callendrello (squeed) to the relevant OWNERS files
  images/dind/OWNERS
  pkg/cmd/OWNERS
  pkg/cmd/server/kubernetes/network/OWNERS
  pkg/network/OWNERS
  pkg/proxy/OWNERS
  pkg/util/ovs/OWNERS
  test/cmd/OWNERS
  test/end-to-end/OWNERS
  test/extended/OWNERS
  test/integration/OWNERS
  test/testdata/OWNERS
Labels: approved, lgtm, size/S

#19953 Set etcd DialTimeout, fix etcd start order in all-in-one
  pkg/cmd/server/start/start_master.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3.go
Labels: approved, lgtm, size/M

#19956 UPSTREAM: 64916: improve memory footprint of daemonset simulate
  vendor/k8s.io/kubernetes/pkg/controller/daemon/BUILD
  vendor/k8s.io/kubernetes/pkg/controller/daemon/daemon_controller.go
Labels: approved, lgtm, size/S

#19960 UPSTREAM: 64969: volume: decrease memory allocations for debugging messages
  vendor/k8s.io/kubernetes/pkg/controller/volume/attachdetach/reconciler/reconciler.go
Labels: approved, lgtm, size/S

#19959 Prevent a router panic when ROUTER_BIND_PORTS_AFTER_SYNC is set
  pkg/cmd/infra/router/template.go
  pkg/router/metrics/health.go
Labels: approved, component/routing, kind/bug, lgtm, size/S

#19943 Update set commands
  pkg/oc/cli/cmd/set/buildhook.go
  pkg/oc/cli/cmd/set/buildsecret.go
  pkg/oc/cli/cmd/set/deploymenthook.go
  pkg/oc/cli/cmd/set/imagelookup.go
  pkg/oc/cli/cmd/set/probe.go
  pkg/oc/cli/cmd/set/routebackends.go
  pkg/oc/cli/cmd/set/set.go
  pkg/oc/cli/cmd/set/triggers.go
  pkg/oc/cli/cmd/set/volume.go
  test/cmd/deployments.sh
  test/cmd/image-lookup.sh
  test/cmd/routes.sh
  test/cmd/set-liveness-probe.sh
  test/cmd/setbuildhook.sh
  test/cmd/setbuildsecret.sh
  test/cmd/triggers.sh
  test/cmd/volumes.sh
Labels: approved, size/XXL

#19970 UPSTREAM: 65001: Quiet verbose apiserver logs
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/get.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/storage/etcd3/watcher.go
Labels: approved, lgtm, size/XS

#19980 UPSTREAM: 65009: daemon: add custom node indexer
  vendor/k8s.io/kubernetes/pkg/controller/daemon/daemon_controller.go
  vendor/k8s.io/kubernetes/pkg/controller/daemon/daemon_controller_test.go
Labels: approved, lgtm, size/M

#19892 restrict upstream patches to k8s.io/kubernetes only
  tools/rebasehelpers/commitchecker/validate.go
Labels: approved, lgtm, size/S

#19994 use release-3.10 for deps
  glide.lock
  glide.yaml
  vendor/github.com/golang/glog/README
  vendor/github.com/golang/glog/glog.go
  vendor/github.com/gorilla/securecookie/AUTHORS
  vendor/github.com/gorilla/securecookie/LICENSE
  vendor/github.com/openshift/client-go/glide.lock
  vendor/github.com/openshift/client-go/glide.yaml
  vendor/github.com/openshift/imagebuilder/dockerclient/client.go
  vendor/github.com/openshift/library-go/glide.lock
  vendor/github.com/openshift/library-go/glide.yaml
  vendor/github.com/openshift/service-serving-cert-signer/glide.lock
  vendor/github.com/openshift/service-serving-cert-signer/glide.yaml
Labels: approved, lgtm, size/M

#19982 Egress DNS: Get lowest TTL from the dns resolution chain
  pkg/network/common/dns.go
  pkg/network/common/dns_test.go
Labels: approved, lgtm, sig/networking, size/S

#19963 Replace Perl with Bash in router echo test server
  test/extended/testdata/bindata.go
  test/extended/testdata/router-http-echo-server.yaml
Labels: approved, kind/bug, lgtm, size/XS

#19992 etcd healthz, hotloop fixes
  glide.lock
  glide.yaml
  pkg/cmd/server/origin/webconsole_proxy.go
  vendor/github.com/coreos/etcd/clientv3/client.go
  vendor/github.com/coreos/etcd/clientv3/watch.go
  vendor/github.com/google/cadvisor/container/crio/handler.go
  vendor/github.com/google/cadvisor/container/docker/handler.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/options/BUILD
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/options/etcd.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd2.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/storage/storagebackend/factory/factory.go
Labels: approved, lgtm, size/L

#19929 diagnostics: replace usage of brctl with /sbin/ip
  pkg/oc/admin/diagnostics/diagnostics/cluster/network/in_pod/util/log.go
Labels: approved, component/diagnostics, lgtm, size/XS

#20003 Update set probe (part 2)
  pkg/oc/cli/cmd/set/probe.go
  test/cmd/basicresources.sh
Labels: approved, size/M

#20006 add kube staging publish rules
  publishing-kube-rules.yaml
Labels: approved, lgtm, size/M

#19990 [release-3.9] Replace Perl with Bash in router echo test server
  test/extended/testdata/bindata.go
  test/extended/testdata/router-http-echo-server.yaml
Labels: approved, kind/bug, lgtm, size/XS

#19987 Remove the node from dnsmasq config when shutting down
  pkg/cmd/server/kubernetes/network/network.go
  pkg/cmd/server/kubernetes/network/options/options.go
  pkg/cmd/server/origin/dns_server.go
  pkg/cmd/server/start/start_allinone.go
  pkg/cmd/server/start/start_node.go
  pkg/dns/dnsmasq.go
  pkg/dns/dnsmasq_test.go
  pkg/dns/server.go
  pkg/dns/serviceaccessor.go
  test/util/server/server.go
Labels: approved, lgtm, size/L

#20000 UPSTREAM: 65063: Re-use private key after failed CSR
  vendor/k8s.io/kubernetes/pkg/kubelet/certificate/bootstrap/bootstrap.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/util/cert/io.go
Labels: approved, lgtm, size/M

#20014 Image mirror doesn't print out tag in error
  pkg/oc/cli/cmd/image/mirror/mirror.go
Labels: approved, lgtm, size/XS

#19911 [3.9] up: default openshift imagepolicy admission
  pkg/oc/bootstrap/docker/openshift/helper.go
Labels: approved, lgtm, sig/networking, size/XS

#19307 Include the keyword Area:Networking for NetworkPolicy tests
  test/extended/networking/networkpolicy.go
Labels: approved, lgtm, size/XS

#17469 Fix deployer pod tolerations
  pkg/apps/controller/deployer/deployer_controller.go
Labels: approved, lgtm, size/XS

#20015 serviceaccounts: do not manage pull secrets created by third parties
  pkg/serviceaccounts/controllers/docker_registry_service.go
Labels: approved, lgtm, priority/critical-urgent, size/XS

#19951 Fix to pass quoted unsafe strings (with characters like *,<,%) correctly to kubelet
  images/node/scripts/openshift-node
Labels: approved, lgtm, size/XS

#19919 Service Catalog patch update to v0.1.9.1
  cmd/service-catalog/go/src/github.com/kubernetes-incubator/service-catalog/pkg/apis/servicecatalog/validation/binding.go
  cmd/service-catalog/go/src/github.com/kubernetes-incubator/service-catalog/pkg/apis/servicecatalog/validation/binding_test.go
  cmd/service-catalog/go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller_broker.go
  cmd/service-catalog/go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller_broker_test.go
  cmd/service-catalog/go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller_test.go
Labels: approved, lgtm, size/M

#20013 Fix default image paths used in network diagnostics
  pkg/oc/admin/diagnostics/diagnostics/cluster/network/in_pod/util/util.go
Labels: approved, component/diagnostics, lgtm, size/S

#20023 disable mysql replica entirely
  test/extended/image_ecosystem/mysql_replica.go
Labels: approved, lgtm, size/XS

#20011 Move deployer and build binaries into oc
  hack/import-restrictions.json
  hack/lib/build/binaries.sh
  hack/lib/constants.sh
  images/builder/docker/docker-builder/Dockerfile
  images/deployer/Dockerfile
  images/recycler/Dockerfile
  images/router/f5/Dockerfile
  images/router/haproxy/Dockerfile
  images/router/nginx/Dockerfile
  origin.spec
  pkg/cmd/openshift/openshift.go
  pkg/cmd/openshift/openshift_test.go
  pkg/oc/cli/cli.go
Labels: approved, lgtm, size/L

#20008 [3.11 pre-rebase] - Prepare to move pkg/build/builder out of openshift binary
  hack/import-restrictions.json
  pkg/apps/apis/apps/zz_generated.deepcopy.go
  pkg/build/builder/common.go
  pkg/build/builder/dockerutil.go
  pkg/build/controller/strategy/util.go
  pkg/image/apis/image/helper.go
  pkg/image/apis/image/reference.go
  pkg/image/apis/image/reference/reference.go
  pkg/image/apis/image/reference/reference_test.go
  pkg/image/apis/image/types.go
  pkg/image/apis/image/v1/zz_generated.conversion.go
  pkg/image/apis/image/zz_generated.deepcopy.go
  pkg/image/importer/dockerv1client/client.go
Labels: approved, lgtm, size/XL

#19983 Fix math division truncation in migrate storage
  pkg/oc/admin/migrate/storage/storage.go
Labels: approved, lgtm, size/XS

#19768 Replace uses of old policy RBAC types with new ones in oc
  hack/import-restrictions.json
  pkg/authorization/apis/authorization/casts.go
  pkg/authorization/apis/authorization/helpers.go
  pkg/authorization/apis/authorization/rbacconversion/conversion_test.go
  pkg/authorization/apis/authorization/rbacconversion/conversion_test_helper.go
  pkg/authorization/apis/authorization/zz_generated.deepcopy.go
  pkg/authorization/interfaces/interfaces.go
  pkg/authorization/rulevalidation/compact_rules.go
  pkg/authorization/rulevalidation/compact_rules_test.go
  pkg/authorization/rulevalidation/find_rules.go
  pkg/authorization/rulevalidation/policy_comparator_test.go
  pkg/authorization/rulevalidation/user_covers.go
  pkg/oc/admin/diagnostics/cluster.go
  pkg/oc/admin/diagnostics/diagnostics/cluster/aggregated_logging/clusterrolebindings_test.go
  pkg/oc/admin/diagnostics/diagnostics/cluster/aggregated_logging/diagnostic.go
  pkg/oc/admin/diagnostics/diagnostics/cluster/aggregated_logging/interfaces.go
  pkg/oc/admin/diagnostics/diagnostics/cluster/app_create/main.go
  pkg/oc/admin/diagnostics/diagnostics/cluster/app_create/setup_cleanup.go
  pkg/oc/admin/diagnostics/diagnostics/cluster/rolebindings.go
  pkg/oc/admin/diagnostics/diagnostics/cluster/roles.go
  pkg/oc/admin/policy/modify_roles.go
  pkg/oc/admin/policy/modify_roles_test.go
  pkg/oc/admin/policy/policy.go
  pkg/oc/admin/policy/reconcile_clusterrolebindings.go
  pkg/oc/admin/policy/reconcile_clusterroles.go
  pkg/oc/admin/policy/remove_from_project.go
  pkg/oc/admin/project/new_project.go
  pkg/oc/clusterup/coreinstall/components/persistent-volumes/setup_persistent_volumes.go
  test/cmd/admin.sh
  test/cmd/policy.sh
  test/extended/util/test.go
  test/integration/authorization_test.go
  test/integration/build_admission_test.go
  test/integration/imagechange_buildtrigger_test.go
  test/integration/imagesigning_test.go
  test/integration/login_test.go
  test/integration/pod_node_constraints_test.go
  test/integration/policy_commands_test.go
  test/integration/project_test.go
  test/integration/service_account_test.go
  test/util/server/server.go
  tools/testdebug/cmd/load_etcd.go
Labels: approved, area/security, lgtm, sig/security, size/XXL

#19964 Do not log Get failures for OAuthAccessToken lookups
  pkg/apiserver/authentication/internaloauth/tokenauthenticator.go
  pkg/apiserver/authentication/internaloauth/tokenauthenticator_test.go
Labels: approved, kind/bug, lgtm, sig/security, size/S

#20031 Fix a crash on a certain type of unsupported NetworkPolicy
  pkg/network/node/networkpolicy.go
Labels: approved, component/networking, kind/bug, lgtm, sig/networking, size/S

#20021 re-enable slave restart test
  test/extended/image_ecosystem/mysql_replica.go
  test/extended/util/db/mysql.go
Labels: approved, lgtm, size/S

#18775 Allow to reject login if the user id does not match the id in Keystone
  pkg/cmd/server/apis/config/types.go
  pkg/cmd/server/apis/config/v1/swagger_doc.go
  pkg/cmd/server/apis/config/v1/testdata/master-config.yaml
  pkg/cmd/server/apis/config/v1/types.go
  pkg/oauthserver/authenticator/password/keystonepassword/keystonepassword.go
  pkg/oauthserver/authenticator/password/keystonepassword/keystonepassword_test.go
  pkg/oauthserver/oauthserver/auth.go
Labels: approved, lgtm, needs-api-review, sig/security, size/L

#20032 Genericclioptions updates
  pkg/oc/cli/cmd/buildlogs.go
  pkg/oc/cli/cmd/cancelbuild.go
  pkg/oc/cli/cmd/cancelbuild_test.go
  pkg/oc/cli/cmd/cluster/cluster.go
  pkg/oc/cli/cmd/debug.go
  pkg/oc/cli/cmd/set/probe.go
  pkg/oc/clusteradd/cmd.go
  pkg/oc/clusterup/status.go
  pkg/oc/clusterup/up.go
  test/cmd/builds.sh
  test/cmd/debug.sh
  vendor/k8s.io/kubernetes/pkg/kubectl/polymorphichelpers/interface.go
  vendor/k8s.io/kubernetes/pkg/kubectl/polymorphichelpers/logsforobject_patch.go
Labels: size/XL

#20034 UPSTREAM: 65189: fix paths w shortcuts when copying from pods
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cp.go
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cp_test.go
Labels: approved, lgtm, size/M

#19639 Prune builds for Jenkins Pipelines
  pkg/build/controller/build/build_controller.go
  pkg/build/controller/build/build_controller_test.go
  pkg/build/controller/buildconfig/buildconfig_controller.go
  pkg/build/controller/common/util.go
  test/extended/builds/pipeline.go
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/build-pruning/failed-pipeline.yaml
  test/extended/testdata/builds/build-pruning/successful-pipeline.yaml
Labels: approved, lgtm, sig/developer-experience, size/L

#19972 adds --no-owner and --no-group flags to oc rsync
  pkg/oc/cli/cmd/rsync/copyrsync.go
  pkg/oc/cli/cmd/rsync/copyrsyncd.go
  pkg/oc/cli/cmd/rsync/rsync.go
  test/extended/cli/rsync.go
Labels: approved, lgtm, sig/developer-experience, size/M

#20012 update external example content
  examples/db-templates/mysql-ephemeral-template.json
  examples/db-templates/mysql-persistent-template.json
  examples/image-streams/image-streams-centos7.json
  examples/image-streams/image-streams-rhel7.json
  examples/jenkins/jenkins-persistent-template.json
  examples/quickstarts/dotnet-pgsql-persistent.json
  examples/quickstarts/dotnet.json
  pkg/oc/clusterup/manifests/bindata.go
  test/cmd/debug.sh
  test/cmd/images.sh
  test/cmd/newapp.sh
  test/extended/testdata/bindata.go
Labels: approved, lgtm, size/XL

#19976 Bug 1461324 - Log image changes on verify-image-signature without --save
  pkg/oc/admin/image/verify-signature.go
Labels: approved, component/image, lgtm, size/XS

#19986 Revert "Make NewCommandStartNode() handle SIGTERM and SIGINT"
  cmd/openshift/openshift.go
  pkg/cmd/openshift/openshift.go
  pkg/cmd/openshift/openshift_test.go
  pkg/cmd/server/start/command_test.go
  pkg/cmd/server/start/start_allinone.go
  pkg/cmd/server/start/start_node.go
  tools/clicheck/check_cli_conventions.go
  tools/genman/gen_man.go
Labels: approved, lgtm, size/M

#19248 Prometheus metrics for image import controllers
  pkg/image/controller/factory.go
  pkg/image/controller/imagestream_controller.go
  pkg/image/controller/imagestream_controller_test.go
  pkg/image/controller/metrics.go
  pkg/image/controller/scheduled_image_controller.go
  pkg/image/metrics/prometheus/metrics.go
Labels: approved, lgtm, sig/continuous-infrastructure, sig/developer-experience, size/L

#19827 add conformance tag to fast parallel registry tests
  test/extended/imageapis/limitrange_admission.go
  test/extended/imageapis/quota_admission.go
  test/extended/images/hardprune.go
  test/extended/images/prune.go
  test/extended/images/resolve.go
Labels: approved, lgtm, size/S

#20038 update additional cmds
  pkg/oc/cli/cmd/image/image.go
  pkg/oc/cli/cmd/image/mirror/mirror.go
  pkg/oc/cli/cmd/importer/appjson.go
  pkg/oc/cli/cmd/importer/import.go
  pkg/oc/cli/cmd/login/login.go
  pkg/oc/cli/cmd/login/loginoptions.go
  pkg/oc/cli/cmd/login/logout.go
  pkg/oc/cli/cmd/logs.go
  pkg/oc/cli/cmd/set/env.go
  pkg/oc/cli/cmd/set/volume.go
  pkg/oc/cli/cmd/tag.go
  pkg/oc/clusterup/docker/openshift/login.go
  pkg/oc/clusterup/up.go
  test/integration/login_test.go
  test/integration/oauth_oidc_test.go
  test/integration/oauth_request_header_test.go
Labels: size/L

#20045 update process cmd
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/oc/cli/cmd/process.go
Labels: size/XL

#20049 update even more cmds
  pkg/oc/cli/cmd/observe/observe.go
  pkg/oc/cli/cmd/registry/info/info.go
  pkg/oc/cli/cmd/registry/login/login.go
  pkg/oc/cli/cmd/registry/registry.go
  pkg/oc/cli/cmd/rollback.go
  pkg/oc/cli/cmd/startbuild.go
  pkg/oc/cli/cmd/version.go
Labels: size/L

#20047 Verify that someone isn't accidentally importing staging
  hack/import-restrictions.json
Labels: approved, lgtm, size/S

#20035 Revert "Make NewCommandStartNode() handle SIGTERM and SIGINT"
  cmd/openshift/openshift.go
  pkg/cmd/openshift/openshift.go
  pkg/cmd/openshift/openshift_test.go
  pkg/cmd/server/start/command_test.go
  pkg/cmd/server/start/start_allinone.go
  pkg/cmd/server/start/start_node.go
  tools/clicheck/check_cli_conventions.go
  tools/genman/gen_man.go
Labels: approved, lgtm, size/M

#20052 Resuse existing imagestreams with new-app
  pkg/oc/generate/app/pipeline.go
  pkg/oc/generate/cmd/describe.go
  test/cmd/newapp.sh
Labels: approved, lgtm, sig/developer-experience, size/S

#19870 install ceph-common in control plane so rbd provisioner can find rbd cli to create rbd images
  images/origin/Dockerfile
Labels: approved, lgtm, size/XS

#20058 UPSTREAM: 64447: Add block volume support to internal provisioners
  vendor/k8s.io/kubernetes/pkg/volume/aws_ebs/BUILD
  vendor/k8s.io/kubernetes/pkg/volume/aws_ebs/aws_ebs.go
  vendor/k8s.io/kubernetes/pkg/volume/azure_dd/BUILD
  vendor/k8s.io/kubernetes/pkg/volume/azure_dd/azure_provision.go
  vendor/k8s.io/kubernetes/pkg/volume/azure_file/azure_provision.go
  vendor/k8s.io/kubernetes/pkg/volume/cinder/cinder.go
  vendor/k8s.io/kubernetes/pkg/volume/flocker/flocker_volume.go
  vendor/k8s.io/kubernetes/pkg/volume/gce_pd/gce_pd.go
  vendor/k8s.io/kubernetes/pkg/volume/glusterfs/glusterfs.go
  vendor/k8s.io/kubernetes/pkg/volume/host_path/host_path.go
  vendor/k8s.io/kubernetes/pkg/volume/photon_pd/photon_pd.go
  vendor/k8s.io/kubernetes/pkg/volume/portworx/portworx.go
  vendor/k8s.io/kubernetes/pkg/volume/quobyte/quobyte.go
  vendor/k8s.io/kubernetes/pkg/volume/rbd/BUILD
  vendor/k8s.io/kubernetes/pkg/volume/rbd/rbd.go
  vendor/k8s.io/kubernetes/pkg/volume/scaleio/sio_volume.go
  vendor/k8s.io/kubernetes/pkg/volume/storageos/storageos.go
  vendor/k8s.io/kubernetes/pkg/volume/util/util.go
  vendor/k8s.io/kubernetes/pkg/volume/vsphere_volume/vsphere_volume.go
  vendor/k8s.io/kubernetes/test/e2e/storage/volume_provisioning.go
Labels: approved, lgtm, sig/storage, size/L

#20075 UPSTREAM: 65189: revert: fix paths w shortcuts when copying from pods"
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cp.go
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cp_test.go
Labels: approved, lgtm, size/M

#20076 [3.10] bump(*): update to kube 3.10 branch
  glide.lock
  vendor/k8s.io/kubernetes/pkg/volume/aws_ebs/BUILD
  vendor/k8s.io/kubernetes/pkg/volume/aws_ebs/aws_ebs.go
  vendor/k8s.io/kubernetes/pkg/volume/azure_dd/BUILD
  vendor/k8s.io/kubernetes/pkg/volume/azure_dd/azure_provision.go
  vendor/k8s.io/kubernetes/pkg/volume/azure_file/azure_provision.go
  vendor/k8s.io/kubernetes/pkg/volume/cinder/cinder.go
  vendor/k8s.io/kubernetes/pkg/volume/flocker/flocker_volume.go
  vendor/k8s.io/kubernetes/pkg/volume/gce_pd/gce_pd.go
  vendor/k8s.io/kubernetes/pkg/volume/glusterfs/glusterfs.go
  vendor/k8s.io/kubernetes/pkg/volume/host_path/host_path.go
  vendor/k8s.io/kubernetes/pkg/volume/photon_pd/photon_pd.go
  vendor/k8s.io/kubernetes/pkg/volume/portworx/portworx.go
  vendor/k8s.io/kubernetes/pkg/volume/quobyte/quobyte.go
  vendor/k8s.io/kubernetes/pkg/volume/rbd/BUILD
  vendor/k8s.io/kubernetes/pkg/volume/rbd/rbd.go
  vendor/k8s.io/kubernetes/pkg/volume/scaleio/sio_volume.go
  vendor/k8s.io/kubernetes/pkg/volume/storageos/storageos.go
  vendor/k8s.io/kubernetes/pkg/volume/util/util.go
  vendor/k8s.io/kubernetes/pkg/volume/vsphere_volume/vsphere_volume.go
  vendor/k8s.io/kubernetes/test/e2e/storage/volume_provisioning.go
Labels: approved, lgtm, size/L

#20059 Bug 1593209 - Update OpenShift Excluder
  origin.spec
Labels: approved, lgtm, size/XS

#20071 [3.10] UPSTREAM: 65339: Remove item from taint manager workqueue on completion
  vendor/k8s.io/kubernetes/pkg/controller/nodelifecycle/scheduler/taint_manager.go
Labels: approved, lgtm, priority/critical-urgent, queue/critical-fix, size/XS

#20077 mark tests that use docker socket as [local]
  test/extended/imageapis/limitrange_admission.go
  test/extended/imageapis/quota_admission.go
  test/extended/images/prune.go
Labels: approved, lgtm, size/XS

#20051 [3.10] imagebuilder fails for certain COPY statements
  glide.lock
  vendor/github.com/openshift/imagebuilder/Makefile
  vendor/github.com/openshift/imagebuilder/dispatchers_test.go
  vendor/github.com/openshift/imagebuilder/dockerclient/archive.go
  vendor/github.com/openshift/imagebuilder/dockerclient/client.go
  vendor/github.com/openshift/imagebuilder/dockerclient/conformance_test.go
  vendor/github.com/openshift/imagebuilder/dockerclient/copyinfo.go
  vendor/github.com/openshift/imagebuilder/dockerclient/copyinfo_test.go
  vendor/github.com/openshift/imagebuilder/dockerclient/testdata/dir/Dockerfile
  vendor/github.com/openshift/imagebuilder/dockerclient/testdata/overlapdir/Dockerfile.with_slash
  vendor/github.com/openshift/imagebuilder/dockerclient/testdata/overlapdir/Dockerfile.without_slash
  vendor/github.com/openshift/imagebuilder/dockerclient/testdata/overlapdir/existing/etc/file-in-existing-dir
  vendor/github.com/openshift/imagebuilder/dockerclient/testdata/singlefile/Dockerfile
  vendor/github.com/openshift/imagebuilder/internals.go
Labels: approved, lgtm, size/L

#20086 re-enable slave restart test
  test/extended/image_ecosystem/mysql_replica.go
  test/extended/util/db/mysql.go
Labels: approved, lgtm, size/S

#20072 UPSTREAM: 65223: Fixed detection of inaccessible AWS encryption key
  vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws.go
  vendor/k8s.io/kubernetes/test/e2e/storage/volume_provisioning.go
Labels: approved, lgtm, size/L

#20091 Greetings me as a new SCC maintainer!
  pkg/security/OWNERS
Labels: approved, lgtm, retest-not-required-docs-only, sig/security, size/XS

#20087 3.10: imagebuilder: Some `COPY --from` statements would fail
  glide.lock
  vendor/github.com/openshift/imagebuilder/dockerclient/archive.go
  vendor/github.com/openshift/imagebuilder/dockerclient/archive_test.go
  vendor/github.com/openshift/imagebuilder/dockerclient/client.go
  vendor/github.com/openshift/imagebuilder/dockerclient/testdata/Dockerfile.copyfrom_1
  vendor/github.com/openshift/imagebuilder/dockerclient/testdata/Dockerfile.copyfrom_10
  vendor/github.com/openshift/imagebuilder/dockerclient/testdata/Dockerfile.copyfrom_2
  vendor/github.com/openshift/imagebuilder/dockerclient/testdata/Dockerfile.copyfrom_3
  vendor/github.com/openshift/imagebuilder/dockerclient/testdata/Dockerfile.copyfrom_4
  vendor/github.com/openshift/imagebuilder/dockerclient/testdata/Dockerfile.copyfrom_5
  vendor/github.com/openshift/imagebuilder/dockerclient/testdata/Dockerfile.copyfrom_6
  vendor/github.com/openshift/imagebuilder/dockerclient/testdata/Dockerfile.copyfrom_7
  vendor/github.com/openshift/imagebuilder/dockerclient/testdata/Dockerfile.copyfrom_8
  vendor/github.com/openshift/imagebuilder/dockerclient/testdata/Dockerfile.copyfrom_9
  vendor/github.com/openshift/imagebuilder/dockerclient/testdata/copyfrom/Dockerfile
Labels: approved, lgtm, size/L

#20085 update deploy, extract, project, status, whoami cmds
  pkg/oc/cli/cmd/deploy.go
  pkg/oc/cli/cmd/extract.go
  pkg/oc/cli/cmd/project.go
  pkg/oc/cli/cmd/status.go
  pkg/oc/cli/cmd/whoami.go
Labels: size/L

#20094 Allow egress-router to connect to cluster service network for DNS, etc.
  pkg/network/node/cniserver/cniserver.go
  pkg/network/node/cniserver/cniserver_test.go
  pkg/network/node/node.go
  pkg/network/node/pod.go
  pkg/network/node/pod_test.go
  pkg/network/sdn-cni-plugin/openshift-sdn.go
  pkg/network/sdn-cni-plugin/sdn_cni_plugin_test.go
Labels: approved, lgtm, sig/networking, size/M

#20105 update export, req_project, rsync cmds
  pkg/oc/admin/admin.go
  pkg/oc/cli/cli.go
  pkg/oc/cli/cmd/export.go
  pkg/oc/cli/cmd/request_project.go
  pkg/oc/cli/cmd/rsync/rsync.go
  pkg/oc/cli/cmd/version.go
  pkg/oc/clusterup/docker/openshift/project.go
Labels: size/L

#20073 up: store components user ran cluster up
  pkg/oc/clusterup/coreinstall/components/components.go
  pkg/oc/clusterup/up.go
Labels: approved, lgtm, size/M

#20100 start-build: remove false alarm warning for repo binary input
  pkg/oc/cli/cmd/startbuild.go
Labels: approved, component/cli, lgtm, sig/developer-experience, size/M

#20095 Bind mount /etc/origin/kubelet-plugins for flex volumes
  images/node/system-container/config.json.template
Labels: approved, lgtm, sig/storage, size/S

#19673 oc import-image: deprecate legacy path using annotations
  hack/import-restrictions.json
  pkg/oc/cli/cmd/importimage.go
Labels: approved, component/cli, lgtm, sig/developer-experience, size/L

#20118 update remaining cmds
  pkg/oc/cli/cmd/idle.go
  pkg/oc/cli/cmd/importimage.go
  pkg/oc/cli/cmd/newapp.go
  pkg/oc/cli/cmd/newbuild.go
  pkg/oc/cli/cmd/project.go
  pkg/oc/cli/cmd/projects.go
  pkg/oc/cli/cmd/request_project.go
  pkg/oc/cli/cmd/rsh.go
Labels: size/XL

#20138 update publishing rules
  publishing-kube-rules.yaml
  publishing-rules.yaml
Labels: approved, lgtm, retest-not-required, size/L
