Repository openshift/origin, pull requests merged in 2018-04, with the labels that each got.

#19180 Store logs uncompressed in the networking test artifacts
  test/extended/networking.sh
Labels: approved, area/tests, lgtm, sig/networking, size/S

#18911 Minimize direct API calls in SDN master by using informer cache
  pkg/network/master/master.go
  pkg/network/master/subnet_allocator.go
  pkg/network/master/subnet_allocator_test.go
  pkg/network/master/subnets.go
  pkg/network/master/vnids.go
Labels: approved, lgtm, sig/networking, size/XL, ¯\_(ツ)_/¯

#18969 Add option to configure an external OAuth server
  pkg/authorization/authorizer/scope/converter.go
  pkg/cmd/server/apis/config/helpers.go
  pkg/cmd/server/apis/config/types.go
  pkg/cmd/server/apis/config/v1/testdata/master-config.yaml
  pkg/cmd/server/apis/config/v1/types.go
  pkg/cmd/server/apis/config/validation/master.go
  pkg/cmd/server/apis/config/validation/master_test.go
  pkg/cmd/server/kubernetes/master/master_config.go
  pkg/cmd/server/origin/master.go
  pkg/cmd/server/origin/nonapiserver.go
  pkg/oauth/util/discovery.go
  pkg/oauth/util/discovery_test.go
  test/integration/oauth_external_test.go
Labels: api-approved, approved, lgtm, needs-api-review, size/L

#19190 Adjust defaults to better handle self-hosting and bootstrapping
  pkg/cmd/server/kubernetes/node/options/options.go
  pkg/cmd/server/start/start_kube_controller_manager.go
Labels: approved, lgtm, retest-not-required, size/XS

#19186 remove illegal and dead kubemasterconfig fields
  pkg/cmd/server/apis/config/helpers.go
  pkg/cmd/server/apis/config/serialization_test.go
  pkg/cmd/server/apis/config/types.go
  pkg/cmd/server/apis/config/v1/conversions.go
  pkg/cmd/server/apis/config/v1/testdata/master-config.yaml
  pkg/cmd/server/apis/config/v1/types.go
  pkg/cmd/server/apis/config/v1/types_test.go
  pkg/cmd/server/apis/config/v1/zz_generated.deepcopy.go
  pkg/cmd/server/apis/config/validation/master.go
  pkg/cmd/server/apis/config/validation/master_test.go
  pkg/cmd/server/apis/config/zz_generated.deepcopy.go
  pkg/cmd/server/kubernetes/master/master_config.go
Labels: approved, lgtm, size/L

#18658 Replace router support for ingress with an ingress-to-route controller
  pkg/cmd/infra/router/f5.go
  pkg/cmd/infra/router/router.go
  pkg/cmd/infra/router/template.go
  pkg/cmd/openshift-controller-manager/controller/config.go
  pkg/cmd/openshift-controller-manager/controller/ingress.go
  pkg/cmd/openshift-controller-manager/controller/interfaces.go
  pkg/cmd/openshift-controller-manager/controller_manager.go
  pkg/cmd/server/bootstrappolicy/controller_policy.go
  pkg/cmd/server/origin/master_config.go
  pkg/route/controller/ingress/ingress.go
  pkg/route/controller/ingress/ingress_test.go
  pkg/router/controller/extended_validator.go
  pkg/router/controller/factory/factory.go
  pkg/router/controller/host_admitter.go
  pkg/router/controller/ingress.go
  pkg/router/controller/ingress_test.go
  pkg/router/controller/router_controller.go
  pkg/router/controller/status.go
  pkg/router/controller/unique_host.go
  pkg/router/f5/plugin.go
  pkg/router/template/router.go
  test/end-to-end/router_test.go
  test/extended/router/metrics.go
  test/extended/router/router.go
  test/extended/testdata/bindata.go
  test/extended/testdata/ingress.yaml
  test/extended/util/framework.go
  test/integration/router_without_haproxy_test.go
  test/testdata/bootstrappolicy/bootstrap_cluster_role_bindings.yaml
  test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml
  test/testdata/bootstrappolicy/bootstrap_policy_file.yaml
Labels: approved, lgtm, sig/networking, size/XXL

#19192 Fix NetworkPolicy tests to be skipped under kubenet
  test/extended/cni_vendor_test.sh
  test/extended/networking/util.go
Labels: approved, area/tests, component/networking, kind/bug, lgtm, sig/networking, size/S

#19191 remove dead client from config
  pkg/cmd/server/apis/config/helpers.go
  pkg/cmd/server/apis/config/serialization_test.go
  pkg/cmd/server/apis/config/types.go
  pkg/cmd/server/apis/config/v1/conversions.go
  pkg/cmd/server/apis/config/v1/testdata/master-config.yaml
  pkg/cmd/server/apis/config/v1/types.go
  pkg/cmd/server/apis/config/v1/zz_generated.deepcopy.go
  pkg/cmd/server/apis/config/v1/zz_generated.defaults.go
  pkg/cmd/server/apis/config/validation/master.go
  pkg/cmd/server/apis/config/zz_generated.deepcopy.go
  pkg/cmd/server/start/master_args.go
Labels: approved, lgtm, size/M

#19185 remove dead auth related master-config fields
  pkg/cmd/openshift-controller-manager/controller/config.go
  pkg/cmd/server/apis/config/helpers.go
  pkg/cmd/server/apis/config/serialization_test.go
  pkg/cmd/server/apis/config/types.go
  pkg/cmd/server/apis/config/v1/conversions.go
  pkg/cmd/server/apis/config/v1/testdata/master-config.yaml
  pkg/cmd/server/apis/config/v1/types.go
  pkg/cmd/server/apis/config/validation/master.go
  pkg/cmd/server/apis/config/validation/validation.go
  pkg/cmd/server/start/master_args.go
Labels: approved, lgtm, sig/security, size/M

#19112 Updates to CONTRIBUTING documentation.
  CONTRIBUTING.adoc
  docs/cluster_up_down.md
Labels: approved, lgtm, retest-not-required-docs-only, size/L

#19200 Pre-rebase fixes
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  hack/lib/constants.sh
  pkg/cmd/server/apis/config/helpers.go
  pkg/cmd/server/apis/config/helpers_test.go
  pkg/cmd/server/apis/config/validation/master.go
  pkg/cmd/server/kubernetes/master/master_config.go
  pkg/cmd/server/kubernetes/master/master_test.go
  pkg/cmd/server/kubernetes/node/options/options.go
  pkg/cmd/server/start/start_kube_controller_manager.go
  pkg/cmd/server/start/start_kube_scheduler.go
  pkg/cmd/server/start/start_node.go
  pkg/oc/admin/migrate/migrator.go
  pkg/oc/cli/cmd/create/route.go
Labels: approved, lgtm, size/M

#19149 make components for most cluster up add-ons
  pkg/oc/bootstrap/clusterup/components/registry/registry_install.go
  pkg/oc/bootstrap/clusterup/components/router/router_install.go
  pkg/oc/bootstrap/clusterup/components/service-catalog/service_catalog.go
  pkg/oc/bootstrap/clusterup/components/template-service-broker/template_service_broker.go
  pkg/oc/bootstrap/clusterup/components/web-console/web_console.go
  pkg/oc/bootstrap/docker/openshift/admin.go
  pkg/oc/bootstrap/docker/openshift/rbac.go
  pkg/oc/bootstrap/docker/openshift/servicecatalog.go
  pkg/oc/bootstrap/docker/openshift/templateservicebroker.go
  pkg/oc/bootstrap/docker/up.go
  pkg/oc/errors/errors.go
Labels: approved, lgtm, size/XXL

#19197 extended tests: use faster built repo for bc with PR
  test/extended/builds/start.go
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/test-bc-with-pr-ref.yaml
Labels: approved, area/tests, lgtm, sig/developer-experience, size/M

#19184 make kubemasterconfig non-pointer since it is required
  pkg/cmd/openshift-kube-apiserver/server.go
  pkg/cmd/server/apis/config/helpers.go
  pkg/cmd/server/apis/config/serialization_test.go
  pkg/cmd/server/apis/config/types.go
  pkg/cmd/server/apis/config/v1/conversions.go
  pkg/cmd/server/apis/config/v1/types.go
  pkg/cmd/server/apis/config/v1/types_test.go
  pkg/cmd/server/apis/config/v1/zz_generated.deepcopy.go
  pkg/cmd/server/apis/config/v1/zz_generated.defaults.go
  pkg/cmd/server/apis/config/validation/master.go
  pkg/cmd/server/apis/config/validation/master_test.go
  pkg/cmd/server/apis/config/zz_generated.deepcopy.go
  pkg/cmd/server/kubernetes/master/master_config.go
  pkg/cmd/server/kubernetes/master/master_config_test.go
  pkg/cmd/server/origin/admission/config_test.go
  pkg/cmd/server/start/master_args.go
  pkg/cmd/server/start/start_api.go
  pkg/cmd/server/start/start_master.go
  test/integration/api_paths_test.go
  test/integration/clusterresourceoverride_admission_test.go
Labels: approved, lgtm, size/L

#14740 Allow VIP grouping per VRRP
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  images/ipfailover/keepalived/conf/settings.sh
  images/ipfailover/keepalived/lib/config-generators.sh
  pkg/oc/experimental/ipfailover/ipfailover.go
  pkg/oc/experimental/ipfailover/ipfailover/types.go
  pkg/oc/experimental/ipfailover/keepalived/generator.go
Labels: approved, component/networking, lgtm, size/M

#19215 create oc cluster add
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  docs/man/man1/.files_generated_oc
  docs/man/man1/oc-cluster-add.1
  pkg/oc/bootstrap/clusteradd/cmd.go
  pkg/oc/bootstrap/clusterup/components/register-template-service-broker/register_tsb.go
  pkg/oc/bootstrap/clusterup/components/service-catalog/service_catalog.go
  pkg/oc/bootstrap/clusterup/components/template-service-broker/template_service_broker.go
  pkg/oc/bootstrap/docker/down.go
  pkg/oc/bootstrap/docker/run_self_hosted.go
  pkg/oc/bootstrap/docker/status.go
  pkg/oc/bootstrap/docker/up.go
  pkg/oc/cli/cmd/cluster/cluster.go
  test/extended/clusterup.sh
Labels: approved, lgtm, size/XL

#19146 update prometheus 2.1.0 -> 2.2.1
  examples/prometheus/prometheus-standalone.yaml
  examples/prometheus/prometheus.yaml
  pkg/oc/bootstrap/bindata.go
  test/extended/testdata/bindata.go
Labels: approved, lgtm, size/XS

#19225 Observe should exit when enough reflector errors occur
  pkg/oc/cli/cmd/observe/observe.go
Labels: approved, lgtm, sig/master, size/S

#19128 log OVS commands at level 4
  pkg/util/ovs/ovs.go
Labels: approved, area/tests, component/networking, kind/feature, lgtm, sig/networking, size/XS

#19222 allow docker.io prefix in hack/build-local-images.py
  hack/build-local-images.py
Labels: approved, lgtm, size/XS

#19220 remove dockermachine from cluster up
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/oc/bootstrap/clusteradd/cmd.go
  pkg/oc/bootstrap/docker/dockermachine/errors.go
  pkg/oc/bootstrap/docker/dockermachine/helper.go
  pkg/oc/bootstrap/docker/down.go
  pkg/oc/bootstrap/docker/status.go
  pkg/oc/bootstrap/docker/up.go
Labels: approved, lgtm, size/L

#19211 start storing data in groupified format
  pkg/cmd/server/kubernetes/master/master_config.go
  pkg/cmd/server/origin/rest/storage_options.go
  pkg/security/apis/security/install/install.go
  test/integration/etcd_storage_path_test.go
Labels: approved, lgtm, size/M

#19082 networking requirements changes
  docs/openshift_networking_requirements.md
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#19209 remove oc cluster up experimental flags broken since 3.6.1
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  hack/import-restrictions.json
  pkg/oc/bootstrap/docker/host/host.go
  pkg/oc/bootstrap/docker/openshift/ansible.go
  pkg/oc/bootstrap/docker/openshift/helper.go
  pkg/oc/bootstrap/docker/openshift/helper_test.go
  pkg/oc/bootstrap/docker/openshift/logging.go
  pkg/oc/bootstrap/docker/openshift/metrics.go
  pkg/oc/bootstrap/docker/up.go
Labels: approved, lgtm, size/XL

#19233 Further dind start certificate generation serialization
  images/dind/master/openshift-generate-master-config.sh
Labels: approved, lgtm, sig/networking, size/S

#19232 Update console liveness probe
  install/origin-web-console/console-template.yaml
  pkg/oc/bootstrap/bindata.go
  test/extended/testdata/bindata.go
Labels: approved, lgtm, size/XS

#19238 bootstrap: remove factory from cluster up command
  pkg/oc/bootstrap/clusteradd/cmd.go
  pkg/oc/bootstrap/clusterup/componentinstall/apply_list.go
  pkg/oc/bootstrap/clusterup/componentinstall/apply_template.go
  pkg/oc/bootstrap/clusterup/componentinstall/context.go
  pkg/oc/bootstrap/clusterup/componentinstall/interface.go
  pkg/oc/bootstrap/clusterup/componentinstall/log.go
  pkg/oc/bootstrap/clusterup/componentinstall/privileged.go
  pkg/oc/bootstrap/clusterup/componentinstall/readiness_apigroup.go
  pkg/oc/bootstrap/clusterup/components/register-template-service-broker/register_tsb.go
  pkg/oc/bootstrap/clusterup/components/registry/registry_install.go
  pkg/oc/bootstrap/clusterup/components/router/router_install.go
  pkg/oc/bootstrap/clusterup/components/service-catalog/service_catalog.go
  pkg/oc/bootstrap/clusterup/components/template-service-broker/template_service_broker.go
  pkg/oc/bootstrap/clusterup/components/web-console/web_console.go
  pkg/oc/bootstrap/clusterup/kubeapiserver/config.go
  pkg/oc/bootstrap/clusterup/kubelet/config.go
  pkg/oc/bootstrap/clusterup/kubelet/flags.go
  pkg/oc/bootstrap/docker/openshift/login.go
  pkg/oc/bootstrap/docker/openshift/templateservicebroker.go
  pkg/oc/bootstrap/docker/run/run.go
  pkg/oc/bootstrap/docker/run_self_hosted.go
  pkg/oc/bootstrap/docker/up.go
  pkg/oc/cli/cmd/cluster/cluster.go
Labels: approved, lgtm, size/XL

#19229 add * and - as oc clusterup enable concepts
  pkg/oc/bootstrap/docker/up.go
  test/extended/clusterup.sh
Labels: approved, lgtm, size/M

#19231 prevent oc cluster up from allowing bad KUBECONFIGs
  pkg/oc/bootstrap/docker/up.go
Labels: approved, lgtm, size/S

#19243 fix swapped format args and fix ruby version checking
  test/extended/image_ecosystem/s2i_images.go
  test/extended/image_ecosystem/scl.go
Labels: approved, lgtm, size/S

#19123 TestValidateSecurityContextConstraints: fix "index out of range" panic when there no errors encountered
  pkg/security/apis/security/validation/validation_test.go
Labels: approved, lgtm, size/XS

#19249 dind: restart ovn-kubernetes-node via systemd if it fails
  images/dind/node/ovn-kubernetes-node.service
Labels: approved, lgtm, size/XS

#19258 Add 1.10.0 publishing rules
  publishing-kube-rules.yaml
Labels: approved, size/M

#19246 make remaining oc cluster up components
  pkg/oc/bootstrap/clusteradd/cmd.go
  pkg/oc/bootstrap/clusteradd/componentinstall/apply_list.go
  pkg/oc/bootstrap/clusteradd/componentinstall/apply_template.go
  pkg/oc/bootstrap/clusteradd/componentinstall/context.go
  pkg/oc/bootstrap/clusteradd/componentinstall/interface.go
  pkg/oc/bootstrap/clusteradd/componentinstall/privileged.go
  pkg/oc/bootstrap/clusteradd/componentinstall/readiness_apigroup.go
  pkg/oc/bootstrap/clusteradd/components/register-template-service-broker/OWNERS
  pkg/oc/bootstrap/clusteradd/components/register-template-service-broker/register_tsb.go
  pkg/oc/bootstrap/clusteradd/components/registry/OWNERS
  pkg/oc/bootstrap/clusteradd/components/registry/registry_install.go
  pkg/oc/bootstrap/clusteradd/components/router/OWNERS
  pkg/oc/bootstrap/clusteradd/components/router/router_install.go
  pkg/oc/bootstrap/clusteradd/components/service-catalog/OWNERS
  pkg/oc/bootstrap/clusteradd/components/service-catalog/service_catalog.go
  pkg/oc/bootstrap/clusteradd/components/template-service-broker/OWNERS
  pkg/oc/bootstrap/clusteradd/components/template-service-broker/template_service_broker.go
  pkg/oc/bootstrap/clusteradd/components/web-console/OWNERS
  pkg/oc/bootstrap/clusteradd/components/web-console/web_console.go
  pkg/oc/bootstrap/docker/openshift/templateservicebroker.go
  pkg/oc/bootstrap/docker/run_self_hosted.go
  pkg/oc/bootstrap/docker/up.go
  test/extended/clusterup.sh
Labels: approved, lgtm, size/L

#19120 Better warning for --build-loglevel with binary builds
  pkg/oc/cli/cmd/startbuild.go
Labels: approved, lgtm, size/M

#19266 Wait until other routers have written their status
  test/extended/router/stress.go
Labels: approved, lgtm, size/S

#19284 node, syscontainer: bind mount /var/lib/kubelet from the host
  images/node/system-container/config.json.template
  images/node/system-container/manifest.json
Labels: approved, lgtm, priority/critical-urgent, size/S

#19247 remove use-existing from cluster up
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/oc/bootstrap/docker/up.go
Labels: approved, lgtm, size/L

#19280 make images and sample templates components
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/oc/bootstrap/clusteradd/cmd.go
  pkg/oc/bootstrap/clusteradd/componentinstall/apply_list.go
  pkg/oc/bootstrap/clusteradd/componentinstall/union_component.go
  pkg/oc/bootstrap/clusteradd/components/default-imagestreams/OWNERS
  pkg/oc/bootstrap/clusteradd/components/default-imagestreams/artifact_test.go
  pkg/oc/bootstrap/clusteradd/components/default-imagestreams/default_imagestreams.go
  pkg/oc/bootstrap/clusteradd/components/sample-templates/OWNERS
  pkg/oc/bootstrap/clusteradd/components/sample-templates/sample_templates.go
  pkg/oc/bootstrap/docker/up.go
  pkg/oc/bootstrap/docker/up_test.go
Labels: approved, lgtm, size/L

#19285 Hoist sdn informer into Start()
  pkg/network/master/master.go
Labels: approved, component/networking, lgtm, queue/fix, retest-not-required, sig/networking, size/XS

#19194 Dynamic discovery of Web Console Public URL
  pkg/cmd/server/origin/master.go
  pkg/cmd/server/origin/webconsole_proxy.go
  test/integration/master_routes_test.go
Labels: approved, lgtm, size/L

#19321 Fix flake in cluster resource quota test
  test/cmd/quota.sh
Labels: approved, lgtm, queue/fix, size/XS

#19203 create new controller for managing SCC annotation on namespaces
  pkg/cmd/openshift-controller-manager/controller/config.go
  pkg/cmd/openshift-controller-manager/controller/interfaces.go
  pkg/cmd/openshift-controller-manager/controller/security.go
  pkg/cmd/openshift-controller-manager/controller_manager.go
  pkg/cmd/server/bootstrappolicy/controller_policy.go
  pkg/cmd/server/origin/dns_server.go
  pkg/cmd/server/origin/run_components.go
  pkg/security/controller/namespace_scc_allocation_controller.go
  pkg/security/controller/namespace_security_allocation_controller.go
  pkg/security/controller/namespace_security_allocation_controller_test.go
  pkg/security/controller/repair.go
  pkg/security/controller/repair_test.go
  test/testdata/bootstrappolicy/bootstrap_cluster_role_bindings.yaml
  test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml
  test/testdata/bootstrappolicy/bootstrap_policy_file.yaml
Labels: approved, lgtm, size/XXL

#19310 apps: use scale client to scale replication controllers
  pkg/apps/strategy/recreate/recreate.go
  pkg/apps/strategy/recreate/recreate_test.go
  pkg/cmd/infra/deployer/deployer.go
Labels: approved, lgtm, size/L

#19320 Revert "Better warning for --build-loglevel with binary builds"
  pkg/oc/cli/cmd/startbuild.go
Labels: approved, lgtm, queue/critical-fix, size/M

#19317 oc new-app: correctly evaluate env vars in multiple EXPOSE
  pkg/util/docker/dockerfile/dockerfile.go
  pkg/util/docker/dockerfile/dockerfile_test.go
Labels: approved, component/cli, kind/bug, lgtm, sig/developer-experience, size/M

#19269 up: make setup persistent volumes a component
  pkg/oc/bootstrap/clusteradd/cmd.go
  pkg/oc/bootstrap/clusterup/components/persistent-volumes/setup_persistent_volumes.go
  pkg/oc/bootstrap/docker/localcmd/cmd.go
  pkg/oc/bootstrap/docker/localcmd/errors.go
  pkg/oc/bootstrap/docker/openshift/admin.go
  pkg/oc/bootstrap/docker/openshift/cnetwork.go
  pkg/oc/bootstrap/docker/openshift/pvsetup.go
  pkg/oc/bootstrap/docker/openshift/templateservicebroker.go
  pkg/oc/bootstrap/docker/up.go
Labels: approved, lgtm, sig/security, size/XL

#19301 up: set MountPropagation=false on osx to bypass shared mount
  pkg/oc/bootstrap/docker/run_self_hosted.go
Labels: approved, lgtm, size/XS

#19287 Switch preferred storage to apps/v1
  pkg/cmd/server/kubernetes/master/master_config.go
  test/integration/etcd_storage_path_test.go
Labels: approved, kind/post-rebase, lgtm, size/M

#19316 update prometheus 2.0.0 -> 2.2.1
  examples/prometheus/prometheus-standalone.yaml
  examples/prometheus/prometheus.yaml
  pkg/oc/bootstrap/bindata.go
  test/extended/testdata/bindata.go
Labels: approved, lgtm, size/XS

#18989 UPSTREAM: <carry>: filter daemonset nodes by namespace node selectors
  vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/apps.go
  vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/config/config.go
  vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/config/patch.go
  vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go
  vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/options/options.go
  vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/patch.go
  vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/patch_flags.go
  vendor/k8s.io/kubernetes/pkg/controller/daemon/daemon_controller.go
  vendor/k8s.io/kubernetes/pkg/controller/daemon/patch_nodeselector.go
  vendor/k8s.io/kubernetes/pkg/controller/daemon/patch_nodeselector_test.go
Labels: approved, lgtm, size/L, vendor-update

#19169 Change the order of Validate() and Complete() for oc set volume
  pkg/oc/cli/cmd/set/volume.go
  pkg/oc/cli/cmd/set/volume_test.go
Labels: approved, lgtm, sig/master, size/L

#19189 remove dead controller fields
  contrib/completions/bash/openshift
  contrib/completions/zsh/openshift
  pkg/cmd/server/apis/config/serialization_test.go
  pkg/cmd/server/apis/config/types.go
  pkg/cmd/server/apis/config/v1/conversions.go
  pkg/cmd/server/apis/config/v1/testdata/master-config.yaml
  pkg/cmd/server/apis/config/v1/types.go
  pkg/cmd/server/apis/config/validation/master.go
  pkg/cmd/server/start/master_args.go
  pkg/cmd/server/start/start_master.go
Labels: approved, lgtm, size/M

#19219 Template helper code to sort map files
  images/router/haproxy/Dockerfile
  images/router/haproxy/conf/haproxy-config.template
  images/router/haproxy/reload-haproxy
  pkg/router/template/router.go
  pkg/router/template/template_helper.go
  pkg/router/template/template_helper_test.go
  pkg/router/template/util/map_paths.go
  pkg/router/template/util/map_paths_test.go
Labels: approved, lgtm, size/XL

#19288 Fix service catalog RBAC template
  examples/service-catalog/service-catalog-rbac.yaml
  pkg/oc/bootstrap/bindata.go
Labels: approved, kind/bug, lgtm, sig/security, size/M

#19314 Removed an unused variable from reload-haproxy
  images/router/haproxy/reload-haproxy
Labels: approved, component/routing, kind/bug, lgtm

#18904 dockergc: fix example DS to use oc instead of openshift
  examples/dockergc/dockergc-ds.yaml
Labels: approved, lgtm, size/XS

#19063 Make NewCommandStartNode() handle SIGTERM and SIGINT
  cmd/openshift/openshift.go
  pkg/cmd/openshift/openshift.go
  pkg/cmd/openshift/openshift_test.go
  pkg/cmd/server/start/command_test.go
  pkg/cmd/server/start/start_allinone.go
  pkg/cmd/server/start/start_node.go
  tools/clicheck/check_cli_conventions.go
  tools/genman/gen_man.go
Labels: approved, lgtm, size/M

#19279 Make DNS to the local node IP bypass auto-egress-IP routing
  pkg/network/node/ovscontroller.go
Labels: approved, lgtm, size/XS

#19286 catalog: create SSL cert for controller, add prometheus scrape
  examples/service-catalog/service-catalog.yaml
  pkg/oc/bootstrap/bindata.go
Labels: approved, lgtm, size/M

#19313 initial webconsole operator types
  hack/update-generated-clientsets.sh
  pkg/cmd/openshift-operators/apis/operators/v1alpha1/doc.go
  pkg/cmd/openshift-operators/apis/operators/v1alpha1/register.go
  pkg/cmd/openshift-operators/apis/operators/v1alpha1/types.go
  pkg/cmd/openshift-operators/apis/operators/v1alpha1/zz_generated.deepcopy.go
  pkg/cmd/openshift-operators/apis/operators/v1alpha1helpers/helpers.go
  pkg/cmd/openshift-operators/apis/webconsole/v1alpha1/doc.go
  pkg/cmd/openshift-operators/apis/webconsole/v1alpha1/register.go
  pkg/cmd/openshift-operators/apis/webconsole/v1alpha1/types.go
  pkg/cmd/openshift-operators/apis/webconsole/v1alpha1/zz_generated.deepcopy.go
  pkg/cmd/openshift-operators/generated/clientset/versioned/clientset.go
  pkg/cmd/openshift-operators/generated/clientset/versioned/doc.go
  pkg/cmd/openshift-operators/generated/clientset/versioned/fake/clientset_generated.go
  pkg/cmd/openshift-operators/generated/clientset/versioned/fake/doc.go
  pkg/cmd/openshift-operators/generated/clientset/versioned/fake/register.go
  pkg/cmd/openshift-operators/generated/clientset/versioned/scheme/doc.go
  pkg/cmd/openshift-operators/generated/clientset/versioned/scheme/register.go
  pkg/cmd/openshift-operators/generated/clientset/versioned/typed/operators/v1alpha1/doc.go
  pkg/cmd/openshift-operators/generated/clientset/versioned/typed/operators/v1alpha1/fake/doc.go
  pkg/cmd/openshift-operators/generated/clientset/versioned/typed/operators/v1alpha1/fake/fake_operators_client.go
  pkg/cmd/openshift-operators/generated/clientset/versioned/typed/operators/v1alpha1/generated_expansion.go
  pkg/cmd/openshift-operators/generated/clientset/versioned/typed/operators/v1alpha1/operators_client.go
  pkg/cmd/openshift-operators/generated/clientset/versioned/typed/webconsole/v1alpha1/doc.go
  pkg/cmd/openshift-operators/generated/clientset/versioned/typed/webconsole/v1alpha1/fake/doc.go
  pkg/cmd/openshift-operators/generated/clientset/versioned/typed/webconsole/v1alpha1/fake/fake_openshiftwebconsoleconfig.go
  pkg/cmd/openshift-operators/generated/clientset/versioned/typed/webconsole/v1alpha1/fake/fake_webconsole_client.go
  pkg/cmd/openshift-operators/generated/clientset/versioned/typed/webconsole/v1alpha1/generated_expansion.go
  pkg/cmd/openshift-operators/generated/clientset/versioned/typed/webconsole/v1alpha1/openshiftwebconsoleconfig.go
  pkg/cmd/openshift-operators/generated/clientset/versioned/typed/webconsole/v1alpha1/webconsole_client.go
  pkg/cmd/openshift-operators/generated/informers/externalversions/factory.go
  pkg/cmd/openshift-operators/generated/informers/externalversions/generic.go
  pkg/cmd/openshift-operators/generated/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/cmd/openshift-operators/generated/informers/externalversions/webconsole/interface.go
  pkg/cmd/openshift-operators/generated/informers/externalversions/webconsole/v1alpha1/interface.go
  pkg/cmd/openshift-operators/generated/informers/externalversions/webconsole/v1alpha1/openshiftwebconsoleconfig.go
  pkg/cmd/openshift-operators/generated/listers/webconsole/v1alpha1/expansion_generated.go
  pkg/cmd/openshift-operators/generated/listers/webconsole/v1alpha1/openshiftwebconsoleconfig.go
Labels: approved, lgtm, sig/master, size/XXL

#19324 reverting build pruning tests to previous version
  test/extended/builds/build_pruning.go
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/build-pruning/errored-build-config.yaml
  test/extended/testdata/builds/build-pruning/failed-build-config.yaml
  test/extended/testdata/builds/build-pruning/imagestream.yaml
  test/extended/testdata/builds/build-pruning/successful-build-config.yaml
Labels: approved, lgtm, size/L

#19329 UPSTREAM: 61480: Allow sockets to be mounted in subpath
  vendor/k8s.io/kubernetes/pkg/util/mount/mount_linux.go
  vendor/k8s.io/kubernetes/pkg/util/mount/mount_linux_test.go
Labels: approved, lgtm, size/M

#19227 Issue #19226 Removed docker machine doc from cluster up usage message
  docs/cluster_up_down.md
  pkg/oc/bootstrap/docker/down.go
  pkg/oc/bootstrap/docker/errors/docker.go
  pkg/oc/bootstrap/docker/status.go
  pkg/oc/cli/cmd/cluster/cluster.go
Labels: approved, lgtm, size/L

#19334 UPSTREAM: 62416: kuberuntime: logs: reduce logging level on waitLogs msg
  vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/logs/logs.go
Labels: approved, lgtm, size/XS

#19336 remove dead code from login pretty message making
  pkg/oc/cli/cmd/login/error_translation.go
  pkg/oc/cli/cmd/login/loginoptions.go
  pkg/oc/cli/cmd/login/loginoptions_test.go
  pkg/oc/cli/cmd/project.go
  pkg/oc/cli/cmd/projects.go
  pkg/oc/cli/util/clientcmd/errors_test.go
Labels: approved, lgtm

#19340 fix fuzzer test
  pkg/cmd/server/apis/config/serialization_test.go
Labels: approved, lgtm, size/XS

#19273 Fix use of cookies in HostSubnet deletion
  pkg/network/node/ovscontroller.go
  pkg/util/ovs/parse.go
Labels: approved, component/networking, kind/bug, lgtm, sig/networking, size/S

#19306 Remove openvswitch from node system container
  images/node/system-container/config.json.template
  images/node/system-container/manifest.json
  images/node/system-container/service.template
Labels: approved, lgtm, size/S

#17987 Update image pruning example
  examples/pruner/README.md
  examples/pruner/cronjob.yaml
Labels: approved, lgtm, lifecycle/stale, size/M

#19251 dind: Fix crio configuration
  images/dind/node/Dockerfile
Labels: approved, lgtm, sig/networking, size/XS

#19335 use the upstream construction for kubeconfig evaluation
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  hack/import-restrictions.json
  pkg/client/config/loader.go
  pkg/cmd/infra/router/clientcmd.go
  pkg/cmd/infra/router/f5.go
  pkg/cmd/infra/router/template.go
  pkg/oc/admin/diagnostics/config.go
  pkg/oc/admin/diagnostics/diagnostics.go
  pkg/oc/admin/prune/images.go
  pkg/oc/bootstrap/docker/openshift/helper.go
  pkg/oc/bootstrap/docker/openshift/project.go
  pkg/oc/bootstrap/docker/up.go
  pkg/oc/cli/cmd/process.go
  pkg/oc/cli/cmd/version.go
  pkg/oc/cli/cmd/wrappers.go
  pkg/oc/cli/config/loader.go
  pkg/oc/cli/util/clientcmd/factory_client_access.go
  test/cmd/config.sh
  test/integration/login_test.go
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/util/factory_client_access.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/clientcmd/client_config.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/clientcmd/patch_kubeconfig_flag.go
Labels: approved, lgtm, sig/master, size/XXL

#19343 stop using factory.OpenshiftClientConfig
  pkg/oc/admin/diagnostics/config.go
  pkg/oc/admin/image/verify-signature.go
  pkg/oc/cli/cmd/login/login.go
  pkg/oc/cli/cmd/login/logout.go
  pkg/oc/cli/cmd/project.go
  pkg/oc/cli/cmd/projects.go
  pkg/oc/cli/cmd/request_project.go
  pkg/oc/cli/cmd/startbuild.go
  pkg/oc/cli/cmd/startbuild_test.go
  pkg/oc/cli/cmd/status.go
  pkg/oc/cli/cmd/version.go
  pkg/oc/cli/cmd/whoami.go
  pkg/oc/cli/sa/create_kubeconfig.go
  pkg/oc/cli/util/clientcmd/factory_builder.go
  pkg/oc/cli/util/clientcmd/factory_client_access.go
  pkg/oc/cli/util/clientcmd/factory_object_mapping.go
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/util/factory.go
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/util/patch_factory.go
Labels: approved, lgtm, size/L

#19348 own up to the attrocities commited in set
  pkg/oc/cli/cmd/set/set.go
  pkg/oc/cli/util/clientcmd/factory_client_access.go
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/set/patch_setimage.go
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/set/set_image.go
Labels: approved, lgtm, size/L

#19337 remove legacy auth cli actions that no longer work on current servers
  docs/man/man1/.files_generated_oc
  docs/man/man1/oc-adm-migrate-authorization.1
  docs/man/man1/oc-create-policybinding.1
  pkg/authorization/registry/util/normalize.go
  pkg/oc/admin/admin.go
  pkg/oc/admin/migrate/authorization/authorization.go
  pkg/oc/admin/migrate/migrator.go
  pkg/oc/cli/cmd/create/clusterquota.go
  pkg/oc/cli/cmd/create/policy_binding.go
  pkg/oc/cli/cmd/wrappers.go
  pkg/oc/cli/util/clientcmd/gating.go
  pkg/oc/cli/util/clientcmd/gating_test.go
  test/cmd/migrate.sh
  test/cmd/policy.sh
Labels: approved, lgtm, size/XXL

#18864 Require docker >= 1.13
  origin.spec
Labels: approved, lgtm, size/XS

#19308 Mount device manager socket dir path
  images/node/system-container/config.json.template
Labels: approved, lgtm, size/S

#19338 up: write static pod definitions on --write-config
  pkg/oc/bootstrap/docker/run_self_hosted.go
Labels: approved, lgtm, size/M

#19367 Add .NET Core templates
  examples/image-streams/image-streams-centos7.json
  examples/quickstarts/README.md
  examples/quickstarts/dotnet-pgsql-persistent.json
  examples/quickstarts/dotnet.json
  pkg/oc/bootstrap/bindata.go
  test/extended/testdata/bindata.go
Labels: approved, lgtm, size/XXL

#19371 UPSTREAM: 62572: Prevent virtual infinite loop in volume controller
  vendor/k8s.io/kubernetes/pkg/volume/util/recyclerclient/recycler_client.go
Labels: approved, component/storage, kind/bug, lgtm, size/M

#19352 UPSTREAM: 62584: Make x-kubernetes-print-column print handling opt-in
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/resource/get.go
Labels: approved, lgtm, size/XS

#19381 Switch conformance tests to release-1.10
  test/extended/conformance-k8s.sh
Labels: approved, size/XS

#19193 tag a basic test as a smoke test
  test/extended/builds/labels.go
Labels: approved, lgtm, size/XS

#19384 switch glide to https
  glide.lock
  glide.yaml
Labels: approved, lgtm, size/M

#19345 update oc commands to build their own clients
  pkg/oc/admin/diagnostics/diagnostics/client/config_contexts.go
  pkg/oc/admin/diagnostics/diagnostics/cluster/network/in_pod/cmd.go
  pkg/oc/admin/groups/changemembership.go
  pkg/oc/admin/groups/new.go
  pkg/oc/admin/groups/sync/cli/prune.go
  pkg/oc/admin/groups/sync/cli/sync.go
  pkg/oc/admin/image/verify-signature.go
  pkg/oc/admin/migrate/images/imagerefs.go
  pkg/oc/admin/network/project_options.go
  pkg/oc/admin/policy/cani.go
  pkg/oc/admin/policy/modify_roles.go
  pkg/oc/admin/policy/modify_scc.go
  pkg/oc/admin/policy/reconcile_clusterrolebindings.go
  pkg/oc/admin/policy/reconcile_clusterroles.go
  pkg/oc/admin/policy/reconcile_sccs.go
  pkg/oc/admin/policy/remove_from_project.go
  pkg/oc/admin/policy/review.go
  pkg/oc/admin/policy/subject_review.go
  pkg/oc/admin/policy/who_can.go
  pkg/oc/admin/project/new_project.go
  pkg/oc/admin/prune/deployments.go
  pkg/oc/admin/router/router.go
  pkg/oc/admin/top/images.go
  pkg/oc/admin/top/imagestreams.go
  pkg/oc/bootstrap/docker/openshift/project.go
  pkg/oc/cli/cmd/buildlogs.go
  pkg/oc/cli/cmd/create/clusterquota.go
  pkg/oc/cli/cmd/create/deploymentconfig.go
  pkg/oc/cli/cmd/create/identity.go
  pkg/oc/cli/cmd/create/imagestream.go
  pkg/oc/cli/cmd/create/imagestreamtag.go
  pkg/oc/cli/cmd/create/route.go
  pkg/oc/cli/cmd/create/user.go
  pkg/oc/cli/cmd/create/user_identity_mapping.go
  pkg/oc/cli/cmd/debug.go
  pkg/oc/cli/cmd/deploy.go
  pkg/oc/cli/cmd/idle.go
  pkg/oc/cli/cmd/importer/appjson.go
  pkg/oc/cli/cmd/importimage.go
  pkg/oc/cli/cmd/logs.go
  pkg/oc/cli/cmd/newapp.go
  pkg/oc/cli/cmd/process.go
  pkg/oc/cli/cmd/project.go
  pkg/oc/cli/cmd/projects.go
  pkg/oc/cli/cmd/request_project.go
  pkg/oc/cli/cmd/rollback.go
  pkg/oc/cli/cmd/rollout/latest.go
  pkg/oc/cli/cmd/startbuild.go
  pkg/oc/cli/cmd/status.go
  pkg/oc/cli/cmd/tag.go
  pkg/oc/cli/cmd/whoami.go
  pkg/oc/cli/util/clientcmd/client.go
  pkg/oc/cli/util/clientcmd/factory.go
  pkg/oc/cli/util/clientcmd/factory_builder.go
  pkg/oc/cli/util/clientcmd/factory_client_access.go
  pkg/oc/cli/util/clientcmd/factory_object_mapping.go
  pkg/oc/experimental/buildchain/buildchain.go
  pkg/oc/experimental/ipfailover/ipfailover.go
  pkg/oc/experimental/ipfailover/keepalived/plugin.go
Labels: approved, do-not-merge/hold, lgtm, size/XL

#19346 OpenShift SDN: Improvements to UpdateEgressNetworkPolicyRules()
  pkg/network/node/ovscontroller.go
Labels: approved, component/networking, lgtm, sig/networking, size/S

#19375 remove layer for creating event broadcaster
  pkg/apps/controller/deployer/factory.go
  pkg/apps/controller/deploymentconfig/factory.go
  pkg/build/controller/build/build_controller.go
  pkg/build/controller/buildconfig/buildconfig_controller.go
  pkg/cmd/infra/deployer/deployer.go
  pkg/cmd/openshift-controller-manager/controller/image.go
  pkg/cmd/openshift-controller-manager/controller_manager.go
  pkg/service/controller/ingressip/service_ingressip_controller.go
Labels: approved, lgtm, size/S

#19386 switch the sdn to use external types
  pkg/cmd/openshift-controller-manager/controller/interfaces.go
  pkg/cmd/openshift-controller-manager/controller/network_sdn.go
  pkg/cmd/openshift-controller-manager/controller_manager.go
  pkg/cmd/server/origin/admission/plugin_initializer.go
  pkg/cmd/server/origin/informers.go
  pkg/cmd/server/origin/master_config.go
  pkg/network/common/common.go
  pkg/network/common/common_test.go
  pkg/network/master/master.go
  pkg/network/master/subnets.go
  pkg/network/master/vnids.go
  test/integration/buildcontroller_test.go
Labels: approved, lgtm, sig/master, sig/networking, size/M

#19406 recycler images
  pkg/cmd/server/start/start_kube_controller_manager.go
  vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/patch_imagetemplate.go
Labels: approved, lgtm, size/S

#19420 Remove test reference to deleted content
  test/cmd/newapp.sh
Labels: approved, lgtm, queue/critical-fix, size/XS

#19414 Remove duplicate WantsAuthorizer interface
  pkg/cmd/openshift-controller-manager/controller/build.go
  pkg/cmd/server/admission/init.go
  pkg/cmd/server/admission/types.go
  pkg/ingress/admission/ingress_admission.go
  pkg/scheduler/admission/podnodeconstraints/admission.go
  pkg/scheduler/admission/podnodeconstraints/admission_test.go
  pkg/security/registry/podsecuritypolicyselfsubjectreview/rest_test.go
  pkg/service/admission/endpoint_admission.go
Labels: approved, lgtm, size/M

#19373 add a simple web console operator
  cmd/hypershift/main.go
  install/openshift-web-console-operator/install-rbac.yaml
  install/openshift-web-console-operator/install.yaml
  pkg/cmd/openshift-experimental/cmd.go
  pkg/cmd/openshift-operators/apis/operators/v1alpha1/types.go
  pkg/cmd/openshift-operators/apis/operators/v1alpha1helpers/helpers.go
  pkg/cmd/openshift-operators/apis/webconsole/v1alpha1/register.go
  pkg/cmd/openshift-operators/webconsole-operator/cmd.go
  pkg/cmd/openshift-operators/webconsole-operator/starter.go
  pkg/cmd/openshift-operators/webconsole-operator/sync_v310_00.go
  pkg/cmd/openshift-operators/webconsole-operator/webconsole_operator_trigger.go
  pkg/oc/bootstrap/bindata.go
  pkg/oc/bootstrap/clusteradd/cmd.go
  pkg/oc/bootstrap/clusteradd/components/web-console-operator/OWNERS
  pkg/oc/bootstrap/clusteradd/components/web-console-operator/web_console_operator.go
  test/extended/testdata/bindata.go
Labels: approved, lgtm, sig/master, size/XL

#19214 Add custom JSON marshaling implementations, metrics broken into lib
  test/extended/cluster/cl.go
  test/extended/cluster/metrics/metrics.go
Labels: approved, lgtm, size/M

#19328 Fix LDAP test to catch the correct output.
  test/extended/ldap_groups.sh
Labels: approved, lgtm, size/XS

#19372 Explicitly set the MTU on the tun0 interface
  pkg/network/node/ovscontroller.go
  pkg/network/node/ovscontroller_test.go
  pkg/network/node/sdn_controller.go
Labels: approved, component/networking, kind/bug, lgtm, size/S

#19390 cleanup launch of openshift controller client
  pkg/cmd/openshift-apiserver/server.go
  pkg/cmd/openshift-controller-manager/controller/config.go
  pkg/cmd/openshift-controller-manager/controller_manager.go
  pkg/cmd/openshift-kube-apiserver/server.go
  pkg/cmd/server/apis/config/helpers.go
  pkg/cmd/server/kubernetes/node/options/options.go
  pkg/cmd/server/origin/informers.go
  pkg/cmd/server/origin/master_config.go
  pkg/cmd/server/start/start_master.go
  test/extended/templates/helpers.go
  test/extended/templates/templateservicebroker_e2e.go
  test/extended/util/cli.go
  test/integration/buildcontroller_test.go
  test/integration/ingressip_test.go
  test/util/client.go
Labels: approved, lgtm, sig/master, size/L

#19391 UPSTREAM: 62744: Fix kubectl describe cronjob
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/util/factory_object_mapping.go
  vendor/k8s.io/kubernetes/pkg/printers/internalversion/BUILD
  vendor/k8s.io/kubernetes/pkg/printers/internalversion/describe.go
  vendor/k8s.io/kubernetes/pkg/printers/internalversion/describe_test.go
Labels: approved, lgtm, size/M

#19407 up: validate usage of enable on initialized cluster
  pkg/oc/bootstrap/docker/errors/docker.go
  pkg/oc/bootstrap/docker/up.go
  test/extended/clusterup.sh
Labels: approved, lgtm, size/S

#19417 examples/grafana: minor improvements to setup script
  examples/grafana/setup-grafana.sh
Labels: approved, lgtm, size/XS

#19426 glide: fix go4.org repo url and bump the k8s.io shas to match forks
  glide.lock
  glide.yaml
Labels: approved, lgtm, size/S

#19427 node, syscontainer: bind mount /opt/cni/bin from the host
  images/node/system-container/config.json.template
Labels: approved, lgtm, size/S

#19330 Fix for bugz 1564984 - rejected by router when using router sharding and NAMESPACE_LABELS
  pkg/router/controller/host_admitter.go
  pkg/router/controller/host_admitter_test.go
Labels: approved, component/routing, lgtm, size/L

#19445 system containers: remove extra comma, which breaks json syntax
  images/node/system-container/config.json.template
Labels: approved, lgtm, size/XS

#19312 Cluster Mirror Base
  test/extended/cluster/README.md
  test/extended/cluster/cm.go
  test/extended/cluster/context.go
Labels: approved, lgtm, size/L

#19423 Don't install template-service-broker broker resource unless tsb enabled
  pkg/oc/bootstrap/clusteradd/components/service-catalog/service_catalog.go
Labels: approved, lgtm, size/S

#19433 remove cruft
  pkg/oc/admin/diagnostics/diagnostics/client/pod/in_pod/auth.go
  pkg/oc/admin/diagnostics/diagnostics/client/pod/in_pod/cmd.go
  pkg/oc/cli/util/clientcmd/clientcmd.go
  pkg/oc/cli/util/clientcmd/factory_client_access.go
  pkg/oc/cli/util/clientcmd/factory_test.go
Labels: approved, lgtm, size/L

#19446 hack: use control-plane in build local images
  hack/build-local-images.py
Labels: approved, lgtm, size/XS

#19224 Prefix with unix protocol for docker shim socket
  pkg/cmd/server/apis/config/serialization_test.go
  pkg/cmd/server/apis/config/v1/conversions.go
  pkg/cmd/server/apis/config/v1/testdata/node-config.yaml
  pkg/cmd/server/apis/config/v1/types.go
  pkg/cmd/server/kubernetes/node/node_config_test.go
  test/util/server/server.go
Labels: approved, component/networking, lgtm, sig/networking, size/M

#19448 temporarily disable client plugin while we adjust to new kind/apiVersion
  test/extended/builds/pipeline.go
Labels: approved, lgtm, queue/blocks-others, sig/developer-experience, size/S

#19408 up: remove --env flag
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/oc/bootstrap/docker/run_self_hosted.go
  pkg/oc/bootstrap/docker/up.go
Labels: approved, lgtm, size/S

#19442 diagnostics: Break a loop when config file found
  pkg/oc/admin/diagnostics/config.go
Labels: approved, component/diagnostics, lgtm, size/XS

#19453 UPSTREAM: 62914: kubelet: fix flake in TestUpdateExistingNodeStatusTimeout
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_node_status_test.go
Labels: approved, kind/test-flake, lgtm, size/XS

#19456 update build-local-images for controlplane
  hack/build-local-images.py
Labels: approved, lgtm, retest-not-required, size/S

#19298 extended tests: use leaner image in valuefrom.go
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/valuefrom/failed-docker-build-value-from-config.yaml
  test/extended/testdata/builds/valuefrom/successful-docker-build-value-from-config.yaml
Labels: approved, area/tests, lgtm, sig/developer-experience, size/S

#19332 oc new-app: propagate cmdline env to pipeline/git builds
  pkg/oc/generate/app/app.go
  test/extended/builds/pipeline.go
  test/extended/util/framework.go
  test/integration/newapp_test.go
Labels: approved, component/cli, kind/bug, lgtm, sig/developer-experience, size/M

#19455 skip already exists errors for default role bindings
  pkg/authorization/controller/defaultrolebindings/defaultrolebindings.go
Labels: approved, lgtm, size/XS

#19355 Distinguish warning message between --build-loglevel and --env with binary builds
  pkg/oc/cli/cmd/startbuild.go
Labels: approved, lgtm, size/M

#19470 new-app: remove check for volumes in new-app test
  test/cmd/newapp.sh
Labels: approved, lgtm, queue/blocks-others, size/XS

#19472 .NET Core: Fix quickstart example template
  examples/quickstarts/dotnet.json
  pkg/oc/bootstrap/bindata.go
  test/extended/testdata/bindata.go
Labels: approved, lgtm, size/XS

#19416 Bug 1567532 - Unidle handling in router should ignore headless services
  pkg/router/template/plugin.go
Labels: approved, component/routing, lgtm, sig/networking, size/XS

#19263 Cut various dependencies out of the oc binary
  hack/import-restrictions.json
  pkg/cmd/server/apis/config/validation/oauth.go
  pkg/cmd/server/origin/master.go
  pkg/oauth/urls/urls.go
  pkg/oauth/util/discovery.go
  pkg/oauthserver/api/types.go
  pkg/oauthserver/authenticator/redirector/redirector.go
  pkg/oauthserver/authenticator/tokens/tokens.go
  pkg/oauthserver/oauth/handlers/default_auth_handler.go
  pkg/oauthserver/oauth/handlers/interfaces.go
  pkg/oauthserver/oauthserver/auth.go
  pkg/oauthserver/oauthserver/oauth_apiserver.go
  pkg/oauthserver/osinserver/osinserver.go
  pkg/oauthserver/server/errorpage/errorpage.go
  pkg/oauthserver/server/selectprovider/selectprovider.go
  pkg/oauthserver/server/selectprovider/selectprovider_test.go
  pkg/oauthserver/server/tokenrequest/endpoints.go
  pkg/oc/admin/diagnostics/diagnostics/cluster/network/in_pod/node.go
  pkg/oc/admin/diagnostics/diagnostics/cluster/network/in_pod/pod.go
  pkg/oc/admin/diagnostics/diagnostics/cluster/network/in_pod/service.go
  pkg/oc/admin/diagnostics/diagnostics/cluster/network/in_pod/util/log.go
  pkg/oc/admin/prune/imageprune/helper_test.go
  pkg/oc/admin/prune/imageprune/prune_test.go
  pkg/oc/admin/prune/images_test.go
  pkg/oc/bootstrap/clusterup/components/persistent-volumes/setup_persistent_volumes.go
  pkg/oc/util/docker/docker.go
  pkg/oc/util/tokencmd/request_token.go
  pkg/oc/util/tokencmd/request_token_test.go
  test/integration/auth_proxy_test.go
Labels: approved, lgtm, size/L

#19323 UPSTREAM: <carry>: disable local storage isolation feature gate
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_node_status_test.go
Labels: approved, lgtm, size/M

#19428 ipfailover - add missing ipset/libipset to image
  images/ipfailover/keepalived/Dockerfile
Labels: approved, lgtm, size/XS

#19473 remove directly kubelet dependency from deploymentconfigs
  pkg/apps/apiserver/apiserver.go
  pkg/apps/registry/deploylog/rest.go
  pkg/apps/registry/deploylog/rest_test.go
  pkg/cmd/server/origin/openshift_apiserver.go
Labels: approved, lgtm, sig/master, size/L

#19452 Creating an image stream tag is too likely to conflict
  pkg/image/registry/imagestreamtag/rest.go
  test/integration/imagestream_test.go
Labels: approved, lgtm, size/M

#19465 re-enable jenkins client plugin ext tests
  test/extended/builds/pipeline.go
Labels: approved, lgtm, sig/developer-experience, sig/storage, size/S

#19359 UPSTREAM: 62394: Revert "git: Use VolumeHost.GetExec() to execute stuff in volume plugins"
  vendor/k8s.io/kubernetes/pkg/volume/git_repo/BUILD
  vendor/k8s.io/kubernetes/pkg/volume/git_repo/git_repo.go
  vendor/k8s.io/kubernetes/pkg/volume/git_repo/git_repo_test.go
Labels: approved, lgtm, size/L

#19491 SDN: In maybeAddMacvlan(), print the error returned from ns.GetNS
  pkg/network/node/pod.go
Labels: approved, component/networking, lgtm, sig/networking, size/XS

#19512 Shrink openapi package size
  glide.lock
  glide.yaml
  pkg/openapi/zz_generated.openapi.go
  vendor/github.com/openshift/imagebuilder/builder.go
  vendor/github.com/openshift/imagebuilder/cmd/imagebuilder/imagebuilder.go
  vendor/github.com/openshift/imagebuilder/dockerclient/client.go
  vendor/github.com/openshift/imagebuilder/dockerclient/conformance_test.go
  vendor/github.com/openshift/imagebuilder/dockerclient/testdata/Dockerfile.reusebase
  vendor/github.com/openshift/source-to-image/glide.lock
  vendor/github.com/openshift/source-to-image/glide.yaml
  vendor/k8s.io/kube-openapi/pkg/aggregator/aggregator.go
  vendor/k8s.io/kube-openapi/pkg/builder/openapi.go
  vendor/k8s.io/kube-openapi/pkg/common/common.go
  vendor/k8s.io/kube-openapi/pkg/generators/extension.go
  vendor/k8s.io/kube-openapi/pkg/generators/extension_test.go
  vendor/k8s.io/kube-openapi/pkg/generators/openapi.go
  vendor/k8s.io/kube-openapi/pkg/generators/openapi_test.go
  vendor/k8s.io/kube-openapi/pkg/handler/handler.go
  vendor/k8s.io/kube-openapi/pkg/util/proto/testing/swagger.json
  vendor/k8s.io/kube-openapi/pkg/util/util_test.go
  vendor/k8s.io/kubernetes/Godeps/Godeps.json
  vendor/k8s.io/kubernetes/api/openapi-spec/swagger.json
  vendor/k8s.io/kubernetes/api/swagger-spec/resourceListing.json
  vendor/k8s.io/kubernetes/api/swagger-spec/version.json
  vendor/k8s.io/kubernetes/pkg/generated/openapi/zz_generated.openapi.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/Godeps/Godeps.json
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/Godeps/Godeps.json
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/Godeps/Godeps.json
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/Godeps/Godeps.json
  vendor/k8s.io/kubernetes/staging/src/k8s.io/code-generator/Godeps/Godeps.json
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/Godeps/Godeps.json
  vendor/k8s.io/kubernetes/staging/src/k8s.io/sample-apiserver/Godeps/Godeps.json
  vendor/k8s.io/kubernetes/staging/src/k8s.io/sample-controller/Godeps/Godeps.json
Labels: approved, lgtm, size/XXL

#18599 Add --compress option to oc rsync
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/oc/cli/cmd/rsync/copyrsync.go
  pkg/oc/cli/cmd/rsync/rsync.go
  pkg/oc/cli/cmd/rsync/util.go
Labels: approved, lgtm, size/S

#19515 UPSTREAM: 62913: make a simple dynamic client that is easy to use
  vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/core.go
  vendor/k8s.io/kubernetes/pkg/controller/garbagecollector/garbagecollector.go
  vendor/k8s.io/kubernetes/pkg/controller/garbagecollector/garbagecollector_test.go
  vendor/k8s.io/kubernetes/pkg/controller/garbagecollector/graph_builder.go
  vendor/k8s.io/kubernetes/pkg/controller/garbagecollector/operations.go
  vendor/k8s.io/kubernetes/pkg/controller/namespace/deletion/BUILD
  vendor/k8s.io/kubernetes/pkg/controller/namespace/deletion/namespaced_resources_deleter.go
  vendor/k8s.io/kubernetes/pkg/controller/namespace/deletion/namespaced_resources_deleter_test.go
  vendor/k8s.io/kubernetes/pkg/controller/namespace/namespace_controller.go
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/util/factory_object_mapping.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/BUILD
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/unstructured.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/unstructuredscheme/BUILD
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/unstructuredscheme/scheme.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/dynamic/BUILD
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/dynamic/bad_debt.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/dynamic/client.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/dynamic/client_pool.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/dynamic/client_test.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/dynamic/scheme.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/dynamic/simple.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/rest/request.go
  vendor/k8s.io/kubernetes/test/e2e_node/services/BUILD
  vendor/k8s.io/kubernetes/test/e2e_node/services/namespace_controller.go
  vendor/k8s.io/kubernetes/test/integration/client/dynamic_client_test.go
  vendor/k8s.io/kubernetes/test/integration/master/crd_test.go
Labels: approved, lgtm, size/XXL

#18841 Improve NGINX-based router
  images/router/nginx/Dockerfile
  images/router/nginx/conf/error-page-503.html
  images/router/nginx/conf/nginx-config.template
  images/router/nginx/nginx.repo
  images/router/nginx/reload-nginx
  pkg/router/template/template_helper.go
  pkg/router/template/template_helper_test.go
Labels: approved, lgtm, size/XL

#19349 Allow authorization of SCC use via RBAC
  pkg/cmd/server/origin/openshift_apiserver.go
  pkg/oc/admin/router/router.go
  pkg/security/admission/admission.go
  pkg/security/admission/admission_test.go
  pkg/security/admission/scc_exec.go
  pkg/security/apiserver/apiserver.go
  pkg/security/registry/podsecuritypolicyreview/rest.go
  pkg/security/registry/podsecuritypolicyreview/rest_test.go
  pkg/security/registry/podsecuritypolicyselfsubjectreview/rest.go
  pkg/security/registry/podsecuritypolicyselfsubjectreview/rest_test.go
  pkg/security/registry/podsecuritypolicysubjectreview/rest.go
  pkg/security/registry/podsecuritypolicysubjectreview/rest_test.go
  pkg/security/securitycontextconstraints/matcher.go
  test/cmd/policy.sh
  test/integration/scc_test.go
Labels: api-approved, approved, lgtm, needs-api-review, sig/security, size/L

#18926 Fix doc text on `migrate legacy-hpa`
  pkg/oc/admin/migrate/legacyhpa/hpa.go
Labels: approved, lgtm, size/XS

#19489 remove direct kubelet connection for binary builds
  pkg/build/apiserver/apiserver.go
  pkg/build/registry/buildconfiginstantiate/rest.go
  pkg/cmd/server/apis/config/helpers.go
  pkg/cmd/server/origin/master.go
  pkg/cmd/server/origin/master_config.go
  pkg/cmd/server/origin/openshift_apiserver.go
  pkg/cmd/server/origin/reststorage_validation_test.go
Labels: approved, lgtm, size/L

#19496 switch sample jenkins template to ephemeral to match auto provisioner
  pkg/oc/bootstrap/clusteradd/components/sample-templates/sample_templates.go
  test/extended/clusterup.sh
Labels: approved, lgtm, sig/developer-experience, sig/master, size/M

#19499 remove useless logs from level 0
  pkg/build/builder/docker.go
Labels: approved, lgtm, size/XS

#19504 Print pod logs for tests
  test/extended/networking/multicast.go
Labels: approved, lgtm, sig/networking, size/XS

#19507 fix forcepull test to work w/ pullthrough imagespecs
  test/extended/builds/forcepull.go
  test/extended/testdata/bindata.go
  test/extended/testdata/forcepull-test.json
Labels: approved, lgtm, queue/blocks-others, size/XS

#19517 UPSTREAM: 62146: Fix daemon-set-controller bootstrap RBAC policy
  test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml
  test/testdata/bootstrappolicy/bootstrap_policy_file.yaml
  vendor/k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/controller_policy.go
  vendor/k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/controller-roles.yaml
Labels: approved, lgtm, sig/master, size/XS

#19531 ovs: add default 30s timeout to ovs-vsctl operations
  pkg/util/ovs/ovs.go
  pkg/util/ovs/ovs_test.go
Labels: approved, lgtm, size/M

#19541 Fix ext test namespace stuff
  test/extended/image_ecosystem/jenkins_plugin.go
  test/extended/image_ecosystem/s2i_php.go
Labels: approved, lgtm, queue/blocks-others, retest-not-required, sig/developer-experience, size/S

#19545 UPSTREAM: 63160: kubelet: logs: do not wait when following terminated container
  vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/logs/logs.go
Labels: approved, kind/bug, lgtm, size/S

#19544 bump(*)
  glide.lock
  vendor/github.com/openshift/source-to-image/hack/test-stirunimage.sh
  vendor/github.com/openshift/source-to-image/pkg/build/strategies/sti/sti.go
  vendor/github.com/openshift/source-to-image/pkg/tar/tar.go
  vendor/github.com/openshift/source-to-image/tools/depchecker/godepchecker.go
Labels: approved, lgtm, size/L

#19534 Allow imagestreamtag delete to retry conflicts
  pkg/image/registry/imagestreamtag/rest.go
Labels: approved, lgtm, size/M

#19494 Update imagebuilder to fix multistage build bugs
  glide.lock
  pkg/build/builder/dockerutil.go
  vendor/github.com/emicklei/go-restful-swagger12/origin.sha
Labels: approved, lgtm, size/S
