Repository openshift/origin, pull requests merged in 2019-01, with the labels that each got.

#21712 Allow kube:admin to be scoped
  pkg/apiserver/authentication/oauth/bootstrapauthenticator.go
  pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/patch_authenticator.go
  pkg/oauthserver/authenticator/password/bootstrap/bootstrap.go
  pkg/oauthserver/oauthserver/auth.go
  pkg/oauthserver/oauthserver/oauth_apiserver.go
  pkg/oauthserver/server/selectprovider/bootstrapselectprovider.go
  pkg/oauthserver/server/session/bootstrapauthenticator.go
Labels: approved, lgtm, size/L

#21713 Widen the smoke-4 suite to be the full parallel, minus known failures
  cmd/openshift-tests/e2e.go
Labels: approved, lgtm, size/S

#21714 Explain which image short name is missing from the input
  pkg/oc/cli/admin/release/image_mapper.go
Labels: approved, lgtm, size/XS

#21721 [release-3.11] UPSTREAM: 70580: PV Controller -- fix recycling
  vendor/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/pv_controller.go
  vendor/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/recycle_test.go
Labels: approved, lgtm, size/S

#21720 [release-3.10] UPSTREAM: 70580: PV Controller -- fix recycling
  vendor/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/pv_controller.go
  vendor/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/recycle_test.go
Labels: approved, lgtm, size/S

#21139 Fix typos
  HACKING.md
Labels: approved, lgtm, ok-to-test, size/S

#21730 Temporarily remove these tests from conformance until they are fixed
  test/extended/util/test.go
Labels: approved, lgtm, size/XS

#21706 Fix completion for __oc_get_containers
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/oc/cli/cli_bashcomp_func.go
Labels: approved, lgtm, size/XS

#21736 Remove the smoke-4 suite and add new suites for scalability
  cmd/openshift-tests/e2e.go
  cmd/openshift-tests/openshift-tests.go
  pkg/test/ginkgo/cmd_runsuite.go
  pkg/test/ginkgo/test.go
  test/extended/operators/cluster.go
  test/extended/util/test.go
Labels: approved, lgtm, size/L

#21654 sdn: clean up startup scripts, remove DNS, watch config file
  cmd/openshift-sdn/openshift-sdn.go
  cmd/sdn-cni-plugin/openshift-sdn_linux.go
  cmd/sdn-cni-plugin/sdn_cni_plugin_test.go
  pkg/cmd/openshift-sdn/OWNERS
  pkg/cmd/openshift-sdn/cmd.go
  pkg/cmd/openshift-sdn/informers.go
  pkg/cmd/openshift-sdn/proxy.go
  pkg/cmd/openshift-sdn/sdn.go
  pkg/cmd/server/kubernetes/network/network_config.go
  pkg/cmd/server/kubernetes/network/options/options.go
  pkg/cmd/server/kubernetes/network/sdn_linux.go
  pkg/cmd/server/kubernetes/network/sdn_unsupported.go
  pkg/cmd/server/kubernetes/network/transport/transport.go
  pkg/cmd/server/start/network/node_args.go
  pkg/cmd/server/start/network/start_network.go
  pkg/network/node/cniserver/cniserver.go
  pkg/network/node/cniserver/cniserver_test.go
  pkg/network/node/node.go
  pkg/network/node/pod.go
  test/cmd/help.sh
Labels: approved, lgtm, size/XXL

#21740 Make the multicast extended test resilient to packet loss
  test/extended/networking/multicast.go
Labels: approved, component/networking, kind/test-flake, lgtm, sig/networking, size/M

#21746 pkg/version: set versionFromGit to 'unknown' value for debugging in IDE
  HACKING.md
  pkg/version/version.go
  test/util/server/server.go
Labels: approved, lgtm, size/M

#21745 stop looking at legacy clusteroperator objects and fix the clusteroperator status test
  test/extended/operators/operators.go
Labels: approved, lgtm, size/M

#21744 speed up various build tests to avoid flaking
  test/extended/builds/labels.go
  test/extended/builds/proxy.go
  test/extended/builds/s2i_root.go
  test/extended/templates/templateinstance_readiness.go
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/build-postcommit/sti.yaml
  test/extended/testdata/builds/build-secrets/Dockerfile
  test/extended/testdata/builds/build-secrets/test-docker-build.json
  test/extended/testdata/builds/build-secrets/test-s2i-build.json
  test/extended/testdata/builds/build-timing/s2i-binary-dir/.s2i/bin/assemble
  test/extended/testdata/builds/build-timing/s2i-binary-dir/.s2i/bin/run
  test/extended/testdata/builds/build-timing/test-docker-build.json
  test/extended/testdata/builds/build-timing/test-s2i-build.json
  test/extended/testdata/builds/statusfail-failedassemble.yaml
  test/extended/testdata/builds/statusfail-postcommithook.yaml
  test/extended/testdata/builds/statusfail-pushtoregistry.yaml
  test/extended/testdata/builds/test-auth-build.yaml
  test/extended/testdata/builds/test-build-proxy.yaml
  test/extended/testdata/builds/test-build-revision.json
  test/extended/testdata/builds/test-build.yaml
  test/extended/testdata/builds/test-cds-dockerbuild.json
  test/extended/testdata/builds/test-cds-sourcebuild.json
  test/extended/testdata/builds/test-docker-build-pullsecret.json
  test/extended/testdata/builds/test-docker-build.json
  test/extended/testdata/builds/test-docker-no-outputname.json
  test/extended/testdata/builds/test-nosrc-build.json
  test/extended/testdata/builds/test-s2i-build-quota.json
  test/extended/testdata/builds/test-s2i-build.json
  test/extended/testdata/builds/test-s2i-no-outputname.json
  test/extended/testdata/builds/valuefrom/failed-sti-build-value-from-config.yaml
  test/extended/testdata/builds/valuefrom/successful-sti-build-value-from-config.yaml
  test/extended/testdata/templates/templateinstance_readiness.yaml
Labels: approved, lgtm, size/XL

#21269 Re-enable emptydir test, no longer uses git volume
  test/extended/util/test.go
Labels: approved, lgtm, size/XS

#21758 UPSTREAM: <carry>: require good status on discovery check
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/apiserver/apiserver.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/controllers/status/available_controller.go
Labels: approved, lgtm, size/M

#21711 Add kubectl bash compeltion to client RPM package
  origin.spec
Labels: approved, lgtm, size/XS

#21613 build/strategy: wire in blob mount-from functionality
  pkg/build/controller/strategy/docker.go
  pkg/build/controller/strategy/docker_test.go
  pkg/build/controller/strategy/sti.go
  pkg/build/controller/strategy/sti_test.go
  pkg/build/util/util.go
Labels: approved, lgtm, size/M

#21735 Preserve completed deployer pods
  pkg/apps/controller/deployer/deployer_controller.go
  pkg/apps/controller/deployer/deployer_controller_test.go
Labels: approved, lgtm, size/M

#21723 Don't restart pods on SDN restart/upgrade
  pkg/network/node/cniserver/cniserver.go
  pkg/network/node/node.go
  pkg/network/node/ovscontroller.go
  pkg/network/node/pod.go
  pkg/network/node/pod_test.go
  pkg/network/node/runtime.go
  pkg/network/node/sdn_controller.go
  pkg/util/ovs/fake_ovs.go
  pkg/util/ovs/fake_ovs_test.go
  pkg/util/ovs/ovs.go
  pkg/util/ovs/ovs_test.go
  pkg/util/ovs/parse.go
Labels: approved, component/networking, kind/bug, lgtm, sig/networking, size/L

#21764 UPSTREAM: 72744: delete as much content from a namespace as possible
  vendor/k8s.io/kubernetes/pkg/controller/namespace/deletion/namespaced_resources_deleter.go
Labels: approved, lgtm, size/XS

#21773 Set up 1.12.4 branch publishing
  publishing-kube-rules.yaml
Labels: approved, lgtm, size/M

#21752 [3.11] MetricsApiProxy diagnostic: fix endpoint
  pkg/oc/cli/admin/diagnostics/diagnostics/cluster/metrics.go
Labels: approved, lgtm, size/XS

#21772 Support openshift-test profiling like all the other binaries
  cmd/openshift-tests/openshift-tests.go
Labels: approved, lgtm, size/XS

#21761 build - Stage policy.json for Buildah
  pkg/build/controller/build/build_controller.go
  pkg/build/controller/strategy/util.go
  pkg/build/util/consts.go
Labels: approved, lgtm, size/S

#21701 Make viewing node logs from the CLI easy
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/oc/cli/admin/admin.go
  pkg/oc/cli/admin/node/logs/logs.go
  pkg/oc/cli/admin/node/logs/logs_test.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_server_journal.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_server_journal_test.go
Labels: approved, lgtm, size/XXL

#21751 [3.10] MetricsApiProxy diagnostic: fix endpoint
  pkg/oc/admin/diagnostics/diagnostics/cluster/metrics.go
Labels: approved, lgtm, size/XS

#21679 add easy pattern for customresource validation
  pkg/admission/customresourcevalidation/attributes.go
  pkg/admission/customresourcevalidation/customresourcevalidationregistration/cr_validation_registration.go
  pkg/admission/customresourcevalidation/customresourcevalidator.go
  pkg/admission/customresourcevalidation/customresourcevalidator_test.go
  pkg/admission/customresourcevalidation/helpers.go
  pkg/admission/customresourcevalidation/image/validate_image.go
  pkg/cmd/openshift-kube-apiserver/server.go
Labels: approved, lgtm, sig/master, size/XL

#21785 make sure event messages end up one one line and include counts
  pkg/monitor/cmd.go
  pkg/monitor/event.go
Labels: approved, lgtm, size/XS

#21794 test/extended/README openshift/all->all suite
  test/extended/README.md
Labels: approved, lgtm, size/XS

#21634 handle appsv1.DeploymenConfigs in AttachablePodForObject helper
  pkg/oc/originpolymorphichelpers/attachablepodforobject.go
Labels: approved, lgtm, size/S

#21733 add kubeadmin login test
  test/extended/bootstrap_user/bootstrap_user_login.go
  test/extended/include.go
Labels: approved, lgtm, size/M

#21799 Fix the router tests host name to use the external load balancer service
  test/extended/router/router.go
Labels: approved, lgtm, size/XS

#21694 add operator metrics test for requests per second
  pkg/test/ginkgo/cmd_runsuite.go
  test/extended/util/metrics.go
Labels: approved, lgtm, size/L

#21815 set the QPS ratchet correctly
  test/extended/util/metrics.go
Labels: approved, size/XS

#21806 Make DynamicProvisioner serial because it consumes a lot of AWS quota
  test/extended/util/test.go
Labels: approved, lgtm, size/XS

#21819 Revert #21694, most components are not behaving properly
  pkg/test/ginkgo/cmd_runsuite.go
Labels: approved, size/M

#21814 improve deprecation message for non-ca adm cmds
  pkg/oc/cli/admin/admin.go
Labels: approved, lgtm, size/S

#21756 Update custom func in completion
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/oc/cli/cli_bashcomp_func.go
Labels: approved, lgtm, size/M

#21791 Wait at end of deployer tests to catch log output
  test/extended/testdata/bindata.go
  test/extended/testdata/deployments/custom-deployment.yaml
  test/extended/testdata/deployments/test-deployment-test.yaml
Labels: approved, lgtm, size/XS

#21797 Allow --unify=false for journal
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/oc/cli/admin/node/logs/logs.go
Labels: approved, lgtm, size/M

#21810 oc adm release new doesn't replace correctly for leading characters
  pkg/oc/cli/admin/release/image_mapper.go
  pkg/oc/cli/admin/release/image_mapper_test.go
Labels: approved, lgtm, size/M

#21813 Project config validation
  glide.lock
  pkg/admission/customresourcevalidation/customresourcevalidationregistration/cr_validation_registration.go
  pkg/admission/customresourcevalidation/project/validate_project.go
  pkg/openapi/zz_generated.openapi.go
  vendor/bitbucket.org/ww/goautoneg/.hg_archival.txt
  vendor/github.com/openshift/api/config/v1/types_build.go
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/types_project.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/types.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/library-go/pkg/config/clusteroperator/v1helpers/status.go
  vendor/github.com/openshift/library-go/pkg/config/clusteroperator/v1helpers/status_test.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle_test.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target_test.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/event_helpers.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/event_helpers_test.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/apps.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/backingresource/backing_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/backingresource/backing_resource_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/common/helpers.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/common/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/node/node_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/node/node_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/revision/revision_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/revision/revision_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1helpers/helper_test.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1helpers/helpers.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1status/controller.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/test_helpers.go.go
Labels: approved, lgtm, size/XXL

#21824 no longer validate existence of wildfly imagestream as part of switch…
  test/extended/util/framework.go
Labels: approved, lgtm, size/XS

#21787 Add telemetry e2e test and more prometheus e2e tests
  test/common/build/controllers.go
  test/extended/builds/controller_compat.go
  test/extended/prometheus/prometheus.go
  test/extended/prometheus/prometheus_builds.go
  test/extended/util/cli.go
  test/extended/util/framework.go
  test/extended/util/jenkins/ref.go
  test/extended/util/test.go
  test/integration/buildcontroller_test.go
Labels: approved, lgtm, size/L

#21827 oc adm release new should prefer openshift scoped git labels
  pkg/oc/cli/admin/release/new.go
Labels: approved, lgtm, size/S

#21762 move from openshift/jenkins imagestream to test imagestream that forc…
  test/extended/builds/pipeline_origin_bld.go
  test/extended/util/jenkins/ref.go
Labels: approved, lgtm, size/M

#21829 Return decoding errors of non-legacy config types
  pkg/cmd/openshift-apiserver/cmd.go
  pkg/cmd/openshift-controller-manager/cmd.go
  pkg/cmd/openshift-kube-apiserver/cmd.go
Labels: approved, lgtm, size/S

#21753 e2e: Add a test verifying OLM is working properly by listing its resources
  test/extended/operators/olm.go
Labels: approved, lgtm, size/M

#21767 Apply default proxy configuration to build pod through env vars
  pkg/build/controller/build/build_controller.go
  pkg/build/controller/build/defaults/defaults.go
  pkg/build/controller/build/defaults/defaults_test.go
Labels: approved, lgtm, size/L

#21826 test, deployments: do not use logs -f
  test/extended/deployments/deployments.go
  test/extended/testdata/bindata.go
  test/extended/testdata/deployments/custom-deployment.yaml
  test/extended/testdata/deployments/test-deployment-test.yaml
Labels: approved, lgtm, size/S

#21842 Rename Payload in cluster version to Image
  glide.lock
  pkg/oc/cli/admin/release/info.go
  pkg/oc/cli/admin/upgrade/upgrade.go
  pkg/openapi/zz_generated.openapi.go
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/library-go/Makefile
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/lib/golang.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/golang/verify-update.mk
  vendor/github.com/openshift/library-go/pkg/config/clusteroperator/v1helpers/status.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/revision/revision_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/revision/revision_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd_test.go
  vendor/github.com/openshift/library-go/pkg/operator/status/version.go
  vendor/github.com/openshift/library-go/pkg/operator/status/version_test.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
Labels: approved, lgtm, size/XL

#21835 pkg/oc/cli/admin/release/info: Fix pullspecs default
  pkg/oc/cli/admin/release/info.go
Labels: approved, lgtm, size/XS

#21854 Deployment test is too aggressive on start timing
  test/extended/deployments/deployments.go
Labels: approved, lgtm, size/XS

#21845 Synchronize access to shared data in commands with concurrency
  pkg/oc/cli/admin/release/mirror.go
  pkg/oc/cli/admin/release/new.go
Labels: approved, lgtm, size/XS

#21865 Temporarily disable flaky volume test
  test/extended/util/test.go
Labels: approved, lgtm, size/XS

#21860 UPSTREAM: 69895: Reduce cardinality of admission metrics
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/admission/metrics/metrics.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/admission/metrics/metrics_test.go
Labels: approved, lgtm, size/M

#21861 UPSTREAM: 72118: Fixed clearing of devicePath after UnmountDevice
  vendor/k8s.io/kubernetes/pkg/kubelet/volumemanager/cache/actual_state_of_world.go
  vendor/k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler/BUILD
  vendor/k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler/reconciler_test.go
  vendor/k8s.io/kubernetes/pkg/volume/testing/testing.go
Labels: approved, lgtm, size/L

#21862 Update publisher bot for the master branch
  publishing-rules.yaml
Labels: approved, lgtm, size/XS

#21397 UPSTREAM: 69008: improve pleg error msg when it has never been successful
  vendor/k8s.io/kubernetes/pkg/kubelet/pleg/generic.go
  vendor/k8s.io/kubernetes/pkg/kubelet/pleg/generic_test.go
Labels: approved, lgtm, size/S

#21608 UPSTREAM: 68663: Ignore kubelet proxy settings in http probe
  vendor/k8s.io/kubernetes/pkg/probe/http/http.go
  vendor/k8s.io/kubernetes/pkg/probe/http/http_test.go
Labels: approved, kind/post-rebase, lgtm, size/M

#21870 UPSTREAM: 73277: Ignore GOAWAY errors
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/net/http.go
Labels: approved, lgtm, size/XS

#21360 Typo fix
  pkg/oc/cli/set/volume.go
Labels: approved, lgtm, lifecycle/stale, ok-to-test, size/XS

#21874 publishing: get rid of origin-4.0 to kube 1.11 rules
  publishing-kube-rules.yaml
Labels: approved, lgtm, size/M

#21879 Prevent internal OAuth server from running when using external
  pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/patch.go
  pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/patch_handlerchain.go
Labels: approved, lgtm, size/S

#21873 publishing: add rules for 3.11 branch to track 1.11.1 kube
  publishing-rules.yaml
Labels: approved, lgtm, size/XS

#21888 UPSTREAM: 70263: Remove subPath tests from host_path.go
  vendor/k8s.io/kubernetes/test/e2e/common/host_path.go
Labels: approved, lgtm, size/M

#21886 oc login: use system roots when necessary
  pkg/oc/cli/admin/prune/imageprune/prune.go
  pkg/oc/cli/login/helpers.go
  pkg/oc/cli/login/loginoptions_test.go
  pkg/oc/lib/tokencmd/request_token.go
  pkg/oc/lib/tokencmd/request_token_test.go
Labels: approved, lgtm, size/L

#21872 UPSTREAM: 70939: Use more precise Skipf() locations in tests
  vendor/k8s.io/kubernetes/test/e2e/framework/util.go
Labels: approved, lgtm, size/M

#21877 Fix broken update handling of path-based routes
  pkg/router/controller/hostindex/hostindex.go
  pkg/router/controller/hostindex/hostindex_test.go
Labels: approved, lgtm, sig/network-edge, size/M

#21857 handle named certificates with no explicit names
  pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/flags.go
  pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/flags_test.go
Labels: approved, lgtm, size/M

#21903 [release-3.10] Fix broken update handling of path-based routes
  pkg/router/controller/hostindex/hostindex.go
  pkg/router/controller/hostindex/hostindex_test.go
Labels: approved, lgtm, size/M

#21617 Add default wildcard routing e2e test
  test/extended/router/wildcard.go
  test/extended/util/test.go
Labels: approved, lgtm, sig/network-edge, size/L

#21914 UPSTREAM: 69755: Use fsync instead of sync for test
  vendor/k8s.io/kubernetes/test/e2e/apps/statefulset.go
  vendor/k8s.io/kubernetes/test/e2e/framework/statefulset_utils.go
Labels: approved, lgtm, size/XS

#21912 UPSTREAM: <carry>: don't double pluralize features
  vendor/k8s.io/kubernetes/staging/src/k8s.io/code-generator/cmd/client-gen/generators/client_generator.go
Labels: approved, lgtm, size/XS

#21911 Add better logging to deployerPodInvariantChecker
  test/extended/deployments/util.go
Labels: approved, lgtm, size/XS
