Repository openshift/origin, pull requests merged in 2019-04, with the labels that each got.

#22448 UPSTREAM: <drop>: comment out componentconfig registration for kube controller manager
  vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go
Labels: approved, lgtm, size/XS

#22452 update publish rules for origin-4.1-kubernetes-1.13.4
  publishing-rules.yaml
Labels: approved, lgtm, size/XS

#22346 [3.11] Bug 1690066: Report build failures due to eviction
  glide.lock
  pkg/build/controller/build/build_controller.go
  pkg/build/controller/build/build_controller_test.go
  vendor/github.com/google/btree/go.mod
  vendor/github.com/openshift/api/build/v1/consts.go
  vendor/github.com/vmware/photon-controller-go-sdk/photon/client.go
  vendor/github.com/vmware/photon-controller-go-sdk/photon/deployments_test.go
  vendor/github.com/vmware/photon-controller-go-sdk/photon/lightwave/oidcclient_test.go
Labels: approved, lgtm, size/L

#22397 bug 1676720. Fix diagnostics check for logging curator
  pkg/oc/cli/admin/diagnostics/cluster.go
  pkg/oc/cli/admin/diagnostics/diagnostics/cluster/aggregated_logging/cronjobs.go
  pkg/oc/cli/admin/diagnostics/diagnostics/cluster/aggregated_logging/cronjobs_test.go
  pkg/oc/cli/admin/diagnostics/diagnostics/cluster/aggregated_logging/deploymentconfigs.go
  pkg/oc/cli/admin/diagnostics/diagnostics/cluster/aggregated_logging/diagnostic.go
  pkg/oc/cli/admin/diagnostics/diagnostics/cluster/aggregated_logging/interfaces.go
Labels: approved, lgtm, size/L

#22453 zero diff bump to get back masters
  glide.lock
  glide.yaml
  vendor/github.com/openshift/api/glide.lock
  vendor/github.com/openshift/client-go/glide.lock
  vendor/github.com/openshift/client-go/glide.yaml
  vendor/github.com/openshift/library-go/glide.lock
  vendor/github.com/openshift/library-go/glide.yaml
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/certsyncpod/certsync_cmd.go
Labels: approved, size/M

#22455 Disable BlockVolume tests that need kubelet 1.13
  test/extended/util/test.go
Labels: approved, lgtm, size/XS

#22454 e2e: disable broken hostAlias test
  test/extended/util/test.go
Labels: approved, lgtm, size/XS

#22440 Check for closed watches in deployerPodInvariantChecker
  test/extended/deployments/util.go
Labels: approved, lgtm, size/XS

#22467 add rules for publishing 1.14.0
  publishing-kube-rules.yaml
Labels: approved, size/L

#22447 Improve output of upgrade command for versions and important changes
  test/e2e/upgrade/upgrade.go
Labels: approved, lgtm, size/M

#22419 Add an e2e test that verifies the CLI works under arbitrary Linux envs
  test/extended/cli/compat.go
Labels: approved, lgtm, size/L

#22439 release: Support extracting the 'oc' and 'openshift-install' binaries
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/oc/cli/admin/release/extract.go
  pkg/oc/cli/admin/release/extract_tools.go
  pkg/oc/cli/admin/release/extract_tools_test.go
  pkg/oc/cli/admin/release/git.go
  pkg/oc/cli/admin/release/new.go
  pkg/oc/cli/image/extract/extract.go
Labels: approved, lgtm, size/XL

#22476 Disable kcm metrics endpoint temporarily
  test/extended/prometheus/prometheus.go
Labels: approved, lgtm, size/XS

#22458 UPSTREAM: 75943: Fix AWS driver to provision specified fsType
  vendor/k8s.io/kubernetes/pkg/volume/awsebs/aws_util.go
Labels: approved, lgtm, sig/storage, size/XS

#22443 [3.11] Fix up VNID tracking on restart / delete unused NetworkPolicy flows
  pkg/network/node/multitenant.go
  pkg/network/node/networkpolicy.go
  pkg/network/node/ovscontroller.go
  pkg/network/node/ovscontroller_test.go
Labels: approved, lgtm, size/L

#22463 Attempt to fix TestIntermittentConnectionLoss test
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/apis/config/types.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/apis/config/v1/types.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/apis/config/v1/zz_generated.conversion.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/apis/config/v1/zz_generated.deepcopy.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/apis/config/zz_generated.deepcopy.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/options/encryptionconfig/config.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/options/encryptionconfig/config_test.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/storage/value/encrypt/envelope/BUILD
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/storage/value/encrypt/envelope/grpc_service_unix_test.go
Labels: approved, lgtm, size/L

#22477 UPSTREAM: 76142: Fix TestCreateDisk by sorting tags
  vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws_test.go
Labels: approved, lgtm, size/S

#22480 Remove unused code in prune deployments
  pkg/oc/cli/admin/prune/deployments/deployments.go
  pkg/oc/cli/admin/prune/deployments/prune.go
Labels: approved, lgtm, size/XS

#21795 UPSTREAM: 73041: fix some race conditions in logs -f
  vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/logs/logs.go
  vendor/k8s.io/kubernetes/test/e2e/kubectl/kubectl.go
Labels: approved, lgtm, size/M

#22490 UPSTREAM: 76189: Fix flaky legacy pod autoscaler test
  vendor/k8s.io/kubernetes/pkg/controller/podautoscaler/legacy_horizontal_test.go
Labels: approved, lgtm, size/XS

#22475 publishing: skip gomod
  publishing-kube-rules.yaml
  publishing-rules.yaml
Labels: approved, lgtm, size/XS

#22471 Bug 1695554 - SDN may be very slow to start up after a reboot
  pkg/network/node/node.go
Labels: approved, component/networking, kind/bug, lgtm, sig/networking, size/S

#22469 PSP subject review: do not pass empty user to FindApplicableSCCs
  pkg/security/apis/security/validation/validation.go
  pkg/security/apis/security/validation/validation_test.go
  pkg/security/apiserver/registry/podsecuritypolicysubjectreview/rest.go
Labels: approved, lgtm, size/S

#22479 BZ 1592217 Correct error message when joining two projects
  pkg/oc/cli/admin/network/join_projects.go
Labels: approved, lgtm, size/S

#22488 Improve performance of extract --tools
  pkg/oc/cli/admin/release/extract_tools.go
Labels: approved, lgtm, size/S

#22097 Deprecate oc admin ca commands
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/cmd/server/admin/create_mastercerts.go
  pkg/oc/cli/admin/admin.go
  pkg/oc/cli/admin/cert/cert.go
  test/cmd/admin.sh
  test/cmd/help.sh
Labels: approved, lgtm, size/M

#22495 Bug 1690243: Add server side table printer for RangeAllocation
  pkg/printers/internalversion/printer.go
  pkg/printers/internalversion/printer_test.go
Labels: approved, lgtm, size/M

#22466 e2e: test more prometheus scrape targets
  test/extended/prometheus/prometheus.go
Labels: approved, lgtm, size/XS

#22498 Add missing kubectl plugin patches
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/plugin/BUILD
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/plugin/plugin.go
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/plugin/plugin_test.go
Labels: approved, lgtm, size/L

#22429 UPSTREAM: 75785: add annotation from namespace controller to indicate…
  vendor/k8s.io/kubernetes/pkg/controller/namespace/deletion/namespaced_resources_deleter.go
  vendor/k8s.io/kubernetes/pkg/controller/namespace/deletion/namespaced_resources_deleter_test.go
Labels: approved, lgtm, size/L

#22501 Add missing 1.13 nullable patches
  hack/update-generated-openapi.sh
  pkg/openapi/zz_generated.openapi.go
  vendor/k8s.io/kubernetes/pkg/generated/openapi/zz_generated.openapi.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/hack/openapi-violation.list
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/fuzzer/fuzzer.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/types_jsonschema.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.pb.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types_jsonschema.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.conversion.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/validation/validation.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/validation/validation_test.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/apiserver.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/validation/validation.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/validation/validation_test.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/generated/openapi/zz_generated.openapi.go
Labels: approved, lgtm, queue/critical-fix, size/L

#22100 Handle watch restarts in deployers
  pkg/apps/apiserver/registry/deploylog/rest.go
  pkg/apps/apiserver/registry/deploylog/wait.go
  pkg/apps/apiserver/registry/deploylog/wait_test.go
  pkg/apps/strategy/support/acceptor.go
Labels: approved, lgtm, size/L

#22516 Bug 1697875: UPSTREAM 72491: Ensure controller manager and scheduler can perform delegated auth checks
  vendor/k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/namespace_policy.go
  vendor/k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go
  vendor/k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/cluster-roles.yaml
  vendor/k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/namespace-role-bindings.yaml
  vendor/k8s.io/kubernetes/test/integration/serving/BUILD
  vendor/k8s.io/kubernetes/test/integration/serving/serving_test.go
Labels: approved, lgtm, priority/critical-urgent, queue/critical-fix, size/L

#22523 use go 1.11 gofmt
  pkg/apps/apis/apps/v1/defaults_test.go
  pkg/apps/apis/apps/validation/validation_test.go
  pkg/apps/strategy/support/lifecycle_test.go
  pkg/autoscaling/admission/apis/clusterresourceoverride/v1/swagger_doc.go
  pkg/autoscaling/admission/apis/runonceduration/v1/swagger_doc.go
  pkg/autoscaling/admission/runonceduration/admission_test.go
  pkg/build/apiserver/registry/buildconfig/webhook.go
  pkg/build/controller/build/build_controller_test.go
  pkg/build/controller/common/util_test.go
  pkg/build/controller/strategy/docker.go
  pkg/build/controller/strategy/sti.go
  pkg/build/generator/generator_test.go
  pkg/build/generator/test/mocks.go
  pkg/cmd/openshift-apiserver/openshiftapiserver/openshift_apiserver.go
  pkg/cmd/server/admin/create_kubeconfig.go
  pkg/cmd/server/apis/config/validation/master_test.go
  pkg/image/apis/image/validation/validation_test.go
  pkg/image/apis/image/validation/whitelist/whitelister_test.go
  pkg/image/apiserver/admission/imagepolicy/rules/accept.go
  pkg/image/apiserver/registry/imagestream/strategy.go
  pkg/image/apiserver/registry/imagestream/strategy_test.go
  pkg/oauthserver/authenticator/password/ldappassword/ldap.go
  pkg/oc/cli/admin/node/logs.go
  pkg/oc/cli/admin/prune/imageprune/prune_test.go
  pkg/oc/cli/admin/prune/imageprune/testutil/util.go
  pkg/oc/cli/importimage/importimage_test.go
  pkg/oc/cli/tag/tag_test.go
  pkg/oc/lib/groupsync/grouplister.go
  pkg/oc/lib/newapp/app/app_test.go
  pkg/oc/lib/newapp/app/pipeline.go
  pkg/route/apis/route/validation/validation_test.go
  pkg/route/apiserver/admission/apis/ingressadmission/v1/swagger_doc.go
  pkg/route/controller/ingress/ingress.go
  pkg/route/controller/ingress/ingress_test.go
  pkg/scheduler/admission/apis/podnodeconstraints/v1/swagger_doc.go
  pkg/scheduler/admission/nodeenv/admission_test.go
  pkg/serviceaccounts/controllers/create_dockercfg_secrets.go
  pkg/templateservicebroker/servicebroker/catalog_test.go
  test/extended/images/hardprune.go
  test/extended/util/test.go
  test/integration/oauth_serviceaccount_client_events_test.go
  test/integration/oauth_serviceaccount_client_test.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/naming/from_stack_test.go
Labels: approved, size/XL

#22505 cli: make oc rsync impl re-useable
  pkg/oc/cli/rsync/copy_default.go
  pkg/oc/cli/rsync/copy_multi.go
  pkg/oc/cli/rsync/copy_rsync.go
  pkg/oc/cli/rsync/copy_rsync_test.go
  pkg/oc/cli/rsync/copy_rsyncd.go
  pkg/oc/cli/rsync/copy_tar.go
  pkg/oc/cli/rsync/exec_local.go
  pkg/oc/cli/rsync/exec_remote.go
  pkg/oc/cli/rsync/forwarder.go
  pkg/oc/cli/rsync/pathspec.go
  pkg/oc/cli/rsync/rsync.go
Labels: approved, lgtm, sig/developer-experience, size/L

#22494 Cleanup origin polymorphichelpers from internal types
  pkg/oc/originpolymorphichelpers/attachablepodforobject.go
  pkg/oc/originpolymorphichelpers/canbeautoscaled.go
  pkg/oc/originpolymorphichelpers/canbeexposed.go
  pkg/oc/originpolymorphichelpers/historyviewer.go
  pkg/oc/originpolymorphichelpers/logsforobject.go
  pkg/oc/originpolymorphichelpers/mapbasedselectorforobject.go
  pkg/oc/originpolymorphichelpers/portsforobject.go
  pkg/oc/originpolymorphichelpers/protocolsforobject.go
  pkg/oc/originpolymorphichelpers/rollbacker.go
  pkg/oc/originpolymorphichelpers/statusviewer.go
Labels: approved, lgtm, size/L

#22506 Bug 1697206: Return a status error on GET user with invalid name
  pkg/user/apiserver/registry/user/etcd/etcd.go
Labels: approved, lgtm, size/XS

#22509 UPSTREAM: 73484: Sort apiservices properly during openapi aggregation
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/controllers/openapi/aggregator.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/controllers/openapi/aggregator_test.go
Labels: approved, lgtm, size/S

#22521 UPSTREAM: 74747: quota controller fixes
  vendor/k8s.io/kubernetes/pkg/controller/garbagecollector/garbagecollector_test.go
  vendor/k8s.io/kubernetes/pkg/controller/resourcequota/BUILD
  vendor/k8s.io/kubernetes/pkg/controller/resourcequota/resource_quota_controller.go
  vendor/k8s.io/kubernetes/pkg/controller/resourcequota/resource_quota_controller_test.go
  vendor/k8s.io/kubernetes/pkg/controller/resourcequota/resource_quota_monitor.go
  vendor/k8s.io/kubernetes/pkg/quota/v1/BUILD
  vendor/k8s.io/kubernetes/pkg/quota/v1/generic/BUILD
  vendor/k8s.io/kubernetes/pkg/quota/v1/generic/evaluator.go
  vendor/k8s.io/kubernetes/pkg/quota/v1/generic/evaluator_test.go
  vendor/k8s.io/kubernetes/pkg/quota/v1/resources.go
  vendor/k8s.io/kubernetes/pkg/quota/v1/resources_test.go
  vendor/k8s.io/kubernetes/plugin/pkg/admission/resourcequota/admission_test.go
  vendor/k8s.io/kubernetes/plugin/pkg/admission/resourcequota/controller.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/api/extensions/v1beta1/types.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/informers/extensions/v1beta1/BUILD
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/informers/extensions/v1beta1/interface.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/informers/extensions/v1beta1/networkpolicy.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/informers/generic.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/kubernetes/typed/extensions/v1beta1/BUILD
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/kubernetes/typed/extensions/v1beta1/extensions_client.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/kubernetes/typed/extensions/v1beta1/fake/BUILD
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/kubernetes/typed/extensions/v1beta1/fake/fake_extensions_client.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/kubernetes/typed/extensions/v1beta1/fake/fake_networkpolicy.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/kubernetes/typed/extensions/v1beta1/generated_expansion.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/kubernetes/typed/extensions/v1beta1/networkpolicy.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/listers/extensions/v1beta1/BUILD
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/listers/extensions/v1beta1/expansion_generated.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/listers/extensions/v1beta1/networkpolicy.go
Labels: approved, lgtm, size/XXL

#22425 Move ClusterResourceQuota to CRD
  hack/local-up-master/kube-apiserver-manifests/01_cluster_resource_quota_crd.yaml
  hack/local-up-master/lib.sh
  hack/test-cmd.sh
  pkg/admission/customresourcevalidation/attributes.go
  pkg/admission/customresourcevalidation/clusterresourcequota/validate_crq.go
  pkg/admission/customresourcevalidation/clusterresourcequota/validation/validation.go
  pkg/admission/customresourcevalidation/clusterresourcequota/validation/validation_test.go
  pkg/admission/customresourcevalidation/customresourcevalidationregistration/cr_validation_registration.go
  pkg/cmd/openshift-apiserver/openshiftapiserver/informers.go
  pkg/cmd/openshift-apiserver/openshiftapiserver/openshift_apiserver.go
  pkg/cmd/openshift-controller-manager/controller/interfaces.go
  pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/patch.go
  pkg/cmd/openshift-kube-apiserver/server.go
  pkg/quota/apiserver/admission/clusterresourcequota/admission.go
  pkg/quota/apiserver/apiserver.go
  pkg/quota/apiserver/registry/clusterresourcequota/etcd/etcd.go
  test/integration/clusterquota_test.go
  test/integration/clusterresourceoverride_admission_test.go
  test/integration/etcd_storage_path_test.go
  test/util/client.go
  test/util/server/server.go
  vendor/k8s.io/kubernetes/pkg/master/controller/crdregistration/crdregistration_controller.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/apiserver/apiserver.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/apiserver/patch_always_local_delegate.go
Labels: approved, lgtm, size/XL

#22504 hack: Handle multiple entries in OS_EXTRA_GOPATH for brew builds
  Makefile
  hack/lib/build/binaries.sh
Labels: approved, lgtm, size/S

#22512 test/extended: check if prometheus is firing a watchdog alert
  test/extended/prometheus/prometheus.go
Labels: approved, lgtm, size/S

#22514 UPSTREAM: <drop>: Revert: disable CRD validation until openapi fixes land
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/features/kube_features.go
Labels: approved, lgtm, priority/critical-urgent, queue/critical-fix, size/XS

#22546 hack: update cluster resource quota fixture used in tests
  hack/local-up-master/kube-apiserver-manifests/01_cluster_resource_quota_crd.yaml
Labels: approved, lgtm, size/S

#22545 UPSTREAM: <carry>: support SNI with IPs
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/certs/serving.go
Labels: approved, lgtm, size/S

#22527 UPSTREAM: <drop>: TestNewManagerImplStartProbeMode is flaky
  vendor/k8s.io/kubernetes/pkg/kubelet/cm/devicemanager/manager_test.go
Labels: approved, lgtm, size/XS

#22470 Re-enable scheduler serial tests
  test/extended/util/test.go
  vendor/k8s.io/kubernetes/test/e2e/scheduling/priorities.go
Labels: approved, lgtm, size/S

#22450 UPSTREAM: 76021: Fix create secret generic paths examples
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/create/create_secret.go
Labels: approved, lgtm, size/XS

#22508 Bug 1697644: test/extended: update test to use openshift-config pull-secret
  test/extended/operators/images.go
  test/extended/prometheus/prometheus.go
Labels: approved, lgtm, size/S

#22543 Make sure SIGTERM shutdown the controller manager and scheduler API server
  test/util/server/server.go
  vendor/k8s.io/kubernetes/cmd/cloud-controller-manager/app/controllermanager.go
  vendor/k8s.io/kubernetes/cmd/hyperkube/main.go
  vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go
  vendor/k8s.io/kubernetes/cmd/kube-scheduler/app/server.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/deprecated_insecure_serving.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/genericapiserver_test.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/secure_serving.go
Labels: approved, lgtm, size/L

#22550 UPSTREAM: 75985: Fix besteffort pods for conflicting tolerations
  vendor/k8s.io/kubernetes/plugin/pkg/admission/podtolerationrestriction/admission.go
  vendor/k8s.io/kubernetes/plugin/pkg/admission/podtolerationrestriction/admission_test.go
Labels: approved, lgtm, size/S

#22536 Add `--content` to `release info` to print the contents of the release
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/oc/cli/admin/release/info.go
  pkg/oc/cli/admin/release/info_test.go
  pkg/oc/cli/admin/release/mirror.go
  pkg/oc/cli/admin/release/release.go
Labels: approved, lgtm, size/L

#22531 UPSTREAM: 76455: Fix flakes in HPA tests
  vendor/k8s.io/kubernetes/pkg/controller/podautoscaler/horizontal_test.go
Labels: approved, lgtm, size/M

#22552 oc rsync: fix tar strategy
  pkg/oc/cli/rsync/rsync.go
Labels: approved, lgtm, size/XS

#22537 Always set standard security headers for OAuth server
  pkg/oauthserver/oauthserver/oauth_apiserver.go
  pkg/oauthserver/server/grant/grant.go
  pkg/oauthserver/server/headers/headers.go
  pkg/oauthserver/server/login/login.go
  pkg/oauthserver/server/logout/logout.go
  test/integration/oauth_server_headers_test.go
Labels: approved, lgtm, size/L

#22529 Bug 1686476: Force http1.1 in OAuth server
  pkg/cmd/openshift-integrated-oauth-server/server.go
  test/extended/include.go
  test/extended/oauth/http1.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/config.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/secure_serving.go
Labels: approved, lgtm, size/M

#22556 oc: make it clear what challenge handlers are enabled
  pkg/oc/lib/tokencmd/basicauth.go
  pkg/oc/lib/tokencmd/request_token.go
Labels: approved, lgtm, size/S

#22511 UPSTREAM: 75368: replace http.Error that override content type headers
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/filters/waitgroup.go
Labels: approved, lgtm, size/XS

#22486 test/e2e: re-enable kubelet hostAliases test
  test/extended/util/test.go
Labels: approved, lgtm, size/XS

#22563 UPSTREAM: 70002: Fix Azure disk attachment error on Linux
  vendor/k8s.io/kubernetes/pkg/volume/azure_dd/attacher.go
  vendor/k8s.io/kubernetes/pkg/volume/azure_dd/azure_common.go
  vendor/k8s.io/kubernetes/pkg/volume/azure_dd/azure_common_test.go
Labels: approved, lgtm, sig/storage, size/L

#22561 always print name of resources created by must-gather
  pkg/oc/cli/admin/admin.go
  pkg/oc/cli/admin/mustgather/mustgather.go
  test/cmd/admin.sh
Labels: approved, lgtm, size/L

#22430 add must-gather command
  pkg/oc/cli/admin/admin.go
  pkg/oc/cli/admin/mustgather/mustgather.go
  test/cmd/admin.sh
Labels: approved, lgtm, size/L

#22555 Use the image digest in openshift-install, write a release summary to the output, and allow simple signing
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/oc/cli/admin/release/extract.go
  pkg/oc/cli/admin/release/extract_tools.go
  pkg/oc/cli/admin/release/info.go
Labels: approved, lgtm, size/L

#22558 When a registry returns a blob or manifest, verify its contents by default
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/image/importer/image.go
  pkg/image/importer/importer.go
  pkg/image/importer/importer_test.go
  pkg/image/registryclient/client.go
  pkg/image/registryclient/client_test.go
  pkg/oc/cli/admin/release/extract.go
  pkg/oc/cli/admin/release/extract_tools.go
  pkg/oc/cli/admin/release/info.go
  pkg/oc/cli/admin/release/mirror.go
  pkg/oc/cli/admin/release/new.go
  pkg/oc/cli/image/append/append.go
  pkg/oc/cli/image/extract/extract.go
  pkg/oc/cli/image/info/info.go
  pkg/oc/cli/image/manifest/manifest.go
  pkg/oc/cli/image/mirror/mirror.go
  pkg/oc/cli/registry/login/login.go
Labels: approved, lgtm, size/XXL

#22557 Support Mulit-Arch Builds
  images/cli/Dockerfile.rhel
  images/hyperkube/Dockerfile.rhel
  images/hypershift/Dockerfile.rhel
  images/sdn/Dockerfile.rhel
  images/template-service-broker/Dockerfile.rhel
  images/tests/Dockerfile.rhel
Labels: approved, lgtm, size/M

#22574 test/extended/prometheus: temporarily disable scheduler metrics checks
  test/extended/prometheus/prometheus.go
Labels: approved, lgtm, size/XS

#22485 [release-3.11] Bug 1680059: Set reasonable DNSIP consistent with kubelet
  pkg/cmd/server/origin/node/node.go
  pkg/cmd/server/start/start_network.go
  pkg/cmd/util/ip.go
Labels: approved, lgtm, sig/network-edge, size/L

#22182 UPSTREAM: 74682: Fix flag template when both visible and explicit flags are specified
  vendor/k8s.io/kubernetes/pkg/kubectl/util/templates/templates.go
Labels: approved, lgtm, size/XS

#22518 Bug 1671528: clearly state new-app's non-support for CRDs, offer oc p…
  pkg/oc/cli/newapp/newapp.go
  test/cmd/newapp.sh
  test/testdata/newapp/template-with-crd.yaml
Labels: approved, lgtm, sig/developer-experience, size/S

#22577 Follow up feedback on signed output for tools extraction
  pkg/oc/cli/admin/release/extract_tools.go
Labels: approved, lgtm, size/XS

#22573 Fix case when operator fight with CRD registration on quota.openshift.io
  vendor/k8s.io/kubernetes/pkg/master/controller/crdregistration/crdregistration_controller.go
Labels: approved, lgtm, size/XS

#22502 Move the COPY scriptes to below the RUN INSTALL_PKGS for sdn image
  images/sdn/Dockerfile.rhel
  images/sdn/scripts/ip6tables
  images/sdn/scripts/ip6tables-restore
  images/sdn/scripts/ip6tables-save
  images/sdn/scripts/iptables
  images/sdn/scripts/iptables-restore
  images/sdn/scripts/iptables-save
Labels: approved, lgtm, size/S

#22540 Add check for node readiness when recovering workers
  test/extended/machines/workers.go
Labels: approved, lgtm, size/S

#22553 tools/etcdhelper: update default client port
  tools/etcdhelper/etcdhelper.go
Labels: approved, lgtm, size/XS

#22562 UPSTREAM: drop: Add extra logs for flake analysis
  vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws.go
Labels: approved, lgtm, size/S

#22569 Local registry config should only search home dir, not working dir
  pkg/image/registryclient/dockercredentials/credentials.go
Labels: approved, lgtm, size/M

#22591 UPSTREAM: 76455: More flake fixes in HPA legacy tests
  vendor/k8s.io/kubernetes/pkg/controller/podautoscaler/legacy_horizontal_test.go
Labels: approved, lgtm, size/S

#22575 test/extended/prometheus: Add test for host cAdvisor metrics
  test/extended/prometheus/prometheus.go
Labels: approved, lgtm, size/S

#22592 images/tests: Globally-writeable /etc/passwd
  images/tests/Dockerfile.rhel
Labels: approved, lgtm, size/XS

#22530 build controller should ignore builds that are being deleted
  pkg/build/controller/build/build_controller.go
Labels: approved, lgtm, size/XS

#22595 Disable openssl linking in Origin binaries
  hack/lib/constants.sh
Labels: approved, lgtm, size/XS

#22584 UPSTREAM: 76663: Fix preemption race conditions on heavy utilized nodes in e2e tests
  vendor/k8s.io/kubernetes/test/e2e/scheduling/preemption.go
Labels: approved, lgtm, size/M

#22456 Bug 1694859: verify image source symlinks
  test/extended/builds/image_source.go
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/test-imagesource-buildconfig.yaml
Labels: approved, lgtm, size/M

#22542 Dont rely on machine labels for listing worker nodes
  test/extended/machines/workers.go
Labels: approved, lgtm, size/M

#22559 Fix symlink arrays for Bash 3
  hack/lib/build/binaries.sh
  hack/lib/constants.sh
Labels: approved, lgtm, size/S

#22585 BUG 1685322: fix init container check and prevent running to pending …
  pkg/build/controller/build/build_controller.go
Labels: approved, lgtm, sig/developer-experience, size/M

#22590 UPSTREAM: 76707: Warn to stderr when we encounter PathError listing plugins
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/plugin/BUILD
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/plugin/plugin.go
Labels: approved, lgtm, size/XS

#22465 Run e2e tests with "custom" distro
  test/extended/util/test.go
Labels: approved, lgtm, sig/storage, size/XS

#22605 UPSTREAM: <carry>: squash to dynamic certs, don't load zero length certs
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/certs/clientca.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/certs/single_certkey_pair.go
Labels: approved, lgtm, size/XS

#22611 UPSTREAM: 75985: Add feature gates for resource quota
  vendor/k8s.io/kubernetes/test/e2e/framework/util.go
  vendor/k8s.io/kubernetes/test/e2e/scheduling/resource_quota.go
Labels: approved, lgtm, size/S

#22593 SA authenticator performance pick
  pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/patch.go
  pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/patch_authenticator.go
  vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go
  vendor/k8s.io/kubernetes/pkg/controller/serviceaccount/tokengetter.go
  vendor/k8s.io/kubernetes/pkg/serviceaccount/BUILD
  vendor/k8s.io/kubernetes/pkg/serviceaccount/jwt_test.go
  vendor/k8s.io/kubernetes/test/integration/auth/BUILD
  vendor/k8s.io/kubernetes/test/integration/auth/svcaccttoken_test.go
  vendor/k8s.io/kubernetes/test/integration/serviceaccount/service_account_test.go
Labels: approved, lgtm, size/L

#22481 Switch ClusterLoader to use `oc adm` to create projects
  test/extended/cluster/cl.go
  test/extended/cluster/context.go
Labels: approved, lgtm, size/M

#22198 Bug 1656328 - Fix smartLabelFor to properly handle annotations and labels containing .io
  vendor/k8s.io/kubernetes/pkg/kubectl/describe/versioned/describe.go
  vendor/k8s.io/kubernetes/pkg/kubectl/describe/versioned/describe_test.go
  vendor/k8s.io/kubernetes/pkg/kubectl/util/templates/markdown.go
  vendor/k8s.io/kubernetes/pkg/kubectl/util/templates/normalizers.go
Labels: approved, lgtm, size/M

#22594 add e2e test for oc adm must-gather
  test/extended/cli/mustgather.go
Labels: approved, lgtm, size/M

#22613 When watch event returns a "too old" error, we must exit
  pkg/monitor/event.go
Labels: approved, lgtm, size/XS

#22596 Allow release image to be verified and report simple output
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/oc/cli/admin/release/info.go
  pkg/oc/cli/admin/release/new.go
Labels: approved, lgtm, size/M

#22603 Add a disruptive suite to openshift-tests
  cmd/openshift-tests/e2e.go
  cmd/openshift-tests/openshift-tests.go
  vendor/k8s.io/kubernetes/test/e2e/instrumentation/logging/generic_soak.go
Labels: approved, lgtm, size/M

#22597 Use the image retriever and reuse cached command contexts
  pkg/oc/cli/admin/release/info.go
  pkg/oc/cli/image/info/info.go
  pkg/oc/cli/image/manifest/manifest.go
Labels: approved, lgtm, size/L

#22607 Add OWNERS for DevEx build CLI
  pkg/oc/cli/cancelbuild/OWNERS
  pkg/oc/cli/newapp/OWNERS
  pkg/oc/cli/newbuild/OWNERS
  pkg/oc/cli/startbuild/OWNERS
Labels: approved, lgtm, sig/developer-experience, size/S

#22623 BUG 1685322: fix init container check and prevent running to pending …
  pkg/build/controller/build/build_controller.go
Labels: approved, lgtm, size/M

#22606 UPSTREAM: <carry>: filter out RBR and SCC paths from OpenAPI
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/routes/openapi.go
Labels: approved, lgtm, size/XS

#22630 UPSTREAM: 75367: Fix panic when removing docker images
  vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/docker_image.go
Labels: approved, lgtm, size/XS

#22629 [3.11] UPSTREAM: 75367: Fix panic when removing docker images
  vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/docker_image.go
Labels: approved, lgtm, size/XS

#22298 Add Authentication CR validation
  pkg/admission/customresourcevalidation/authentication/validate_authentication.go
  pkg/admission/customresourcevalidation/authentication/validate_authentication_test.go
  pkg/admission/customresourcevalidation/helpers.go
Labels: approved, lgtm, size/L

#22622 implement code review suggestions
  test/extended/cli/mustgather.go
Labels: approved, lgtm, size/S

#22624 [3.11] Update DevEx OWNERS
  examples/OWNERS
  examples/db-templates/OWNERS
  examples/hello-openshift/OWNERS
  examples/image-streams/OWNERS
  examples/jenkins/OWNERS
  examples/quickstarts/OWNERS
  examples/sample-app/OWNERS
  images/builder/OWNERS
  pkg/build/OWNERS
  pkg/image/OWNERS
  pkg/oc/cli/admin/prune/imageprune/OWNERS
  pkg/oc/clusteradd/components/default-imagestreams/OWNERS
  pkg/oc/clusteradd/components/registry/OWNERS
  pkg/oc/clusteradd/components/sample-templates/OWNERS
  pkg/oc/lib/newapp/OWNERS
  pkg/template/OWNERS
  test/templates/OWNERS
  tools/buildanalyzer/OWNERS
Labels: approved, lgtm, size/M

#22626 UPSTREAM: 76625: Skip tests that depend on default SC
  vendor/k8s.io/kubernetes/test/e2e/apps/statefulset.go
  vendor/k8s.io/kubernetes/test/e2e/framework/BUILD
  vendor/k8s.io/kubernetes/test/e2e/framework/pv_util.go
  vendor/k8s.io/kubernetes/test/e2e/storage/pvc_protection.go
  vendor/k8s.io/kubernetes/test/e2e/storage/volume_metrics.go
  vendor/k8s.io/kubernetes/test/e2e/storage/volume_provisioning.go
Labels: approved, lgtm, size/M

#22625 BUG 1685322: fix init container check and prevent running to pending …
  pkg/build/controller/build/build_controller.go
Labels: approved, lgtm, size/M

#22581 Add test/extended to cover bz1694871
  test/extended/builds/start.go
Labels: approved, lgtm, size/XS

#22586 Bug 1700068: test/extended: Use internal service if no router LB
  test/extended/router/headers.go
  test/extended/router/metrics.go
  test/extended/router/reencrypt.go
  test/extended/router/router.go
  test/extended/util/cli.go
Labels: approved, lgtm, sig/network-edge, size/M

#22604 BUG 1671528: QE induced tweaks to recent new-app CRD error message
  pkg/oc/cli/newapp/newapp.go
Labels: approved, lgtm, size/XS

#22628 oc adm must-gather: use gather script
  pkg/oc/cli/admin/mustgather/mustgather.go
Labels: approved, lgtm, size/XS

#22433 UPSTREAM: 75062: Allow to read OpenStack config from the secret
  vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/openstack/BUILD
  vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/openstack/openstack.go
Labels: approved, lgtm, size/L

#22635 test/extended/prometheus: reenable control plane tests
  test/extended/prometheus/prometheus.go
Labels: approved, lgtm, size/S

#22649 cmd: remove integrated etcd server
  cmd/hypershift/main.go
  pkg/cmd/openshift-etcd/start_etcd.go
Labels: approved, lgtm, size/L

#22651 kube-apiserver: exit with zero code on term signal
  pkg/cmd/openshift-kube-apiserver/cmd.go
  pkg/cmd/openshift-kube-apiserver/server.go
Labels: approved, lgtm, size/XS

#22568 pkg/oc/cli/admin/release/extract_tools: Fix false "did not contain" when not hashing
  pkg/oc/cli/admin/release/extract_tools.go
Labels: approved, lgtm, size/S

#22638 UPSTREAM: <carry>: Return journal logs from previous boot if possible
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_server_journal.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_server_journal_test.go
Labels: approved, lgtm, size/M

#22652 Re-fix pod reattachment on SDN restart
  pkg/network/node/node.go
Labels: approved, lgtm, size/XS

#22618 Disable resource quota
  test/extended/util/test.go
Labels: approved, lgtm, size/XS

#22496 Add soltysh to pkg/printer owners
  pkg/printers/OWNERS
Labels: approved, lgtm, size/XS

#22645 Upgrading with --force should set the force boolean
  pkg/oc/cli/admin/upgrade/upgrade.go
  test/e2e/upgrade/upgrade.go
Labels: approved, lgtm, size/XS

#22662 If only one test is being run in a suite, always include success output
  pkg/test/ginkgo/cmd_runsuite.go
Labels: approved, lgtm, size/XS

#22580 UPSTREAM: 76719: vsphere: correctly handle PV size
  vendor/k8s.io/kubernetes/pkg/volume/vsphere_volume/vsphere_volume_util.go
  vendor/k8s.io/kubernetes/test/e2e/storage/vsphere/vsphere_volume_disksize.go
Labels: approved, lgtm, sig/storage, size/M

#22650 Set gitTreeState, golang version, compiler and platform variables in version command
  hack/lib/constants.sh
  pkg/version/version.go
Labels: approved, lgtm, size/S

#22627 fix problem running custom must-gather command
  pkg/oc/cli/admin/mustgather/mustgather.go
  test/extended/cli/mustgather.go
Labels: approved, lgtm, size/M

#22667 Increase upgrade test timeout for now
  cmd/openshift-tests/upgrade.go
Labels: approved, size/XS

#22670 Wait slightly longer to observe version
  test/e2e/upgrade/upgrade.go
Labels: approved, lgtm, size/XS

#22634 Bugfix: oc describe scc <name> printing error
  pkg/oc/lib/describe/describer.go
Labels: approved, lgtm, ok-to-test, size/XS

#22442 UPSTREAM: 75772: Avoid panic in cronjob sorting
  vendor/k8s.io/kubernetes/pkg/controller/cronjob/utils.go
  vendor/k8s.io/kubernetes/pkg/controller/cronjob/utils_test.go
Labels: approved, lgtm, size/M

#22659 Bug 1701422: registry auth without port number
  pkg/serviceaccounts/controllers/docker_registry_service.go
  pkg/serviceaccounts/controllers/docker_registry_service_test.go
Labels: approved, lgtm, size/M

#22663 Fix two issues with s3 mirroring and extend to release images
  pkg/oc/cli/admin/release/mirror.go
  pkg/oc/cli/image/mirror/mappings.go
  pkg/oc/cli/image/mirror/mirror.go
  pkg/oc/cli/image/mirror/s3.go
Labels: approved, lgtm, size/L

#22676 Disable tests while flake is investigated
  test/extended/builds/new_app.go
Labels: approved, lgtm, size/XS

#22487 [release-3.10] Bug 1696394: Set reasonable DNSIP consistent with kubelet
  pkg/cmd/server/origin/node/node.go
  pkg/cmd/server/start/bootstrap_node.go
  pkg/cmd/util/ip.go
Labels: approved, lgtm, sig/network-edge, size/L

#22657 move to a supported (non depricated) tools container
  pkg/oc/cli/debug/debug.go
Labels: approved, lgtm, size/XS

#22678 When pod restarts with exitCode 1, monitor should print term message
  pkg/monitor/operator.go
  pkg/monitor/pod.go
Labels: approved, lgtm, size/M

#22672 Passing `--to-signature` to release new creates the signature file
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/oc/cli/admin/release/new.go
  pkg/oc/cli/admin/release/signature.go
Labels: approved, lgtm, size/M

#22641 Accept buildah 1.7.3+ unused build arg error
  test/extended/builds/start.go
Labels: approved, lgtm, size/XS

#22688 Correct Dockerfile FROM statements
  images/cli-artifacts/Dockerfile.rhel
  images/cli/Dockerfile.rhel
  images/hyperkube/Dockerfile.rhel
  images/hypershift/Dockerfile.rhel
  images/sdn/Dockerfile.rhel
  images/template-service-broker/Dockerfile.rhel
  images/tests/Dockerfile.rhel
Labels: approved, lgtm, size/S

#22679 Bug 1694878: Always honor OAuth tokens
  pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/patch_authenticator.go
Labels: approved, lgtm, size/M

#22653 UPSTREAM: 77010: Check error when copying from pod
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cp/cp.go
Labels: approved, lgtm, size/XS

#22369 Enable local storage e2e
  test/extended/util/test.go
Labels: approved, lgtm, sig/storage, size/XS

#22690 Move default components to an appropriate upgrade order (generic)
  pkg/oc/cli/admin/release/new.go
Labels: approved, lgtm, size/XS

#22682 test that must-gather generated audit logs
  test/extended/cli/mustgather.go
Labels: approved, lgtm, size/XS

#22684 Continue improving SDN startup logging
  pkg/network/node/node.go
  pkg/network/node/runtime.go
Labels: approved, lgtm, size/S

#22691 Collapse version changes in monitor output
  pkg/monitor/operator.go
  pkg/monitor/operator_test.go
Labels: approved, lgtm

#22692 Report the pod exit reason in the event monitor
  pkg/monitor/pod.go
Labels: approved, lgtm, size/XS

#22664 test/extenden/prometheus: add monitoring team as owners
  test/extended/prometheus/OWNERS
Labels: lgtm, size/S

#22693 When no argument passed to oc adm release new, dry run the output
  pkg/oc/cli/admin/release/image_mapper.go
  pkg/oc/cli/admin/release/new.go
  pkg/oc/cli/image/append/append.go
Labels: approved, lgtm, size/L

#22695 extended: print empty files when must-gather test fail
  test/extended/cli/mustgather.go
Labels: approved, lgtm, size/S
