Repository openshift/origin, pull requests merged in 2019-11, with the labels that each got.

#24058 Bug 1756421: bring back explain tests
  test/extended/cli/explain.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#24036 Upstream 84466: gce: ensureInternalInstanceGroups: reuse instance-groups for internal load balancers
  vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/gce/gce.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/gce/gce_fake.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/gce/gce_instancegroup.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/gce/gce_loadbalancer_internal.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/gce/gce_loadbalancer_internal_test.go
Labels: approved, lgtm, size/L

#23966 Bug 1761809: Informers can miss notifications
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/cache/delta_fifo.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/cache/delta_fifo_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#24048 Update build e2e check for internal registry host
  test/extended/util/framework.go
Labels: approved, lgtm, size/XS

#24059 test: Catch panics in the disruption suite
  test/extended/util/disruption/disruption.go
Labels: approved, lgtm, size/XS

#24073 [MON-832] test/extended/prometheus: check if any rule evaluation is failing
  test/extended/prometheus/prometheus.go
Labels: approved, lgtm, size/S

#24075 Bug 1683057: Fix router metrics test flakes
  test/extended/router/metrics.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#23955 Bug 1759181: UPSTREAM: <carry>:Add a RBAC checker for external IP ranger
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/admission/network/externalipranger/externalip_admission.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/admission/network/externalipranger/externalip_admission_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#24067 test: must-gather pods may tolerate all taints
  test/extended/operators/qos.go
  test/extended/operators/tolerations.go
Labels: approved, lgtm, size/XS

#23942 Bug 1718487: fix CVE-2019-11244: kubectl --http-cache=<world-accessible dir>
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/discovery/cached_discovery.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/discovery/cached_discovery_test.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/discovery/round_tripper.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/discovery/round_tripper_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#23910 Bug 1766365: TestNamespaceCondition integration test fails
  vendor/k8s.io/kubernetes/test/integration/etcd/data.go
  vendor/k8s.io/kubernetes/test/integration/namespace/ns_conditions_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#23999 Bug 1751640: Enable block bad-case tests
  test/extended/util/test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#24084 test: Disable TestDockercfgTokenDeletedController until fixed
  test/extended/controller_manager/pull_secret.go
Labels: approved, lgtm, size/XS

#23994 Bug 1761925: CL fix fixture path & update config path, quickstarts & bindata
  test/extended/cluster/cl.go
  test/extended/testdata/bindata.go
  test/extended/testdata/cluster/master-vert.yaml
  test/extended/testdata/cluster/quickstarts/cakephp-mysql.json
  test/extended/testdata/cluster/quickstarts/dancer-mysql.json
  test/extended/testdata/cluster/quickstarts/django-postgresql.json
  test/extended/testdata/cluster/quickstarts/nodejs-mongodb.json
  test/extended/testdata/cluster/quickstarts/rails-postgresql.json
Labels: approved, bugzilla/valid-bug, lgtm, size/XXL

#24085 e2e: fix router metrics test flake on AWS
  test/extended/router/metrics.go
  test/extended/router/scoped.go
  test/extended/router/weighted.go
Labels: approved, lgtm, size/S

#24070 Add Ben as top-level OWNER
  OWNERS
Labels: approved, lgtm, size/XS

#24081 bug 1713134: UPSTREAM: 84513: test/e2e: AddOrUpdateAvoidPodOnNode/RemoveAvoidPodsOffNode: retry when conflict hit during annotation update
  vendor/k8s.io/kubernetes/test/e2e/framework/util.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#23954 Bug 1751124: UPSTREAM: 83727: Optionally run e2e pod as privileged for SELinux
  vendor/k8s.io/kubernetes/test/e2e/framework/volume/fixtures.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#24092 test: Skip pending must-gather pods in the crashloop test
  test/extended/operators/cluster.go
Labels: approved, lgtm, size/XS

#24095 Remove command execution from the extended image
  test/extended/images/extract.go
Labels: approved, lgtm, size/XS

#23664 Bug 1711535: Convert tbe e2e to integration test
  vendor/k8s.io/kubernetes/test/e2e/scheduling/BUILD
  vendor/k8s.io/kubernetes/test/e2e/scheduling/taint_based_evictions.go
  vendor/k8s.io/kubernetes/test/integration/scheduler/taint_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#24094 Switch to docker.io/busybox
  test/extended/testdata/bindata.go
  test/extended/testdata/jobs/v1.yaml
Labels: approved, lgtm, size/XS

#24057 Bug 1765756: UPSTREAM: 80004: Prefer to delete doubled-up pods of a ReplicaSet
  vendor/k8s.io/kubernetes/pkg/controller/controller_utils.go
  vendor/k8s.io/kubernetes/pkg/controller/controller_utils_test.go
  vendor/k8s.io/kubernetes/pkg/controller/replicaset/BUILD
  vendor/k8s.io/kubernetes/pkg/controller/replicaset/replica_set.go
  vendor/k8s.io/kubernetes/pkg/controller/replicaset/replica_set_test.go
  vendor/k8s.io/kubernetes/test/e2e/apps/deployment.go
  vendor/k8s.io/kubernetes/test/e2e/apps/types.go
  vendor/k8s.io/kubernetes/test/e2e/framework/service/jig.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XL

#23901 Bug 1757807: e2e: stabilize ingress metrics tests
  test/extended/prometheus/prometheus.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#24100 React to openshift/ruby-hello-world update
  test/extended/builds/pipeline_origin_bld.go
  test/extended/builds/start.go
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/test-build-proxy.yaml
  test/extended/testdata/cmd/test/cmd/admin.sh
  test/extended/testdata/cmd/test/cmd/builds.sh
  test/extended/testdata/cmd/test/cmd/newapp.sh
  test/extended/testdata/cmd/test/cmd/templates.sh
  test/extended/testdata/cmd/test/cmd/testdata/app-scenarios/new-project-deployed-app.yaml
  test/extended/testdata/cmd/test/cmd/testdata/app-scenarios/new-project-no-build.yaml
  test/extended/testdata/cmd/test/cmd/testdata/app-scenarios/new-project-one-build.yaml
  test/extended/testdata/cmd/test/cmd/testdata/app-scenarios/new-project-two-deployment-configs.yaml
  test/extended/testdata/cmd/test/cmd/testdata/application-template-dockerbuild.json
  test/extended/testdata/cmd/test/cmd/testdata/application-template-stibuild.json
  test/extended/testdata/cmd/test/cmd/testdata/new-app/build-arg-dockerfile/Dockerfile
  test/extended/testdata/cmd/test/cmd/testdata/new-app/template-with-app-label.json
  test/extended/testdata/cmd/test/cmd/testdata/new-app/template-without-app-label.json
  test/extended/testdata/cmd/test/cmd/testdata/statefulset.yaml
  test/extended/testdata/cmd/test/cmd/testdata/test-bc.yaml
  test/extended/testdata/cmd/test/cmd/testdata/test-buildcli.json
  test/extended/testdata/cmd/test/cmd/triggers.sh
Labels: approved, lgtm, size/L

#24088 UPSTREAM: 84123: Handle namespace shutdown gracefully
  vendor/k8s.io/kubernetes/pkg/controller/controller_utils.go
  vendor/k8s.io/kubernetes/pkg/controller/cronjob/BUILD
  vendor/k8s.io/kubernetes/pkg/controller/cronjob/cronjob_controller.go
  vendor/k8s.io/kubernetes/pkg/controller/daemon/daemon_controller.go
  vendor/k8s.io/kubernetes/pkg/controller/deployment/deployment_controller.go
  vendor/k8s.io/kubernetes/pkg/controller/deployment/sync.go
  vendor/k8s.io/kubernetes/pkg/controller/endpoint/endpoints_controller.go
  vendor/k8s.io/kubernetes/pkg/controller/endpointslice/reconciler.go
  vendor/k8s.io/kubernetes/pkg/controller/job/job_controller.go
  vendor/k8s.io/kubernetes/pkg/controller/replicaset/replica_set.go
  vendor/k8s.io/kubernetes/pkg/controller/serviceaccount/serviceaccounts_controller.go
  vendor/k8s.io/kubernetes/pkg/controller/serviceaccount/tokens_controller.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/api/core/v1/types.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/api/errors/errors.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/admission/plugin/namespace/lifecycle/BUILD
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/admission/plugin/namespace/lifecycle/admission.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/admission/plugin/namespace/lifecycle/admission_test.go
Labels: approved, lgtm, size/L

#24072 apiserver crd validation: remove tls1.3 and modern profile
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/admission/customresourcevalidation/apiserver/validate_apiserver.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/admission/customresourcevalidation/apiserver/validate_apiserver_test.go
Labels: approved, lgtm, sig/network-edge, size/M

#24082 Bug 1763988: LDAP e2e: add dnf install retries, extend run timeout
  test/extended/oauth/groupsync.go
  test/extended/util/framework.go
  test/extended/util/ldap.go
  test/extended/util/oauthserver/oauthserver.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#24053 e2e requestheader: make client follow TLS correctly
  test/extended/oauth/requestheaders.go
Labels: approved, lgtm, size/XS

#23947 Check ocm rollout between build tests
  test/extended/builds/cluster_config.go
Labels: approved, lgtm, size/M

#24063 [release-4.2] Bug 1765179: e2e: fix flaky route wait functions
  test/extended/router/config_manager.go
  test/extended/router/headers.go
  test/extended/router/scoped.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#24123 Add "get configmaps from openshift namespace" rule to expected rules
  test/extended/authorization/rbac/groups_default_rules.go
Labels: approved, lgtm, size/XS

#24093 Bug 1752646: e2e: Re-enable HAProxy router header test
  test/extended/router/headers.go
  test/extended/util/test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#24115 Fix cmd tests to be more resilient to changes
  test/extended/testdata/cmd/test/cmd/help.sh
Labels: approved, lgtm, size/XS

#23370 Bug 1711538: Reenable 'should be rejected when no endpoints exist' test
  test/extended/util/test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#24129 Bug 1768262: Bump nodes ready timeout
  vendor/k8s.io/kubernetes/test/e2e/framework/framework.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#24096 Bug 1767163: Verify new-app works with imagestream
  test/extended/builds/new_app.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#24101 Remove non-existing fields
  examples/hello-openshift/hello-pod.json
  examples/jenkins/jenkins-ephemeral-template.json
  test/extended/builds/valuefrom.go
  test/extended/testdata/bindata.go
  test/extended/testdata/cmd/test/cmd/testdata/hello-openshift/hello-pod.json
  test/extended/testdata/cmd/test/cmd/testdata/jenkins/jenkins-ephemeral-template.json
  test/extended/testdata/cmd/test/cmd/testdata/templates/guestbook.json
  test/extended/testdata/cmd/test/cmd/testdata/test-image.json
  test/extended/testdata/image/test-image.json
  test/extended/testdata/oauthserver/oauth-network.yaml
  test/extended/testdata/templates/guestbook.json
  test/integration/testdata/test-image.json
Labels: approved, lgtm, size/M

#24108 Fix deprecated versions in cmd test
  test/extended/testdata/cmd/test/cmd/testdata/statefulset.yaml
Labels: approved, lgtm, size/XS

#24128 Bug 1761689: Fix RS expectations for recreate case
  vendor/k8s.io/kubernetes/pkg/controller/replicaset/init_test.go
  vendor/k8s.io/kubernetes/pkg/controller/replicaset/replica_set.go
  vendor/k8s.io/kubernetes/pkg/controller/replicaset/replica_set_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#23560 Install CSI driver on openshift-test start.
  cmd/openshift-tests/csi.go
  cmd/openshift-tests/openshift-tests.go
  test/extended/csi/install.go
  test/extended/testdata/bindata.go
  test/extended/testdata/csi/README.md
  test/extended/testdata/csi/aws-ebs/install-template.yaml
  test/extended/testdata/csi/aws-ebs/manifest.yaml
Labels: approved, lgtm, size/XL

#24069 Bug 1758543: Fix volume reconstruction
  vendor/k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler/reconciler.go
  vendor/k8s.io/kubernetes/pkg/volume/awsebs/aws_ebs.go
  vendor/k8s.io/kubernetes/pkg/volume/awsebs/aws_ebs_block.go
  vendor/k8s.io/kubernetes/pkg/volume/awsebs/aws_ebs_block_test.go
  vendor/k8s.io/kubernetes/pkg/volume/awsebs/aws_ebs_test.go
  vendor/k8s.io/kubernetes/pkg/volume/awsebs/aws_util.go
  vendor/k8s.io/kubernetes/pkg/volume/cinder/cinder_block.go
  vendor/k8s.io/kubernetes/pkg/volume/cinder/cinder_block_test.go
  vendor/k8s.io/kubernetes/pkg/volume/gcepd/gce_pd_block.go
  vendor/k8s.io/kubernetes/pkg/volume/gcepd/gce_pd_block_test.go
  vendor/k8s.io/kubernetes/pkg/volume/local/local.go
  vendor/k8s.io/kubernetes/pkg/volume/local/local_test.go
  vendor/k8s.io/kubernetes/pkg/volume/vsphere_volume/vsphere_volume_block.go
  vendor/k8s.io/kubernetes/pkg/volume/vsphere_volume/vsphere_volume_block_test.go
  vendor/k8s.io/kubernetes/test/e2e/storage/testsuites/disruptive.go
  vendor/k8s.io/kubernetes/test/e2e/storage/testsuites/subpath.go
  vendor/k8s.io/kubernetes/test/e2e/storage/utils/BUILD
  vendor/k8s.io/kubernetes/test/e2e/storage/utils/utils.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XL

#24103 Bug 1765294: Changing from passive to active approach on secret deletion.
  test/extended/controller_manager/pull_secret.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#24121 Cleanup created image
  test/extended/images/imagestream.go
Labels: approved, lgtm, size/XS

#24104 Bug 1768002: Stabilize router stress test
  test/extended/router/stress.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#24105 Bug 1763807: UPSTREAM: <carry>: Expose a simple journald shim on the kubelet logs endpoint
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_server_journal.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#24131 Bug 1762162: e2e: fix incorrect router image references
  test/extended/router/config_manager.go
  test/extended/router/scoped.go
  test/extended/router/stress.go
  test/extended/router/unprivileged.go
  test/extended/router/weighted.go
  test/extended/testdata/bindata.go
  test/extended/testdata/router/router-config-manager.yaml
  test/extended/testdata/router/router-override-domains.yaml
  test/extended/testdata/router/router-override.yaml
  test/extended/testdata/router/router-scoped.yaml
  test/extended/testdata/router/weighted-router.yaml
  test/extended/util/framework.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#24133 Bug 1769016: Verify ocm's CRD schema
  test/extended/cli/explain.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#24147 test/extended: skip "Services should be rejected when no endpoints exist" for OVNKubernetes
  test/extended/util/test.go
Labels: approved, lgtm, size/XS

#24145 e2e: run router header test on AWS/GCP/Azure only
  test/extended/router/headers.go
Labels: approved, lgtm, size/S

#24135 Bug 1767295: UPSTREAM: 84466: gce: skip ensureInstanceGroup for a zone that has no remaining nodes for k8s managed IG
  vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/gce/gce_loadbalancer_internal.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/gce/gce_loadbalancer_internal_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#24146 test: Upgrade rollback abort at 100 should work
  test/e2e/upgrade/monitor.go
Labels: approved, lgtm, size/XS

#24163 README: Update readme for OKD4
  CONTRIBUTING.adoc
  HACKING.md
  README.md
  UPGRADE.md
  Vagrantfile
Labels: approved, lgtm, size/XL

#23908 Bug 1758158: aws: sort addresses of multiple interfaces correctly [4.2]
  vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws.go
  vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws_fakes.go
  vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#24148 Bug 1771335: Verify pullsecret builds
  test/extended/builds/pullsecret.go
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/pullsecret/linked-nodejs-bc.yaml
  test/extended/testdata/builds/pullsecret/pullsecret-nodejs-bc.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#24167 Fix cmd tests to be more resilient to changes
  test/extended/testdata/cmd/test/cmd/help.sh
Labels: approved, lgtm, size/XS

#24166 bump ghodss/yaml and library-go
  glide.lock
  glide.yaml
  vendor/github.com/apparentlymart/go-cidr/cidr/cidr.go
  vendor/github.com/apparentlymart/go-cidr/cidr/cidr_test.go
  vendor/github.com/apparentlymart/go-cidr/cidr/wrangling.go
  vendor/github.com/docker/libtrust/README.md
  vendor/github.com/docker/libtrust/util.go
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/github.com/ghodss/yaml/yaml_go110.go
  vendor/github.com/ghodss/yaml/yaml_go110_test.go
  vendor/github.com/ghodss/yaml/yaml_test.go
  vendor/github.com/openshift/api/samples/v1/0000_10_samplesconfig.crd.yaml
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer_polling.go
  vendor/github.com/openshift/library-go/pkg/image/reference/reference.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiextensions.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apps.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core_test.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/json_patch_helpers.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/json_patch_helpers_test.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/monitoring.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/rbac.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go
  vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
  vendor/go.mongodb.org/mongo-driver/.evergreen/config.yml
  vendor/go.mongodb.org/mongo-driver/mongo/client_encryption.go
  vendor/go.mongodb.org/mongo-driver/mongo/client_test.go
  vendor/go.mongodb.org/mongo-driver/mongo/doc.go
  vendor/go.mongodb.org/mongo-driver/mongo/options/autoencryptionoptions.go
  vendor/go.mongodb.org/mongo-driver/mongo/options/clientoptions.go
  vendor/go.mongodb.org/mongo-driver/x/mongo/driver/connstring/connstring.go
  vendor/go.mongodb.org/mongo-driver/x/mongo/driver/connstring/connstring_test.go
  vendor/go.mongodb.org/mongo-driver/x/mongo/driver/examples/server_monitoring/main.go
  vendor/go.mongodb.org/mongo-driver/x/mongo/driver/topology/connection_options.go
  vendor/go.mongodb.org/mongo-driver/x/mongo/driver/topology/server_options.go
  vendor/go.mongodb.org/mongo-driver/x/mongo/driver/topology/server_test.go
  vendor/go.mongodb.org/mongo-driver/x/mongo/driver/topology/topology.go
  vendor/go.mongodb.org/mongo-driver/x/mongo/driver/topology/topology_options.go
  vendor/go.mongodb.org/mongo-driver/x/mongo/driver/topology/topology_options_test.go
  vendor/go.mongodb.org/mongo-driver/x/mongo/driver/topology/topology_test.go
  vendor/k8s.io/csi-api/go.mod
  vendor/k8s.io/csi-api/go.sum
Labels: approved, lgtm, size/XL

#24138 Stop excluding ClusterMachineApproverDown from firing check
  test/extended/prometheus/prometheus.go
Labels: approved, lgtm

#24176 Bug 1769951: [4.1.z] Fix origin tests
  pkg/oauth/apis/oauth/validation/validation_test.go
  pkg/oc/cli/admin/buildchain/test/multiple-namespaces-bcs.yaml
  pkg/oc/cli/admin/buildchain/test/multiple-trigger-bcs.yaml
  pkg/oc/cli/admin/buildchain/test/single-namespace-bcs.yaml
  pkg/oc/cli/kubectlwrappers/wrappers.go
  pkg/oc/lib/describe/chaindescriber_test.go
  pkg/oc/lib/describe/projectstatus_test.go
  pkg/oc/lib/graph/genericgraph/test/bare-bc.yaml
  pkg/oc/lib/graph/genericgraph/test/bare-dc.yaml
  pkg/oc/lib/graph/genericgraph/test/circular-not.yaml
  pkg/oc/lib/graph/genericgraph/test/circular.yaml
  pkg/oc/lib/graph/genericgraph/test/deployment.yaml
  pkg/oc/lib/graph/genericgraph/test/failed-build.yaml
  pkg/oc/lib/graph/genericgraph/test/missing-istag.yaml
  pkg/oc/lib/graph/genericgraph/test/new-app.yaml
  pkg/oc/lib/graph/genericgraph/test/new-project-deployed-app.yaml
  pkg/oc/lib/graph/genericgraph/test/new-project-no-build.yaml
  pkg/oc/lib/graph/genericgraph/test/new-project-one-build.yaml
  pkg/oc/lib/graph/genericgraph/test/new-project-two-deployment-configs.yaml
  pkg/oc/lib/graph/genericgraph/test/prereq-image-not-present.yaml
  pkg/oc/lib/graph/genericgraph/test/prereq-image-present-notag.yaml
  pkg/oc/lib/graph/genericgraph/test/prereq-image-present.yaml
  pkg/oc/lib/graph/genericgraph/test/pushable-build.yaml
  pkg/oc/lib/graph/genericgraph/test/unpushable-build-2.yaml
  pkg/oc/lib/graph/genericgraph/test/unpushable-build.yaml
  pkg/oc/lib/newapp/app/imageref_test.go
  pkg/serviceaccounts/oauthclient/oauthclientregistry_test.go
  test/cmd/basicresources.sh
  test/cmd/newapp.sh
  test/cmd/triggers.sh
  test/end-to-end/core.sh
  test/extended/builds/pipeline_origin_bld.go
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/test-build-proxy.yaml
  test/integration/newapp_test.go
  vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/vsphere/vclib/connection_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#24180 UPSTREAM: 82705: use controller to publish cluster authentication info
  vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go
  vendor/k8s.io/kubernetes/pkg/master/client_ca_hook.go
  vendor/k8s.io/kubernetes/pkg/master/client_ca_hook_test.go
  vendor/k8s.io/kubernetes/pkg/master/master.go
  vendor/k8s.io/kubernetes/test/integration/framework/master_utils.go
  vendor/k8s.io/kubernetes/test/integration/serviceaccount/service_account_test.go
Labels: approved, lgtm, size/L

#24175 UPSTREAM: <carry>: remove version skew filter
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/openshiftkubeapiserver/handlers.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/openshiftkubeapiserver/handlers_test.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/openshiftkubeapiserver/patch.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/openshiftkubeapiserver/patch_handlerchain.go
Labels: approved, lgtm, size/L

#24152 Bug 1767182: test/extended/prometheus: run full promQL queries and improve reporting firing alerts
  test/extended/prometheus/prometheus.go
  test/extended/prometheus/prometheus_builds.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#24061 Bug 1764147: don't install CRD SCC types into global scheme
  cmd/oc/oc.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S

#24183 UPSTREAM: 84963: Fix json patch limit check
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/patch.go
  vendor/k8s.io/kubernetes/test/integration/apiserver/max_request_body_bytes_test.go
Labels: approved, lgtm, size/M

#23909 Bug 1758159: aws: sort addresses of multiple interfaces correctly [4.1]
  vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws.go
  vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws_fakes.go
  vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#24182 UPSTREAM: 84466: gce: skip ensureInstanceGroup for a zone that has noremaining nodes for k8s managed IG
  vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/gce/gce_loadbalancer_internal.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/gce/gce_loadbalancer_internal_test.go
Labels: approved, lgtm, size/M

#24177 Bug 1761689: Fix RS expectations for recreate case
  vendor/k8s.io/kubernetes/pkg/controller/replicaset/init_test.go
  vendor/k8s.io/kubernetes/pkg/controller/replicaset/replica_set.go
  vendor/k8s.io/kubernetes/pkg/controller/replicaset/replica_set_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#24117 test: Verify platform metrics are available
  test/extended/prometheus/prometheus.go
  test/extended/prometheus/prometheus_builds.go
Labels: approved, lgtm, size/M

#24199 Bug 1776295: Pin dependencies in release-4.3 branch
  glide.lock
  glide.yaml
  hack/update-deps.sh
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/hack/lib/init.sh
  vendor/github.com/openshift/api/hack/update-deepcopy.sh
  vendor/github.com/openshift/api/imageregistry/install.go
  vendor/github.com/openshift/api/imageregistry/v1/00-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/doc.go
  vendor/github.com/openshift/api/imageregistry/v1/register.go
  vendor/github.com/openshift/api/imageregistry/v1/types.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/install.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XXL

#24204 Bug 1776351: Restore UPSTREAM: 84123: Handle namespace shutdown gracefully
  vendor/k8s.io/kubernetes/pkg/controller/controller_utils.go
  vendor/k8s.io/kubernetes/pkg/controller/cronjob/BUILD
  vendor/k8s.io/kubernetes/pkg/controller/cronjob/cronjob_controller.go
  vendor/k8s.io/kubernetes/pkg/controller/daemon/daemon_controller.go
  vendor/k8s.io/kubernetes/pkg/controller/deployment/deployment_controller.go
  vendor/k8s.io/kubernetes/pkg/controller/deployment/sync.go
  vendor/k8s.io/kubernetes/pkg/controller/endpoint/endpoints_controller.go
  vendor/k8s.io/kubernetes/pkg/controller/endpointslice/reconciler.go
  vendor/k8s.io/kubernetes/pkg/controller/job/job_controller.go
  vendor/k8s.io/kubernetes/pkg/controller/replicaset/replica_set.go
  vendor/k8s.io/kubernetes/pkg/controller/serviceaccount/serviceaccounts_controller.go
  vendor/k8s.io/kubernetes/pkg/controller/serviceaccount/tokens_controller.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/api/core/v1/types.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/api/errors/errors.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/admission/plugin/namespace/lifecycle/BUILD
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/admission/plugin/namespace/lifecycle/admission.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/admission/plugin/namespace/lifecycle/admission_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#24203 Bug 1776351: Restore Miciah's dropped UPSTREAM commits from #24159
  vendor/k8s.io/kubernetes/pkg/controller/controller_utils.go
  vendor/k8s.io/kubernetes/pkg/controller/controller_utils_test.go
  vendor/k8s.io/kubernetes/pkg/controller/replicaset/BUILD
  vendor/k8s.io/kubernetes/pkg/controller/replicaset/replica_set.go
  vendor/k8s.io/kubernetes/pkg/controller/replicaset/replica_set_test.go
  vendor/k8s.io/kubernetes/test/e2e/apps/deployment.go
  vendor/k8s.io/kubernetes/test/e2e/apps/types.go
  vendor/k8s.io/kubernetes/test/e2e/framework/service/jig.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XL

#24206 Bug 1776351: Restore UPSTREAM: <carry>: bump nodes ready timeout
  vendor/k8s.io/kubernetes/test/e2e/framework/framework.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#23711 Marketplace OPSRC&CSC with publisher&displayName
  test/extended/include.go
  test/extended/marketplace/marketplace_lables.go
  test/extended/marketplace/marketplace_utils.go
  test/extended/testdata/bindata.go
  test/extended/testdata/marketplace/csc/02-csc.yaml
  test/extended/testdata/marketplace/opsrc/02-opsrc.yaml
Labels: approved, lgtm, ok-to-test, size/L

#24201 Bug 1776351: Restore UPSTREAM from #24159: Expose a simple journald shim on the kubelet logs endpoint
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_server_journal.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#24207 UPSTREAM: <carry>: use a filter for well-known instead of an apiserver delegate
  vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/patch_openshift.go
  vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/openshiftkubeapiserver/discovery.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/openshiftkubeapiserver/discovery_test.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/openshiftkubeapiserver/nonapiserver.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/openshiftkubeapiserver/patch.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/openshiftkubeapiserver/patch_handlerchain.go
Labels: approved, lgtm, size/L

#24155 Bug 1761346: e2e: populate pending pods map everytime with most recent data
  test/extended/operators/cluster.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#24022 Bug 1719686: Fix ceph expansion
  vendor/k8s.io/kubernetes/pkg/volume/rbd/rbd_test.go
  vendor/k8s.io/kubernetes/pkg/volume/rbd/rbd_util.go
Labels: approved, bugzilla/valid-bug, lgtm, sig/storage, size/M

#24202 Bug 1776351: Restore UPSTREAMs dropped in #24159
  vendor/k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler/reconciler.go
  vendor/k8s.io/kubernetes/pkg/volume/awsebs/aws_ebs.go
  vendor/k8s.io/kubernetes/pkg/volume/awsebs/aws_ebs_block.go
  vendor/k8s.io/kubernetes/pkg/volume/awsebs/aws_ebs_block_test.go
  vendor/k8s.io/kubernetes/pkg/volume/awsebs/aws_ebs_test.go
  vendor/k8s.io/kubernetes/pkg/volume/awsebs/aws_util.go
  vendor/k8s.io/kubernetes/pkg/volume/cinder/cinder_block.go
  vendor/k8s.io/kubernetes/pkg/volume/cinder/cinder_block_test.go
  vendor/k8s.io/kubernetes/pkg/volume/gcepd/gce_pd_block.go
  vendor/k8s.io/kubernetes/pkg/volume/gcepd/gce_pd_block_test.go
  vendor/k8s.io/kubernetes/pkg/volume/local/local.go
  vendor/k8s.io/kubernetes/pkg/volume/local/local_test.go
  vendor/k8s.io/kubernetes/pkg/volume/vsphere_volume/vsphere_volume_block.go
  vendor/k8s.io/kubernetes/pkg/volume/vsphere_volume/vsphere_volume_block_test.go
  vendor/k8s.io/kubernetes/test/e2e/storage/testsuites/disruptive.go
  vendor/k8s.io/kubernetes/test/e2e/storage/testsuites/subpath.go
  vendor/k8s.io/kubernetes/test/e2e/storage/utils/BUILD
  vendor/k8s.io/kubernetes/test/e2e/storage/utils/utils.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XL

#24191 Bug 1775757: KubeAPI server doesn't accept large patch requests
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/patch.go
  vendor/k8s.io/kubernetes/test/integration/apiserver/max_request_body_bytes_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#24219 Bug 1741416: UPSTREAM: 81330: Hide bearer token in logs
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/transport/round_trippers.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/transport/round_trippers_test.go
  vendor/k8s.io/kubernetes/test/e2e/kubectl/kubectl.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#24218 Bug 1741417: UPSTREAM: 81330: Hide bearer token in logs
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/transport/round_trippers.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/transport/round_trippers_test.go
  vendor/k8s.io/kubernetes/test/e2e/kubectl/kubectl.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#24209 inject poststarthooks via config
  vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/aggregator.go
  vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/apiextensions.go
  vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/patch_openshift.go
  vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/openshiftkubeapiserver/patch.go
Labels: approved, lgtm, size/M

#24200 hack: fix unbound variable
  hack/update-deps.sh
Labels: approved, lgtm, size/XS

#24205 Bug 1776351: Restore UPSTREAM:<carry>: apiserver crd validation: remove tls1.3 and modern profile
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/admission/customresourcevalidation/apiserver/validate_apiserver.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/admission/customresourcevalidation/apiserver/validate_apiserver_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#24221 Bug 1765294: Disable flaking token delete test
  test/extended/controller_manager/pull_secret.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#23872 Bug 1727441: kube-proxy periodic iptables reloads are extremely disruptive in large clusters
  vendor/k8s.io/kubernetes/cmd/kube-proxy/app/BUILD
  vendor/k8s.io/kubernetes/cmd/kube-proxy/app/server_others.go
  vendor/k8s.io/kubernetes/cmd/kubeadm/.import-restrictions
  vendor/k8s.io/kubernetes/go.mod
  vendor/k8s.io/kubernetes/pkg/kubelet/BUILD
  vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/network/hostport/fake_iptables.go
  vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/network/kubenet/BUILD
  vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/network/kubenet/kubenet_linux.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_network_linux.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_network_others.go
  vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go
  vendor/k8s.io/kubernetes/pkg/util/BUILD
  vendor/k8s.io/kubernetes/pkg/util/dbus/BUILD
  vendor/k8s.io/kubernetes/pkg/util/dbus/dbus.go
  vendor/k8s.io/kubernetes/pkg/util/dbus/dbus_test.go
  vendor/k8s.io/kubernetes/pkg/util/dbus/doc.go
  vendor/k8s.io/kubernetes/pkg/util/dbus/fake_dbus.go
  vendor/k8s.io/kubernetes/pkg/util/iptables/BUILD
  vendor/k8s.io/kubernetes/pkg/util/iptables/iptables.go
  vendor/k8s.io/kubernetes/pkg/util/iptables/iptables_test.go
  vendor/k8s.io/kubernetes/pkg/util/iptables/monitor_test.go
  vendor/k8s.io/kubernetes/pkg/util/iptables/testing/fake.go
  vendor/k8s.io/kubernetes/test/e2e/network/networking.go
  vendor/k8s.io/kubernetes/test/e2e/network/service.go
  vendor/k8s.io/kubernetes/test/test_owners.csv
Labels: approved, bugzilla/valid-bug, lgtm, size/XXL

#24230 remove publishing staging rules
  publishing-staging-rules.yaml
Labels: approved, lgtm, size/XS

#24196 Bug 1776226: KubeAPI server doesn't accept large patch requests
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/patch.go
  vendor/k8s.io/kubernetes/test/integration/apiserver/max_request_body_bytes_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#24124 Bug 1739262: RequestHeaders IdP: fix TLS handshake [4.1]
  pkg/oauthserver/oauthserver/auth.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#24160 Bug 1772904: [4.1] Clean up egress IPs on startup
  pkg/network/common/egressip.go
  pkg/network/common/egressip_test.go
  pkg/network/master/egressip.go
  pkg/network/node/egressip.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#24006 [release-4.2] Bug 1762658: UPSTREAM: 83747: Improve efficiency of csiMountMgr.GetAttributes
  vendor/k8s.io/kubernetes/pkg/volume/csi/csi_mounter.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#24217 extended util oauthserver - increase pod ready wait time
  test/extended/util/oauthserver/oauthserver.go
Labels: approved, lgtm, size/XS

#24237 UPSTREAM: 85722: apiextensions: filter required nullable to workaround kubectl validation
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/controller/openapi/v2/conversion.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/controller/openapi/v2/conversion_test.go
Labels: approved, lgtm, size/L
