Repository openshift/origin, pull requests merged in 2019-10, with the labels that each got.

#23747 origin.spec OKD RPM build readiness
  hack/build-rpms.sh
  origin.spec
Labels: approved, lgtm, size/M

#23891 Bug 1757424: remove use of deprecated -p with kubectl/oc exec
  test/extended/builds/s2i_env.go
  test/extended/builds/s2i_incremental.go
  test/extended/image_ecosystem/scl.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#23863 Disable GPUDevicePluginAcrossRecreate test
  test/extended/util/test.go
Labels: approved, lgtm, size/XS

#23848 cmd/openshift-tests: Autodetect cloud
  cmd/openshift-tests/openshift-tests.go
  test/extended/util/cloud/cloud.go
  test/extended/util/test.go
Labels: approved, lgtm, size/L

#23783 Bug 1752045: UPSTREAM: <carry>:Add a RBAC checker for external IP ranger
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/admission/network/externalipranger/externalip_admission.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/admission/network/externalipranger/externalip_admission_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#23892 Bug 1755936: e2e: stabilize ingress metrics tests
  test/extended/prometheus/prometheus.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#23904 Bug 1709178: Prevent egress DNS request flooding
  pkg/network/common/dns.go
  pkg/network/common/dns_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#23905 test: Don't block on cloud providers without zones in autodetect
  test/extended/util/cloud/cloud.go
Labels: approved, lgtm, size/XS

#23791 changes openshift-tests to report and error when creating kube client fails
  cmd/openshift-tests/openshift-tests.go
  test/extended/util/test.go
Labels: approved, lgtm, size/XS

#23914 [3.11] BUG 1758267: UPSTREAM: 61330: fix workgroup panic bug
  vendor/k8s.io/kubernetes/cmd/kubelet/app/server.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#23183 [3.10] ImageGC fixes
  vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/docker_image.go
  vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/docker_image_test.go
  vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/libdocker/fake_client.go
Labels: approved, lgtm, size/L

#23907 UPSTREAM: <carry> print merged flags at startup
  vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go
Labels: approved, lgtm, size/XS

#23894 Bug 1755039: Enable storage tests that require 1.16 kubelet
  test/extended/util/test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#23487 auto for smoke case OCP-10658
  test/extended/cli/rsh.go
  test/extended/testdata/bindata.go
  test/extended/testdata/cli/pod-with-two-containers.yaml
Labels: approved, lgtm, size/L

#23913 Bug 1758235: NetworkPolicy performance fixes [3.11]
  pkg/network/node/networkpolicy.go
  pkg/network/node/networkpolicy_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XL

#23896 OVN-Kubernetes: some more test tweaks
  test/extended/util/test.go
Labels: approved, lgtm, size/S

#23897 Bug 1711600: UPSTREAM: 82424:Use pod + nsenter instead of SSH in mount propagation tests
  test/extended/util/test.go
  vendor/k8s.io/kubernetes/test/e2e/node/BUILD
  vendor/k8s.io/kubernetes/test/e2e/node/mount_propagation.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#23761 [3.9] Bug 1749930: ImageGC fixes
  vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/docker_image.go
  vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/docker_image_test.go
  vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/libdocker/fake_client.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#23936 UPSTREAM: <drop>: Lower DescribeVolumes polling frequency
  vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/aws/aws.go
Labels: approved, lgtm, size/M

#23939 Bug 1757887: CVE-2019-11253 billion laughs
  glide.lock
  glide.yaml
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/google.golang.org/appengine/aetest/instance_vm.go
  vendor/google.golang.org/appengine/delay/delay.go
  vendor/google.golang.org/appengine/delay/delay_test.go
  vendor/google.golang.org/appengine/go.mod
  vendor/google.golang.org/appengine/go.sum
  vendor/gopkg.in/yaml.v2/benchmark_test.go
  vendor/gopkg.in/yaml.v2/decode.go
  vendor/gopkg.in/yaml.v2/decode_test.go
  vendor/gopkg.in/yaml.v2/encode.go
  vendor/gopkg.in/yaml.v2/encode_test.go
  vendor/gopkg.in/yaml.v2/resolve.go
  vendor/gopkg.in/yaml.v2/scannerc.go
  vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/options/options_test.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/apiserver.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_handler.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/test/integration/BUILD
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/test/integration/limit_test.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/runtime/serializer/json/BUILD
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/runtime/serializer/json/json.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/runtime/serializer/json/json_limit_test.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/runtime/serializer/yaml/BUILD
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/runtime/serializer/yaml/yaml_test.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/json/json.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/fieldmanager.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/patch.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/config.go
  vendor/k8s.io/kubernetes/test/integration/apiserver/max_request_body_bytes_test.go
  vendor/k8s.io/kubernetes/test/integration/master/synthetic_master_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XXL

#23946 Bug 1757712: CVE-2019-11253 billion laughs
  glide.lock
  glide.yaml
  vendor/github.com/google/btree/btree_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/certsyncpod/certsync_cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/certsyncpod/certsync_controller.go
  vendor/gopkg.in/yaml.v2/benchmark_test.go
  vendor/gopkg.in/yaml.v2/decode.go
  vendor/gopkg.in/yaml.v2/decode_test.go
  vendor/gopkg.in/yaml.v2/encode.go
  vendor/gopkg.in/yaml.v2/encode_test.go
  vendor/gopkg.in/yaml.v2/resolve.go
  vendor/gopkg.in/yaml.v2/scannerc.go
  vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/options/options_test.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/apiserver.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_handler.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/test/integration/BUILD
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/test/integration/limit_test.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/runtime/serializer/json/BUILD
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/runtime/serializer/json/json.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/runtime/serializer/json/json_limit_test.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/runtime/serializer/yaml/BUILD
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/runtime/serializer/yaml/yaml_test.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/json/json.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/patch.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/config.go
  vendor/k8s.io/kubernetes/test/integration/apiserver/max_request_body_bytes_test.go
  vendor/k8s.io/kubernetes/test/integration/master/synthetic_master_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XXL

#23945 UPSTREAM: 00000: add debugging for upgrade tests
  vendor/k8s.io/kubernetes/test/e2e/upgrades/apps/daemonsets.go
  vendor/k8s.io/kubernetes/test/e2e/upgrades/apps/deployments.go
  vendor/k8s.io/kubernetes/test/e2e/upgrades/apps/replicasets.go
Labels: approved, lgtm, size/S

#23952 UPSTREAM: 83751: Fixed bug in TopologyManager with SingleNUMANode Policy
  vendor/k8s.io/kubernetes/pkg/kubelet/cm/topologymanager/topology_manager.go
  vendor/k8s.io/kubernetes/pkg/kubelet/cm/topologymanager/topology_manager_test.go
Labels: approved, lgtm, size/M

#23944 UPSTREAM: 00000: add debugging for upgrade tests
  vendor/k8s.io/kubernetes/test/e2e/upgrades/apps/daemonsets.go
  vendor/k8s.io/kubernetes/test/e2e/upgrades/apps/deployments.go
  vendor/k8s.io/kubernetes/test/e2e/upgrades/apps/replicasets.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S

#23958 Bug 1761276: Write test monitor errors to monitor_*.xml
  pkg/test/ginkgo/cmd_runsuite.go
  pkg/test/ginkgo/junit.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#23957 Bug 1753731: add extended build new-app tests back
  test/extended/builds/new_app.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#23934 Bug 1753500: UPSTREAM: 82503
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cp/cp.go
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cp/cp_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#23963 UPSTREAM: 83911: Fix DeltaFIFO Replace method to prevent SharedIndexInformers from missing notifications
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/cache/delta_fifo.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/cache/delta_fifo_test.go
Labels: approved, lgtm, size/M

#23933 Bug 1753501: UPSTREAM: 82503
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cp.go
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cp_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#23752 Bug 1748814: Remove 'option tcplog' from passthrough backend in template router
  images/router/haproxy/conf/haproxy-config.template
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#23918 [release-3.11] Bug 1758375: fix haproxy reload crash when processing ECDSA keys
  pkg/route/controller/routeapihelpers/validation.go
  pkg/route/controller/routeapihelpers/validation_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#23975 Add consoleyamlsamples to list of console resource exceptions
  test/extended/authorization/rbac/groups_default_rules.go
Labels: approved, lgtm, size/XS

#23410 Add OWNERS of storage components
  vendor/OWNERS
Labels: approved, lgtm, size/XS

#23974 Update OWNERS
  contrib/completions/OWNERS
  docs/man/OWNERS
  hack/OWNERS
  images/openldap/OWNERS
  test/OWNERS
  test/extended/authorization/rbac/OWNERS
  tools/etcdhelper/OWNERS
Labels: approved, lgtm, size/S

#23964 Bug 1761682: test oauth server: increase timeout, wait for pod ready first
  test/extended/util/oauthserver/oauthserver.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#23969 Bug 1745773: UPSTREAM: 83747: Improve efficiency of csiMountMgr.GetAttributes
  vendor/k8s.io/kubernetes/pkg/volume/csi/csi_mounter.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#23980 Bug 1749649: Fix ignoring non-server records when server threshold is exceeded
  pkg/router/metrics/haproxy/haproxy.go
Labels: approved, bugzilla/valid-bug, lgtm, ok-to-test, size/XS

#23962 test: Update junit naming to ensure disruption tests are recorded
  pkg/test/ginkgo/cmd_runsuite.go
  pkg/test/ginkgo/junit.go
  test/e2e/upgrade/upgrade.go
  test/extended/util/disruption/disruption.go
Labels: approved, lgtm, size/S

#23976 Bug 1751654: Revert "CHECK(workload): e2e: disable kubectl exec test with pod/name…
  test/extended/util/test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#23870 Bug 1734319: aws: sort addresses of multiple interfaces correctly
  vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/aws/aws.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/aws/aws_fakes.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/aws/aws_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#23727 Bug 1737654: UPSTREAM: 75037: UPSTREAM: 76788: UPSTREAM: 80436
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cp.go
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cp_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XL

#23960 tests: exclude ovnkube-master from toleration test
  test/extended/operators/tolerations.go
Labels: approved, lgtm, size/XS

#23990 Clear providerID during quorum restore test
  test/extended/dr/quorum_restore.go
Labels: approved, lgtm, size/XS

#23988 monitor: Report when pods are evicted or preempted
  pkg/monitor/pod.go
Labels: approved, lgtm, size/S

#23992 Bug 1751820: test/extended/operators: ensure clusterversion current version is set
  test/extended/operators/operators.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#22631 test/extended/util/url: Truncate test output files
  test/extended/util/url/url.go
Labels: approved, lgtm, size/XS

#23977 Bug 1698829: UPSTREAM: 83567: Fix attachment of just detached AWS volumes
  vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/aws/aws.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#23972 UPSTREAM: 83296: Only kill process where killing failed during previous iterations
  vendor/k8s.io/kubernetes/pkg/kubelet/cm/pod_container_manager_linux.go
Labels: approved, lgtm, size/XS

#23915 Bug 1757904: Add missing patches against between ose and origin 3.10
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cp.go
  vendor/k8s.io/kubernetes/pkg/volume/flexvolume/detacher.go
  vendor/k8s.io/kubernetes/pkg/volume/flexvolume/unmounter.go
  vendor/k8s.io/kubernetes/pkg/volume/util/util.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#23884 Bug 1757046: Sanitize user input when erroring on an unknown redirect handler [4.1]
  pkg/oauthserver/oauth/handlers/default_auth_handler.go
  pkg/oauthserver/oauth/handlers/default_auth_handler_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S

#23875 Bug 1756458: Separate upgrade flags for safety instead of abusing force
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/oc/cli/admin/upgrade/upgrade.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#23912 Bug 1758233: NetworkPolicy performance fixes [4.1]
  pkg/network/node/networkpolicy.go
  pkg/network/node/networkpolicy_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XL

#23998 Test conditionally installing cri-o
  images/os/Dockerfile
Labels: approved, lgtm, size/XS

#23995 Make the metric more readable when fails
  test/extended/prometheus/prometheus.go
Labels: approved, lgtm, size/XS

#24002 images: Extend the os image to install machine-config-daemon
  images/os/Dockerfile
Labels: approved, lgtm, size/XS

#23983 UPSTREAM: 82439: Delete e2e namespaces asynchronously
  vendor/k8s.io/kubernetes/pkg/registry/core/namespace/storage/storage.go
  vendor/k8s.io/kubernetes/pkg/registry/core/namespace/storage/storage_test.go
  vendor/k8s.io/kubernetes/test/e2e/framework/framework.go
  vendor/k8s.io/kubernetes/test/e2e/framework/util.go
Labels: approved, lgtm, size/L

#23806 UPSTREAM: 80004: Prefer to delete doubled-up pods of a ReplicaSet
  vendor/k8s.io/kubernetes/pkg/controller/controller_utils.go
  vendor/k8s.io/kubernetes/pkg/controller/controller_utils_test.go
  vendor/k8s.io/kubernetes/pkg/controller/replicaset/BUILD
  vendor/k8s.io/kubernetes/pkg/controller/replicaset/replica_set.go
  vendor/k8s.io/kubernetes/pkg/controller/replicaset/replica_set_test.go
  vendor/k8s.io/kubernetes/test/e2e/apps/deployment.go
  vendor/k8s.io/kubernetes/test/e2e/apps/types.go
  vendor/k8s.io/kubernetes/test/e2e/framework/service/jig.go
Labels: approved, lgtm, size/XL

#24001 Disable the s2i build with quota memory test
  test/extended/builds/s2i_quota.go
Labels: approved, lgtm, size/XS

#23982 Remove Travis CI definition from this repo
  .travis.yml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S

#23989 UPSTREAM: 84120: Preemption metrics
  vendor/k8s.io/kubernetes/pkg/kubelet/metrics/metrics.go
  vendor/k8s.io/kubernetes/pkg/kubelet/preemption/preemption.go
Labels: approved, lgtm, size/S

#24012 Bug 1765177: e2e: fix flaky route wait function
  test/extended/router/scoped.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#24004 Bug 1759998: Bug 1690588: UPSTREAM: 84181: Lower AWS DescribeVolume frequency
  vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/aws/aws.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#23862 Bug 1753071: Skip alert test when test environment is known to be skewed
  test/extended/prometheus/prometheus.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#23712 Automate [OLM] [OCP-24061] - [bz 1685230] OLM operator should use imagePullPolicy: IfNotPresent
  test/extended/operators/olm.go
Labels: approved, lgtm, size/S

#24029 Revert "test/extended/operators: ensure clusterversion current version is set"
  test/extended/operators/operators.go
Labels: approved, lgtm, size/XS

#24005 test/extended/prometheus: better check for firing alerts
  test/extended/prometheus/prometheus.go
  test/extended/prometheus/prometheus_builds.go
Labels: approved, lgtm, size/S

#24028 e2e: fix more flaky route wait functions
  test/extended/router/config_manager.go
  test/extended/router/headers.go
  test/extended/router/scoped.go
Labels: approved, lgtm, size/XS

#24032 UPSTREAM: carry: add pod logs dump to e2e
  vendor/k8s.io/kubernetes/test/e2e/framework/pod/resource.go
Labels: approved, lgtm, size/S

#24024 test: Fewer smoke tests
  test/extended/machines/machines.go
  test/extended/operators/images.go
  test/extended/operators/qos.go
  test/extended/operators/tolerations.go
Labels: approved, lgtm, size/XS

#24016 adds publishing rules for origin-4.3-kubernetes-1.16.2
  publishing-rules.yaml
Labels: approved, lgtm, size/XS

#24015 adds origin-4.3-kubernetes-1.16.2 to publishing-kube-rules
  publishing-kube-rules.yaml
Labels: approved, lgtm, size/L

#23965 Bug 1761814: Informers can miss notifications
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/cache/delta_fifo.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/cache/delta_fifo_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#24023 test: Add additional debugging to flaky pull secret test
  test/extended/controller_manager/pull_secret.go
Labels: approved, lgtm, size/S

#23887 Bug 1757234: Cherry-pick: Kubelet should use watch-based configMapAndSecretChangeDetectionStrategy
  vendor/k8s.io/kubernetes/cmd/kubeadm/app/util/config/testdata/defaulting/controlplane/defaulted.yaml
  vendor/k8s.io/kubernetes/cmd/kubeadm/app/util/config/testdata/defaulting/controlplane/defaulted_non_linux.yaml
  vendor/k8s.io/kubernetes/pkg/kubelet/apis/config/v1beta1/defaults.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#24043 Bug 1764414: oauth: add more debugging to oauth test
  test/extended/oauth/requestheaders.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#24041 switches the remainings repos to origin-4.3-kubernetes-1.16.2
  glide.lock
  glide.yaml
  vendor/k8s.io/csi-api/Godeps/Godeps.json
  vendor/k8s.io/csi-api/go.mod
  vendor/k8s.io/csi-api/go.sum
Labels: approved, lgtm, size/L

#23635 test/extended/router: Fix namespace for DumpPodLogs
  test/extended/router/metrics.go
  test/extended/router/reencrypt.go
Labels: approved, lgtm, size/XS

#23656 test/extended/util: SetupProject: Fix cancel logic
  test/extended/util/client.go
Labels: approved, lgtm

#24046 adds missing commits after 1.16.2 rebase
  vendor/k8s.io/kubernetes/pkg/kubelet/metrics/metrics.go
  vendor/k8s.io/kubernetes/pkg/kubelet/preemption/preemption.go
  vendor/k8s.io/kubernetes/test/e2e/framework/framework.go
  vendor/k8s.io/kubernetes/test/e2e/framework/util.go
Labels: approved, lgtm, size/L

#24050 removes origin-4.3-kubernetes-1.16.0-rc.2 from kube publishing rules
  publishing-kube-rules.yaml
Labels: approved, lgtm, size/L

#24051 UPSTREAM: 84561: FIPS changes for passing unit tests
  vendor/k8s.io/kubernetes/pkg/controller/certificates/approver/sarapprove_test.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/httpstream/spdy/roundtripper_test.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/proxy/dial_test.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/proxy/upgradeaware_test.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/storage/value/encrypt/aes/aes_test.go
Labels: approved, lgtm, size/L

#24052 e2e: RequestHeader IDP: fix common flake
  test/extended/oauth/requestheaders.go
Labels: approved, lgtm, size/M

#24065 try to run all 4 jenkins e2e ginkgos in parallel before bumping timeout
  cmd/openshift-tests/e2e.go
Labels: approved, lgtm, size/XS

#24056 Fix completion tests to be more resilient to changes
  test/extended/testdata/bindata.go
  test/extended/testdata/cmd/test/cmd/completions.sh
Labels: approved, lgtm, size/XS
