Repository openshift/origin, pull requests merged in 2019-03, with the labels that each got.

#22176 [4.0] UPSTREAM: 74524: Don't fail if iface is being used by iSCSI session
  vendor/k8s.io/kubernetes/pkg/volume/iscsi/BUILD
  vendor/k8s.io/kubernetes/pkg/volume/iscsi/iscsi_util.go
Labels: approved, lgtm, sig/storage, size/S

#22180 UPSTREAM: 74636: Remove reflector metrics as they currently cause a memory leak
  vendor/k8s.io/kubernetes/pkg/util/reflector/prometheus/prometheus.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/cache/reflector.go
Labels: approved, lgtm, size/S

#22188 apiextensions-apiserver: fix empty APIResource group+version handling in wait logic
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/apiserver.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_discovery_controller.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go
Labels: approved, lgtm, size/M

#22184 Ensure clone works without `-C` for release extraction
  pkg/oc/cli/admin/release/git.go
Labels: approved, lgtm, size/S

#21995 Test conformance from 1.12 for Kube
  test/extended/conformance-k8s.sh
Labels: approved, lgtm, size/XS

#22175 UPSTREAM: 74524: Don't fail if iface is being used by iSCSI session
  vendor/k8s.io/kubernetes/pkg/volume/iscsi/BUILD
  vendor/k8s.io/kubernetes/pkg/volume/iscsi/iscsi_util.go
Labels: approved, lgtm, sig/storage, size/S

#22201 Bug 1666583 - improve image layer size output when size info not available
  pkg/oc/cli/image/info/info.go
Labels: approved, lgtm, size/S

#22195 Require OsinServerConfig in OAuth server binary
  pkg/cmd/openshift-integrated-oauth-server/cmd.go
Labels: approved, lgtm, size/XS

#21546 docs/rebase.md: fix word typo
  docs/rebase.md
Labels: approved, lgtm, ok-to-test, size/XS

#22213 Write image-references to disk after all metadata is fetched
  pkg/oc/cli/admin/release/extract.go
  pkg/oc/cli/admin/release/git.go
  pkg/oc/cli/admin/release/image_mapper.go
  pkg/oc/cli/admin/release/new.go
Labels: approved, lgtm, size/M

#21920 UPSTREAM: 70580: PV Controller: fix recycling
  vendor/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/pv_controller.go
  vendor/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/recycle_test.go
Labels: approved, lgtm, size/S

#21138 contrib: systemd: fix systemd accounting
  contrib/systemd/origin-accounting.conf
Labels: approved, lgtm, size/XS

#22044 Allow system:registry to use layers API
  pkg/cmd/server/bootstrappolicy/policy.go
  test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml
  test/testdata/bootstrappolicy/bootstrap_policy_file.yaml
Labels: approved, lgtm, size/XS

#22211 Bug 1684368 - Use proper deletion propagation policy when removing deployments
  pkg/oc/cli/admin/prune/deployments/prune.go
Labels: approved, lgtm, size/S

#22205 UPSTREAM: 74806: src/k8s.io/apiserver: Increase cert expiration histo…
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/authentication/request/x509/x509.go
Labels: approved, lgtm, size/XS

#22165 Fix bug 1278683
  pkg/oc/lib/describe/describer.go
Labels: approved, lgtm, size/S

#22223 explain UPSTREAM: 00000:
  HACKING.md
Labels: approved, lgtm, size/S

#22202 UPSTREAM: 74804: apiextensions: add nullable support to OpenAPI v3 validations
  pkg/openapi/zz_generated.openapi.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/fuzzer/fuzzer.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/types_jsonschema.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types_jsonschema.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.conversion.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/validation/validation.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/validation/validation_test.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/validation/validation.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/validation/validation_test.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/controller/openapi/conversion.go
Labels: approved, lgtm, size/L

#22227 TEMP: Disabling build cluster config tests
  test/extended/builds/cluster_config.go
Labels: approved, lgtm, size/XS

#22138 UPSTREAM: 72245: Add AWS Custom Endpoint capability
  vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/aws/BUILD
  vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws.go
  vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws_test.go
Labels: approved, lgtm, size/L

#22222 UPSTREAM: 72245: Add AWS Custom Endpoint capability
  vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/aws/BUILD
  vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws.go
  vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws_test.go
Labels: approved, lgtm, size/L

#22234 openshift-apiserver: set openshift apiserver config defaults for legacy config
  pkg/cmd/openshift-apiserver/cmd.go
Labels: approved, lgtm, size/XS

#22229 Support reloading CA files
  pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/patch_authenticator.go
  vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go
  vendor/k8s.io/kubernetes/cmd/kubelet/app/auth.go
  vendor/k8s.io/kubernetes/pkg/kubeapiserver/authenticator/config.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/authentication/authenticatorfactory/delegating.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/authentication/request/headerrequest/requestheader.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/authentication/request/x509/x509.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/certs/clientca.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/certs/serving.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/config.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/config_selfclient.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/dynamic_certificate.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/dynamic_certificate_test.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/hooks.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/options/authentication.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/options/serving.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/options/serving_test.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/options/serving_with_loopback.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/options/testing/certs.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/secure_serving.go
Labels: approved, lgtm, size/XL

#22158 properly delete NetworkPolicies when deleting their namespace
  pkg/network/node/networkpolicy.go
Labels: approved, component/networking, kind/bug, lgtm, sig/networking, size/S

#22232 release: Add newlines to descriptions in changelog
  pkg/oc/cli/admin/release/info.go
Labels: approved, lgtm, size/XS

#22235 UPSTREAM: 74956: make delegating authorization use protobuf client
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/options/authorization.go
Labels: approved, lgtm, size/XS

#22239 dynamically reload aggregator cert
  vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/aggregator.go
  vendor/k8s.io/kubernetes/pkg/kubeapiserver/authenticator/config.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/certs/serving.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/certs/single_certkey_pair.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/config.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/apiserver/apiserver.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/apiserver/apiservice_controller.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/apiserver/handler_proxy.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/apiserver/handler_proxy_test.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/cmd/server/start.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/controllers/status/available_controller.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/controllers/status/available_controller_test.go
Labels: approved, lgtm, size/L

#22244 cert logging
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/certs/clientca.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/certs/serving.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/options/authentication.go
Labels: approved, lgtm, size/S

#22209 check for and report sync errors properly
  pkg/build/controller/build/build_controller.go
Labels: approved, lgtm, size/XS

#22245 Strip binaries by default, debug use is not common
  hack/lib/constants.sh
Labels: approved, lgtm, size/XS

#22219 UPSTREAM: 72376: Filter resources logged by e2e ns debugging
  vendor/k8s.io/kubernetes/test/e2e/framework/util.go
Labels: approved, lgtm, size/XS

#22210 Add adambkaplan as DevEx approver
  examples/db-templates/OWNERS
  examples/hello-openshift/OWNERS
  examples/image-streams/OWNERS
  examples/quickstarts/OWNERS
  examples/sample-app/OWNERS
  pkg/admission/customresourcevalidation/image/OWNERS
  pkg/api/OWNERS
  pkg/build/OWNERS
  pkg/image/OWNERS
  pkg/oc/cli/admin/prune/imageprune/OWNERS
  pkg/oc/lib/newapp/OWNERS
  pkg/openapi/OWNERS
  pkg/template/OWNERS
  test/extended/OWNERS
  tools/buildanalyzer/OWNERS
Labels: approved, lgtm, size/M

#22179 Don't override kubelet volume path
  test/extended/util/test.go
Labels: approved, lgtm, sig/storage, size/XS

#21905 test/extended: Properly wait for project/namespace to be provisioned and fix deployer role
  test/extended/builds/build_pruning.go
  test/extended/builds/build_timing.go
  test/extended/builds/completiondeadlineseconds.go
  test/extended/builds/digest.go
  test/extended/builds/docker_pullsecret.go
  test/extended/builds/dockerfile.go
  test/extended/builds/failure_status.go
  test/extended/builds/forcepull.go
  test/extended/builds/gitauth.go
  test/extended/builds/hooks.go
  test/extended/builds/image_source.go
  test/extended/builds/imagechangetriggers.go
  test/extended/builds/labels.go
  test/extended/builds/multistage.go
  test/extended/builds/new_app.go
  test/extended/builds/nosrc.go
  test/extended/builds/optimized.go
  test/extended/builds/pipeline_jenkins_e2e.go
  test/extended/builds/pipeline_origin_bld.go
  test/extended/builds/proxy.go
  test/extended/builds/pullsecret.go
  test/extended/builds/remove_buildconfig.go
  test/extended/builds/revision.go
  test/extended/builds/run_policy.go
  test/extended/builds/s2i_dropcaps.go
  test/extended/builds/s2i_env.go
  test/extended/builds/s2i_incremental.go
  test/extended/builds/s2i_quota.go
  test/extended/builds/s2i_root.go
  test/extended/builds/service.go
  test/extended/builds/start.go
  test/extended/builds/valuefrom.go
  test/extended/cli/debug.go
  test/extended/deployments/deployments.go
  test/extended/image_ecosystem/mariadb_ephemeral.go
  test/extended/image_ecosystem/mongodb_ephemeral.go
  test/extended/image_ecosystem/mysql_ephemeral.go
  test/extended/image_ecosystem/s2i_perl.go
  test/extended/image_ecosystem/s2i_php.go
  test/extended/image_ecosystem/s2i_python.go
  test/extended/image_ecosystem/s2i_ruby.go
  test/extended/image_ecosystem/sample_repos.go
  test/extended/image_ecosystem/scl.go
  test/extended/imageapis/limitrange_admission.go
  test/extended/imageapis/quota_admission.go
  test/extended/images/append.go
  test/extended/images/hardprune.go
  test/extended/images/prune.go
  test/extended/prometheus/prometheus_builds.go
  test/extended/templates/templateinstance_fail.go
  test/extended/templates/templateinstance_readiness.go
  test/extended/templates/templateservicebroker_e2e.go
  test/extended/templates/templateservicebroker_security.go
  test/extended/util/cli.go
Labels: approved, lgtm, sig/master, size/L

#21839 Fix incorrect validation message in sccadmission (replace psp with scc)
  pkg/security/apiserver/admission/sccadmission/admission.go
Labels: approved, lgtm, ok-to-test, size/XS

#22251 [3.11] properly delete NetworkPolicies when deleting their namespace
  pkg/network/node/networkpolicy.go
Labels: approved, component/networking, kind/bug, lgtm, sig/networking, size/S

#22012 Drop duplicate copy of NetworkPolicy tests
  test/extended/networking/networkpolicy.go
Labels: approved, component/networking, lgtm, sig/networking, size/XL

#22256 Fixing openapi spec
  vendor/k8s.io/kubernetes/pkg/generated/openapi/zz_generated.openapi.go
Labels: approved, lgtm, priority/critical-urgent, queue/critical-fix, size/XS

#22262 skip openshift admission on default namespace
  pkg/admission/namespaceconditions/decorator.go
  pkg/quota/apiserver/admission/clusterresourcequota/admission.go
Labels: approved, lgtm, size/XS

#22199 Bug 1665357 - update oc registry info help message
  pkg/oc/cli/registry/info/info.go
Labels: approved, lgtm, size/XS

#22204 Add soltysh to test approvers
  test/OWNERS
Labels: approved, lgtm, size/XS

#22212 Bug 1564849 - Fix oc command suggestions in new-app
  pkg/oc/lib/newapp/cmd/describe.go
Labels: approved, lgtm, size/S

#22183 Bug 1558935 - Replace kubectl name in long description of oc commands
  pkg/cmd/util/cmd.go
Labels: approved, lgtm, size/XS

#22264 remove admission dependencies on project cache
  pkg/autoscaling/admission/clusterresourceoverride/admission.go
  pkg/autoscaling/admission/clusterresourceoverride/admission_test.go
  pkg/autoscaling/admission/runonceduration/admission.go
  pkg/autoscaling/admission/runonceduration/admission_test.go
  pkg/cmd/openshift-kube-apiserver/kubeadmission/register.go
  pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/patch.go
  pkg/cmd/server/admission/init.go
  pkg/cmd/server/admission/types.go
  pkg/image/apiserver/admission/imagepolicy/imagepolicy.go
  pkg/image/apiserver/admission/imagepolicy/imagepolicy_test.go
  pkg/project/apiserver/admission/requestlimit/admission.go
  pkg/project/apiserver/admission/requestlimit/admission_test.go
  pkg/project/cache/cache.go
  pkg/scheduler/admission/nodeenv/admission.go
  pkg/scheduler/admission/nodeenv/admission_test.go
Labels: approved, lgtm, size/L

#22258 UPSTREAM: 75037: Fix panic in kubectl cp command
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cp.go
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cp_test.go
Labels: approved, lgtm, size/L

#22226 Added windows executable extensions to Kubectl plugins
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/plugin.go
Labels: approved, lgtm, size/S

#22265 Fix URL ( bug 1686322 )
  pkg/oc/cli/admin/release/info.go
Labels: approved, lgtm, size/XS

#22263 project admission isn't required on the kube-apiserver
  pkg/cmd/openshift-kube-apiserver/kubeadmission/register.go
Labels: approved, lgtm, priority/critical-urgent, queue/critical-fix, size/XS

#22266 UPSTREAM: 65849: fix kube-aggregator dailer
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/apiserver/handler_proxy.go
Labels: approved, lgtm, size/S

#22254 fix(kubeadmission): turn RestrictSubjectBindings admission plugin on by default
  pkg/cmd/openshift-kube-apiserver/kubeadmission/register.go
Labels: approved, lgtm, size/XS

#22257 UPSTREAM: 75037: Fix panic in kubectl cp command
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cp.go
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cp_test.go
Labels: approved, lgtm, size/L

#21978 UPSTREAM: 73758: kubelet: set low oom_score_adj for containers in critical pods
  vendor/k8s.io/kubernetes/pkg/kubelet/qos/BUILD
  vendor/k8s.io/kubernetes/pkg/kubelet/qos/policy.go
  vendor/k8s.io/kubernetes/pkg/kubelet/qos/policy_test.go
Labels: approved, lgtm, size/M

#22236 UPSTREAM: 74755: Revert kubelet to default to ttl cache secret/configmap
  vendor/k8s.io/kubernetes/cmd/kubeadm/app/util/config/testdata/conversion/master/internal.yaml
  vendor/k8s.io/kubernetes/cmd/kubeadm/app/util/config/testdata/conversion/master/v1alpha2.yaml
  vendor/k8s.io/kubernetes/cmd/kubeadm/app/util/config/testdata/conversion/master/v1alpha3.yaml
  vendor/k8s.io/kubernetes/cmd/kubeadm/app/util/config/testdata/defaulting/master/defaulted.yaml
  vendor/k8s.io/kubernetes/pkg/kubelet/apis/config/v1beta1/defaults.go
Labels: approved, lgtm, size/S

#22241 UPSTREAM: 74222: kubelet: return mirror pod in GetActivePods()
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_pods.go
  vendor/k8s.io/kubernetes/test/e2e_node/BUILD
  vendor/k8s.io/kubernetes/test/e2e_node/system_node_critical_test.go
Labels: approved, lgtm, size/L

#22272 Do not set empty volume directory
  test/extended/util/test.go
Labels: approved, lgtm, size/XS

#22196 prevent deletion of cluster-wide config resources
  pkg/admission/customresourcevalidation/config/deny_delete_cluster_config_resource.go
  pkg/admission/customresourcevalidation/config/deny_delete_cluster_config_resource_test.go
  pkg/admission/customresourcevalidation/customresourcevalidationregistration/cr_validation_registration.go
  pkg/admission/customresourcevalidation/features/deny_delete_features.go
Labels: approved, lgtm, size/L

#22280 Add scheduling CRD validation
  pkg/admission/customresourcevalidation/customresourcevalidationregistration/cr_validation_registration.go
  pkg/admission/customresourcevalidation/scheduler/OWNERS
  pkg/admission/customresourcevalidation/scheduler/validate_scheduler.go
Labels: approved, lgtm, size/L

#22271 test/extended/prom: use coreos-pull-secret for pullsecret
  test/extended/prometheus/prometheus.go
Labels: approved, lgtm, size/S

#22281 code-generator: add FeaturesList and DNSList to pluralExceptions
  vendor/k8s.io/kubernetes/staging/src/k8s.io/code-generator/cmd/client-gen/generators/client_generator.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/code-generator/cmd/informer-gen/generators/generic.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/code-generator/cmd/informer-gen/generators/packages.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/code-generator/cmd/lister-gen/generators/lister.go
Labels: approved, lgtm, size/S

#22261 Bug 1684397: Remove custom build template
  examples/examples_test.go
  test/cmd/printer.sh
  test/end-to-end/core.sh
  test/extended/cli/rsync.go
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/application-template-custombuild.json
Labels: approved, lgtm, size/XXL

#22285 Suppress monitor output per test when only running a few tests
  pkg/test/ginkgo/status.go
Labels: approved, lgtm, size/XS

#22286 Display more debug info and wait longer for upgrade test
  test/e2e/upgrade/upgrade.go
Labels: approved, lgtm, size/S

#22284 release: Fetch the target repo instead of '--all'
  pkg/oc/cli/admin/release/git.go
  pkg/oc/cli/admin/release/info.go
Labels: approved, lgtm, size/XS

#22287 Increase the upgrade suite timeout longer
  cmd/openshift-tests/upgrade.go
  test/e2e/upgrade/upgrade.go
Labels: approved, lgtm, size/XS

#22289 Bindmount /var/lib/iscsi rw for iscsi attach
  images/node/system-container/config.json.template
Labels: approved, lgtm, size/S

#22288 deploymentconfig: log update conflicts using higher log level in controller
  pkg/apps/controller/deploymentconfig/deploymentconfig_controller.go
Labels: approved, lgtm, size/XS

#22295 [3.11] contrib: systemd: fix systemd accounting
  contrib/systemd/origin-accounting.conf
Labels: approved, kind/bug, lgtm, sig/pod, size/XS

#22291 UPSTREAM: 75223: kubelet: include init containers when determining pod QoS
  vendor/k8s.io/kubernetes/pkg/apis/core/helper/qos/qos.go
  vendor/k8s.io/kubernetes/pkg/apis/core/v1/helper/qos/qos.go
  vendor/k8s.io/kubernetes/pkg/apis/core/v1/helper/qos/qos_test.go
Labels: approved, kind/bug, lgtm, size/M

#22292 UPSTREAM: 75264: Optimize authorization service account check
  vendor/k8s.io/kubernetes/pkg/registry/rbac/validation/rule.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/authentication/serviceaccount/util.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/authentication/serviceaccount/util_test.go
Labels: approved, lgtm, size/M

#22247 Fix example flake
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/examples/fake-client/main_test.go
Labels: approved, lgtm, size/S

#22207 Bug 1682978: Verify builder version is reported
  test/extended/builds/start.go
Labels: approved, lgtm, size/XS

#22270 Remove stale skydns/dnsmasq DNS implementation
  docs/openshift_networking_requirements.md
  glide.lock
  glide.yaml
  pkg/dns/OWNERS
  pkg/dns/dnsmasq.go
  pkg/dns/dnsmasq_test.go
  pkg/dns/server.go
  pkg/dns/serviceaccessor.go
  pkg/dns/serviceresolver.go
  tools/rebasehelpers/godepchecker/godepchecker.go
  vendor/github.com/skynetservices/skydns/.gitignore
  vendor/github.com/skynetservices/skydns/.travis.yml
  vendor/github.com/skynetservices/skydns/AUTHORS
  vendor/github.com/skynetservices/skydns/CONTRIBUTORS
  vendor/github.com/skynetservices/skydns/Dockerfile
  vendor/github.com/skynetservices/skydns/LICENSE
  vendor/github.com/skynetservices/skydns/README.md
  vendor/github.com/skynetservices/skydns/backends/etcd/etcd.go
  vendor/github.com/skynetservices/skydns/cache/cache.go
  vendor/github.com/skynetservices/skydns/cache/cache_test.go
  vendor/github.com/skynetservices/skydns/cache/hit.go
  vendor/github.com/skynetservices/skydns/main.go
  vendor/github.com/skynetservices/skydns/metrics/metrics.go
  vendor/github.com/skynetservices/skydns/msg/service.go
  vendor/github.com/skynetservices/skydns/msg/service_test.go
  vendor/github.com/skynetservices/skydns/server/backend.go
  vendor/github.com/skynetservices/skydns/server/cache_test.go
  vendor/github.com/skynetservices/skydns/server/config.go
  vendor/github.com/skynetservices/skydns/server/dnssec.go
  vendor/github.com/skynetservices/skydns/server/doc.go
  vendor/github.com/skynetservices/skydns/server/exchange.go
  vendor/github.com/skynetservices/skydns/server/forwarding.go
  vendor/github.com/skynetservices/skydns/server/log.go
  vendor/github.com/skynetservices/skydns/server/metrics_test.go
  vendor/github.com/skynetservices/skydns/server/msg.go
  vendor/github.com/skynetservices/skydns/server/nsec3.go
  vendor/github.com/skynetservices/skydns/server/server.go
  vendor/github.com/skynetservices/skydns/server/server_test.go
  vendor/github.com/skynetservices/skydns/server/stub.go
  vendor/github.com/skynetservices/skydns/singleflight/singleflight.go
Labels: approved, lgtm, sig/network-edge, size/XXL

#22283 sdn: clarify SDN startup log message
  pkg/network/node/node.go
Labels: approved, lgtm, size/S

#22124 Cleanup fixture reading in extended tests
  test/extended/deployments/deployments.go
  test/extended/deployments/util.go
  test/extended/scheme/install.go
  test/extended/scheme/scheme.go
  test/extended/util/manifest.go
  test/extended/util/manifest_test.go
Labels: approved, lgtm, sig/master, size/L

#22024 UPSTREAM: 72980: Fix Cinder volume limits
  vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/predicates/max_attachable_volume_predicate_test.go
  vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/predicates/predicates.go
  vendor/k8s.io/kubernetes/pkg/scheduler/algorithmprovider/defaults/compatibility_test.go
  vendor/k8s.io/kubernetes/pkg/scheduler/algorithmprovider/defaults/defaults.go
  vendor/k8s.io/kubernetes/pkg/scheduler/factory/factory.go
  vendor/k8s.io/kubernetes/pkg/volume/cinder/cinder.go
  vendor/k8s.io/kubernetes/pkg/volume/util/attach_limit.go
Labels: approved, lgtm, size/L

#22153 UPSTREAM: 70647: Always run untag when removing docker image
  vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/docker_image.go
  vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/docker_image_test.go
  vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/libdocker/fake_client.go
Labels: approved, lgtm, size/L

#22154 UPSTREAM: 70647: Always run untag when removing docker image
  vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/docker_image.go
  vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/docker_image_test.go
  vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/libdocker/fake_client.go
Labels: approved, lgtm, size/L

#22273 Simplify the host root message
  pkg/oc/cli/debug/debug.go
Labels: approved, lgtm, size/XS

#22278 Add build-all target to Makefile
  Makefile
Labels: approved, lgtm, size/S

#22192 Bug 1590743 - Include all webhook types when listing all
  pkg/oc/cli/startbuild/startbuild.go
  test/cmd/builds.sh
Labels: approved, lgtm, size/M

#22309 sdn: clarify SDN startup log message
  pkg/network/node/node.go
Labels: approved, lgtm, size/S

#21989 UPSTREAM: 72980: Fix Cinder volume limits
  vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/predicates/max_attachable_volume_predicate_test.go
  vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/predicates/predicates.go
  vendor/k8s.io/kubernetes/pkg/scheduler/algorithmprovider/defaults/compatibility_test.go
  vendor/k8s.io/kubernetes/pkg/scheduler/algorithmprovider/defaults/defaults.go
  vendor/k8s.io/kubernetes/pkg/scheduler/factory/factory.go
  vendor/k8s.io/kubernetes/pkg/volume/cinder/cinder.go
  vendor/k8s.io/kubernetes/pkg/volume/util/attach_limit.go
Labels: approved, lgtm, sig/storage, size/L

#22311 kube-apiserver: delete CRD validation from default off plugin list
  pkg/cmd/openshift-kube-apiserver/kubeadmission/register.go
Labels: approved, lgtm, size/XS

#22302 OVS flows go missing during upgrade
  pkg/network/node/multitenant.go
  pkg/network/node/networkpolicy.go
  pkg/network/node/ovscontroller.go
  pkg/network/node/ovscontroller_test.go
Labels: approved, component/networking, kind/bug, lgtm, sig/networking, size/M

#22305 Make it easier to see how old images are for freshness
  pkg/oc/cli/admin/release/info.go
Labels: approved, lgtm, size/S

#22308 UPSTREAM: 75213: Make mount and unmount op. have different name
  vendor/k8s.io/kubernetes/pkg/volume/util/nestedpendingoperations/BUILD
  vendor/k8s.io/kubernetes/pkg/volume/util/nestedpendingoperations/nestedpendingoperations.go
  vendor/k8s.io/kubernetes/pkg/volume/util/nestedpendingoperations/nestedpendingoperations_test.go
  vendor/k8s.io/kubernetes/pkg/volume/util/operationexecutor/operation_generator.go
  vendor/k8s.io/kubernetes/pkg/volume/util/types/types.go
Labels: approved, lgtm, sig/storage, size/L

#22315 Revert NetworkPolicy cleanup
  pkg/network/node/networkpolicy.go
Labels: approved, component/networking, kind/bug, lgtm, sig/networking, size/S

#22303 Fix bug 1278683 for 3.11
  pkg/oc/lib/describe/describer.go
Labels: approved, lgtm, size/S

#22297 imagepolicy: remove legacy oapi
  pkg/image/apiserver/admission/apis/imagepolicy/v1/default-policy.yaml
  pkg/image/apiserver/admission/apis/imagepolicy/v1/defaults.go
  pkg/image/apiserver/admission/imagepolicy/imagepolicy.go
  pkg/image/apiserver/admission/imagepolicy/imagepolicy_test.go
Labels: approved, lgtm, size/L

#22203 Bug 1683819 - allow empty selector
  pkg/util/labelselector/labelselector.go
  pkg/util/labelselector/labelselector_test.go
Labels: approved, lgtm, size/S

#22255 UPSTREAM: 71713: Plumb token and token file through rest.Config
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/util/webhook/authentication.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/rest/BUILD
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/rest/config.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/rest/config_test.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/clientcmd/client_config.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/transport/BUILD
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/transport/config.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/transport/round_trippers.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/transport/token_source.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/transport/token_source_test.go
Labels: approved, lgtm, size/M

#22323 add 1.13.4 sync rules
  publishing-kube-rules.yaml
Labels: approved, size/L

#22313 UPSTREAM: 75399: apiextensions: merge OpenAPI specs once after cache sync
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/controller/openapi/controller.go
Labels: approved, lgtm, size/M

#22317 Mirroring a new payload should rewrite payload image references
  pkg/oc/cli/admin/release/image_mapper.go
  pkg/oc/cli/admin/release/new.go
  pkg/oc/cli/image/mirror/mirror.go
Labels: approved, lgtm, size/L

#22327 switch unidling to external API
  pkg/cmd/openshift-controller-manager/controller/unidling.go
  pkg/oc/cli/idle/idle.go
  pkg/unidling/controller/unidling_controller.go
  pkg/unidling/controller/unidling_controller_test.go
  pkg/unidling/util/scale.go
Labels: approved, lgtm, sig/network-edge, size/L

#22328 switch project auth cache to external types
  pkg/cmd/openshift-apiserver/openshiftapiserver/config.go
  pkg/cmd/openshift-apiserver/openshiftapiserver/project.go
  pkg/project/apiserver/apiserver.go
  pkg/project/apiserver/registry/project/proxy/proxy.go
  pkg/project/apiserver/registry/project/proxy/proxy_test.go
  pkg/project/auth/cache.go
  pkg/project/auth/cache_test.go
  pkg/project/auth/watch.go
  pkg/project/auth/watch_test.go
  pkg/project/util/util.go
  pkg/project/util/util_test.go
Labels: approved, lgtm, size/L

#22322 apiserver: add /readyz endpoint
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/healthz.go
Labels: approved, lgtm, size/M

#22326 switch network to use external clients
  pkg/cmd/openshift-sdn/informers.go
  pkg/cmd/openshift-sdn/proxy.go
  pkg/cmd/openshift-sdn/sdn.go
  pkg/network/node/multitenant.go
  pkg/network/node/networkpolicy.go
  pkg/network/node/node.go
  pkg/network/node/ovscontroller.go
  pkg/network/node/ovscontroller_test.go
  pkg/network/node/pod.go
  pkg/network/node/sdn_controller.go
  pkg/network/proxy/proxy.go
Labels: approved, lgtm, sig/networking, size/L

#22329 switch scheduling.openshift.io/OriginPodNodeEnvironment to external client
  pkg/scheduler/admission/nodeenv/admission.go
  pkg/scheduler/admission/nodeenv/admission_test.go
Labels: approved, lgtm, sig/pod, size/S

#22334 switch security/apiserver to external client
  pkg/cmd/openshift-apiserver/openshiftapiserver/openshift_apiserver.go
  pkg/security/apiserver/admission/sccadmission/admission.go
  pkg/security/apiserver/admission/sccadmission/admission_test.go
  pkg/security/apiserver/admission/sccadmission/scc_exec.go
  pkg/security/apiserver/admission/sccadmission/scc_exec_test.go
  pkg/security/apiserver/admission/testing/util.go
  pkg/security/apiserver/apiserver.go
  pkg/security/apiserver/registry/podsecuritypolicyreview/rest.go
  pkg/security/apiserver/registry/podsecuritypolicyreview/rest_test.go
  pkg/security/apiserver/registry/podsecuritypolicyselfsubjectreview/rest.go
  pkg/security/apiserver/registry/podsecuritypolicyselfsubjectreview/rest_test.go
  pkg/security/apiserver/registry/podsecuritypolicysubjectreview/rest.go
  pkg/security/apiserver/registry/podsecuritypolicysubjectreview/rest_test.go
  pkg/security/apiserver/securitycontextconstraints/matcher.go
  pkg/security/apiserver/securitycontextconstraints/matcher_test.go
  pkg/security/securitycontextconstraints/user/util.go
Labels: approved, lgtm, size/XL

#22319 Improve error output in upgrades
  test/e2e/upgrade/upgrade.go
  vendor/k8s.io/kubernetes/test/e2e/framework/networking_utils.go
Labels: approved, lgtm, size/M

#22259 Generate kube OpenAPI spec from hack/update-generated-openapi.sh
  hack/update-generated-openapi.sh
  vendor/k8s.io/kubernetes/hack/openapi-violation.list
  vendor/k8s.io/kubernetes/pkg/generated/openapi/zz_generated.openapi.go
Labels: approved, lgtm, size/L

#22335 switch quota to external clients
  pkg/cmd/openshift-apiserver/openshiftapiserver/openshift_apiserver.go
  pkg/quota/apiserver/admission/clusterresourcequota/accessor.go
  pkg/quota/apiserver/admission/clusterresourcequota/accessor_test.go
  pkg/quota/apiserver/admission/clusterresourcequota/admission.go
  pkg/quota/apiserver/apiserver.go
  pkg/quota/apiserver/registry/appliedclusterresourcequota/filter.go
Labels: approved, lgtm, sig/master, size/L

#22330 remove internal client dependency from apps server
  pkg/apps/apis/apps/internaltest/internal.go
  pkg/apps/apiserver/apiserver.go
  pkg/apps/apiserver/registry/instantiate/rest.go
  pkg/apps/apiserver/registry/instantiate/rest_test.go
  pkg/apps/apiserver/registry/rollback/rest.go
  pkg/apps/apiserver/registry/rollback/rest_test.go
Labels: approved, lgtm, sig/master, size/L

#22338 network: fix conversion when handling network policy delete
  pkg/network/node/networkpolicy.go
Labels: approved, lgtm, size/XS

#22343 switch oc to external clients where possible
  pkg/oc/cli/rollout/latest.go
  pkg/oc/cli/rsh/rsh.go
  pkg/oc/cli/rsync/forwarder.go
  pkg/oc/cli/set/volume.go
  pkg/oc/cli/set/volume_test.go
Labels: approved, lgtm, size/L

#22339 switch to external limitranger
  pkg/autoscaling/admission/clusterresourceoverride/admission.go
  pkg/autoscaling/admission/clusterresourceoverride/admission_test.go
  pkg/cmd/openshift-apiserver/openshiftapiserver/config.go
  pkg/cmd/openshift-apiserver/openshiftapiserver/openshift_apiserver.go
  pkg/image/apiserver/admission/limitrange/admission.go
  pkg/image/apiserver/admission/limitrange/admission_test.go
  pkg/image/apiserver/admission/limitrange/imagestream_limits.go
  pkg/image/apiserver/admission/limitrange/imagestream_limits_test.go
  pkg/image/apiserver/admission/limitrange/usage.go
  pkg/image/apiserver/admission/limitrange/usage_test.go
  pkg/image/apiserver/apiserver.go
  pkg/image/apiserver/registry/imagestream/etcd/etcd.go
  pkg/image/apiserver/registry/imagestream/etcd/etcd_test.go
  pkg/image/apiserver/registry/imagestream/etcd/limit_verifier.go
  pkg/image/apiserver/registry/imagestream/strategy_test.go
  pkg/image/apiserver/registry/imagestreamimage/rest_test.go
  pkg/image/apiserver/registry/imagestreammapping/rest_test.go
  pkg/image/apiserver/registry/imagestreamtag/rest_test.go
  vendor/k8s.io/kubernetes/plugin/pkg/admission/limitranger/BUILD
  vendor/k8s.io/kubernetes/plugin/pkg/admission/limitranger/admission.go
  vendor/k8s.io/kubernetes/plugin/pkg/admission/limitranger/admission_test.go
  vendor/k8s.io/kubernetes/plugin/pkg/admission/limitranger/interfaces.go
Labels: approved, lgtm, sig/developer-experience, sig/pod, size/XXL

#22340 use external clients for authorization admission
  pkg/authorization/apiserver/admission/restrictusers/restrictusers.go
  pkg/authorization/apiserver/admission/restrictusers/restrictusers_test.go
  pkg/authorization/apiserver/admission/restrictusers/subjectchecker.go
  pkg/authorization/apiserver/admission/restrictusers/subjectchecker_test.go
Labels: approved, lgtm, size/M

#22341 remove internal types from projectrequest
  pkg/cmd/openshift-apiserver/openshiftapiserver/openshift_apiserver.go
  pkg/project/apiserver/apiserver.go
  pkg/project/apiserver/registry/projectrequest/delegated/delegated.go
  pkg/project/apiserver/registry/projectrequest/delegated/delegated_test.go
Labels: approved, lgtm, size/M

#22349 remove internal clients from controller-manager
  pkg/cmd/openshift-controller-manager/controller/interfaces.go
Labels: approved, lgtm, size/M

#22310 Add label selector support for oc observe command
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/oc/cli/observe/observe.go
Labels: approved, lgtm, ok-to-test, size/S

#22307 add some more dump of jenkins pod logs on e2e test failures
  test/extended/builds/pipeline_origin_bld.go
Labels: approved, lgtm, sig/developer-experience, size/S

#22342 switch image rest API to external client
  pkg/image/apiserver/apiserver.go
  pkg/image/apiserver/registry/imagesecret/rest.go
  pkg/image/apiserver/registry/imagesecret/rest_test.go
Labels: approved, lgtm, sig/developer-experience, size/M

#22347 Update authorization to RBAC proxy registry to use external clients
  pkg/authorization/apiserver/registry/clusterrole/proxy.go
  pkg/authorization/apiserver/registry/clusterrolebinding/proxy.go
  pkg/authorization/apiserver/registry/role/proxy.go
  pkg/authorization/apiserver/registry/rolebinding/proxy.go
  pkg/authorization/apiserver/registry/util/convert.go
  pkg/build/apiserver/admission/secretinjector/admission.go
  pkg/client/impersonatingclient/impersonate.go
  pkg/client/impersonatingclient/impersonate_rbac.go
  test/integration/authorization_rbac_proxy_test.go
Labels: approved, lgtm, size/XL

#22348 Support mirroring a release to an image stream
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/oc/cli/admin/release/mirror.go
  pkg/oc/cli/image/mirror/mappings.go
Labels: approved, lgtm, size/L

#22355 UPSTREAM: 75368: handle apiserver is shutting down errors
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/filters/BUILD
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/filters/waitgroup.go
Labels: approved, lgtm, size/S

#22316 UPSTREAM: 00000: debug wedged openshift api cert reload
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/certs/clientca.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/certs/serving.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/certs/single_certkey_pair.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/certs/util.go
Labels: approved, lgtm, size/M

#22361 UPSTREAM: 75368: fix content-type for apiserver shutdown error
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/filters/waitgroup.go
Labels: approved, lgtm, size/XS

#22366 [release-3.11] Clear conntrack entries for externalIPs
  vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go
  vendor/k8s.io/kubernetes/pkg/proxy/ipvs/proxier.go
  vendor/k8s.io/kubernetes/pkg/proxy/service.go
  vendor/k8s.io/kubernetes/pkg/proxy/types.go
Labels: approved, lgtm, size/S

#22108 SDN test image for QE testing with ovs-2.11.0
  images/sdn/Dockerfile.rhel
Labels: approved, lgtm, size/XS

#22177 [release 3.11] UPSTREAM: 66617: Do not set cgroup parent when --cgroups-per-qos is disabled
  vendor/k8s.io/kubernetes/pkg/kubelet/cm/pod_container_manager_linux.go
Labels: approved, lgtm, size/XS

#22367 [release-3.10] Clear conntrack entries for externalIPs
  vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go
  vendor/k8s.io/kubernetes/pkg/proxy/ipvs/proxier.go
  vendor/k8s.io/kubernetes/pkg/proxy/service.go
  vendor/k8s.io/kubernetes/pkg/proxy/types.go
Labels: approved, lgtm, size/S

#22362 cmd/sdn-cni-plugin: add OWNERS file
  cmd/sdn-cni-plugin/OWNERS
Labels: approved, lgtm, size/S

#22359 UPSTREAM: 75144: kubelet: updated logic of verifying a static critical pod
  vendor/k8s.io/kubernetes/pkg/kubelet/eviction/eviction_manager.go
  vendor/k8s.io/kubernetes/pkg/kubelet/eviction/eviction_manager_test.go
  vendor/k8s.io/kubernetes/pkg/kubelet/eviction/types.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_test.go
  vendor/k8s.io/kubernetes/pkg/kubelet/runonce_test.go
Labels: approved, lgtm, size/M

#21975 Support CNI 0.3.x in openshift-sdn
  cmd/sdn-cni-plugin/openshift-sdn_linux.go
  cmd/sdn-cni-plugin/sdn_cni_plugin_test.go
  pkg/network/node/node.go
  pkg/network/node/pod.go
Labels: approved, lgtm, ok-to-test, size/L

#22368 switch idling to use the generic scale client
  pkg/apps/client/v1/scale.go
  pkg/cmd/openshift-controller-manager/controller/unidling.go
  pkg/oc/cli/idle/idle.go
  pkg/oc/cli/idle/idle_test.go
  pkg/unidling/controller/unidling_controller.go
  pkg/unidling/controller/unidling_controller_test.go
  pkg/unidling/util/scale.go
Labels: approved, sig/monitoring, size/L

#22356 UPSTREAM: 74902: Update generated protobuf files
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.pb.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.proto
Labels: approved, lgtm, priority/critical-urgent, queue/critical-fix, size/XS

#22370 Confirm escalation is not possible via authorization to RBAC proxy
  test/integration/authorization_rbac_proxy_test.go
Labels: approved, lgtm, size/L

#22351 Make the release image vary only by inputs
  pkg/oc/cli/admin/release/new.go
Labels: approved, lgtm, size/L

#22333 Check the payload for real Kube objects before accepting
  pkg/oc/cli/admin/release/new.go
Labels: approved, lgtm, size/S

#22373 Refactor UserFor helper to ResponseFor
  pkg/oauthserver/authenticator/identitymapper/identitymapper.go
  pkg/oauthserver/authenticator/password/allowanypassword/anyauthpassword.go
  pkg/oauthserver/authenticator/password/basicauthpassword/basicauthpassword.go
  pkg/oauthserver/authenticator/password/htpasswd/htpasswd.go
  pkg/oauthserver/authenticator/password/keystonepassword/keystonepassword.go
  pkg/oauthserver/authenticator/password/ldappassword/ldap.go
  pkg/oauthserver/authenticator/request/headerrequest/requestheader.go
  pkg/oauthserver/oauth/external/handler.go
Labels: approved, lgtm, size/M

#22374 stop using a carry on FIFO queue to observe pods
  pkg/apps/strategy/support/lifecycle.go
Labels: approved, lgtm, size/L

#22380 Fetch alternate repos for commits on release extraction
  pkg/oc/cli/admin/release/extract.go
  pkg/oc/cli/admin/release/git.go
  pkg/oc/cli/admin/release/info.go
Labels: approved, lgtm, size/L

#22357 hack/cherry-pick.sh: switch to glide.yaml
  hack/cherry-pick.sh
Labels: approved, lgtm, size/S

#22379 [3.11] hack: make verify commits work against correct branch
  hack/verify-upstream-commits.sh
Labels: approved, lgtm, size/XS

#22156 e2e: Add conformance test to verify cluster operators have versions
  test/extended/operators/operators.go
Labels: approved, lgtm, size/M

#22365 oc: remove unnecessary conversion
  pkg/oc/cli/cancelbuild/cancelbuild.go
  pkg/oc/cli/rollback/rollback.go
  pkg/oc/cli/rollout/cancel.go
  pkg/oc/cli/rollout/latest.go
  pkg/oc/cli/rollout/retry.go
  pkg/oc/cli/set/env.go
  pkg/oc/cli/set/volume.go
  pkg/oc/cli/set/volume_test.go
Labels: approved, lgtm, size/M

#22388 Bug 1673806: build - support UTF-8 filenames in binary builds
  pkg/build/controller/strategy/custom.go
  pkg/build/controller/strategy/custom_test.go
  pkg/build/controller/strategy/docker.go
  pkg/build/controller/strategy/docker_test.go
  pkg/build/controller/strategy/sti.go
  pkg/build/controller/strategy/sti_test.go
  pkg/build/util/consts.go
  pkg/build/util/util_test.go
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/test-build-app/utf8_tést_app.rb
Labels: approved, lgtm, size/L

#22390 UPSTREAM: 75335: test/e2e: fix PreemptionExecutionPath nodeSelector
  vendor/k8s.io/kubernetes/test/e2e/scheduling/preemption.go
Labels: approved, lgtm, size/L

#22382 switch integration tests to external kubeclient
  pkg/scheduler/admission/podnodeconstraints/admission.go
  test/extended/image_ecosystem/mysql_replica.go
  test/extended/image_ecosystem/postgresql_replica.go
  test/extended/imageapis/quota_admission.go
  test/integration/admissionconfig_test.go
  test/integration/aggregator_test.go
  test/integration/audit_test.go
  test/integration/authorization_test.go
  test/integration/build_admission_test.go
  test/integration/buildcontroller_test.go
  test/integration/buildpod_admission_test.go
  test/integration/clusterquota_test.go
  test/integration/clusterresourceoverride_admission_test.go
  test/integration/deploy_trigger_test.go
  test/integration/discovery_test.go
  test/integration/endpoint_admission_test.go
  test/integration/extension_apiserver_test.go
  test/integration/extensions_api_deletion_test.go
  test/integration/extensions_api_disabled_test.go
  test/integration/imagechange_buildtrigger_test.go
  test/integration/imageimporter_test.go
  test/integration/imagesigning_test.go
  test/integration/imagestream_admission_test.go
  test/integration/master_routes_test.go
  test/integration/metrics_test.go
  test/integration/namespace_lifecycle_admission_test.go
  test/integration/node_authorizer_test.go
  test/integration/oauth_disabled_test.go
  test/integration/oauth_serviceaccount_client_events_test.go
  test/integration/oauth_serviceaccount_client_test.go
  test/integration/ownerrefs_test.go
  test/integration/patch_test.go
  test/integration/pod_node_constraints_test.go
  test/integration/project_reqlimit_test.go
  test/integration/project_request_test.go
  test/integration/project_test.go
  test/integration/restrictusers_test.go
  test/integration/runonce_duration_test.go
  test/integration/scc_test.go
  test/integration/service_account_test.go
  test/integration/storage_versions_test.go
  test/integration/unprivileged_newproject_test.go
  test/integration/watch_cache_test.go
  test/integration/webhook_test.go
  test/util/client.go
  test/util/namespace.go
  test/util/policy.go
  test/util/server/server.go
  vendor/k8s.io/kubernetes/pkg/quota/v1/resources.go
Labels: approved, lgtm, size/XXL

#22395 UPSTREAM: 00000: fix closure error when calling cert rotation Run func
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/options/authentication.go
Labels: approved, lgtm, priority/critical-urgent, queue/critical-fix, size/XS

#22230 extended: validate release image used and image pull policy
  test/extended/operators/images.go
Labels: approved, lgtm, size/M

#22377 bump(*): pick cadvisor fix
  glide.lock
  glide.yaml
  vendor/github.com/containers/image/openshift/openshift.go
  vendor/github.com/docker/docker/pkg/archive/archive_unix.go
  vendor/github.com/docker/docker/pkg/archive/changes_linux.go
  vendor/github.com/docker/docker/pkg/signal/signal_linux.go
  vendor/github.com/docker/docker/pkg/system/mknod.go
  vendor/github.com/docker/docker/vendor.conf
  vendor/github.com/google/cadvisor/metrics/prometheus.go
  vendor/github.com/openshift/imagebuilder/dockerclient/client.go
  vendor/github.com/vmware/photon-controller-go-sdk/photon/client.go
  vendor/github.com/vmware/photon-controller-go-sdk/photon/deployments_test.go
  vendor/github.com/vmware/photon-controller-go-sdk/photon/lightwave/oidcclient_test.go
Labels: approved, lgtm, size/M

#22386 Bug 1691857: Use protobuf from kubelet to retrieve resources, not just send them
  vendor/k8s.io/kubernetes/cmd/kubelet/app/server.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/runtime/types.go
Labels: approved, lgtm, size/M

#22399 bootstrap-policy: add /readyz to system:discovery
  vendor/k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go
  vendor/k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/cluster-roles.yaml
Labels: approved, lgtm, size/XS

#22402 extended: exit early if unable to read release payload
  test/extended/operators/images.go
Labels: approved, lgtm, size/XS

#22401 UPSTREAM: <carry>: bootstrap-policy: add /readyz system:openshift:public-info-viewer policy
  vendor/k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go
  vendor/k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/cluster-role-bindings.yaml
  vendor/k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/cluster-roles.yaml
Labels: approved, lgtm, size/M

#22061 Retry when checking prometheus working target for router-internal-default job
  test/extended/router/metrics.go
Labels: approved, lgtm, sig/network-edge, size/S

#22376 change the sdn pod to run the iptables command on the host
  images/sdn/Dockerfile.rhel
  images/sdn/scripts/ip6tables
  images/sdn/scripts/ip6tables-restore
  images/sdn/scripts/ip6tables-save
  images/sdn/scripts/iptables
  images/sdn/scripts/iptables-restore
  images/sdn/scripts/iptables-save
Labels: approved, lgtm, size/S

#22398 UPSTREAM: <carry>: allow running bare kube-controller-manager
  vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go
  vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/patch.go
  vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/patch_flags.go
Labels: approved, lgtm, size/M
