Repository openshift/origin, pull requests merged in 2019-05, with the labels that each got.

#22722 oc adm release info diff should output JSON for the user
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/oc/cli/admin/release/info.go
Labels: approved, lgtm, size/M

#22723 UPSTREAM: <carry>: test/e2e: increase timeout for pod readiness test
  vendor/k8s.io/kubernetes/test/e2e/common/pods.go
Labels: approved, lgtm, size/XS

#22706 e2e must-gather disable check for file sizes
  test/extended/cli/mustgather.go
Labels: approved, lgtm, size/XS

#22711 UPSTREAM: <carry>: Always test PDB's during service upgrade test
  vendor/k8s.io/kubernetes/test/e2e/upgrades/services.go
Labels: approved, lgtm, size/XS

#22712 Ignore pending pods with running init containers when trying to detect crash loops
  test/extended/operators/cluster.go
Labels: approved, lgtm, size/S

#22714 Bug 1704570: Include kubectl in extracted tools with a readme and streamline oc help
  pkg/oc/cli/admin/release/extract_tools.go
  pkg/oc/cli/cli.go
  pkg/oc/cli/requestproject/request_project.go
Labels: approved, lgtm, size/L

#22715 UPSTREAM: 75110: Send events before adding watchers in traversePluginDir
  vendor/k8s.io/kubernetes/pkg/kubelet/util/pluginwatcher/BUILD
  vendor/k8s.io/kubernetes/pkg/kubelet/util/pluginwatcher/plugin_watcher.go
  vendor/k8s.io/kubernetes/pkg/kubelet/util/pluginwatcher/plugin_watcher_test.go
Labels: approved, lgtm, size/M

#22696 Migrate oc explain tests to extended
  test/cmd/explain.sh
  test/extended/cli/explain.go
Labels: approved, lgtm, size/L

#22697 Bug 1703595: oauth/user/authz: tighten API validation checks
  pkg/apiserver/authentication/oauth/tokenauthenticator.go
  pkg/authorization/authorizer/scope/converter.go
  pkg/authorization/authorizer/scope/validate_test.go
  pkg/oauth/apis/oauth/validation/validation.go
  pkg/oauth/apis/oauth/validation/validation_test.go
  pkg/oauth/apiserver/registry/oauthclientauthorization/strategy_test.go
  pkg/oauthserver/ldaputil/identityfactory.go
  pkg/user/apis/user/validation/validation.go
  pkg/user/apis/user/validation/validation_test.go
  pkg/user/apiserver/registry/user/strategy.go
  test/integration/etcd_storage_path_test.go
  test/integration/groups_test.go
  test/integration/oauth_ldap_test.go
  test/integration/oauth_serviceaccount_client_test.go
  test/integration/oauthstorage_test.go
  test/integration/scopes_test.go
  test/testdata/oauthaccesstoken.yaml
  test/util/client.go
Labels: approved, lgtm, size/XL

#22728 Bug 1703506: Move OAuth server to standard handler chain
  pkg/cmd/openshift-integrated-oauth-server/server.go
  pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/patch_oauthserver.go
  pkg/oauthserver/oauthserver/oauth_apiserver.go
  pkg/oauthserver/server/headers/oauthbasic.go
Labels: approved, lgtm, size/M

#22727 [release-3.11] Don't send identical SAR checks on ImageStream creation
  pkg/image/apiserver/registry/imagestream/strategy.go
  pkg/image/apiserver/registry/imagestream/strategy_test.go
Labels: approved, lgtm, size/L

#22717 UPSTREAM: 76788: Clean links handling in cp's tar code
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cp/BUILD
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cp/cp.go
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cp/cp_test.go
Labels: approved, lgtm, size/L

#22732 SCC bootstrapping must not return until it has created all defaults
  hack/local-up-master/lib.sh
  pkg/cmd/openshift-apiserver/openshiftapiserver/openshift_apiserver.go
  test/util/server/server.go
Labels: approved, lgtm, size/M

#22661 test/extended/prometheus: Add etcd target check
  test/extended/prometheus/prometheus.go
Labels: approved, lgtm, size/XS

#22707 Simplify pod node constraints
  pkg/cmd/openshift-apiserver/openshiftadmission/register.go
  pkg/image/apiserver/admission/imagepolicy/accept.go
  pkg/image/apiserver/admission/imagepolicy/imagepolicy.go
  pkg/image/apiserver/admission/imagepolicy/internalimagereferencemutators/builds.go
  pkg/image/apiserver/admission/imagepolicy/internalimagereferencemutators/builds_test.go
  pkg/image/apiserver/admission/imagepolicy/internalimagereferencemutators/meta.go
  pkg/image/apiserver/admission/imagepolicy/internalimagereferencemutators/pods.go
  pkg/image/apiserver/admission/imagepolicy/internalimagereferencemutators/pods_test.go
  pkg/scheduler/admission/podnodeconstraints/admission.go
  pkg/scheduler/admission/podnodeconstraints/admission_test.go
  test/integration/pod_node_constraints_test.go
Labels: approved, lgtm, size/L

#22730 Remove /healthz/* from bootstrap RBAC
  pkg/cmd/server/bootstrappolicy/policy.go
  test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml
  test/testdata/bootstrappolicy/bootstrap_policy_file.yaml
Labels: approved, lgtm, sig/master, size/XS

#22720 Allow extra tolerations in buildpod admission test
  test/integration/buildpod_admission_test.go
Labels: approved, lgtm, size/M

#22740 UPSTREAM: 76184: Use pvc uid in endpoint/service label
  vendor/k8s.io/kubernetes/pkg/volume/glusterfs/glusterfs.go
Labels: approved, lgtm, size/S

#22718 UPSTREAM: 76788: Clean links handling in cp's tar code
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cp.go
  vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cp_test.go
Labels: approved, lgtm, size/XL

#22609 Fix up SDN CNIServer startup security logic
  pkg/network/node/cniserver/cniserver.go
  pkg/network/node/cniserver/cniserver_test.go
Labels: approved, lgtm, size/L

#22738 Update conformance-k8s.sh to 1.13
  test/extended/conformance-k8s.sh
Labels: approved, lgtm, size/XS

#22737 add minimal SCC changes to switch to CRD
  hack/local-up-master/kube-apiserver-manifests/01_security_context_constraint_crd.yaml
  hack/local-up-master/lib.sh
  pkg/admission/customresourcevalidation/attributes.go
  pkg/admission/customresourcevalidation/customresourcevalidationregistration/cr_validation_registration.go
  pkg/admission/customresourcevalidation/securitycontextconstraints/defaulting_scc.go
  pkg/admission/customresourcevalidation/securitycontextconstraints/defaulting_scc_test.go
  pkg/cmd/openshift-apiserver/openshiftapiserver/openshift_apiserver.go
  pkg/cmd/openshift-kube-apiserver/server.go
  pkg/security/apiserver/apiserver.go
  pkg/security/apiserver/registry/securitycontextconstraints/doc.go
  pkg/security/apiserver/registry/securitycontextconstraints/etcd/etcd.go
  pkg/security/apiserver/registry/securitycontextconstraints/etcd/etcd_test.go
  pkg/security/apiserver/registry/securitycontextconstraints/etcd/shim_storage.go
  pkg/security/apiserver/registry/securitycontextconstraints/strategy.go
  pkg/security/apiserver/registry/securitycontextconstraints/strategy_test.go
  test/integration/etcd_storage_path_test.go
  test/util/client.go
  test/util/server/server.go
Labels: approved, lgtm, size/XL

#21922 Add validation for Authentication and OAuth CRs
  hack/import-restrictions.json
  pkg/admission/customresourcevalidation/oauth/helpers.go
  pkg/admission/customresourcevalidation/oauth/validate_github.go
  pkg/admission/customresourcevalidation/oauth/validate_github_test.go
  pkg/admission/customresourcevalidation/oauth/validate_gitlab.go
  pkg/admission/customresourcevalidation/oauth/validate_gitlab_test.go
  pkg/admission/customresourcevalidation/oauth/validate_google.go
  pkg/admission/customresourcevalidation/oauth/validate_google_test.go
  pkg/admission/customresourcevalidation/oauth/validate_idp.go
  pkg/admission/customresourcevalidation/oauth/validate_idp_test.go
  pkg/admission/customresourcevalidation/oauth/validate_keystone.go
  pkg/admission/customresourcevalidation/oauth/validate_keystone_test.go
  pkg/admission/customresourcevalidation/oauth/validate_ldap.go
  pkg/admission/customresourcevalidation/oauth/validate_ldap_test.go
  pkg/admission/customresourcevalidation/oauth/validate_oauth.go
  pkg/admission/customresourcevalidation/oauth/validate_openid.go
  pkg/admission/customresourcevalidation/oauth/validate_openid_test.go
  pkg/admission/customresourcevalidation/oauth/validate_requestheader.go
  pkg/admission/customresourcevalidation/oauth/validate_requestheader_test.go
Labels: approved, lgtm, size/XXL

#22724 Improve error when SCC admission fails to create SecurityContextConstraintsProvider
  pkg/security/apiserver/admission/sccadmission/admission.go
Labels: approved, lgtm, size/S

#22588 Enable unidling tests
  pkg/unidling/controller/unidling_controller_test.go
Labels: approved, lgtm, size/L

#22726 Support --option on upgrade tests to abort in progress
  cmd/openshift-tests/openshift-tests.go
  cmd/openshift-tests/upgrade.go
  pkg/test/ginkgo/cmd_runsuite.go
  pkg/test/ginkgo/status.go
  pkg/test/ginkgo/test.go
  test/e2e/upgrade/monitor.go
  test/e2e/upgrade/upgrade.go
Labels: approved, lgtm, size/XL

#22744 Bug 1705627: Add --show-console flag to whoami command
  contrib/completions/bash/oc
  contrib/completions/zsh/oc
  pkg/oc/cli/whoami/whoami.go
  test/cmd/whoami.sh
Labels: approved, lgtm, size/M

#22746 add SCC validation plugin
  pkg/admission/customresourcevalidation/customresourcevalidationregistration/cr_validation_registration.go
  pkg/admission/customresourcevalidation/securitycontextconstraints/validate_scc.go
  pkg/admission/customresourcevalidation/securitycontextconstraints/validation/validation.go
  pkg/admission/customresourcevalidation/securitycontextconstraints/validation/validation_test.go
Labels: approved, lgtm, size/XL

#22747 fallback to quay.io/openshift/origin-must-gather:latest
  pkg/oc/cli/admin/mustgather/mustgather.go
Labels: approved, lgtm, size/XS

#22705 Bug 1702743: Wait for internal registry hostname to be published before running e2e tests
  test/extended/imageapis/limitrange_admission.go
  test/extended/util/framework.go
Labels: approved, lgtm, size/M

#22763 UPSTREAM: 76983: Shuffle addresslist for random mount server and cleanup error messages
  vendor/k8s.io/kubernetes/pkg/volume/glusterfs/glusterfs.go
Labels: approved, lgtm, size/S

#22748 Add clusteroperators and clusterversions to explain tests
  test/extended/cli/explain.go
Labels: approved, lgtm, size/M

#22769 UPSTREAM: <carry>: filter out RBR and SCC paths from OpenAPI
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/routes/openapi.go
Labels: approved, lgtm, size/XS

#22741 Add CronJobs and StatefulSet to debug for workload controllers
  pkg/oc/cli/debug/debug.go
Labels: approved, lgtm, size/S

#22743 Bug 1704874: Copy Registry CA to Build Pods
  pkg/build/controller/build/build_controller.go
  pkg/build/controller/build/build_controller_test.go
  pkg/build/util/util.go
  pkg/cmd/openshift-controller-manager/controller/build.go
  pkg/cmd/openshift-controller-manager/controller/interfaces.go
Labels: approved, lgtm, size/L

#22734 Bug 1704722: increase build controller client rate limit and reduce api calls
  pkg/build/controller/build/build_controller.go
  pkg/build/controller/build/build_controller_test.go
  pkg/build/util/util.go
  pkg/cmd/openshift-controller-manager/controller/build.go
Labels: approved, lgtm, size/M

#22754 always dump logs
  cmd/openshift-tests/openshift-tests.go
Labels: approved, lgtm, size/XS

#22755 UPSTREAM: <drop>: Remove use of alpha initializers
  vendor/k8s.io/kubernetes/test/e2e/apimachinery/namespace.go
Labels: approved, lgtm, size/S

#22757 test-cmd: don't hang in bash if SCCs fail to appear
  hack/local-up-master/lib.sh
Labels: approved, lgtm, size/XS

#22640 adding e2e tests to ensure sdn metrics
  test/extended/prometheus/prometheus.go
Labels: approved, lgtm, size/S

#22765 add RBR from CRDs
  hack/local-up-master/kube-apiserver-manifests/01_role_binding_restriction_crd.yaml
  hack/test-cmd.sh
  pkg/admission/customresourcevalidation/attributes.go
  pkg/admission/customresourcevalidation/customresourcevalidationregistration/cr_validation_registration.go
  pkg/admission/customresourcevalidation/rolebindingrestriction/validate_rbr.go
  pkg/admission/customresourcevalidation/rolebindingrestriction/validation/validation.go
  pkg/authorization/apiserver/apiserver.go
  pkg/authorization/apiserver/registry/rolebindingrestriction/etcd/etcd.go
  pkg/authorization/apiserver/registry/rolebindingrestriction/strategy.go
  pkg/cmd/openshift-kube-apiserver/kubeadmission/register.go
  pkg/cmd/openshift-kube-apiserver/server.go
  test/integration/etcd_storage_path_test.go
  test/integration/restrictusers_test.go
  test/util/client.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/apiserver/handler_proxy.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/apiserver/patch_always_local_delegate.go
Labels: approved, lgtm, size/L

#22775 Run RBR on all namespaces
  pkg/cmd/openshift-kube-apiserver/kubeadmission/register.go
Labels: approved, lgtm, size/XS

#22513 test/extended: check if there is less than two alerts fired
  test/extended/prometheus/prometheus.go
Labels: approved, lgtm, size/S

#22762 Bug 1702743: Re-enable new-app extended tests
  test/extended/builds/new_app.go
Labels: approved, lgtm, size/XS

#22782 openshift-sdn: exit with 0 when gracefully shut down
  pkg/cmd/openshift-sdn/cmd.go
Labels: approved, lgtm, size/XS

#22733 UPSTREAM: 77303: Update iptables.IsNotFoundError for iptables-nft error messages
  vendor/k8s.io/kubernetes/pkg/util/iptables/iptables.go
Labels: approved, component/networking, lgtm, sig/networking, size/M

#22764 origin.spec: replace 3.x client RPMs
  origin.spec
Labels: approved, lgtm, size/XS

#22791 The new release command incorrectly detected user metadata
  pkg/oc/cli/admin/release/new.go
Labels: approved, lgtm, size/XS

#22796 disable broken test
  test/integration/dockerregistryclient_test.go
Labels: approved, lgtm, size/XS

#22759 sdn: wait for proxy initialization before declaring node network ready
  pkg/cmd/openshift-sdn/cmd.go
  pkg/cmd/openshift-sdn/proxy.go
  pkg/cmd/openshift-sdn/sdn.go
  pkg/network/node/node.go
Labels: approved, lgtm, size/L

#22771 switch leader election lock for ocm to openshift-controller-manager
  hack/local-up-master/openshift-apiserver-manifests/04-namespace.yaml
  pkg/cmd/openshift-controller-manager/controller_manager.go
  test/integration/project_test.go
  test/util/server/server.go
Labels: approved, lgtm, size/M

#22739 tests follow-up to tightening authn APIs validation
  test/integration/groups_test.go
  test/integration/oauth_serviceaccount_client_test.go
Labels: approved, lgtm, size/S

#22619 extract_tools: pass security options
  pkg/oc/cli/admin/release/extract_tools.go
Labels: approved, lgtm, size/XS

#22786 Allow oc adm upgrade with --force even if versions match
  pkg/oc/cli/admin/upgrade/upgrade.go
Labels: approved, lgtm, size/XS

#22752 Bug: 1705649: test: extended: add check for pod tolerations
  test/extended/operators/tolerations.go
Labels: approved, lgtm, size/M

#22772 oc adm must-gather: provide better feedback
  pkg/oc/cli/admin/mustgather/mustgather.go
Labels: approved, lgtm, size/M

#22774 image-eco/dancer build's dependency downloads can become way too slow…
  test/extended/image_ecosystem/sample_repos.go
Labels: approved, lgtm, sig/developer-experience, size/S

#22788 sdn: install nftables in SDN image
  images/sdn/Dockerfile.rhel
Labels: approved, lgtm, size/XS

#22790 Bug 1707205: Get rid of oc wrappers where we can
  pkg/oc/cli/cli.go
  pkg/oc/cli/kubectlwrappers/wrappers.go
  test/cmd/deployments.sh
Labels: approved, lgtm, size/L

#22793 Bug 1704767: Update tests for S2I incremental builds
  test/extended/builds/s2i_incremental.go
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/incremental-auth-build.json
Labels: approved, lgtm, size/L

#22794 Revert "e2e must-gather disable check for file sizes"
  test/extended/cli/mustgather.go
Labels: approved, lgtm, size/XS

#22803 Only accept buildah 1.7.3+ unused build arg error
  test/extended/builds/start.go
Labels: approved, lgtm, size/XS

#22809 log more failures during e2e
  cmd/openshift-tests/openshift-tests.go
  vendor/k8s.io/kubernetes/test/e2e/upgrades/apps/job.go
  vendor/k8s.io/kubernetes/test/e2e/upgrades/apps/replicasets.go
Labels: approved, lgtm, size/S

#22824 Update publishing rules for origin 4.2 and k8s 1.14
  publishing-kube-rules.yaml
Labels: approved, lgtm, size/M

#22821 Bug 1707162: Block access to MCS
  cmd/sdn-cni-plugin/openshift-sdn_linux.go
  pkg/network/admission/restrictedendpoints/endpoint_admission.go
  pkg/network/node/iptables.go
Labels: approved, lgtm, size/M

#22800 Revert "disable broken test"
  test/integration/dockerregistryclient_test.go
Labels: approved, lgtm, size/XS

#22829 wait for must-gather logs to be available
  pkg/oc/cli/admin/mustgather/mustgather.go
Labels: approved, lgtm, size/S

#22825 Fix my github id in sdn-cni-plugin/OWNERS
  cmd/sdn-cni-plugin/OWNERS
Labels: approved, lgtm, size/XS

#22832 Fix invocation of log function on local-up
  hack/local-up-master/lib.sh
Labels: approved, lgtm, size/XS

#22836 Sort the release changelog by newest pull request first
  pkg/oc/cli/admin/release/git.go
Labels: approved, lgtm, size/XS

#22806 Don't use the %s formatting directive for ldap.Entry type
  pkg/oc/lib/groupsync/rfc2307/ldapinterface.go
  pkg/oc/lib/groupsync/rfc2307/ldapinterface_test.go
Labels: approved, lgtm, size/XS

#22797 test/extented/prometheus: Relax alert firing smoke test
  test/extended/prometheus/prometheus.go
Labels: approved, lgtm, size/XS

#22834 Bug 1694087: Do not reset container state when pod is deleted
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go
  vendor/k8s.io/kubernetes/pkg/kubelet/status/status_manager.go
  vendor/k8s.io/kubernetes/pkg/kubelet/status/status_manager_test.go
Labels: approved, lgtm, size/M

#22841 disable registry v1 client test
  test/integration/dockerregistryclient_test.go
Labels: approved, lgtm, size/XS

#22835 test/e2e/upgrade: wait until all pools have upgraded
  test/e2e/upgrade/upgrade.go
Labels: approved, lgtm, size/M

#22655 Use pager to get images for pruning
  pkg/oc/cli/admin/prune/images/images.go
Labels: approved, lgtm, size/S

#21540 Add reflector and workqueue metrics
  pkg/cmd/openshift-apiserver/server.go
Labels: approved, lgtm, size/XS

#22826 Restrict access to EC2 metadata
  cmd/sdn-cni-plugin/openshift-sdn_linux.go
  pkg/network/admission/restrictedendpoints/endpoint_admission.go
  pkg/network/node/ovscontroller.go
Labels: approved, lgtm, size/M

#22784 Bug 1705686: Work around a kernel bug in the assign-macvlan code
  cmd/sdn-cni-plugin/openshift-sdn_linux.go
Labels: approved, component/networking, kind/bug, lgtm, sig/networking, size/XS

#22857 Disable NodeLease and RuntimeClass tests temporarily
  test/extended/util/test.go
Labels: approved, lgtm, size/XS

#22862 PrunerPing unit fails because of golang 1.12 HTTPS server change
  pkg/oc/cli/admin/prune/imageprune/helper_test.go
Labels: approved, lgtm, size/S

#22863 UPSTREAM: 76603: TestEventChannelFull is flaky
  vendor/k8s.io/kubernetes/pkg/kubelet/pleg/generic_test.go
Labels: approved, lgtm, size/XS

#22861 Fix abort-at=random on upgrade tests
  test/e2e/upgrade/upgrade.go
Labels: approved, lgtm, size/XS

#22860 Switch to golang-1.12 for image builds
  images/cli-artifacts/Dockerfile.rhel
  images/cli/Dockerfile.rhel
  images/hyperkube/Dockerfile.rhel
  images/hypershift/Dockerfile.rhel
  images/sdn/Dockerfile.rhel
  images/template-service-broker/Dockerfile.rhel
  images/tests/Dockerfile.rhel
Labels: approved, lgtm, size/S

#22865 Disable probe restart test because it is flaky under kubelet skew
  test/extended/util/test.go
Labels: approved, lgtm, size/XS

#22859 Switch conformance-k8s to 1.14
  test/extended/conformance-k8s.sh
Labels: approved, lgtm, size/XS

#22866 UPSTREAM: 00000: gRPC tests for encryption envelope are flaky
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/storage/value/encrypt/envelope/grpc_service_unix_test.go
Labels: approved, lgtm, size/M

#22858 Re-enable a large chunk of disabled tests
  test/extended/util/test.go
Labels: approved, lgtm, size/L

#22867 UPSTREAM: <carry>: Disable excessive success logging in HTTP checking
  vendor/k8s.io/kubernetes/test/e2e/framework/networking_utils.go
Labels: approved, lgtm, size/XS

#22874 Display the randomly chosen upgrade abort percentage
  test/e2e/upgrade/upgrade.go
Labels: approved, lgtm, size/XS

#22872 text/extended: Check both IP and Hostname on LB
  test/extended/router/headers.go
  test/extended/router/metrics.go
  test/extended/router/reencrypt.go
  test/extended/router/router.go
  test/extended/util/router.go
Labels: approved, lgtm, size/L

#22870 Cluster Loader: Add switch to handle yaml as podspec in config
  test/extended/cluster/cl.go
  test/extended/cluster/utils.go
Labels: approved, lgtm, size/M

#22799 UPSTREAM: 77415: Allow to define kubeconfig file for OpenStack cloud provider
  vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/openstack/openstack.go
  vendor/k8s.io/kubernetes/pkg/volume/cinder/cinder_test.go
Labels: approved, lgtm, sig/storage, size/S

#22883 add support for SCTP in the Openshift SDN
  pkg/network/node/networkpolicy.go
  pkg/network/node/ovscontroller.go
Labels: approved, lgtm, size/XS

#22853 images: use cli:4.2 as a base for all images
  images/cli-artifacts/Dockerfile.rhel
  images/cli/Dockerfile.rhel
  images/deployer/Dockerfile.rhel
  images/hyperkube/Dockerfile.rhel
  images/hypershift/Dockerfile.rhel
  images/recycler/Dockerfile.rhel
  images/sdn/Dockerfile.rhel
  images/template-service-broker/Dockerfile.rhel
  images/tests/Dockerfile.rhel
Labels: approved, lgtm, size/S

#22813 UPSTREAM: 77742: improve e2e namespace dumping on failure
  vendor/k8s.io/kubernetes/test/e2e/framework/util.go
Labels: approved, lgtm, size/S

#22893 Bug 1713262: pkg/oc/cli/admin/upgrade: Fix and test sortSemanticVersions
  pkg/oc/cli/admin/upgrade/upgrade.go
  pkg/oc/cli/admin/upgrade/upgrade_test.go
Labels: approved, lgtm, size/M

#22885 avoid builds on non-linux nodes
  pkg/build/controller/build/defaults/defaults.go
  pkg/build/controller/build/defaults/defaults_test.go
  pkg/build/controller/build/overrides/overrides.go
  pkg/build/controller/build/overrides/overrides_test.go
  pkg/build/controller/build/podcreationstrategy.go
  pkg/build/controller/build/podcreationstrategy_test.go
  test/extended/builds/start.go
  test/integration/buildpod_admission_test.go
Labels: approved, lgtm, sig/developer-experience, size/L

#22814 Bug 1699285: Add warning when unrecognized resource is found
  pkg/oc/cli/admin/policy/who_can.go
  pkg/oc/cli/policy/cani/cani.go
Labels: approved, lgtm, size/S

#22886 UPSTREAM: 76193: Fix nfs multi-node PV test
  vendor/k8s.io/kubernetes/test/e2e/storage/testsuites/provisioning.go
Labels: approved, lgtm, size/S

#22894 UPSTREAM: 78132: Fix CSI attacher test
  vendor/k8s.io/kubernetes/pkg/volume/csi/csi_attacher_test.go
Labels: approved, lgtm, sig/storage, size/XS

#22899 add samples operator back into cli/explain extended test
  test/extended/cli/explain.go
Labels: approved, lgtm, sig/developer-experience, size/XS

#22902 Use new name for sample operator config
  test/extended/util/framework.go
Labels: approved, lgtm, size/XS

#22903 UPSTREAM: 78257: Fix volume reconciler flake
  vendor/k8s.io/kubernetes/pkg/volume/testing/testing.go
Labels: approved, lgtm, sig/storage, size/XS

#22890 UPSTREAM: 77426: Remove terminated pod from summary api
  vendor/k8s.io/kubernetes/pkg/kubelet/stats/BUILD
  vendor/k8s.io/kubernetes/pkg/kubelet/stats/cri_stats_provider.go
  vendor/k8s.io/kubernetes/pkg/kubelet/stats/cri_stats_provider_test.go
  vendor/k8s.io/kubernetes/pkg/kubelet/stats/log_metrics_provider_test.go
Labels: approved, lgtm, size/L

#22920 add publishing rule file for staging
  publishing-staging-rules.yaml
Labels: approved, size/XS

#22922 fix staging publishing rules
  publishing-staging-rules.yaml
Labels: approved, size/XS

#22923 fix staging publishing rule one more time
  publishing-staging-rules.yaml
Labels: size/XS

#22924 add openshift/oc to publishing rules
  publishing-staging-rules.yaml
Labels: approved, size/XS

#22928 publishing: introduce openshift-apiserver to staging
  publishing-staging-rules.yaml
Labels: approved, size/XS

#22889 UPSTREAM: 77426: Remove terminated pod from summary api
  vendor/k8s.io/kubernetes/pkg/kubelet/stats/BUILD
  vendor/k8s.io/kubernetes/pkg/kubelet/stats/cri_stats_provider.go
  vendor/k8s.io/kubernetes/pkg/kubelet/stats/cri_stats_provider_test.go
  vendor/k8s.io/kubernetes/pkg/kubelet/stats/log_metrics_provider_test.go
Labels: approved, lgtm, size/L

#22926 remove dead packages
  pkg/oauth/osintypes/types.go
  pkg/security/mcsallocator/allocator.go
  pkg/security/mcsallocator/allocator_test.go
  pkg/template/client/internalversion/templateconfig.go
Labels: approved, lgtm, size/L

#22930 stop accepting old master config
  pkg/cmd/openshift-apiserver/cmd.go
  pkg/cmd/openshift-controller-manager/cmd.go
  pkg/cmd/openshift-kube-apiserver/cmd.go
Labels: approved, lgtm, size/L

#22916 move authorization validation functions
  hack/import-restrictions.json
  pkg/authorization/apis/authorization/helpers.go
  pkg/authorization/apis/authorization/internal/serviceaccount/doc.go
  pkg/authorization/apis/authorization/util.go
Labels: approved, lgtm, size/M

#22932 update publishing rules for kube 1.13.4 and kube 1.14.0
  publishing-rules.yaml
Labels: approved, lgtm, priority/critical-urgent, queue/critical-fix, size/XS

#22919 utils/errors: remove cruft
  hack/import-restrictions.json
  pkg/authorization/apiserver/registry/registry/wrapper.go
  pkg/oc/cli/admin/prune/images/images.go
  pkg/oc/cli/idle/idle.go
  pkg/oc/lib/describe/projectstatus.go
  pkg/util/errors/doc.go
  pkg/util/errors/errors.go
  pkg/util/errors/wrapper.go
  pkg/util/errors/wrapper_test.go
  test/extended/util/endpoints.go
Labels: approved, lgtm, size/L

#22773 Fix guidance for e2e tests in HACKING.md
  HACKING.md
Labels: approved, lgtm, size/M

#22942 Bug 1715055: Work around a kernel bug in the assign-macvlan code [4.1]
  cmd/sdn-cni-plugin/openshift-sdn_linux.go
Labels: approved, component/networking, kind/bug, lgtm, sig/networking, size/XS

#22831 test-extended: test MCS is blocked for pods and CMA does not approve random CSRs
  test/extended/csrapprover/csrapprover.go
  test/extended/include.go
Labels: approved, lgtm, size/L

#22918 remove unnecessarily validation
  hack/import-restrictions.json
  pkg/admission/customresourcevalidation/oauth/helpers.go
  pkg/admission/customresourcevalidation/oauth/validate_gitlab.go
  pkg/admission/customresourcevalidation/oauth/validate_openid.go
  pkg/admission/customresourcevalidation/oauth/validate_requestheader.go
  pkg/cmd/openshift-sdn/cmd.go
  pkg/cmd/server/apis/config/validation/build_defaults.go
  pkg/cmd/server/apis/config/validation/build_defaults_test.go
  pkg/cmd/server/apis/config/validation/build_overrides.go
  pkg/cmd/server/apis/config/validation/build_overrides_test.go
  pkg/cmd/server/apis/config/validation/common/common.go
  pkg/cmd/server/apis/config/validation/common/serving.go
  pkg/cmd/server/apis/config/validation/common/serving_test.go
  pkg/cmd/server/apis/config/validation/etcd.go
  pkg/cmd/server/apis/config/validation/master.go
  pkg/cmd/server/apis/config/validation/master_test.go
  pkg/cmd/server/apis/config/validation/network/network.go
  pkg/cmd/server/apis/config/validation/node.go
  pkg/cmd/server/apis/config/validation/node_test.go
  pkg/cmd/server/apis/config/validation/oauth.go
  pkg/cmd/server/apis/config/validation/oauth_test.go
  pkg/cmd/server/apis/config/validation/validation.go
  pkg/cmd/server/apis/config/validation/validation_test.go
  pkg/network/common/networkvalidation/network.go
  pkg/oc/cli/admin/groups/examples/examples_test.go
  pkg/oc/cli/admin/groups/sync/prune.go
  pkg/oc/cli/admin/groups/sync/sync.go
  pkg/oc/lib/groupsync/ldap/ldap.go
Labels: approved, lgtm, size/XXL

#22925 move constants to single point of use to separate client and server tools
  hack/import-restrictions.json
  pkg/oauthserver/server/errorpage/errorpage_test.go
  pkg/oauthserver/server/errorpage/templates.go
  pkg/oauthserver/server/login/login_test.go
  pkg/oauthserver/server/login/templates.go
  pkg/oauthserver/server/selectprovider/selectprovider_test.go
  pkg/oauthserver/server/selectprovider/templates.go
  pkg/oc/cli/admin/createerrortemplate/create_error_template.go
  pkg/oc/cli/admin/createlogintemplate/create_login_template.go
  pkg/oc/cli/admin/createproviderselectiontemplate/create_provider_selection_template.go
Labels: approved, lgtm, size/L

#22937 snip most cmdutil deps
  pkg/cmd/openshift-controller-manager/controller/net.go
  pkg/cmd/openshift-controller-manager/controller/net_test.go
  pkg/cmd/openshift-controller-manager/controller/standalone_apiserver.go
  pkg/cmd/server/apis/config/helpers.go
  pkg/cmd/util/crypto.go
  pkg/cmd/util/crypto_test.go
  pkg/cmd/util/doc.go
  pkg/cmd/util/filepath.go
  pkg/cmd/util/filepath_test.go
  pkg/cmd/util/log.go
  pkg/cmd/util/net.go
  pkg/cmd/util/product.go
  test/integration/oauth_basicauth_test.go
  test/integration/oauth_cert_fallback_test.go
  test/util/server/server.go
Labels: approved, lgtm, size/XL

#22940 move recycler into oc where it is used
  hack/import-restrictions.json
  pkg/oc/cli/cli.go
  staging/src/github.com/openshift/oc/pkg/cli/recycle/recycle.go
  staging/src/github.com/openshift/oc/pkg/cli/recycle/recycle_test.go
  staging/src/github.com/openshift/oc/pkg/cli/recycle/walker.go
  staging/src/github.com/openshift/oc/pkg/cli/recycle/walker_linux.go
  staging/src/github.com/openshift/oc/pkg/cli/recycle/walker_other.go
  staging/src/github.com/openshift/oc/pkg/cli/recycle/walker_test.go
Labels: approved, lgtm, size/XS

#22946 get more strict on staging
  hack/verify-imports.sh
Labels: approved, lgtm, size/M

#22945 use library-go functionality for logs and template processing
  glide.lock
  hack/import-restrictions.json
  pkg/cmd/openshift-apiserver/server.go
  pkg/cmd/openshift-controller-manager/controller_manager.go
  pkg/cmd/openshift-network-controller/network_controller.go
  pkg/cmd/util/log.go
  pkg/oc/cli/process/process.go
  pkg/template/apiserver/registry/template/rest.go
  pkg/template/templateprocessing/template.go
  pkg/template/templateprocessing/template_test.go
  vendor/github.com/openshift/library-go/glide.lock
  vendor/github.com/openshift/library-go/glide.yaml
  vendor/github.com/openshift/library-go/pkg/config/helpers/readresource.go
  vendor/github.com/openshift/library-go/pkg/oauth/oauthdiscovery/discovery.go
  vendor/github.com/openshift/library-go/pkg/oauth/oauthdiscovery/urls.go
  vendor/github.com/openshift/library-go/pkg/serviceability/logrus.go
  vendor/github.com/openshift/library-go/pkg/template/OWNERS
  vendor/github.com/openshift/library-go/pkg/template/generator/doc.go
  vendor/github.com/openshift/library-go/pkg/template/generator/examples/doc.go
  vendor/github.com/openshift/library-go/pkg/template/generator/examples/remotevalue.go
  vendor/github.com/openshift/library-go/pkg/template/generator/examples/remotevalue_test.go
  vendor/github.com/openshift/library-go/pkg/template/generator/expressionvalue.go
  vendor/github.com/openshift/library-go/pkg/template/generator/expressionvalue_test.go
  vendor/github.com/openshift/library-go/pkg/template/generator/generator.go
  vendor/github.com/openshift/openshift-apiserver
Labels: approved, lgtm, size/L

#22214 Add example 'oc rsh' command
  pkg/oc/cli/rsh/rsh.go
Labels: approved, lgtm, size/XS

#22939 move legacy launch to point of use
  pkg/cmd/openshift/openshift.go
  pkg/cmd/openshift/product.go
  pkg/cmd/server/etcd/doc.go
  pkg/cmd/server/start/options/image_args.go
  pkg/cmd/server/start/options/network_args.go
  test/integration/etcd_storage_path_test.go
  test/integration/userclient_test.go
  test/util/server/deprecated_openshift/etcd/etcd.go
  test/util/server/deprecated_openshift/etcd/etcdserver/run.go
  test/util/server/deprecated_openshift/start/master_args.go
  test/util/server/deprecated_openshift/start/options/image_args.go
  test/util/server/deprecated_openshift/start/options/kube_connection_args.go
  test/util/server/deprecated_openshift/start/options/listen_arg.go
  test/util/server/deprecated_openshift/start/options/network_args.go
  test/util/server/server.go
Labels: approved, lgtm, size/L

#22949 Bug 1715020: oauth validation: don't allow multiple IdPs in single IdP object
  pkg/admission/customresourcevalidation/oauth/validate_idp.go
  pkg/admission/customresourcevalidation/oauth/validate_idp_test.go
Labels: approved, lgtm, size/M

#22963 staging: prepare openshift-controller-manager and oauth-server
  staging/src/github.com/openshift/oauth-server/OWNERS
  staging/src/github.com/openshift/oauth-server/README.md
  staging/src/github.com/openshift/openshift-controller-manager/OWNERS
  staging/src/github.com/openshift/openshift-controller-manager/README.md
  vendor/github.com/openshift/oauth-server
  vendor/github.com/openshift/openshift-controller-manager
Labels: approved, size/S

#22964 staging: update publishing rules for oauth-server and controller manager
  publishing-staging-rules.yaml
Labels: approved, do-not-merge/hold, size/S

#22934 Move oc/libs to staging
  hack/import-restrictions.json
  pkg/oc/cli/admin/groups/sync/ad.go
  pkg/oc/cli/admin/groups/sync/augmented_ad.go
  pkg/oc/cli/admin/groups/sync/interfaces.go
  pkg/oc/cli/admin/groups/sync/prune.go
  pkg/oc/cli/admin/groups/sync/rfc2307.go
  pkg/oc/cli/admin/groups/sync/sync.go
  pkg/oc/cli/status/status.go
  pkg/oc/lib/describe/chaindescriber.go
  pkg/oc/lib/serviceaccount/helpers.go
  staging/src/github.com/openshift/oc/pkg/helpers/dot/dot.go
  staging/src/github.com/openshift/oc/pkg/helpers/dot/dot_test.go
  staging/src/github.com/openshift/oc/pkg/helpers/groupsync/ad/augmented_ldapinterface.go
  staging/src/github.com/openshift/oc/pkg/helpers/groupsync/ad/augmented_ldapinterface_test.go
  staging/src/github.com/openshift/oc/pkg/helpers/groupsync/ad/ldapinterface.go
  staging/src/github.com/openshift/oc/pkg/helpers/groupsync/ad/ldapinterface_test.go
  staging/src/github.com/openshift/oc/pkg/helpers/groupsync/consts.go
  staging/src/github.com/openshift/oc/pkg/helpers/groupsync/groupdetector/groupdetector.go
  staging/src/github.com/openshift/oc/pkg/helpers/groupsync/groupdetector/groupdetector_test.go
  staging/src/github.com/openshift/oc/pkg/helpers/groupsync/grouplister.go
  staging/src/github.com/openshift/oc/pkg/helpers/groupsync/grouplister_test.go
  staging/src/github.com/openshift/oc/pkg/helpers/groupsync/groupnamemapper.go
  staging/src/github.com/openshift/oc/pkg/helpers/groupsync/grouppruner.go
  staging/src/github.com/openshift/oc/pkg/helpers/groupsync/grouppruner_test.go
  staging/src/github.com/openshift/oc/pkg/helpers/groupsync/groupsyncer.go
  staging/src/github.com/openshift/oc/pkg/helpers/groupsync/groupsyncer_test.go
  staging/src/github.com/openshift/oc/pkg/helpers/groupsync/interfaces/interfaces.go
  staging/src/github.com/openshift/oc/pkg/helpers/groupsync/rfc2307/ldapinterface.go
  staging/src/github.com/openshift/oc/pkg/helpers/groupsync/rfc2307/ldapinterface_test.go
  staging/src/github.com/openshift/oc/pkg/helpers/groupsync/syncerror/errors.go
  staging/src/github.com/openshift/oc/pkg/helpers/groupsync/syncerror/handler.go
  staging/src/github.com/openshift/oc/pkg/helpers/groupsync/syncerror/handler_test.go
  staging/src/github.com/openshift/oc/pkg/helpers/groupsync/usernamemapper.go
Labels: approved, lgtm, sig/master, size/M

#22933 UPSTREAM: 76188: csi: Implement NodeServiceCapability_RPC_GET_VOLUME_STATS rpc call
  vendor/k8s.io/kubernetes/pkg/volume/csi/BUILD
  vendor/k8s.io/kubernetes/pkg/volume/csi/csi_client.go
  vendor/k8s.io/kubernetes/pkg/volume/csi/csi_client_test.go
  vendor/k8s.io/kubernetes/pkg/volume/csi/csi_metrics.go
  vendor/k8s.io/kubernetes/pkg/volume/csi/csi_metrics_test.go
  vendor/k8s.io/kubernetes/pkg/volume/csi/csi_mounter.go
  vendor/k8s.io/kubernetes/pkg/volume/csi/csi_plugin.go
  vendor/k8s.io/kubernetes/pkg/volume/csi/fake/fake_client.go
Labels: approved, lgtm, sig/storage, size/L

#22936 pkg/build/client: remove this cruft
  pkg/build/apiserver/registry/buildconfig/webhook.go
  pkg/build/apiserver/registry/buildconfig/webhook_test.go
  pkg/build/client/clients.go
  pkg/build/controller/build/build_controller.go
  pkg/build/controller/buildconfig/buildconfig_controller.go
  pkg/build/controller/buildconfig/buildconfig_controller_test.go
  pkg/build/controller/common/util.go
  pkg/build/controller/common/util_test.go
  pkg/build/controller/policy/parallel.go
  pkg/build/controller/policy/parallel_test.go
  pkg/build/controller/policy/policy.go
  pkg/build/controller/policy/policy_test.go
  pkg/build/controller/policy/serial.go
  pkg/build/controller/policy/serial_latest_only.go
  pkg/build/controller/policy/serial_latest_only_test.go
  pkg/build/controller/policy/serial_test.go
  pkg/cmd/openshift-controller-manager/controller/image.go
  pkg/image/controller/trigger/image_trigger_controller_test.go
  pkg/image/trigger/buildconfigs/buildconfigs.go
  pkg/image/trigger/buildconfigs/buildconfigs_test.go
  pkg/oc/cli/cancelbuild/cancelbuild.go
Labels: approved, lgtm, size/XL

#22960 template: remove templateprocessing dep from new-app
  pkg/oc/cli/newapp/newapp.go
  pkg/template/templateprocessing/template.go
  pkg/template/templateprocessing/template_test.go
Labels: approved, lgtm, size/M

#22965 switch to library-go naming helpers
  glide.lock
  hack/import-restrictions.json
  pkg/apps/strategy/support/lifecycle.go
  pkg/apps/strategy/support/lifecycle_test.go
  pkg/apps/util/util.go
  pkg/build/apis/build/fields.go
  pkg/build/apis/build/internal_helpers/internal_helpers.go
  pkg/build/buildapihelpers/util.go
  pkg/build/controller/strategy/util.go
  pkg/build/generator/generator.go
  pkg/build/util/util.go
  pkg/oc/lib/newapp/app/imageref.go
  pkg/oc/lib/newapp/app/uniquenamegenerator.go
  pkg/oc/lib/newapp/app/uniquenamegenerator_test.go
  pkg/openapi/zz_generated.openapi.go
  pkg/serviceaccounts/controllers/create_dockercfg_secrets.go
  test/extended/util/framework.go
  vendor/github.com/openshift/api/operator/v1/types_console.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/osin/v1/register.go
  vendor/github.com/openshift/api/osin/v1/types.go
  vendor/github.com/openshift/api/osin/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/library-go/pkg/build/naming/namer.go
  vendor/github.com/openshift/library-go/pkg/build/naming/namer_test.go
  vendor/github.com/openshift/library-go/pkg/image/imageutil/helpers.go
  vendor/github.com/openshift/library-go/pkg/image/referencemutator/builds.go
  vendor/github.com/openshift/library-go/pkg/image/referencemutator/builds_test.go
  vendor/github.com/openshift/library-go/pkg/image/referencemutator/meta.go
  vendor/github.com/openshift/library-go/pkg/image/referencemutator/pods.go
  vendor/github.com/openshift/library-go/pkg/image/referencemutator/pods_test.go
  vendor/github.com/openshift/library-go/pkg/image/trigger/annotations.go
  vendor/github.com/openshift/library-go/pkg/image/trigger/annotations_test.go
  vendor/github.com/openshift/library-go/pkg/image/trigger/interfaces.go
  vendor/github.com/openshift/library-go/pkg/image/trigger/types.go
  vendor/github.com/openshift/library-go/pkg/network/networkutils/networkutils.go
  vendor/github.com/openshift/library-go/pkg/network/networkutils/networkutils_test.go
  vendor/github.com/openshift/library-go/pkg/quota/clusterquotamapping/clusterquotamapping.go
  vendor/github.com/openshift/library-go/pkg/quota/clusterquotamapping/clusterquotamapping_test.go
  vendor/github.com/openshift/library-go/pkg/quota/clusterquotamapping/helpers.go
  vendor/github.com/openshift/library-go/pkg/quota/clusterquotamapping/mapper.go
  vendor/github.com/openshift/library-go/pkg/security/ldapquery/errors.go
  vendor/github.com/openshift/library-go/pkg/security/ldapquery/query.go
  vendor/github.com/openshift/library-go/pkg/security/ldapquery/query_test.go
  vendor/github.com/openshift/library-go/pkg/security/ldapquery/types.go
Labels: approved, lgtm, size/XXL

#22972 UPSTREAM: 78541: choose a more unique request timeout default
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/rest.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/rest_test.go
Labels: approved, lgtm, size/XS

#22572 deploy hook inherit the inexistent volume
  test/extended/testdata/bindata.go
  test/extended/testdata/deployments/custom-deployment.yaml
Labels: approved, lgtm, size/XS

#22844 Improve Cluster Loader VIPERCONFIG handling and template file locating
  test/extended/cluster/cl.go
  test/extended/cluster/context.go
  test/extended/cluster/utils.go
Labels: approved, lgtm, size/M

#22884 Bug 1712581: test/e2e/upgrade: Summarize ClusterVersion on upgrade failures
  test/e2e/upgrade/monitor.go
  test/e2e/upgrade/upgrade.go
Labels: approved, lgtm, size/M

#22896 Allow `oc adm release info` to output digest, name, or pull spec
  pkg/oc/cli/admin/release/info.go
Labels: approved, lgtm, size/M

#22953 Bug 1711533: UPSTREAM: revert: 00000: restore unprivileged access
  vendor/k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go
  vendor/k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/cluster-role-bindings.yaml
Labels: approved, lgtm, size/XS

#22981 use shared library for building CRQ mapping
  glide.lock
  pkg/cmd/openshift-apiserver/openshiftadmission/plugin_initializer.go
  pkg/cmd/openshift-apiserver/openshiftapiserver/openshift_apiserver.go
  pkg/cmd/openshift-apiserver/openshiftapiserver/project.go
  pkg/cmd/openshift-controller-manager/controller/quota.go
  pkg/cmd/server/admission/init.go
  pkg/cmd/server/admission/types.go
  pkg/quota/apiserver/admission/clusterresourcequota/accessor.go
  pkg/quota/apiserver/admission/clusterresourcequota/accessor_test.go
  pkg/quota/apiserver/admission/clusterresourcequota/admission.go
  pkg/quota/apiserver/apiserver.go
  pkg/quota/apiserver/registry/appliedclusterresourcequota/filter.go
  pkg/quota/controller/clusterquotamapping/clusterquotamapping.go
  pkg/quota/controller/clusterquotamapping/clusterquotamapping_test.go
  pkg/quota/controller/clusterquotamapping/mapper.go
  pkg/quota/controller/clusterquotareconciliation/reconciliation_controller.go
  pkg/quota/controller/clusterquotareconciliation/reconciliation_controller_test.go
  vendor/github.com/openshift/library-go/pkg/apps/OWNERS
  vendor/github.com/openshift/library-go/pkg/apps/appsserialization/scheme.go
  vendor/github.com/openshift/library-go/pkg/apps/appsserialization/scheme_test.go
  vendor/github.com/openshift/library-go/pkg/apps/appsserialization/serialize.go
  vendor/github.com/openshift/library-go/pkg/apps/appsutil/const.go
  vendor/github.com/openshift/library-go/pkg/apps/appsutil/rc_scale_client.go
  vendor/github.com/openshift/library-go/pkg/apps/appsutil/util.go
  vendor/github.com/openshift/library-go/pkg/apps/appsutil/util_test.go
  vendor/github.com/openshift/library-go/pkg/authorization/scopemetadata/clusterrole_describers.go
  vendor/github.com/openshift/library-go/pkg/authorization/scopemetadata/describers.go
  vendor/github.com/openshift/library-go/pkg/authorization/scopemetadata/user_describers.go
  vendor/github.com/openshift/library-go/pkg/authorization/scopemetadata/validation.go
  vendor/github.com/openshift/library-go/pkg/authorization/scopemetadata/validation_test.go
  vendor/github.com/openshift/library-go/pkg/legacyapi/legacygroupification/groupification.go
Labels: approved, lgtm, size/XXL

#22979 bring in library-go updates to break bad deps
  glide.lock
  vendor/github.com/openshift/library-go/pkg/apps/OWNERS
  vendor/github.com/openshift/library-go/pkg/apps/appsserialization/scheme.go
  vendor/github.com/openshift/library-go/pkg/apps/appsserialization/scheme_test.go
  vendor/github.com/openshift/library-go/pkg/apps/appsserialization/serialize.go
  vendor/github.com/openshift/library-go/pkg/apps/appsutil/const.go
  vendor/github.com/openshift/library-go/pkg/apps/appsutil/rc_scale_client.go
  vendor/github.com/openshift/library-go/pkg/apps/appsutil/util.go
  vendor/github.com/openshift/library-go/pkg/apps/appsutil/util_test.go
  vendor/github.com/openshift/library-go/pkg/authorization/scopemetadata/clusterrole_describers.go
  vendor/github.com/openshift/library-go/pkg/authorization/scopemetadata/describers.go
  vendor/github.com/openshift/library-go/pkg/authorization/scopemetadata/user_describers.go
  vendor/github.com/openshift/library-go/pkg/authorization/scopemetadata/validation.go
  vendor/github.com/openshift/library-go/pkg/authorization/scopemetadata/validation_test.go
  vendor/github.com/openshift/library-go/pkg/legacyapi/legacygroupification/groupification.go
Labels: approved, lgtm, size/XXL
