Repository openshift/origin, pull requests merged in 2020-11, with the labels that each got.

#25650 add cakephp back in with upstream fix landing
  test/extended/image_ecosystem/s2i_php.go
  test/extended/image_ecosystem/sample_repos.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#25647 Bug 1892775: disabling cakephp until upstream problem addressed: bugzilla 1891989
  test/extended/builds/build_pruning.go
  test/extended/templates/templateinstance_readiness.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#25626 Bug 1890901: Fixes the wrong file path(/var/lib//var/lib/haproxy/conf/haproxy.conf) for the CI test to pass
  test/extended/router/router.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25602 Report API server unavailability in e2e tests
  pkg/monitor/api.go
  pkg/monitor/sampler.go
  pkg/test/ginkgo/synthentic_tests.go
  test/extended/util/disruption/disruption.go
Labels: approved, lgtm

#25646 Bug 1891459: bump(k8s.io/kubernetes)
  go.mod
  go.sum
  vendor/k8s.io/kubernetes/pkg/credentialprovider/config.go
  vendor/k8s.io/kubernetes/pkg/kubelet/time_cache.go
  vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go
  vendor/k8s.io/kubernetes/pkg/volume/fc/fc_util.go
  vendor/k8s.io/kubernetes/pkg/volume/vsphere_volume/attacher.go
  vendor/k8s.io/kubernetes/test/e2e/apps/daemon_set.go
  vendor/k8s.io/kubernetes/test/e2e/e2e.go
  vendor/k8s.io/kubernetes/test/e2e/framework/ingress/ingress_utils.go
  vendor/k8s.io/kubernetes/test/e2e/framework/network/BUILD
  vendor/k8s.io/kubernetes/test/e2e/framework/network/utils.go
  vendor/k8s.io/kubernetes/test/e2e/framework/node/wait.go
  vendor/k8s.io/kubernetes/test/e2e/framework/pod/resource.go
  vendor/k8s.io/kubernetes/test/e2e/framework/pod/wait.go
  vendor/k8s.io/kubernetes/test/e2e/framework/ssh/BUILD
  vendor/k8s.io/kubernetes/test/e2e/framework/ssh/ssh.go
  vendor/k8s.io/kubernetes/test/e2e/framework/util.go
  vendor/k8s.io/kubernetes/test/e2e/scheduling/priorities.go
  vendor/k8s.io/kubernetes/test/e2e/storage/host_path_type.go
  vendor/k8s.io/kubernetes/test/e2e/storage/persistent_volumes-local.go
  vendor/k8s.io/kubernetes/test/e2e/storage/testsuites/snapshottable.go
  vendor/k8s.io/kubernetes/test/e2e/storage/testsuites/volume_io.go
  vendor/k8s.io/kubernetes/test/e2e/storage/utils/utils.go
  vendor/k8s.io/kubernetes/test/integration/framework/perf_utils.go
  vendor/k8s.io/kubernetes/test/integration/framework/util.go
  vendor/k8s.io/kubernetes/test/utils/BUILD
  vendor/k8s.io/kubernetes/test/utils/create_resources.go
  vendor/k8s.io/kubernetes/test/utils/delete_resources.go
  vendor/k8s.io/kubernetes/test/utils/update_resources.go
  vendor/k8s.io/legacy-cloud-providers/vsphere/vclib/virtualmachine.go
  vendor/k8s.io/legacy-cloud-providers/vsphere/vsphere.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, vendor-update

#25542 Bug 1879445: Add a route annotation for Samesite
  images/router/haproxy/Dockerfile
  images/router/haproxy/RPM-GPG-KEY-CentOS-SIG-PaaS
  images/router/haproxy/centos-openshift-origin.repo
  images/router/haproxy/conf/haproxy-config.template
  images/router/haproxy/rhel-server-ose.repo
  pkg/router/template/configmanager/haproxy/manager.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#25574 Bug 1838751: oVirt, enable Skipped network tests
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#25663 Bug 1894011: images/router: Add ART specific Dockerfile
  images/router/haproxy/Dockerfile.art
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#25447 Bug 1872726: [3.11] Upstream: 89160: Remove potentially unhealthy symlink only for dead containers
  vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_gc.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/legacy.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#25501 Bug 1878795: UPSTREAM: 89160 Only Remove unhealthy symlink for dead containers
  vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_gc.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/legacy.go
  vendor/k8s.io/kubernetes/pkg/kubelet/remote/remote_runtime.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, ok-to-test, vendor-update

#25603 [release-4.5] Bug 1880326: Backport disruption test improvements
  pkg/test/ginkgo/cmd_runtest.go
  pkg/test/ginkgo/junit.go
  pkg/test/ginkgo/result/result.go
  pkg/test/ginkgo/status.go
  pkg/test/ginkgo/test.go
  test/e2e/upgrade/monitor.go
  test/e2e/upgrade/upgrade.go
  test/extended/dr/quorum_restore.go
  test/extended/util/annotate/annotate.go
  test/extended/util/disruption/disruption.go
  test/extended/util/test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#25653 Remove CSI driver installation from openshift-tests
  cmd/openshift-tests/csi.go
  cmd/openshift-tests/e2e.go
  test/extended/csi/install.go
  test/extended/testdata/bindata.go
  test/extended/testdata/csi/OWNERS
  test/extended/testdata/csi/README.md
  test/extended/testdata/csi/aws-ebs/install-template.yaml
  test/extended/testdata/csi/aws-ebs/manifest.yaml
  test/extended/testdata/csi/aws-ebs/storageclass.yaml
Labels: approved, lgtm

#25661 fix/re-enable template e2e dependent on php; adjust cmds/bindata for php changes; backport 4.x image ecosystem stability fixes to 3.11
  examples/image-streams/image-streams-centos7.json
  examples/image-streams/image-streams-rhel7.json
  examples/quickstarts/cakephp-mysql-persistent.json
  examples/quickstarts/cakephp-mysql.json
  pkg/oc/clusterup/manifests/bindata.go
  test/cmd/newapp.sh
  test/extended/builds/build_pruning.go
  test/extended/image_ecosystem/s2i_php.go
  test/extended/image_ecosystem/s2i_python.go
  test/extended/image_ecosystem/s2i_ruby.go
  test/extended/image_ecosystem/sample_repos.go
  test/extended/templates/templateinstance_readiness.go
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/build-pruning/successful-build-config.yaml
Labels: approved, lgtm

#25671 rename 'foo' build arg to avoid conflicts with 'foo' env's in the tools image
  test/extended/builds/start.go
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/test-build.yaml
Labels: approved, lgtm

#25673 Bug 1896188: bump wait timeout for build completion in oc debug test
  test/extended/cli/debug.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25497 IR-137: Awaiting for operators rollout to complete
  test/extended/images/imagestreamimport.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#25623 [release-3.11] Bug 1890545: Backport Fix decreasing metric counters when reloading HAProxy
  pkg/router/metrics/haproxy/haproxy.go
  pkg/router/metrics/haproxy/haproxy_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#25678 Bug 1895537: Image extract tests should check results of ImageStreamImport
  test/extended/images/extract.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25693 hello-openshift: Set BZ component in OWNERS
  images/hello-openshift/OWNERS
Labels: approved, lgtm

#25652 Add e2e testing of server-side apply for openshift types
  test/extended/apiserver/apply.go
  test/extended/etcd/etcd_storage_path.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/client.go
Labels: approved, lgtm

#25680 Make oc mirror tests aware of HTTP/2
  test/extended/images/mirror.go
Labels: approved, lgtm

#25635 [release-4.5] Bug 1828858: use net/http instead of client-go for e2e PDB test
  test/e2e/upgrade/service/service.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#25687 Reword CNV as OpenShift Virtualization
  cmd/openshift-tests/storagecaps.go
Labels: approved, lgtm

#25656 Bug 1852695: CVE-2020-8559 compromised node could escalate to cluster level privileges
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/net/http.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/net/http_test.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/proxy/upgradeaware.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/proxy/upgradeaware_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm, vendor-update

#25679 IR-152: Monitor availability of image registry during upgrades
  test/e2e/upgrade/upgrade.go
  test/extended/util/disruption/imageregistry/imageregistry.go
Labels: approved, lgtm

#25703 hello-openshift: Make request-port header spec compliant
  examples/hello-openshift/hello_openshift.go
Labels: approved, lgtm

#25698 Bug 1899721: HPA: Ignore deleted pods.
  vendor/k8s.io/kubernetes/pkg/controller/podautoscaler/replica_calculator.go
  vendor/k8s.io/kubernetes/pkg/controller/podautoscaler/replica_calculator_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, vendor-update

#25690 Bug 1898118: Logging more during ephemeral registry deployment
  test/extended/images/imagestreamimport.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25689 Bug 1887509: e2e: node: filter out worker nodes without MCD
  test/extended/topology_manager/resourcealign.go
  test/extended/topology_manager/utils.go
  test/extended/util/pods.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#25701 Bug 1900239: bump(*): Skip "subPath should be able to unmount" NFS test
  go.mod
  go.sum
  test/extended/util/annotate/generated/zz_generated.annotations.go
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccadmission/admission.go
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccmatching/provider.go
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccmatching/types.go
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/util/sort/bypriority.go
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/util/sort/byrestrictions.go
  vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go
  vendor/k8s.io/apiserver/pkg/server/config.go
  vendor/k8s.io/apiserver/pkg/server/filters/BUILD
  vendor/k8s.io/apiserver/pkg/server/filters/timeout.go
  vendor/k8s.io/apiserver/pkg/server/filters/wrap.go
  vendor/k8s.io/cloud-provider/go.sum
  vendor/k8s.io/kubernetes/openshift-hack/e2e/annotate/rules.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/openshiftkubeapiserver/flags.go
  vendor/k8s.io/kubernetes/pkg/kubeapiserver/server/insecure_handler.go
  vendor/k8s.io/kubernetes/pkg/kubelet/BUILD
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_server_journal.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_server_journal_linux.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_server_journal_others.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_server_journal_windows.go
  vendor/k8s.io/kubernetes/pkg/kubelet/metrics/metrics.go
  vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go
  vendor/k8s.io/kubernetes/test/e2e/storage/persistent_volumes.go
  vendor/k8s.io/kubernetes/test/integration/etcd/data.go
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/k8s.io/legacy-cloud-providers/openstack/openstack_volumes.go
  vendor/k8s.io/legacy-cloud-providers/vsphere/vclib/connection.go
  vendor/k8s.io/legacy-cloud-providers/vsphere/vclib/vsphere_metrics.go
  vendor/k8s.io/legacy-cloud-providers/vsphere/vsphere.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, vendor-update

#25704 [sig-cli][Feature:LegacyCommandTests][Disruptive][Serial] test-cmd: adjust tests to rebased 1.20-beta.2 oc command
  test/extended/testdata/bindata.go
  test/extended/testdata/cmd/test/cmd/config.sh
  test/extended/testdata/cmd/test/cmd/convert.sh
  test/extended/testdata/cmd/test/cmd/edit.sh
  test/extended/testdata/cmd/test/cmd/secrets.sh
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#25702 Bug 1900030: Fix monitoring availability of image registry
  test/extended/util/disruption/imageregistry/imageregistry.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#25655 UPSTREAM: <carry>: Bug 1893156: include / prefix in instance ID output
  vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/openstack/openstack_instances.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm, vendor-update

#25709 e2e: add useraccessoauthtokens RBAC
  test/extended/authorization/rbac/groups_default_rules.go
Labels: approved, lgtm

#25712 e2e/cli: move policy-storage-admin.sh to proper e2e & drop rsync.sh
  test/extended/cli/admin.go
  test/extended/testdata/bindata.go
  test/extended/testdata/cmd/test/cmd/policy-storage-admin.sh
  test/extended/testdata/cmd/test/cmd/rsync.sh
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#25708 Update oc explain tests
  test/extended/cli/explain.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm
