Repository openshift/origin, pull requests merged in 2020-04, with the labels that each got.

#24800 Add extended test to check buildah expand env vars in file paths
  test/extended/builds/dockerfile.go
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/docker-add/docker-add-env/Dockerfile
  test/extended/testdata/builds/docker-add/docker-add-env/foo
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#24799 UPSTREAM: 89592: e2e/network: get previous pod errors on NetworkPolicy test failure
  vendor/k8s.io/kubernetes/test/e2e/network/network_policy.go
Labels: approved, lgtm, vendor-update

#24808 Revert "Bug 1797788: add openshift-tests as a future delegation binary"
  Makefile
  cmd/openshift-tests-kubernetes/openshift-tests-kubernetes.go
  cmd/openshift-tests/csi.go
  cmd/openshift-tests/e2e.go
  cmd/openshift-tests/openshift-tests.go
  cmd/openshift-tests/provider.go
  cmd/openshift-tests/upgrade.go
  images/tests-base/Dockerfile.rhel
  images/tests-base/OWNERS
  images/tests-kubernetes/Dockerfile.rhel
  images/tests-kubernetes/OWNERS
  images/tests/Dockerfile.rhel
  test/extended/etcd/etcd_storage_path.go
Labels: approved, bugzilla/valid-bug, lgtm

#24795 Check if prometheus-operator is reporting metrics
  test/extended/prometheus/prometheus.go
Labels: approved, lgtm

#24814 test: Allow CSI tests to access fixtures pre run
  cmd/openshift-tests/csi.go
  cmd/openshift-tests/e2e.go
  cmd/openshift-tests/provider.go
  test/extended/csi/install.go
  test/extended/util/test.go
Labels: approved, lgtm

#24804 Bug 1819276: use rbac vs direct scc edit for s2i root bld test
  test/extended/builds/s2i_root.go
Labels: approved, bugzilla/valid-bug, lgtm

#24801 4.4: Bug 1818961: UPSTREAM: 89589: Wait for APIServer 'ok' forever during CSINode initialization during Kubelet init
  vendor/k8s.io/kubernetes/pkg/volume/csi/csi_plugin.go
  vendor/k8s.io/kubernetes/pkg/volume/csi/nodeinfomanager/nodeinfomanager.go
  vendor/k8s.io/kubernetes/pkg/volume/testing/testing.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, vendor-update

#24803 Metrics should be exposed over secure channel
  test/extended/prometheus/prometheus.go
Labels: approved, lgtm

#24811 monitor: Report node when events include it
  pkg/monitor/api.go
  pkg/monitor/event.go
  pkg/monitor/pod.go
Labels: approved, lgtm

#24832 Fix typo in 1.18.0-rc.1 publish rule
  publishing-kube-rules.yaml
  publishing-rules.yaml
Labels: approved, lgtm

#24728 Bug 1805588: Fix flaky olm test
  test/extended/operators/olm.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#24834 Bug 1814054: UPSTREAM: 89885: allow to read openstack cloud provider config from a secret
  vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/openstack/BUILD
  vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/openstack/metadata.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/openstack/openstack.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/openstack/openstack_instances.go
Labels: approved, bugzilla/valid-bug, lgtm, vendor-update

#24831 UPSTREAM: 88006: Unregister csiplugin even if socket path is gone
  vendor/k8s.io/kubernetes/pkg/kubelet/pluginmanager/cache/actual_state_of_world.go
  vendor/k8s.io/kubernetes/pkg/kubelet/pluginmanager/operationexecutor/operation_executor.go
  vendor/k8s.io/kubernetes/pkg/kubelet/pluginmanager/operationexecutor/operation_executor_test.go
  vendor/k8s.io/kubernetes/pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go
  vendor/k8s.io/kubernetes/pkg/kubelet/pluginmanager/reconciler/reconciler.go
  vendor/k8s.io/kubernetes/pkg/kubelet/pluginmanager/reconciler/reconciler_test.go
Labels: approved, lgtm, vendor-update

#24835 test: Enable a range of tests that are allegedly fixed
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm

#24830 Capture e2e events in monitor
  pkg/monitor/event.go
  pkg/monitor/pod.go
Labels: approved, lgtm

#24717 test/extended/builds: Setting Build Defaults should has effect on build pod
  test/extended/builds/cluster_config.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#24833 e2e/network: skip new session affinity timeout tests for OVNKubernetes
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm

#24848 make the flowcontrol storage tests variable depending upon discovery
  test/extended/etcd/etcd_storage_path.go
Labels: approved, lgtm

#24839 [release-4.4] Bug 1821334: Managed cluster should have no crashlooping pods in core namespaces over two minutes
  test/extended/marketplace/marketplace_diffname.go
  test/extended/marketplace/marketplace_lables.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#24844 Bug 1822514: tests: split API availability monitor into kube and OpenShift
  pkg/monitor/api.go
  test/e2e/upgrade/upgrade.go
  test/extended/util/disruption/controlplane/controlplane.go
Labels: approved, bugzilla/valid-bug, lgtm

#24841 [release-4.3] Bug 1821341: UPSTREAM: 88440: Report deleted pod status correctly
  vendor/k8s.io/kubernetes/pkg/kubelet/container/helpers.go
  vendor/k8s.io/kubernetes/pkg/kubelet/container/helpers_test.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_pods.go
  vendor/k8s.io/kubernetes/pkg/kubelet/status/status_manager.go
  vendor/k8s.io/kubernetes/test/e2e/node/BUILD
  vendor/k8s.io/kubernetes/test/e2e/node/pods.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#24847 sort expression
  hack/listtests/main.go
Labels: approved, lgtm, ok-to-test

#24857 test/extended: exclude ovnkube master/node metrics endpoints from secure test
  test/extended/prometheus/prometheus.go
Labels: approved, lgtm

#24543 Bug 1803083: 4.2: UPSTREAM: 87673: blank out value for unbounded client label
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/metrics/BUILD
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, priority/critical-urgent, size/XS

#24828 Bug 1820687: NS SCC annotations exist, else forbidden: unable to validate...
  test/extended/util/client.go
  test/extended/util/framework.go
Labels: approved, bugzilla/valid-bug, lgtm

#24852 Bug 1822515: 4.4 - tests: split API availability monitor into kube and OpenShift
  pkg/monitor/api.go
  test/e2e/upgrade/upgrade.go
  test/extended/util/disruption/controlplane/controlplane.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#24893 e2e requestheaders idp: fix ingress CA cert location
  test/extended/oauth/requestheaders.go
Labels: approved, lgtm

#24896 Bug 1826071: [marketplace] Remove CSC related tests
  test/extended/marketplace/marketplace_diffname.go
  test/extended/marketplace/marketplace_labels.go
Labels: approved, bugzilla/unspecified, bugzilla/valid-bug, lgtm

#24879 Bug 1826252: preserve integers decoding raw JSON values
  vendor/k8s.io/kube-openapi/pkg/util/proto/validation/types.go
  vendor/k8s.io/kubernetes/Godeps/Godeps.json
  vendor/k8s.io/kubernetes/go.mod
  vendor/k8s.io/kubernetes/go.sum
  vendor/k8s.io/kubernetes/staging/src/k8s.io/api/go.mod
  vendor/k8s.io/kubernetes/staging/src/k8s.io/api/go.sum
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/go.mod
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/go.sum
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/goopenapi_test.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/test/integration/defaulting_test.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/go.mod
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/go.sum
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/json/json.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/json/json_test.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/go.mod
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/go.sum
  vendor/k8s.io/kubernetes/staging/src/k8s.io/cli-runtime/go.mod
  vendor/k8s.io/kubernetes/staging/src/k8s.io/cli-runtime/go.sum
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/go.mod
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/go.sum
  vendor/k8s.io/kubernetes/staging/src/k8s.io/cloud-provider/go.mod
  vendor/k8s.io/kubernetes/staging/src/k8s.io/cloud-provider/go.sum
  vendor/k8s.io/kubernetes/staging/src/k8s.io/cluster-bootstrap/go.mod
  vendor/k8s.io/kubernetes/staging/src/k8s.io/cluster-bootstrap/go.sum
  vendor/k8s.io/kubernetes/staging/src/k8s.io/code-generator/go.mod
  vendor/k8s.io/kubernetes/staging/src/k8s.io/code-generator/go.sum
  vendor/k8s.io/kubernetes/staging/src/k8s.io/component-base/go.mod
  vendor/k8s.io/kubernetes/staging/src/k8s.io/component-base/go.sum
  vendor/k8s.io/kubernetes/staging/src/k8s.io/csi-translation-lib/go.mod
  vendor/k8s.io/kubernetes/staging/src/k8s.io/csi-translation-lib/go.sum
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/go.mod
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/go.sum
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-controller-manager/go.mod
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-controller-manager/go.sum
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-proxy/go.mod
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-proxy/go.sum
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-scheduler/go.mod
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-scheduler/go.sum
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kubectl/go.mod
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kubectl/go.sum
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kubelet/go.mod
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kubelet/go.sum
  vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/go.mod
  vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/go.sum
  vendor/k8s.io/kubernetes/staging/src/k8s.io/metrics/go.mod
  vendor/k8s.io/kubernetes/staging/src/k8s.io/metrics/go.sum
  vendor/k8s.io/kubernetes/staging/src/k8s.io/sample-apiserver/go.mod
  vendor/k8s.io/kubernetes/staging/src/k8s.io/sample-apiserver/go.sum
  vendor/k8s.io/kubernetes/staging/src/k8s.io/sample-cli-plugin/go.mod
  vendor/k8s.io/kubernetes/staging/src/k8s.io/sample-cli-plugin/go.sum
  vendor/k8s.io/kubernetes/staging/src/k8s.io/sample-controller/go.mod
  vendor/k8s.io/kubernetes/staging/src/k8s.io/sample-controller/go.sum
Labels: approved, bugzilla/unspecified, bugzilla/valid-bug, lgtm, vendor-update

#24868 Bug 1731263: Disable failing preemption e2es
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, bugzilla/low, bugzilla/valid-bug, lgtm

#24815 integration: fix TestOadmPodNetwork for CI changes
  test/integration/sdn_test.go
Labels: approved, lgtm

#24905 e2e: wait longer for authn operator to come up
  test/extended/oauth/requestheaders.go
Labels: approved, bugzilla/valid-bug, lgtm

#24819 Bug 1740604: UPSTREAM 89300: Expand the PVC validation messages
  vendor/k8s.io/kubernetes/pkg/apis/core/validation/validation.go
Labels: approved, bugzilla/valid-bug, kind/bug, lgtm, vendor-update

#24856 Bug 1826186: router: add gRPC interop end-2-end tests
  test/extended/router/grpc-interop.go
  test/extended/router/grpc-interop/Makefile
  test/extended/router/grpc-interop/README
  test/extended/router/grpc-interop/clientconn.go
  test/extended/router/grpc-interop/cluster/client/client.go
  test/extended/router/grpc-interop/cluster/go.mod
  test/extended/router/grpc-interop/cluster/go.sum
  test/extended/router/grpc-interop/cluster/server/server.go
  test/extended/router/grpc-interop/test-fixture-gen/gen.go
  test/extended/router/grpc-interop/test_utils.go
  test/extended/router/grpc-interop/testcases.go
  test/extended/testdata/bindata.go
  test/extended/testdata/router/router-grpc-interop.yaml
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, bugzilla/medium, bugzilla/valid-bug, lgtm

#24873 Bug 1810470: UPSTREAM: <drop> Increase timeout in volume expansion test
  vendor/k8s.io/kubernetes/test/e2e/framework/util.go
  vendor/k8s.io/kubernetes/test/e2e/storage/testsuites/volume_expand.go
Labels: approved, bugzilla/valid-bug, lgtm, vendor-update

#24889 Bug 1826499: IngressClass error test is flaky
  vendor/k8s.io/kubernetes/test/e2e/network/ingressclass.go
Labels: approved, bugzilla/high, bugzilla/valid-bug, lgtm, vendor-update

#24892 Bug 1824596: UPSTREAM: 90234: Remove PreStop hook from hostpath CSI driver
  vendor/k8s.io/kubernetes/test/e2e/generated/bindata.go
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-attacher.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-driverinfo.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-plugin.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-provisioner.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-resizer.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-snapshotter.yaml
Labels: approved, bugzilla/medium, bugzilla/valid-bug, lgtm, vendor-update

#24880 Bug 1813927: UPSTREAM: 89172: Fix mountOptions in iSCSI and FC volume plugins
  vendor/k8s.io/kubernetes/pkg/volume/fc/fc_test.go
  vendor/k8s.io/kubernetes/pkg/volume/fc/fc_util.go
  vendor/k8s.io/kubernetes/pkg/volume/iscsi/BUILD
  vendor/k8s.io/kubernetes/pkg/volume/iscsi/iscsi_util.go
Labels: approved, bugzilla/valid-bug, lgtm, vendor-update

#24891 Bug 1826502: PriorityClass tests can cause preemptions
  vendor/k8s.io/kubernetes/test/e2e/apimachinery/resource_quota.go
Labels: approved, bugzilla/high, bugzilla/valid-bug, lgtm, vendor-update

#24699 Bug 1813847: fixes configmap "extension-apiserver-authentication" not found
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/dynamiccertificates/configmap_cafile_content.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/dynamiccertificates/dynamic_cafile_content.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/dynamiccertificates/dynamic_serving_content.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/dynamiccertificates/static_content.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#24900 Bug 1823494: Storage tests should more carefully select zones for testing
  vendor/k8s.io/kubernetes/test/e2e/storage/drivers/in_tree.go
Labels: approved, bugzilla/high, bugzilla/valid-bug, lgtm, vendor-update

#24883 clarify test failure message
  test/extended/util/framework.go
Labels: approved, bugzilla/valid-bug, lgtm

#24817 Bug 1827414: e2e: Add ibmcloud provider, skips and fixes
  test/extended/apiserver/root_403.go
  test/extended/authentication/front_proxy.go
  test/extended/cli/mustgather.go
  test/extended/csrapprover/csrapprover.go
  test/extended/etcd/etcd_test_runner.go
  test/extended/machines/machines.go
  test/extended/machines/scale.go
  test/extended/oauth/oauthcertfallback.go
  test/extended/oauth/requestheaders.go
  test/extended/oauth/well_known.go
  test/extended/prometheus/prometheus.go
  test/extended/prometheus/prometheus_builds.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
  test/extended/util/client.go
  test/extended/util/framework.go
  test/extended/util/ibmcloud/provider.go
  test/extended/util/oauthserver/oauthserver.go
Labels: approved, bugzilla/medium, bugzilla/valid-bug, lgtm

#24901 [release-4.4] Bug 1826033: Ignore ImagePruningDisabled alert
  test/extended/prometheus/prometheus.go
Labels: approved, bugzilla/urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#24913 Bug 1825354: test/extended/router: Disable HTTP/2 tests
  test/extended/router/grpc-interop.go
  test/extended/router/h2spec.go
Labels: approved, bugzilla/high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#24904 Bug 1827751: Enables secure metrics tests for dns
  test/extended/prometheus/prometheus.go
Labels: approved, bugzilla/unspecified, bugzilla/valid-bug, lgtm

#24786 Bug 1828427: Add CI test to check for critical alerts post upgrade success
  test/e2e/upgrade/alert/alert.go
  test/e2e/upgrade/upgrade.go
  test/extended/prometheus/prometheus.go
  test/extended/prometheus/prometheus_builds.go
  test/extended/util/client.go
  test/extended/util/prometheus/helpers.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#24679 Bug 1826807: Add tests for topology manager in single and multisocket configurations
  test/extended/include.go
  test/extended/topology_manager/README.md
  test/extended/topology_manager/numa_alignment.go
  test/extended/topology_manager/resourcealign.go
  test/extended/topology_manager/utils.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, bugzilla/medium, bugzilla/valid-bug, lgtm, size/L

#24920 Bug 1761043: provides a temporal fix to improve CRD publishing e2e tests in an HA setup
  vendor/k8s.io/kubernetes/test/e2e/apimachinery/crd_publish_openapi.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, vendor-update

#24923 Bug 1826230: oc get --request-timeout: Timeout exceeded while reading body printed with -v=5
  test/extended/testdata/bindata.go
  test/extended/testdata/cmd/test/cmd/timeout.sh
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#24919 test: Do not create namespaces twice
  test/extended/util/client.go
Labels: approved, bugzilla/valid-bug, lgtm

#24922 test: Allow disruptive tests on any platform with machine APIs
  test/extended/dr/quorum_restore.go
Labels: approved, bugzilla/valid-bug, lgtm

#24930 Bug 1761043: provides a temporal fix to improve CRD publishing e2e tests in an HA setup
  vendor/k8s.io/kubernetes/test/e2e/apimachinery/crd_publish_openapi.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, vendor-update

#24813 Bug 1828280: Remove deprecated flags and commands from test-cmd
  test/extended/testdata/bindata.go
  test/extended/testdata/cmd/test/cmd/deployments.sh
  test/extended/testdata/cmd/test/cmd/policy-storage-admin.sh
  test/extended/testdata/cmd/test/cmd/policy.sh
  test/extended/testdata/cmd/test/cmd/projects.sh
  test/extended/testdata/cmd/test/cmd/secrets.sh
  test/extended/testdata/cmd/test/cmd/status.sh
  test/extended/testdata/cmd/test/cmd/templates.sh
  test/extended/testdata/cmd/test/cmd/volumes.sh
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#24932 adds kube publishing rules for origin-4.5-kubernetes-1.18.2
  publishing-kube-rules.yaml
Labels: approved, lgtm

#24927 Bug 1822286: Serializes k8s IngressClass test
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#24454 [release-4.2] Bug 1794854: UPSTREAM: 86195: Sync the status of static Pods
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_getters.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS
