Repository openshift/origin, pull requests merged in 2020-06, with the labels that each got.

#25011 improve disruption "failure" messaging
  test/extended/util/disruption/disruption.go
Labels: approved, lgtm

#24928 test/e2e/upgrade/service: Use 10m timeout for TestReachableHTTPWithMinSuccessCount
  test/e2e/upgrade/service/service.go
Labels: approved, lgtm

#25022 Fix testRemoteConnectivity error message
  test/extended/networking/internal_ports.go
Labels: approved, lgtm

#25057 Bug 1843407: oVirt, add oVirt as a provide to openshift tests
  cmd/openshift-tests/provider.go
  test/extended/util/ovirt/provider.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25049 [4.3] Bug 1822487: UPSTREAM: 89794: Clean up event messages for errors
  vendor/k8s.io/kubernetes/pkg/volume/glusterfs/glusterfs.go
  vendor/k8s.io/kubernetes/pkg/volume/quobyte/quobyte.go
  vendor/k8s.io/kubernetes/pkg/volume/scaleio/sio_client.go
  vendor/k8s.io/kubernetes/pkg/volume/storageos/storageos_util.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#25048 [4.4] Bug 1822488: UPSTREAM: 89794: Clean up event messages for errors
  vendor/k8s.io/kubernetes/pkg/volume/glusterfs/glusterfs.go
  vendor/k8s.io/kubernetes/pkg/volume/quobyte/quobyte.go
  vendor/k8s.io/kubernetes/pkg/volume/scaleio/sio_client.go
  vendor/k8s.io/kubernetes/pkg/volume/storageos/storageos_util.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm, vendor-update

#25038 Bug 1840872: UPSTREAM: 88440: Report deleted pod status correctly
  vendor/k8s.io/kubernetes/pkg/kubelet/container/helpers.go
  vendor/k8s.io/kubernetes/pkg/kubelet/container/helpers_test.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_pods.go
  vendor/k8s.io/kubernetes/pkg/kubelet/status/status_manager.go
  vendor/k8s.io/kubernetes/test/e2e/node/BUILD
  vendor/k8s.io/kubernetes/test/e2e/node/pods.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#25050 [4.2] Bug 1822486: UPSTREAM: 89794: Clean up event messages for errors
  vendor/k8s.io/kubernetes/pkg/volume/glusterfs/glusterfs.go
  vendor/k8s.io/kubernetes/pkg/volume/quobyte/quobyte.go
  vendor/k8s.io/kubernetes/pkg/volume/scaleio/sio_client.go
  vendor/k8s.io/kubernetes/pkg/volume/storageos/storageos_util.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#25041 Bug 1728130: Bump libseccomp-golang to v0.9.1
  glide.lock
  glide.yaml
  vendor/github.com/seccomp/libseccomp-golang/.gitignore
  vendor/github.com/seccomp/libseccomp-golang/CHANGELOG
  vendor/github.com/seccomp/libseccomp-golang/Makefile
  vendor/github.com/seccomp/libseccomp-golang/README
  vendor/github.com/seccomp/libseccomp-golang/SUBMITTING_PATCHES
  vendor/github.com/seccomp/libseccomp-golang/seccomp.go
  vendor/github.com/seccomp/libseccomp-golang/seccomp_internal.go
  vendor/github.com/seccomp/libseccomp-golang/seccomp_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#24909 [release-4.4] BUG 1824092: Managed cluster should grow and decrease when scaling different machineSets simultaneously (backport)
  test/extended/machines/scale.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#24971 Bug 1763340: ingress: targetPortForService: Use port name only
  pkg/route/controller/ingress/ingress.go
  pkg/route/controller/ingress/ingress_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25051 [3.11] Bug 1822491: UPSTREAM: 89794: Clean up event messages for errors
  vendor/k8s.io/kubernetes/pkg/volume/glusterfs/glusterfs.go
  vendor/k8s.io/kubernetes/pkg/volume/quobyte/quobyte.go
  vendor/k8s.io/kubernetes/pkg/volume/scaleio/sio_client.go
  vendor/k8s.io/kubernetes/pkg/volume/storageos/storageos_util.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25052 Bug 1842650: All NetworkPolicy tests currently being skipped on openshift-sdn
  cmd/openshift-tests/provider.go
  test/extended/util/cloud/cloud.go
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#25060 Bug 1843187: UPSTREAM: 91008: Do not swallow NotFound error for DeletePod in dsc.manage
  vendor/k8s.io/kubernetes/pkg/controller/BUILD
  vendor/k8s.io/kubernetes/pkg/controller/controller_utils.go
  vendor/k8s.io/kubernetes/pkg/controller/controller_utils_test.go
  vendor/k8s.io/kubernetes/pkg/controller/daemon/daemon_controller.go
  vendor/k8s.io/kubernetes/pkg/controller/job/job_controller.go
  vendor/k8s.io/kubernetes/pkg/controller/replicaset/replica_set.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, vendor-update

#25075 Bug 1839098: UPSTREAM: 91500: reduce race risk in kubelet for missing KUBERNETES_SERVICE_HOST
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_pods.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_pods_test.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm, vendor-update

#25053 pkg/test/ginkgo: Include flake retries in JUnit
  pkg/test/ginkgo/cmd_runsuite.go
Labels: approved, lgtm

#25078 Bug 1845188: Revert "UPSTREAM: <carry>: Disable by default the addition of service ca to token secrets
  vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/patch_satoken.go
  vendor/k8s.io/kubernetes/pkg/controller/serviceaccount/tokens_controller.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, group-lead-approved, lgtm, vendor-update

#25073 apiserver: verbosity 3 on termination and watch-termination binary
  cmd/watch-termination/main.go
  images/hyperkube/Dockerfile.rhel
  vendor/k8s.io/kubernetes/cmd/controller-manager/app/serve.go
  vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go
  vendor/k8s.io/kubernetes/cmd/kube-scheduler/app/server.go
  vendor/k8s.io/kubernetes/pkg/kubeapiserver/server/insecure_handler.go
  vendor/k8s.io/kubernetes/pkg/kubelet/server/server.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/config.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/filters/timeout_test.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/filters/wrap.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/httplog/httplog.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/httplog/httplog_test.go
  vendor/k8s.io/kubernetes/test/integration/framework/test_server.go
Labels: approved, lgtm, vendor-update

#25059 Bug 1838730: UPSTREAM: 91642: Adjust Azure e2e binding mode
  vendor/k8s.io/kubernetes/test/e2e/storage/drivers/in_tree.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, vendor-update

#25096 Remove dumpLogs for nonexistent DC - Jenkins e2e
  test/extended/builds/pipeline_origin_bld.go
Labels: approved, lgtm

#24984 add test for oauth client secret with plus
  test/extended/oauth/client_secret.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#25045 Bug 1835371: router/metrics: Fix haproxy_server_max_sessions test
  test/extended/router/metrics.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#25094 add kubepodcrashlooping to list of ignored alerts
  test/extended/prometheus/prometheus.go
Labels: approved, lgtm

#25086 watch-termination: add log rotation
  cmd/watch-termination/main.go
Labels: approved, lgtm

#25082 Bug 1845434: router/grpc-interop: switch to WaitForPodRunningSlow
  test/extended/router/grpc-interop.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25024 UPSTREAM: 91816: GC doesn't have to create monitors in the constructor
  vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/core.go
  vendor/k8s.io/kubernetes/pkg/controller/garbagecollector/garbagecollector.go
  vendor/k8s.io/kubernetes/pkg/controller/garbagecollector/garbagecollector_test.go
  vendor/k8s.io/kubernetes/test/integration/garbagecollector/garbage_collector_test.go
Labels: approved, lgtm, vendor-update

#25106 kube-apiserver: drain HTTP/2 early during termination
  cmd/watch-termination/main.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/config.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/filters/goaway.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/options/server_run_options.go
Labels: approved, lgtm, vendor-update

#25122 use golang-1.13 for the tests Dockerfile
  images/tests/Dockerfile.rhel
Labels: approved, lgtm

#25108 UPSTREAM: 91984: genericapiserver library must wait for server.Shutdown
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go
Labels: approved, lgtm, vendor-update

#25115 Measure container restarts over an interval instead of absolute
  test/extended/operators/cluster.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#25100 [test extended] don't be strict about set probe missing probe flag
  test/extended/testdata/bindata.go
  test/extended/testdata/cmd/test/cmd/basicresources.sh
Labels: approved, lgtm

#25107 e2e: Add other client-authn methods to token request test
  test/extended/oauth/client_secret.go
Labels: approved, lgtm

#25127 Bug 1845369: UPSTREAM: 91500: reduce race risk in kubelet for missing KUBERNETES_SERVICE_HOST
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_pods.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_pods_test.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, group-lead-approved, lgtm, vendor-update

#25071 Bug 1797244: test/extended/dr: update test to reflect new DR process
  test/extended/dr/common.go
  test/extended/dr/quorum_restore.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, vendor-update

#25123 UPSTREAM: <carry>: apiserver: log new connections during termination
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/config.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/filters/goaway.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/options/server_run_options.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/secure_serving.go
Labels: approved, lgtm, vendor-update

#25134 Bug 1809195: test/extended/prometheus: During transition, allow HTTP(S) for CVO
  test/extended/prometheus/prometheus.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#25091 Bug 1845549: manually patch scc/restricted and scc/anyuid for conformamce tests
  test/extended/conformance-k8s.sh
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#25149 Bug 1825372: Revert "Bug 1840872: UPSTREAM: 88440: Report deleted pod status correctly"
  vendor/k8s.io/kubernetes/pkg/kubelet/container/helpers.go
  vendor/k8s.io/kubernetes/pkg/kubelet/container/helpers_test.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_pods.go
  vendor/k8s.io/kubernetes/pkg/kubelet/status/status_manager.go
  vendor/k8s.io/kubernetes/test/e2e/node/BUILD
  vendor/k8s.io/kubernetes/test/e2e/node/pods.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#25146 Bug 1845778: [release-3.11] kubelet: block non-forwarded packets from crossing the localhost boundary
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_network.go
Labels: approved, lgtm

#25072 Bug 1844831: oVirt, skip network service tests
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#25126 apiserver: create LateConnections events on connections in the last 20% of graceful termination time
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go
Labels: approved, lgtm, vendor-update

#25121 Bug 1847185: fix: GetLabelsForVolume panic issue for azure disk PV
  vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/azure/azure_managedDiskController.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm, vendor-update

#25061 [release-4.5] Bug 1843462: UPSTREAM: 91008: Do not swallow NotFound error for DeletePod in dsc.manage
  vendor/k8s.io/kubernetes/pkg/controller/BUILD
  vendor/k8s.io/kubernetes/pkg/controller/controller_utils.go
  vendor/k8s.io/kubernetes/pkg/controller/controller_utils_test.go
  vendor/k8s.io/kubernetes/pkg/controller/daemon/daemon_controller.go
  vendor/k8s.io/kubernetes/pkg/controller/job/job_controller.go
  vendor/k8s.io/kubernetes/pkg/controller/replicaset/replica_set.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, group-lead-approved, lgtm, vendor-update

#25158 Bug 1847368: [release-4.5]: UPSTREAM: 92166: fix: GetLabelsForVolume panic issue for azure disk PV
  vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/azure/azure_managedDiskController.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, group-lead-approved, lgtm, priority/critical-urgent, vendor-update

#25159 Bug 1847419: [release-4.4] UPSTREAM: 92166: fix: GetLabelsForVolume panic issue for azure disk PV
  vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/azure/azure_managedDiskController.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm, priority/critical-urgent, vendor-update

#25138 Bug 1848622: [release-4.3]: UPSTREAM: 92166: fix: GetLabelsForVolume panic issue for azure disk PV
  vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/azure/azure_managedDiskController.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#25118 watch-termination: don't log oauth tokens
  cmd/watch-termination/main.go
Labels: approved, lgtm

#25135 Bug 1809195: test/extended/prometheus: Require HTTPS for the CVO
  test/extended/prometheus/prometheus.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#25137 Bug 1841035: Add volumesnapshotclass to default RBAC test
  test/extended/authorization/rbac/groups_default_rules.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25140 Bug 1831908: bump cadvisor for incorrect diskstats fix
  glide.lock
  glide.yaml
  vendor/github.com/google/cadvisor/fs/fs.go
  vendor/github.com/google/cadvisor/fs/fs_test.go
  vendor/github.com/google/cadvisor/fs/types.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm, vendor-update

#25141 Bug 1849175: UPSTREAM: 91569: kubelet: block non-forwarded packets from crossing the localhost boundary
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_network_linux.go
Labels: approved, lgtm, vendor-update

#25150 Bug 1848379: UPSTREAM: 89937: portAllocator sync local data before allocate
  vendor/k8s.io/kubernetes/pkg/registry/core/service/allocator/storage/storage.go
  vendor/k8s.io/kubernetes/pkg/registry/core/service/allocator/storage/storage_test.go
  vendor/k8s.io/kubernetes/pkg/registry/core/service/portallocator/BUILD
  vendor/k8s.io/kubernetes/test/integration/master/BUILD
  vendor/k8s.io/kubernetes/test/integration/master/kube_apiserver_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, vendor-update

#25153 Bug 1842660: 4.6: UPSTREAM: 91748: FieldManager: Reset if we receive nil or a list with one
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/validation/validation.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/validation/validation_test.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/create.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/fieldmanager.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/fieldmanager_test.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/internal/managedfields.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/internal/managedfields_test.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/structuredmerge.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/patch.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/update.go
  vendor/k8s.io/kubernetes/test/integration/apiserver/apply/apply_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, vendor-update

#25180 disable broken jenkins test
  test/extended/builds/pipeline_origin_bld.go
Labels: approved, bugzilla/valid-bug, group-lead-approved, lgtm

#24382 Bug 1741138: Add mandatory ifExists field to CL config, and add ignore-params flag
  test/extended/cluster/utils.go
  test/extended/testdata/bindata.go
  test/extended/testdata/cluster/master-vert.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#25181 [4.5] disable broken jenkins test
  test/extended/builds/pipeline_origin_bld.go
Labels: approved, bugzilla/valid-bug, group-lead-approved, lgtm

#25113 Update test owners
  test/extended/builds/OWNERS
  test/extended/imageapis/OWNERS
  test/extended/images/OWNERS
Labels: approved, lgtm

#24981 Bug 1814282: Storage e2es leaving namespaces/pods around
  vendor/k8s.io/kubernetes/test/e2e/framework/cleanup.go
  vendor/k8s.io/kubernetes/test/e2e/framework/pod/delete.go
  vendor/k8s.io/kubernetes/test/e2e/framework/util.go
  vendor/k8s.io/kubernetes/test/e2e/storage/csi_mock_volume.go
  vendor/k8s.io/kubernetes/test/e2e/storage/drivers/csi.go
  vendor/k8s.io/kubernetes/test/e2e/storage/external/external.go
  vendor/k8s.io/kubernetes/test/e2e/storage/testsuites/base.go
  vendor/k8s.io/kubernetes/test/e2e/storage/testsuites/testdriver.go
  vendor/k8s.io/kubernetes/test/e2e/storage/utils/create.go
  vendor/k8s.io/kubernetes/test/e2e/storage/utils/utils.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, sig/storage, vendor-update

#24991 Bug 1807822: UPSTREAM: 86009: kubelet: guarantee at most only one cinfo per containerID
  vendor/k8s.io/kubernetes/pkg/kubelet/stats/cadvisor_stats_provider.go
  vendor/k8s.io/kubernetes/pkg/kubelet/stats/cadvisor_stats_provider_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25035 Bug 1802849: Update to github.com/mtrmac/gpgme v0.1.2
  glide.lock
  glide.yaml
  vendor/github.com/mtrmac/gpgme/.appveyor.yml
  vendor/github.com/mtrmac/gpgme/.travis.yml
  vendor/github.com/mtrmac/gpgme/data.go
  vendor/github.com/mtrmac/gpgme/examples/decrypt.go
  vendor/github.com/mtrmac/gpgme/examples/encrypt.go
  vendor/github.com/mtrmac/gpgme/go.mod
  vendor/github.com/mtrmac/gpgme/go_gpgme.c
  vendor/github.com/mtrmac/gpgme/go_gpgme.h
  vendor/github.com/mtrmac/gpgme/gpgme.go
  vendor/github.com/mtrmac/gpgme/gpgme_test.go
  vendor/github.com/mtrmac/gpgme/testdata/gpghome/gpg-agent.conf
  vendor/github.com/mtrmac/gpgme/unset_agent_info.go
  vendor/github.com/mtrmac/gpgme/unset_agent_info_windows.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25189 UPSTREAM: <carry>: apiserver: log source in LateConnections event
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go
Labels: approved, lgtm, vendor-update

#25031 Bug 1850140: tests: extended: fix TM regression test
  test/extended/topology_manager/resourcealign.go
  test/extended/topology_manager/utils.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25166 Bug 1821280: Unable to provision vSphere volume
  vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/vsphere/BUILD
  vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/vsphere/nodemanager.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/vsphere/vsphere.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/vsphere/vsphere_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, vendor-update

#25187 test/etcd: wait for default service account to be avaiable
  test/extended/etcd/etcd_storage_path.go
Labels: approved, lgtm

#25190 watch-termination: create lock file on launch to catch every hard termination
  cmd/watch-termination/main.go
Labels: approved, lgtm, vendor-update

#25142 Bug 1845774: [release-4.5] kubelet: block non-forwarded packets from crossing the localhost boundary
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_network_linux.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, group-lead-approved, lgtm, vendor-update

#25179 Bug 1850109: remove problematic upstream client plugin test
  test/extended/builds/pipeline_origin_bld.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25192 watch-termination: create NonGracefulTermination event on next launch
  cmd/watch-termination/main.go
Labels: approved, lgtm

#25185 only patch authenticators when there's no webhook authenticators
  vendor/k8s.io/kubernetes/pkg/kubeapiserver/authenticator/config.go
Labels: approved, lgtm, vendor-update

#25062 [release-4.4] Bug 1843876: UPSTREAM: 91008: Do not swallow NotFound error for DeletePod in dsc.manage
  vendor/k8s.io/kubernetes/pkg/controller/BUILD
  vendor/k8s.io/kubernetes/pkg/controller/controller_utils.go
  vendor/k8s.io/kubernetes/pkg/controller/controller_utils_test.go
  vendor/k8s.io/kubernetes/pkg/controller/daemon/daemon_controller.go
  vendor/k8s.io/kubernetes/pkg/controller/job/job_controller.go
  vendor/k8s.io/kubernetes/pkg/controller/replicaset/replica_set.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, vendor-update

#25206 Bring back sig-cli tests
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm

#25047 Bug 1806034: UPSTREAM: 90638: Fix race in VSphere volume provisioning
  vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/vsphere/vclib/diskmanagers/vdm.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, vendor-update

#25165 Bug 1848687: Fix router metrics to be accurate in 4.4
  test/extended/router/metrics.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#25205 UPSTREAM: 89164: Fix data race issue in unit test
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/storage/cacher/cacher_whitebox_test.go
Labels: approved, lgtm, vendor-update

#25109 Bug 1839933: UPSTREAM: 91307: CSI: Modify VolumeAttachment check to use Informer/Cache
  vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/core.go
  vendor/k8s.io/kubernetes/pkg/controller/volume/attachdetach/attach_detach_controller.go
  vendor/k8s.io/kubernetes/pkg/controller/volume/attachdetach/attach_detach_controller_test.go
  vendor/k8s.io/kubernetes/pkg/volume/csi/BUILD
  vendor/k8s.io/kubernetes/pkg/volume/csi/csi_attacher.go
  vendor/k8s.io/kubernetes/pkg/volume/csi/csi_attacher_test.go
  vendor/k8s.io/kubernetes/pkg/volume/csi/csi_plugin.go
  vendor/k8s.io/kubernetes/pkg/volume/csi/csi_plugin_test.go
  vendor/k8s.io/kubernetes/pkg/volume/csi/csi_test.go
  vendor/k8s.io/kubernetes/pkg/volume/csi/nodeinfomanager/nodeinfomanager_test.go
  vendor/k8s.io/kubernetes/pkg/volume/csi/testing/testing.go
  vendor/k8s.io/kubernetes/pkg/volume/plugins.go
  vendor/k8s.io/kubernetes/pkg/volume/testing/testing.go
  vendor/k8s.io/kubernetes/test/integration/volume/attach_detach_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, vendor-update

#25161 [release-4.4] Bug 1829327: annotations exist, else forbidden: unable to validate
  test/extended/util/client.go
  test/extended/util/framework.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#24998 Provide a basic test for secondary interface naming metrics
  test/extended/prometheus/prometheus.go
  test/extended/prometheus/secondary_network.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#25199 UPSTREAM: <carry>: apiserver: skip local IPs for LateConnections
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/config.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/patch_genericapiserver.go
Labels: approved, lgtm, vendor-update

#25110 Bug 1847089: UPSTREAM: 86691: fix: azure disk could not mounted on Standard_DC4s/DC2s
  vendor/k8s.io/kubernetes/pkg/volume/azure_dd/azure_common_linux.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#25219 UPSTREAM: <carry>: Bug 1852056: change etcd health check timeout to 10s
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, vendor-update

#25225 Bug 1852526: test: topology manager: temporarily disable broken tests
  test/extended/topology_manager/resourcealign.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm, priority/critical-urgent
