Repository openshift/origin, pull requests merged in 2020-10, with the labels that each got.

#25573 bug 1884245: add test for failing network sandbox creation
  pkg/test/ginkgo/synthentic_tests.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#25576 bug 1884252: add test for systemd timeouts
  pkg/test/ginkgo/synthentic_tests.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#25557 Bug 1883235: Adjust wait duration for marketplace test
  test/extended/marketplace/marketplace_labels.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#25538 Bug 1881529: openshift-sdn: bump EgressNetworkPolicyMaxRules to 1000
  pkg/network/apis/network/types.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#25575 Bug 1884229: test: add more debug info when we fail to wait for service account
  test/extended/util/framework.go
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#25489 Bug 1877346: KubeAPIErrorsHigh firing due to too large resource version
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/storage/errors.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/cache/reflector.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/cache/reflector_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, vendor-update

#25565 Bug 1873043: Fix annotation generation
  cmd/openshift-tests/upgrade.go
  go.mod
  go.sum
  test/extended/util/annotate/generated/zz_generated.annotations.go
  vendor/k8s.io/apiserver/pkg/audit/request.go
  vendor/k8s.io/apiserver/pkg/server/patch_genericapiserver.go
  vendor/k8s.io/kubernetes/openshift-hack/e2e/annotate/annotate.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, vendor-update

#25568 Bug 1882750: extended/apiserver: add test looking out for GracefulTerminationTimeout events
  test/extended/apiserver/graceful_termination.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#25579 Bug 1881144: Fix Cinder e2e tests not to leak volumes
  go.mod
  go.sum
  vendor/k8s.io/kubernetes/test/e2e/storage/drivers/in_tree.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm, vendor-update

#25494 Update OWNERS
  OWNERS
Labels: approved, lgtm

#25564 test: extended: add Late systemd timeout test
  test/extended/include.go
  test/extended/pods/systemd.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#25009 Bug 1791520: CVE-2018-1002102: Unvalidated redirect
  vendor/k8s.io/kubernetes/pkg/kubelet/server/server_test.go
  vendor/k8s.io/kubernetes/pkg/registry/core/pod/rest/log.go
  vendor/k8s.io/kubernetes/pkg/registry/core/pod/rest/subresources.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/httpstream/spdy/roundtripper.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/httpstream/spdy/roundtripper_test.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/net/http.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/net/http_test.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/proxy/upgradeaware.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/registry/generic/rest/streamer.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/registry/generic/rest/streamer_test.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/transport/spdy/spdy.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/apiserver/handler_proxy.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#25437 test: add error output for build logs
  test/extended/util/framework.go
Labels: approved, lgtm

#25582 skip service type load balancer upgrade test on ovirt
  test/e2e/upgrade/service/service.go
Labels: approved, lgtm

#25552 image_ecosystem: reinstate nodejs test with postgresql based app
  test/extended/image_ecosystem/sample_repos.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#25400 Bug 1867800: Make EBS attachDisk idempotent
  test/extended/util/annotate/generated/zz_generated.annotations.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/aws/aws.go
  vendor/k8s.io/kubernetes/test/e2e/storage/pd.go
  vendor/k8s.io/kubernetes/test/e2e/storage/utils/BUILD
  vendor/k8s.io/kubernetes/test/e2e/storage/utils/ebs.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, sig/storage, vendor-update

#25560 Bug 1860789: test: Report an error message when a pod fails in a cmd test
  test/extended/util/framework.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#25583 hello-openshift: fix base images
  images/hello-openshift/Dockerfile.rhel
Labels: approved, lgtm

#25481 Bug 1868490: upgrade test use LoadBalancers with ExternalTrafficPolicy set to Local
  test/e2e/upgrade/service/service.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#25496 Bug 1855325: Move checking telemetry data sending to later stages
  test/extended/prometheus/prometheus.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#25594 add event monitor test for kube-apiserver not being shutdown gracefully
  pkg/test/ginkgo/synthentic_tests.go
Labels: approved, lgtm

#25469 Bug 1886488: move jenkins e2e nfs setup from docker.io to quay.io image
  test/extended/util/nfs.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25591 bug 1886174: skip test during skew testing that won't run on 4.6
  test/extended/authorization/rbac/groups_default_rules.go
  test/extended/cli/mustgather.go
  test/extended/oauth/expiration.go
  test/extended/prometheus/prometheus.go
  vendor/k8s.io/kubernetes/test/e2e/apps/disruption.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, vendor-update

#25471 test: improve handling of pending pods crashloop detection test
  test/extended/operators/cluster.go
Labels: approved, lgtm

#25566 Bug 1879057: e2e: skip write/read cache when running Block-mode RWX PVC tests
  go.mod
  go.sum
  vendor/k8s.io/kubernetes/test/e2e/framework/pod/create.go
  vendor/k8s.io/kubernetes/test/e2e/storage/testsuites/multivolume.go
  vendor/k8s.io/kubernetes/test/e2e/storage/utils/utils.go
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, vendor-update

#25592 test: Increase allowed telemetry series by 100
  test/extended/prometheus/prometheus.go
Labels: approved, lgtm

#25169 Move admin.sh to a proper e2e
  test/extended/cli/adm.go
  test/extended/cli/admin.go
  test/extended/image_ecosystem/sample_repos.go
  test/extended/operators/olm.go
  test/extended/testdata/bindata.go
  test/extended/testdata/cmd/test/cmd/admin.sh
  test/extended/testdata/cmd/test/cmd/testdata/app-scenarios/README.md
  test/extended/testdata/cmd/test/cmd/testdata/app-scenarios/docker-compose/complex/app/Dockerfile
  test/extended/testdata/cmd/test/cmd/testdata/app-scenarios/docker-compose/complex/docker-compose.generated.yaml
  test/extended/testdata/cmd/test/cmd/testdata/app-scenarios/docker-compose/complex/docker-compose.imported.yaml
  test/extended/testdata/cmd/test/cmd/testdata/app-scenarios/docker-compose/complex/docker-compose.yml
  test/extended/testdata/cmd/test/cmd/testdata/app-scenarios/docker-compose/complex/nginx/Dockerfile
  test/extended/testdata/cmd/test/cmd/testdata/app-scenarios/docker-compose/wordpress/docker-compose.yml
  test/extended/testdata/cmd/test/cmd/testdata/app-scenarios/k8s-lonely-pod.json
  test/extended/testdata/cmd/test/cmd/testdata/app-scenarios/k8s-sample-app.json
  test/extended/testdata/cmd/test/cmd/testdata/app-scenarios/k8s-service-pod-no-rc.json
  test/extended/testdata/cmd/test/cmd/testdata/app-scenarios/k8s-service-with-nothing.json
  test/extended/testdata/cmd/test/cmd/testdata/app-scenarios/k8s-unserviced-rc.json
  test/extended/testdata/cmd/test/cmd/testdata/app-scenarios/new-project-deployed-app.yaml
  test/extended/testdata/cmd/test/cmd/testdata/app-scenarios/new-project-no-build.yaml
  test/extended/testdata/cmd/test/cmd/testdata/app-scenarios/new-project-one-build.yaml
  test/extended/testdata/cmd/test/cmd/testdata/app-scenarios/new-project-two-deployment-configs.yaml
  test/extended/testdata/cmd/test/cmd/testdata/app-scenarios/petset.yaml
  test/extended/testdata/cmd/test/cmd/testdata/roles/empty-role.yaml
  test/extended/testdata/cmd/test/cmd/testdata/roles/policy-clusterroles.yaml
  test/extended/testdata/cmd/test/cmd/testdata/roles/policy-roles.yaml
  test/extended/testdata/roles/policy-clusterroles.yaml
  test/extended/testdata/roles/policy-roles.yaml
  test/extended/testdata/stable-busybox.yaml
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/client.go
  test/extended/util/jenkins/ref.go
Labels: approved, lgtm

#25362 Add a new FIPS test
  test/extended/security/fips.go
  test/extended/topology_manager/utils.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/pods.go
Labels: approved, lgtm

#25609 hello-openshift: Echo listening port in HTTP responses via headers
  examples/hello-openshift/hello_openshift.go
Labels: approved, lgtm

#25543 Bug 1882033: UPSTREAM: 94112: Remove canonicalization of endpoints by endpoints controller for better comparison
  vendor/k8s.io/kubernetes/pkg/controller/endpoint/endpoints_controller.go
  vendor/k8s.io/kubernetes/pkg/controller/endpoint/endpoints_controller_test.go
  vendor/k8s.io/kubernetes/pkg/registry/core/endpoint/strategy.go
  vendor/k8s.io/kubernetes/test/integration/endpoints/endpoints_test.go
  vendor/k8s.io/kubernetes/test/integration/endpoints/main_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, vendor-update

#25295 add a security test to verify capabilities
  test/extended/security/scc.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#25401 Bug 1867803: Make EBS AttachDisk idempotent
  test/extended/util/annotate/generated/zz_generated.annotations.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/aws/aws.go
  vendor/k8s.io/kubernetes/test/e2e/storage/pd.go
  vendor/k8s.io/kubernetes/test/e2e/storage/utils/BUILD
  vendor/k8s.io/kubernetes/test/e2e/storage/utils/ebs.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, sig/storage, vendor-update

#25605 tests/extended/OWNERS: add ashcrow to approvers
  test/extended/OWNERS
Labels: approved, lgtm

#25607 fail on pods moving back to pending in 4.7 and later
  pkg/test/ginkgo/synthentic_tests.go
Labels: approved, lgtm

#25610 handle cases where pod sandboxes fail after pod deletion
  pkg/test/ginkgo/synthentic_tests.go
Labels: approved, lgtm

#25615 fix typo in word: strategy
  README.md
Labels: approved, lgtm, ok-to-test

#25595 Bug 1890141: move off docker.io in templates/builds/jenkins tests
  test/extended/builds/multistage.go
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/build-postcommit/sti.yaml
  test/extended/testdata/builds/build-secrets/test-docker-build.json
  test/extended/testdata/builds/build-secrets/test-s2i-build.json
  test/extended/testdata/builds/build-timing/test-docker-build.json
  test/extended/testdata/builds/build-timing/test-s2i-build.json
  test/extended/testdata/builds/incremental-auth-build.json
  test/extended/testdata/builds/statusfail-badcontextdirs2i.yaml
  test/extended/testdata/builds/statusfail-failedassemble.yaml
  test/extended/testdata/builds/statusfail-fetchimagecontentdocker.yaml
  test/extended/testdata/builds/statusfail-fetchsourcedocker.yaml
  test/extended/testdata/builds/statusfail-fetchsources2i.yaml
  test/extended/testdata/builds/statusfail-genericreason.yaml
  test/extended/testdata/builds/statusfail-oomkilled.yaml
  test/extended/testdata/builds/statusfail-postcommithook.yaml
  test/extended/testdata/builds/statusfail-pushtoregistry.yaml
  test/extended/testdata/builds/test-auth-build.yaml
  test/extended/testdata/builds/test-bc-with-pr-ref.yaml
  test/extended/testdata/builds/test-build-cluster-config.yaml
  test/extended/testdata/builds/test-build-proxy.yaml
  test/extended/testdata/builds/test-build-revision.json
  test/extended/testdata/builds/test-build.yaml
  test/extended/testdata/builds/test-cds-sourcebuild.json
  test/extended/testdata/builds/test-context-build.json
  test/extended/testdata/builds/test-docker-build-pullsecret.json
  test/extended/testdata/builds/test-docker-build.json
  test/extended/testdata/builds/test-docker-no-outputname.json
  test/extended/testdata/builds/test-env-build.json
  test/extended/testdata/builds/test-imagechangetriggers.yaml
  test/extended/testdata/builds/test-nosrc-build.json
  test/extended/testdata/builds/test-s2i-build-quota.json
  test/extended/testdata/builds/test-s2i-build.json
  test/extended/testdata/builds/test-s2i-no-outputname.json
  test/extended/testdata/builds/valuefrom/failed-sti-build-value-from-config.yaml
  test/extended/testdata/builds/valuefrom/successful-sti-build-value-from-config.yaml
  test/extended/testdata/gssapi/proxy/gssapiproxy-buildconfig.yaml
  test/extended/testdata/image/test-image.json
  test/extended/testdata/imagestreamtag-jenkins-slave-pods.yaml
  test/extended/testdata/jenkins-plugin/multitag-template.json
  test/extended/testdata/long_names/fixture.json
  test/extended/testdata/run_policy/parallel-bc.yaml
  test/extended/testdata/run_policy/serial-bc.yaml
  test/extended/testdata/run_policy/serial-latest-only-bc.yaml
  test/extended/testdata/signer-buildconfig.yaml
  test/extended/testdata/templates/templateinstance_readiness.yaml
  test/integration/testdata/test-buildcli.json
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25608 tighten scc test to start failing on more than six pods failing
  test/extended/authorization/scc.go
  test/extended/security/fips.go
  test/extended/util/client.go
Labels: approved, lgtm

#25461 bug 1857268: UPSTREAM: 94252: If firstTimestamp is not set use eventTime when printing event
  vendor/k8s.io/kubernetes/pkg/printers/internalversion/printers.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm, vendor-update

#25556 Bug 1879192: Make offline volume expansion tests more robust
  vendor/k8s.io/kubernetes/pkg/controller/volume/expand/BUILD
  vendor/k8s.io/kubernetes/pkg/controller/volume/expand/expand_controller.go
  vendor/k8s.io/kubernetes/pkg/controller/volume/expand/expand_controller_test.go
  vendor/k8s.io/kubernetes/test/e2e/storage/testsuites/volume_expand.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm, sig/storage, vendor-update

#25618 Enable build root from repo
  .ci-operator.yaml
Labels: approved, lgtm

#25581 Fix network test exclusion
  go.mod
  go.sum
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
  vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go
  vendor/k8s.io/kubernetes/openshift-hack/e2e/annotate/rules.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/openshiftkubeapiserver/patch.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/openshiftkubeapiserver/sdn_readyz_wait.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_pods.go
  vendor/k8s.io/kubernetes/pkg/volume/rbd/rbd_util.go
  vendor/k8s.io/kubernetes/test/e2e/network/network_policy.go
  vendor/k8s.io/kubernetes/test/e2e/node/pods.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update

#25588 Fix skipping of SDN tests
  test/extended/networking/util.go
Labels: approved, lgtm

#25616 [release-3.11] Bug 1889868: Clean up 3.11.z build tests
  pkg/build/builder/docker_test.go
  pkg/build/builder/sti_test.go
  test/extended/builds/pipeline.go
  test/extended/builds/secrets.go
  test/extended/builds/start.go
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/statusfail-postcommithook.yaml
  test/extended/testdata/builds/statusfail-pushtoregistry.yaml
  test/extended/testdata/builds/test-build-app/Dockerfile
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#24958 Add mirror.centos.org repository to get the latest haproxy version
  images/router/haproxy/Dockerfile
  images/router/haproxy/RPM-GPG-KEY-CentOS-SIG-PaaS
  images/router/haproxy/centos-openshift-origin.repo
Labels: approved, lgtm, ok-to-test

#25529 [Release-3.11] Bug 1881133: haproxy 503 error page: replace all LF by CRLF to be fully RFC compliant
  images/router/haproxy/conf/error-page-503.http
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25392 Bug 1888004: [release-4.4] move image ecosystem e2e suite from centos to rhel; create rhel only jenkins e2e suite
  cmd/openshift-tests/e2e.go
  test/extended/builds/pipeline_origin_bld_rhelimagesonly.go
  test/extended/image_ecosystem/s2i_images.go
  test/extended/image_ecosystem/scl.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/url/url.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#25520 Bug 1883345: [release-4.5] Re-enable skipped conformance tests for IBM Cloud
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, cherry-pick-approved, lgtm

#25628 Bug 1887850: update SCC test to either pass or fail, but never flake
  test/extended/authorization/scc.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25606 Bug 1886620: deflake e2e test "Application behind service load balancer with PDB is not disrupted "
  test/e2e/upgrade/service/service.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#25620 check apiserver uptime with both new and re-used connections
  cmd/openshift-tests/upgrade.go
  pkg/monitor/api.go
  test/e2e/upgrade/upgrade.go
  test/extended/dr/machine_recover.go
  test/extended/util/disruption/controlplane/controlplane.go
Labels: approved, lgtm

#25633 Bug 1883642: Give informers time to observe limitrange
  test/extended/images/imagestream_admission.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#25638 Move debug.sh & timeout.sh to a proper e2e
  test/extended/cli/debug.go
  test/extended/cli/timeout.go
  test/extended/testdata/bindata.go
  test/extended/testdata/cmd/test/cmd/debug.sh
  test/extended/testdata/cmd/test/cmd/timeout.sh
  test/extended/testdata/test-deployment-config.yaml
  test/extended/testdata/test-replication-controller.yaml
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/framework.go
Labels: approved, lgtm

#25640 disable cakephp while cuppett/scl sort out new upstream regression
  test/extended/image_ecosystem/s2i_php.go
  test/extended/image_ecosystem/sample_repos.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#25536 [release-4.5] Bug 1881351: KCM and KS graceful termination
  vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go
  vendor/k8s.io/kubernetes/cmd/kube-scheduler/app/server.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, vendor-update

#25625 Bug 1882556: Access git over https for tests
  examples/sample-app/github-webhook-example.json
  test/extended/builds/clone_git_protocol.go
  test/extended/builds/controllers.go
  test/extended/images/imagechange_buildtrigger.go
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/test-build-revision.json
  test/extended/testdata/builds/test-build.yaml
  test/extended/testdata/builds/webhook/generic/testdata/push-generic-envs.json
  test/extended/testdata/builds/webhook/generic/testdata/push-generic-envs.yaml
  test/extended/testdata/builds/webhook/generic/testdata/push-generic.json
  test/extended/testdata/builds/webhook/github/testdata/pushevent-not-master-branch.json
  test/extended/testdata/builds/webhook/github/testdata/pushevent.json
  test/extended/testdata/cmd/test/cmd/env.sh
  test/extended/testdata/cmd/test/cmd/testdata/test-bc.yaml
  test/extended/testdata/cmd/test/cmd/testdata/test-buildcli.json
  test/extended/testdata/long_names/fixture.json
  test/extended/testdata/run_policy/parallel-bc.yaml
  test/extended/testdata/run_policy/serial-bc.yaml
  test/extended/testdata/run_policy/serial-latest-only-bc.yaml
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/proxy.go
  test/integration/testdata/test-buildcli-beta2.json
  test/integration/testdata/test-buildcli.json
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#25645 an e2e for testing "openshift.io/imagestreams" count quota
  test/extended/quota/resourcequota.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#25644 move cakephp e2e skip down a level to make openshift-tests happy
  test/extended/image_ecosystem/s2i_php.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#25614 Evaluate storage metrics of an e2e test.
  test/e2e/upgrade/alert/alert.go
  test/extended/prometheus/prometheus.go
  test/extended/prometheus/prometheus_builds.go
  test/extended/prometheus/storage.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/prometheus/helpers.go
Labels: approved, lgtm
