Repository openshift/origin, pull requests merged in 2020-12, with the labels that each got.

#25717 Update etcd data locations for kube 1.20.0-beta.2
  test/extended/etcd/etcd_storage_path.go
Labels: approved, lgtm

#25688 Bug 1887488: e2e: node: fix ping tester pod
  test/extended/topology_manager/README.md
  test/extended/topology_manager/resourcealign.go
  test/extended/topology_manager/utils.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#25732 Temporary disable tests broken upstream
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm

#25725 Replace oc --config with oc --kubeconfig
  examples/pruner/README.md
  examples/sample-app/README.md
  hack/lib/cleanup.sh
  hack/lib/start.sh
  test/extended/cmd.sh
  test/extended/testdata/bindata.go
  test/extended/testdata/cmd/test/cmd/login.sh
Labels: approved, lgtm

#25715 [sig-auth][Feature:LDAP][Serial] ldap group sync can sync groups from ldap: do not oc cp nonexisting folders
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm

#25700 Bug 1884195: test/extended/operators: add etcd-quorum-guard to unevictable whitelist
  test/extended/operators/tolerations.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, cherry-pick-approved, lgtm

#25730 Fix cluster quota test to tolerate a new default config map in every namespace
  test/extended/quota/clusterquota.go
  test/extended/util/wait.go
Labels: approved, lgtm

#25731 Tolerate 1.20 error message in test-cmd
  test/extended/testdata/bindata.go
  test/extended/testdata/cmd/test/cmd/quota.sh
Labels: approved, lgtm

#25660 Bug 1852692: CVE-2020-8559 compromised node could escalate to cluster level privileges
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/net/http.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/net/http_test.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/proxy/upgradeaware.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/proxy/upgradeaware_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25737 Fix panic dereferencing nil
  test/e2e/upgrade/monitor.go
Labels: approved, lgtm

#25657 Bug 1852694: CVE-2020-8559 compromised node could escalate to cluster level privileges
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/net/http.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/net/http_test.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/proxy/upgradeaware.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/proxy/upgradeaware_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm, vendor-update

#25710 e2e/cli: move observe.sh to proper e2e
  test/extended/cli/debug.go
  test/extended/cli/mustgather.go
  test/extended/cli/observe.go
  test/extended/cli/timeout.go
  test/extended/testdata/bindata.go
  test/extended/testdata/cmd/test/cmd/observe.sh
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#25718 Fix minor bit to make oc validation possible & remove unused test files
  Makefile
  examples/sample-app/application-template-dockerbuild.json
  examples/sample-app/application-template-pullspecbuild.json
  examples/sample-app/application-template-stibuild.json
  test/extended/builds/digest.go
  test/extended/builds/labels.go
  test/extended/builds/s2i_env.go
  test/extended/cmd.sh
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/test-image-stream.json
  test/extended/testdata/cli/pod-with-two-containers.yaml
  test/extended/testdata/cmd/test/cmd/basicresources.sh
  test/extended/testdata/cmd/test/cmd/testdata/mixed-api-versions.yaml
  test/extended/testdata/cmd/test/cmd/testdata/test-deployment-config.yaml
  test/extended/testdata/cmd/test/cmd/testdata/test-image.json
  test/extended/testdata/image/test-image.json
  test/extended/testdata/roles/policy-clusterroles.yaml
  test/extended/testdata/roles/policy-roles.yaml
  test/extended/testdata/router/router-metrics.yaml
  test/extended/testdata/stable-busybox.yaml
  test/extended/testdata/test-deployment-config.yaml
  test/integration/testdata/project-request-template-with-quota.yaml
  test/integration/testdata/test-buildcli-beta2.json
  test/integration/testdata/test-buildcli.json
  test/integration/testdata/test-image-stream-mapping.json
  test/integration/testdata/test-image.json
  test/integration/testdata/test-route.json
  test/integration/testdata/test-service-with-finalizer.json
  test/integration/testdata/test-service.json
Labels: approved, lgtm

#25733 Bug 1903524: [3.11] UPSTREAM: 97013: Fix FibreChannel volume plugin corrupting filesystem on detach
  vendor/k8s.io/kubernetes/pkg/volume/fc/attacher.go
  vendor/k8s.io/kubernetes/pkg/volume/fc/fc.go
  vendor/k8s.io/kubernetes/pkg/volume/fc/fc_test.go
  vendor/k8s.io/kubernetes/pkg/volume/fc/fc_util.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm, vendor-update

#25749 Bug 1905232: Append image test should be relative to the tools image
  test/extended/images/append.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#25641 Bug 1881319: IPtable rules are racy when pod is created before svc
  vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25683 Bug 1870050: Mount ImageFS in node container
  images/node/system-container/config.json.template
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#25743 add kubevirt as a provide to openshift tests
  cmd/openshift-tests/provider.go
  test/e2e/upgrade/service/service.go
  test/extended/util/kubevirt/provider.go
Labels: approved, lgtm

#25755 allow operators to settle after MCPs are done upgrading
  test/e2e/upgrade/upgrade.go
Labels: approved, lgtm

#25756 Bug 1906713: Add consolequickstarts to list of console resource exceptions
  test/extended/authorization/rbac/groups_default_rules.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25699 [release-4.6] Add e2e testing of server-side apply for openshift types
  test/extended/apiserver/apply.go
  test/extended/etcd/etcd_storage_path.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/client.go
Labels: approved, lgtm

#25754 Bug 1906588: normalize ginkgo structuring so we avoid timing windows with k8s e2e setup when changing user
  test/extended/builds/pipeline_jenkins_e2e.go
  test/extended/builds/pipeline_origin_bld.go
  test/extended/builds/pipeline_origin_bld_rhelimagesonly.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm, vendor-update

#25740 Bug 1901982: clean up remaining build busybox refs after claytons overhaul
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/build-pruning/successful-build-config.yaml
  test/extended/testdata/builds/valuefrom/failed-docker-build-value-from-config.yaml
  test/extended/testdata/builds/valuefrom/successful-docker-build-value-from-config.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#25463 [release-3.11] Bug 1760807: Update pod affinity check in priority for valid labels
  vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/priorities/interpod_affinity.go
  vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/priorities/interpod_affinity_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#25760 extended-tests: kube-apiserver: switch flowcontrol storage to alpha
  test/extended/etcd/etcd_storage_path.go
Labels: approved, lgtm

#25383 Bug 1866789: Remove problematic upstream client plugin test
  pkg/build/builder/docker_test.go
  test/extended/builds/pipeline.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25761 Bug 1907373: Fix build test CM count
  test/extended/builds/remove_buildconfig.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#25766 Skip table tests broken by 1.20 rebase
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm

#25735 bug 1903674: Revert "Temporary disable tests broken upstream"
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#25769 test: Update images README and add OWNERS
  test/extended/util/image/OWNERS
  test/extended/util/image/README.md
Labels: approved, lgtm

#25721 Bug 1902029: move off docker.io in build e2e's (approximate recent 4.7 changes)
  test/extended/builds/contextdir.go
  test/extended/builds/dockerfile.go
  test/extended/builds/hooks.go
  test/extended/builds/multistage.go
  test/extended/builds/optimized.go
  test/extended/builds/s2i_root.go
  test/extended/builds/service.go
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/application-template-custombuild.json
  test/extended/testdata/builds/build-postcommit/docker.yaml
  test/extended/testdata/builds/build-pruning/successful-build-config.yaml
  test/extended/testdata/builds/build-quota/Dockerfile
  test/extended/testdata/builds/build-secrets/Dockerfile
  test/extended/testdata/builds/build-secrets/test-docker-build.json
  test/extended/testdata/builds/build-secrets/test-s2i-build.json
  test/extended/testdata/builds/build-timing/test-docker-build.json
  test/extended/testdata/builds/custom-build/Dockerfile.sample
  test/extended/testdata/builds/custom-build/build.sh
  test/extended/testdata/builds/docker-add/Dockerfile
  test/extended/testdata/builds/docker-add/docker-add-env/Dockerfile
  test/extended/testdata/builds/incremental-auth-build.json
  test/extended/testdata/builds/pullsecret/linked-nodejs-bc.yaml
  test/extended/testdata/builds/statusfail-badcontextdirs2i.yaml
  test/extended/testdata/builds/statusfail-fetchimagecontentdocker.yaml
  test/extended/testdata/builds/statusfail-fetchsourcedocker.yaml
  test/extended/testdata/builds/statusfail-fetchsources2i.yaml
  test/extended/testdata/builds/statusfail-genericreason.yaml
  test/extended/testdata/builds/statusfail-oomkilled.yaml
  test/extended/testdata/builds/test-build-proxy.yaml
  test/extended/testdata/builds/test-build.yaml
  test/extended/testdata/builds/test-cds-dockerbuild.json
  test/extended/testdata/builds/test-cds-sourcebuild.json
  test/extended/testdata/builds/test-context-build.json
  test/extended/testdata/builds/test-docker-build-pullsecret.json
  test/extended/testdata/builds/test-docker-build.json
  test/extended/testdata/builds/test-docker-no-outputname.json
  test/extended/testdata/builds/test-env-build.json
  test/extended/testdata/builds/valuefrom/successful-docker-build-value-from-config.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#25707 Bug 1886160: Improve reliability of e2-aws-disruptive
  cmd/openshift-tests/e2e.go
  test/extended/dr/common.go
  test/extended/dr/machine_recover.go
  test/extended/dr/quorum_restore.go
  test/extended/dr/restore_from_snapshot.go
  test/extended/testdata/bindata.go
  test/extended/testdata/disaster-recovery/restore-etcd.sh
  test/extended/testdata/disaster-recovery/rollback-A.yaml
  test/extended/testdata/disaster-recovery/rollback-B.yaml
  test/extended/testdata/disaster-recovery/ssh-bastion/clusterrole.yaml
  test/extended/testdata/disaster-recovery/ssh-bastion/clusterrolebinding.yaml
  test/extended/testdata/disaster-recovery/ssh-bastion/deployment.yaml
  test/extended/testdata/disaster-recovery/ssh-bastion/namespace.yaml
  test/extended/testdata/disaster-recovery/ssh-bastion/role.yaml
  test/extended/testdata/disaster-recovery/ssh-bastion/rolebinding.yaml
  test/extended/testdata/disaster-recovery/ssh-bastion/service.yaml
  test/extended/testdata/disaster-recovery/ssh-bastion/serviceaccount.yaml
  test/extended/testdata/disaster-recovery/ssh-bastion/sshd_config
  test/extended/testdata/disaster-recovery/update_route_53.py
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#25745 Bug 1904683: add build s2i as root uid image for associated tests
  test/extended/builds/s2i_root.go
  test/extended/util/image/image.go
  test/extended/util/image/zz_generated.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25772 Bug 1908764: Skew 4.5 to 4.6 tests are failing due to a misplaced skip (prevents all tests from running)
  test/extended/oauth/expiration.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#25770 Bug 1896977: Match e2e test to new enhanced host name validation
  test/extended/etcd/etcd_storage_path.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#25775 Bug 1908675: Re-Enable fsgroup policy test
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#25773 Bug 1907938: Nodes goes into NotReady state (VMware)
  glide.lock
  glide.yaml
  vendor/github.com/openshift/library-go/go.mod
  vendor/github.com/openshift/library-go/pkg/config/client/client_config.go
  vendor/github.com/openshift/library-go/pkg/network/dialer.go
  vendor/github.com/openshift/library-go/pkg/network/dialer_linux.go
  vendor/github.com/openshift/library-go/pkg/network/dialer_others.go
  vendor/github.com/openshift/library-go/pkg/operator/loglevel/logging_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/loglevel/logging_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/loglevel/util.go
  vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/manifests/installer-pod.yaml
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/manifests/pruner-pod.yaml
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller_test.go
  vendor/github.com/openshift/library-go/test/library/encryption/e_log.go
  vendor/github.com/openshift/library-go/test/library/encryption/perf_helpers.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/transport/cache.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm, vendor-update
