Repository openshift/origin, pull requests merged in 2020-07, with the labels that each got.

#25191 Bug 1844483: poll on deleted obj check; give controller finalizer deletes time to complete
  test/extended/templates/templateinstance_cross_namespace.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25014 move image ecosystem e2e suite from centos to rhel; create rhel only jenkins e2e suite
  cmd/openshift-tests/e2e.go
  test/extended/builds/pipeline_origin_bld_rhelimagesonly.go
  test/extended/image_ecosystem/s2i_images.go
  test/extended/image_ecosystem/scl.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/url/url.go
Labels: approved, lgtm

#25027 [release 3.11]Bug 1824243: Fix egressVXLANMonitor and egressIPTracker deadlock
  pkg/network/node/egressip.go
  pkg/network/node/vxlan_monitor.go
  pkg/network/node/vxlan_monitor_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#25208 Bug 1843319: Fix DS expectations on recreate
  vendor/k8s.io/kubernetes/pkg/controller/daemon/daemon_controller.go
  vendor/k8s.io/kubernetes/pkg/controller/daemon/daemon_controller_test.go
  vendor/k8s.io/kubernetes/pkg/controller/daemon/init_test.go
  vendor/k8s.io/kubernetes/pkg/controller/daemon/update_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, vendor-update

#25211 watch-termination: fix NewNonInteractiveDeferredLoadingClientConfig NFE
  cmd/watch-termination/main.go
Labels: approved, lgtm

#25218 monitor: add time to track from for a Condition
  pkg/monitor/monitor.go
  pkg/monitor/sampler_test.go
  pkg/monitor/types.go
Labels: approved, lgtm

#25069 test: Verify machine shutdown/health check/recover in disruptive
  cmd/openshift-tests/e2e.go
  test/extended/dr/common.go
  test/extended/dr/machine_recover.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#25132 UPSTREAM: 92197: make log output of failed healthchecks more focused
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/healthz/healthz.go
Labels: approved, lgtm, vendor-update

#25229 BUILD-92: update WaitForOpenShiftNamespaceImageStreams with more detailed diagnostics
  test/extended/util/framework.go
Labels: approved, lgtm

#25203 Pick scheduler v1beta1 componentconfig API
  vendor/k8s.io/kubernetes/cmd/kube-scheduler/app/options/configfile.go
  vendor/k8s.io/kubernetes/cmd/kube-scheduler/app/options/deprecated.go
  vendor/k8s.io/kubernetes/cmd/kube-scheduler/app/options/options.go
  vendor/k8s.io/kubernetes/cmd/kube-scheduler/app/options/options_test.go
  vendor/k8s.io/kubernetes/pkg/generated/openapi/zz_generated.openapi.go
  vendor/k8s.io/kubernetes/pkg/scheduler/apis/config/scheme/scheme.go
  vendor/k8s.io/kubernetes/pkg/scheduler/apis/config/v1alpha2/conversion.go
  vendor/k8s.io/kubernetes/pkg/scheduler/apis/config/v1alpha2/zz_generated.conversion.go
  vendor/k8s.io/kubernetes/pkg/scheduler/apis/config/v1beta1/BUILD
  vendor/k8s.io/kubernetes/pkg/scheduler/apis/config/v1beta1/conversion.go
  vendor/k8s.io/kubernetes/pkg/scheduler/apis/config/v1beta1/conversion_test.go
  vendor/k8s.io/kubernetes/pkg/scheduler/apis/config/v1beta1/defaults.go
  vendor/k8s.io/kubernetes/pkg/scheduler/apis/config/v1beta1/defaults_test.go
  vendor/k8s.io/kubernetes/pkg/scheduler/apis/config/v1beta1/doc.go
  vendor/k8s.io/kubernetes/pkg/scheduler/apis/config/v1beta1/register.go
  vendor/k8s.io/kubernetes/pkg/scheduler/apis/config/v1beta1/zz_generated.conversion.go
  vendor/k8s.io/kubernetes/pkg/scheduler/apis/config/v1beta1/zz_generated.deepcopy.go
  vendor/k8s.io/kubernetes/pkg/scheduler/apis/config/v1beta1/zz_generated.defaults.go
  vendor/k8s.io/kubernetes/pkg/scheduler/factory.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-scheduler/config/v1beta1/BUILD
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-scheduler/config/v1beta1/doc.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-scheduler/config/v1beta1/register.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-scheduler/config/v1beta1/types.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-scheduler/config/v1beta1/zz_generated.deepcopy.go
Labels: approved, lgtm, priority/important-soon, vendor-update

#25204 Bug 1828477: Add CI test to check for critical alerts post upgrade
  test/e2e/upgrade/alert/alert.go
  test/e2e/upgrade/upgrade.go
  test/extended/prometheus/prometheus.go
  test/extended/prometheus/prometheus_builds.go
  test/extended/util/client.go
  test/extended/util/prometheus/helpers.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#25202 Bug 1850719: Measure container restarts over an interval instead of absolute
  test/extended/operators/cluster.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#25239 must-gather: temporarily disable broken test
  test/extended/cli/mustgather.go
Labels: approved, lgtm

#24967 UPSTREAM: <carry>: eliminate unnecessary closure in openshift configu…
  vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/patch_openshift.go
  vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/openshiftkubeapiserver/paramtoken/BUILD
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/openshiftkubeapiserver/paramtoken/paramtoken.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/openshiftkubeapiserver/patch.go
Labels: approved, lgtm, vendor-update

#25243 Bug 1853711: Disable HTTP/2 tests
  test/extended/router/grpc-interop.go
  test/extended/router/h2spec.go
  test/extended/router/http2.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#25244 Bug 1854195: Disable HTTP/2 tests
  test/extended/router/grpc-interop.go
  test/extended/router/h2spec.go
  test/extended/router/http2.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#25246 test: Broaden check for base images that are RHEL8
  test/extended/operators/images.go
Labels: approved, lgtm

#25249 defines Kube publishing rules for origin-4.6-kubernetes-1.18.3
  publishing-kube-rules.yaml
Labels: approved, lgtm

#25164 Bug 1731905: [backport 3.11] SDN cannot add egress IP to team interface
  pkg/network/node/egressip.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#24963 IPFamily fixes from upstream
  vendor/k8s.io/kubernetes/pkg/apis/core/validation/conditional_validation.go
  vendor/k8s.io/kubernetes/pkg/apis/core/validation/conditional_validation_test.go
  vendor/k8s.io/kubernetes/pkg/apis/core/validation/validation.go
  vendor/k8s.io/kubernetes/pkg/apis/core/validation/validation_test.go
  vendor/k8s.io/kubernetes/pkg/registry/core/rest/storage_core.go
  vendor/k8s.io/kubernetes/pkg/registry/core/service/BUILD
  vendor/k8s.io/kubernetes/pkg/registry/core/service/storage/BUILD
  vendor/k8s.io/kubernetes/pkg/registry/core/service/storage/rest.go
  vendor/k8s.io/kubernetes/pkg/registry/core/service/storage/rest_test.go
  vendor/k8s.io/kubernetes/pkg/registry/core/service/storage/storage.go
  vendor/k8s.io/kubernetes/pkg/registry/core/service/storage/storage_test.go
  vendor/k8s.io/kubernetes/pkg/registry/core/service/strategy.go
  vendor/k8s.io/kubernetes/pkg/registry/core/service/strategy_test.go
Labels: approved, lgtm, vendor-update

#25256 updates publishing rules for origin-4.6-kubernetes-1.18.3
  publishing-rules.yaml
Labels: approved, lgtm

#25231 Bug 1851623: e2e: extended: re-enable topology manager tests
  test/extended/topology_manager/resourcealign.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#25143 Bug 1845780: [release-4.4] kubelet: block non-forwarded packets from crossing the localhost boundary
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_network_linux.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm, vendor-update

#25222 UPSTREAM: <carry>: Bug 1852565: change etcd health check timeout to 10s
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, vendor-update

#25255 test: Report disruption flakes correctly in junit
  test/extended/util/disruption/disruption.go
Labels: approved, lgtm

#25131 [release-3.11] Bug 1847478: Backport haproxy router metrics fix (openshift/router#127)
  pkg/router/metrics/haproxy/haproxy.go
  pkg/router/metrics/haproxy/haproxy_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25063 [release-4.3] Bug 1843877: UPSTREAM: 91008: Do not swallow NotFound error for DeletePod in dsc.manage
  vendor/k8s.io/kubernetes/pkg/controller/BUILD
  vendor/k8s.io/kubernetes/pkg/controller/controller_utils.go
  vendor/k8s.io/kubernetes/pkg/controller/controller_utils_test.go
  vendor/k8s.io/kubernetes/pkg/controller/daemon/daemon_controller.go
  vendor/k8s.io/kubernetes/pkg/controller/job/job_controller.go
  vendor/k8s.io/kubernetes/pkg/controller/replicaset/replica_set.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#25261 bug 1853786: UPSTREAM: 91648: Changes to ManagedFields is not mutation for GC
  vendor/k8s.io/kubernetes/pkg/registry/rbac/BUILD
  vendor/k8s.io/kubernetes/pkg/registry/rbac/helpers.go
  vendor/k8s.io/kubernetes/pkg/registry/rbac/helpers_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm, vendor-update

#25263 Bug 1855444: UPSTREAM: 91648: Changes to ManagedFields is not mutation for GC
  vendor/k8s.io/kubernetes/pkg/registry/rbac/BUILD
  vendor/k8s.io/kubernetes/pkg/registry/rbac/helpers.go
  vendor/k8s.io/kubernetes/pkg/registry/rbac/helpers_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, vendor-update

#25258 wires the egress proxy to the kube-aggregator
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/apiserver/apiserver.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/controllers/status/available_controller.go
Labels: approved, lgtm, vendor-update

#25124 Bug 1763610: use proper version of PodLogOptions struct in diagnostics
  pkg/oc/cli/admin/diagnostics/diagnostics/cluster/network/setup.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25269 UPSTREAM: 92941: Don't return proxied redirects to the client
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/net/http.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/net/http_test.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/proxy/upgradeaware.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/proxy/upgradeaware_test.go
Labels: approved, lgtm, vendor-update

#25111 Bug 1847043: UPSTREAM: 89053: migration of re-usable package from pkg/kubelet/cm/cpumanager to pkg/kubelet/cm
  vendor/k8s.io/kubernetes/pkg/kubelet/cm/BUILD
  vendor/k8s.io/kubernetes/pkg/kubelet/cm/container_manager_linux.go
  vendor/k8s.io/kubernetes/pkg/kubelet/cm/containermap/BUILD
  vendor/k8s.io/kubernetes/pkg/kubelet/cm/containermap/container_map.go
  vendor/k8s.io/kubernetes/pkg/kubelet/cm/containermap/container_map_test.go
  vendor/k8s.io/kubernetes/pkg/kubelet/cm/cpumanager/BUILD
  vendor/k8s.io/kubernetes/pkg/kubelet/cm/cpumanager/cpu_manager.go
  vendor/k8s.io/kubernetes/pkg/kubelet/cm/cpumanager/cpu_manager_test.go
  vendor/k8s.io/kubernetes/pkg/kubelet/cm/cpumanager/fake_cpu_manager.go
  vendor/k8s.io/kubernetes/pkg/kubelet/cm/cpumanager/state/BUILD
  vendor/k8s.io/kubernetes/pkg/kubelet/cm/cpumanager/state/state_checkpoint.go
  vendor/k8s.io/kubernetes/pkg/kubelet/cm/cpumanager/state/state_checkpoint_test.go
  vendor/k8s.io/kubernetes/pkg/kubelet/cm/cpumanager/state/state_file.go
  vendor/k8s.io/kubernetes/pkg/kubelet/cm/cpumanager/state/state_file_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, vendor-update

#25209 [release-4.5] Bug 1845242: Fix DS expectations on recreate
  vendor/k8s.io/kubernetes/pkg/controller/daemon/daemon_controller.go
  vendor/k8s.io/kubernetes/pkg/controller/daemon/daemon_controller_test.go
  vendor/k8s.io/kubernetes/pkg/controller/daemon/init_test.go
  vendor/k8s.io/kubernetes/pkg/controller/daemon/update_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, vendor-update

#25270 FIx CI for 3.11
  test/extended/router/metrics.go
  vendor/k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler/reconciler_test.go
Labels: approved, lgtm

#25278 Fix oc observe tests
  test/extended/testdata/bindata.go
  test/extended/testdata/cmd/test/cmd/observe.sh
Labels: approved, lgtm

#25282 e2e/mustgather: ignore non audit files in /var/log/*-apiserver dir
  test/extended/cli/mustgather.go
Labels: approved, lgtm

#25210 [release-4.4] Bug 1851407: Fix DS expectations on recreate
  vendor/k8s.io/kubernetes/pkg/controller/daemon/daemon_controller.go
  vendor/k8s.io/kubernetes/pkg/controller/daemon/daemon_controller_test.go
  vendor/k8s.io/kubernetes/pkg/controller/daemon/init_test.go
  vendor/k8s.io/kubernetes/pkg/controller/daemon/update_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, vendor-update

#25290 UPSTREAM: <carry>: apiserver: skip local IPs and probes for LateConnections – fix race
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/patch_genericapiserver.go
Labels: approved, lgtm, vendor-update

#25286 Bug 1857083: Include pod /etc/hosts in ephemeral storage calculation for eviction
  vendor/k8s.io/kubernetes/pkg/kubelet/eviction/BUILD
  vendor/k8s.io/kubernetes/pkg/kubelet/eviction/eviction_manager.go
  vendor/k8s.io/kubernetes/pkg/kubelet/eviction/helpers.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_pods.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_test.go
  vendor/k8s.io/kubernetes/pkg/kubelet/runonce_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25151 Bug 1753649: UPSTREAM: 89937: portAllocator sync local data before allocate
  vendor/k8s.io/kubernetes/pkg/registry/core/service/allocator/storage/storage.go
  vendor/k8s.io/kubernetes/pkg/registry/core/service/allocator/storage/storage_test.go
  vendor/k8s.io/kubernetes/pkg/registry/core/service/portallocator/BUILD
  vendor/k8s.io/kubernetes/test/integration/master/kube_apiserver_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#25274 Bug 1856250: UPSTREAM: 84792: Fixes for the `No ref for container` in probes after kubelet restart
  vendor/k8s.io/kubernetes/pkg/kubelet/prober/prober.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#25144 Bug 1845773: [release-4.3] kubelet: block non-forwarded packets from crossing the localhost boundary
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_network_linux.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#25292 Remove watch termination command (moved to openshift/kubernetes)
  .gitignore
  cmd/watch-termination/main.go
  go.mod
Labels: approved, lgtm

#25296 bug 1858287: UPSTREAM: 71063: fix a scheduler panic due to internal cache inconsistency
  vendor/k8s.io/kubernetes/pkg/scheduler/core/generic_scheduler.go
Labels: approved, lgtm

#25250 Bug 1854311: 4.5: UPSTREAM: 91307: CSI: Modify VolumeAttachment check to use Informer/Cache
  vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/core.go
  vendor/k8s.io/kubernetes/pkg/controller/volume/attachdetach/attach_detach_controller.go
  vendor/k8s.io/kubernetes/pkg/controller/volume/attachdetach/attach_detach_controller_test.go
  vendor/k8s.io/kubernetes/pkg/volume/csi/BUILD
  vendor/k8s.io/kubernetes/pkg/volume/csi/csi_attacher.go
  vendor/k8s.io/kubernetes/pkg/volume/csi/csi_attacher_test.go
  vendor/k8s.io/kubernetes/pkg/volume/csi/csi_plugin.go
  vendor/k8s.io/kubernetes/pkg/volume/csi/csi_plugin_test.go
  vendor/k8s.io/kubernetes/pkg/volume/csi/csi_test.go
  vendor/k8s.io/kubernetes/pkg/volume/csi/nodeinfomanager/nodeinfomanager_test.go
  vendor/k8s.io/kubernetes/pkg/volume/csi/testing/testing.go
  vendor/k8s.io/kubernetes/pkg/volume/plugins.go
  vendor/k8s.io/kubernetes/pkg/volume/testing/testing.go
  vendor/k8s.io/kubernetes/test/integration/volume/attach_detach_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, vendor-update

#25259 pins all 4.5 dependencies and runs hack/update-deps.sh
  glide.lock
  glide.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#25303 hack: make update and make verify check for test name generation
  Makefile
  hack/update-generated.sh
  hack/verify-generated.sh
  test/extended/include.go
  test/extended/util/annotate/annotate.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#25304 test: Allow test suites to define additional checks for suite failure
  pkg/test/ginkgo/cmd_runsuite.go
  test/e2e/upgrade/alert/alert.go
  test/e2e/upgrade/service/service.go
  test/extended/util/disruption/controlplane/controlplane.go
  test/extended/util/disruption/frontends/frontends.go
Labels: approved, lgtm

#25308 etcd-storage-test: apply 1.19 diff
  test/extended/etcd/etcd_storage_path.go
Labels: approved, lgtm

#25315 bug 1860157: allow recycler pods to run with best effort qos
  test/extended/operators/qos.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25313 make the error message specific to which API server connection blipped
  test/e2e/upgrade/upgrade.go
  test/extended/dr/machine_recover.go
  test/extended/util/disruption/controlplane/controlplane.go
Labels: approved, lgtm

#25307 test: Report an error message when a pod fails in a cmd test
  test/extended/util/framework.go
Labels: approved

#25283 test/extended/cli/mustgather: Separate gather_audit_logs test
  test/extended/cli/mustgather.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#25319 e2e-cmd: fix the bits necessary for e2e-cmd to pass
  test/extended/testdata/bindata.go
  test/extended/testdata/cmd/test/cmd/basicresources.sh
  test/extended/testdata/cmd/test/cmd/builds.sh
  test/extended/testdata/cmd/test/cmd/edit.sh
  test/extended/testdata/cmd/test/cmd/env.sh
  test/extended/testdata/cmd/test/cmd/help.sh
Labels: approved, lgtm

#25318 deploymentconfig: drop unnecessary conversions in tests
  test/extended/controller_manager/deploy_scale.go
  test/extended/deployments/deployments.go
Labels: approved, lgtm

#25325 Disable named network metrics test.
  test/extended/prometheus/prometheus.go
Labels: approved, lgtm

#25328 Fix "should provide named network metrics" test.
  test/extended/prometheus/prometheus.go
Labels: approved, lgtm

#25320 Update OLM e2e to include quotes on substring check
  test/extended/operators/olm.go
Labels: approved, lgtm

#25336 bug 1861201: make must-gather test resilient to failures and disk timing
  test/extended/cli/mustgather.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, do-not-merge/hold, lgtm

#25335 bug 1861189: UPSTREAM: <drop>: make pdb tests pass reliably
  vendor/k8s.io/kubernetes/test/e2e/apps/disruption.go
Labels: approved, bugzilla/invalid-bug, bugzilla/severity-medium, do-not-merge/hold, lgtm, vendor-update

#25341 skip flaky must-gather audit test to get a payload accepted
  test/extended/cli/mustgather.go
Labels: approved

#25323 Bug 1857928: switch to amq operator from cockroach for olm sanity test
  test/extended/operators/olm.go
  test/extended/testdata/bindata.go
  test/extended/testdata/olm/operatorgroup.yaml
  test/extended/testdata/olm/subscription.yaml
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, vendor-update

#25251 Bug 1854312: 4.4: UPSTREAM: 92014: CSI: Modify VolumeAttachment check to use Informer/cache
  vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/core.go
  vendor/k8s.io/kubernetes/pkg/controller/volume/attachdetach/attach_detach_controller.go
  vendor/k8s.io/kubernetes/pkg/controller/volume/attachdetach/attach_detach_controller_test.go
  vendor/k8s.io/kubernetes/pkg/volume/csi/BUILD
  vendor/k8s.io/kubernetes/pkg/volume/csi/csi_attacher.go
  vendor/k8s.io/kubernetes/pkg/volume/csi/csi_attacher_test.go
  vendor/k8s.io/kubernetes/pkg/volume/csi/csi_plugin.go
  vendor/k8s.io/kubernetes/pkg/volume/csi/csi_plugin_test.go
  vendor/k8s.io/kubernetes/pkg/volume/csi/csi_test.go
  vendor/k8s.io/kubernetes/pkg/volume/csi/nodeinfomanager/nodeinfomanager_test.go
  vendor/k8s.io/kubernetes/pkg/volume/csi/testing/testing.go
  vendor/k8s.io/kubernetes/pkg/volume/plugins.go
  vendor/k8s.io/kubernetes/pkg/volume/testing/testing.go
  vendor/k8s.io/kubernetes/test/integration/volume/attach_detach_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, vendor-update

#25352 Bug 1862322: e2e/extended: disable OLM 'can subscribe to the operator' test
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#25347 e2e/oauth: unescape token taken from redirect url fragment
  test/extended/oauth/requestheaders.go
Labels: approved, lgtm

#25346 e2e/oauth/expiration: support sha256 tokens
  test/extended/oauth/expiration.go
Labels: approved, lgtm

#25356 ovnkube: skip Conntrack test that's flaky upstream
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm
