Repository openshift/origin, pull requests merged in 2020-05, with the labels that each got.

#24838 [release-4.1] Bug 1816388: handle pod updates correctly in networkpolicy
  pkg/network/node/networkpolicy.go
  pkg/network/node/networkpolicy_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#24518 [release-3.11] Bug 1772594: Make DNS querying more efficient by querying once per dns name
  pkg/network/common/dns.go
  pkg/network/common/dns_test.go
  pkg/network/common/egress_dns.go
  pkg/network/node/egress_network_policy.go
  pkg/network/node/node.go
  pkg/network/node/ovscontroller.go
  pkg/network/proxy/proxy.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#24899 Remove skipped tests that OVN now supports
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, bugzilla/valid-bug, lgtm

#24837 [release-3.11] Bug 1745898: handle pod updates correctly in networkpolicy
  pkg/network/node/networkpolicy.go
  pkg/network/node/networkpolicy_test.go
Labels: approved, bugzilla/valid-bug, lgtm

#24895 [release-3.11] Bug 1814804: UPSTREAM: 88251: Partially fix incorrect configuration of kubepods.slice unit by kubelet
  vendor/k8s.io/kubernetes/pkg/kubelet/cm/node_container_manager.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#24941 Bug 1829223: test/extended/prometheus: allow a pending state for AlertmanagerReceiversNotConfigured
  test/extended/prometheus/prometheus.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#24949 Bug 1829225: Increase waiting time for namespace deletion in project test
  test/extended/project/project.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#24945 Bug 1831533: stop printing usage help when the server commands exit
  vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm, vendor-update

#24942 Bug 1831042: Fix client-ca dynamic reload in apiserver
  vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go
  vendor/k8s.io/kubernetes/cmd/kubelet/app/auth.go
  vendor/k8s.io/kubernetes/cmd/kubelet/app/server.go
  vendor/k8s.io/kubernetes/pkg/kubeapiserver/options/authentication.go
  vendor/k8s.io/kubernetes/test/integration/apiserver/certreload/certreload_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm, vendor-update

#24933 Bug 1828174: Fix azure tests in unzoned environment
  vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/azure/azure_managedDiskController.go
  vendor/k8s.io/kubernetes/test/e2e/framework/providers/azure/azure.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, sig/storage, vendor-update

#24951 Bug 1831906: Add more debug messages to RequestHeaders IdP test
  test/extended/oauth/requestheaders.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#24948 Bug 1829405: test/extended/operators/operators: Rework "start all core operators"
  test/extended/operators/operators.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#24854 Bug 1822667: UPSTREAM: 88424: Respect ignore-volume-az option in admission plugin
  vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/openstack/openstack_volumes.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, vendor-update

#24501 Bug 1798461: makes unavailableGauge metric to always reflect the current state of a service
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/controllers/status/available_controller.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#24946 Bug 1824200: use cockroachdb in OLM e2e test
  test/extended/operators/olm.go
  test/extended/testdata/bindata.go
  test/extended/testdata/olm/cockroachdb-subscription.yaml
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#24952 Bug 1829331: UPSTREAM: 90715: Ignore NotFound error when cleaning up Gluster tests
  vendor/k8s.io/kubernetes/test/e2e/common/volumes.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, vendor-update

#24912 Bug 1731222: unskip template extended tests
  cmd/openshift-tests/e2e.go
  test/extended/templates/template.go
  test/extended/templates/templateinstance_cross_namespace.go
  test/extended/templates/templateinstance_fail.go
  test/extended/templates/templateinstance_impersonation.go
  test/extended/templates/templateinstance_objectkinds.go
  test/extended/templates/templateinstance_readiness.go
  test/extended/templates/templateinstance_security.go
  test/extended/templates/templateservicebroker_bind.go
  test/extended/templates/templateservicebroker_e2e.go
  test/extended/templates/templateservicebroker_security.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#24597 Bug 1805821: change restart policy of command pod to RestartPolicyOnFailure
  test/extended/util/framework.go
  test/extended/util/ldap.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, size/M

#24947 Bug 1731263: Balance preemption e2e nodes
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
  vendor/k8s.io/kubernetes/test/e2e/scheduling/preemption.go
  vendor/k8s.io/kubernetes/test/e2e/scheduling/priorities.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, kind/failing-test, lgtm, vendor-update

#24944 Bug 1749246: UPSTREAM: Fix TestContext references in e2e skippers
  vendor/k8s.io/kubernetes/test/e2e/framework/skipper/skipper.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, vendor-update

#24937 Bug 1829958: [release-4.4] Introduce IBMCloud provider, skip/fix tests
  test/extended/apiserver/root_403.go
  test/extended/authentication/front_proxy.go
  test/extended/bootstrap_user/bootstrap_user_login.go
  test/extended/cli/mustgather.go
  test/extended/csrapprover/csrapprover.go
  test/extended/etcd/etcd_test_runner.go
  test/extended/images/imagestream.go
  test/extended/machines/machines.go
  test/extended/machines/scale.go
  test/extended/oauth/oauthcertfallback.go
  test/extended/oauth/requestheaders.go
  test/extended/oauth/well_known.go
  test/extended/prometheus/prometheus.go
  test/extended/prometheus/prometheus_builds.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
  test/extended/util/client.go
  test/extended/util/framework.go
  test/extended/util/ibmcloud/provider.go
  test/extended/util/oauthserver/oauthserver.go
  test/extended/util/test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, cherry-pick-approved, lgtm

#24855 Bug 1822680: UPSTREAM: 88424: Respect ignore-volume-az option in admission plugin
  vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/openstack/openstack_volumes.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#24623 [4.2] Bug 1808549: UPSTREAM: 88146: remove duplicate pv delete commands
  vendor/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/framework_test.go
  vendor/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/pv_controller.go
  vendor/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/pv_controller_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm, sig/storage, size/M

#24924 Bug 1828790: provides a temporal fix to improve CRD publishing e2e tests in an HA setup
  vendor/k8s.io/kubernetes/test/e2e/apimachinery/crd_publish_openapi.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, vendor-update

#24977 Bug 1835785: UPSTREAM: 90378: bugfix: initcontainer wasn't considered when calculate resource request
  vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/noderesources/resource_allocation.go
  vendor/k8s.io/kubernetes/pkg/scheduler/nodeinfo/node_info.go
  vendor/k8s.io/kubernetes/pkg/scheduler/nodeinfo/node_info_test.go
  vendor/k8s.io/kubernetes/pkg/scheduler/util/BUILD
  vendor/k8s.io/kubernetes/pkg/scheduler/util/non_zero.go
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm, vendor-update

#24978 Bug 1835042: UPSTREAM: 91066: tweak exec-probe log statement to be more concise
  vendor/k8s.io/kubernetes/pkg/kubelet/prober/prober.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm, vendor-update

#24965 Bug 1833824: unskip template extended tests
  cmd/openshift-tests/e2e.go
  test/extended/templates/template.go
  test/extended/templates/templateinstance_cross_namespace.go
  test/extended/templates/templateinstance_fail.go
  test/extended/templates/templateinstance_impersonation.go
  test/extended/templates/templateinstance_objectkinds.go
  test/extended/templates/templateinstance_readiness.go
  test/extended/templates/templateinstance_security.go
  test/extended/templates/templateservicebroker_bind.go
  test/extended/templates/templateservicebroker_e2e.go
  test/extended/templates/templateservicebroker_security.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#24829 Bug 1829959: [release-4.3] Introduce IBMCloud provider, skip/fix tests
  test/extended/apiserver/root_403.go
  test/extended/authentication/front_proxy.go
  test/extended/bootstrap_user/bootstrap_user_login.go
  test/extended/cli/mustgather.go
  test/extended/csrapprover/csrapprover.go
  test/extended/etcd/etcd_test_runner.go
  test/extended/images/imagestream.go
  test/extended/machines/machines.go
  test/extended/machines/scale.go
  test/extended/oauth/oauthcertfallback.go
  test/extended/oauth/requestheaders.go
  test/extended/oauth/well_known.go
  test/extended/prometheus/prometheus.go
  test/extended/prometheus/prometheus_builds.go
  test/extended/util/client.go
  test/extended/util/framework.go
  test/extended/util/ibmcloud/provider.go
  test/extended/util/oauthserver/oauthserver.go
  test/extended/util/test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#24982 Bug 1835931: Fix panic in test code
  test/extended/dr/common.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#24943 Bug 1831045: Fix client-ca dynamic reload in apiserver
  vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go
  vendor/k8s.io/kubernetes/cmd/kubelet/app/auth.go
  vendor/k8s.io/kubernetes/cmd/kubelet/app/server.go
  vendor/k8s.io/kubernetes/pkg/kubeapiserver/options/authentication.go
  vendor/k8s.io/kubernetes/test/integration/apiserver/certreload/certreload_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm, vendor-update

#24953 Bug 1832366: router: add extended http/2 tests
  test/extended/router/http2.go
  test/extended/router/http2/Makefile
  test/extended/router/http2/cluster/go.mod
  test/extended/router/http2/cluster/go.sum
  test/extended/router/http2/cluster/server/server.go
  test/extended/router/http2/doc.go
  test/extended/router/http2/test-fixture-gen/gen.go
  test/extended/testdata/bindata.go
  test/extended/testdata/router/router-http2.yaml
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, sig/network-edge

#24973 Bug 1821945: Ensure the server FQIN is stored and searched in lowercase (vsphere)
  vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/vsphere/credentialmanager.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/vsphere/credentialmanager_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm, vendor-update

#24992 Bug 1833387: test/extended/operators/operators: Don't worry about Progressing ClusterOperator
  test/extended/operators/operators.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#24989 Bug 1592653: detect int64 overflow when converting volume sizes
  vendor/k8s.io/kubernetes/pkg/volume/azure_file/azure_file.go
  vendor/k8s.io/kubernetes/pkg/volume/azure_file/azure_provision.go
  vendor/k8s.io/kubernetes/pkg/volume/gcepd/gce_util.go
  vendor/k8s.io/kubernetes/pkg/volume/glusterfs/glusterfs.go
  vendor/k8s.io/kubernetes/pkg/volume/portworx/portworx_util.go
  vendor/k8s.io/kubernetes/pkg/volume/rbd/rbd_util.go
  vendor/k8s.io/kubernetes/pkg/volume/scaleio/BUILD
  vendor/k8s.io/kubernetes/pkg/volume/scaleio/sio_volume.go
  vendor/k8s.io/kubernetes/pkg/volume/scaleio/sio_volume_test.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/cloud-provider/volume/helpers/rounding.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/cloud-provider/volume/helpers/rounding_test.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/aws/aws.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/azure/azure_managedDiskController.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/gce/gce_disks.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm, sig/storage, vendor-update

#24926 Bug 1823406: Upstream: 89160: Remove potentially unhealthy symlink only for dead containers
  vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_gc.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/legacy.go
  vendor/k8s.io/kubernetes/pkg/kubelet/remote/remote_runtime.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, vendor-update

#24996 Bug 1837400: Disable broken etcd DR test
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#24975 bug 1837464: prevent panic-ing in test to try to figure out what's failing
  test/extended/project/project.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#24545 Bug 1803090: 3.11: UPSTREAM: 87673: blank out value for unbounded client label
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#24994 Bug 1835845: Metrics test for router should allow backend metrics
  test/extended/router/metrics.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#24976 Bug 1834343: router: Re-enable h2spec and grpc-interop e2e tests
  test/extended/router/grpc-interop.go
  test/extended/router/grpc-interop/Makefile
  test/extended/router/grpc-interop/cluster/Makefile
  test/extended/router/grpc-interop/cluster/server/server.go
  test/extended/router/grpc-interop/test-fixture-gen/gen.go
  test/extended/router/h2spec.go
  test/extended/testdata/bindata.go
  test/extended/testdata/router/router-grpc-interop.yaml
  test/extended/testdata/router/router-h2spec.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25002 Bug 1837992: images/hyperkube: install iproute
  images/hyperkube/Dockerfile.rhel
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#24940 Bug 1830093: provides a temporal fix to improve CRD publishing e2e tests in an HA setup
  vendor/k8s.io/kubernetes/test/e2e/apimachinery/crd_publish_openapi.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#25013 Add publishing rules for origin-4.5-kubernetes-1.18.3
  publishing-kube-rules.yaml
Labels: approved, lgtm

#24599 Bug 1806454: Allow multiple toleration values with the same key
  pkg/apps/apiserver/registry/deployconfig/etcd/etcd.go
  vendor/k8s.io/kubernetes/pkg/util/tolerations/tolerations.go
  vendor/k8s.io/kubernetes/pkg/util/tolerations/tolerations_test.go
  vendor/k8s.io/kubernetes/plugin/pkg/admission/podtolerationrestriction/admission.go
  vendor/k8s.io/kubernetes/plugin/pkg/admission/podtolerationrestriction/admission_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, size/XL

#25001 Bug 1820449: update gopkg.in/yaml.v2 to v2.2.8
  glide.lock
  glide.yaml
  vendor/github.com/getsentry/raven-go/Dockerfile.test
  vendor/github.com/gogo/protobuf/test/tags/Makefile
  vendor/github.com/gogo/protobuf/test/tags/doc.go
  vendor/github.com/gogo/protobuf/test/tags/tags.pb.go
  vendor/github.com/gogo/protobuf/test/tags/tags.proto
  vendor/github.com/gogo/protobuf/test/tags/tags_test.go
  vendor/github.com/heketi/heketi/client/api/python/heketi/__init__.py
  vendor/github.com/heketi/heketi/client/api/python/heketi/heketi.py
  vendor/github.com/jmespath/go-jmespath/cmd/jpgo/main.go
  vendor/github.com/vmware/photon-controller-go-sdk/photon/client.go
  vendor/github.com/vmware/photon-controller-go-sdk/photon/deployments_test.go
  vendor/github.com/vmware/photon-controller-go-sdk/photon/lightwave/oidcclient_test.go
  vendor/gopkg.in/yaml.v2/.travis.yml
  vendor/gopkg.in/yaml.v2/benchmark_test.go
  vendor/gopkg.in/yaml.v2/decode.go
  vendor/gopkg.in/yaml.v2/decode_test.go
  vendor/gopkg.in/yaml.v2/limit_test.go
  vendor/gopkg.in/yaml.v2/scannerc.go
  vendor/gopkg.in/yaml.v2/yaml.go
  vendor/gopkg.in/yaml.v2/yamlh.go
  vendor/k8s.io/kubernetes/third_party/etcd.BUILD
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#24954 Bug 1832641: UPSTREAM: 90823: Service load balancers should include unschedulable nodes
  vendor/k8s.io/kubernetes/pkg/controller/service/controller.go
  vendor/k8s.io/kubernetes/pkg/controller/service/controller_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, vendor-update

#24986 Bug 1820731: samename test flake fix
  test/extended/marketplace/marketplace_diffname.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#24962 Bug 1833583: Serializes IngressClass conformance test
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#24987 Bug 1827071: UPSTREAM: 90792: Send a nicer event when resizing attached Cinder volume
  vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/openstack/openstack_volumes.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, vendor-update

#24990 Bug 1827062: UPSTREAM: 90608: Updates the fstype of Cinder volumes to be ext4 if nil
  vendor/k8s.io/kubernetes/pkg/volume/cinder/cinder.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm, vendor-update

#25007 Bug 1825915: UPSTREAM: 90985: Set session scanning to manual to avoid discovering all iSCSI devices during login
  vendor/k8s.io/kubernetes/pkg/volume/iscsi/iscsi_util.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm, vendor-update

#25008 Bug 1765301: UPSTREAM: 89379: deflake grace period for pod deletion in node e2e
  test/extended/util/annotate/generated/zz_generated.annotations.go
  vendor/k8s.io/kubernetes/test/e2e/node/pods.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, vendor-update

#24700 Bug 1813421: e2e well-known: use proxy if in a proxied environment
  test/extended/oauth/http1.go
  test/extended/oauth/well_known.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#25012 Bug 1840707: oVirt, skip network service tests
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#25018 Bug 1839187: more upstream to installed template switch in image-eco (django)
  test/extended/image_ecosystem/s2i_python.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25023 Bug 1837108: Use HostIP on internal connectivity test for vsphere
  test/extended/networking/internal_ports.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#25032 Bug 1833558: update test to be more resilient for oc adm policy add-sss-to-user changes
  test/extended/testdata/bindata.go
  test/extended/testdata/cmd/test/cmd/admin.sh
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#24993 Bug 1833387: test/extended/operators/operators: Drop cvoWait and operatorWait
  test/extended/operators/operators.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#25037 Bug 1839517: UPSTREAM: <carry>: kube-controller-manager: allow running bare kube-controller-manager
  vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go
  vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/patch.go
  vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/patch_flags.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm, vendor-update

#25039 Bug 1841097: wait for the default service account in must-gather test
  test/extended/cli/mustgather.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#25034 Bug 1824423: Revert "UPSTREAM: <drop>: Increate timeout in volume expansion test"
  vendor/k8s.io/kubernetes/test/e2e/framework/util.go
  vendor/k8s.io/kubernetes/test/e2e/storage/testsuites/volume_expand.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, vendor-update

#24956 Bug 1813894: Disable the addition of service ca to token secrets
  vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/patch_satoken.go
  vendor/k8s.io/kubernetes/pkg/controller/serviceaccount/tokens_controller.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, vendor-update

#25040 Bug 1841185: more upstream to installed template switch in image-eco (django this time)
  test/extended/image_ecosystem/s2i_python.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#25033 Bug 1841315: reenable jenkins e2e in e2e-gcp-builds
  test/extended/builds/pipeline_origin_bld.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
