Repository openshift/origin, pull requests merged in 2020-08, with the labels that each got.

#25355 test: Fix inconsistencies in path reporting between Go versions
  test/extended/util/annotate/annotate.go
  test/extended/util/disruption/disruption.go
  test/extended/util/test.go
Labels: approved, lgtm

#25331 Bug 1860837: Re-enable prometheus named network metrics test.
  test/extended/prometheus/prometheus.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#25217 e2e-oauth-authn: support sha256 prefixed tokens
  test/extended/oauth/token.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, vendor-update

#25232 Added skips to checks for IBM serviceaccount and IAM components
  test/extended/authorization/authorization.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm

#25357 Update expected text for test-cmd timeout
  test/extended/testdata/bindata.go
  test/extended/testdata/cmd/test/cmd/timeout.sh
Labels: approved, lgtm

#25349 BUG 1820422: test: extended: reenable ImmutableEphemeralVolume test
  test/extended/util/annotate/rules.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25364 skip openshift-marketplace namespace when checking that images come from the release
  test/extended/operators/images.go
Labels: approved, lgtm

#25332 test/extended/prometheus: remove exclusion for targets already exposing data over HTTPS
  test/extended/prometheus/prometheus.go
Labels: approved, lgtm

#25363 e2e/oauth/expiration: support sha256 tokens – auth tokens
  test/extended/oauth/expiration.go
Labels: approved, lgtm

#25300 Removed the "Managed cluster should ensure control plane pods do not run in best-effort QoS" test from IBM's skipped list
  test/extended/util/annotate/rules.go
Labels: approved, lgtm

#25367 [release-4.4] Fix commit checker
  hack/verify-upstream-commits.sh
  tools/rebasehelpers/commitchecker/commitchecker.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm, vendor-update

#25366 [release-4.5] Fix commit checker
  hack/verify-upstream-commits.sh
  tools/rebasehelpers/commitchecker/commitchecker.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#25309 [release-4.5] Bug 1846453: UPSTREAM: 90377: fix exclusive CPU allocations being deleted at container restart
  vendor/k8s.io/kubernetes/pkg/kubelet/cm/cpumanager/cpu_manager.go
  vendor/k8s.io/kubernetes/pkg/kubelet/cm/cpumanager/cpu_manager_test.go
  vendor/k8s.io/kubernetes/pkg/kubelet/cm/internal_container_lifecycle.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, vendor-update

#25380 fix disruption test name
  test/extended/util/disruption/controlplane/controlplane.go
Labels: approved, lgtm

#25326 Bug 1860830: Ensure Azure availability zone is always in lower cases
  vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/azure/azure_standard.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/azure/azure_vmss.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/azure/azure_vmss_test.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/azure/azure_zones.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/azure/azure_zones_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm, vendor-update

#25343 [release-4.4] Bug 1861850: UPSTREAM: 90740: Update createBalancedPodForNodes function in scheduler e2e
  vendor/k8s.io/kubernetes/test/e2e/scheduling/priorities.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm, vendor-update

#25373 e2e: topomgr: disable again failing test
  test/extended/topology_manager/resourcealign.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#25365 e2e/oauth: deflake by using random tokens
  test/extended/oauth/token.go
Labels: approved, lgtm

#25377 extended/oauth: skip sha256 test until https://github.com/openshift/kubernetes/pull/305 merged
  test/extended/oauth/token.go
Labels: approved, lgtm

#25374 oauth: switch to sha256~ prefix
  test/extended/oauth/expiration.go
  test/extended/oauth/token.go
Labels: approved, lgtm

#25389 adds a new monitoring test for checking OAuth API server
  pkg/monitor/api.go
  test/e2e/upgrade/upgrade.go
  test/extended/dr/machine_recover.go
  test/extended/util/disruption/controlplane/controlplane.go
Labels: approved, lgtm

#25370 Bug 1861215: test: extended: unskip secret test
  go.mod
  go.sum
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/admission/customresourcevalidation/customresourcevalidationregistration/cr_validation_registration.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/admission/customresourcevalidation/network/BUILD
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/admission/customresourcevalidation/network/validate_network_config.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/authentication/oauth/tokenauthenticator.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_container_windows.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_sandbox.go
  vendor/k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/controller_policy.go
  vendor/k8s.io/kubernetes/test/e2e/generated/bindata.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, vendor-update

#25388 Print error if watch.Error happens
  test/extended/controller_manager/deploy_trigger.go
Labels: approved, lgtm

#25390 Revert "extended/oauth: skip sha256 test until https://github.com/openshift/kubernetes/pull/305 merged"
  test/extended/oauth/token.go
Labels: approved, lgtm

#25368 [release-4.3] Fix commit checker
  hack/verify-upstream-commits.sh
  tools/rebasehelpers/commitchecker/commitchecker.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#25399 test: Upgrade test should log more granular failures
  test/e2e/upgrade/monitor.go
  test/e2e/upgrade/upgrade.go
  test/extended/dr/machine_recover.go
  test/extended/dr/quorum_restore.go
  test/extended/util/disruption/disruption.go
Labels: approved, lgtm

#25220 Re-enable skipped conformance tests for IBM Cloud
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm

#25402 Remove exit code skip
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm

#25287 Bug 1857081: Include pod /etc/hosts in ephemeral storage calculation for eviction
  vendor/k8s.io/kubernetes/pkg/kubelet/eviction/BUILD
  vendor/k8s.io/kubernetes/pkg/kubelet/eviction/eviction_manager.go
  vendor/k8s.io/kubernetes/pkg/kubelet/eviction/helpers.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_pods.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_test.go
  vendor/k8s.io/kubernetes/pkg/kubelet/runonce_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, vendor-update

#25411 allow longer upgrade times to run tests, but continue to fail junit at 75 minutes
  test/e2e/upgrade/upgrade.go
Labels: approved, lgtm

#25409 split the crashlooping pod test to more precisely tag recycler pods
  test/extended/operators/cluster.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#25413 remove marketplace tests
  test/extended/include.go
  test/extended/marketplace/marketplace_diffname.go
  test/extended/marketplace/marketplace_labels.go
  test/extended/marketplace/marketplace_utils.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, priority/critical-urgent

#25327 Bug 1860832: Ensure Azure availability zone is always in lower cases
  vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/azure/azure_standard.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/azure/azure_vmss.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/azure/azure_vmss_test.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/azure/azure_zones.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/azure/azure_zones_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#25386 Bug 1826094: Add retry options to Prometheus helper curl command
  test/extended/util/prometheus/helpers.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25288 Bug 1857080: Include pod /etc/hosts in ephemeral storage calculation for eviction
  vendor/k8s.io/kubernetes/pkg/kubelet/eviction/BUILD
  vendor/k8s.io/kubernetes/pkg/kubelet/eviction/eviction_manager.go
  vendor/k8s.io/kubernetes/pkg/kubelet/eviction/helpers.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_pods.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_test.go
  vendor/k8s.io/kubernetes/pkg/kubelet/runonce_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, vendor-update

#25417 finish splitting each part of the upgrade into distinct junit
  test/e2e/upgrade/upgrade.go
Labels: approved, lgtm

#25419 test: extended: add test checking for mismatch between Machines and Nodes
  test/extended/machines/cluster.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#25281 Bug 1857025: Sanitize TLS config that has key bundled with cert
  pkg/route/controller/routeapihelpers/validation.go
  pkg/route/controller/routeapihelpers/validation_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#25350 [release-3.11] Bug 1760807: UPSTREAM: <carry>: Enforce label selector validation in scheduler podAffinity
  vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/predicates/predicates.go
  vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/predicates/predicates_test.go
  vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/priorities/interpod_affinity.go
  vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/priorities/interpod_affinity_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#25381 Update README and add script to simplify vendoring openshift/kubernetes
  HACKING.md
  README.md
  hack/update-kube-vendor.sh
Labels: approved, lgtm

#25423 bug 1870247: re-establish etcd connection if required for etcd test
  test/extended/etcd/etcd_storage_path.go
  test/extended/etcd/etcd_test_runner.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#25359 [release-4.5] Bug 1862194: UPSTREAM: 85983: fix metrics kubelet_running_pod_count
  vendor/k8s.io/kubernetes/pkg/kubelet/pleg/generic.go
  vendor/k8s.io/kubernetes/pkg/kubelet/pleg/generic_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm, vendor-update

#25425 Bug 1870345: test: extended: only run new machines test against platforms that have machines
  test/extended/machines/cluster.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25410 Bug 1868436: test/extended/dr: fix quorum-guard namespace
  test/extended/dr/quorum_restore.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#25344 [release-4.3] Bug 1852857: UPSTREAM: 90740: Update createBalancedPodForNodes function in scheduler e2e
  vendor/k8s.io/kubernetes/test/e2e/scheduling/priorities.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#25154 Bug 1848437: 4.4: UPSTREAM: 91748: FieldManager: Reset if we receive nil or a list with one
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/validation/validation.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/validation/validation_test.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/create.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/fieldmanager.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/fieldmanager_test.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/internal/BUILD
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/internal/atmostevery.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/internal/atmostevery_test.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/internal/managedfields.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/internal/managedfields_test.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/structuredmerge.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/patch.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/update.go
  vendor/k8s.io/kubernetes/test/integration/apiserver/apply/apply_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm, vendor-update

#25441 Bug 1863763: Fix statefulset update loop
  vendor/k8s.io/kubernetes/pkg/controller/history/controller_history.go
  vendor/k8s.io/kubernetes/pkg/controller/history/controller_history_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25271 [release-3.11] Bug 1855852: Backport HAProxy report all backend metrics
  pkg/router/metrics/haproxy/haproxy.go
  test/extended/router/metrics.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#25421 Bug 1872038: openshift-tests: fix upgrade test suites reference to controlplane availability tests
  cmd/openshift-tests/upgrade.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#25339 Bug 1861218: Tune storage tests for 4.6
  test/extended/util/annotate/rules.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25058 Bug 1871080: IR-21: Adding tests for image stream imports on blocked/insecure registries
  go.mod
  test/extended/images/imagestreamimport.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25369 Bug 1862426: gather the audit logs for oauth apiserver
  test/extended/cli/mustgather.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#25404 Bug 1723603: test: don't skip storage tests in Azure
  test/extended/util/annotate/rules.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25414 Bug 1861526: test: extended: reenable service account test disabled during rebase
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25428 tests/cluster: Check for machinesets, not platforms
  test/extended/machines/cluster.go
Labels: approved, bugzilla/valid-bug, lgtm

#25445 Bug 1870222: remove skipped forcepull test since imagestream prechecks can still fail
  test/extended/builds/forcepull.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25407 Bug 1868314: UPSTREAM: 93355: Fix scheduler issue with nodetree additions
  vendor/k8s.io/kubernetes/pkg/scheduler/internal/cache/cache.go
  vendor/k8s.io/kubernetes/pkg/scheduler/internal/cache/cache_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm, vendor-update

#25415 Bug 1869220: UPSTREAM: <carry>: oauth: support sha256~ prefixed tokens
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/authentication/oauth/bootstrapauthenticator.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/authentication/oauth/tokenauthenticator.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/authentication/oauth/tokenauthenticator_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm, vendor-update

#25427 BUG 1863009: vSphere provision failure on ocp46
  go.mod
  go.sum
  vendor/k8s.io/legacy-cloud-providers/vsphere/nodemanager.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, vendor-update

#25449 Bug 1871948: Use WaitForABuild helper instead of wait.Poll
  test/extended/images/layers.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25236 Bug 1873961: e2e/apiserver: check for LateConnections+NonGracefulTermination events
  test/extended/apiserver/graceful_termination.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
