Repository openshift/origin, pull requests merged in 2021-08, with the labels that each got.

#26365 Bug 1985073: test/e2e/upgrade/alert: Temporarily allow ExtremelyHighIndividualControlPlaneCPU
  test/e2e/upgrade/alert/alert.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#26367 Bug 1986003: Ignore openshift-marketplace pods
  test/extended/pods/priorityclasses.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#26370 Bug 1986003: Disable oc adm storage-admin and idle tests
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#26371 Bug 1988828: fix test - reduce minimum size of expected files in must-gather tests
  test/extended/cli/mustgather.go
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#26374 Bug 1941224: pkg/synthetictests/operators: Drop Progressing from "stable" transition checks
  pkg/synthetictests/operators.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#26372 Bug 1986003: Temporarily disable oc observe single test
  test/extended/cli/observe.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#26355 Bug 1981582: [release-4.6] use vpa package and add debug logs to olm test
  test/extended/operators/olm.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#26360 Update canary/minimal e2e suite for 4.9
  cmd/openshift-tests/minimal.go
Labels: approved, bugzilla/valid-bug, lgtm

#26380 add several skip cases for pathological events
  cmd/openshift-tests/images.go
  pkg/monitor/api.go
  pkg/monitor/cmd.go
  pkg/synthetictests/duplicated_events.go
  pkg/synthetictests/duplicated_events_test.go
  pkg/synthetictests/event_junits.go
  pkg/synthetictests/events.go
  pkg/synthetictests/events_test.go
  pkg/test/ginkgo/cmd_runsuite.go
  pkg/test/ginkgo/synthentic_tests.go
Labels: approved, lgtm, bugzilla/valid-bug

#26382 tidy up the duplicate event handling
  pkg/synthetictests/duplicated_events.go
Labels: approved, lgtm, bugzilla/valid-bug

#26266 Bug 1980141: Skip the new "NetPol" tests for now
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#26373 bug 1989961: refine apiserver downtime sampling and calculations
  pkg/monitor/monitorapi/types.go
  pkg/monitor/sampler.go
  pkg/synthetictests/apiserver.go
  test/extended/util/disruption/disruption.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#26386 Bug 1991507: kubectl: mark exit codes test flaky until 1.22 rebase
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#26387 Bug 1981736: Fix a lock contention problem in the proxy
  vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#26389 Bug 1986413: Do not use egressIP on reply packets
  pkg/network/node/ovscontroller.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#26363 temporary search for memory.max in build container during quota test
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/build-quota/.s2i/bin/assemble
Labels: approved, lgtm, bugzilla/valid-bug

#26349 Ignore upgradable false condition on TechPreview clusters
  test/extended/operators/operators.go
Labels: approved, lgtm, bugzilla/valid-bug

#26141 Bug 1992596: e2e/cli: move half of builds.sh to proper e2e
  test/extended/cli/builds.go
  test/extended/testdata/bindata.go
  test/extended/testdata/cmd/test/cmd/builds.sh
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#26394 Bug 1991507: Remove kubectl command exit codes from canary tests
  cmd/openshift-tests/minimal.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#26384 Bug 1990988: Updating s2i images for php
  test/extended/image_ecosystem/s2i_images.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#25891 [release-3.11] Bug 1884422: Backport router hostindex fixes
  pkg/router/controller/hostindex/activation.go
  pkg/router/controller/hostindex/hostindex_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#26393 Allow TechPreviewNoUpgrade alerts when running on a TechPreview cluster
  test/extended/prometheus/prometheus.go
Labels: approved, lgtm, bugzilla/valid-bug

#26391 Bug 1994113: exclude local volume conflicts
  pkg/synthetictests/duplicated_events.go
  pkg/synthetictests/duplicated_events_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#26377 Bug 1986003: Retry kubeconfig checks, when kube-apiserver is temporarily unavailable
  test/extended/apiserver/kubeconfigs.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#26362 Bug 1994613: Re-disable the IPV6 should provide Internet connection test
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#26409 Bug 1993985, Bug 1993980, Bug 1990041: duplicated events: update list of known issues
  pkg/synthetictests/duplicated_events.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-unspecified

#26407 Bug 1986003: Switch kubeconfig retries to use backoff
  test/extended/apiserver/kubeconfigs.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#26399 BUILD-278: account for cgroup v2 swap file only having swap for its amount, while cgroup v1 has memory+swap for its amount
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/build-quota/.s2i/bin/assemble
Labels: approved, lgtm, bugzilla/valid-bug

#26406 Add 'DeploymentAwaitingCancellation' as an allowed repeated event
  pkg/synthetictests/duplicated_events.go
Labels: approved, lgtm, bugzilla/valid-bug

#26414 Bug 1996097: Skip renamed dualstack tests in OVNKubernetes
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#26397 fix: add proxy support to OAuthServer tests
  test/extended/oauth/requestheaders.go
Labels: approved, lgtm, bugzilla/valid-bug

#26403 Add me to test approvers so I can approve annotation changes
  test/extended/OWNERS
Labels: approved, lgtm, bugzilla/valid-bug

#26392 kubelet: detect process overlap during apiserver rollout
  pkg/synthetictests/event_junits.go
  pkg/synthetictests/kubelet.go
Labels: approved, lgtm, bugzilla/valid-bug

#26422 Bug 1995198: Skip admin can subscribe to operator using olm test on arm64
  test/extended/operators/olm.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#26421 Fix regex pattern for `DeploymentAwaitingCancellation` event
  pkg/synthetictests/duplicated_events.go
Labels: approved, lgtm, bugzilla/valid-bug

#26420 Add imagepull backoff to frequent event allowlist
  pkg/synthetictests/duplicated_events.go
Labels: approved, lgtm, bugzilla/valid-bug

#26416 Bug 1992596: cli: use ubi8/ruby-27
  test/extended/cli/builds.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#26428 Bug 1986307: update downstream k8 dependency
  go.mod
  go.sum
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
  vendor/k8s.io/apiserver/pkg/server/config.go
  vendor/k8s.io/apiserver/pkg/server/filters/waitgroup.go
  vendor/k8s.io/apiserver/pkg/server/filters/with_retry_after.go
  vendor/k8s.io/apiserver/pkg/server/genericapiserver.go
  vendor/k8s.io/apiserver/pkg/server/lifecycle_signals.go
  vendor/k8s.io/apiserver/pkg/server/options/server_run_options.go
  vendor/k8s.io/apiserver/pkg/server/patch_config.go
  vendor/k8s.io/cloud-provider/go.mod
  vendor/k8s.io/cloud-provider/go.sum
  vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go
  vendor/k8s.io/kubernetes/openshift-hack/e2e/annotate/rules.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/admission/autoscaling/managementcpusoverride/admission.go
  vendor/k8s.io/mount-utils/go.mod
  vendor/k8s.io/mount-utils/go.sum
  vendor/k8s.io/utils/clock/clock.go
  vendor/k8s.io/utils/lru/lru.go
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, bugzilla/severity-high

#26412 Bug 1985998: Enable CSI hostpath tests
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#26436 Bug 1989505: enable back oc observe test
  test/extended/cli/observe.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#26337 Bug 1999561: Add API rollout resiliency test
  test/extended/apiserver/resiliency.go
  test/extended/single_node/topology.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low
