Repository openshift/origin, pull requests merged in 2021-11, with the labels that each got.

#26554 Disable vSphere-specific storage tests
  test/doc.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
  tools/gotest2junit/test/test_test.go
Labels: approved, lgtm

#26560 Bug 2019516: Skip test 'clone repository using git:// protocol should clone using git:// if no proxy is configured'
  test/extended/builds/clone_git_protocol.go
Labels: bugzilla/valid-bug, bugzilla/severity-high

#26555 Oauth server tests: Get Oauth issuer url from discovery instead of route
  test/extended/oauth/client_secret.go
Labels: approved, lgtm

#26456 Bug 1826225: test/extended/router: Enable edge-terminated gRPC
  test/extended/router/grpc-interop.go
  test/extended/testdata/bindata.go
  test/extended/testdata/router/router-grpc-interop-routes.yaml
  test/extended/testdata/router/router-grpc-interop.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#26451 Bug 1999561: Extend API rollout resiliency test to validate pods restart during the rollout
  test/extended/apiserver/resiliency.go
  test/extended/operators/cluster.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#26536 Bug 2000216: Add more tests for image policy
  test/extended/images/resolve.go
  test/extended/util/OWNERS
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#26558 Bug 2019375: tests: skip some tests for proxy
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#26484 Add baremetal operator validating webhook healthy test
  test/extended/baremetal/hosts.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#26525 Bug 2009879: Add admin ack Upgradeable condition gate test
  test/e2e/upgrade/adminack/adminack.go
  test/e2e/upgrade/upgrade.go
  test/extended/adminack/adminack.go
  test/extended/include.go
  test/extended/util/adminack.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#26530 Bug 2011293: add default search image registry test to build e2es
  test/extended/builds/docker_pullsearch.go
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/test-build-search-registries.yaml
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#26565 Disable topology tests for vSphere in-tree storage plugin
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm

#26570 Bug 1992596: e2e/cli: Add probe tests
  test/extended/cli/probe.go
  test/extended/testdata/bindata.go
  test/extended/testdata/cmd/test/cmd/basicresources.sh
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#26548 write disruption data
  pkg/monitor/api.go
  pkg/monitor/monitorapi/disruption.go
  pkg/monitor/write_job_run_data.go
  pkg/synthetictests/apiserver.go
  pkg/test/ginkgo/cmd_runsuite.go
  test/e2e/upgrade/service/service.go
  test/extended/util/disruption/frontends/frontends.go
  test/extended/util/disruption/imageregistry/imageregistry.go
Labels: approved, lgtm

#26545 refactor writing data artifacts without behavior change
  pkg/monitor/write_job_run_data.go
  pkg/test/ginkgo/cmd_runsuite.go
Labels: approved

#26526 Bug 2010225: vendor: e2e iperf2 change threshold to 10MBps = 80 Mbps
  go.mod
  go.sum
  test/extended/util/annotate/generated/zz_generated.annotations.go
  vendor/k8s.io/apiserver/pkg/server/config.go
  vendor/k8s.io/apiserver/pkg/server/filters/patch_optin_retry.go
  vendor/k8s.io/apiserver/pkg/server/filters/with_retry_after.go
  vendor/k8s.io/apiserver/pkg/server/options/server_run_options.go
  vendor/k8s.io/apiserver/pkg/server/patch_config.go
  vendor/k8s.io/kubernetes/cmd/kubelet/app/options/globalflags_linux.go
  vendor/k8s.io/kubernetes/openshift-hack/e2e/annotate/rules.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/admission/network/restrictedendpoints/endpoint_admission.go
  vendor/k8s.io/kubernetes/pkg/kubelet/cadvisor/cadvisor_linux.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_pods.go
  vendor/k8s.io/kubernetes/pkg/kubelet/pod_workers.go
  vendor/k8s.io/kubernetes/pkg/kubelet/status/status_manager.go
  vendor/k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/controller_policy.go
  vendor/k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go
  vendor/k8s.io/kubernetes/test/e2e/network/networking_perf.go
  vendor/k8s.io/kubernetes/test/e2e/node/pods.go
  vendor/k8s.io/legacy-cloud-providers/vsphere/vsphere_util.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#26573 Bug 1992596: e2e/cli: Add env tests
  test/extended/cli/env.go
  test/extended/testdata/bindata.go
  test/extended/testdata/cmd/test/cmd/basicresources.sh
  test/extended/testdata/test-buildcli.json
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#26574 CLI tests: Softcode the kubernetes.default cluster IP
  test/extended/cli/observe.go
Labels: approved, lgtm

#26581 Bug 2021433: Disable new build test on disconnected
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#26571 add alerts to tracked metadata
  pkg/monitor/monitorapi/identification.go
  pkg/monitor/write_job_run_data.go
Labels: approved, lgtm

#26578 Bug 1992596: e2e/cli: Finish basicresources.sh migration
  test/extended/cli/basics.go
  test/extended/cli/expose.go
  test/extended/cli/probe.go
  test/extended/testdata/bindata.go
  test/extended/testdata/cmd/test/cmd/basicresources.sh
  test/extended/testdata/cmd/test/cmd/testdata/application-template-stibuild.json
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#26580 Bug 2002776: fix intermittent test failure due to missing tools image
  test/extended/prometheus/prometheus.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#26583 Set upper bounds to 50 percentile
  test/extended/apiserver/api_requests.go
Labels: approved, lgtm

#26591 Refresh prometheus OWNERS
  test/extended/prometheus/OWNERS
Labels: approved, lgtm

#26594 oauth e2e: fix the expected http2 error to match golang 1.17+
  test/extended/oauth/http1.go
Labels: approved, lgtm

#26596 oauth/requestheaders: escape semicolon in URI
  test/extended/oauth/requestheaders.go
Labels: approved, lgtm

#26597 Revert "Finish basicresources.sh migration"
  test/extended/cli/basics.go
  test/extended/cli/expose.go
  test/extended/cli/probe.go
  test/extended/testdata/bindata.go
  test/extended/testdata/cmd/test/cmd/basicresources.sh
  test/extended/testdata/cmd/test/cmd/testdata/application-template-stibuild.json
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#26601 account for longer tests runs in the watch pathological watch test case
  test/extended/apiserver/api_requests.go
Labels: approved, lgtm

#26600 Bug 2020611: Reduce Test Focus for Jenkins
  test/extended/builds/imagechangetriggers.go
  test/extended/builds/jenkins_autoprovision.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#26576 Bug 2021141: Cluster should allow a fast rollout of kube-apiserver is…
  test/extended/apiserver/resiliency.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#26592 Fix single-node frontends disruption test tolerated disruption %
  test/extended/util/disruption/frontends/frontends.go
Labels: approved, lgtm

#26602 pkg/synthetictests: add toleration for missing versioned etcd-endpoints cm during upgrade
  pkg/synthetictests/duplicated_events.go
Labels: approved, lgtm

#26514 Added 2 Whereabouts e2e tests
  test/extended/networking/whereabouts.go
  test/extended/testdata/bindata.go
  test/extended/testdata/net-attach-defs/whereabouts-nad.yml
  test/extended/testdata/net-attach-defs/whereabouts-race-awake.yml
  test/extended/testdata/net-attach-defs/whereabouts-race-sleepy.yml
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#26608 Update baremetal tests owners
  test/extended/baremetal/OWNERS
Labels: approved, lgtm

#26605 prevent rare alert gathering panic
  pkg/monitor/alerts.go
Labels: approved, lgtm

#26541 Add parallel test for new baremetal resources
  test/extended/baremetal/hosts.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#26552 kubeconfigs: fix capture loop variable in closure
  test/extended/apiserver/kubeconfigs.go
Labels: approved, lgtm

#26579 Managed cluster should ensure control plane operator: Allow hypershift kapi proxy
  test/extended/operators/tolerations.go
Labels: approved, lgtm

#26609 olm: enable test on arm64
  test/extended/olm/olm.go
Labels: approved, lgtm

#26603 Bug 2022797: Switch the cluster-role-reapers test to Serial
  test/extended/cli/admin.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#26610 Bug 2023631: Create new-project without updating kubeconfig
  test/extended/cli/admin.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#26547 Skip imageregistry serial test for disconnected environments
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm

#26537 Bug 2015624: Refactor IBM Cloud skips to External
  test/extended/authentication/front_proxy.go
  test/extended/authorization/authorization.go
  test/extended/cli/explain.go
  test/extended/cli/mustgather.go
  test/extended/csrapprover/csrapprover.go
  test/extended/etcd/etcd_test_runner.go
  test/extended/oauth/client_secret.go
  test/extended/oauth/oauthcertfallback.go
  test/extended/oauth/requestheaders.go
  test/extended/oauth/well_known.go
  test/extended/prometheus/prometheus.go
  test/extended/prometheus/prometheus_builds.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
  test/extended/util/cluster/cluster.go
  test/extended/util/framework.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#26617 Bug 2023238: Skipping Django Test until bug is fixed
  test/extended/image_ecosystem/s2i_python.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#26620 Bug 1992596: e2e/cli: Finish basicresources.sh migration
  test/extended/cli/basics.go
  test/extended/cli/expose.go
  test/extended/cli/probe.go
  test/extended/testdata/bindata.go
  test/extended/testdata/cmd/test/cmd/basicresources.sh
  test/extended/testdata/cmd/test/cmd/testdata/application-template-stibuild.json
  test/extended/testdata/cmd/test/cmd/testdata/external-service-ipv6.yaml
  test/extended/testdata/cmd/test/cmd/testdata/multiport-service-ipv6.yaml
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#26627 Allow operator-lifecycle-manager-packageserver to not define related objects when external controlplane
  test/extended/operators/clusteroperators.go
Labels: approved, lgtm

#26625 Allow disruption in image-registry availability during single node upgrades
  test/extended/util/disruption/imageregistry/imageregistry.go
Labels: approved, lgtm

#26628 Disable app behind service lb with pdb disruption test on single-node
  test/e2e/upgrade/service/service.go
Labels: approved, lgtm

#26624 Allow even greater downtime on Azure single-node upgrade
  test/extended/util/disruption/controlplane/controlplane.go
Labels: approved, lgtm

#26589 Bug 1992596: e2e/cli: Migrate apiresources.go and add version
  test/extended/cli/apiresources.go
  test/extended/cli/basics.go
  test/extended/testdata/bindata.go
  test/extended/testdata/cmd/test/cmd/apiresources.sh
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#26630 cli: use ProxyFromEnvironment for requests
  test/extended/cli/basics.go
Labels: approved, lgtm

#26469 Bug 1880738: Minimise test disruption by removing newest workers in scale down
  test/extended/machines/scale.go
  test/extended/machines/workers.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#26623 Local kubeconfig tests: Allow no master nodes when external controlpane topology
  test/extended/apiserver/kubeconfigs.go
Labels: approved, lgtm

#26636 OC explain should contain proper spec+status for CRDs: Skip some resources when controlplane is external
  test/extended/cli/explain.go
Labels: approved, lgtm

#26637 Fix 'oc expose can ensure the expose command' for custom service cidrs
  test/extended/testdata/bindata.go
  test/extended/testdata/cmd/test/cmd/testdata/external-service.yaml
  test/extended/testdata/cmd/test/cmd/testdata/multiport-service.yaml
Labels: approved, lgtm

#26642 double space preventing proper reporting for disruption
  pkg/monitor/api.go
Labels: approved, lgtm

#26639 Fix 'should only include cluster daemonsets that have maxUnavailable' for Hypershift
  test/extended/operators/daemon_set.go
Labels: approved, lgtm

#26612 Update imagestreams in build and image-ecosystem
  test/extended/image_ecosystem/s2i_images.go
  test/extended/image_ecosystem/scl.go
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/build-pruning/default-group-build-config.yaml
  test/extended/testdata/builds/build-pruning/default-legacy-build-config.yaml
  test/extended/testdata/builds/build-pruning/errored-build-config.yaml
  test/extended/testdata/builds/build-pruning/failed-build-config.yaml
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#26616 Specify default namespace when getting API endpoint
  test/extended/cli/builds.go
Labels: approved, lgtm, backport-risk-assessed

#26634 Bug 2025722: test/e2e/upgrade: Bump durationToSoftFailure by 15m for minor updates
  test/e2e/upgrade/upgrade.go
  test/extended/util/adminack.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#26595 Add test to check kubernetes version
  test/extended/cli/version.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#26652 Move shared OWNERS file into generated dir
  test/extended/util/annotate/generated/OWNERS
Labels: approved, lgtm

#26650 test/extended/util/openshift/clusterversionoperator: Delegate admin-ack ownership
  OWNERS_ALIASES
  test/e2e/upgrade/adminack/OWNERS
  test/e2e/upgrade/adminack/adminack.go
  test/extended/adminack/OWNERS
  test/extended/adminack/adminack.go
  test/extended/util/openshift/clusterversionoperator/OWNERS
  test/extended/util/openshift/clusterversionoperator/adminack.go
Labels: approved, lgtm

#26655 Skip oc version test in disconnected
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm

#26654 Bug 1929650: Increase OVN upgrade timeout by 15m
  test/e2e/upgrade/upgrade.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-low, backport-risk-assessed

#26649 Bug 2026806: test/e2e/upgrade/adminack: Poll gates for duration of update
  test/e2e/upgrade/adminack/adminack.go
  test/extended/util/openshift/clusterversionoperator/adminack.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low
