Repository openshift/origin, pull requests merged in 2021-12, with the labels that each got.

#26638 OLM should have imagePullPolicy: Fix when ExternalControlplane
  test/extended/olm/olm.go
  test/extended/util/client.go
  test/extended/util/framework.go
Labels: approved, lgtm

#26659 Revert "Add test to check kubernetes version"
  test/extended/cli/version.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm

#26663 vendor: update openshift/kubernetes to include gcp quota fix
  go.mod
  go.sum
  vendor/github.com/openshift/apiserver-library-go/pkg/admission/imagepolicy/apis/imagepolicy/v1/defaults.go
  vendor/github.com/openshift/apiserver-library-go/pkg/admission/imagepolicy/imagepolicy.go
  vendor/github.com/openshift/apiserver-library-go/pkg/admission/imagepolicy/imagereferencemutators/pods.go
  vendor/github.com/openshift/apiserver-library-go/pkg/admission/quota/clusterresourcequota/admission.go
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccadmission/admission.go
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccmatching/matcher.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/admission/admissionenablement/admission_config.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/admission/customresourcevalidation/apiserver/validate_apiserver.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/admission/namespaceconditions/decorator.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_pods.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_manager.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/logs/logs.go
  vendor/k8s.io/kubernetes/pkg/kubelet/metrics/metrics.go
  vendor/k8s.io/kubernetes/pkg/kubelet/pod_workers.go
  vendor/k8s.io/kubernetes/pkg/kubelet/status/status_manager.go
  vendor/k8s.io/kubernetes/pkg/volume/csi/csi_mounter.go
  vendor/k8s.io/kubernetes/pkg/volume/util/hostutil/fake_hostutil.go
  vendor/k8s.io/kubernetes/pkg/volume/util/hostutil/hostutil_linux.go
  vendor/k8s.io/kubernetes/pkg/volume/util/subpath/subpath_linux.go
  vendor/k8s.io/kubernetes/test/e2e/autoscaling/cluster_size_autoscaling.go
  vendor/k8s.io/kubernetes/test/e2e/framework/pv/pv.go
  vendor/k8s.io/kubernetes/test/e2e/framework/timeouts.go
  vendor/k8s.io/kubernetes/test/e2e/node/pods.go
  vendor/k8s.io/kubernetes/test/e2e/storage/flexvolume_mounted_volume_resize.go
  vendor/k8s.io/kubernetes/test/e2e/storage/flexvolume_online_resize.go
  vendor/k8s.io/kubernetes/test/e2e/storage/framework/volume_resource.go
  vendor/k8s.io/kubernetes/test/e2e/storage/nfs_persistent_volume-disruptive.go
  vendor/k8s.io/kubernetes/test/e2e/storage/persistent_volumes-gce.go
  vendor/k8s.io/kubernetes/test/e2e/storage/persistent_volumes-local.go
  vendor/k8s.io/kubernetes/test/e2e/storage/persistent_volumes.go
  vendor/k8s.io/kubernetes/test/e2e/storage/ubernetes_lite_volumes.go
  vendor/k8s.io/kubernetes/test/e2e/storage/volume_metrics.go
  vendor/k8s.io/kubernetes/test/e2e/storage/vsphere/persistent_volumes-vsphere.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update

#26657 Bug 2028021: Bump update time limit 4.8
  test/e2e/upgrade/upgrade.go
  test/extended/util/adminack.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#26661 Bug 2026806: Admin ack ignore unrelated upgradeable false
  test/extended/util/openshift/clusterversionoperator/adminack.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#26668 Bug 2026806: clusterversionoperator/adminack.go: Check for nil cm map
  test/extended/util/openshift/clusterversionoperator/adminack.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#26667 Alter junit test suite names for jobs with multiple junit xmls.
  cmd/openshift-tests/openshift-tests.go
  cmd/openshift-tests/upgrade.go
  pkg/test/ginkgo/cmd_runsuite.go
Labels: approved, lgtm

#26669 refactor disruption suite to collapse to a single implementation
  e2echart/e2e-chart-template.html
  pkg/monitor/api.go
  pkg/monitor/disruption_backend_sampler.go
  pkg/monitor/disruption_known_backends.go
  pkg/monitor/disruption_locator.go
  pkg/monitor/monitor.go
  pkg/monitor/sampler.go
  pkg/monitor/types.go
  pkg/test/ginkgo/status.go
  test/e2e/upgrade/upgrade.go
  test/extended/testdata/bindata.go
  test/extended/util/disruption/backend_sampler_tester.go
  test/extended/util/disruption/controlplane/controlplane.go
  test/extended/util/disruption/disruption.go
  test/extended/util/disruption/frontends/frontends.go
  test/extended/util/disruption/imageregistry/imageregistry.go
Labels: approved, lgtm

#26671 Revert "refactor disruption suite to collapse to a single implementation"
  e2echart/e2e-chart-template.html
  pkg/monitor/api.go
  pkg/monitor/disruption_backend_sampler.go
  pkg/monitor/disruption_known_backends.go
  pkg/monitor/disruption_locator.go
  pkg/monitor/monitor.go
  pkg/monitor/sampler.go
  pkg/monitor/types.go
  pkg/test/ginkgo/status.go
  test/e2e/upgrade/upgrade.go
  test/extended/testdata/bindata.go
  test/extended/util/disruption/backend_sampler_tester.go
  test/extended/util/disruption/controlplane/controlplane.go
  test/extended/util/disruption/disruption.go
  test/extended/util/disruption/frontends/frontends.go
  test/extended/util/disruption/imageregistry/imageregistry.go
Labels: approved, lgtm

#26656 Bug 2027929: test/e2e/upgrade/adminack: Poll gates for duration of update
  test/e2e/upgrade/adminack/adminack.go
  test/extended/util/adminack.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-low, backport-risk-assessed

#26632 OLM: Fix tests that check on pods when external ControlplaneToplogy
  test/extended/olm/olm.go
Labels: approved, lgtm

#26658 Fix etcd leader changes are not excessive for Hypershift
  test/extended/etcd/leader_changes.go
Labels: approved, lgtm

#26670 Disable intree vsphere tests
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm

#26598 Adjust build test images for multi-arch support
  test/extended/builds/s2i_root.go
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/build-postcommit/sti.yaml
  test/extended/testdata/builds/build-timing/test-s2i-build.json
  test/extended/testdata/builds/statusfail-failedassemble.yaml
  test/extended/testdata/builds/statusfail-postcommithook.yaml
  test/extended/testdata/builds/statusfail-pushtoregistry.yaml
  test/extended/testdata/builds/test-build-cluster-config.yaml
  test/extended/testdata/builds/test-build-proxy.yaml
  test/extended/testdata/builds/test-build-revision.json
  test/extended/testdata/builds/test-nosrc-build.json
  test/extended/testdata/builds/test-s2i-build-quota.json
  test/extended/testdata/builds/test-s2i-build.json
  test/extended/testdata/builds/test-s2i-no-outputname.json
  test/extended/testdata/builds/valuefrom/failed-sti-build-value-from-config.yaml
  test/extended/testdata/builds/valuefrom/successful-sti-build-value-from-config.yaml
  test/extended/testdata/builds/volumes/docker-buildconfig.yaml
  test/extended/testdata/builds/volumes/s2i-buildconfig.yaml
  test/extended/testdata/templates/templateinstance_readiness.yaml
  test/extended/util/image/image.go
  test/extended/util/image/zz_generated.txt
  test/extended/util/nfs.go
Labels: approved, lgtm

#26641 Only known images used by tests: Fix for Hypershift
  cmd/openshift-tests/images.go
Labels: approved, lgtm

#26673 test/extended/etcd: cleanup OWNERS
  test/extended/etcd/OWNERS
Labels: approved, lgtm

#26648 Skip must-gather tests when running on Hypershift
  test/extended/cli/mustgather.go
Labels: approved, lgtm

#26678 Hypershift: Skip Prometheus should have important platform topology metrics
  test/extended/prometheus/prometheus.go
  test/extended/util/framework.go
Labels: approved, lgtm

#26677 Fix TestFIPS on Hypershift
  test/extended/security/fips.go
Labels: approved, lgtm

#26653 test/extended/util/disruption: Include tolerated percentage when failing
  test/extended/util/disruption/disruption.go
Labels: approved, lgtm

#26686 Revert "Alter junit test suite names for jobs with multiple junit xmls."
  cmd/openshift-tests/openshift-tests.go
  cmd/openshift-tests/upgrade.go
  pkg/test/ginkgo/cmd_runsuite.go
Labels: approved, lgtm

#26631 prometheus: adjust telemetry test for remote_write switch
  test/extended/prometheus/prometheus.go
Labels: approved, lgtm

#26691 test: avoid double slash in path
  test/extended/util/oauthserver/oauthserver.go
Labels: approved, lgtm

#26693 Add workaround for baremetal resources test
  test/extended/baremetal/hosts.go
Labels: approved, lgtm

#26682 fix disruption sampler
  e2echart/e2e-chart-template.html
  pkg/monitor/api.go
  pkg/monitor/backenddisruption/disruption_backend_sampler.go
  pkg/monitor/backenddisruption/disruption_backend_sampler_test.go
  pkg/monitor/backenddisruption/disruption_locator.go
  pkg/monitor/backenddisruption/simple_recorder.go
  pkg/monitor/backenddisruption/types.go
  pkg/monitor/disruption_known_backends.go
  pkg/monitor/monitor.go
  pkg/monitor/monitorapi/disruption.go
  pkg/monitor/monitorapi/types.go
  pkg/monitor/monitorapi/types_test.go
  pkg/monitor/sampler.go
  pkg/monitor/types.go
  pkg/synthetictests/apiserver.go
  pkg/test/ginkgo/status.go
  test/e2e/upgrade/alert/alert.go
  test/e2e/upgrade/service/service.go
  test/e2e/upgrade/upgrade.go
  test/extended/testdata/bindata.go
  test/extended/util/disruption/backend_sampler_tester.go
  test/extended/util/disruption/controlplane/controlplane.go
  test/extended/util/disruption/disruption.go
  test/extended/util/disruption/frontends/frontends.go
  test/extended/util/disruption/imageregistry/imageregistry.go
Labels: approved, lgtm

#26698 bug 2033379: [release-4.8] remove perma-failing prometheus upgrade invariant
  test/e2e/upgrade/alert/alert.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#26700 oc label will properly report removed label
  test/extended/cli/label.go
Labels: approved, lgtm

#26703 use standard disruption checker for load balancer
  pkg/monitor/backenddisruption/disruption_backend_sampler.go
  pkg/monitor/disruption_known_backends.go
  test/e2e/upgrade/service/service.go
  test/e2e/upgrade/upgrade.go
  test/extended/util/disruption/backend_sampler_tester.go
  test/extended/util/disruption/disruption.go
  test/extended/util/disruption/frontends/frontends.go
  test/extended/util/disruption/imageregistry/imageregistry.go
  test/extended/util/disruption/test_identification.go
Labels: approved, lgtm

#26709 extend tcp dial timeout and http response header timeout
  pkg/monitor/backenddisruption/disruption_backend_sampler.go
Labels: approved

#26705 Bug 2033341: tests: skip some tests for proxy
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#26692 Bug 2033740: Implement e2e-images-update label
  test/extended/util/image/OWNERS
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#26706 find disruption backends from the event intervals instead of a hardcoded list
  go.mod
  pkg/monitor/backenddisruption/disruption_locator.go
  pkg/monitor/disruption_known_backends.go
  pkg/monitor/monitorapi/disruption.go
  pkg/monitor/monitorapi/identification.go
  pkg/monitor/monitorapi/types.go
  pkg/monitor/write_job_run_data.go
  pkg/synthetictests/apiserver.go
  pkg/synthetictests/event_junits.go
  test/e2e/upgrade/service/service.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update

#26713 extend timeouts with 5s for each part
  pkg/monitor/backenddisruption/disruption_backend_sampler.go
  test/extended/util/disruption/controlplane/controlplane.go
  test/extended/util/disruption/frontends/frontends.go
  test/extended/util/disruption/imageregistry/imageregistry.go
Labels: approved

#26715 Bug 2033810: pkg: Buffer signals for abortCh
  pkg/monitor/cmd.go
  pkg/test/ginkgo/cmd_runsuite.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#26699 Bug 1983758: Add GCE back into the frontend disruption test
  test/extended/util/disruption/frontends/frontends.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#26712 Bug 2033751: Disable etcd test for 1.23
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#26720 Bug 2035128: disruption: use proxy from environment when measuring disruption
  pkg/monitor/backenddisruption/disruption_backend_sampler.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#26717 set allowed disruption based on historical p95 data
  pkg/synthetictests/allowedbackenddisruption/matches.go
  pkg/synthetictests/allowedbackenddisruption/matches_test.go
  pkg/synthetictests/allowedbackenddisruption/query_results.json
  pkg/synthetictests/allowedbackenddisruption/types.go
  test/e2e/upgrade/service/service.go
  test/extended/util/disruption/backend_sampler_tester.go
  test/extended/util/disruption/controlplane/controlplane.go
  test/extended/util/disruption/disruption.go
  test/extended/util/disruption/frontends/frontends.go
  test/extended/util/disruption/imageregistry/imageregistry.go
Labels: approved, lgtm, bugzilla/valid-bug

#26721 allow skipping a backend test
  test/extended/util/disruption/backend_sampler_tester.go
Labels: approved, lgtm, bugzilla/valid-bug
