Repository openshift/origin, pull requests merged in 2021-10, with the labels that each got.

#26388 Bug 1991980: Skipped non-standard openshift installed crd testing for ibmcloud
  test/extended/cli/explain.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#26476 test/extended/prometheus: Validate alerting rules
  test/extended/prometheus/prometheus.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
  test/extended/util/prometheus/helpers.go
Labels: approved, lgtm

#26487 stop adding individual serviceaccount namespace groups to SCC for e2e tests
  test/extended/util/test.go
Labels: approved, lgtm

#26491 Bug 2000754: vendor: e2e iperf2 change threshold to 10MBps
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3.go
  vendor/k8s.io/kubelet/pkg/apis/well_known_labels.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/filters/deprecatedapirequest/deprecated.go
  vendor/k8s.io/kubernetes/pkg/features/patch_kube_features.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_pods.go
  vendor/k8s.io/kubernetes/pkg/kubelet/pod_workers.go
  vendor/k8s.io/kubernetes/pkg/volume/csimigration/patch_adc_plugin_manager.go
  vendor/k8s.io/kubernetes/test/e2e/network/networking_perf.go
  vendor/k8s.io/kubernetes/test/e2e/storage/testsuites/volumemode.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, bugzilla/severity-medium

#26493 This would make CI for 4.10 in vSphere environment wee bit happier
  pkg/synthetictests/duplicated_events.go
  pkg/synthetictests/duplicated_events_test.go
Labels: approved, lgtm

#26501 Revert "stop adding individual serviceaccount namespace groups to SCC…
  test/extended/util/test.go
Labels: approved, lgtm

#26495 split the event should not repeat pathologically into e2e and core
  pkg/synthetictests/duplicated_events.go
Labels: approved, lgtm

#26494 record only known images test pass so we can get a percentage of passes
  cmd/openshift-tests/images.go
Labels: approved, lgtm

#26461 Bug 2003239: builds: skip private git repo tests outside of CI
  test/extended/builds/gitauth.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#26423 improve RestrictedEndpointsAdmission test
  test/extended/networking/endpoint_admission.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, vendor-update

#26506 suppress NetworkPodsCrashLooping while we work out whether its a bug …
  test/e2e/upgrade/alert/alert.go
Labels: approved, lgtm

#26507 Skipping test "[sig-devex][Feature:ImageEcosystem][perl][Slow] hot deploy for openshift perl image hot deploy should work" for ARM64
  test/extended/image_ecosystem/s2i_perl.go
Labels: approved, lgtm

#26498 Tolerate API downtime in upgrade disruption tests on single-node topologies
  test/extended/util/disruption/controlplane/controlplane.go
Labels: approved, lgtm
