Repository openshift/origin, pull requests merged in 2021-05, with the labels that each got.

#26127 test: Associate ClusterOperatorDown for machine-config with bug
  test/e2e/upgrade/alert/alert.go
Labels: approved, bugzilla/valid-bug, lgtm

#26130 test: Suppress the SCC failure when a limit is present
  test/extended/authorization/scc.go
Labels: approved, bugzilla/valid-bug, lgtm

#25931 Bug 1957295: All platform pods should have system-* or openshift-user-critical priority class
  test/extended/pods/priorityclasses.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#26062 Bug 1948606: test: replace dns test with known image
  test/extended/dns/dns.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#26109 Bug 1936974: Access git over https for tests
  examples/sample-app/github-webhook-example.json
  test/extended/builds/clone_git_protocol.go
  test/extended/builds/controllers.go
  test/extended/images/imagechange_buildtrigger.go
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/test-build-revision.json
  test/extended/testdata/builds/test-build.yaml
  test/extended/testdata/builds/webhook/generic/testdata/push-generic-envs.json
  test/extended/testdata/builds/webhook/generic/testdata/push-generic-envs.yaml
  test/extended/testdata/builds/webhook/generic/testdata/push-generic.json
  test/extended/testdata/builds/webhook/github/testdata/pushevent-not-master-branch.json
  test/extended/testdata/builds/webhook/github/testdata/pushevent.json
  test/extended/testdata/cmd/test/cmd/env.sh
  test/extended/testdata/cmd/test/cmd/testdata/test-bc.yaml
  test/extended/testdata/cmd/test/cmd/testdata/test-buildcli.json
  test/extended/testdata/long_names/fixture.json
  test/extended/testdata/run_policy/serial-latest-only-bc.yaml
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/proxy.go
  test/integration/testdata/test-buildcli-beta2.json
  test/integration/testdata/test-buildcli.json
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm, qe-approved

#26046 e2echart: Handle intervals that extend past the test range
  e2echart/e2e-chart-template.html
  test/extended/testdata/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm

#26133 fix test README link
  test/extended/README.md
Labels: approved, bugzilla/valid-bug, lgtm

#26059 Bug 1948233: Add openshift/network/third-party suite, for CNI plugin conformance
  cmd/openshift-tests/cni.go
  cmd/openshift-tests/e2e.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#26118 Bug 1957222: [test/oc_tag] Add internal option for registry info
  test/extended/images/oc_tag.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#26093 Bug 1957041: Update e2echart to include node roles info
  e2echart/e2e-chart-template.html
  pkg/monitor/event.go
  pkg/monitor/intervalcreation/node.go
  pkg/monitor/intervalcreation/node_test.go
  pkg/monitor/intervalcreation/testdata/node.json
  pkg/monitor/monitorapi/identification_node.go
  pkg/monitor/monitorapi/identification_node_test.go
  pkg/monitor/node.go
  pkg/monitor/node_test.go
  test/extended/testdata/bindata.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#26132 Bug 1957146: test/extended/router/idle: Only run on OVNKubernetes or OpenShiftSDN
  test/extended/router/idle.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#25950 Bug 1955089: Add IPv6 check to support observe parallel tests
  test/extended/cli/observe.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#26122 Bug 1957512: openshift-tests: fix a --provider --dry-run edge case
  cmd/openshift-tests/provider.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#26148 Bug 1958094: must-gather: check file name instead of whole path
  test/extended/cli/mustgather.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#26135 Bug 1957927: test/e2e/upgrade/upgrade.go: Bump upgrade ACK timeout to 4 minutes
  test/e2e/upgrade/upgrade.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#26151 Bug 1960171: Enable SNO check for image registry
  test/extended/single_node/topology.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, qe-approved

#26156 Bug 1959564: builds: skip /run verification tests
  test/extended/builds/run_fs_verification.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#26142 monitor: Allow samplers to be edge triggered by recording intervals
  e2echart/e2e-chart-template.html
  pkg/monitor/api.go
  pkg/monitor/event.go
  pkg/monitor/monitor.go
  pkg/monitor/monitorapi/types.go
  pkg/monitor/noop.go
  pkg/monitor/operator.go
  pkg/monitor/pod.go
  pkg/monitor/sampler.go
  pkg/monitor/sampler_test.go
  pkg/monitor/types.go
  pkg/synthetictests/apiserver.go
  pkg/test/ginkgo/cmd_runsuite.go
  test/e2e/upgrade/service/service.go
  test/extended/include.go
  test/extended/testdata/bindata.go
  test/extended/util/disruption/disruption.go
  test/extended/util/disruption/frontends/frontends.go
  test/extended/util/disruption/imageregistry/imageregistry.go
Labels: approved, bugzilla/valid-bug, lgtm

#26159 Wait longer in tests where namespace cleanup is slow
  test/extended/cli/admin.go
  test/extended/project/project.go
  test/extended/util/client.go
  test/extended/util/framework.go
Labels: approved, bugzilla/valid-bug, lgtm

#26131 Bug 1957131: test: Add the Cinder client to the test image
  images/tests/Dockerfile.rhel
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#26147 Bug 1947800: Router: Switch from networking v1beta1 to v1
  test/extended/testdata/bindata.go
  test/extended/testdata/router/ingress.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#26164 Bug 1959564: move verify run test from tools to cli image to avoid additional /run content
  test/extended/builds/run_fs_verification.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, qe-approved

#26165 Bug 1961201: DNS: Use endpointslice v1 for DNS dual-stack test
  test/extended/dns/dns.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#26170 Bug 1961582: Do not install python3-cinderclient on s390x
  images/tests/Dockerfile.rhel
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#26163 Bug 1961057: Add [Driver: gluster] tests into unsupported list
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#26174 Bug 1957295: test/extended/pods/priorityclasses: Improve error actionability
  test/extended/pods/priorityclasses.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#26168 Bug 1960780: Bump k8s to pick up v1beta1 PDB jig
  go.mod
  go.sum
  test/e2e/upgrade/service/service.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
  vendor/github.com/openshift/apiserver-library-go/pkg/labelselector/labelselector.go
  vendor/k8s.io/kubernetes/openshift-hack/e2e/annotate/rules.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/admission/customresourcevalidation/features/validate_features.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/admission/scheduler/nodeenv/admission.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/filters/deprecatedapirequest/apiaccess_count_controller.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/filters/deprecatedapirequest/deprecated.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/filters/deprecatedapirequest/request_counts.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/filters/deprecatedapirequest/update_func.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/filters/deprecatedapirequest/v1helpers/helpers.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/filters/deprecatedapirequest_filter.go
  vendor/k8s.io/kubernetes/pkg/kubelet/cm/container_manager_linux.go
  vendor/k8s.io/kubernetes/pkg/kubelet/cm/cpumanager/cpu_manager.go
  vendor/k8s.io/kubernetes/pkg/kubelet/cm/qos_container_manager_linux.go
  vendor/k8s.io/kubernetes/pkg/kubelet/config/apiserver.go
  vendor/k8s.io/kubernetes/pkg/kubelet/config/file.go
  vendor/k8s.io/kubernetes/pkg/kubelet/config/file_linux.go
  vendor/k8s.io/kubernetes/pkg/kubelet/eviction/eviction_manager.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_getters.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_volumes.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_container.go
  vendor/k8s.io/kubernetes/pkg/kubelet/managed/managed.go
  vendor/k8s.io/kubernetes/pkg/kubelet/stats/host_stats_provider.go
  vendor/k8s.io/kubernetes/pkg/volume/nfs/nfs.go
  vendor/k8s.io/kubernetes/pkg/volume/vsphere_volume/vsphere_volume_util.go
  vendor/k8s.io/kubernetes/test/e2e/framework/service/jig.go
  vendor/k8s.io/kubernetes/test/e2e/storage/testsuites/snapshottable.go
  vendor/k8s.io/kubernetes/test/e2e/upgrades/network/services.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, vendor-update

#26179 test: Tolerate no AWS disruption during control plane upgrade
  test/extended/util/disruption/controlplane/controlplane.go
Labels: approved, bugzilla/valid-bug, lgtm

#26181 Bug 1959564: narrow verify /run test to /run/secrets
  test/extended/builds/run_fs_verification.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#26180 Bug 1963115: narrow verify /run test to /run/secrets
  test/extended/builds/run_fs_verification.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#26152 test: Report FailedCreatePodSandBox for multus -> API as known issue (v2)
  pkg/synthetictests/networking.go
Labels: approved, bugzilla/valid-bug, lgtm

#26177 Bug 1963909: move verify run test from tools to cli image; narrow scope to /run/secrets
  test/extended/builds/run_fs_verification.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, qe-approved

#26183 Bug 1948012: test/extended/operators: Drop service-ca Upgradeable exception
  test/extended/operators/operators.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#26175 Bug 1929396: Revert part of PR #25406 - use ExternalTrafficPolicyCluster
  test/e2e/upgrade/service/service.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#26189 Bug 1948012: Revert "test/extended/operators: Drop service-ca Upgradeable exception"
  test/extended/operators/operators.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#26171 Bug 1961367: Add Cinder client to the test image
  images/tests/Dockerfile.rhel
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#26185 Bug 1960758: test/extended/cli/mustgather: Local-only getPluginOutputDir
  test/extended/cli/mustgather.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#26149 BUILD-250 pull in multi-arch friendly version of roots2i and simples2i, add simples2i to mirroring test infra
  test/extended/builds/s2i_root.go
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/build-postcommit/sti.yaml
  test/extended/testdata/builds/build-timing/test-s2i-build.json
  test/extended/testdata/builds/statusfail-failedassemble.yaml
  test/extended/testdata/builds/statusfail-postcommithook.yaml
  test/extended/testdata/builds/statusfail-pushtoregistry.yaml
  test/extended/testdata/builds/test-build-cluster-config.yaml
  test/extended/testdata/builds/test-build-proxy.yaml
  test/extended/testdata/builds/test-build-revision.json
  test/extended/testdata/builds/test-nosrc-build.json
  test/extended/testdata/builds/test-s2i-build-quota.json
  test/extended/testdata/builds/test-s2i-build.json
  test/extended/testdata/builds/test-s2i-no-outputname.json
  test/extended/testdata/builds/valuefrom/failed-sti-build-value-from-config.yaml
  test/extended/testdata/builds/valuefrom/successful-sti-build-value-from-config.yaml
  test/extended/testdata/templates/templateinstance_readiness.yaml
  test/extended/util/image/image.go
  test/extended/util/image/zz_generated.txt
Labels: approved, bugzilla/valid-bug, lgtm

#26184 Bug 1946479: Skip cluster quota test while bound token projected volume is being re-enabled
  test/extended/quota/clusterquota.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#26187 Bug 1964334: use bearer token to access prometheus /metrics endpoint
  test/extended/prometheus/prometheus.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#26192 Bug 1961582: Dockerfile.rhel: fix a bash typo
  images/tests/Dockerfile.rhel
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm
