Repository openshift/origin, pull requests merged in 2021-01, with the labels that each got.

#25783 test: Assess average series rather than max over the test window
  test/extended/prometheus/prometheus.go
Labels: approved, lgtm

#25784 test: Allow tests that check invariants over time to be constrained
  test/e2e/upgrade/alert/alert.go
  test/extended/apiserver/graceful_termination.go
  test/extended/prometheus/prometheus.go
  test/extended/prometheus/storage.go
  test/extended/util/conditions.go
  test/extended/util/prometheus/helpers.go
Labels: approved, lgtm

#25744 Bug 1904679: drop docker.io from image tests
  test/extended/images/info.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25780 Bug 1908217: server-side apply e2e: fix oauthclientauthorization race with KCM
  test/extended/apiserver/apply.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#25794 Add consoleplugins to list of console resource exceptions
  test/extended/authorization/rbac/groups_default_rules.go
Labels: approved, lgtm

#25786 Bug 1914343: Replacing centos with ubi in image-annotation test.
  test/extended/images/trigger/annotation.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#25799 Bug 1916419: broaden acceptance of scl sample s2i image usage messages
  test/extended/image_ecosystem/scl.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25789 test: Only consider rule evaluation failures in current window
  pkg/test/ginkgo/cmd_runsuite.go
  test/extended/prometheus/prometheus.go
  test/extended/util/conditions.go
Labels: approved, bugzilla/valid-bug, lgtm

#25802 Bug 1914894: make cmd tests more resilient
  test/extended/testdata/bindata.go
  test/extended/testdata/cmd/test/cmd/basicresources.sh
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25798 Bug 1915907: replace test/cmd/builds.sh direct/indirect docker.io refs with imagestream image refs
  test/extended/testdata/bindata.go
  test/extended/testdata/cmd/test/cmd/builds.sh
  test/extended/testdata/cmd/test/cmd/testdata/application-template-dockerbuild.json
  test/extended/testdata/cmd/test/cmd/testdata/test-buildcli.json
  test/extended/testdata/cmd/test/cmd/testdata/test-s2i-build.json
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25792 Bug 1896244: Bump(github.com/openshift/kubernetes)
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/server/filters/BUILD
  vendor/k8s.io/apiserver/pkg/util/flowcontrol/BUILD
  vendor/k8s.io/apiserver/pkg/util/flowcontrol/apf_controller.go
  vendor/k8s.io/apiserver/pkg/util/flowcontrol/apf_filter.go
  vendor/k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/queueset/queueset.go
  vendor/k8s.io/kubernetes/pkg/kubelet/OWNERS
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go
  vendor/k8s.io/kubernetes/pkg/kubelet/server/server.go
  vendor/k8s.io/kubernetes/pkg/volume/fc/attacher.go
  vendor/k8s.io/kubernetes/pkg/volume/fc/fc.go
  vendor/k8s.io/kubernetes/pkg/volume/fc/fc_util.go
  vendor/k8s.io/kubernetes/test/e2e/storage/persistent_volumes-local.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_loadbalancer.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_standard.go
  vendor/k8s.io/legacy-cloud-providers/openstack/openstack_volumes.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, vendor-update

#25787 test: Fail if nodes go unready during a normal parallel run
  test/extended/machines/cluster.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, bugzilla/valid-bug, lgtm

#25807 Bug 1914894: make tests more resilient
  test/extended/testdata/bindata.go
  test/extended/testdata/cmd/test/cmd/basicresources.sh
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25803 Bug 1896188: wait for RC presence before starting debug session
  test/extended/cli/debug.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25586 Bug 1852289: Add libvirt to the list of unsupported platforms for LB service
  test/e2e/upgrade/service/service.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25809 bug 1915945: UPSTREAM: 96990: Increase preemption timeout from 1 minute to 2 minutes
  go.mod
  go.sum
  vendor/k8s.io/kubernetes/pkg/kubelet/BUILD
  vendor/k8s.io/kubernetes/pkg/kubelet/container/runtime.go
  vendor/k8s.io/kubernetes/pkg/kubelet/container/testing/fake_runtime.go
  vendor/k8s.io/kubernetes/pkg/kubelet/container/testing/runtime_mock.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_node_status.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_pods.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_container.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_gc.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_sandbox.go
  vendor/k8s.io/kubernetes/pkg/kubelet/pod_sandbox_deleter.go
  vendor/k8s.io/kubernetes/pkg/volume/BUILD
  vendor/k8s.io/kubernetes/pkg/volume/plugins.go
  vendor/k8s.io/kubernetes/pkg/volume/util/volumepathhandler/volume_path_handler_linux.go
  vendor/k8s.io/kubernetes/test/e2e/scheduling/predicates.go
  vendor/k8s.io/kubernetes/test/e2e/scheduling/preemption.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, vendor-update

#25811 tests: Synthetic tests moved up and out of test infra
  cmd/openshift-tests/e2e.go
  cmd/openshift-tests/images.go
  cmd/openshift-tests/openshift-tests.go
  pkg/test/ginkgo/cmd_runsuite.go
  pkg/test/ginkgo/synthentic_tests.go
  pkg/test/ginkgo/test.go
Labels: approved, bugzilla/valid-bug, lgtm

#25813 test/ginkgo: When --count is used tests all fail together
  pkg/test/ginkgo/cmd_runsuite.go
  pkg/test/ginkgo/status.go
Labels: approved, bugzilla/valid-bug, lgtm

#25791 Bug 1907939: Nodes goes into NotReady state (VMware)
  glide.lock
  glide.yaml
  vendor/github.com/openshift/api/config/v1/types_operatorhub.go
  vendor/github.com/openshift/apiserver-library-go/Makefile
  vendor/github.com/openshift/apiserver-library-go/go.mod
  vendor/github.com/openshift/apiserver-library-go/go.sum
  vendor/github.com/openshift/apiserver-library-go/pkg/dependencymagnet/doc.go
  vendor/github.com/openshift/library-go/go.mod
  vendor/github.com/openshift/library-go/go.sum
  vendor/github.com/openshift/library-go/pkg/apiserver/httprequest/httprequest.go
  vendor/github.com/openshift/library-go/pkg/config/client/client_config.go
  vendor/github.com/openshift/library-go/pkg/network/dialer.go
  vendor/github.com/openshift/library-go/pkg/network/dialer_linux.go
  vendor/github.com/openshift/library-go/pkg/network/dialer_others.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/manifests/installer-pod.yaml
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/manifests/pruner-pod.yaml
  vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/transport/cache.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm, vendor-update

#25777 Bug 1912566: UPSTREAM: 97206: clean up executing request on panic
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/util/flowcontrol/apf_filter.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/queueset/queueset.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/queueset/queueset_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, kind/bug, lgtm, vendor-update

#25819 add additional settling debug information
  pkg/test/ginkgo/cmd_runsuite.go
  test/e2e/upgrade/upgrade.go
  test/extended/util/operator/settle.go
  test/extended/util/operator/settle_test.go
Labels: approved, lgtm, vendor-update

#25823 Bug 1896188: bump build timeout to 10m and deploy to 2m in oc debug
  test/extended/cli/debug.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25820 bug 1870342: UPSTREAM: 94684: e2e: Pod should avoid nodes that have avoidPod annotation: clean remaining pods
  go.mod
  go.sum
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_container.go
  vendor/k8s.io/kubernetes/test/e2e/scheduling/predicates.go
  vendor/k8s.io/kubernetes/test/e2e/scheduling/priorities.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, vendor-update

#25785 Bug 1913751: Add openshift/network/third-party suite, for CNI plugin conformance
  cmd/openshift-tests/cni.go
  cmd/openshift-tests/e2e.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25810 Bug 1916897: add test to verify build /run fs contents
  test/extended/builds/run_fs_verification.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25746 Bug 1904684: get rid of docker.io in tests
  examples/image-streams/image-streams-centos7.json
  examples/image-streams/image-streams-rhel7.json
  test/extended/cli/debug.go
  test/extended/testdata/bindata.go
  test/extended/testdata/cmd/test/cmd/edit.sh
  test/extended/testdata/cmd/test/cmd/images.sh
  test/extended/testdata/cmd/test/cmd/newapp.sh
  test/extended/testdata/cmd/test/cmd/quota.sh
  test/extended/testdata/cmd/test/cmd/set-image.sh
  test/extended/testdata/cmd/test/cmd/testdata/image-streams/image-streams-centos7.json
  test/extended/testdata/cmd/test/cmd/testdata/modified-ruby-imagestream.json
  test/extended/testdata/cmd/test/cmd/testdata/new-app/imagestream-ref.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25824 Bug 1879208: fixes a data race in SerializeObject function
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, vendor-update

#25827 Bug 1921088: don't wait for PV removal in volumes.sh
  test/extended/testdata/bindata.go
  test/extended/testdata/cmd/test/cmd/volumes.sh
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#25834 test: etcd leader changes should be measured over the test, not the run
  test/extended/etcd/leader_changes.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#25826 Bug 1914894: get stdout only when invoking oc process
  test/extended/cli/admin.go
  test/extended/util/client.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25838 [release-4.6] Bug 1920626: add test to verify build /run fs contents
  test/extended/builds/run_fs_verification.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, bugzilla/valid-bug, lgtm

#25839 Bug 1904684: fix missing bits in images.sh tests
  test/extended/testdata/bindata.go
  test/extended/testdata/cmd/test/cmd/builds.sh
  test/extended/testdata/cmd/test/cmd/images.sh
  test/extended/testdata/cmd/test/cmd/printer.sh
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25841 test/cmd/images.sh: create imagestreamtag --from is a tag
  test/extended/testdata/bindata.go
  test/extended/testdata/cmd/test/cmd/images.sh
Labels: approved, lgtm
