Repository openshift/origin, pull requests merged in 2021-02, with the labels that each got.

#25846 test: Use wildfly 20 since 19 can no longer be accessed at quay
  test/extended/testdata/bindata.go
  test/extended/testdata/cmd/test/cmd/images.sh
Labels: approved, lgtm

#25835 Bug 1921857: Router should require multiple 200 responses (hit multiple instances of the router) before continuing the test
  test/extended/router/scoped.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25844 Bug 1900989: idle.sh: Drop endpoints mocks from idle tests
  test/extended/testdata/bindata.go
  test/extended/testdata/cmd/test/cmd/idle.sh
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#25837 Bug 1923737: Add `--fail-fast` to the tests command
  cmd/openshift-tests/e2e.go
  cmd/openshift-tests/images.go
  cmd/openshift-tests/openshift-tests.go
  cmd/openshift-tests/provider.go
  cmd/openshift-tests/upgrade.go
  examples/examples_test.go
  go.mod
  pkg/monitor/resourcewatch/controller/configmonitor/crd_controller.go
  pkg/monitor/resourcewatch/storage/git_store.go
  pkg/test/ginkgo/cmd_runsuite.go
  pkg/test/ginkgo/queue.go
  pkg/test/ginkgo/status.go
  pkg/test/ginkgo/test.go
  test/extended/apiserver/graceful_termination.go
  test/extended/authorization/scc.go
  test/extended/etcd/leader_changes.go
  test/extended/images/oc_copy.go
  test/extended/machines/cluster.go
  test/extended/pods/systemd.go
  test/extended/prometheus/prometheus.go
  test/extended/prometheus/storage.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
  test/extended/util/client.go
  test/extended/util/framework.go
  test/extended/util/oauthserver/tokencmd/basicauth.go
  test/extended/util/oauthserver/tokencmd/multi.go
  test/extended/util/oauthserver/tokencmd/negotiate.go
  test/extended/util/oauthserver/tokencmd/request_token.go
  test/extended/util/test.go
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/CONTRIBUTING.md
  vendor/k8s.io/klog/LICENSE
  vendor/k8s.io/klog/OWNERS
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/RELEASE.md
  vendor/k8s.io/klog/SECURITY_CONTACTS
  vendor/k8s.io/klog/code-of-conduct.md
  vendor/k8s.io/klog/go.mod
  vendor/k8s.io/klog/go.sum
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, vendor-update

#25845 Bug 1922991: allow OKD /run contents for build fs test
  test/extended/builds/run_fs_verification.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#25849 test: Upgrade should prereq early tests
  cmd/openshift-tests/upgrade.go
Labels: approved, bugzilla/valid-bug, lgtm

#25850 Bug 1900989: test/extended/router: add idle/unidle e2e test
  test/extended/router/idle.go
  test/extended/testdata/bindata.go
  test/extended/testdata/router/router-idle.yaml
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#25800 Bug 1916660: UPSTREAM: 97916: kube-aggregator: fix apiservice availability gauge
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/controllers/status/BUILD
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/controllers/status/available_controller.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/controllers/status/available_controller_test.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/controllers/status/metrics.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/controllers/status/metrics_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, vendor-update

#25751 Bug 1894918: Panic output due to timeouts in kube-apiserver
  vendor/k8s.io/kubernetes/cmd/cloud-controller-manager/app/options/options_test.go
  vendor/k8s.io/kubernetes/cmd/controller-manager/app/serve.go
  vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/options/options_test.go
  vendor/k8s.io/kubernetes/cmd/kube-scheduler/app/server.go
  vendor/k8s.io/kubernetes/pkg/kubeapiserver/server/insecure_handler.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/config.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/filters/BUILD
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/filters/timeout.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/filters/timeout_test.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/filters/wrap.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/options/authentication.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/options/authorization.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm, vendor-update

#25860 tests: Upgrade tests should always include success output
  cmd/openshift-tests/upgrade.go
Labels: approved, bugzilla/valid-bug, lgtm

#25694 [release-4.5] Bug 1887311: UPSTREAM: 94712: [credentialprovider] avoid potential secret leaking while reading .dockercfg
  vendor/k8s.io/kubernetes/pkg/credentialprovider/config.go
  vendor/k8s.io/kubernetes/pkg/credentialprovider/config_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm, vendor-update

#25854 Bug 1924128: Allow RHE7 /run contents for build fs test
  test/extended/builds/run_fs_verification.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#25862 Bug 1915912: Fix CSI snapshotter image version
  test/extended/util/image/image.go
  test/extended/util/image/zz_generated.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#25859 tests: Double up the network stress test pressure
  cmd/openshift-tests/e2e.go
  test/extended/oauth/server_headers.go
Labels: approved, bugzilla/valid-bug, lgtm

#25848 Bug 1896558: bump(openshift/kubernetes): fix flaking multi-AZ test
  go.mod
  go.sum
  test/extended/util/annotate/generated/zz_generated.annotations.go
  vendor/k8s.io/kubernetes/test/e2e/apimachinery/BUILD
  vendor/k8s.io/kubernetes/test/e2e/apimachinery/request_timeout.go
  vendor/k8s.io/kubernetes/test/e2e/scheduling/ubernetes_lite.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, vendor-update

#25869 Upgrade openshift/api to 670ac3fc997c
  go.mod
  go.sum
  vendor/github.com/openshift/api/Dockerfile.build
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_scheduler.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/console/install.go
  vendor/github.com/openshift/api/console/v1alpha1/0000_10_consoleplugin.crd.yaml
  vendor/github.com/openshift/api/console/v1alpha1/doc.go
  vendor/github.com/openshift/api/console/v1alpha1/register.go
  vendor/github.com/openshift/api/console/v1alpha1/types.go
  vendor/github.com/openshift/api/console/v1alpha1/types_console_plugin.go
  vendor/github.com/openshift/api/console/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/console/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_12_etcd-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_20_kube-apiserver-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-controller-manager-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-scheduler-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_40_cloud-credential-operator_00_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_console-operator.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/types_cloudcredential.go
  vendor/github.com/openshift/api/operator/v1/types_console.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1alpha1/0000_10_config-operator_01_imagecontentsourcepolicy.crd.yaml
  vendor/github.com/openshift/api/operator/v1alpha1/types_image_content_source_policy.go
  vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/project/v1/generated.proto
  vendor/github.com/openshift/api/project/v1/types.go
  vendor/github.com/openshift/api/project/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update

#25723 Bug 1886160: Add test of documented backup/restore procedure
  test/extended/dr/backup_restore.go
  test/extended/dr/common.go
  test/extended/dr/force_redeploy.go
  test/extended/dr/quorum_restore.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#25870 Bug 1924953: Allow prometheus state clear to pass etcd leader change test
  test/extended/etcd/leader_changes.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25863 Change registry.svc.ci.openshift.org to registry.ci.openshift.org
  Makefile
  test/extended/builds/s2i_root.go
  test/extended/util/image/image.go
  test/extended/util/image/zz_generated.txt
Labels: approved, lgtm

#25812 Test that new single replica topology API is taken into account
  test/extended/include.go
  test/extended/single_node/topology.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, vendor-update

#25877 Bug 1926977: adjust route host for redis/nodejs to accomodate new apiserver restrictions
  test/extended/image_ecosystem/OWNERS
  test/extended/image_ecosystem/sample_repos.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25879 e2e: test OAuth API connections in the tests by that name
  test/extended/util/disruption/controlplane/controlplane.go
Labels: approved, lgtm

#25858 [release-4.6] Bug 1900991: test/extended/router: add idle/unidle e2e test
  test/extended/router/idle.go
  test/extended/testdata/bindata.go
  test/extended/testdata/router/router-idle.yaml
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#25881 tolerate permissions for allowing in-cluster CA bundles to all authenticated
  test/extended/authorization/rbac/groups_default_rules.go
Labels: approved, lgtm

#25882 test: Calculate leader elections over individual metrics
  test/extended/etcd/leader_changes.go
Labels: approved, bugzilla/valid-bug, lgtm

#25883 test: Calculate leader elections over individual metrics
  test/extended/etcd/leader_changes.go
Labels: approved, bugzilla/valid-bug, group-lead-approved, lgtm

#25874 Bug 1926146: test/extended/router/idle: address flakes/failures seen in CI
  test/extended/router/idle.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25876 Bug 1925493: Bump (openshift/kubernetes) with updated tests
  go.mod
  go.sum
  test/extended/util/annotate/generated/zz_generated.annotations.go
  vendor/k8s.io/apiserver/pkg/audit/BUILD
  vendor/k8s.io/apiserver/pkg/endpoints/filters/BUILD
  vendor/k8s.io/apiserver/pkg/endpoints/filters/request_deadline.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/create.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/delete.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/patch.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/update.go
  vendor/k8s.io/apiserver/pkg/server/BUILD
  vendor/k8s.io/apiserver/pkg/server/config.go
  vendor/k8s.io/apiserver/pkg/server/filters/timeout.go
  vendor/k8s.io/kubernetes/openshift-hack/e2e/annotate/rules.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, vendor-update

#25825 Bug 1902054: Update multicast test image for use in release-4.6
  test/extended/networking/multicast.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#25828 Bug 1899941: Add e2e test for liveness override annotation
  test/extended/pods/liveness_override.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, bugzilla/valid-bug, lgtm

#25906 test: SCC early failures (before suite) flake until fixed
  test/extended/authorization/scc.go
Labels: approved, lgtm

#25901 test: Synthetic failures were not failing the job
  pkg/test/ginkgo/synthentic_tests.go
Labels: approved, lgtm

#25903 test: AWS and Azure should tolerate no API disruption
  test/extended/util/disruption/controlplane/controlplane.go
Labels: approved, lgtm

#25896 test: Ensure nodes stay ready during upgrades after reboot
  cmd/openshift-tests/e2e.go
  cmd/openshift-tests/upgrade.go
  pkg/monitor/node.go
  test/e2e/upgrade/upgrade.go
Labels: approved, lgtm

#25909 Bug 1921720: fix sig-cli flakes
  test/extended/cli/admin.go
  test/extended/cli/observe.go
  test/extended/cli/rsh.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25795 [release-3.11] Bug 1760807: Revert #25463 regression in pod affinity check
  vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/priorities/interpod_affinity.go
  vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/priorities/interpod_affinity_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, cherry-pick-approved, lgtm, priority/important-soon

#25902 Added openshift-image-registry to single node topology test allowedToFail list
  test/extended/single_node/topology.go
Labels: approved, lgtm

#25900 Bug 1929110: test: add vsphere to unsupported platforms for LB service
  test/e2e/upgrade/service/service.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#25911 put the SCC test back
  test/extended/authorization/scc.go
Labels: approved, lgtm

#25921 monitor: Improve cluster operator transition message
  pkg/monitor/operator.go
Labels: approved, lgtm

#25923 Bug 1932618: Don't allow alerts to fire during a test run
  test/extended/prometheus/prometheus.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#25922 test: Detect when the master pool is still updating after upgrade
  test/e2e/upgrade/upgrade.go
  test/extended/dr/common.go
Labels: approved, lgtm

#25899 [release-4.5] Bug 1928978: UPSTREAM: 89885: SQUASH: Fix cinder crash
  vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/openstack/openstack.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, vendor-update

#25919 test: Prevent all SCC failures from being allowed during normal e2e
  test/extended/authorization/scc.go
Labels: approved, lgtm

#25627 BUG 1891106: UPSTREAM: 95259: allocate service-account flowschema to global-default
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/apis/flowcontrol/bootstrap/default.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, kind/bug, lgtm, vendor-update

#25925 test: Exclude AggregatedAPIDown alert caused by test cleanup
  test/extended/prometheus/prometheus.go
Labels: approved, lgtm
