Repository openshift/origin, pull requests merged in 2021-04, with the labels that each got.

#25993 tests/extended: Add a basic sanity test for CoreOS bootimages
  test/extended/coreos/coreos.go
  test/extended/include.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#26039 Update test rules to bump k8s
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm

#26040 Change BindNetwork of outhserver to tcp to support IPv6
  test/extended/util/oauthserver/oauthserver.go
Labels: approved, lgtm

#25946 Add list of canary tests to openshift-tests image
  cmd/openshift-tests/e2e.go
  cmd/openshift-tests/minimal.go
Labels: approved, lgtm

#26037 require operator availability and non-degraded for upgrades
  pkg/synthetictests/event_junits.go
  pkg/synthetictests/operators.go
Labels: approved, lgtm

#26017 test: skip checking nodejs 10 and perl 5.26
  test/extended/image_ecosystem/s2i_images.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#25954 NE-544: DNS: Add new dual-stack service DNS test
  test/extended/dns/dns.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#26009 fix the rest of parallel tests working with old token format
  test/extended/authorization/scopes.go
  test/extended/cli/mustgather.go
  test/extended/oauth/client_secret.go
  test/extended/oauth/token.go
  test/extended/project/project.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#26034 visualize monitor event intervals
  Makefile
  e2echart/e2e-chart-template.html
  pkg/monitor/api.go
  pkg/monitor/e2etest.go
  pkg/monitor/intervalcreation/e2etest.go
  pkg/monitor/intervalcreation/operator.go
  pkg/monitor/intervalcreation/operator_test.go
  pkg/monitor/monitor.go
  pkg/monitor/monitorapi/identification_operator.go
  pkg/monitor/monitorapi/identification_operator_test.go
  pkg/monitor/operator_test.go
  pkg/monitor/serialization/serialize.go
  pkg/monitor/types.go
  pkg/synthetictests/operators.go
  pkg/test/ginkgo/cmd_runsuite.go
  test/extended/testdata/bindata.go
Labels: approved, lgtm, vendor-update

#26043 Baremetal platform tests refinement
  test/extended/baremetal/hosts.go
Labels: approved, lgtm

#26019 test: provide a way to skip tests on disconnected clusters
  cmd/openshift-tests/provider.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
  test/extended/util/cloud/cloud.go
Labels: approved, lgtm

#26053 Bug 1945398: e2e requestheader: properly wait for a new oauth-server rollout
  test/extended/oauth/requestheaders.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#25897 Bug 1947806: test/extended/router: enable http/2, gRPC router tests
  test/extended/router/certgen/certgen.go
  test/extended/router/grpc-interop.go
  test/extended/router/grpc-interop/Makefile
  test/extended/router/grpc-interop/README
  test/extended/router/grpc-interop/cluster/Makefile
  test/extended/router/grpc-interop/cluster/client/client.go
  test/extended/router/grpc-interop/cluster/go.mod
  test/extended/router/grpc-interop/cluster/go.sum
  test/extended/router/grpc-interop/cluster/server/server.go
  test/extended/router/grpc-interop/test-fixture-gen/gen.go
  test/extended/router/h2spec.go
  test/extended/router/http2.go
  test/extended/router/http2/Makefile
  test/extended/router/http2/cluster/go.mod
  test/extended/router/http2/cluster/go.sum
  test/extended/router/http2/cluster/server/server.go
  test/extended/router/http2/doc.go
  test/extended/router/http2/test-fixture-gen/gen.go
  test/extended/router/idle.go
  test/extended/router/shard/shard.go
  test/extended/testdata/bindata.go
  test/extended/testdata/router/router-grpc-interop-routes.yaml
  test/extended/testdata/router/router-grpc-interop.yaml
  test/extended/testdata/router/router-http2-routes.yaml
  test/extended/testdata/router/router-http2.yaml
  test/extended/testdata/router/router-shard.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#26058 update list of canary tests
  cmd/openshift-tests/minimal.go
Labels: approved, lgtm

#26061 Bug 1948629: upgrades: add "none" / "minimal" test suites to skip disruption tests
  cmd/openshift-tests/upgrade.go
  test/e2e/upgrade/upgrade.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#26044 Bug 1947806: test/extended/router: Re-enable h2spec tests
  test/extended/router/h2spec.go
  test/extended/testdata/bindata.go
  test/extended/testdata/router/router-h2spec-routes.yaml
  test/extended/testdata/router/router-h2spec.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#26030 Bug 1948021: test/extended/operators: Require Upgradeable=True or unset for "start all core operators"
  test/extended/operators/operators.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#26068 Bug 1949042: test/extended/router: skip h2 related tests on OpenStack
  test/extended/router/grpc-interop.go
  test/extended/router/h2spec.go
  test/extended/router/http2.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#26027 Bug 1948634: upgrade: allow upgrades without version change
  test/e2e/upgrade/upgrade.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#26060 Bug 1949050: Fix oauthaccesstoken test to use the new required name
  test/extended/testdata/bindata.go
  test/extended/testdata/cmd/test/cmd/basicresources.sh
  test/extended/testdata/cmd/test/cmd/testdata/oauthaccesstoken.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#26066 test: Expose node changes as intervals
  e2echart/e2e-chart-template.html
  pkg/monitor/api.go
  pkg/monitor/e2etest.go
  pkg/monitor/event.go
  pkg/monitor/intervalcreation/e2etest.go
  pkg/monitor/intervalcreation/node.go
  pkg/monitor/intervalcreation/node_test.go
  pkg/monitor/intervalcreation/operator.go
  pkg/monitor/intervalcreation/testdata/node.json
  pkg/monitor/monitor.go
  pkg/monitor/monitor_test.go
  pkg/monitor/monitorapi/identification.go
  pkg/monitor/monitorapi/types.go
  pkg/monitor/node.go
  pkg/monitor/noop.go
  pkg/monitor/sampler_test.go
  pkg/monitor/serialization/serialize.go
  pkg/monitor/types.go
  pkg/synthetictests/apiserver.go
  pkg/synthetictests/kubelet.go
  pkg/synthetictests/networking.go
  pkg/synthetictests/operators.go
  pkg/test/ginkgo/cmd_runsuite.go
  pkg/test/ginkgo/synthentic_tests.go
  test/extended/testdata/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm

#26048 Bug 1938465: test/extended/operators: remove CPU limits exception for Thanos querier
  test/extended/operators/resources.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#26078 Set a minimum width to e2e-intervals chart by default
  Makefile
  e2echart/e2e-chart-template.html
  test/extended/testdata/bindata.go
Labels: approved

#26052 SNO topology: the oauth-server should only have a single replica now
  test/extended/single_node/topology.go
Labels: approved, bugzilla/valid-bug, lgtm

#26081 Bug 1947809: upgrade: register none suite
  cmd/openshift-tests/upgrade.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#26083 Bug 1949978: test/extended/router: h2spec increase timeout and retry tests
  test/extended/router/h2spec.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#26086 Bug 1949978: test/extended/router: skip h2spec on proxy jobs
  test/extended/router/grpc-interop.go
  test/extended/router/h2spec.go
  test/extended/router/http2.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#26085 Bug 1938492: test/extended/operators/resources: Marketplace Job sets requests
  test/extended/operators/resources.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#26082 Bug 1949928: Remove references to EOL ImageStream Tags
  cmd/openshift-tests/minimal.go
  examples/image-streams/image-streams-centos7.json
  examples/quickstarts/dancer-mysql-persistent.json
  examples/quickstarts/dancer-mysql.json
  examples/quickstarts/rails-postgresql-persistent.json
  examples/quickstarts/rails-postgresql.json
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/pullsecret/linked-nodejs-bc.yaml
  test/extended/testdata/cluster/quickstarts/dancer-mysql.json
  test/extended/testdata/cluster/quickstarts/rails-postgresql.json
  test/extended/testdata/cmd/test/cmd/images.sh
  test/extended/testdata/cmd/test/cmd/newapp.sh
  test/extended/testdata/cmd/test/cmd/testdata/image-streams/image-streams-centos7.json
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#26063 Remove non conformance test from the minimal suite
  cmd/openshift-tests/e2e.go
Labels: approved, bugzilla/valid-bug, lgtm

#25778 Bug 1895053: Verify builds can mount proxy trustedCA
  test/extended/builds/proxy.go
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/test-build-proxy.yaml
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, qe-approved

#26080 ensure that sampled conditions always have a range of time in their event interval
  pkg/monitor/monitor.go
Labels: approved, bugzilla/valid-bug, lgtm

#26084 monitor: Clamp intervals to the test duration
  cmd/openshift-tests/images.go
  pkg/monitor/cmd.go
  pkg/monitor/e2etest.go
  pkg/monitor/intervalcreation/e2etest.go
  pkg/monitor/intervalcreation/node.go
  pkg/monitor/intervalcreation/node_test.go
  pkg/monitor/intervalcreation/operator.go
  pkg/monitor/intervalcreation/operator_test.go
  pkg/monitor/monitor.go
  pkg/monitor/monitor_test.go
  pkg/monitor/monitorapi/types.go
  pkg/monitor/sampler_test.go
  pkg/monitor/serialization/serialize.go
  pkg/monitor/types.go
  pkg/synthetictests/apiserver.go
  pkg/synthetictests/event_junits.go
  pkg/synthetictests/kubelet.go
  pkg/synthetictests/networking.go
  pkg/synthetictests/operators.go
  pkg/test/ginkgo/cmd_runsuite.go
  pkg/test/ginkgo/synthentic_tests.go
  test/e2e/upgrade/service/service.go
  test/extended/util/disruption/controlplane/controlplane.go
  test/extended/util/disruption/disruption.go
  test/extended/util/disruption/frontends/frontends.go
  test/extended/util/disruption/imageregistry/imageregistry.go
Labels: approved

#26074 monitor: Add pull time to pulled events for analysis
  pkg/monitor/event.go
Labels: approved, bugzilla/valid-bug

#26087 Bug 1938467: test/extended/operators/resources: Autoscaler sets requests
  test/extended/operators/resources.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#26089 Bug 1949978: test/extended/router: skip http2, grpc-interop and h2spec on AWS
  test/extended/router/http2.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#26015 Bug 1949096: Restore private git clone tests
  test/extended/builds/gitauth.go
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/test-auth-build.yaml
  test/extended/testdata/test-gitserver.yaml
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm, qe-approved

#26091 Bug 1848408: fix validation issues in test files
  test/extended/builds/run_fs_verification.go
  test/extended/testdata/bindata.go
  test/extended/testdata/cmd/test/cmd/basicresources.sh
  test/extended/testdata/cmd/test/cmd/testdata/application-template-dockerbuild.json
  test/extended/testdata/cmd/test/cmd/testdata/statefulset.yaml
  test/extended/testdata/cmd/test/cmd/testdata/templates/template_required_params.yaml
  test/extended/testdata/cmd/test/cmd/testdata/test-replication-controller.yaml
  test/extended/testdata/cmd/test/cmd/testdata/test-stream.yaml
  test/extended/testdata/roles/policy-roles.yaml
  test/extended/testdata/stable-busybox.yaml
  test/extended/testdata/test-replication-controller.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#26096 Bug 1949050: fix images.sh script
  test/extended/testdata/bindata.go
  test/extended/testdata/cmd/test/cmd/images.sh
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#26092 monitor: mark the starting point for clusteroperators
  pkg/monitor/operator.go
Labels: approved, bugzilla/valid-bug, lgtm

#26069 [release-4.6] Bug 1941577: test/extended/router/idle: skip test on virt platforms
  test/extended/router/idle.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#26099 bug 1951705: allow HighOverallControlPlaneCPU during e2e runs
  test/extended/prometheus/prometheus.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#26088 Bug 1952045: request mirroring for nfs-server image used in jenkins-e2e tests
  test/extended/util/image/image.go
  test/extended/util/image/zz_generated.txt
  test/extended/util/nfs.go
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#26045 bug 1952473: Dump pod displacement during upgrade
  pkg/test/ginkgo/cmd_runsuite.go
  pkg/test/ginkgo/podanalysis.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#25818 Bug 1945091: Refactor openshift-tests a bit, add more network-test-autodetecting support
  cmd/openshift-tests/e2e.go
  cmd/openshift-tests/openshift-tests.go
  cmd/openshift-tests/provider.go
  cmd/openshift-tests/provider_test.go
  go.mod
  test/extended/util/cloud/cloud.go
  test/extended/util/cluster/cluster.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, vendor-update

#26102 Bug 1949589: allow high CPU alerts to be firing and pending
  test/extended/prometheus/prometheus.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#26103 test: Mark known alert failure for auth operator to bug
  test/extended/prometheus/prometheus.go
Labels: approved, lgtm

#26107 test: Allow KubeAPIErrorBudgetBurn on GCP platforms only
  test/e2e/upgrade/alert/alert.go
  test/extended/prometheus/prometheus.go
  test/extended/util/disruption/controlplane/controlplane.go
  test/extended/util/prometheus/helpers.go
Labels: approved

#26106 Bug 1938466: test/extended/operators/resources: Packageserver already sets requests
  test/extended/operators/resources.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#26097 monitor: Move "crashlooping pods" test to an invariant
  pkg/monitor/pod.go
  pkg/synthetictests/event_junits.go
  pkg/synthetictests/kubelet.go
  test/extended/operators/cluster.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, bugzilla/valid-bug, lgtm

#26105 Bug 1953729: test/extended/router: Fix-up Unidling test
  test/extended/router/idle.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#26113 Bug 1949991: Ignore Catalog update pods in openshift/conformance/parallel
  test/extended/operators/cluster.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#26094 Bug 1951663: Fix volume loop bugs
  vendor/k8s.io/kubernetes/pkg/volume/util/operationexecutor/operation_executor.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm, vendor-update

#26116 test: Exclude terminal pods from ForceDeletion
  pkg/monitor/pod.go
  pkg/synthetictests/kubelet.go
Labels: approved, bugzilla/valid-bug, lgtm

#26114 test: Wait for service account token
  test/extended/images/oc_tag.go
Labels: approved, bugzilla/valid-bug, lgtm

#26115 test: Report FailedCreatePodSandBox for multus -> API as known issue
  pkg/synthetictests/networking.go
Labels: approved, bugzilla/valid-bug, lgtm

#26121 Bug 1955669: flake testKubeletToAPIServerGracefulTermination
  cmd/openshift-tests/e2e.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm
