Repository openshift/origin, pull requests merged in 2022-09, with the labels that each got.

#27393 Update etcd tests with k8s data
  test/extended/etcd/etcd_storage_path.go
Labels: approved, lgtm

#27396 Update etcd tests with k8s 1.25 data
  test/extended/etcd/etcd_storage_path.go
Labels: approved, lgtm

#27388 Fix upgrade dry-run.
  cmd/openshift-tests/upgrade.go
Labels: approved, lgtm

#27270 Bug 2100091: Ignore FailedCreatePodSandBox events for garbage collector tests
  pkg/synthetictests/networking.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#27381 Remove flake for 40% Secret/ConfigMap growth test.
  pkg/synthetictests/resource_growth.go
Labels: approved, lgtm

#27394 skip route-controller-manager scaling events in build testsuite
  pkg/synthetictests/duplicated_events.go
Labels: approved, lgtm

#27406 Automatically skip tests with apigroups which are not served
  pkg/test/ginkgo/cmd_runsuite.go
  pkg/test/ginkgo/group_filter.go
  pkg/test/ginkgo/status.go
  pkg/test/ginkgo/test.go
Labels: approved, lgtm

#27418 OCPBUGS-587: Temporarily flake FailedToUpdateEndpointSlices
  pkg/synthetictests/duplicated_events_special.go
  pkg/synthetictests/duplicated_events_special_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug

#27384 Address exceeded maximum resolution of 11,000 points per timeseries
  pkg/monitor/alerts.go
Labels: approved, lgtm

#27419 OCPBUGS-1237: Fix s2i ruby test that relys on rack
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/s2i-environment-build-app/Gemfile
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug

#27420 upkeep: updated data set for 4.12
  pkg/synthetictests/allowedalerts/query_results.json
  pkg/synthetictests/allowedbackenddisruption/query_results.json
Labels: approved, lgtm

#27413 Add a test case to find job name/cluster version mismatches
  test/extended/ci/job_names.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#27417 OCPBUGS-967: temporarily disable IngressClass test, which is changed in upstream in 1.25
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug

#27043 Enable ServiceInternalTrafficPolicy tests in OVNK
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm

#27371 e2e/cli: Migrate completions, whoami and projects tests to go
  test/extended/cli/basics.go
  test/extended/cli/completions.go
  test/extended/cli/project.go
  test/extended/testdata/bindata.go
  test/extended/testdata/cmd/test/cmd/completions.sh
  test/extended/testdata/cmd/test/cmd/projects.sh
  test/extended/testdata/cmd/test/cmd/whoami.sh
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#27424 add retry for checkLADPConn
  test/extended/util/ldap.go
Labels: approved, lgtm

#27415 Fix double disruption testing and values for most backends in intervals chart and bigquery.
  cmd/openshift-tests/openshift-tests.go
  cmd/openshift-tests/upgrade.go
  pkg/monitor/monitorapi/disruption.go
  pkg/synthetictests/allowedbackenddisruption/matches.go
  pkg/synthetictests/apiserver.go
  pkg/synthetictests/disruption.go
  pkg/synthetictests/event_junits.go
  test/e2e/upgrade/cidisruptiontester/cidisruptiontester.go
  test/e2e/upgrade/upgrade.go
  test/extended/util/disruption/backend_sampler_tester.go
  test/extended/util/disruption/disruption.go
  test/extended/util/disruption/externalservice/known_backends.go
Labels: approved, lgtm

#27422 OCPBUGS-1265: test/extended/prometheus: Consider telemeterClient.enabled
  cmd/openshift-tests/minimal.go
  test/extended/prometheus/prometheus.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-low

#27426 make runonce-ldapsearch pod name unique
  test/extended/util/ldap.go
Labels: approved, lgtm

#27409 USHIFT-353: MicroShift: skip sig-installer tests
  test/extended/baremetal/high_availability.go
  test/extended/baremetal/hosts.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#27431 Bump api-requests for console-operator on vsphere
  test/extended/apiserver/api_requests.go
Labels: approved, lgtm

#27333 sig-api-machinery: remove project from authenticated browser APIServe…
  test/extended/apiserver/root_403.go
Labels: approved, lgtm

#27358 USHIFT-285: MicroShift: allow CLI creation without OpenShift APIs
  test/extended/util/client.go
  test/extended/util/framework.go
  test/extended/util/oc_copy.go
Labels: approved, lgtm

#27432 Check version when discovery client
  pkg/test/ginkgo/cmd_runsuite.go
Labels: approved, lgtm

#27380 Bug 1933144: Bump k8s to include c83b5d076f5
  go.mod
  go.sum
  test/extended/prometheus/prometheus.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  vendor/k8s.io/kubernetes/openshift-hack/e2e/annotate/rules.go
  vendor/k8s.io/kubernetes/pkg/quota/v1/install/registry.go
  vendor/k8s.io/kubernetes/test/e2e/apimachinery/aggregator.go
  vendor/k8s.io/kubernetes/test/e2e/network/netpol/kubemanager.go
  vendor/k8s.io/kubernetes/test/e2e/network/netpol/model.go
  vendor/k8s.io/kubernetes/test/e2e/network/netpol/network_policy.go
  vendor/k8s.io/kubernetes/test/e2e/network/netpol/probe.go
  vendor/k8s.io/kubernetes/test/e2e/network/netpol/reachability.go
  vendor/k8s.io/kubernetes/test/e2e/network/netpol/test_helper.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, bugzilla/severity-medium

#27391 Remove test 'clone repository using git:// protocol should clone using git:// if no proxy is configured'
  test/extended/builds/clone_git_protocol.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#27410 USHIFT-343: MicroShift: skip sig-api-machinery tests
  test/extended/apiserver/apply.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#27369 USHIFT-301: microshift: skip sig-operator tests
  test/extended/olm/olm.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#27397 USHIFT-344: MicroShift: fix sig-apps tests
  test/extended/controller_manager/deploy_scale.go
  test/extended/controller_manager/deploy_trigger.go
  test/extended/jobs/jobs.go
  test/extended/testdata/bindata.go
  test/extended/testdata/jobs/v1.yaml
Labels: approved, lgtm

#27441 OCPBUGS-985: Revert "Test Baremetal deployment without a provisoning network"
  test/extended/baremetal/common.go
  test/extended/baremetal/hosts.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug

#27408 remove test/extended OWNERS file
  test/extended/OWNERS
Labels: approved, lgtm

#27442 Fix rare race condition in ImageStream admission tests.
  test/extended/images/imagestream_admission.go
Labels: approved, lgtm

#27361 USHIFT-283: microshift: skip sig-builds tests
  test/extended/builds/build_pruning.go
  test/extended/builds/new_app.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#27448 feat: update query results
  pkg/synthetictests/allowedalerts/query_results.json
  pkg/synthetictests/allowedbackenddisruption/query_results.json
Labels: lgtm, do-not-merge/hold

#27356 include storage and must-gather tests in expectedTestCount
  pkg/test/ginkgo/cmd_runsuite.go
Labels: approved, lgtm

#27443 OCPBUGS-1079: Use kubeconfig from secret mount instead of /tmp
  cmd/openshift-tests/provider.go
  test/extended/util/test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug

#27379 egressip: avoid curl hanging when sending probes
  test/extended/networking/egressip_helpers.go
Labels: approved, lgtm

#27400 USHIFT-350: MicroShift: skip sig-coreos tests
  test/extended/coreos/coreos.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#27434 OCPBUGS-1052: allow frontends to tolerate 2.5% disruption during upgrades
  test/extended/util/disruption/frontends/frontends.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug
