Repository openshift/origin, pull requests merged in 2022-02, with the labels that each got.

#26569 Add baremetal high availability tests
  test/extended/baremetal/high_availability.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#26808 Fix broken console disruption test.
  test/extended/util/disruption/frontends/known_backends.go
Labels: approved, lgtm

#26812 Only run parallel tests in the canary job since it runs in parallel
  cmd/openshift-tests/e2e.go
Labels: approved, lgtm

#26806 Bug 2047911: IBMCloud: Concurrent CRB create
  test/extended/util/ibmcloud/provider.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#26815 bug 2050345: update p99 values for disruption and alerts
  pkg/synthetictests/allowedalerts/matches.go
  pkg/synthetictests/allowedalerts/matches_test.go
  pkg/synthetictests/allowedalerts/query_results.json
  pkg/synthetictests/allowedbackenddisruption/query_results.json
  test/extended/util/disruption/disruption.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#26811 images: update registry to 2.8.0-beta.1
  test/extended/images/imagestreamimport.go
  test/extended/images/mirror.go
  test/extended/util/image/image.go
  test/extended/util/image/zz_generated.txt
Labels: approved, lgtm, e2e-images-update

#26813 Delete extra workers before running metal high availability test
  test/extended/baremetal/helper.go
  test/extended/baremetal/high_availability.go
Labels: approved, lgtm

#26798 Debug missing OSUpdateStarted events
  pkg/monitor/event.go
  pkg/synthetictests/operators.go
Labels: approved, lgtm

#26817 Revert "Flake failed sandboxes from bug in new guard pods"
  pkg/synthetictests/networking.go
Labels: approved, lgtm

#26818 Bug 2045590: Alibaba: enable init for alibabacloud provider
  cmd/openshift-tests/provider.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#26780 baremetal: add test for preprovisioning images
  test/extended/baremetal/common.go
  test/extended/baremetal/hosts.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#26823 add job type key to the error we track for statistical jobs
  pkg/synthetictests/allowedalerts/basic_alert.go
  pkg/synthetictests/allowedalerts/matches.go
  pkg/synthetictests/allowedalerts/types.go
  pkg/synthetictests/allowedbackenddisruption/matches.go
  pkg/synthetictests/allowedbackenddisruption/matches_test.go
  pkg/synthetictests/allowedbackenddisruption/types.go
  test/extended/util/disruption/backend_sampler_tester.go
Labels: approved, lgtm

#26824 Break out test for OSUpdateStaged event with no OSUpdateStarted.
  pkg/synthetictests/event_junits.go
  pkg/synthetictests/operators.go
Labels: approved, lgtm

#26830 Bug 2052058: Break out test for OSUpdateStaged event with no OSUpdateStarted
  pkg/synthetictests/event_junits.go
  pkg/synthetictests/operators.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium, staff-eng-approved, backport-risk-assessed

#26831 bug 2053143:allow inexact matches for disruption data
  pkg/synthetictests/allowedalerts/matches.go
  pkg/synthetictests/allowedalerts/matches_test.go
  pkg/synthetictests/allowedalerts/types.go
  pkg/synthetictests/allowedbackenddisruption/matches.go
  pkg/synthetictests/allowedbackenddisruption/matches_test.go
  pkg/synthetictests/allowedbackenddisruption/types.go
  pkg/synthetictests/historicaldata/next_best_guess.go
  pkg/synthetictests/historicaldata/types.go
  pkg/synthetictests/platformidentification/types.go
  test/extended/util/disruption/backend_sampler_tester.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#26834 bug 2053312: requestheader test must wait for authentication operator to settle after config update
  test/extended/oauth/requestheaders.go
Labels: approved, lgtm, bugzilla/invalid-bug, bugzilla/severity-high

#26833 Allow a single test to override suite timeout
  pkg/test/ginkgo/ginkgo.go
  pkg/test/ginkgo/status.go
  pkg/test/ginkgo/test.go
Labels: approved, lgtm

#26837 bug 2053582: fail on static pod lifecycle failures
  pkg/synthetictests/event_junits.go
  pkg/synthetictests/static_pod.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#26810 Bug 2049117: Reenable wait on worker deletion and increase serial test timeout
  test/extended/baremetal/helper.go
  test/extended/machines/scale.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#26842 ip reconciler ignore
  test/e2e/upgrade/alert/alert.go
  test/extended/prometheus/prometheus.go
Labels: approved, lgtm

#26844 update alert thresholds after extending static pod install duration
  pkg/synthetictests/allowedalerts/query_results.json
Labels: approved, lgtm

#26848 Bug 2055193: Reenable wait on worker deletion and increase serial tes…
  test/extended/baremetal/helper.go
  test/extended/machines/scale.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium, staff-eng-approved, backport-risk-assessed

#26847 Bug 2055193: Allow a single test to override suite timeout
  pkg/test/ginkgo/ginkgo.go
  pkg/test/ginkgo/status.go
  pkg/test/ginkgo/test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium, staff-eng-approved, backport-risk-assessed

#26850 vsphere is firing this alert/VSphereOpenshiftNodeHealthFail and it is hiding other alerts
  pkg/synthetictests/allowedalerts/all.go
  pkg/synthetictests/allowedalerts/types.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#26368 OWNERS: Declare Bugzilla component
  OWNERS
Labels: approved, lgtm

#26852 allow slow kubelet updates for static pods, but still fail if they never succeed
  pkg/synthetictests/static_pod.go
  pkg/synthetictests/static_pod_test.go
Labels: approved, lgtm

#26685 Increase cluster-monitor-operator watch count threshold on single-node clusters
  test/extended/apiserver/api_requests.go
Labels: approved, lgtm

#26855 Set ovnkube-node readiness failure to flake for now.
  pkg/synthetictests/duplicated_events.go
  pkg/synthetictests/event_junits.go
  pkg/synthetictests/networking.go
Labels: approved, lgtm

#26857 Bz2054254 rearrange test cases
  test/extended/oauth/requestheaders.go
Labels: approved, lgtm

#26860 Fix ovnkube-node readiness test to include successes.
  pkg/synthetictests/networking.go
Labels: approved, lgtm

#26861 Increase scale test timeout to 30 minutes
  test/extended/machines/scale.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm
