Repository openshift/origin, pull requests merged in 2022-06, with the labels that each got.

#27193 wait for kube-apiserver to settle after modifying network configuration
  test/extended/networking/util.go
  test/extended/util/operator.go
Labels: approved

#27177 Bug 2086519: label project-created namespaces to not sync PodSecurity labels
  test/extended/util/client.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#27182 rename intervals to timelines to be self-explanatory
  pkg/monitor/intervalcreation/rendering.go
Labels: approved, lgtm, bugzilla/valid-bug

#27176 Bug 2085997: brings back the etcd scaling test
  test/extended/etcd/helpers/helpers.go
  test/extended/etcd/vertical_scaling.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  vendor/github.com/openshift/library-go/test/library/apiserver/apiserver.go
  vendor/github.com/openshift/library-go/test/library/client.go
  vendor/github.com/openshift/library-go/test/library/library.go
  vendor/github.com/openshift/library-go/test/library/pod_same_revision.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, bugzilla/severity-high

#27129 Bug 2085997: report late request (broken LB) for the external client
  test/extended/apiserver/graceful_termination.go
  test/extended/cli/mustgather.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#27185 Bug 2091067: EgressIP: Make tests retry on API timeout errors
  test/extended/networking/egressip.go
  test/extended/networking/egressip_helpers.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#27201 Bug 2079679: pkg/monitor: wait for Prometheus sidecars to be ready
  pkg/monitor/alerts.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#27093 Bug 2091547: Skip internet connection test if we use a proxy
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#27195 Bug 2081732: remove incorrect namespace check in static pod test
  pkg/synthetictests/static_pod.go
  pkg/synthetictests/static_pod_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#27204 Bug 2093046: priority class: add exception for must-gather pending bug fix
  test/extended/pods/priorityclasses.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-unspecified

#27186 Bug 2093234: Add regex filter and intervals duration to e2e-charts
  e2echart/e2e-chart-template.html
  test/extended/testdata/bindata.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#27203 Bug 2093049: test/extended/networking: fix [pod sysctls should not affect node] to use host interfaces
  test/extended/networking/tuning.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#27210 Bug 2092961: Flake almost all ci cluster to external svc disruption.
  test/e2e/upgrade/cidisruptiontester/cidisruptiontester.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#27202 Bug 2091110: Skip ErrImagePull for expected failures
  pkg/synthetictests/kubelet.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#27223 Revert "Bug 2079679: pkg/monitor: wait for Prometheus sidecars to be ready"
  pkg/monitor/alerts.go
Labels: lgtm, bugzilla/invalid-bug, bugzilla/severity-medium

#27216 Bug 2085997: explicit timeout for the etcd scaling test
  test/extended/etcd/vertical_scaling.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#27221 Bug 2093049: test/extended/networking: fix [pod sysctls should not affect node] to use known host interfaces
  test/extended/networking/tuning.go
  test/extended/security/sysctl.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#27230 Bug 2084361: Print error msg before os.Exit()
  cmd/openshift-tests/openshift-tests.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#27217 Bug 2092961: Use http for network endpoint test.
  test/e2e/upgrade/cidisruptiontester/cidisruptiontester.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#27236 Bug 2094919: Skip etcd vertical scaling test on vsphere
  test/extended/etcd/helpers/helpers.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-unspecified

#27220 Bug 2085997: Report late requests verification: Fix for Hypershift
  test/extended/apiserver/graceful_termination.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#27234 Bug 2086086: update samples for 4.11
  examples/db-templates/mariadb-ephemeral-template.json
  examples/db-templates/mariadb-persistent-template.json
  examples/image-streams/image-streams-centos7.json
  examples/jenkins/jenkins-ephemeral-template.json
  examples/jenkins/jenkins-persistent-template.json
  examples/quickstarts/cakephp-mysql-persistent.json
  hack/update-external-examples.sh
  test/extended/image_ecosystem/s2i_images.go
  test/extended/testdata/bindata.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#27189 Bug 2064800: skip imageregistry serial test on disconnected environments
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, qe-approved, backport-risk-assessed

#27249 Bug 2097009: Run must-gather tests in later to reduce resource contention
  pkg/test/ginkgo/cmd_runsuite.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#27252 Bug 2086092: Extend time for kube rebase
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#27206 bug 2093051: use the node update finished as a backup completion time for OSStaged
  pkg/monitor/monitorapi/identification_pod.go
  pkg/synthetictests/operators.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#27250 Bug 2097297: Don't consider DNS lookup failure disruption
  pkg/monitor/backenddisruption/disruption_backend_sampler.go
  pkg/monitor/backenddisruption/disruption_backend_sampler_test.go
  pkg/monitor/backenddisruption/disruption_locator.go
  pkg/monitor/write_job_run_data.go
  pkg/synthetictests/event_junits.go
  pkg/synthetictests/networking.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#27254 Bug 2093992: Bump timeout for cvo ugprade check to 10 minutes for Baremetal jobs
  test/e2e/upgrade/upgrade.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#27102 Bug 2097684: Nutanix provider for e2e testing
  cmd/openshift-tests/provider.go
  test/extended/util/nutanix/provider.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#27238 Bug 2097713: Extend the allowance for etcdHighNumberOfLeaderChanges.
  pkg/synthetictests/allowedalerts/allow_on_revision_change.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#27258 Bug 2086092: Re-enable tests
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#27267 Bug 2093339: move provisioning test to permanent disablement, since this is not yet officially supported
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#27191 Bug 2098094: EgressIP test: Remove print statement on test failure
  test/extended/networking/egressip.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#27263 Bug 2099611: Increase etcd-operator watch channels upperbound for BareMetal Platform
  test/extended/apiserver/api_requests.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#27243 Bug 2098095: EgressIP tests: Use OpenShift API to retrieve CloudPrivateIPConfigs and EgressIPs
  test/extended/networking/egressip.go
  test/extended/networking/egressip_helpers.go
  vendor/github.com/openshift/client-go/cloudnetwork/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/cloudnetwork/clientset/versioned/doc.go
  vendor/github.com/openshift/client-go/cloudnetwork/clientset/versioned/scheme/doc.go
  vendor/github.com/openshift/client-go/cloudnetwork/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/cloudnetwork/clientset/versioned/typed/cloudnetwork/v1/cloudnetwork_client.go
  vendor/github.com/openshift/client-go/cloudnetwork/clientset/versioned/typed/cloudnetwork/v1/cloudprivateipconfig.go
  vendor/github.com/openshift/client-go/cloudnetwork/clientset/versioned/typed/cloudnetwork/v1/doc.go
  vendor/github.com/openshift/client-go/cloudnetwork/clientset/versioned/typed/cloudnetwork/v1/generated_expansion.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, bugzilla/severity-low

#27257 Bug 2086519: authorization: add a test checking that the restricted-v2 SCC mutates securityContext to match restricted PSa
  test/extended/authorization/podsecurity_admission.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#27208 Bug 2093122: synthetictests: Event struct's Related field is optional
  pkg/synthetictests/duplicated_events.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#27272 Bug 2100439: Enable GCP PD in-tree tests
  hack/update-generated.sh
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#26985 Bug 2098053: Re-revert "Add networking test for invalid external gateway"
  test/extended/networking/external_gateway.go
  test/extended/networking/util.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, ok-to-test, bugzilla/valid-bug, bugzilla/severity-medium

#27273 Bug 2098053: Re-revert "Add networking test for invalid external gateway"
  test/extended/networking/external_gateway.go
  test/extended/networking/util.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium
