Repository openshift/origin, pull requests merged in 2022-05, with the labels that each got.

#27065 [release-4.10] Bug 2080759: Remove BlueOcean annotation check
  test/extended/builds/pipeline_origin_bld.go
  test/extended/builds/pipeline_origin_bld_rhelimagesonly.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#27080 haproxy needs to request privilege escalation in order to work
  test/extended/router/h2spec.go
  test/extended/testdata/bindata.go
  test/extended/testdata/router/router-h2spec.yaml
Labels: lgtm

#27087 skip 'should not see excessive Back-off restarting failed containers' for e2e tests
  pkg/monitor/monitorapi/types.go
  pkg/synthetictests/duplicated_events.go
  pkg/synthetictests/event_junits.go
  pkg/synthetictests/image_pulls.go
Labels: approved, lgtm

#27085 give multi-arch more time to complete upgrades to clean up signal
  pkg/synthetictests/platformidentification/types.go
  test/e2e/upgrade/upgrade.go
Labels: approved, lgtm

#27067 test/extended/prometheus/image_pulls: New "should be fast" test-case
  test/e2e/upgrade/upgrade.go
  test/extended/prometheus/image_pulls.go
Labels: approved, lgtm

#27044 Remove non-functional gu workload tests.
  go.mod
  test/extended/include.go
  test/extended/topology_manager/README.md
  test/extended/topology_manager/numa_alignment.go
  test/extended/topology_manager/resourcealign.go
  test/extended/topology_manager/utils.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#27084 router: wait for "use scc restricted" SAR before pod creation
  test/extended/deployments/deployments.go
  test/extended/router/h2spec.go
  test/extended/util/framework.go
  test/extended/util/oauthserver/oauthserver.go
Labels: approved, lgtm

#27091 test: allow -f to match tests for any test suite
  pkg/test/ginkgo/cmd_runsuite.go
  pkg/test/ginkgo/test.go
Labels: approved, lgtm

#27031 MON-2148: Handle 401 code for prometheus api route
  test/extended/operators/routable.go
Labels: approved, lgtm

#26989 Bug 2069201: Check resolv.conf file existence
  pkg/cmd/server/kubernetes/network/network_config.go
Labels: approved, lgtm, ok-to-test, bugzilla/valid-bug, bugzilla/severity-high

#26957 NE-626: Add DNS CI coverage for golang and glibc resolver libraries
  test/extended/dns/dns_libraries.go
  test/extended/testdata/bindata.go
  test/extended/testdata/dns/Dockerfile
  test/extended/testdata/dns/dns_libraries_go
  test/extended/testdata/dns/dns_libraries_go.yaml
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#27103 Revert "NE-626: Add DNS CI coverage for golang and glibc resolver libraries"
  test/extended/dns/dns_libraries.go
  test/extended/testdata/bindata.go
  test/extended/testdata/dns/Dockerfile
  test/extended/testdata/dns/dns_libraries_go
  test/extended/testdata/dns/dns_libraries_go.yaml
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#27098 Bug 2080681: Request new token instead of using node-bootstrapper token
  test/extended/csrapprover/csrapprover.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#27092 make it easy to create pod interval tests
  pkg/monitor/intervalcreation/podTest/container-life/expected.json
  pkg/monitor/intervalcreation/podTest/container-life/podData.json
  pkg/monitor/intervalcreation/podTest/container-life/startingEvents.json
  pkg/monitor/intervalcreation/podTest/container-life/times.txt
  pkg/monitor/intervalcreation/podTest/end-before-begin/expected.json
  pkg/monitor/intervalcreation/podTest/end-before-begin/podData.json
  pkg/monitor/intervalcreation/podTest/end-before-begin/startingEvents.json
  pkg/monitor/intervalcreation/podTest/end-before-begin/times.txt
  pkg/monitor/intervalcreation/podTest/installer-pod/expected.json
  pkg/monitor/intervalcreation/podTest/installer-pod/podData.json
  pkg/monitor/intervalcreation/podTest/installer-pod/startingEvents.json
  pkg/monitor/intervalcreation/podTest/installer-pod/times.txt
  pkg/monitor/intervalcreation/podTest/long-not-ready/expected.json
  pkg/monitor/intervalcreation/podTest/long-not-ready/podData.json
  pkg/monitor/intervalcreation/podTest/long-not-ready/startingEvents.json
  pkg/monitor/intervalcreation/podTest/long-not-ready/times.txt
  pkg/monitor/intervalcreation/podTest/run-once-done/expected.json
  pkg/monitor/intervalcreation/podTest/run-once-done/podData.json
  pkg/monitor/intervalcreation/podTest/run-once-done/startingEvents.json
  pkg/monitor/intervalcreation/podTest/run-once-done/times.txt
  pkg/monitor/intervalcreation/podTest/simple/expected.json
  pkg/monitor/intervalcreation/podTest/simple/podData.json
  pkg/monitor/intervalcreation/podTest/simple/startingEvents.json
  pkg/monitor/intervalcreation/podTest/simple/times.txt
  pkg/monitor/intervalcreation/podTest/trailing-ready-2/expected.json
  pkg/monitor/intervalcreation/podTest/trailing-ready-2/podData.json
  pkg/monitor/intervalcreation/podTest/trailing-ready-2/startingEvents.json
  pkg/monitor/intervalcreation/podTest/trailing-ready-2/times.txt
  pkg/monitor/intervalcreation/podTest/trailing-ready/expected.json
  pkg/monitor/intervalcreation/podTest/trailing-ready/podData.json
  pkg/monitor/intervalcreation/podTest/trailing-ready/startingEvents.json
  pkg/monitor/intervalcreation/podTest/trailing-ready/times.txt
  pkg/monitor/intervalcreation/pod_test.go
Labels: approved, lgtm

#27110 test/extended/util/openshift/clusterversionoperator/adminack: Accept MultipleReasons
  test/extended/util/openshift/clusterversionoperator/adminack.go
Labels: approved, lgtm

#27101 Bug 2082239: Bump net.ipv6.neigh.IFNAME from 30005 to 30010 for Multiarch
  test/extended/networking/tuning.go
Labels: approved, lgtm

#27086 [rebase 1.24] disable tests with time limit to facilitate rebase
  cmd/openshift-tests/e2e.go
  cmd/openshift-tests/e2e_test.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm

#27099 Bug 2080679: fix oc related test to land k8s 1.24
  test/extended/images/oc_tag.go
  test/extended/testdata/bindata.go
  test/extended/testdata/cmd/test/cmd/quota.sh
  test/extended/testdata/cmd/test/cmd/secrets.sh
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#27107 prometheus helper: add helper to retrieve prometheus query token
  test/extended/prometheus/client/via_route.go
  test/extended/util/prometheus/helpers.go
Labels: approved, lgtm

#27104 Bug 2081012: Don't wait for sa token
  test/extended/controller_manager/pull_secret.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#27113 Fix request token ic cli/admin tests
  test/extended/cli/admin.go
Labels: approved, lgtm

#27100 Bug 2080687: request prometheus service account token
  test/extended/router/metrics.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#27112 Correct pod timing
  cmd/openshift-tests/openshift-tests.go
  pkg/monitor/api.go
  pkg/monitor/intervalcreation/pod.go
  pkg/monitor/intervalcreation/rendering.go
  pkg/monitor/intervalcreation/rendering_per_namespace.go
  pkg/monitor/monitor_cmd/command.go
  pkg/monitor/monitorapi/types.go
  pkg/monitor/pod.go
  pkg/monitor/serialization/serialize.go
Labels: approved, lgtm

#27116 Add config for golangci-lint no-sprintf-host-port
  .golangci.yml
Labels: approved, lgtm

#27030 NE-883: test/extended/router: Add test for spec.subdomain
  test/extended/router/subdomain.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, docs-approved, qe-approved, px-approved

#27114 timeline command, container exit fix, key resources by uid, and use reflector
  e2echart/e2e-chart-template.html
  pkg/monitor/intervalcreation/pod.go
  pkg/monitor/intervalcreation/podTest/end-before-begin/podData.json
  pkg/monitor/intervalcreation/podTest/installer-pod/podData.json
  pkg/monitor/intervalcreation/podTest/run-once-done/podData.json
  pkg/monitor/intervalcreation/pod_test.go
  pkg/monitor/monitor.go
  pkg/monitor/monitor_cmd/command.go
  pkg/monitor/monitorapi/types.go
  pkg/monitor/monitoring_reflector_store.go
  pkg/monitor/pod.go
  pkg/monitor/serialization/resource.go
  test/extended/testdata/bindata.go
Labels: approved, lgtm

#27120 Don't hardcode the SA token audience when requesting one
  test/extended/router/metrics.go
Labels: approved, lgtm

#27119 Bump net.ipv6.neigh.IFNAME.retrans_time_ms for Multiarch
  test/extended/networking/tuning.go
Labels: approved, lgtm

#27111 Add debugging message for static pod test
  pkg/synthetictests/static_pod.go
Labels: approved, lgtm

#27132 add test to catch single second disruption patterns
  pkg/synthetictests/apiserver.go
  pkg/synthetictests/event_junits.go
Labels: approved, lgtm

#27123 Bug 2083941: feat: add fuzzy match on micro release
  pkg/synthetictests/allowedbackenddisruption/matches_test.go
  pkg/synthetictests/historicaldata/next_best_guess.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#27078 Bug 2080007: unrevert external ip configuration e2e networking tests
  cmd/openshift-tests/e2e.go
  test/extended/networking/services.go
  test/extended/networking/util.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/framework.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#27131 always allow at least one second for disruption
  test/extended/util/disruption/backend_sampler_tester.go
Labels: approved, lgtm, bugzilla/valid-bug

#27134 Bug 2085997: gives the backend monitoring an identity
  pkg/monitor/backenddisruption/disruption_backend_sampler.go
  test/extended/util/disruption/controlplane/known_backends.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#27130 update alert and disruption limits
  pkg/synthetictests/allowedalerts/matches_test.go
  pkg/synthetictests/allowedalerts/query_results.json
  pkg/synthetictests/allowedbackenddisruption/matches_test.go
  pkg/synthetictests/allowedbackenddisruption/query_results.json
Labels: approved, lgtm, bugzilla/valid-bug

#27118 Bug 2085997: adds new test to the API monitor
  test/extended/util/disruption/controlplane/known_backends.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#27136 Bug 2084361: Add some debugging information for mysterious exit 2 errors
  cmd/openshift-tests/openshift-tests.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#27141 Bug 2085997: ensure number of voting members in the cm matches the number of master machines
  test/extended/etcd/invariants.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#27142 commenting ipv6 for sysctls
  test/extended/networking/tuning.go
Labels: approved, lgtm, bugzilla/valid-bug

#27144 Add user coreydaley as an approver
  OWNERS_ALIASES
  examples/db-templates/OWNERS
  examples/hello-openshift/OWNERS
  examples/image-streams/OWNERS
  examples/jenkins/OWNERS
  examples/quickstarts/OWNERS
  examples/sample-app/OWNERS
  test/extended/builds/OWNERS
  test/extended/image_ecosystem/OWNERS
  tools/buildanalyzer/OWNERS
Labels: approved, lgtm, bugzilla/valid-bug

#26999 EgressIP downstream tests for OVN Kubernetes
  test/extended/networking/egressip.go
  test/extended/networking/egressip_helpers.go
  test/extended/networking/util.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
  test/extended/util/framework.go
  test/extended/util/oauthserver/oauthserver.go
  test/extended/util/release.go
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug

#27147 Bug 2085997: the machine API can be unavailable resulting in a 404 or an empty list
  pkg/synthetictests/duplicated_events.go
  test/extended/etcd/helpers/helpers.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#27150 Bug 2087230: disable flaky unidling test
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#26954 BZ 2087504: Add Early test to check for CRD subresource.status
  test/extended/operators/check_crd_status.go
  test/extended/operators/check_crd_status_test.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, bugzilla/valid-bug

#27149 Bug 2085997: ExternalControlPlaneTopology: Skip etcd master endpoint verification
  test/extended/etcd/invariants.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#27148 Bug 2085997: makes the etcd invariant test work on dualstack platform
  test/extended/etcd/invariants.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#27152 Bug 2086519: Auth-133: test/extended/util: comply exec pod to restricted pod security profile
  test/extended/util/pods.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#27133 Bug 2086086: image_ecosystem: remove deprecated imagestreams
  test/extended/image_ecosystem/s2i_images.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#27143 Bug 2081732: Dump debug message whenever static pod test fails
  pkg/synthetictests/static_pod.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#27161 don't trigger single second disruption on contiguous disruption
  pkg/synthetictests/apiserver.go
Labels: approved, lgtm

#27173 Bug 2086519: bump o/kube so that test namespaces aren't PSa label synced
  go.mod
  go.sum
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go
  vendor/k8s.io/kubernetes/pkg/kubelet/pod/pod_manager.go
  vendor/k8s.io/kubernetes/pkg/kubelet/util/manager/cache_based_manager.go
  vendor/k8s.io/kubernetes/test/e2e/framework/framework.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, bugzilla/severity-urgent

#27164 Bug 2089276: Detect and use the packet capture interface for EgessIP tests.
  test/extended/networking/egressip.go
  test/extended/networking/egressip_helpers.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#27151 add per-namespace tests for kubepodnotready alert failures
  pkg/monitor/alerts.go
  pkg/synthetictests/allowedalerts/all.go
  pkg/synthetictests/allowedalerts/basic_alert.go
  pkg/synthetictests/operator_mapping.go
  pkg/synthetictests/operators.go
  pkg/synthetictests/platformidentification/operator_mapping.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, bugzilla/valid-bug

#27172 Bug 2077167: disable unidling test failing under ovn-k
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#27168 Revert "Bug 2089831: Temporarily disable telemetry token test."
  test/extended/prometheus/prometheus.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#27160 Bug 2081732: Static pod test error
  pkg/synthetictests/static_pod.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#27178 Bug 2086092: skip tests to facilitate rebase
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#27175 allow up to two DNS check pods to be waiting
  test/e2e/upgrade/dns/dns.go
Labels: approved, lgtm, bugzilla/valid-bug

#27183 Bug 2090692: slightly loosen oc exec help test
  test/extended/testdata/bindata.go
  test/extended/testdata/cmd/test/cmd/help.sh
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#27184 restrict the per-namespace invariant alert check
  pkg/monitor/alerts.go
  pkg/synthetictests/allowedalerts/basic_alert.go
  pkg/synthetictests/platformidentification/operator_mapping.go
Labels: approved, lgtm, bugzilla/valid-bug

#26998 Bug 2091086: cli: don't insist on metal3 CRDs being present when cluster capabilities are None
  test/extended/cli/explain.go
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, bugzilla/severity-low

#27190 Bug 1992596: move help.sh to golang-based e2e
  pkg/monitor/monitoring_reflector_store.go
  test/extended/cli/help.go
  test/extended/testdata/bindata.go
  test/extended/testdata/cmd/test/cmd/help.sh
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium
