Repository openshift/origin, pull requests merged in 2022-01, with the labels that each got.

#26719 Bug 2026488: Skip Duplicate openshift-controller-manager Events
  cmd/openshift-tests/images.go
  pkg/synthetictests/duplicated_events.go
  pkg/synthetictests/event_junits.go
  pkg/test/ginkgo/cmd_runsuite.go
  pkg/test/ginkgo/synthentic_tests.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#26708 Bug 2033720: Drop usage of old imagestreams
  examples/jenkins/pipeline/bluegreen-pipeline.yaml
  examples/jenkins/pipeline/samplepipeline.yaml
  test/extended/image_ecosystem/s2i_images.go
  test/extended/testdata/bindata.go
  test/extended/testdata/cluster/quickstarts/cakephp-mysql.json
  test/extended/testdata/cluster/quickstarts/nodejs-postgresql.json
  test/extended/testdata/cluster/quickstarts/rails-postgresql.json
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#26726 update p95 values
  pkg/synthetictests/allowedbackenddisruption/matches.go
  pkg/synthetictests/allowedbackenddisruption/query_results.json
  pkg/synthetictests/allowedbackenddisruption/types.go
Labels: approved, lgtm, bugzilla/valid-bug

#26702 Add tests for ErrImagePull monitor intervals.
  pkg/synthetictests/event_junits.go
  pkg/synthetictests/kubelet.go
  pkg/test/ginkgo/synthentic_tests.go
Labels: approved, lgtm, bugzilla/valid-bug

#26729 Bug 1919453: [release-4.6] configure tests to pull images from mirror
  test/extended/images/append.go
  test/extended/images/extract.go
  test/extended/images/info.go
  test/extended/images/layers.go
  test/extended/images/oc_tag.go
  test/extended/images/resolve.go
  test/extended/images/trigger/annotation.go
  test/extended/util/image/util.go
  test/extended/util/ldap.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#26730 making missing p95 obvious to see and add topology to our search keys
  pkg/synthetictests/allowedbackenddisruption/matches.go
  pkg/synthetictests/allowedbackenddisruption/matches_test.go
  pkg/synthetictests/allowedbackenddisruption/query_results.json
  pkg/synthetictests/allowedbackenddisruption/types.go
Labels: approved, lgtm, bugzilla/valid-bug

#26714 test/extended/util/annotate/generated: Delegate to team leads
  OWNERS_ALIASES
  test/extended/util/annotate/generated/OWNERS
Labels: approved, lgtm, bugzilla/valid-bug

#26728 Bug 1981867: add backoff retries for oc explain tests
  test/extended/cli/explain.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#26734 Bug 2039074: Revert "Add workaround for baremetal resources test"
  test/extended/baremetal/hosts.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#26740 use route to access prometheus instead of exec pods.
  test/e2e/upgrade/alert/alert.go
  test/extended/machines/cluster.go
  test/extended/prometheus/prometheus.go
  test/extended/prometheus/prometheus_builds.go
  test/extended/prometheus/storage.go
  test/extended/prometheus/upgrade.go
  test/extended/util/client.go
  test/extended/util/prometheus/helpers.go
Labels: approved, lgtm, bugzilla/valid-bug

#26742 allow wardle aggregated apiservers to be down pending bug
  test/extended/prometheus/prometheus.go
Labels: approved, lgtm, bugzilla/valid-bug

#26741 watch specific alerts for pending and firing
  pkg/monitor/alerts.go
  pkg/monitor/monitorapi/types.go
  pkg/synthetictests/alerts.go
  pkg/synthetictests/allowedalerts/all.go
  pkg/synthetictests/allowedalerts/basic_alert.go
  pkg/synthetictests/allowedbackenddisruption/matches.go
  pkg/synthetictests/event_junits.go
  pkg/synthetictests/platformidentification/types.go
  pkg/test/ginkgo/cmd_runsuite.go
  test/extended/prometheus/alerts.go
  test/extended/prometheus/prometheus.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/conditions.go
Labels: approved, lgtm, bugzilla/valid-bug

#26743 separate out more alerts into specific tests
  pkg/monitor/monitorapi/types.go
  pkg/synthetictests/allowedalerts/all.go
  pkg/synthetictests/allowedalerts/basic_alert.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, bugzilla/valid-bug

#26733 Bug 2038876: [release-4.8] test: skip tests that won't work behind a proxy automatically
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
  test/extended/util/cluster/cluster.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#26735 stop flaking on disruption because we always produce data for analysis
  test/extended/util/disruption/disruption.go
Labels: approved, lgtm, bugzilla/valid-bug

#26746 for upgrades, skip alerts with individual invariant tests
  test/e2e/upgrade/alert/alert.go
Labels: approved

#26747 allow burn budget to flake until kube-apiserver team finds and fixes it
  pkg/synthetictests/allowedalerts/all.go
Labels: approved, lgtm

#26737 Bug 2038389: Fix vsphere testing workarounds
  pkg/synthetictests/duplicated_events.go
  pkg/synthetictests/duplicated_events_test.go
  test/extended/operators/operators.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#26660 Bug 2040741: Allow baremetal tests to run on multiple platforms
  test/extended/baremetal/hosts.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#26757 make it easy to create multiple flavors of interval charts
  pkg/monitor/intervalcreation/rendering.go
  pkg/monitor/write_job_run_data.go
  pkg/test/ginkgo/cmd_runsuite.go
  pkg/test/ginkgo/write_job_run_data.go
Labels: approved, lgtm, bugzilla/valid-bug

#26761 allow promtail restarts as designed
  pkg/synthetictests/duplicated_events.go
Labels: approved, lgtm, do-not-merge/hold, bugzilla/valid-bug

#26760 split watchdog test into its own test
  pkg/synthetictests/allowedalerts/all.go
  pkg/synthetictests/allowedalerts/basic_alert.go
  pkg/synthetictests/allowedalerts/watchdog.go
  test/e2e/upgrade/alert/alert.go
  test/extended/prometheus/prometheus.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, bugzilla/valid-bug

#26755 Alter junit test suite names for jobs with multiple junit xmls.
  cmd/openshift-tests/openshift-tests.go
  cmd/openshift-tests/upgrade.go
  pkg/test/ginkgo/cmd_runsuite.go
Labels: approved, lgtm, bugzilla/valid-bug

#26762 separate prometheus watch alerts
  pkg/synthetictests/allowedalerts/all.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, bugzilla/valid-bug

#26756 Bug 1931594: add one more timeout condition for --request-timeout test
  test/extended/cli/timeout.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#26759 Add test for OS updates being staged within 5-10m.
  pkg/synthetictests/event_junits.go
  pkg/synthetictests/operators.go
Labels: approved, lgtm, bugzilla/valid-bug

#26767 update disruption times and shift to p99
  pkg/synthetictests/allowedbackenddisruption/matches.go
  pkg/synthetictests/allowedbackenddisruption/matches_test.go
  pkg/synthetictests/allowedbackenddisruption/query_results.json
  pkg/synthetictests/allowedbackenddisruption/types.go
Labels: approved, lgtm, bugzilla/valid-bug

#26766 bug 2005901: Allow KA guard probe to fail as designed
  pkg/synthetictests/duplicated_events.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#26769 loki moved namespaces, so we have to move to match
  pkg/synthetictests/duplicated_events.go
Labels: approved, lgtm, bugzilla/valid-bug

#26736 Bug 2026802: copy api-request upperbound for cluster-monitoring-operator
  test/extended/apiserver/api_requests.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, qe-approved, backport-risk-assessed

#26771 allow loki target to be down
  test/e2e/upgrade/alert/alert.go
  test/extended/prometheus/prometheus.go
Labels: approved, lgtm, bugzilla/valid-bug

#26646 Bug 2037075: Verify Builds with CSI Volume Sources
  test/extended/builds/volumes.go
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/volumes/csi-docker-buildconfig.yaml
  test/extended/testdata/builds/volumes/csi-s2i-buildconfig.yaml
  test/extended/testdata/builds/volumes/csi-sharedresourcerole.yaml
  test/extended/testdata/builds/volumes/csi-sharedresourcerolebinding.yaml
  test/extended/testdata/builds/volumes/csi-sharedsecret.yaml
  test/extended/testdata/builds/volumes/csi-without-rr-docker-buildconfig.yaml
  test/extended/testdata/builds/volumes/csi-without-rr-s2i-buildconfig.yaml
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#26681 Bug 2035534: Baremetal skip inspection
  test/extended/baremetal/common.go
  test/extended/baremetal/helper.go
  test/extended/baremetal/hosts.go
  test/extended/machines/scale.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#26773 storage operator can go upgradeable=unknown if vsphere is unreachable
  test/extended/operators/operators.go
Labels: approved, lgtm, bugzilla/valid-bug

#26772 adds a synthetic test for checking if the pod.spec.nodeName field is immutable
  pkg/monitor/pod.go
  pkg/synthetictests/apiserver.go
  pkg/synthetictests/event_junits.go
Labels: approved, lgtm, do-not-merge/hold, bugzilla/valid-bug

#26776 Bug 2038481: Flake failed sandboxes from bug in new guard pods
  pkg/synthetictests/networking.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#26768 Bug 2034285: test/extended: re-enable API data in etcd test
  test/extended/etcd/etcd_storage_path.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#26774 Bug 2044210: [baremetal] remove wait condition when deleting extraworkers
  test/extended/baremetal/helper.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#26778 Bug 2040793: Fix ordering issues with snapshot e2e
  go.mod
  go.sum
  vendor/k8s.io/cloud-provider/go.mod
  vendor/k8s.io/cloud-provider/go.sum
  vendor/k8s.io/csi-translation-lib/go.sum
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/test/e2e/apimachinery/aggregator.go
  vendor/k8s.io/kubernetes/test/e2e/storage/drivers/in_tree.go
  vendor/k8s.io/kubernetes/test/e2e/storage/testsuites/snapshottable.go
  vendor/k8s.io/legacy-cloud-providers/openstack/openstack.go
  vendor/k8s.io/mount-utils/go.mod
  vendor/k8s.io/mount-utils/go.sum
  vendor/k8s.io/utils/clock/clock.go
  vendor/k8s.io/utils/clock/testing/fake_clock.go
  vendor/k8s.io/utils/inotify/inotify_linux.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, bugzilla/severity-medium

#26781 use real alert data to determine flake and failure timeframes for alerts
  pkg/synthetictests/allowedalerts/basic_alert.go
  pkg/synthetictests/allowedalerts/matches.go
  pkg/synthetictests/allowedalerts/matches_test.go
  pkg/synthetictests/allowedalerts/query_results.json
  pkg/synthetictests/allowedalerts/types.go
Labels: approved, lgtm, bugzilla/valid-bug

#26782 Bug 2045590: Adding new cloud provider e2e for alibabacloud
  cmd/openshift-tests/provider.go
  cmd/openshift-tests/provider_test.go
  test/extended/util/alibabacloud/provider.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#26777 Bug 2043042: Additional checks for requestheaders.go
  test/extended/oauth/requestheaders.go
Labels: approved, bugzilla/valid-bug, bugzilla/severity-high

#26789 Flake instead of fail the timely OSUpdateStaged test on metal and ovirt.
  pkg/synthetictests/event_junits.go
  pkg/synthetictests/operators.go
Labels: approved, lgtm

#26790 Revert "add support for build csi volume source"
  test/extended/builds/volumes.go
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/volumes/csi-docker-buildconfig.yaml
  test/extended/testdata/builds/volumes/csi-s2i-buildconfig.yaml
  test/extended/testdata/builds/volumes/csi-sharedresourcerole.yaml
  test/extended/testdata/builds/volumes/csi-sharedresourcerolebinding.yaml
  test/extended/testdata/builds/volumes/csi-sharedsecret.yaml
  test/extended/testdata/builds/volumes/csi-without-rr-docker-buildconfig.yaml
  test/extended/testdata/builds/volumes/csi-without-rr-s2i-buildconfig.yaml
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#26748 Bug 2039539: Allow apiserver burn rate alert to fire in CI
  pkg/synthetictests/allowedalerts/all.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#26796 don't double report early alert failures
  test/extended/prometheus/prometheus.go
Labels: approved, lgtm, bugzilla/valid-bug

#26800 Bug 2047790: Skip some HAProxy tests on FIPS
  test/extended/router/scoped.go
  test/extended/router/unprivileged.go
  test/extended/router/weighted.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#26791 Verify Builds with CSI Volume Sources
  test/extended/builds/volumes.go
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/volumes/csi-docker-buildconfig.yaml
  test/extended/testdata/builds/volumes/csi-s2i-buildconfig.yaml
  test/extended/testdata/builds/volumes/csi-sharedresourcerole.yaml
  test/extended/testdata/builds/volumes/csi-sharedresourcerolebinding.yaml
  test/extended/testdata/builds/volumes/csi-sharedsecret.yaml
  test/extended/testdata/builds/volumes/csi-without-rr-docker-buildconfig.yaml
  test/extended/testdata/builds/volumes/csi-without-rr-s2i-buildconfig.yaml
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#26793 Bug 2047362: Prometheus check targets endpoint
  test/extended/operators/routable.go
  test/extended/prometheus/prometheus.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium
