Repository openshift/origin, pull requests merged in 2022-12, with the labels that each got.

#27585 TRT-662: include test count totals for analysis
  pkg/riskanalysis/cmd.go
  pkg/riskanalysis/types.go
  pkg/riskanalysis/write_test_failure_summary.go
Labels: approved, lgtm

#27584 USHIFT-658: ushift: skip networking bond interface tests
  test/extended/networking/bonds.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#27579 USHIFT-647: ushift: fix loop variable capture in sig-cli
  test/extended/cli/explain.go
Labels: approved, lgtm

#27582 Remove redundant messages that might contain non-xml charactor
  test/extended/util/disruption/disruption.go
Labels: approved, lgtm

#27577 USHIFT-644: Skip sig-cloud-provider tests
  test/extended/cloud_controller_manager/ccm.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#27569 Allow baremetal tests to run on AWS platform
  test/extended/baremetal/common.go
  test/extended/baremetal/hosts.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#27592 Round the ratio for excessive watch requests test
  test/extended/apiserver/api_requests.go
Labels: approved, lgtm

#27574 OCPBUGS-4190: 1sec
  test/extended/util/disruption/backend_sampler_tester.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug

#27590 Separate out "startupProbe failed" messages from pathological events test
  pkg/synthetictests/duplicated_events.go
  pkg/synthetictests/duplicated_events_special.go
  pkg/synthetictests/event_junits.go
  pkg/synthetictests/marketplace.go
Labels: approved, lgtm

#27395 Add trozet to networking approvers
  test/extended/networking/OWNERS
Labels: approved, lgtm

#27597 OCPBUGS-4502: Unskip service session affinity tests
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-critical

#27596 run resourcewatch fixes
  go.mod
  go.sum
  pkg/monitor/resourcewatch/cmd/resourcewatch.go
  pkg/monitor/resourcewatch/controller/clusteroperatormetric/controller.go
  pkg/monitor/resourcewatch/controller/configmonitor/crd_controller.go
  pkg/monitor/resourcewatch/controller/configmonitor/dynamic_informer.go
  pkg/monitor/resourcewatch/operator/starter.go
  pkg/monitor/resourcewatch/storage/diff.go
  pkg/monitor/resourcewatch/storage/git_store.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/base_controller.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/controller_context.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/eventfilters.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/factory.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/management/management_state.go
  vendor/github.com/robfig/cron/.gitignore
  vendor/github.com/robfig/cron/.travis.yml
  vendor/github.com/robfig/cron/LICENSE
  vendor/github.com/robfig/cron/README.md
  vendor/github.com/robfig/cron/constantdelay.go
  vendor/github.com/robfig/cron/cron.go
  vendor/github.com/robfig/cron/doc.go
  vendor/github.com/robfig/cron/parser.go
  vendor/github.com/robfig/cron/spec.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update

#27605 OCPBUGS-4550: Bump api-requests for console-operator on vsphere
  test/extended/apiserver/api_requests.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate

#27606 remove special cases for priority classes in the payload
  test/extended/pods/priorityclasses.go
Labels: approved, lgtm

#27600 TRT-703: Fix upgrade junit results not present in risk analysis
  pkg/alerts/check.go
  test/extended/util/disruption/disruption.go
Labels: approved, lgtm

#27572 Add tests for oc scc-subject-review and scc-review commands
  test/extended/cli/policy.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#27608 OCPBUGS-4731: oc status: clean job resource to prevent leaks
  test/extended/cli/status.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate

#27583 Remove ambiguity when checking for api resources existence
  test/extended/cli/explain.go
  test/extended/networking/egressip.go
  test/extended/util/client.go
  test/extended/util/disruption/frontends/known_backends.go
  test/extended/util/framework.go
Labels: approved, lgtm

#27598 OCPBUGS-4503: Unskip service session affinity tests
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical

#27613 OpenStack: Skip in-tree cinder provisioner tests
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm

#27511 NE-1068: Add test using chaos plugin to detect local DNS endpoint preference.
  test/extended/dns/dns.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#27594 Filter out dropped targets to minimize the size of target api result
  test/extended/prometheus/prometheus.go
  test/extended/prometheus/storage.go
  test/extended/util/prometheus/helpers.go
Labels: approved, lgtm

#27622 Update ETCD storage data for k8s 1.26
  test/extended/etcd/etcd_storage_path.go
Labels: approved, lgtm
