Repository openshift/origin, pull requests merged in 2022-11, with the labels that each got.

#27486 Write test failure summary, and add new command to request failure risk analysis from sippy.
  cmd/openshift-tests/openshift-tests.go
  pkg/riskanalysis/cmd.go
  pkg/riskanalysis/types.go
  pkg/riskanalysis/write_test_failure_summary.go
  pkg/test/ginkgo/cmd_runsuite.go
  pkg/test/ginkgo/cmd_runtest.go
  pkg/test/ginkgo/junit.go
  pkg/test/ginkgo/options_monitor_events.go
Labels: approved, lgtm

#27509 only print the timeline into artifact dir to reduce noise
  pkg/test/ginkgo/cmd_runsuite.go
Labels: approved, lgtm

#27514 Add more resource to watch
  pkg/monitor/resourcewatch/cmd/resourcewatch.go
  pkg/monitor/resourcewatch/controller/clusteroperatormetric/controller.go
  pkg/monitor/resourcewatch/controller/configmonitor/crd_controller.go
  pkg/monitor/resourcewatch/operator/starter.go
  pkg/monitor/resourcewatch/storage/git_store.go
Labels: approved, lgtm

#27405 Add bond cni test
  go.mod
  go.sum
  test/extended/networking/bonds.go
  test/extended/networking/util.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  vendor/github.com/emicklei/go-restful/.gitignore
  vendor/github.com/emicklei/go-restful/CHANGES.md
  vendor/github.com/emicklei/go-restful/README.md
  vendor/github.com/emicklei/go-restful/container.go
  vendor/github.com/emicklei/go-restful/curly.go
  vendor/github.com/emicklei/go-restful/custom_verb.go
  vendor/github.com/emicklei/go-restful/path_processor.go
  vendor/github.com/emicklei/go-restful/route.go
  vendor/github.com/emicklei/go-restful/web_service.go
  vendor/github.com/fsnotify/fsnotify/.mailmap
  vendor/github.com/fsnotify/fsnotify/.travis.yml
  vendor/github.com/fsnotify/fsnotify/AUTHORS
  vendor/github.com/fsnotify/fsnotify/CHANGELOG.md
  vendor/github.com/fsnotify/fsnotify/README.md
  vendor/github.com/fsnotify/fsnotify/fen.go
  vendor/github.com/fsnotify/fsnotify/fsnotify.go
  vendor/github.com/fsnotify/fsnotify/inotify.go
  vendor/github.com/fsnotify/fsnotify/inotify_poller.go
  vendor/github.com/fsnotify/fsnotify/kqueue.go
  vendor/github.com/fsnotify/fsnotify/open_mode_bsd.go
  vendor/github.com/fsnotify/fsnotify/open_mode_darwin.go
  vendor/github.com/fsnotify/fsnotify/windows.go
  vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/LICENSE
  vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/apis/k8s.cni.cncf.io/register.go
  vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/apis/k8s.cni.cncf.io/v1/doc.go
  vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/apis/k8s.cni.cncf.io/v1/register.go
  vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/apis/k8s.cni.cncf.io/v1/types.go
  vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/apis/k8s.cni.cncf.io/v1/zz_generated.deepcopy.go
  vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/client/clientset/versioned/clientset.go
  vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/client/clientset/versioned/doc.go
  vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/client/clientset/versioned/scheme/doc.go
  vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/client/clientset/versioned/scheme/register.go
  vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/client/clientset/versioned/typed/k8s.cni.cncf.io/v1/doc.go
  vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/client/clientset/versioned/typed/k8s.cni.cncf.io/v1/generated_expansion.go
  vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/client/clientset/versioned/typed/k8s.cni.cncf.io/v1/k8s.cni.cncf.io_client.go
  vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/client/clientset/versioned/typed/k8s.cni.cncf.io/v1/networkattachmentdefinition.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update

#27515 Store monitor events in artifact directory at the end of run monitor
  cmd/openshift-tests/openshift-tests.go
  pkg/monitor/cmd.go
Labels: approved, lgtm

#27516 refactor how tests are run
  pkg/test/ginkgo/cmd_runsuite.go
  pkg/test/ginkgo/group_filter.go
  pkg/test/ginkgo/junit.go
  pkg/test/ginkgo/queue.go
  pkg/test/ginkgo/queue_test.go
  pkg/test/ginkgo/status.go
  pkg/test/ginkgo/test.go
  pkg/test/ginkgo/testNames.txt
  pkg/test/ginkgo/test_runner.go
Labels: approved, lgtm

#27525 OCPBUGS-3282: Fix apigroup tag missing closing brace.
  test/extended/scheduling/pods.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug

#27528 Set Jakub as a Test Platform team lead
  OWNERS_ALIASES
Labels: approved, lgtm

#27532 [release-4.12] Update annotations to account for removal of duplicate whitespace
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm

#27464 Unrevert etcd vertical scaling test
  cmd/openshift-tests/e2e.go
  test/extended/etcd/helpers/helpers.go
  test/extended/etcd/vertical_scaling.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, vendor-update

#27483 ignore kubepodnotready alerts firing when it happens during node upgrade
  pkg/monitor/monitorapi/identification.go
  pkg/monitor/monitorapi/types.go
  pkg/synthetictests/allowedalerts/basic_alert.go
Labels: approved, lgtm

#27487 move alerting tests into invariants only
  pkg/synthetictests/allowedalerts/basic_alert.go
  test/extended/prometheus/alerts.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#27537 OCPBUGS-3428: Skip broken [sig-devex][Feature:ImageEcosystem] tests
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-important

#27404 USHIFT-346: MicroShift: skip sig-auth tests
  test/extended/authorization/podsecurity_admission.go
  test/extended/authorization/scopes.go
  test/extended/oauth/client_secret.go
  test/extended/oauth/expiration.go
  test/extended/oauth/http1.go
  test/extended/oauth/server_headers.go
  test/extended/oauth/token.go
  test/extended/project/project.go
  test/extended/security/scc.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/client.go
  test/extended/util/oauthserver/oauthserver.go
Labels: approved, lgtm

#27427 OWNERS_ALIASES: update list of team leads
  OWNERS_ALIASES
Labels: approved, lgtm

#27454 Trt 579 http2 connection lost
  pkg/monitor/intervalcreation/node.go
  pkg/monitor/intervalcreation/node_test.go
  pkg/synthetictests/event_junits.go
  pkg/synthetictests/kubelet.go
Labels: approved, lgtm

#27508 Add test risk analysis html for spyglass
  e2echart/test-risk-analysis.html
  pkg/riskanalysis/cmd.go
  test/extended/testdata/bindata.go
Labels: approved, lgtm

#27540 USHIFT-345 USHIFT-348 USHIFT-355: API Groups for cli, arch & network
  test/extended/apiserver/api_requests.go
  test/extended/cli/admin.go
  test/extended/cli/apiresources.go
  test/extended/cli/basics.go
  test/extended/cli/compat.go
  test/extended/cli/explain.go
  test/extended/cli/observe.go
  test/extended/cli/probe.go
  test/extended/cli/rsh.go
  test/extended/idling/idling.go
  test/extended/networking/multus.go
  test/extended/networking/services.go
  test/extended/networking/tuning.go
  test/extended/networking/whereabouts.go
  test/extended/operators/clusteroperators.go
  test/extended/operators/images.go
  test/extended/security/scc.go
  test/extended/testdata/bindata.go
  test/extended/testdata/cli/pod-with-two-containers.yaml
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
  test/extended/util/client.go
  test/extended/util/framework.go
Labels: approved, lgtm

#27538 OCPBUGSM-35025: reenable unidling ci tests
  test/extended/idling/idling.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm

#27539 Separate out more tests from 'events should not repeat pathologically' test
  pkg/synthetictests/apiserver.go
  pkg/synthetictests/duplicated_events.go
  pkg/synthetictests/event_junits.go
  pkg/synthetictests/kubelet.go
  pkg/synthetictests/node.go
Labels: approved, lgtm

#27510 cosmetic fix for bad disruption substitution
  pkg/synthetictests/disruption.go
Labels: approved, lgtm

#27476 Drop template.openshift.io apigroup dependency
  test/extended/router/certs.go
  test/extended/router/config_manager.go
  test/extended/router/grpc-interop.go
  test/extended/router/h2spec.go
  test/extended/router/http2.go
  test/extended/router/idle.go
  test/extended/router/scoped.go
  test/extended/router/shard/shard.go
  test/extended/router/unprivileged.go
  test/extended/router/weighted.go
  test/extended/testdata/bindata.go
  test/extended/testdata/router/router-common.yaml
  test/extended/testdata/router/router-config-manager.yaml
  test/extended/testdata/router/router-grpc-interop-routes.yaml
  test/extended/testdata/router/router-grpc-interop.yaml
  test/extended/testdata/router/router-h2spec-routes.yaml
  test/extended/testdata/router/router-h2spec.yaml
  test/extended/testdata/router/router-http2-routes.yaml
  test/extended/testdata/router/router-http2.yaml
  test/extended/testdata/router/router-idle.yaml
  test/extended/testdata/router/router-override-domains.yaml
  test/extended/testdata/router/router-override.yaml
  test/extended/testdata/router/router-scoped.yaml
  test/extended/testdata/router/router-shard.yaml
  test/extended/testdata/router/weighted-router.yaml
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm, tide/merge-method-squash

#27547 OCPBUGS-3633: Revert "Merge pull request #27533 from dgoodwin/merge-alert-backstops"
  pkg/alerts/allowed_conformance.go
  pkg/alerts/allowed_upgrade.go
  pkg/alerts/check.go
  test/e2e/upgrade/alert/alert.go
  test/extended/operators/images.go
  test/extended/operators/operators.go
  test/extended/prometheus/prometheus.go
  test/extended/util/conditions.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug

#27544 make command errors easier to read
  test/extended/util/client.go
Labels: approved, lgtm

#27546 OCPBUGS-3694: [4.12] Drop template.openshift.io apigroup dependency
  test/extended/router/certs.go
  test/extended/router/config_manager.go
  test/extended/router/grpc-interop.go
  test/extended/router/h2spec.go
  test/extended/router/http2.go
  test/extended/router/idle.go
  test/extended/router/scoped.go
  test/extended/router/shard/shard.go
  test/extended/router/unprivileged.go
  test/extended/router/weighted.go
  test/extended/testdata/bindata.go
  test/extended/testdata/router/router-common.yaml
  test/extended/testdata/router/router-config-manager.yaml
  test/extended/testdata/router/router-grpc-interop-routes.yaml
  test/extended/testdata/router/router-grpc-interop.yaml
  test/extended/testdata/router/router-h2spec-routes.yaml
  test/extended/testdata/router/router-h2spec.yaml
  test/extended/testdata/router/router-http2-routes.yaml
  test/extended/testdata/router/router-http2.yaml
  test/extended/testdata/router/router-idle.yaml
  test/extended/testdata/router/router-override-domains.yaml
  test/extended/testdata/router/router-override.yaml
  test/extended/testdata/router/router-scoped.yaml
  test/extended/testdata/router/router-shard.yaml
  test/extended/testdata/router/weighted-router.yaml
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm, tide/merge-method-squash, bugzilla/valid-bug, jira/valid-bug

#27551 Nginx 1.18 images will reach EOL in November 2022
  test/extended/image_ecosystem/s2i_images.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, ok-to-test

#27553 OCPBUGS-3633: Fix flake reporting for certain tests.
  pkg/test/ginkgo/cmd_runsuite.go
  pkg/test/ginkgo/junit.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug

#27473 disruption checking is disabled for prior releases because we lack a …
  pkg/synthetictests/event_junits.go
  test/extended/util/disruption/disruption.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed

#27559 Flake and improve alert tests
  pkg/alerts/allowed_conformance.go
  pkg/alerts/allowed_upgrade.go
  pkg/alerts/check.go
  test/e2e/upgrade/alert/alert.go
  test/extended/operators/images.go
  test/extended/operators/operators.go
  test/extended/prometheus/prometheus.go
  test/extended/util/conditions.go
Labels: approved, lgtm

#27534 Bug 2093339: Reenable data source test
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#27435 Add Kuryr exception to "pods should successfully create sandboxes" test
  pkg/synthetictests/networking.go
Labels: approved, lgtm

#27568 Fix risk analysis html to link to correct release and show bug keys
  e2echart/test-risk-analysis.html
  test/extended/testdata/bindata.go
Labels: approved, lgtm

#27495 Remove unused cmd tests
  test/extended/cmd/cmd.go
  test/extended/testdata/bindata.go
  test/extended/testdata/cmd/test/cmd/login.sh
  test/extended/testdata/cmd/test/cmd/migrate.sh
  test/extended/testdata/cmd/test/cmd/newapp.sh
  test/extended/testdata/cmd/test/cmd/policy.sh
  test/extended/testdata/cmd/test/cmd/registry.sh
Labels: approved, lgtm

#27564 Introduce timeout for sippy risk analysis; add retries with backoff; add dated logging
  pkg/riskanalysis/cmd.go
Labels: approved, lgtm

#27447 Test tuning cni whitelist update
  test/extended/networking/tuning.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#27542 Add separate tests for QPS exceeded and manifest unknown
  pkg/synthetictests/event_junits.go
  pkg/synthetictests/kubelet.go
Labels: approved, lgtm

#27554 OCPBUGS-3819: Add bond cni test
  go.mod
  go.sum
  test/extended/networking/bonds.go
  test/extended/networking/util.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  vendor/github.com/emicklei/go-restful/.gitignore
  vendor/github.com/emicklei/go-restful/CHANGES.md
  vendor/github.com/emicklei/go-restful/README.md
  vendor/github.com/emicklei/go-restful/container.go
  vendor/github.com/emicklei/go-restful/curly.go
  vendor/github.com/emicklei/go-restful/custom_verb.go
  vendor/github.com/emicklei/go-restful/path_processor.go
  vendor/github.com/emicklei/go-restful/route.go
  vendor/github.com/emicklei/go-restful/web_service.go
  vendor/github.com/fsnotify/fsnotify/.mailmap
  vendor/github.com/fsnotify/fsnotify/.travis.yml
  vendor/github.com/fsnotify/fsnotify/AUTHORS
  vendor/github.com/fsnotify/fsnotify/CHANGELOG.md
  vendor/github.com/fsnotify/fsnotify/README.md
  vendor/github.com/fsnotify/fsnotify/fen.go
  vendor/github.com/fsnotify/fsnotify/fsnotify.go
  vendor/github.com/fsnotify/fsnotify/go.mod
  vendor/github.com/fsnotify/fsnotify/go.sum
  vendor/github.com/fsnotify/fsnotify/inotify.go
  vendor/github.com/fsnotify/fsnotify/inotify_poller.go
  vendor/github.com/fsnotify/fsnotify/kqueue.go
  vendor/github.com/fsnotify/fsnotify/open_mode_bsd.go
  vendor/github.com/fsnotify/fsnotify/open_mode_darwin.go
  vendor/github.com/fsnotify/fsnotify/windows.go
  vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/LICENSE
  vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/apis/k8s.cni.cncf.io/register.go
  vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/apis/k8s.cni.cncf.io/v1/doc.go
  vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/apis/k8s.cni.cncf.io/v1/register.go
  vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/apis/k8s.cni.cncf.io/v1/types.go
  vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/apis/k8s.cni.cncf.io/v1/zz_generated.deepcopy.go
  vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/client/clientset/versioned/clientset.go
  vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/client/clientset/versioned/doc.go
  vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/client/clientset/versioned/scheme/doc.go
  vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/client/clientset/versioned/scheme/register.go
  vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/client/clientset/versioned/typed/k8s.cni.cncf.io/v1/doc.go
  vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/client/clientset/versioned/typed/k8s.cni.cncf.io/v1/generated_expansion.go
  vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/client/clientset/versioned/typed/k8s.cni.cncf.io/v1/k8s.cni.cncf.io_client.go
  vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/client/clientset/versioned/typed/k8s.cni.cncf.io/v1/networkattachmentdefinition.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#27562 TRT-691: use duplicateEventThreshold for ProbeTests
  pkg/synthetictests/apiserver.go
  pkg/synthetictests/duplicated_events.go
  pkg/synthetictests/duplicated_events_special.go
  pkg/synthetictests/duplicated_events_test.go
  pkg/synthetictests/kubelet.go
  pkg/synthetictests/node.go
Labels: approved, lgtm

#27580 OCPBUGS-2991: Bump openshift/kubernetes to latest master v2
  go.mod
  go.sum
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccadmission/admission.go
  vendor/github.com/openshift/library-go/pkg/config/serving/server.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/crypto/OWNERS
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go
  vendor/github.com/openshift/library-go/pkg/template/templateprocessingclient/dynamic_process.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/logs/logs.go
  vendor/k8s.io/kubernetes/test/e2e/storage/testsuites/ephemeral.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, jira/valid-bug, jira/severity-important
