Repository openshift/origin, pull requests merged in 2022-03, with the labels that each got.

#26863 Bug 2059277: images/tests: yum update python3-six to workaround ART issue
  images/tests/Dockerfile.rhel
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#26867 Switch to batch/v1 CronJob
  test/extended/images/resolve.go
Labels: approved, lgtm

#26864 Bug 2059299: IBMCloud: Ignore CRB already exists
  test/extended/util/ibmcloud/provider.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#26858 Make a test to specifically look for image pull backoff for registry.redhat.io
  pkg/synthetictests/duplicated_events.go
  pkg/synthetictests/event_junits.go
  pkg/synthetictests/image_pulls.go
  pkg/synthetictests/image_pulls_test.go
Labels: approved, lgtm

#26876 cleanup network policy ACL extended test
  test/extended/networking/acl_audit_log.go
Labels: approved, lgtm

#26873 Use common threshold constant as other event tests
  pkg/synthetictests/image_pulls.go
Labels: approved, lgtm

#26877 bug 2060406: operators should not create watch channels very often: bump OpenStack monitoring operator
  test/extended/apiserver/api_requests.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#26880 Bug 2060498: only add failure when no event was found for the target revision
  pkg/synthetictests/static_pod.go
  pkg/synthetictests/static_pod_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#26868 MGMT-9440: Fix single node serial tests API crash.
  test/extended/apiserver/resiliency.go
Labels: approved, lgtm

#26884 Bug 2057990: Add debug info for signature test
  test/extended/images/signatures.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#26885 Bug 2026063: build-quota test: fix cgroupv2 parsing holes exposed by buildah upgrade
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/build-quota/.s2i/bin/assemble
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#26797 Revert "Disable intree vsphere tests"
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm

#26795 Bug 1961233: Add DNS availability upgrade test
  test/e2e/upgrade/dns/dns.go
  test/e2e/upgrade/upgrade.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#26897 Mark image pull from registry.redhat.io as flake to track but not fail
  pkg/synthetictests/image_pulls.go
Labels: approved, lgtm

#26896 Give each interval chart a title
  e2echart/e2e-chart-template.html
  pkg/monitor/intervalcreation/rendering.go
  test/extended/testdata/bindata.go
Labels: approved, lgtm

#26899 Add early test to check router pods are not on same node
  test/extended/include.go
  test/extended/scheduling/pods.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#26906 Pod scheduling tests improve pod deployment identification
  test/extended/scheduling/pods.go
Labels: approved, lgtm

#26909 Migrate builds tests away from using sample imagestreams since samples will be optional
  test/extended/builds/build_pruning.go
  test/extended/builds/clone_git_protocol.go
  test/extended/builds/new_app.go
  test/extended/builds/service.go
  test/extended/builds/valuefrom.go
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/build-pruning/default-group-build-config.yaml
  test/extended/testdata/builds/build-pruning/default-legacy-build-config.yaml
  test/extended/testdata/builds/build-pruning/errored-build-config.yaml
  test/extended/testdata/builds/build-pruning/failed-build-config.yaml
  test/extended/testdata/cmd/test/cmd/deployments.sh
  test/extended/testdata/cmd/test/cmd/testdata/application-template-dockerbuild.json
Labels: approved, lgtm

#26695 Bug 2034688: allow Prometheus/Thanos to return 401 or 403 when the request isn't authenticated
  test/extended/prometheus/prometheus.go
  test/extended/util/prometheus/helpers.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#26922 Bug 2058086: Add item length check in legacyPrinterToTable
  pkg/oc/cli/admin/buildchain/test/multiple-namespaces-bcs.yaml
  pkg/oc/cli/admin/buildchain/test/single-namespace-bcs.yaml
  pkg/oc/lib/graph/genericgraph/test/new-project-deployed-app.yaml
  test/cmd/env.sh
  test/common/build/controllers.go
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/test-build-revision.json
  test/extended/testdata/builds/test-build.yaml
  test/extended/testdata/long_names/fixture.json
  test/extended/testdata/run_policy/parallel-bc.yaml
  test/extended/testdata/run_policy/serial-bc.yaml
  test/extended/testdata/run_policy/serial-latest-only-bc.yaml
  test/integration/imagechange_buildtrigger_test.go
  test/integration/master_routes_test.go
  test/integration/newapp_test.go
  test/integration/testdata/test-buildcli-beta2.json
  test/integration/testdata/test-buildcli.json
  test/old-start-configs/v1.0.0/examples/sample-app/application-template-custombuild.json
  test/old-start-configs/v1.0.0/examples/sample-app/application-template-dockerbuild.json
  test/old-start-configs/v1.0.0/examples/sample-app/application-template-stibuild.json
  test/testdata/app-scenarios/new-project-deployed-app.yaml
  test/testdata/failing-bc.json
  test/testdata/test-bc.yaml
  vendor/k8s.io/kubernetes/pkg/printers/humanreadable.go
Labels: lgtm, bugzilla/valid-bug, bugzilla/severity-high

#26924 Simplify 26907
  pkg/synthetictests/duplicated_events.go
  pkg/synthetictests/event_junits.go
  pkg/synthetictests/networking.go
Labels: approved, lgtm

#26916 Attempt multiple different token requests
  test/extended/oauth/client_secret.go
Labels: approved, lgtm

#26914 JKNS-267: minimize jenkins e2es (pipeline strategy verification only)
  test/extended/builds/pipeline_jenkins_e2e.go
  test/extended/builds/pipeline_origin_bld.go
  test/extended/builds/pipeline_origin_bld_rhelimagesonly.go
  test/extended/builds/run_policy.go
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/simple-pipeline-bc.yaml
  test/extended/testdata/config-map-jenkins-slave-pods.yaml
  test/extended/testdata/imagestream-jenkins-slave-pods.yaml
  test/extended/testdata/imagestreamtag-jenkins-slave-pods.yaml
  test/extended/testdata/jenkins-plugin/build-job-clone.xml
  test/extended/testdata/jenkins-plugin/build-job-slave.xml
  test/extended/testdata/jenkins-plugin/build-job.xml
  test/extended/testdata/jenkins-plugin/build-with-env-job.xml
  test/extended/testdata/jenkins-plugin/build-with-exec-steps.xml
  test/extended/testdata/jenkins-plugin/create-job.xml
  test/extended/testdata/jenkins-plugin/delete-job-keys.xml
  test/extended/testdata/jenkins-plugin/delete-job-labels.xml
  test/extended/testdata/jenkins-plugin/delete-job.xml
  test/extended/testdata/jenkins-plugin/imagestream-scm-dsl-job.xml
  test/extended/testdata/jenkins-plugin/imagestream-scm-job.xml
  test/extended/testdata/jenkins-plugin/multitag-job.xml
  test/extended/testdata/jenkins-plugin/multitag-template.json
  test/extended/testdata/jenkins-plugin/shared-resources-template.json
  test/extended/testdata/jenkins-slave-template.yaml
  test/extended/testdata/openshift-secret-to-jenkins-credential.yaml
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/jenkins/monitor.go
  test/extended/util/jenkins/ref.go
Labels: approved, lgtm

#26862 Attempted fix for missing monitor events.
  pkg/monitor/event.go
Labels: approved, lgtm

#26875 Implementation for egress-router-cni e2e ci test
  test/extended/networking/egress_router_cni.go
  test/extended/testdata/bindata.go
  test/extended/testdata/egress-router-cni/egress-router-cni-v4-cr.yaml
  test/extended/testdata/egress-router-cni/egress-router-cni-v6-cr.yaml
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#26865 Implementation for basic egressfw e2e CI test
  test/extended/networking/egress_firewall.go
  test/extended/networking/util.go
  test/extended/testdata/bindata.go
  test/extended/testdata/egress-firewall/ovnk-egressfirewall-test.yaml
  test/extended/testdata/egress-firewall/sdn-egressnetworkpolicy-test.yaml
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, ok-to-test, e2e-images-update

#26930 Update where the canary test lists is retrieved from
  cmd/openshift-tests/minimal.go
Labels: approved, lgtm

#26931 Revert "Implementation for basic egressfw e2e CI test"
  test/extended/networking/egress_firewall.go
  test/extended/networking/util.go
  test/extended/testdata/bindata.go
  test/extended/testdata/egress-firewall/ovnk-egressfirewall-test.yaml
  test/extended/testdata/egress-firewall/sdn-egressnetworkpolicy-test.yaml
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#26809 Add pod securityContext sysctl whitelist tests
  test/extended/security/sysctl.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#26932 Flake on FailedCreatePodSandbox if missing ovn readiness file.
  pkg/synthetictests/networking.go
Labels: approved, lgtm

#26933 coarse serialization of storage tests
  pkg/test/ginkgo/cmd_runsuite.go
Labels: approved, lgtm

#26912 Clarify that the image mirroring requirement applies to conformance tests only
  test/extended/util/image/README.md
Labels: approved, lgtm, e2e-images-update

#26946 Bug 2055381: cleanup network policy ACL extended test
  test/extended/networking/acl_audit_log.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#26926 Check token response error code
  test/extended/oauth/client_secret.go
Labels: approved, lgtm

#26934 Implementation for basic egressfw e2e CI test
  test/extended/networking/egress_firewall.go
  test/extended/networking/util.go
  test/extended/testdata/bindata.go
  test/extended/testdata/egress-firewall/ovnk-egressfirewall-test.yaml
  test/extended/testdata/egress-firewall/sdn-egressnetworkpolicy-test.yaml
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#26941 Bug 1996883: Increasing log level to support decrease in default buildah log level
  test/extended/builds/multistage.go
  test/extended/builds/optimized.go
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/build-postcommit/sti.yaml
  test/extended/testdata/builds/build-pruning/errored-build-config.yaml
  test/extended/testdata/builds/build-pruning/failed-build-config.yaml
  test/extended/testdata/builds/build-pruning/successful-build-config.yaml
  test/extended/testdata/builds/pullsecret/linked-nodejs-bc.yaml
  test/extended/testdata/builds/statusfail-badcontextdirs2i.yaml
  test/extended/testdata/builds/statusfail-fetchsourcedocker.yaml
  test/extended/testdata/builds/statusfail-fetchsources2i.yaml
  test/extended/testdata/builds/statusfail-genericreason.yaml
  test/extended/testdata/builds/statusfail-oomkilled.yaml
  test/extended/testdata/builds/statusfail-postcommithook.yaml
  test/extended/testdata/builds/statusfail-pushtoregistry.yaml
  test/extended/testdata/builds/test-bc-with-pr-ref.yaml
  test/extended/testdata/builds/test-build-proxy.yaml
  test/extended/testdata/builds/test-build-revision.json
  test/extended/testdata/builds/test-build.yaml
  test/extended/testdata/builds/test-buildconfigsecretinjector.yaml
  test/extended/testdata/builds/test-cds-dockerbuild.json
  test/extended/testdata/builds/test-cds-sourcebuild.json
  test/extended/testdata/builds/test-custom-build.yaml
  test/extended/testdata/builds/test-docker-build-pullsecret.json
  test/extended/testdata/builds/test-docker-build.json
  test/extended/testdata/builds/test-env-build.json
  test/extended/testdata/builds/test-imagechangetriggers.yaml
  test/extended/testdata/builds/test-imagesource-buildconfig.yaml
  test/extended/testdata/builds/test-nosrc-build.json
  test/extended/testdata/builds/test-symlink-build.yaml
  test/extended/testdata/builds/volumes/csi-s2i-buildconfig.yaml
  test/extended/testdata/builds/volumes/s2i-buildconfig.yaml
  test/extended/testdata/signer-buildconfig.yaml
  test/extended/testdata/test-buildcli.json
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#26947 Bug 2055380: cleanup network policy ACL extended test
  test/extended/networking/acl_audit_log.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#26950 Fix typo in OVN Kubernetes skipper
  test/extended/networking/util.go
Labels: approved, lgtm

#26956 Use ServerGroupResources instead deprecated ServerResources
  test/extended/authorization/authorization.go
  test/extended/etcd/etcd_storage_path.go
Labels: approved, lgtm

#26958 Bug 1996883: increasing build config loglevel
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/volumes/csi-without-rr-s2i-buildconfig.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low
