Repository openshift/origin, pull requests merged in 2023-10, with the labels that each got.

#28270 OCPBUGS-18527: Ignore timeout and connection refused errors during upgrade tests for 4.12
  pkg/synthetictests/duplicated_events.go
  pkg/synthetictests/duplicated_events_test.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#28247 OCPBUGS-18129: Ignore timeout and connection refused errors during upgrade tests for 4.11
  pkg/synthetictests/duplicated_events.go
  pkg/synthetictests/duplicated_events_test.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#28295 Automating test "check the quota after import-image with --all option" in upstrem
  test/extended/quota/resourcequota.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#28292 OPNET-330: fix DualStackIPv6Primary
  pkg/clioptions/clusterdiscovery/cluster.go
  pkg/clioptions/clusterdiscovery/provider.go
  pkg/clioptions/clusterdiscovery/provider_test.go
Labels: approved, lgtm, jira/valid-reference

#28298 Remove bug-related annotations
  test/extended/util/annotate/rules.go
Labels: approved, lgtm

#28293 Fix bug with disable-monitor
  pkg/cmd/openshift-tests/monitor/run/run_monitor_command.go
Labels: approved, lgtm

#28294 Limit intervals to the current phase (addresses loki upload problems)
  pkg/monitor/monitor.go
Labels: approved, lgtm

#28304 OCPBUGS-20308: Backport PR 28295 and 28238
  test/extended/quota/resourcequota.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#28308 test/extended: Consolidate hard-coded local image registry dependencies
  test/extended/cli/basics.go
  test/extended/cli/status.go
  test/extended/deployments/deployments.go
  test/extended/etcd/etcd_storage_path.go
  test/extended/images/trigger/annotation.go
  test/extended/router/idle.go
  test/extended/util/image/image.go
Labels: approved, lgtm, e2e-images-update

#28309 trt-1271: add risk analysis for monitor junit suites
  pkg/clioptions/clusterinfo/api.go
  pkg/clioptions/clusterinfo/write_job_run_data.go
  pkg/cmd/openshift-tests/monitor/run/run_monitor_command.go
  pkg/cmd/openshift-tests/run-disruption/disruption.go
  pkg/monitor/monitor.go
  pkg/monitortests/node/legacynodemonitortests/updates.go
  pkg/monitortests/testframework/clusterinfoserializer/monitortest.go
  pkg/resourcewatch/operator/starter.go
  pkg/riskanalysis/write_test_failure_summary.go
  pkg/test/ginkgo/cmd_runsuite.go
  pkg/test/ginkgo/cmd_runtest.go
  test/extended/util/disruption/disruption.go
Labels: approved, lgtm, jira/valid-reference

#28315 SDN-4062: Revert "SDN-4042: Increase total upgrade time on OVN platforms"
  test/e2e/upgrade/upgrade.go
Labels: approved, lgtm, jira/valid-reference

#28316 fix for OCP-11594 to skipped on disconnected env
  test/extended/quota/resourcequota.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#28312 hs, kubevirt: Wait node readiness before migration
  test/extended/kubevirt/migration.go
  test/extended/kubevirt/util.go
Labels: approved, lgtm

#28239 OCPBUGS-18490: bump monitoring SNO bounds
  test/extended/apiserver/api_requests.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-low, jira/valid-reference

#28322 test/extended/images: update OWNERS
  test/extended/images/OWNERS
Labels: approved, lgtm

#28324 Bump watch requests for cluster-baremetal-operator
  test/extended/apiserver/api_requests.go
Labels: approved, lgtm

#28306 pkg/monitortests/clusterversionoperator/legacycvomonitortests: Structured condition types
  pkg/monitortests/clusterversionoperator/legacycvomonitortests/operators.go
Labels: approved, lgtm

#28233 OCPBUGS-20024: Revert "OCPBUGS-13366: ignore repeated TopologyAwareHintsDisabled events"
  pkg/monitortestlibrary/pathologicaleventlibrary/duplicated_event_patterns.go
  pkg/monitortests/testframework/watchevents/event_test.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#28307 OCPBUGS-20205: feat: added support for ImageRegistry capability
  pkg/clioptions/clusterdiscovery/provider.go
  pkg/monitortests/network/disruptionpodnetwork/monitortest.go
  test/extended/cli/debug.go
  test/extended/images/extract.go
  test/extended/images/resolve.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
  test/extended/util/framework.go
  test/extended/util/image/image.go
Labels: approved, lgtm, e2e-images-update, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#28311 Add debug info for interval counts and times
  pkg/monitor/monitor.go
  pkg/monitortestframework/impl.go
  pkg/monitortests/testframework/uploadtolokiserializer/monitortest.go
Labels: approved, lgtm

#28302 OCPVE-723: Add optional olm fixes
  go.mod
  go.sum
  test/extended/cli/explain.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
  vendor/github.com/openshift/api/.gitignore
  vendor/github.com/openshift/api/Dockerfile.rhel8
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/annotations/annotations.go
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_image.crd.yaml
  vendor/github.com/openshift/api/config/v1/stable.clusterversion.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/helm/v1beta1/00_helm-chart-repository.crd.yaml
  vendor/github.com/openshift/api/helm/v1beta1/00_project-helm-chart-repository.crd.yaml
  vendor/github.com/openshift/api/helm/v1beta1/stable.helmchartrepository.testsuite.yaml
  vendor/github.com/openshift/api/helm/v1beta1/stable.projecthelmchartrepository.testsuite.yaml
  vendor/github.com/openshift/api/kubecontrolplane/v1/types.go
  vendor/github.com/openshift/api/kubecontrolplane/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/legacyconfig/v1/types.go
  vendor/github.com/openshift/api/legacyconfig/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/types.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_80_machine-config-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/register.go
  vendor/github.com/openshift/api/operator/v1/stable.machineconfiguration.testsuite.yaml
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/types_machineconfiguration.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, jira/valid-reference

#28326 Remove some redundant monitor tests
  pkg/monitortests/network/legacynetworkmonitortests/monitortest.go
Labels: approved, lgtm

#28329 fix: wrap InitializeReleasePullSpecString in check for HasNoOptionalCapabilities
  pkg/clioptions/clusterdiscovery/provider.go
Labels: approved, lgtm

#28331 Extract the cluster operator name from Down/Degraded Alerts
  pkg/monitor/monitorapi/construction.go
  pkg/monitortests/testframework/alertanalyzer/alerts.go
Labels: approved, lgtm

#28299 Port Node and Pod State to Structured Intervals
  pkg/monitor/monitorapi/construction.go
  pkg/monitor/monitorapi/identification_pod.go
  pkg/monitor/monitorapi/types.go
  pkg/monitor/monitorapi/types_test.go
  pkg/monitor/serialization/serialize.go
  pkg/monitortestlibrary/statetracker/state_tracker.go
  pkg/monitortests/node/kubeletlogcollector/node.go
  pkg/monitortests/node/nodestateanalyzer/node.go
  pkg/monitortests/node/nodestateanalyzer/nodeTest/drain-01/expected.json
  pkg/monitortests/node/nodestateanalyzer/nodeTest/drain-02/expected.json
  pkg/monitortests/node/watchnodes/node.go
  pkg/monitortests/node/watchpods/collection.go
  pkg/monitortests/node/watchpods/compute_intervals.go
  pkg/monitortests/node/watchpods/monitoring_reflector.go
  pkg/monitortests/node/watchpods/podTest/container-life/expected.json
  pkg/monitortests/node/watchpods/podTest/container-life/startingEvents.json
  pkg/monitortests/node/watchpods/podTest/end-before-begin/expected.json
  pkg/monitortests/node/watchpods/podTest/end-before-begin/startingEvents.json
  pkg/monitortests/node/watchpods/podTest/installer-pod/expected.json
  pkg/monitortests/node/watchpods/podTest/installer-pod/startingEvents.json
  pkg/monitortests/node/watchpods/podTest/long-not-ready/expected.json
  pkg/monitortests/node/watchpods/podTest/long-not-ready/startingEvents.json
  pkg/monitortests/node/watchpods/podTest/run-once-done/expected.json
  pkg/monitortests/node/watchpods/podTest/run-once-done/startingEvents.json
  pkg/monitortests/node/watchpods/podTest/simple/expected.json
  pkg/monitortests/node/watchpods/podTest/simple/startingEvents.json
  pkg/monitortests/node/watchpods/podTest/trailing-ready-2/expected.json
  pkg/monitortests/node/watchpods/podTest/trailing-ready-2/startingEvents.json
  pkg/monitortests/node/watchpods/podTest/trailing-ready/expected.json
  pkg/monitortests/node/watchpods/podTest/trailing-ready/startingEvents.json
Labels: approved, lgtm

#28301 OCPBUGS-9037: Require http 1.1 or earlier when using curl
  test/extended/util/url/url.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#28267 OCPBUGS-19378: [4.13] backport etcd restore tests
  cmd/openshift-tests/e2e.go
  go.mod
  test/extended/dr/OWNERS
  test/extended/dr/backup_restore.go
  test/extended/dr/common.go
  test/extended/dr/force_redeploy.go
  test/extended/dr/machine_recover.go
  test/extended/dr/quorum_restore.go
  test/extended/dr/recovery.go
  test/extended/dr/resource_assertions.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  vendor/k8s.io/kubernetes/test/e2e/upgrades/network/kube_proxy_migration.go
  vendor/k8s.io/kubernetes/test/e2e/upgrades/network/services.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#28336 prune the system CAs from proxy-ca in rawTLSInfo json
  test/extended/operators/certs.go
Labels: approved, lgtm

#28332 Improvements and Additions to Alert Testing Stack
  pkg/alerts/check.go
  pkg/cmd/openshift-tests/dev/dev.go
  pkg/cmd/openshift-tests/monitor/timeline/timeline_command.go
  pkg/disruption/backend/sampler/remote.go
  pkg/monitor/monitorapi/types.go
  pkg/monitor/serialization/serialize.go
  pkg/monitortestlibrary/allowedalerts/basic_alert.go
  pkg/monitortestlibrary/allowedalerts/matches.go
  pkg/monitortestlibrary/allowedalerts/matches_test.go
  pkg/monitortestlibrary/allowedalerts/types.go
  pkg/monitortestlibrary/historicaldata/alert_types.go
  pkg/monitortestlibrary/historicaldata/disruption_types.go
  pkg/monitortests/node/nodestateanalyzer/node_test.go
  pkg/monitortests/node/watchpods/compute_intervals_test.go
  pkg/monitortests/testframework/alertanalyzer/alerts.go
  pkg/monitortests/testframework/legacytestframeworkmonitortests/alerts.go
  pkg/monitortests/testframework/legacytestframeworkmonitortests/alerts_test.go
  pkg/monitortests/testframework/timelineserializer/rendering.go
  pkg/monitortests/testframework/timelineserializer/rendering_test.go
  test/e2e/upgrade/alert/alert.go
  test/e2e/upgrade/upgrade.go
  test/extended/prometheus/prometheus.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/prometheus/helpers.go
Labels: approved, lgtm, vendor-update

#28341 Port remaining clusteroperator monitor intervals to structured
  pkg/monitor/monitorapi/construction.go
  pkg/monitor/monitorapi/types.go
  pkg/monitortests/testframework/watchclusteroperators/operator.go
Labels: approved, lgtm

#28343 trt-1320: update trt approvers
  OWNERS
Labels: approved, lgtm, jira/valid-reference

#28349 Restore Node NotReady intervals
  e2echart/e2e-chart-template.html
  e2echart/non-spyglass-e2e-chart-template.html
  test/extended/testdata/bindata.go
Labels: approved, lgtm

#28235 [release-4.11] OCPBUGS-18424: Add missing watch permission for console users
  test/extended/authorization/rbac/groups_default_rules.go
Labels: kind/bug, approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference

#28347 OCPBUGS-22276: Remove all docker.io images due to access denied
  examples/image-streams/image-streams-centos7.json
  test/extended/testdata/bindata.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/valid-reference

#28344 put back previous Interval Slice algorithm
  pkg/monitor/monitorapi/types.go
Labels: approved, lgtm

#28353 OCPBUGS-22358: fix: increase upper bounds for samples operator
  test/extended/apiserver/api_requests.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#28348 Remove timelines command reprocessing intervals
  pkg/cmd/openshift-tests/monitor/timeline/timeline_command.go
Labels: approved, lgtm

#28351 Fix intervals mistakenly showing mass node NotReady
  pkg/monitortests/node/nodestateanalyzer/node.go
Labels: approved, lgtm

#28354 Restore APIServer graceful shutdown windows
  e2echart/e2e-chart-template.html
  pkg/monitor/monitorapi/types.go
  pkg/monitortests/kubeapiserver/apiservergracefulrestart/monitortest.go
  pkg/monitortests/kubeapiserver/apiservergracefulrestart/monitortest_test.go
  test/extended/testdata/bindata.go
Labels: approved, lgtm

#28334 start adding raw tls info
  tls/raw-data/raw-tls-artifacts-ha-amd64-aws-ovn.json
  tls/raw-data/raw-tls-artifacts-ha-amd64-aws-sdn.json
  tls/raw-data/raw-tls-artifacts-ha-amd64-azure-ovn.json
  tls/raw-data/raw-tls-artifacts-ha-amd64-azure-sdn.json
  tls/raw-data/raw-tls-artifacts-ha-amd64-gcp-ovn.json
  tls/raw-data/raw-tls-artifacts-ha-amd64-gcp-sdn.json
  tls/raw-data/raw-tls-artifacts-ha-amd64-metal-ovn.json
  tls/raw-data/raw-tls-artifacts-ha-amd64-metal-sdn.json
  tls/raw-data/raw-tls-artifacts-ha-amd64-vsphere-ovn.json
  tls/raw-data/raw-tls-artifacts-ha-amd64-vsphere-sdn.json
  tls/raw-data/raw-tls-artifacts-single-amd64-aws-ovn.json
Labels: approved, lgtm

#28330 [TRT-1279] Drop not-used pulledInvalidImages method
  pkg/clioptions/imagesetup/images.go
Labels: approved, lgtm

#28359 add hack/update-tls-ownership.sh
  .gitignore
  Makefile
  cmd/update-tls-artifacts/update-tls-artifacts.go
  go.mod
  hack/update-tls-ownership.sh
  hack/verify-tls-ownership.sh
  pkg/cmd/update-tls-artifacts/generate-owners/generate_owners_flags.go
  pkg/cmd/update-tls-artifacts/generate-owners/generate_owners_options.go
  tls/ownership/ownership.md
  tls/ownership/tls-ownership.json
  tls/violations/OWNERS
  tls/violations/README.md
  tls/violations/ownership/ownership-violations.json
  vendor/modules.txt
Labels: approved, lgtm, vendor-update

#28345 Allow the unknown alerts test to fail as it looks stable
  pkg/monitortests/testframework/legacytestframeworkmonitortests/alerts.go
  pkg/monitortests/testframework/legacytestframeworkmonitortests/alerts_test.go
Labels: approved, lgtm

#28357 OCPBUGS-22413: Use Centos 8 Stream mysql image in tests
  examples/image-streams/image-streams-centos7.json
  examples/sample-app/application-template-dockerbuild.json
  examples/sample-app/application-template-pullspecbuild.json
  examples/sample-app/application-template-stibuild.json
  test/extended/testdata/bindata.go
  test/extended/testdata/cmd/test/cmd/deployments.sh
  test/extended/testdata/cmd/test/cmd/testdata/application-template-dockerbuild.json
  test/extended/testdata/cmd/test/cmd/testdata/new-app/template-with-app-label.json
  test/extended/testdata/cmd/test/cmd/testdata/new-app/template-without-app-label.json
Labels: approved, lgtm, e2e-images-update, jira/valid-bug, jira/valid-reference

#28358 Skip FailedScheduling intervals when masters are in NodeUpdate
  pkg/cmd/openshift-tests/monitor/timeline/timeline_command.go
  pkg/monitor/monitorapi/identification_pod.go
  pkg/monitor/monitorapi/types.go
  pkg/monitortestlibrary/pathologicaleventlibrary/duplicated_events.go
  pkg/monitortestlibrary/pathologicaleventlibrary/duplicated_events_test.go
  pkg/monitortestlibrary/statetracker/state_tracker.go
  pkg/monitortests/node/nodestateanalyzer/node.go
  pkg/monitortests/node/nodestateanalyzer/nodeTest/drain-01/expected.json
  pkg/monitortests/node/nodestateanalyzer/nodeTest/drain-02/expected.json
  pkg/monitortests/node/nodestateanalyzer/node_test.go
Labels: approved, lgtm

#28367 Revert "OCPBUGS-22413: Use Centos 8 Stream mysql image in tests"
  examples/image-streams/image-streams-centos7.json
  examples/sample-app/application-template-dockerbuild.json
  examples/sample-app/application-template-pullspecbuild.json
  examples/sample-app/application-template-stibuild.json
  test/extended/testdata/bindata.go
  test/extended/testdata/cmd/test/cmd/deployments.sh
  test/extended/testdata/cmd/test/cmd/testdata/application-template-dockerbuild.json
  test/extended/testdata/cmd/test/cmd/testdata/new-app/template-with-app-label.json
  test/extended/testdata/cmd/test/cmd/testdata/new-app/template-without-app-label.json
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference
