Repository openshift/origin, pull requests merged in 2023-06, with the labels that each got.

#27959 OCPBUGS-14338: test/extended/prometheus: increase telemetry series threshold
  test/extended/prometheus/prometheus.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#27921 ETCD-425: restore test should validate state
  test/extended/dr/common.go
  test/extended/dr/recovery.go
  test/extended/dr/resource_assertions.go
Labels: approved, lgtm, jira/valid-reference

#27946 hard monitor.Event message creation
  pkg/monitor/apiserveravailability/summarizer.go
  pkg/monitor/backenddisruption/disruption_backend_sampler.go
  pkg/monitor/backenddisruption/disruption_locator.go
  pkg/monitor/intervalcreation/node.go
  pkg/monitor/intervalcreation/node_test.go
  pkg/monitor/intervalcreation/pod.go
  pkg/monitor/intervalcreation/podTest/container-life/expected.json
  pkg/monitor/intervalcreation/podTest/end-before-begin/expected.json
  pkg/monitor/intervalcreation/podTest/installer-pod/expected.json
  pkg/monitor/intervalcreation/podTest/long-not-ready/expected.json
  pkg/monitor/intervalcreation/podTest/run-once-done/expected.json
  pkg/monitor/intervalcreation/podTest/simple/expected.json
  pkg/monitor/intervalcreation/podTest/trailing-ready-2/expected.json
  pkg/monitor/intervalcreation/podTest/trailing-ready/expected.json
  pkg/monitor/intervalcreation/rendering_per_namespace.go
  pkg/monitor/monitorapi/identification_pod.go
  pkg/monitor/pod.go
  pkg/monitor/podipcontroller/pod_ip_controller.go
  pkg/synthetictests/disruption.go
  pkg/synthetictests/kubelet.go
  pkg/synthetictests/networking.go
Labels: approved, lgtm

#27964 USHIFT-1300: Avoid getting cluster state for TEST_PROVIDER env var
  pkg/test/ginkgo/test_runner.go
Labels: approved, lgtm, jira/valid-reference

#27930 push intervals to loki
  cmd/openshift-tests/dev.go
  pkg/cmd/monitor_command/run_monitor_command.go
  pkg/monitor/intervalcreation/e2etest.go
  pkg/monitor/loki_upload.go
  pkg/monitor/monitorapi/identification.go
  pkg/test/ginkgo/options_monitor_events.go
Labels: approved, lgtm

#27933 MON-3213: Changing the severity of "missing runbook_url annotation for critical alerts" test case from flaky to failure
  test/extended/prometheus/prometheus.go
Labels: approved, lgtm, jira/valid-reference

#27969 OCPBUGS-14667: Revert "MON-3213: Changing the severity of "missing runbook_url annotation for critical alerts" test case from flaky to failure"
  test/extended/prometheus/prometheus.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#27838 new disruption backend
  cmd/disruption/main.go
  e2echart/e2e-chart-template.html
  pkg/disruption/backend/context.go
  pkg/disruption/backend/core.go
  pkg/disruption/backend/descriptor.go
  pkg/disruption/backend/disruption/handler.go
  pkg/disruption/backend/disruption/interval.go
  pkg/disruption/backend/disruption/interval_test.go
  pkg/disruption/backend/logger/logger.go
  pkg/disruption/backend/reqresp.go
  pkg/disruption/backend/roundtripper/roundtripper.go
  pkg/disruption/backend/roundtripper/roundtripper_test.go
  pkg/disruption/backend/roundtripper/shutdown.go
  pkg/disruption/backend/roundtripper/shutdown_test.go
  pkg/disruption/backend/sampler/interface.go
  pkg/disruption/backend/sampler/knownerror.go
  pkg/disruption/backend/sampler/producer_consumer.go
  pkg/disruption/backend/sampler/producer_consumer_test.go
  pkg/disruption/backend/sampler/requestor.go
  pkg/disruption/backend/sampler/response_checker.go
  pkg/disruption/backend/shutdown.go
  pkg/disruption/backend/shutdown/handler.go
  pkg/disruption/backend/shutdown/interval.go
  pkg/disruption/backend/shutdown/interval_test.go
  pkg/disruption/backend/transport/transport.go
  pkg/disruption/ci/backend_sampler.go
  pkg/disruption/ci/factory.go
  pkg/disruption/ci/factory_test.go
  pkg/disruption/ci/host_decoder.go
  pkg/disruption/sampler/sample.go
  pkg/disruption/sampler/sampler.go
  pkg/disruption/sampler/sampler_test.go
  pkg/monitor/monitorapi/identification.go
  pkg/monitor/write_job_run_data.go
  test/extended/testdata/bindata.go
  test/extended/util/disruption/controlplane/known_backends.go
Labels: approved, lgtm

#27942 Updated pathological events
  pkg/duplicateevents/duplicated_event_patterns.go
  pkg/synthetictests/duplicated_events_special.go
  pkg/synthetictests/duplicated_events_special_test.go
  pkg/synthetictests/event_junits.go
Labels: approved, lgtm

#27974 Update expected name for OVN acl logging test
  test/extended/networking/acl_audit_log.go
Labels: approved, lgtm

#27919 add shutdown interval for apiserver from events
  e2echart/e2e-chart-template.html
  pkg/monitor/api.go
  pkg/monitor/shutdown/consumer.go
  pkg/monitor/shutdown/gatherer.go
  test/extended/testdata/bindata.go
Labels: approved, lgtm

#27970 STOR-1263: Bump (openshift/kubernetes): to get openshift/kubernetes#1595
  go.mod
  go.sum
  vendor/k8s.io/kubernetes/openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  vendor/k8s.io/kubernetes/openshift-hack/e2e/annotate/rules.go
  vendor/k8s.io/kubernetes/openshift-hack/e2e/include.go
  vendor/k8s.io/kubernetes/test/e2e/storage/csi_mock/base.go
  vendor/k8s.io/kubernetes/test/e2e/storage/csi_mock/csi_attach_volume.go
  vendor/k8s.io/kubernetes/test/e2e/storage/csi_mock/csi_fsgroup_mount.go
  vendor/k8s.io/kubernetes/test/e2e/storage/csi_mock/csi_fsgroup_policy.go
  vendor/k8s.io/kubernetes/test/e2e/storage/csi_mock/csi_node_stage_error_cases.go
  vendor/k8s.io/kubernetes/test/e2e/storage/csi_mock/csi_selinux_mount.go
  vendor/k8s.io/kubernetes/test/e2e/storage/csi_mock/csi_service_account_token.go
  vendor/k8s.io/kubernetes/test/e2e/storage/csi_mock/csi_snapshot.go
  vendor/k8s.io/kubernetes/test/e2e/storage/csi_mock/csi_storage_capacity.go
  vendor/k8s.io/kubernetes/test/e2e/storage/csi_mock/csi_volume_expansion.go
  vendor/k8s.io/kubernetes/test/e2e/storage/csi_mock/csi_volume_limit.go
  vendor/k8s.io/kubernetes/test/e2e/storage/csi_mock/csi_workload.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, jira/valid-reference

#27978 Update kubevirt LB connectivity tests to work with AWS ELB
  test/extended/kubevirt/util.go
Labels: approved, lgtm

#27983 Replace dashes in locator keys for upload to loki, add namespace label when possible
  pkg/monitor/loki_upload.go
Labels: approved, lgtm

#27991 Fix panic in loki upload
  pkg/monitor/loki_upload.go
Labels: approved, lgtm

#27972 strip operator framework from resource watch and fix bugs
  pkg/monitor/resourcewatch/cmd/resourcewatch.go
  pkg/monitor/resourcewatch/controller/configmonitor/crd_controller.go
  pkg/monitor/resourcewatch/operator/starter.go
  pkg/monitor/resourcewatch/storage/git_store.go
  vendor/github.com/openshift/library-go/pkg/config/clusterstatus/clusterstatus.go
  vendor/github.com/openshift/library-go/pkg/config/leaderelection/leaderelection.go
  vendor/github.com/openshift/library-go/pkg/config/serving/options.go
  vendor/github.com/openshift/library-go/pkg/config/serving/server.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/flags.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/OWNERS
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer_polling.go
  vendor/k8s.io/client-go/tools/leaderelection/OWNERS
  vendor/k8s.io/client-go/tools/leaderelection/healthzadaptor.go
  vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go
  vendor/k8s.io/client-go/tools/leaderelection/metrics.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/configmaplock.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/endpointslock.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/interface.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/leaselock.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/multilock.go
  vendor/k8s.io/component-base/metrics/prometheus/clientgo/leaderelection/metrics.go
  vendor/k8s.io/component-base/metrics/prometheus/clientgo/metrics.go
  vendor/k8s.io/component-base/metrics/prometheus/restclient/metrics.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update

#27993 OCPBUGS-13379: machines: add a test which verifies number of node reboots
  test/extended/machines/cluster.go
  test/extended/machines/display_reboots_pod.yaml
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#27990 Flake ci-cluster-network-liveness and new backend disruption failures to avoid payload rejections
  pkg/synthetictests/disruption.go
Labels: approved, lgtm

#27998 OCPBUGS-15291: [sig-cli] oc idle: get a dc name through labels instead of parsing oc create output
  test/extended/cli/idle.go
  test/extended/testdata/bindata.go
  test/extended/testdata/cmd/test/cmd/testdata/idling-dc.yaml
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#27999 skip reboot test when machineconfigs not in target cluster
  test/extended/machines/cluster.go
Labels: approved, lgtm

#27992 OCPBUGS-11652: Enable oc adm node-logs
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#28002 TRT-1097: add KubeMemoryOvercommit to specific test so that the general test doesn't fail
  pkg/synthetictests/allowedalerts/all.go
Labels: approved, lgtm, jira/valid-reference

#28003 disruption refinement for availability, not latency.
  .gitignore
  pkg/disruption/backend/disruption/handler.go
  pkg/monitor/backenddisruption/disruption_backend_sampler.go
  pkg/monitor/backenddisruption/disruption_locator.go
  pkg/monitor/monitorapi/identification_pod.go
Labels: approved, lgtm

#27987 Changing the severity of "missing runbook_url annotation for critical alerts" test case from flaky to failure
  test/extended/prometheus/prometheus.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/prometheus/helpers.go
Labels: approved, lgtm

#28000 Report external binary usage
  pkg/test/ginkgo/cmd_runsuite.go
  pkg/test/ginkgo/external.go
Labels: approved, lgtm

#27996 USHIFT-647: skip sig-cli explain for CRDs in MicroShift
  test/extended/cli/explain.go
  test/extended/util/framework.go
Labels: approved, lgtm, tide/merge-method-squash, jira/valid-reference

#27911 OCPVE-378: feat: remove skip, allow check on all platforms regardless
  test/extended/cpu_partitioning/pods.go
  test/extended/cpu_partitioning/utils.go
Labels: approved, lgtm, jira/valid-reference

#28007 add debugging info for cluster not ready to upgrade
  test/e2e/upgrade/clusteroperator.go
  test/e2e/upgrade/upgrade.go
Labels: approved, lgtm

#28008 add a networking alert for OVNKubernetesResourceRetryFailure
  pkg/synthetictests/allowedalerts/all.go
Labels: approved, lgtm

#28009 allow cluster-config-operator to manage featuregate upgrade block
  test/extended/operators/operators.go
Labels: approved, lgtm
