Repository openshift/origin, pull requests merged in 2023-07, with the labels that each got.

#28016 Update "verify that nodes have no unexpected reboots" test
  test/extended/machines/cluster.go
  test/extended/machines/display_reboots_pod.yaml
Labels: approved, lgtm

#27967 OCPBUGS-14425: Skip CCM upgradable condition on AlibabaCloud
  test/extended/operators/operators.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#28011 print out deployment for incorrectly scheduled pods
  test/extended/scheduling/pods.go
Labels: approved, lgtm

#28020 trt-1117: Test for update lease errors
  pkg/monitor/intervalcreation/node.go
  pkg/monitor/intervalcreation/node_test.go
  pkg/synthetictests/event_junits.go
  pkg/synthetictests/kubelet.go
Labels: approved, lgtm, jira/valid-reference

#27897 USHIFT-647: skip non-existing resources from security.openshift.io
  test/extended/cli/explain.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, jira/valid-reference

#27922 AUTH-377: Add oauth-server redirect URI validation e2e tests
  test/extended/oauth/redirect_uris.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, jira/valid-reference

#28010 OCPBUGS-15558: retry promql a few times to mask i/o timeouts
  test/extended/util/prometheus/helpers.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#28026 OCPBUGS-15568: Increase clusterquota wait timeout from 10 to 30 seconds
  test/extended/quota/clusterquota.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#28006 OCPVE-379: fix: avoid checking resources for BestEffort pods
  test/extended/cpu_partitioning/pods.go
Labels: approved, lgtm, jira/valid-reference

#28029 OCPBUGS-15835: remove references to registry.centos.org
  examples/image-streams/image-streams-centos7.json
  test/extended/testdata/bindata.go
  test/extended/testdata/cmd/test/cmd/testdata/image-streams/image-streams-centos7.json
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/valid-reference

#28004 trt-1030: 80s for service lb under test
  test/e2e/upgrade/service/service.go
Labels: approved, lgtm, jira/valid-reference

#28028 Add test checking nodes are in proper read state before upgrade
  test/e2e/upgrade/upgrade.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#28012 OCPBUGS-15500: Avoid panic attempting to process interval logs
  pkg/monitor/intervalcreation/podlogs.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#28032 Add logs in clusterquota test for more verbosity
  test/extended/quota/clusterquota.go
Labels: approved, lgtm

#27689 test: extended: deployment: use correct apigroup for imagestreamtags
  test/extended/deployments/deployments.go
Labels: approved, lgtm

#28034 Provide more detailed information when extracting binary fails
  cmd/openshift-tests/openshift-tests.go
  pkg/test/ginkgo/cmd_runsuite.go
  pkg/test/ginkgo/external.go
Labels: approved, lgtm

#28015 USHIFT-1379: skip must-gather tests for MicroShift
  test/extended/cli/mustgather.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, jira/valid-reference

#28035 multinetpolicy: use RetryOnConflict to reduce flakes
  test/extended/networking/multinetpolicy.go
Labels: approved, lgtm

#28038 update pathological event namespace label to be unambiguous
  pkg/synthetictests/duplicated_events.go
Labels: approved, lgtm

#27776 [OCPCLOUD-1987] Enable Azure platform check in external cloud provider test
  test/extended/cloud_controller_manager/ccm.go
Labels: approved, lgtm, lifecycle/rotten

#28041 OCPBUGS-15291: Update broken dc tests due to deprecation warning
  test/extended/cli/idle.go
  test/extended/cli/run.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#28046 increase cloud-credential-operator watch since we added a self-clusteroperator watch
  test/extended/apiserver/api_requests.go
Labels: approved, lgtm

#28044 OCPBUGS-15893: Update permission to incl. watch for helmchartrepositories for console users
  test/extended/authorization/rbac/groups_default_rules.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#28045 ODC-7333: Add consolesamples to the list of console resources that all users should have read access
  test/extended/authorization/rbac/groups_default_rules.go
Labels: approved, lgtm, jira/valid-reference

#27960 Remove sampler
  pkg/monitor/api.go
  pkg/monitor/intervalcreation/node.go
  pkg/monitor/intervalcreation/node_test.go
  pkg/monitor/intervalcreation/pod.go
  pkg/monitor/intervalcreation/state_tracker.go
  pkg/monitor/intervalcreation/types.go
  pkg/monitor/monitor.go
  pkg/monitor/monitorapi/identification_pod.go
  pkg/monitor/monitorapi/types.go
  pkg/monitor/node.go
  pkg/monitor/noop.go
  pkg/monitor/operator.go
  pkg/monitor/pod.go
  pkg/monitor/sampler.go
  pkg/monitor/sampler_test.go
  pkg/monitor/types.go
Labels: approved, lgtm

#28050 OCPBUGS-16164: allow cluster-config-operator to manage featuregate upgrade block
  test/extended/operators/operators.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#28043 Remove audit id from sample err
  pkg/monitor/backenddisruption/disruption_backend_sampler.go
Labels: approved, lgtm

#28047 Handle partial discovery results in DoesApiResourceExist.
  test/extended/util/framework.go
Labels: approved, lgtm

#28057 ODC-7333: Add consolesamples to the exception list of CRDs without a status
  test/extended/cli/explain.go
  test/extended/operators/check_crd_status.go
Labels: approved, lgtm, jira/valid-reference

#28005 USHIFT-704: skip [sig-cli] whoami result with console for MicroShift
  cmd/openshift-tests/provider.go
  test/extended/cli/explain.go
  test/extended/util/framework.go
Labels: approved, lgtm, jira/valid-reference

#28059 only close intervals if they are open
  e2echart/e2e-chart-template.html
  e2echart/non-spyglass-e2e-chart-template.html
  pkg/monitor/intervalcreation/node.go
  pkg/monitor/intervalcreation/nodeTest/drain-01/expected.json
  pkg/monitor/intervalcreation/nodeTest/drain-01/startingEvents.json
  pkg/monitor/intervalcreation/nodeTest/drain-01/times.txt
  pkg/monitor/intervalcreation/nodeTest/drain-02/expected.json
  pkg/monitor/intervalcreation/nodeTest/drain-02/startingEvents.json
  pkg/monitor/intervalcreation/nodeTest/drain-02/times.txt
  pkg/monitor/intervalcreation/node_test.go
  pkg/monitor/intervalcreation/pod.go
  pkg/monitor/intervalcreation/podTest/container-life/expected.json
  pkg/monitor/intervalcreation/podTest/end-before-begin/expected.json
  pkg/monitor/intervalcreation/podTest/installer-pod/expected.json
  pkg/monitor/intervalcreation/podTest/long-not-ready/expected.json
  pkg/monitor/intervalcreation/podTest/run-once-done/expected.json
  pkg/monitor/intervalcreation/podTest/simple/expected.json
  pkg/monitor/intervalcreation/podTest/trailing-ready-2/expected.json
  pkg/monitor/intervalcreation/podTest/trailing-ready/expected.json
  pkg/monitor/intervalcreation/render_test_01_skip_e2e.json
  pkg/monitor/intervalcreation/rendering.go
  pkg/monitor/intervalcreation/state_tracker.go
  pkg/monitor/monitorapi/identification.go
  pkg/monitor/monitorapi/identification_pod.go
  test/extended/testdata/bindata.go
Labels: approved, lgtm

#28058 Update S2i Image tests for removing nodejs 14 ubi8 eol
  test/extended/image_ecosystem/s2i_images.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#28060 fix: add missing namespaces to exclude list
  test/extended/cpu_partitioning/pods.go
Labels: approved, lgtm

#27909 OCPBUGS-13158: Run new tests which monitors in-cluster API server disruption as daemonsets on masters/workers
  cmd/disruption/main.go
  cmd/openshift-tests/disruption.go
  cmd/openshift-tests/openshift-tests.go
  pkg/cmd/monitor_command/run_monitor_command.go
  pkg/disruption/backend/descriptor.go
  pkg/disruption/backend/sampler/manifests/crb-hostaccess.yaml
  pkg/disruption/backend/sampler/manifests/crb-monitor.yaml
  pkg/disruption/backend/sampler/manifests/ds-internal-lb.yaml
  pkg/disruption/backend/sampler/manifests/ds-localhost.yaml
  pkg/disruption/backend/sampler/manifests/ds-service-network.yaml
  pkg/disruption/backend/sampler/manifests/namespace.yaml
  pkg/disruption/backend/sampler/manifests/role-monitor.yaml
  pkg/disruption/backend/sampler/manifests/serviceaccount.yaml
  pkg/disruption/backend/sampler/remote.go
  pkg/disruption/ci/backend_sampler.go
  pkg/disruption/ci/factory.go
  pkg/disruption/ci/factory_test.go
  pkg/disruption/ci/remote_sampler.go
  pkg/monitor/api.go
  pkg/monitor/monitorapi/disruption.go
  pkg/monitor/nodedetails/node_log.go
  pkg/monitor/types.go
  pkg/test/ginkgo/cmd_runsuite.go
  pkg/test/ginkgo/options_monitor_events.go
  test/extended/util/disruption/controlplane/known_backends.go
  test/extended/util/disruption/externalservice/known_backends.go
  test/extended/util/disruption/frontends/known_backends.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#28049 MON-3280: enable etcd metrics check again
  test/extended/prometheus/prometheus.go
Labels: approved, lgtm, jira/valid-reference

#28076 finish scrubbing out sampler
  cmd/openshift-tests/disruption.go
  pkg/cmd/monitor_command/run_monitor_command.go
  pkg/monitor/api.go
  pkg/monitor/event_test.go
  pkg/monitor/monitor.go
  pkg/monitor/monitor_test.go
  pkg/monitor/types.go
  test/extended/util/disruption/backend_sampler_tester.go
Labels: approved, lgtm

#28065 trt-1150: move lock so prevent multiple file updates in single commit
  pkg/monitor/resourcewatch/storage/git_store.go
Labels: approved, lgtm, jira/valid-reference

#28078 Fix usage of priviliged pods in sig-kubevirt test cases
  test/extended/kubevirt/util.go
Labels: approved, lgtm

#28082 [sig-kubevirt] Fix retrieval of virt-launcher pod of the guest node
  test/extended/kubevirt/util.go
Labels: approved, lgtm

#28079 remove unnecessary options and make monitor act like controller
  cmd/openshift-tests/disruption.go
  pkg/cmd/monitor_command/run_monitor_command.go
  pkg/monitor/api.go
  pkg/monitor/event_test.go
  pkg/monitor/monitor.go
  pkg/monitor/noop.go
  pkg/monitor/types.go
  pkg/test/ginkgo/options_monitor_events.go
  test/extended/util/disruption/backend_sampler_tester.go
Labels: approved, lgtm

#28080 create a recorder interface that separates monitoring from recording
  cmd/openshift-tests/disruption.go
  pkg/monitor/backenddisruption/disruption_backend_sampler.go
  pkg/monitor/event.go
  pkg/monitor/event_test.go
  pkg/monitor/monitor.go
  pkg/monitor/monitor_test.go
  pkg/monitor/recorder.go
  pkg/monitor/types.go
  test/extended/util/disruption/backend_sampler_tester.go
  test/extended/util/disruption/controlplane/known_backends.go
Labels: approved, lgtm

#28073 add experimental etcd rev bump to test
  test/extended/dr/common.go
  test/extended/dr/recovery.go
Labels: approved, lgtm, tide/merge-method-squash

#28077 add interface for future invariant tests
  pkg/defaultinvariants/types.go
  pkg/invariants/impl.go
  pkg/invariants/types.go
Labels: approved, lgtm

#28084 fix logic -- If error, return current time; else return log line time
  pkg/monitor/apiserveravailability/summarizer.go
Labels: approved, lgtm

#28092 AUTH-401: test/e/authorization/pod_security_admission: add e2e test for pinning SCCs
  test/extended/authorization/podsecurity_admission.go
  test/extended/authorization/scc.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, jira/valid-reference

#28056 OCPVE-318: feat: add node validation for workload partitioning
  test/extended/cpu_partitioning/OWNERS
  test/extended/cpu_partitioning/crio.go
  test/extended/cpu_partitioning/utils.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, jira/valid-reference

#28090 remove suite hook configuration and make information flow one-way
  cmd/openshift-tests/dev.go
  cmd/openshift-tests/e2e.go
  cmd/openshift-tests/openshift-tests.go
  cmd/openshift-tests/runsuite_options.go
  cmd/openshift-tests/upgrade.go
  cmd/openshift-tests/upgrade_options.go
  pkg/clioptions/clusterdiscovery/cluster.go
  pkg/clioptions/clusterdiscovery/csi.go
  pkg/clioptions/clusterdiscovery/provider.go
  pkg/clioptions/clusterdiscovery/provider_test.go
  pkg/clioptions/clusterdiscovery/storagecaps.go
  pkg/test/ginkgo/cmd_runsuite.go
  pkg/test/ginkgo/test_runner.go
  pkg/test/ginkgo/test_suite.go
  pkg/test_suite_definition/README.md
  pkg/test_suite_definition/cni.go
  pkg/test_suite_definition/e2e.go
  pkg/test_suite_definition/e2e_test.go
  pkg/test_suite_definition/filters.go
  pkg/test_suite_definition/minimal.go
  pkg/test_suite_definition/upgrade.go
  test/extended/util/disruption/frontends/known_backends.go
Labels: approved, lgtm

#28102 feat: make data gathering more robust
  test/extended/cpu_partitioning/crio.go
Labels: approved, lgtm

#28091 Put times in UTC to allow local testing; use asserts where we can
  pkg/synthetictests/duplicated_events_test.go
Labels: approved, lgtm

#28109 Adjust interval builder before we continue porting
  pkg/disruption/backend/disruption/handler.go
  pkg/disruption/backend/shutdown/handler.go
  pkg/monitor/alerts.go
  pkg/monitor/alerts_test.go
  pkg/monitor/apiserveravailability/summarizer.go
  pkg/monitor/backenddisruption/disruption_locator.go
  pkg/monitor/intervalcreation/node.go
  pkg/monitor/intervalcreation/operator.go
  pkg/monitor/intervalcreation/podlogs.go
  pkg/monitor/intervalcreation/state_tracker.go
  pkg/monitor/monitor_test.go
  pkg/monitor/monitorapi/construction.go
  pkg/monitor/monitorapi/types.go
  pkg/monitor/pod.go
Labels: approved, lgtm

#28017 Update image stream test to create a manifest list image by default
  test/extended/images/append.go
Labels: approved, lgtm

#28074 SDN-4042: Increase total upgrade time on OVN platforms
  test/e2e/upgrade/upgrade.go
Labels: approved, lgtm, jira/valid-reference
