Repository openshift/origin, pull requests merged in 2023-09, with the labels that each got.

#28234 [release-4.12] OCPBUGS-18309: Add missing watch permission for console users
  test/extended/authorization/rbac/groups_default_rules.go
Labels: kind/bug, approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference

#28193 USHIFT-1590: skip failing invariants in MicroShift
  pkg/monitortests/kubeapiserver/disruptionnewapiserver/monitortest.go
  pkg/monitortests/network/legacynetworkmonitortests/networking.go
  pkg/monitortests/node/kubeletlogcollector/monitortest.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#28177 STOR-1425: Disable NetworkPolicyStatus tests
  test/extended/util/annotate/rules.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#28200 STOR-1425: Add images coming in k8s 1.28
  pkg/cmd/openshift-tests/images/images_command.go
  test/extended/util/image/zz_generated.txt
Labels: approved, lgtm, e2e-images-update, jira/valid-reference, acknowledge-critical-fixes-only

#28220 OCPVE-295: fix: add rteval to the test image
  images/tests/Dockerfile.rhel
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#28245 Bug OCPBUGS-18718 Remove duplicate connection type from disruption name
  pkg/monitortestlibrary/disruptionlibrary/disruption_invariant_adapter.go
Labels: approved, lgtm, acknowledge-critical-fixes-only

#28157 OCP-66086-Automate PSAP NTO Prevent from stalld continually restarting
  test/extended/include.go
  test/extended/node_tuning/OWNERS
  test/extended/node_tuning/node_tuning.go
  test/extended/testdata/bindata.go
  test/extended/testdata/node_tuning/OWNERS
  test/extended/testdata/node_tuning/nto-stalld.yaml
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/nodes.go
Labels: approved, lgtm, acknowledge-critical-fixes-only

#28248 STOR-1425: Add images coming in k8s 1.28
  pkg/cmd/openshift-tests/images/images_command.go
  test/extended/util/image/zz_generated.txt
Labels: approved, lgtm, e2e-images-update, jira/valid-reference, acknowledge-critical-fixes-only

#28250 Revert fake image injections for k8s 1.28
  pkg/cmd/openshift-tests/images/images_command.go
  test/extended/util/image/zz_generated.txt
Labels: approved, lgtm, e2e-images-update, acknowledge-critical-fixes-only

#28253 When --from-repository use built-in tests only
  pkg/cmd/openshift-tests/run-upgrade/flags.go
  pkg/cmd/openshift-tests/run/flags.go
  pkg/test/ginkgo/cmd_runsuite.go
Labels: approved, lgtm, acknowledge-critical-fixes-only

#28256 Bring in updates k8s to disable networking test
  go.mod
  go.sum
  test/extended/util/annotate/rules.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/etcd3retry/retry_etcdclient.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/metrics/metrics.go
  vendor/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3.go
  vendor/k8s.io/kubernetes/cmd/kubelet/app/server.go
  vendor/k8s.io/kubernetes/openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  vendor/k8s.io/kubernetes/openshift-hack/e2e/annotate/rules.go
  vendor/k8s.io/kubernetes/pkg/kubelet/cm/cgroup_manager_linux.go
  vendor/k8s.io/kubernetes/pkg/registry/authorization/selfsubjectaccessreview/rest.go
  vendor/k8s.io/kubernetes/pkg/registry/authorization/selfsubjectaccessreview/rest_patch.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, acknowledge-critical-fixes-only

#28053 Improvements and fixes for Loki intervals uploader
  pkg/cmd/openshift-tests/dev/dev.go
  pkg/cmd/openshift-tests/monitor/timeline/timeline_command.go
  pkg/disruption/backend/sampler/remote.go
  pkg/monitor/serialization/serialize.go
  pkg/monitortests/node/nodestateanalyzer/node_test.go
  pkg/monitortests/node/watchpods/compute_intervals_test.go
  pkg/monitortests/testframework/additionaleventscollector/monitortest.go
  pkg/monitortests/testframework/timelineserializer/rendering_test.go
  pkg/monitortests/testframework/uploadtolokiserializer/loki_upload_test.go
  pkg/monitortests/testframework/uploadtolokiserializer/monitortest.go
Labels: approved, lgtm

#28225 Adding leader election information to timeline
  pkg/monitortests/etcd/etcdloganalyzer/podlogs.go
Labels: approved, lgtm

#28265 TRT-1244: Bump aws-ovn upgradeDurationLimits to 130
  test/e2e/upgrade/upgrade.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#28268 Revert "Improvements and fixes for Loki intervals uploader"
  pkg/cmd/openshift-tests/dev/dev.go
  pkg/cmd/openshift-tests/monitor/timeline/timeline_command.go
  pkg/disruption/backend/sampler/remote.go
  pkg/monitor/serialization/serialize.go
  pkg/monitortests/node/nodestateanalyzer/node_test.go
  pkg/monitortests/node/watchpods/compute_intervals_test.go
  pkg/monitortests/testframework/additionaleventscollector/monitortest.go
  pkg/monitortests/testframework/timelineserializer/rendering_test.go
  pkg/monitortests/testframework/uploadtolokiserializer/loki_upload_test.go
  pkg/monitortests/testframework/uploadtolokiserializer/monitortest.go
Labels: approved, lgtm

#28042 OCPBUGS-14053: remove exception for MultipleDefaultStorageClasses
  test/extended/prometheus/prometheus.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#28226 AUTH-365: add PodSecurityViolation to watched alerts
  pkg/monitortestlibrary/allowedalerts/all.go
  test/extended/apiserver/apply.go
  test/extended/kubevirt/services.go
  test/extended/networking/internal_ports.go
  test/extended/networking/isolation.go
  test/extended/networking/services.go
  test/extended/pods/liveness_override.go
  test/extended/testdata/bindata.go
  test/extended/testdata/cmd/hack/lib/init.sh
  test/extended/util/client.go
  test/extended/util/disruption/disruption.go
Labels: approved, lgtm, jira/valid-reference

#28231 OCPBUGS-18865: add monitortest: in-cluster disruption monitors
  pkg/clioptions/iooptions/io_options.go
  pkg/cmd/openshift-tests/monitor/run/run_monitor_command.go
  pkg/cmd/openshift-tests/run-disruption/disruption.go
  pkg/defaultmonitortests/types.go
  pkg/disruption/backend/sampler/remote.go
  pkg/disruption/ci/backend_sampler.go
  pkg/disruption/ci/factory.go
  pkg/disruption/ci/host_decoder.go
  pkg/disruption/ci/remote_sampler.go
  pkg/monitortestframework/impl.go
  pkg/monitortestframework/panic.go
  pkg/monitortestframework/types.go
  pkg/monitortestlibrary/disruptionlibrary/collect.go
  pkg/monitortests/kubeapiserver/disruptionnewapiserver/monitortest.go
  pkg/monitortests/kubeapiserver/incluster_disruption_serializer/manifests/crb-hostaccess.yaml
  pkg/monitortests/kubeapiserver/incluster_disruption_serializer/manifests/crb-monitor.yaml
  pkg/monitortests/kubeapiserver/incluster_disruption_serializer/manifests/dep-internal-lb.yaml
  pkg/monitortests/kubeapiserver/incluster_disruption_serializer/manifests/dep-localhost.yaml
  pkg/monitortests/kubeapiserver/incluster_disruption_serializer/manifests/dep-service-network.yaml
  pkg/monitortests/kubeapiserver/incluster_disruption_serializer/manifests/namespace.yaml
  pkg/monitortests/kubeapiserver/incluster_disruption_serializer/manifests/role-monitor.yaml
  pkg/monitortests/kubeapiserver/incluster_disruption_serializer/manifests/serviceaccount.yaml
  pkg/monitortests/kubeapiserver/incluster_disruption_serializer/remote.go
  pkg/monitortests/network/disruptionpodnetwork/monitortest.go
  pkg/test/ginkgo/cmd_runsuite.go
  test/extended/util/disruption/controlplane/known_backends.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#28243 add pod log streaming to monitor for etcd so we see all intervals
  e2echart/e2e-chart-template.html
  e2echart/non-spyglass-e2e-chart-template.html
  pkg/monitor/monitorapi/construction.go
  pkg/monitor/monitorapi/types.go
  pkg/monitortestlibrary/podaccess/location.go
  pkg/monitortestlibrary/podaccess/pod_log_streamer.go
  pkg/monitortestlibrary/podaccess/pod_logs_stream_all.go
  pkg/monitortests/etcd/etcdloganalyzer/monitortest.go
  pkg/monitortests/etcd/etcdloganalyzer/podlogs.go
  pkg/monitortests/etcd/etcdloganalyzer/podlogs_test.go
  test/extended/testdata/bindata.go
Labels: approved, lgtm

#28261 OCPVE-295: rteval
  test/extended/kernel/kernel_rt_latency.go
  test/extended/kernel/tools.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, jira/valid-reference

#28274 Revert "OCPBUGS-18865: add monitortest: in-cluster disruption monitors"
  pkg/clioptions/iooptions/io_options.go
  pkg/cmd/openshift-tests/monitor/run/run_monitor_command.go
  pkg/cmd/openshift-tests/run-disruption/disruption.go
  pkg/defaultmonitortests/types.go
  pkg/disruption/backend/sampler/manifests/crb-hostaccess.yaml
  pkg/disruption/backend/sampler/manifests/crb-monitor.yaml
  pkg/disruption/backend/sampler/manifests/ds-internal-lb.yaml
  pkg/disruption/backend/sampler/manifests/ds-localhost.yaml
  pkg/disruption/backend/sampler/manifests/ds-service-network.yaml
  pkg/disruption/backend/sampler/manifests/namespace.yaml
  pkg/disruption/backend/sampler/manifests/role-monitor.yaml
  pkg/disruption/backend/sampler/manifests/serviceaccount.yaml
  pkg/disruption/backend/sampler/remote.go
  pkg/disruption/ci/backend_sampler.go
  pkg/disruption/ci/factory.go
  pkg/disruption/ci/host_decoder.go
  pkg/disruption/ci/remote_sampler.go
  pkg/monitortestframework/impl.go
  pkg/monitortestframework/panic.go
  pkg/monitortestframework/types.go
  pkg/monitortestlibrary/disruptionlibrary/collect.go
  pkg/monitortests/kubeapiserver/disruptionnewapiserver/monitortest.go
  pkg/monitortests/kubeapiserver/incluster_disruption_serializer/remote.go
  pkg/monitortests/network/disruptionpodnetwork/monitortest.go
  pkg/test/ginkgo/cmd_runsuite.go
  test/extended/util/disruption/controlplane/known_backends.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#28223 OCPBUGS-17240: etcd-recovery: fix resource leaks, more meaningful errors
  test/extended/dr/recovery.go
  test/extended/dr/resource_assertions.go
Labels: approved, lgtm, tide/merge-method-squash, jira/valid-bug, jira/severity-low, jira/valid-reference

#28228 OCPBUGS-18141: retry query on MetricsAvailableAfterUpgradeTest setup
  test/extended/prometheus/upgrade.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#28238 fix PR 28224
  test/extended/quota/resourcequota.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#28242 wait for the service to have endpoints before starting pollers
  pkg/monitortests/network/disruptionpodnetwork/monitortest.go
Labels: approved, lgtm

#28251 some monitor tests only function on disruptive tests
  pkg/defaultmonitortests/types.go
Labels: approved, lgtm

#27980 kubevirt: Add live migration tests
  test/extended/kubevirt/migration.go
  test/extended/kubevirt/util.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#28258 Force using mirrored images in disruption tests
  cmd/openshift-tests/openshift-tests.go
  pkg/cmd/openshift-tests/monitor/run/run_monitor_command.go
Labels: approved, lgtm

#28278 Bump openshift/kubernetes to get vSphere fix
  go.mod
  go.sum
  vendor/k8s.io/kubernetes/pkg/controller/daemon/update.go
  vendor/k8s.io/kubernetes/test/e2e/storage/drivers/in_tree.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update

#28252 add disruptive flag from suite
  pkg/cmd/openshift-tests/run-upgrade/options.go
  pkg/cmd/openshift-tests/run/options.go
  pkg/test/ginkgo/cmd_runsuite.go
Labels: approved, lgtm, tide/merge-method-squash

#28286 Revert "Force using mirrored images in disruption tests"
  cmd/openshift-tests/openshift-tests.go
  pkg/cmd/openshift-tests/monitor/run/run_monitor_command.go
Labels: approved, lgtm

#28283 Revert "Disable EgressIP test temporarily due to OVN-K bug"
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm

#28215 make it possible to select which monitor tests to run
  pkg/cmd/openshift-tests/monitor/run/run_monitor_command.go
  pkg/monitortestframework/impl.go
  pkg/monitortestframework/types.go
Labels: approved, lgtm

#28288 OCPBUGS-19909: Updating parameters for build timing PushImage test
  test/extended/builds/build_timing.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#28285 Properly default --from-repository in run-monitor
  cmd/openshift-tests/openshift-tests.go
  pkg/cmd/openshift-tests/monitor/run/run_monitor_command.go
Labels: approved, lgtm
