Repository openshift/origin, pull requests merged in 2023-12, with the labels that each got.

#28402 NO-JIRA: test/e2e/upgrade/monitor: --abort-at=100 requires a complete update
  pkg/cmd/openshift-tests/run-upgrade/command.go
  test/e2e/upgrade/monitor.go
  test/e2e/upgrade/upgrade.go
Labels: approved, lgtm, jira/valid-reference

#28435 OCPNODE-1892: Update ETCD storage data for k8s 1.29
  Makefile
  test/extended/etcd/etcd_storage_path.go
Labels: approved, lgtm, jira/valid-reference

#27231 OTA-362: pkg/monitortests/clusterversionoperator: Fatal unless Available=False in allow-list
  pkg/monitortests/clusterversionoperator/legacycvomonitortests/operators.go
Labels: approved, lgtm, jira/valid-reference

#28425 TRT-1347: Add ability to indicate a monitor test was skipped
  pkg/monitortestframework/errors.go
  pkg/monitortestframework/impl.go
  pkg/monitortests/imageregistry/disruptionimageregistry/monitortest.go
  pkg/monitortests/kubeapiserver/disruptionlegacyapiservers/monitortest.go
  pkg/monitortests/kubeapiserver/disruptionnewapiserver/monitortest.go
  pkg/monitortests/network/disruptionpodnetwork/monitortest.go
  pkg/monitortests/network/disruptionserviceloadbalancer/monitortest.go
  pkg/monitortests/testframework/disruptionexternalservicemonitoring/monitortest.go
Labels: approved, lgtm, jira/valid-reference

#28420 TRT-1359: Ignore azure interaction errors since they are not fatal for our usage
  pkg/monitortests/cloud/azure/metrics/monitortest.go
Labels: approved, lgtm, jira/valid-reference

#28440 NO-JIRA: Add test case for namespaced filename in oc process
  test/extended/cli/template.go
  test/extended/testdata/bindata.go
  test/extended/testdata/cmd/test/cmd/testdata/new-app/template-with-crd-ns.yaml
Labels: approved, lgtm, jira/valid-reference

#28436 OCPNODE-1892: Conditionally skip tests to help with k8s 1.29
  pkg/test/ginkgo/cmd_runsuite.go
Labels: approved, lgtm, jira/valid-reference

#28443 NOJIRA: collect certificate data: use SkipHashed option
  test/extended/operators/certs.go
Labels: approved, lgtm, jira/valid-reference

#28447 OWNER_ALIASES: update CoreOS team leads
  OWNERS_ALIASES
Labels: approved, lgtm

#28449 add pacevedom to the team-leads alias
  OWNERS_ALIASES
Labels: approved

#28448 OCPBUGS-24537: Properly ignore kube guard probe events
  pkg/monitortestlibrary/pathologicaleventlibrary/duplicated_event_patterns.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#28454 fix jira components to match actual jira components
  pkg/defaultmonitortests/types.go
Labels: approved, lgtm, jira/valid-reference

#28453 TRT-786: Relax the per-job disruption tests and fix bugs/improve consistency
  pkg/monitortestlibrary/allowedalerts/matches_test.go
  pkg/monitortestlibrary/allowedbackenddisruption/matches_test.go
  pkg/monitortestlibrary/disruptionlibrary/disruption_invariant_adapter.go
  pkg/monitortestlibrary/historicaldata/next_best_guess.go
  pkg/monitortests/imageregistry/disruptionimageregistry/monitortest.go
  pkg/monitortests/kubeapiserver/disruptionlegacyapiservers/monitortest.go
  pkg/monitortests/network/disruptionserviceloadbalancer/monitortest.go
Labels: approved, lgtm, jira/valid-reference

#28431 trt-1042: collect watch request counts
  pkg/dataloader/types.go
  pkg/defaultmonitortests/types.go
  pkg/monitortests/testframework/watchrequestcountscollector/monitortest.go
  test/extended/apiserver/api_requests.go
Labels: approved, lgtm, jira/valid-reference

#28460 update-tls-artifacts: add AnnotationRequirement
  pkg/cmd/update-tls-artifacts/generate-owners/tlsmetadata/autoregenerate_after_expiry/requirement.go
  pkg/cmd/update-tls-artifacts/generate-owners/tlsmetadatainterfaces/annotation_requirement.go
  pkg/cmd/update-tls-artifacts/generate-owners/tlsmetadatainterfaces/markdown.go
  pkg/cmd/update-tls-artifacts/generate-owners/tlsmetadatainterfaces/types.go
  test/extended/operators/certs.go
  tls/autoregenerate-after-expiry/autoregenerate-after-expiry.md
  tls/ownership/ownership.md
Labels: approved, lgtm, jira/valid-reference

#28458 OCPNODE-1892: Update etcd test data for 1.29 release
  test/extended/etcd/etcd_storage_path.go
Labels: approved, lgtm, jira/valid-reference

#28461 Show how we can add new annotations using descriptions
  pkg/cmd/update-tls-artifacts/generate-owners/tlsmetadata/descriptions/requirement.go
  pkg/cmd/update-tls-artifacts/generate-owners/tlsmetadatadefaults/defaults.go
  tls/descriptions/descriptions.json
  tls/descriptions/descriptions.md
  tls/violations/descriptions/descriptions-violations.json
Labels: approved, lgtm, jira/valid-reference

#28465 OCPNODE-1892: Conditionally skip tests to help with k8s 1.29
  pkg/test/ginkgo/cmd_runsuite.go
Labels: approved, lgtm, jira/valid-reference

#28446 NO-JIRA: Fix issue 28445
  pkg/test/ginkgo/cmd_runsuite.go
Labels: approved, lgtm, ok-to-test, jira/valid-reference

#28459 TRT-1359: Add mechanism for creating flake junit for a monitor test
  pkg/monitortestframework/errors.go
  pkg/monitortestframework/impl.go
  pkg/monitortests/cloud/azure/metrics/monitortest.go
Labels: approved, lgtm, jira/valid-reference

#28457 NE-1477: Regenerate cert in 1024 key FIPs test to use SHA256
  test/extended/router/certs.go
Labels: approved, lgtm, jira/valid-reference

#28471 OCPBUGS-25610: fix: lane e2e-gcp-ovn-builds perma fail
  examples/quickstarts/rails-postgresql.json
  test/extended/builds/dockerfile.go
  test/extended/cli/setimage.go
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/build-secrets/test-s2i-build.json
  test/extended/testdata/builds/incremental-auth-build.json
  test/extended/testdata/builds/statusfail-badcontextdirs2i.yaml
  test/extended/testdata/builds/statusfail-fetchimagecontentdocker.yaml
  test/extended/testdata/builds/statusfail-fetchsourcedocker.yaml
  test/extended/testdata/builds/statusfail-fetchsources2i.yaml
  test/extended/testdata/builds/statusfail-genericreason.yaml
  test/extended/testdata/builds/statusfail-oomkilled.yaml
  test/extended/testdata/builds/test-build-proxy.yaml
  test/extended/testdata/builds/test-build.yaml
  test/extended/testdata/builds/test-context-build.json
  test/extended/testdata/builds/test-env-build.json
  test/extended/testdata/builds/test-imagesource-buildconfig.yaml
  test/extended/testdata/cluster/quickstarts/rails-postgresql.json
  test/extended/testdata/cmd/test/cmd/testdata/image-streams/image-streams-centos7.json
  test/extended/testdata/cmd/test/cmd/testdata/new-app/imagestream-ref.yaml
  test/extended/testdata/image/test-image.json
  test/extended/testdata/long_names/fixture.json
  test/extended/testdata/run_policy/parallel-bc.yaml
  test/extended/testdata/run_policy/serial-bc.yaml
  test/extended/testdata/run_policy/serial-latest-only-bc.yaml
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#28463 TRT-1403: Finish porting ALL intervals to structured
  pkg/disruption/backend/disruption/handler.go
  pkg/disruption/backend/shutdown/handler.go
  pkg/monitor/backenddisruption/disruption_backend_sampler.go
  pkg/monitor/backenddisruption/disruption_locator.go
  pkg/monitor/monitorapi/types.go
  pkg/monitor/recorder.go
  pkg/monitor/recorder_jsonl.go
  pkg/monitortests/etcd/etcdloganalyzer/monitortest.go
  pkg/monitortests/node/kubeletlogcollector/node.go
  pkg/monitortests/node/legacynodemonitortests/kubelet.go
  pkg/test/ginkgo/test_runner.go
Labels: approved, lgtm, jira/valid-reference

#28421 OCPBUGS-22438: feat: add extra check for ready state on resiliency test
  pkg/monitortestlibrary/pathologicaleventlibrary/duplicated_event_patterns.go
  test/extended/apiserver/resiliency.go
  test/extended/util/oc_copy.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#28481 OCPBUGS-25610: fix: update missing ruby 3.0 ref
  examples/quickstarts/rails-postgresql-persistent.json
  test/extended/testdata/bindata.go
  test/extended/testdata/cmd/test/cmd/images.sh
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#28469 NO-JIRA: images: don't log entire image status on failure
  test/extended/images/layers.go
Labels: approved, lgtm, jira/valid-reference

#28382 PSAP-1210: Update code for automate OCPBUGS-18052
  test/extended/node_tuning/node_tuning.go
  test/extended/node_tuning/node_tuning_utils.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, jira/valid-reference

#28474 OCPBUGS-25687: Increase timeout for pod-network-service
  pkg/monitortests/network/disruptionpodnetwork/monitortest.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#28485 OCPNODE-1895: Update etcd test data for 1.29 release
  test/extended/etcd/etcd_storage_path.go
Labels: approved, lgtm, jira/valid-reference
