Repository openshift/origin, pull requests merged in 2023-01, with the labels that each got.

#27630 Fix intervalcreation incorrect year unit test bug
  pkg/monitor/intervalcreation/node_test.go
Labels: approved, lgtm

#27629 Use create token instead serviceaccounts token command
  test/extended/images/oc_tag.go
Labels: approved, lgtm

#27631 Use cluster network MTU for bond interfaces
  test/extended/networking/bonds.go
Labels: approved, lgtm

#27612 Add Event intervals for Startup Probe failures
  e2echart/e2e-chart-template.html
  pkg/monitor/intervalcreation/node.go
  pkg/monitor/monitorapi/identification_pod.go
  test/extended/testdata/bindata.go
Labels: approved, lgtm

#27633 Add tests for template cross namespace processing
  test/extended/cli/template.go
  test/extended/testdata/bindata.go
  test/extended/testdata/cmd/test/cmd/templates.sh
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, tide/merge-method-squash

#27646 Update CVO test ownership: -Jack and Vadim, +Petr
  OWNERS_ALIASES
Labels: approved, lgtm

#27636 Fix missing disruption uploads.
  test/extended/util/disruption/backend_sampler_tester.go
Labels: approved, lgtm

#27641 Add result key value to each topological event test output line
  pkg/synthetictests/duplicated_events.go
  pkg/synthetictests/duplicated_events_test.go
Labels: approved, lgtm

#27651 Fix missing disruption data again.
  test/extended/util/disruption/backend_sampler_tester.go
  test/extended/util/disruption/disruption.go
Labels: approved, lgtm

#27643 WRKLDS-605: Remove dependency on some router tests on config.openshift.io api group
  test/extended/router/config_manager.go
  test/extended/router/subdomain.go
  test/extended/router/unprivileged.go
  test/extended/router/weighted.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#27642 do not check for DeploymentConfig routers in router tests
  test/extended/operators/routable.go
  test/extended/router/headers.go
  test/extended/router/reencrypt.go
  test/extended/router/router.go
  test/extended/testdata/bindata.go
  test/extended/testdata/router/router-http-echo-server.yaml
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
  test/extended/util/framework.go
Labels: approved, lgtm

#27648 Separate mcd error alert
  pkg/synthetictests/allowedalerts/all.go
Labels: approved, lgtm

#27645 upgrade/adminack: guarantee one admin ack check post-upgrade
  test/extended/util/openshift/clusterversionoperator/adminack.go
Labels: approved, lgtm

#27650 OCPBUGS-5506: DNS pod to be created on master node
  test/extended/dns/dns.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-critical

#27652 Don't emit failure junit testcase when a retry is skipped
  pkg/test/ginkgo/cmd_runsuite.go
Labels: approved, lgtm

#27661 Revert "Remove dependency on some router tests on config.openshift.io api group"
  test/extended/router/config_manager.go
  test/extended/router/subdomain.go
  test/extended/router/unprivileged.go
  test/extended/router/weighted.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#27663 Fix nil pointer dereference for createDNSPod.
  test/extended/dns/dns.go
Labels: approved, lgtm

#27662 Update annotated rules for router tests
  test/extended/router/config_manager.go
  test/extended/router/subdomain.go
  test/extended/router/unprivileged.go
  test/extended/router/weighted.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm

#27666 ignore repeated TopologyAwareHintsDisabled events
  pkg/synthetictests/duplicated_events.go
Labels: approved, lgtm

#27656 Add result tag to the end of first line of an event message
  pkg/synthetictests/duplicated_events.go
  pkg/synthetictests/duplicated_events_test.go
Labels: approved, lgtm

#27672 ignore more repeated TopologyAwareHintsDisabled events
  pkg/synthetictests/duplicated_events.go
Labels: approved, lgtm

#27680 Use ingress-canary route for testing instead of console since the console might be disabled
  test/extended/operators/routable.go
Labels: approved, lgtm

#27688 TRT-803: FIxing test name
  cmd/openshift-tests/minimal.go
Labels: approved, lgtm, jira/valid-reference

#27497 Update etcd scaling test for CPMS supported platforms
  test/extended/etcd/helpers/helpers.go
  test/extended/etcd/vertical_scaling.go
Labels: approved, lgtm, vendor-update

#27679 Skip the oc whoami --show-console test when the console capability is disabled
  test/extended/cli/basics.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm

#27657 Changes for NodeTuning cluster capability
  go.mod
  go.sum
  test/extended/cli/explain.go
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/config/.codegen.yaml
  vendor/github.com/openshift/api/config/install.go
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_ingress.crd.yaml
  vendor/github.com/openshift/api/config/v1/stable.clusterversion.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/stable.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1alpha1/0000_10_config-operator_01_insightsdatagather.crd.yaml
  vendor/github.com/openshift/api/config/v1alpha1/Makefile
  vendor/github.com/openshift/api/config/v1alpha1/doc.go
  vendor/github.com/openshift/api/config/v1alpha1/register.go
  vendor/github.com/openshift/api/config/v1alpha1/techpreview.insightsdatagather.testsuite.yaml
  vendor/github.com/openshift/api/config/v1alpha1/types_insights.go
  vendor/github.com/openshift/api/config/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/image/v1/generated.pb.go
  vendor/github.com/openshift/api/image/v1/generated.proto
  vendor/github.com/openshift/api/image/v1/types.go
  vendor/github.com/openshift/api/image/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/image/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/imageregistry/v1/00_imageregistry.crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/types.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1/0000_10_controlplanemachineset.crd.yaml
  vendor/github.com/openshift/api/machine/v1beta1/0000_10_machine.crd.yaml
  vendor/github.com/openshift/api/machine/v1beta1/0000_10_machinehealthcheck.yaml
  vendor/github.com/openshift/api/machine/v1beta1/0000_10_machineset.crd.yaml
  vendor/github.com/openshift/api/machine/v1beta1/types_machine.go
  vendor/github.com/openshift/api/monitoring/.codegen.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_insights-operator_00-insightsoperator.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_console-operator.crd.yaml
  vendor/github.com/openshift/api/operator/v1/stable.console.testsuite.yaml
  vendor/github.com/openshift/api/operator/v1/types_console.go
  vendor/github.com/openshift/api/operator/v1/types_insights.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update
