Repository openshift/origin, pull requests merged in 2023-02, with the labels that each got.

#27697 extended: security: do not explicitly set api audience on token request
  test/extended/security/scc.go
Labels: approved, lgtm

#27698 Update S2i image tests for dotnet3.1 EOL
  test/extended/image_ecosystem/s2i_images.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#27678 OCPBUGS-6503: upgrade/adminack: simplify polling and unblock "guaranteed" post-upgrade check
  test/extended/util/openshift/clusterversionoperator/adminack.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#27695 bump timeout
  test/extended/etcd/helpers/helpers.go
Labels: approved, lgtm

#27701 TRT-813: Disabling disruption fallback for upgrades
  pkg/synthetictests/allowedbackenddisruption/matches_test.go
  pkg/synthetictests/historicaldata/next_best_guess.go
Labels: approved, lgtm, jira/valid-reference

#27654 CNF-6711 filter storage tests
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm, tide/merge-method-squash

#27632 AUTH-337: PSa: add test for SCC-mutated PodSpec extraction
  test/extended/authorization/podsecurity_admission.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#27664 make supplemental groups test working again
  test/extended/security/scc.go
  test/extended/security/supplemental_groups.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#27623 OCPBUGS-3923: adjust watch budget for monitoring components
  test/extended/apiserver/api_requests.go
Labels: approved, lgtm, bugzilla/valid-bug, qe-approved, jira/valid-bug, jira/severity-moderate

#27682 STOR-1066: add e2e tests for CSIInlineVolumeAdmission plugin
  test/extended/include.go
  test/extended/storage/OWNERS
  test/extended/storage/inline.go
  test/extended/testdata/bindata.go
  test/extended/testdata/storage/inline/csi-sharedresourcerole.yaml
  test/extended/testdata/storage/inline/csi-sharedresourcerolebinding.yaml
  test/extended/testdata/storage/inline/csi-sharedsecret.yaml
  test/extended/testdata/storage/inline/secret.yaml
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, jira/valid-reference

#27685 OCPBUGS-6851: [release-4.11] upgrade/adminack: guarantee one admin ack check post-upgrade
  test/extended/util/openshift/clusterversionoperator/adminack.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#27710 Alert Testing on new Namespace and Level
  pkg/synthetictests/allowedalerts/allow_on_revision_change.go
  pkg/synthetictests/allowedalerts/basic_alert.go
  pkg/synthetictests/allowedalerts/matches.go
  pkg/synthetictests/allowedalerts/matches_test.go
  pkg/synthetictests/allowedalerts/query_results.json
  pkg/synthetictests/allowedalerts/types.go
  pkg/synthetictests/allowedbackenddisruption/matches_test.go
  pkg/synthetictests/allowedbackenddisruption/types.go
  pkg/synthetictests/historicaldata/alert_types.go
  pkg/synthetictests/historicaldata/disruption_types.go
Labels: approved, lgtm

#27709 Ensure NoColor for ginkgo in disruption/chamosmoney suite
  test/extended/util/disruption/disruption.go
Labels: approved, lgtm

#27708 BUILD-407: stage one of two of migrating shared resource from tech preview to GA
  test/extended/builds/volumes.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, jira/valid-reference

#27704 STOR-950: Add CI job for skipping StorageClass creation
  test/extended/storage/storageclass.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, jira/valid-reference

#27717 Add external disruption sampling in openshift test
  pkg/test/ginkgo/options_monitor_events.go
Labels: approved, lgtm

#27718 replace centos with ubi8 in build test dockerfile
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/docker-add/docker-add-env/Dockerfile
Labels: approved, lgtm

#27721 Add PDB to resource watch
  pkg/monitor/resourcewatch/operator/starter.go
Labels: approved, lgtm

#27618 Allow baremetal tests to run on GCP platform
  test/extended/baremetal/common.go
  test/extended/baremetal/hosts.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#27705 TRT-819: Add check for parse signature error
  pkg/monitor/intervalcreation/node.go
  pkg/monitor/intervalcreation/node_test.go
  pkg/monitor/monitorapi/identification_pod.go
  pkg/synthetictests/allowedalerts/basic_alert.go
  pkg/synthetictests/event_junits.go
  pkg/synthetictests/kubelet.go
Labels: approved, lgtm, jira/valid-reference

#27669 WRKLDS-577: Migrate templates.sh to template.go
  test/extended/cli/template.go
  test/extended/testdata/bindata.go
  test/extended/testdata/cmd/test/cmd/templates.sh
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, tide/merge-method-squash

#27456 Kubevirt network connectivity tests
  OWNERS_ALIASES
  test/extended/kubevirt/OWNERS
  test/extended/kubevirt/services.go
  test/extended/kubevirt/util.go
Labels: approved, lgtm

#27720 BUILD-407: perform build csi volume test on GA clusters
  test/extended/builds/volumes.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, jira/valid-reference

#27649 Add pathological events into spyglass charts
  e2echart/e2e-chart-template.html
  pkg/duplicateevents/duplicated_event_patterns.go
  pkg/monitor/event.go
  pkg/monitor/event_test.go
  pkg/monitor/intervalcreation/rendering.go
  pkg/synthetictests/apiserver.go
  pkg/synthetictests/duplicated_events.go
  pkg/synthetictests/duplicated_events_special.go
  pkg/synthetictests/duplicated_events_test.go
  pkg/synthetictests/marketplace.go
  pkg/synthetictests/networking.go
  test/extended/testdata/bindata.go
Labels: approved, lgtm

#27719 Chart CI cluster DNS problems in different color from disruption
  e2echart/e2e-chart-template.html
  test/extended/testdata/bindata.go
Labels: approved, lgtm

#27722 OCPBUGS-7319: Unskip service session affinity tests
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference

#27715 OCPBUGS-6902: Wait for DNS DS pods to be ready
  test/e2e/upgrade/dns/dns.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#27573 Allow baremetal tests to run on Azure platform
  test/extended/baremetal/common.go
  test/extended/baremetal/hosts.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#27687 audit inspection
  cmd/openshift-tests/openshift-tests.go
  pkg/monitor/intervalcreation/node.go
  pkg/monitor/intervalcreation/types.go
  pkg/monitor/nodedetails/audit_log_loadbalancer_summary.go
  pkg/monitor/nodedetails/audit_log_summarizer.go
  pkg/monitor/nodedetails/audit_log_summary_serialization.go
  pkg/monitor/nodedetails/cmd.go
  pkg/monitor/nodedetails/node_log.go
  pkg/test/ginkgo/options_monitor_events.go
Labels: approved, lgtm

#27729 Do not bail on producing artifacts when nodes are dead
  pkg/monitor/intervalcreation/node.go
  pkg/test/ginkgo/options_monitor_events.go
Labels: approved, lgtm

#27727 OCPBUGS-1125: remove reference to old guard pods
  test/extended/dr/quorum_restore.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-low, jira/valid-reference

#27730 Revert "perform build csi volume test on GA clusters"
  test/extended/builds/volumes.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#27726 OCPBUGS-7488: test flake: should not reconcile SC when state is Unmanaged
  test/extended/storage/storageclass.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-low, jira/valid-reference

#27734 Revert "Alert Testing on new Namespace and Level"
  pkg/synthetictests/allowedalerts/allow_on_revision_change.go
  pkg/synthetictests/allowedalerts/basic_alert.go
  pkg/synthetictests/allowedalerts/matches.go
  pkg/synthetictests/allowedalerts/matches_test.go
  pkg/synthetictests/allowedalerts/query_results.json
  pkg/synthetictests/allowedalerts/types.go
  pkg/synthetictests/allowedbackenddisruption/matches_test.go
  pkg/synthetictests/allowedbackenddisruption/types.go
  pkg/synthetictests/historicaldata/alert_types.go
  pkg/synthetictests/historicaldata/types.go
Labels: approved, lgtm

#27681 test/extended/authorization/rbac: Condition console RBAC on 'Console' capability
  test/extended/authorization/rbac/groups_default_rules.go
Labels: approved, lgtm

#27740 OCPVE-278: feat: add rt tests package to openshift-tests
  images/tests/Dockerfile.rhel
Labels: approved, lgtm, jira/valid-reference

#27747 OCPBUGS-7519: Skip nfs tests temporarilly
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-critical, jira/valid-reference

#27742 Restore alert refactor with fix for disruption tests all being skipped
  pkg/synthetictests/allowedalerts/allow_on_revision_change.go
  pkg/synthetictests/allowedalerts/basic_alert.go
  pkg/synthetictests/allowedalerts/matches.go
  pkg/synthetictests/allowedalerts/matches_test.go
  pkg/synthetictests/allowedalerts/query_results.json
  pkg/synthetictests/allowedalerts/types.go
  pkg/synthetictests/allowedbackenddisruption/matches_test.go
  pkg/synthetictests/allowedbackenddisruption/types.go
  pkg/synthetictests/historicaldata/alert_types.go
  pkg/synthetictests/historicaldata/disruption_types.go
Labels: approved, lgtm

#27749 OCPVE-278: fix: multi build error, only add rt-tests for x86
  images/tests/Dockerfile.rhel
Labels: approved, lgtm, jira/valid-reference

#27745 OCPBUGS-7833: Rework no optional capabilities rules
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-important, jira/valid-reference

#27750 Fix defunct owners file in test/extended/util/annotate
  test/extended/util/annotate/OWNERS
Labels: approved, lgtm

#27753 Switch to readyz path for health probes on Azure
  test/e2e/upgrade/service/service.go
Labels: approved, lgtm

#27713 STOR-1077: promote CSIInlineVolumeAdmission feature gate to GA
  test/extended/storage/inline.go
Labels: approved, lgtm, jira/valid-reference
