Repository openshift/origin, pull requests merged in 2023-11, with the labels that each got.

#28363 OCPBUGS-22703: tolerate AWS edge nodes on monitor tests
  pkg/monitortests/network/disruptionpodnetwork/host-network-target-deployment.yaml
  pkg/monitortests/network/disruptionpodnetwork/host-network-to-host-network-poller-deployment.yaml
  pkg/monitortests/network/disruptionpodnetwork/host-network-to-pod-network-poller-deployment.yaml
  pkg/monitortests/network/disruptionpodnetwork/host-network-to-service-poller-deployment.yaml
  pkg/monitortests/network/disruptionpodnetwork/pod-network-target-deployment.yaml
  pkg/monitortests/network/disruptionpodnetwork/pod-network-to-host-network-poller-deployment.yaml
  pkg/monitortests/network/disruptionpodnetwork/pod-network-to-pod-network-poller-deployment.yaml
  pkg/monitortests/network/disruptionpodnetwork/pod-network-to-service-poller-deployment.yaml
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#28371 TRT-1340: Increase cmd support for ExactMonitorTests and DisableMonitorTests
  pkg/cmd/openshift-tests/monitor/run/run_monitor_command.go
  pkg/cmd/openshift-tests/run-test/command.go
  pkg/cmd/openshift-tests/run-upgrade/flags.go
  pkg/cmd/openshift-tests/run-upgrade/options.go
  pkg/cmd/openshift-tests/run/flags.go
  pkg/cmd/openshift-tests/run/options.go
  pkg/defaultmonitortests/types.go
  pkg/monitor/monitorapi/types.go
  pkg/monitor/serialization/serialize.go
  pkg/monitortestframework/types.go
  pkg/test/ginkgo/cmd_runsuite.go
  pkg/test/ginkgo/cmd_runtest.go
Labels: approved, lgtm, jira/valid-reference

#28370 skip revisioned certificates in raw info
  go.mod
  go.sum
  test/extended/operators/certs.go
  vendor/github.com/openshift/library-go/pkg/certs/cert-inspection/certgraphanalysis/collector.go
  vendor/github.com/openshift/library-go/pkg/certs/cert-inspection/certgraphanalysis/options.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, jira/valid-reference

#28366 OCPBUGS-20479: Add pod sandbox failures to e2e charts
  e2echart/e2e-chart-template.html
  pkg/monitor/serialization/serialize.go
  pkg/monitortests/network/legacynetworkmonitortests/networking.go
  pkg/monitortests/testframework/watchevents/event.go
  test/extended/testdata/bindata.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-low, jira/valid-reference

#28323 OCPBUGS-19527: retry Prometheus client creation
  test/extended/util/client.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#28379 trt-1344: remove msg assertion
  pkg/monitortestlibrary/allowedalerts/matches_test.go
Labels: approved, lgtm, jira/valid-reference

#28381 TRT-1339: Revert #28233 "ignore repeated TopologyAwareHintsDisabled events"
  pkg/monitortestlibrary/pathologicaleventlibrary/duplicated_event_patterns.go
  pkg/monitortests/testframework/watchevents/event_test.go
Labels: approved, lgtm, jira/valid-reference

#28380 trt-1340: update run-upgrade to use ginkgorunsuiteoptions
  pkg/cmd/openshift-tests/run-upgrade/options.go
Labels: approved, lgtm, jira/valid-reference

#28372 "TRT-1342: Trim the intervals for loki serializer to avoid errors during ingest"
  pkg/monitor/monitorapi/types.go
  pkg/monitortests/testframework/uploadtolokiserializer/monitortest.go
Labels: approved, lgtm, jira/valid-reference

#28320 OCPBUGS-18776: [sig-instrumentation] tests fail due to JSON parsing error.
  test/extended/prometheus/prometheus.go
  test/extended/util/prometheus/helpers.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#28376 TRT-1354: Add support for intervals to have row differentiators
  e2echart/e2e-chart-template.html
  e2echart/non-spyglass-e2e-chart-template.html
  pkg/monitor/monitorapi/construction.go
  pkg/monitor/monitorapi/types.go
  pkg/monitor/serialization/serialize.go
  pkg/monitortestlibrary/statetracker/state_tracker.go
  pkg/monitortests/node/nodestateanalyzer/node.go
  pkg/monitortests/node/nodestateanalyzer/nodeTest/drain-01/expected.json
  pkg/monitortests/node/nodestateanalyzer/nodeTest/drain-02/expected.json
  pkg/monitortests/node/nodestateanalyzer/node_test.go
  pkg/monitortests/node/watchpods/compute_intervals.go
  test/extended/testdata/bindata.go
Labels: approved, lgtm, jira/valid-reference

#28352 OCPBUGS-23084: expect to not see "git clone" and not just "clone" during a test
  test/extended/builds/proxy.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#28389 OCPBUGS-23102: Revert "[sig-instrumentation] tests fail due to JSON parsing error."
  test/extended/prometheus/prometheus.go
  test/extended/util/prometheus/helpers.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#28388 OCPBUGS-23079: fix: increase watch count for KubeControllerManagerOperator
  test/extended/apiserver/api_requests.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#28386 Revert "TRT-1339: Revert #28233 "ignore repeated TopologyAwareHintsDisabled events""
  pkg/monitortestlibrary/pathologicaleventlibrary/duplicated_event_patterns.go
  pkg/monitortestlibrary/pathologicaleventlibrary/duplicated_events.go
  pkg/monitortestlibrary/pathologicaleventlibrary/duplicated_events_test.go
  pkg/monitortests/testframework/watchevents/event_test.go
Labels: approved, lgtm, jira/valid-reference

#28204 ignore stale condition challenge events
  pkg/monitortestlibrary/pathologicaleventlibrary/duplicated_event_patterns.go
Labels: approved, lgtm, jira/valid-reference

#28395 Certs 11 fix certs after break
  go.mod
  go.sum
  test/extended/operators/certs.go
  vendor/github.com/openshift/library-go/pkg/certs/cert-inspection/certgraphanalysis/collection_options.go
  vendor/github.com/openshift/library-go/pkg/certs/cert-inspection/certgraphanalysis/collector.go
  vendor/github.com/openshift/library-go/pkg/certs/cert-inspection/certgraphanalysis/metadata_options.go
  vendor/github.com/openshift/library-go/pkg/certs/cert-inspection/certgraphanalysis/options.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, jira/valid-reference, acknowledge-critical-fixes-only

#28396 [release-4.13] AUTH-443: Add oauth-server redirect URI validation e2e tests
  test/extended/oauth/redirect_uris.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#28405 collect certificate data: rewrite configmap/secret names
  go.mod
  go.sum
  test/extended/operators/certs.go
  vendor/github.com/openshift/library-go/pkg/certs/cert-inspection/certgraphanalysis/collection_options.go
  vendor/github.com/openshift/library-go/pkg/certs/cert-inspection/certgraphanalysis/collector.go
  vendor/github.com/openshift/library-go/pkg/certs/cert-inspection/certgraphanalysis/filtering_options.go
  vendor/github.com/openshift/library-go/pkg/certs/cert-inspection/certgraphanalysis/metadata_options.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, jira/valid-reference, acknowledge-critical-fixes-only

#28404 WRKLDS-908: test: ignore deprecation warnings in command outputs
  test/extended/images/hardprune.go
  test/extended/images/oc_tag.go
Labels: approved, lgtm, jira/valid-reference

#28368 Revert "[release-4.14] OCPBUGS-22720: Use Centos 8 Stream mysql image in tests"
  examples/image-streams/image-streams-centos7.json
  examples/sample-app/application-template-dockerbuild.json
  examples/sample-app/application-template-pullspecbuild.json
  examples/sample-app/application-template-stibuild.json
  test/extended/testdata/bindata.go
  test/extended/testdata/cmd/test/cmd/deployments.sh
  test/extended/testdata/cmd/test/cmd/testdata/application-template-dockerbuild.json
  test/extended/testdata/cmd/test/cmd/testdata/new-app/template-with-app-label.json
  test/extended/testdata/cmd/test/cmd/testdata/new-app/template-without-app-label.json
Labels: approved, lgtm, cherry-pick-approved, staff-eng-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#28394 update the TLS ownership files
  tls/ownership/ownership.md
  tls/ownership/tls-ownership.json
  tls/raw-data/raw-tls-artifacts-ha-amd64-aws-ovn.json
  tls/raw-data/raw-tls-artifacts-ha-amd64-aws-sdn.json
  tls/raw-data/raw-tls-artifacts-ha-amd64-azure-ovn.json
  tls/raw-data/raw-tls-artifacts-ha-amd64-azure-sdn.json
  tls/raw-data/raw-tls-artifacts-ha-amd64-gcp-ovn.json
  tls/raw-data/raw-tls-artifacts-ha-amd64-gcp-sdn.json
  tls/raw-data/raw-tls-artifacts-ha-amd64-metal-ovn.json
  tls/raw-data/raw-tls-artifacts-ha-amd64-metal-sdn.json
  tls/raw-data/raw-tls-artifacts-ha-amd64-vsphere-ovn.json
  tls/raw-data/raw-tls-artifacts-ha-amd64-vsphere-sdn.json
  tls/raw-data/raw-tls-artifacts-single-amd64-aws-ovn.json
  tls/violations/ownership/ownership-violations.json
Labels: approved, lgtm, jira/valid-reference

#28407 make it slightly easy to produce markdown with table of contents
  pkg/cmd/update-tls-artifacts/generate-owners/generate_owners_options.go
  pkg/cmd/update-tls-artifacts/generate-owners/markdown.go
  tls/ownership/ownership.md
Labels: approved, lgtm, jira/valid-reference

#28411 TRT-1235: Add ability to specify alerts that should never fire
  pkg/monitortestlibrary/allowedalerts/all.go
  pkg/monitortestlibrary/allowedalerts/basic_alert.go
  pkg/monitortestlibrary/allowedalerts/matches.go
Labels: approved, lgtm, jira/valid-reference

#28254 OCPCLOUD-2169: Check that CPMS does not rollout
  test/extended/machines/machines.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, tide/merge-method-squash, jira/valid-reference

#28415 trt-1367: Get JobType After Collection Ends
  pkg/monitortestlibrary/disruptionlibrary/disruption_invariant_adapter.go
Labels: approved, lgtm, jira/valid-reference

#28422 OCPCLOUD-2256: Increase cluster-capi-operator watch count
  test/extended/apiserver/api_requests.go
Labels: approved, lgtm, jira/valid-reference

#28397 OSASINFRA-3291: Remove Kuryr bits
  pkg/monitortests/network/legacynetworkmonitortests/networking.go
Labels: approved, lgtm, jira/valid-reference

#28426 eliminate the closed channel race in pod_log_streamer
  pkg/monitortestlibrary/podaccess/pod_log_streamer.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference
