Repository openshift/origin, pull requests merged in 2023-08, with the labels that each got.

#28114 oauth requestheaders: gather oauth-server logs as admin
  test/extended/oauth/requestheaders.go
Labels: approved, lgtm

#28107 refactor command line start for openshift-tests
  cmd/openshift-tests/openshift-tests.go
  cmd/openshift-tests/runsuite_flags.go
  cmd/openshift-tests/runsuite_options.go
  cmd/openshift-tests/runupgradesuite_flags.go
  cmd/openshift-tests/runupgradesuite_options.go
  pkg/clioptions/clusterdiscovery/provider.go
  pkg/clioptions/iooptions/oidc_options.go
  pkg/test/ginkgo/cmd_runsuite.go
  pkg/test/ginkgo/cmd_runtest.go
  pkg/test/ginkgo/options_monitor_events.go
  pkg/test_suite_definition/README.md
  pkg/testsuites/README.md
  pkg/testsuites/cni.go
  pkg/testsuites/filters.go
  pkg/testsuites/minimal.go
  pkg/testsuites/standard_suites.go
  pkg/testsuites/standard_suites_test.go
  pkg/testsuites/upgrade_suites.go
Labels: approved, lgtm

#28111 fix: workload partitioning - added more error handling for retry attempts
  test/extended/cpu_partitioning/crio.go
Labels: approved, lgtm

#28101 Update image mirroring instructions to handle uncompressed layers
  test/extended/util/image/README.md
Labels: approved, lgtm, e2e-images-update

#28110 OCPVE-292: OCPVE-293: OCPVE-294: feat: added a realtime latency test suite
  pkg/testsuites/standard_suites.go
  test/extended/kernel/OWNERS
  test/extended/kernel/kernel_rt_functional.go
  test/extended/kernel/kernel_rt_latency.go
  test/extended/kernel/tools.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, jira/valid-reference

#28116 Remove enabling multinetwork policy
  test/extended/networking/multinetpolicy.go
Labels: approved, lgtm

#28121 separate the run, run-upgrade, and run-test
  cmd/openshift-tests/openshift-tests.go
  pkg/clioptions/imagesetup/images.go
  pkg/clioptions/upgradeoptions/upgrade_options.go
  pkg/cmd/openshift-tests/images/images_command.go
  pkg/cmd/openshift-tests/run-test/command.go
  pkg/cmd/openshift-tests/run-upgrade/command.go
  pkg/cmd/openshift-tests/run-upgrade/flags.go
  pkg/cmd/openshift-tests/run-upgrade/options.go
  pkg/cmd/openshift-tests/run/command.go
  pkg/cmd/openshift-tests/run/flags.go
  pkg/cmd/openshift-tests/run/options.go
  pkg/defaultinvariants/types.go
  pkg/invariants/knownimagechecker/invariant.go
  pkg/test/ginkgo/cmd_runsuite.go
  test/extended/util/image/image.go
Labels: approved, lgtm, do-not-merge/hold, e2e-images-update

#28125 Add Fabio and remove Stefan from image approvers
  test/extended/util/image/OWNERS
Labels: approved, lgtm, e2e-images-update

#28128 expedient engineering: inject intervals into recorded events from out…
  pkg/cmd/monitor_command/timeline/timeline_command.go
  pkg/monitor/intervalcreation/types.go
  pkg/test/ginkgo/options_monitor_events.go
Labels: approved, lgtm

#28126 Remove exception on KubeSchedulerDown runbook
  test/extended/prometheus/prometheus.go
Labels: approved, lgtm

#28118 MON-1960: Remove exceptions for alert annotations
  test/extended/prometheus/prometheus.go
Labels: approved, lgtm, jira/valid-reference

#28120 Fix ClusterOperator tests that can only report failures
  pkg/synthetictests/operators.go
  pkg/synthetictests/platformidentification/operator_mapping.go
Labels: approved, lgtm

#28141 return calculated intervals
  pkg/invariants/e2etestanalyzer/invariant.go
  pkg/invariants/nodestateanalyzer/invariant.go
  pkg/invariants/operatorstateanalyzer/invariant.go
Labels: approved

#28138 OCPBUGS-16615: Moving Prometheus reporting telemetry to serial jobs
  pkg/test/ginkgo/testNames.txt
  pkg/testsuites/minimal.go
  test/extended/prometheus/prometheus.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#28143 remove unnecessary global modification from upgrade
  pkg/clioptions/upgradeoptions/upgrade_options.go
  pkg/cmd/openshift-tests/run-upgrade/options.go
Labels: approved, lgtm

#28070 USHIFT-1484: skip prometheus alerts for MicroShift
  test/extended/prometheus/prometheus.go
  test/extended/util/framework.go
Labels: approved, lgtm, jira/valid-reference

#27876 Bug OCPBUGS-6778: Correct condition for rejecting connection
  test/extended/csrapprover/csrapprover.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#28146 Disable EgressIP test termporarily due to OVN-K bug
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm

#28145 move the discovery filtering into suite filtering instead of post filtering
  pkg/clioptions/kubeconfig/defaulrestconfig.go
  pkg/clioptions/kubeconfig/discovery.go
  pkg/clioptions/suiteselection/group_filter.go
  pkg/clioptions/suiteselection/suite_flags.go
  pkg/cmd/openshift-tests/run-upgrade/command.go
  pkg/cmd/openshift-tests/run-upgrade/flags.go
  pkg/cmd/openshift-tests/run/command.go
  pkg/cmd/openshift-tests/run/flags.go
  pkg/test/ginkgo/cmd_runsuite.go
  pkg/test/ginkgo/group_filter.go
  pkg/test/ginkgo/test_suite.go
Labels: approved, lgtm

#28153 Fix kubevirt test flake caused by pod name collision
  test/extended/kubevirt/util.go
Labels: approved, lgtm

#28148 OCPBUGS-16166: disable 2 tests in preparation to land k8s 1.27.4
  pkg/test/ginkgo/test_suite.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#28154 Bug OCPBUGS-17483: Skip invariant load balancer test for OpenStack
  pkg/invariants/network/disruptionserviceloadbalancer/invariant.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#28158 Remove obsolete buildanalyzer tool
  tools/buildanalyzer/.gitignore
  tools/buildanalyzer/OWNERS
  tools/buildanalyzer/README.md
  tools/buildanalyzer/buildanalyzer.go
  tools/buildanalyzer/cmd/buildanalyzer.go
Labels: approved, lgtm

#28147 OCPBUGS-16166: Update to Kubernetes 1.27.4
  go.mod
  go.sum
  pkg/test/ginkgo/test_suite.go
  vendor/github.com/google/cadvisor/container/crio/handler.go
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccadmission/admission.go
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccmatching/matcher.go
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccmatching/provider.go
  vendor/k8s.io/apimachinery/pkg/runtime/converter.go
  vendor/k8s.io/apimachinery/pkg/util/wait/loop.go
  vendor/k8s.io/apiserver/pkg/server/options/etcd.go
  vendor/k8s.io/apiserver/pkg/server/storage/storage_factory.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/healthcheck.go
  vendor/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3.go
  vendor/k8s.io/apiserver/pkg/storage/storagebackend/factory/factory.go
  vendor/k8s.io/client-go/util/cert/cert.go
  vendor/k8s.io/kube-aggregator/pkg/apiserver/apiserver.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/openapiv3/aggregator/aggregator.go
  vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/aggregator.go
  vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go
  vendor/k8s.io/kubernetes/cmd/kube-proxy/app/server.go
  vendor/k8s.io/kubernetes/cmd/kube-proxy/app/server_others.go
  vendor/k8s.io/kubernetes/openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/admission/customresourcevalidation/customresourcevalidationregistration/cr_validation_registration.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/admission/customresourcevalidation/operator/deny_delete_cluster_operator_resource.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/openshiftkubeapiserver/patch.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/openshiftkubeapiserver/sdn_readyz_wait.go
  vendor/k8s.io/kubernetes/pkg/apis/core/validation/validation.go
  vendor/k8s.io/kubernetes/pkg/controller/daemon/daemon_controller.go
  vendor/k8s.io/kubernetes/pkg/controller/daemon/update.go
  vendor/k8s.io/kubernetes/pkg/controller/job/job_controller.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_pods.go
  vendor/k8s.io/kubernetes/pkg/kubelet/nodestatus/setters.go
  vendor/k8s.io/kubernetes/pkg/kubelet/preemption/preemption.go
  vendor/k8s.io/kubernetes/pkg/kubelet/status/status_manager.go
  vendor/k8s.io/kubernetes/pkg/proxy/node.go
  vendor/k8s.io/kubernetes/pkg/proxy/winkernel/hns.go
  vendor/k8s.io/kubernetes/pkg/registry/core/componentstatus/rest.go
  vendor/k8s.io/kubernetes/pkg/registry/core/componentstatus/validator.go
  vendor/k8s.io/kubernetes/pkg/registry/core/rest/storage_core.go
  vendor/k8s.io/kubernetes/pkg/scheduler/framework/types.go
  vendor/k8s.io/kubernetes/pkg/scheduler/internal/queue/scheduling_queue.go
  vendor/k8s.io/kubernetes/pkg/scheduler/schedule_one.go
  vendor/k8s.io/kubernetes/plugin/pkg/admission/imagepolicy/admission.go
  vendor/k8s.io/kubernetes/plugin/pkg/admission/serviceaccount/admission.go
  vendor/k8s.io/kubernetes/test/e2e/apimachinery/field_validation.go
  vendor/k8s.io/kubernetes/test/e2e/apps/daemon_set.go
  vendor/k8s.io/kubernetes/test/e2e/apps/statefulset.go
  vendor/k8s.io/kubernetes/test/e2e/apps/wait.go
  vendor/k8s.io/kubernetes/test/e2e/framework/get.go
  vendor/k8s.io/kubernetes/test/e2e/network/netpol/network_legacy.go
  vendor/k8s.io/kubernetes/test/e2e/scheduling/predicates.go
  vendor/k8s.io/kubernetes/test/e2e/storage/csi_mock/csi_storage_capacity.go
  vendor/k8s.io/kubernetes/test/e2e/storage/persistent_volumes-local.go
  vendor/k8s.io/kubernetes/test/utils/pki_helpers.go
  vendor/k8s.io/legacy-cloud-providers/vsphere/nodemanager.go
  vendor/k8s.io/legacy-cloud-providers/vsphere/vsphere.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, jira/valid-bug, jira/valid-reference

#28099 Refactor e2e-test intervals to use the new locator builder
  pkg/invariants/clusterversionoperator/legacycvoinvariants/operators.go
  pkg/invariants/clusterversionoperator/operatorstateanalyzer/e2etest.go
  pkg/invariants/testframework/e2etestanalyzer/e2etest.go
  pkg/invariants/testframework/timelineserializer/rendering.go
  pkg/monitor/monitorapi/construction.go
  pkg/monitor/monitorapi/identification.go
  pkg/monitor/monitorapi/types.go
  pkg/test/ginkgo/test_runner.go
Labels: approved, lgtm

#28160 Skip external service monitoring invariant for microshift
  pkg/invariants/testframework/disruptionexternalservicemonitoring/invariant.go
Labels: approved, lgtm

#28064 USHIFT-1464: skip TestFrontProxy for MicroShift
  test/extended/authentication/front_proxy.go
Labels: approved, lgtm, jira/valid-reference

#28163 Add some tests for event interval generation
  pkg/invariants/testframework/pathologicaleventanalyzer/invariant.go
  pkg/monitor/event.go
  pkg/monitor/event_test.go
  pkg/monitor/monitorapi/types.go
Labels: approved, lgtm

#28166 Add stlaz and p0lyn0mial to OWNERS
  OWNERS
Labels: approved, lgtm

#28175 fix microshift fix that broke all disruption
  pkg/invariants/kubeapiserver/disruptionlegacyapiservers/invariant.go
Labels: approved

#28129 OCPBUGS-15726: add tests for openapi v3
  test/extended/apiserver/openapiv3.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#28168 make monitor command separately runnable
  cmd/openshift-tests/openshift-tests.go
  images/tests/dev.Dockerfile
  pkg/clioptions/iooptions/io_options.go
  pkg/cmd/openshift-tests/monitor/monitor_command.go
  pkg/cmd/openshift-tests/monitor/run/run_monitor_command.go
  pkg/disruption/backend/core.go
  pkg/disruption/backend/disruption/handler.go
  pkg/disruption/backend/disruption/interval.go
  pkg/disruption/backend/shutdown/handler.go
  pkg/disruption/backend/shutdown/interval.go
  pkg/disruption/ci/backend_sampler.go
  pkg/disruption/ci/factory.go
  pkg/disruption/ci/factory_test.go
  pkg/disruption/ci/remote_sampler.go
  pkg/monitor/backenddisruption/disruption_backend_sampler.go
  pkg/monitor/backenddisruption/types.go
  pkg/monitor/monitor.go
  pkg/monitor/monitorapi/types.go
  pkg/monitor/recorder.go
  pkg/monitor/recorder_jsonl.go
  pkg/monitor/serialization/serialize.go
  pkg/monitor/shutdown/consumer.go
  pkg/monitor/shutdown/gatherer.go
  test/extended/util/image/image.go
Labels: approved, lgtm, e2e-images-update

#28170 only close node ready if the node was not ready before
  pkg/invariants/node/nodestateanalyzer/node.go
Labels: approved

#28178 stop sampling when we stop
  pkg/monitor/backenddisruption/disruption_backend_sampler.go
Labels: approved, lgtm

#28179 basic setup of podNetwork disruption tests
  pkg/defaultinvariants/types.go
  pkg/invariants/network/disruptionpodnetwork/invariant.go
  pkg/invariants/network/disruptionpodnetwork/namespace.yaml
  pkg/invariants/network/disruptionpodnetwork/pod-network-poller-deployment.yaml
  pkg/invariants/network/disruptionpodnetwork/pod-network-target-deployment.yaml
  pkg/invariants/network/disruptionpodnetwork/pod-network-target-service.yaml
  pkg/invariants/network/disruptionpodnetwork/poller-rolebinding.yaml
Labels: approved

#28186 add comments requested in review
  pkg/cmd/openshift-tests/disruption/disruption_command.go
  pkg/cmd/openshift-tests/disruption/watch-endpointslice/endpointslice_controller.go
Labels: approved, lgtm

#28184 update watch-endpoint-slices to usable shape
  images/tests/dev.Dockerfile
  pkg/cmd/openshift-tests/disruption/watch-endpointslice/endpointslice_controller.go
  pkg/cmd/openshift-tests/disruption/watch-endpointslice/watch_endpointslice_flags.go
  pkg/cmd/openshift-tests/disruption/watch-endpointslice/watch_endpointslice_options.go
  pkg/disruption/backend/sampler/remote.go
  pkg/disruption/ci/factory.go
  pkg/monitor/backenddisruption/disruption_backend_sampler.go
  pkg/monitor/backenddisruption/disruption_backend_sampler_test.go
  pkg/monitor/monitorapi/construction.go
  pkg/monitor/monitorapi/disruption.go
  pkg/monitor/monitorapi/identification.go
  pkg/monitor/monitorapi/types.go
  pkg/monitortestlibrary/disruptionlibrary/disruption_invariant_adapter.go
  pkg/monitortestlibrary/disruptionlibrary/lib.go
  pkg/monitortests/imageregistry/disruptionimageregistry/monitortest.go
  pkg/monitortests/network/disruptionpodnetwork/monitortest.go
  pkg/monitortests/network/disruptionpodnetwork/pod-network-poller-deployment.yaml
  pkg/monitortests/network/disruptionserviceloadbalancer/monitortest.go
  pkg/monitortests/network/legacynetworkmonitortests/disruption.go
  pkg/monitortests/testframework/disruptionexternalservicemonitoring/monitortest.go
  pkg/monitortests/testframework/disruptionserializer/monitortest.go
  pkg/monitortests/testframework/disruptionserializer/write_job_run_data_test.go
Labels: approved, lgtm

#28181 OCPBUGS-16615: Making prometheus telemetry test flake
  test/extended/prometheus/prometheus.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#28098 Add a test to flake if we see NetworkManager log "too many netlink events"
  pkg/monitor/monitorapi/types.go
  pkg/monitortests/network/legacynetworkmonitortests/monitortest.go
  pkg/monitortests/network/legacynetworkmonitortests/networking.go
  pkg/monitortests/node/kubeletlogcollector/node.go
  pkg/monitortests/node/kubeletlogcollector/node_test.go
Labels: approved, lgtm

#28142 add e2e non-functional test for required-scc SCCs
  test/extended/authorization/scc.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#28165 Fixes openshift-tests dry-run failure asking for KUBERNETES_MASTER
  pkg/cmd/openshift-tests/run/flags.go
Labels: approved, lgtm, ok-to-test

#28194 select poller image from payload
  pkg/cmd/openshift-tests/monitor/run/run_monitor_command.go
  pkg/cmd/openshift-tests/monitor/timeline/timeline_command.go
  pkg/cmd/openshift-tests/run-upgrade/options.go
  pkg/cmd/openshift-tests/run/options.go
  pkg/defaultmonitortests/types.go
  pkg/monitortestframework/types.go
  pkg/monitortests/network/disruptionpodnetwork/monitortest.go
  pkg/monitortests/network/disruptionpodnetwork/pod-network-poller-deployment.yaml
  pkg/test/ginkgo/cmd_runsuite.go
  pkg/test/ginkgo/cmd_runtest.go
Labels: approved, lgtm

#28197 tolerate cluster without clusterversion
  pkg/monitortests/network/disruptionpodnetwork/monitortest.go
Labels: approved, lgtm

#28180 OCPBUGS-17497: Skip invariant load balancer test for None platform
  pkg/monitortests/network/disruptionserviceloadbalancer/monitortest.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#28182 Fix possibility of intervals without from/to by requiring when we Build()
  pkg/monitor/monitorapi/construction.go
  pkg/monitortests/node/kubeletlogcollector/node.go
  pkg/monitortests/testframework/alertanalyzer/alerts.go
  pkg/monitortests/testframework/e2etestanalyzer/e2etest.go
Labels: approved, lgtm

#28198 fail if no sampler output is found for the poller
  pkg/monitortests/network/disruptionpodnetwork/host-network-target-deployment.yaml
  pkg/monitortests/network/disruptionpodnetwork/host-network-target-service.yaml
  pkg/monitortests/network/disruptionpodnetwork/host-network-to-host-network-poller-deployment.yaml
  pkg/monitortests/network/disruptionpodnetwork/host-network-to-pod-network-poller-deployment.yaml
  pkg/monitortests/network/disruptionpodnetwork/monitortest.go
  pkg/monitortests/network/disruptionpodnetwork/pod-network-to-host-network-poller-deployment.yaml
  pkg/monitortests/network/disruptionpodnetwork/pod-network-to-pod-network-poller-deployment.yaml
Labels: approved

#28189 add host-to-pod disruption checking
  pkg/monitortests/network/disruptionpodnetwork/host-network-target-deployment.yaml
  pkg/monitortests/network/disruptionpodnetwork/host-network-target-service.yaml
  pkg/monitortests/network/disruptionpodnetwork/host-network-to-host-network-poller-deployment.yaml
  pkg/monitortests/network/disruptionpodnetwork/host-network-to-pod-network-poller-deployment.yaml
  pkg/monitortests/network/disruptionpodnetwork/monitortest.go
  pkg/monitortests/network/disruptionpodnetwork/pod-network-to-host-network-poller-deployment.yaml
  pkg/monitortests/network/disruptionpodnetwork/pod-network-to-pod-network-poller-deployment.yaml
Labels: approved

#28188 migrate some watching code to monitortests
  pkg/defaultmonitortests/types.go
  pkg/monitor/api.go
  pkg/monitor/monitor.go
  pkg/monitortests/node/watchnodes/monitortest.go
  pkg/monitortests/node/watchnodes/node.go
  pkg/monitortests/node/watchnodes/node_test.go
  pkg/monitortests/testframework/watchclusteroperators/monitortest.go
  pkg/monitortests/testframework/watchclusteroperators/operator.go
  pkg/monitortests/testframework/watchclusteroperators/operator_test.go
  pkg/monitortests/testframework/watchclusteroperators/watcher.go
  pkg/monitortests/testframework/watchevents/event.go
  pkg/monitortests/testframework/watchevents/event_test.go
  pkg/monitortests/testframework/watchevents/monitortest.go
Labels: approved, lgtm

#28209 fix *-to-host sampler failure calculation
  pkg/cmd/openshift-tests/disruption/watch-endpointslice/endpointslice_controller.go
  pkg/cmd/openshift-tests/disruption/watch-endpointslice/watch_endpointslice_flags.go
  pkg/cmd/openshift-tests/disruption/watch-endpointslice/watch_endpointslice_options.go
  pkg/monitor/backenddisruption/disruption_backend_sampler.go
  pkg/monitortests/network/disruptionpodnetwork/host-network-to-host-network-poller-deployment.yaml
  pkg/monitortests/network/disruptionpodnetwork/host-network-to-pod-network-poller-deployment.yaml
  pkg/monitortests/network/disruptionpodnetwork/pod-network-to-host-network-poller-deployment.yaml
Labels: approved, lgtm

#28207 if no openshift-tests image can be auto-detected or specified, skip it
  pkg/cmd/openshift-tests/disruption/watch-endpointslice/endpointslice_controller.go
  pkg/monitor/monitor.go
  pkg/monitortests/network/disruptionpodnetwork/monitortest.go
Labels: approved, lgtm

#28206 [WRKLDS-707] move PDBUnhealthyPodEvictionPolicy from TP to beta
  test/extended/poddisruptionbudget/poddisruptionbudget.go
  test/extended/testdata/bindata.go
  test/extended/testdata/poddisruptionbudgets/nginx-with-delayed-ready-deployment.yaml
Labels: approved, lgtm

#28212 Reduce usage of dcs
  test/extended/cli/basics.go
  test/extended/cli/policy.go
  test/extended/images/resolve.go
  test/extended/testdata/bindata.go
  test/extended/testdata/cmd/test/cmd/testdata/application-template-mix.json
  test/extended/testdata/deployments/deployment-simple-sleep.yaml
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#28219 [test/extended/networking] Rename ovnkube containers
  test/extended/networking/egressip_helpers.go
Labels: approved, lgtm

#28161 OCPBUGS-17477: requestheader: wait for only 3 oauth-servers to be available
  test/extended/oauth/requestheaders.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#28221 prevent secondary errors reported in prior steps
  pkg/monitortests/imageregistry/disruptionimageregistry/monitortest.go
  pkg/monitortests/kubeapiserver/disruptionlegacyapiservers/monitortest.go
  pkg/monitortests/network/disruptioningress/monitortest.go
  pkg/monitortests/network/disruptionserviceloadbalancer/monitortest.go
Labels: approved, lgtm

#28202 Service invariant
  pkg/cmd/openshift-tests/disruption/disruption_command.go
  pkg/cmd/openshift-tests/disruption/poll-service/poll_service_flags.go
  pkg/cmd/openshift-tests/disruption/poll-service/poll_service_options.go
  pkg/cmd/openshift-tests/disruption/poll-service/service_controller.go
  pkg/monitortests/network/disruptionpodnetwork/host-network-to-service-poller-deployment.yaml
  pkg/monitortests/network/disruptionpodnetwork/monitortest.go
  pkg/monitortests/network/disruptionpodnetwork/pod-network-to-service-poller-deployment.yaml
Labels: approved, lgtm

#27561 Fail on APIs removed in the next release
  test/extended/apiserver/api_requests.go
  test/extended/etcd/etcd_storage_path.go
  test/extended/etcd/etcd_test_runner.go
Labels: approved, lgtm

#28081 OCPBUGS-13158: in-cluster disruption: ensure that only one monitor is started in cluster
  pkg/clioptions/iooptions/io_options.go
  pkg/cmd/openshift-tests/monitor/run/run_monitor_command.go
  pkg/cmd/openshift-tests/run-disruption/disruption.go
  pkg/defaultmonitortests/types.go
  pkg/disruption/backend/sampler/remote.go
  pkg/disruption/ci/backend_sampler.go
  pkg/disruption/ci/factory.go
  pkg/disruption/ci/host_decoder.go
  pkg/disruption/ci/remote_sampler.go
  pkg/monitortestframework/impl.go
  pkg/monitortestframework/panic.go
  pkg/monitortestframework/types.go
  pkg/monitortestlibrary/disruptionlibrary/collect.go
  pkg/monitortests/kubeapiserver/disruptionnewapiserver/monitortest.go
  pkg/monitortests/kubeapiserver/incluster_disruption_serializer/manifests/crb-hostaccess.yaml
  pkg/monitortests/kubeapiserver/incluster_disruption_serializer/manifests/crb-monitor.yaml
  pkg/monitortests/kubeapiserver/incluster_disruption_serializer/manifests/dep-internal-lb.yaml
  pkg/monitortests/kubeapiserver/incluster_disruption_serializer/manifests/dep-localhost.yaml
  pkg/monitortests/kubeapiserver/incluster_disruption_serializer/manifests/dep-service-network.yaml
  pkg/monitortests/kubeapiserver/incluster_disruption_serializer/manifests/namespace.yaml
  pkg/monitortests/kubeapiserver/incluster_disruption_serializer/manifests/role-monitor.yaml
  pkg/monitortests/kubeapiserver/incluster_disruption_serializer/manifests/serviceaccount.yaml
  pkg/monitortests/kubeapiserver/incluster_disruption_serializer/remote.go
  pkg/monitortests/network/disruptionpodnetwork/monitortest.go
  pkg/test/ginkgo/cmd_runsuite.go
  test/extended/util/disruption/controlplane/known_backends.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#28227 Revert "Fail on APIs removed in the next release"
  test/extended/apiserver/api_requests.go
  test/extended/etcd/etcd_storage_path.go
  test/extended/etcd/etcd_test_runner.go
Labels: approved

#28224 created persistent volume claims can not exceed the limitation
  test/extended/quota/resourcequota.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm

#28230 Revert "in-cluster disruption: ensure that only one monitor is started in cluster"
  pkg/clioptions/iooptions/io_options.go
  pkg/cmd/openshift-tests/monitor/run/run_monitor_command.go
  pkg/cmd/openshift-tests/run-disruption/disruption.go
  pkg/defaultmonitortests/types.go
  pkg/disruption/backend/sampler/manifests/crb-hostaccess.yaml
  pkg/disruption/backend/sampler/manifests/crb-monitor.yaml
  pkg/disruption/backend/sampler/manifests/ds-internal-lb.yaml
  pkg/disruption/backend/sampler/manifests/ds-localhost.yaml
  pkg/disruption/backend/sampler/manifests/ds-service-network.yaml
  pkg/disruption/backend/sampler/manifests/namespace.yaml
  pkg/disruption/backend/sampler/manifests/role-monitor.yaml
  pkg/disruption/backend/sampler/manifests/serviceaccount.yaml
  pkg/disruption/backend/sampler/remote.go
  pkg/disruption/ci/backend_sampler.go
  pkg/disruption/ci/factory.go
  pkg/disruption/ci/host_decoder.go
  pkg/disruption/ci/remote_sampler.go
  pkg/monitortestframework/impl.go
  pkg/monitortestframework/panic.go
  pkg/monitortestframework/types.go
  pkg/monitortestlibrary/disruptionlibrary/collect.go
  pkg/monitortests/kubeapiserver/disruptionnewapiserver/monitortest.go
  pkg/monitortests/kubeapiserver/incluster_disruption_serializer/remote.go
  pkg/monitortests/network/disruptionpodnetwork/monitortest.go
  pkg/test/ginkgo/cmd_runsuite.go
  test/extended/util/disruption/controlplane/known_backends.go
Labels: approved, lgtm
