Repository openshift/origin, pull requests merged in 2024-08, with the labels that each got.

#28961 NO-JIRA: riskanalysis: improve request retries
  pkg/riskanalysis/cmd.go
  pkg/riskanalysis/cmd_test.go
Labels: approved, lgtm, jira/valid-reference

#28968 NO-JIRA: Disable:Broken for [sig-builds][Feature:Builds][Slow] can use private repositories as build input build using an HTTP token should be able to clone source code via an HTTP token [apigroup:build.openshift.io]
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm, jira/valid-reference

#28944 OCPBUGS-18865: Reapply "Merge pull request #28277 from vrutkovs/in-cluster-fixes-v3"
  pkg/clioptions/iooptions/io_options.go
  pkg/cmd/openshift-tests/monitor/run/run_monitor_command.go
  pkg/cmd/openshift-tests/run-disruption/disruption.go
  pkg/defaultmonitortests/types.go
  pkg/disruption/ci/backend_sampler.go
  pkg/disruption/ci/factory.go
  pkg/disruption/ci/host_decoder.go
  pkg/monitortestframework/types.go
  pkg/monitortestlibrary/disruptionlibrary/collect.go
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/clusterrole-monitor.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/crb-monitor.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/crb-privileged.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/dep-internal-lb.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/dep-localhost.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/dep-service-network.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/namespace.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/rb-monitor.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/role-monitor.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/serviceaccount.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/remote.go
  pkg/monitortests/kubeapiserver/disruptionnewapiserver/monitortest.go
  pkg/monitortests/network/disruptionpodnetwork/monitortest.go
  pkg/test/ginkgo/cmd_runsuite.go
  test/extended/operators/manifests/pod.yaml
  test/extended/util/disruption/controlplane/known_backends.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#28973 OCPBUGS-37245: Ignore pod sandbox adds expected to fail
  pkg/monitortests/network/legacynetworkmonitortests/networking.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#28975 IR-471: Skipping chunksizemib tests
  test/extended/storage/s3_configuration.go
Labels: approved, lgtm, jira/valid-reference

#28977 OCPBUGS-37986: Revert #28944 " Reapply \"Merge pull request #28277 from vrutkovs/in-cluster-fixes-v3\
  pkg/clioptions/iooptions/io_options.go
  pkg/cmd/openshift-tests/monitor/run/run_monitor_command.go
  pkg/cmd/openshift-tests/run-disruption/disruption.go
  pkg/defaultmonitortests/types.go
  pkg/disruption/ci/backend_sampler.go
  pkg/disruption/ci/factory.go
  pkg/disruption/ci/host_decoder.go
  pkg/monitortestframework/types.go
  pkg/monitortestlibrary/disruptionlibrary/collect.go
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/clusterrole-monitor.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/crb-monitor.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/crb-privileged.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/dep-internal-lb.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/dep-localhost.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/dep-service-network.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/namespace.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/rb-monitor.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/role-monitor.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/serviceaccount.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/remote.go
  pkg/monitortests/kubeapiserver/disruptionnewapiserver/monitortest.go
  pkg/monitortests/network/disruptionpodnetwork/monitortest.go
  pkg/test/ginkgo/cmd_runsuite.go
  test/extended/operators/manifests/pod.yaml
  test/extended/util/disruption/controlplane/known_backends.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#28969 OCPBUGS-37837: vertical scaling test should not rely on CPMS replicas
  test/extended/etcd/helpers/helpers.go
  test/extended/etcd/vertical_scaling.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#28978 TRT-1688: Revert "allow etcd log test to flake under vsphere"
  pkg/monitortests/etcd/legacyetcdmonitortests/etcd.go
  pkg/monitortests/etcd/legacyetcdmonitortests/monitortest.go
Labels: approved, lgtm, jira/valid-reference

#28979 OCPEDGE-1182: fix: remove un-needed test
  test/extended/node_tuning/node_tuning.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, jira/valid-reference

#28980 OCPEDGE-1033: fix: making oslat test more dynamic to handle different cpu sets
  test/extended/kernel/tools.go
Labels: approved, lgtm, jira/valid-reference

#28945 SDN-4919: NetworkSegmentation: Add tests for EndpointSlices mirror controller
  test/extended/networking/network_segmentation.go
  test/extended/networking/network_segmentation_endpointslice_mirror.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  zz_generated.manifests/test-reporting.yaml
Labels: approved, lgtm, jira/valid-reference

#28984 TRT-1723: riskanalysis: pass along errors from API request
  pkg/riskanalysis/cmd.go
  pkg/riskanalysis/cmd_test.go
Labels: approved, lgtm, jira/valid-reference

#28967 STOR-1819: Add OpenShift specific CSI certification test
  pkg/clioptions/clusterdiscovery/csi.go
  pkg/clioptions/clusterdiscovery/provider.go
  pkg/testsuites/standard_suites.go
  test/extended/storage/csi/README.md
  test/extended/storage/csi/csi.go
  test/extended/storage/csi/scsi_overflow.go
Labels: approved, lgtm, docs-approved, qe-approved, px-approved, jira/valid-reference

#28793 NO-JIRA: drop ocp-storage exceptions for termination policy
  pkg/monitortests/clusterversionoperator/terminationmessagepolicy/monitortest.go
Labels: approved, lgtm, jira/valid-reference

#28986 NO-JIRA: create a test that repeatedly rolls out the kube-apiserver and uses m…
  pkg/testsuites/standard_suites.go
  test/extended/apiserver/resiliency.go
  test/extended/apiserver/rollout.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, jira/valid-reference

#28848 STOR-1839: run vsphere driver config test on non techpreview clusters
  test/extended/storage/driver_configuration.go
Labels: approved, lgtm, jira/valid-reference

#28912 [release-4.15] OCPBUGS-36264: add Proxy config
  test/extended/router/h2spec.go
  test/extended/router/http2.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference

#28997 OCPBUGS-38359: NetworkSegmentation tests: fix the IPv6 node IP detection
  test/extended/networking/network_segmentation_endpointslice_mirror.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#28976 Revert "IR-471: Skipping chunksizemib tests"
  test/extended/storage/s3_configuration.go
Labels: approved, lgtm, jira/valid-reference

#28965 SO-126: Sync the list of tests for s2i images with the image versions available in the library
  test/extended/image_ecosystem/s2i_images.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, ok-to-test, tide/merge-method-squash, jira/valid-reference

#28989 OCPBUGS-38061: add unexpected ready for monitor tests
  pkg/monitor/monitorapi/types.go
  pkg/monitortests/node/watchnodes/monitortest.go
  pkg/monitortests/node/watchnodes/node.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#29011 NO-JIRA: add important resources to watch
  cmd/openshift-tests/openshift-tests.go
  pkg/cmd/openshift-tests/run_resource_watch/resourcewatch.go
  pkg/resourcewatch/operator/starter.go
Labels: approved, lgtm, jira/valid-reference

#28996 WRKLDS-1431: e2e: extend DC testing to Deployments
  test/extended/cli/debug.go
  test/extended/cli/env.go
  test/extended/cli/idle.go
  test/extended/cli/run.go
  test/extended/cli/setimage.go
  test/extended/cli/timeout.go
  test/extended/idling/idling.go
  test/extended/images/resolve.go
  test/extended/testdata/bindata.go
  test/extended/testdata/cmd/test/cmd/testdata/idling-deployment.yaml
  test/extended/testdata/cmd/test/cmd/testdata/test-deployment.yaml
  test/extended/testdata/idling-echo-server-deployment.yaml
  test/extended/testdata/test-deployment.yaml
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm, jira/valid-reference

#29015 NO-JIRA: new test for detecting ungraceful kube-apiserver termination by kubelet
  test/extended/apiserver/graceful_termination.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, jira/valid-reference

#29016 NO-JIRA: apiserver/graceful_termination: simplify condition for "kubelet terminates kube-apiserver gracefully extended" test
  test/extended/apiserver/graceful_termination.go
Labels: approved, lgtm, jira/valid-reference

#29017 NO-JIRA: rename unexpected node unreachable and add unreachable interval
  pkg/monitor/monitorapi/types.go
  pkg/monitortests/node/watchnodes/monitortest.go
  pkg/monitortests/node/watchnodes/node.go
Labels: approved, lgtm, jira/valid-reference

#29019 NO-JIRA: Tame some build-log.txt output
  pkg/monitortests/testframework/metricsendpointdown/metricsendpointdown.go
Labels: approved, lgtm, jira/valid-reference

#29023 WRKLDS-1449: Update etcd test data for 1.31 release
  test/extended/etcd/etcd_storage_path.go
Labels: approved, lgtm, jira/valid-reference

#29027 NO-JIRA: Expand approvers for origin
  OWNERS
Labels: approved, lgtm, jira/valid-reference

#29028 OCPBUGS-38805: fix: removed grouping flag for jq
  test/extended/cpu_partitioning/crio.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#28990 OCPBUGS-38792: Try also user CA for getting openshift-tests image
  pkg/monitortests/network/disruptionpodnetwork/utils.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#29030 WRKLDS-1449: remove create job extended test in favor of the upstream ones
  pkg/test/ginkgo/testNames.txt
  pkg/testsuites/minimal.go
  test/extended/include.go
  test/extended/jobs/jobs.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm, jira/valid-reference

#29003 OCPBUGS-38859: add api-unreachable-from-client monitor test
  e2echart/e2e-chart-template.html
  pkg/defaultmonitortests/types.go
  pkg/monitor/monitorapi/construction.go
  pkg/monitor/monitorapi/types.go
  pkg/monitortests/kubeapiserver/apiunreachablefromclientmetrics/monitortest.go
  pkg/monitortests/kubeapiserver/apiunreachablefromclientmetrics/monitortest_test.go
  pkg/monitortests/kubeapiserver/apiunreachablefromclientmetrics/testdata/rest_client_metrics.json
  pkg/monitortests/metrics/metrics.go
  pkg/monitortests/metrics/rate_analyzer.go
  pkg/monitortests/metrics/rate_analyzer_test.go
  test/extended/testdata/bindata.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#28938 OCPBUGS-38788: [4.16] egressfirewall: skip ping tests in case of hypershift kubevirt on Azure infra
  test/extended/kubevirt/migration.go
  test/extended/kubevirt/services.go
  test/extended/kubevirt/util.go
  test/extended/networking/egress_firewall.go
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backport-risk-assessed, e2e-images-update, jira/valid-bug, jira/valid-reference

#29000 OCPBUGS-36891: Update OWNERS file in origin/test/extended/router
  test/extended/router/OWNERS
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/severity-low, jira/valid-reference

#29018 OCPBUGS-38650: fix: add check for sa secrets after ns creation
  pkg/monitortests/network/disruptionpodnetwork/monitortest.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#29026 NO-JIRA: monitor/recorder: snapshot makes copy before returning events
  pkg/monitor/recorder.go
Labels: approved, lgtm, jira/valid-reference

#29004 NO-JIRA: Additional job name verification tests
  test/extended/ci/job_names.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#29013 OCPBUGS-38435: deflake container restart tests
  pkg/monitortests/node/legacynodemonitortests/kubelet.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#28994 OCPBUGS-38787: [4.15] egressfirewall: skip ping tests in case of hypershift kubevirt on Azure infra
  test/extended/kubevirt/migration.go
  test/extended/kubevirt/services.go
  test/extended/kubevirt/util.go
  test/extended/networking/egress_firewall.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#29035 TRT-1777: Properly identify dual stack for cluster data
  pkg/monitortestlibrary/platformidentification/types.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#29032 NO-JIRA: add basic graceful lease checking
  pkg/defaultmonitortests/types.go
  pkg/monitor/monitor.go
  pkg/monitor/monitorapi/types.go
  pkg/monitortestlibrary/podaccess/one_time_pod_log_streamer.go
  pkg/monitortests/testframework/operatorloganalyzer/operator_lease_check.go
  pkg/monitortests/testframework/operatorloganalyzer/operator_log_scraper.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#29042 USHIFT-4090: Skip api-unreachable-from-client-metrics monitor in Micr…
  pkg/monitortests/kubeapiserver/apiunreachablefromclientmetrics/monitortest.go
Labels: approved, lgtm, jira/valid-reference

#29043 WRKLDS-1449: skip health handlers e2e for 1.31 rebase
  pkg/test/ginkgo/cmd_runsuite.go
Labels: approved, lgtm, jira/valid-reference

#29039 OCPBUGS-39030: kube-apiserver rollout: wait for stability before exiting
  test/extended/apiserver/rollout.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#29044 NO-JIRA: Turning the quorum guard back on at the end of test to leave the cluster in same state
  test/extended/dr/recovery.go
Labels: approved, lgtm, jira/valid-reference

#28698 OCPBUGS-31738: Bump timeout for the pod-network-service endpoints check
  pkg/monitortests/network/disruptionpodnetwork/monitortest.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#29046 NO-JIRA: allow http2 connection errors until the client tolerates it
  test/extended/apiserver/rollout.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#29050 NO-JIRA: Update ONWERS list to add current OLM members and remove former ones
  test/extended/olm/OWNERS
Labels: approved, lgtm, jira/valid-reference

#28982 OCPBUGS-18865: Reapply "Merge pull request #28944 from vrutkovs/in-cluster-fixes-v4"
  pkg/clioptions/iooptions/io_options.go
  pkg/cmd/openshift-tests/monitor/run/run_monitor_command.go
  pkg/cmd/openshift-tests/run-disruption/disruption.go
  pkg/defaultmonitortests/types.go
  pkg/disruption/ci/backend_sampler.go
  pkg/disruption/ci/factory.go
  pkg/disruption/ci/host_decoder.go
  pkg/monitor/monitorapi/disruption.go
  pkg/monitortestframework/types.go
  pkg/monitortestlibrary/disruptionlibrary/collect.go
  pkg/monitortestlibrary/disruptionlibrary/deployment.go
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/clusterrole-monitor.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/crb-monitor.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/crb-privileged.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/dep-internal-lb.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/dep-localhost.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/dep-service-network.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/namespace.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/rb-monitor.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/role-monitor.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/serviceaccount.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/remote.go
  pkg/monitortests/kubeapiserver/disruptionlegacyapiservers/monitortest.go
  pkg/monitortests/kubeapiserver/disruptionnewapiserver/monitortest.go
  pkg/monitortests/network/disruptionpodnetwork/monitortest.go
  pkg/monitortests/network/legacynetworkmonitortests/disruption.go
  pkg/test/ginkgo/cmd_runsuite.go
  test/extended/operators/manifests/pod.yaml
  test/extended/util/disruption/controlplane/known_backends.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#29048 OCPBUGS-39232: Change Operator Installed for Smoke Test
  test/extended/olm/olm.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/severity-important, jira/valid-reference

#29034 OCPBUGS-38859: add a test (that flakes) to detect faulty load balancer
  pkg/defaultmonitortests/types.go
  pkg/monitortests/kubeapiserver/faultyloadbalancer/monitortest.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#28958 ETCD-639: Add E2E test to check if etcd is able to block the rollout of a revision when the quorum is not safe
  test/extended/dr/common.go
  test/extended/dr/static_pod_rollouts.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, jira/valid-reference

#29002 TRT-1578: Enable operator degraded check
  pkg/monitortests/clusterversionoperator/legacycvomonitortests/operators.go
Labels: approved, lgtm, jira/valid-reference
