Repository openshift/origin, pull requests merged in 2024-07, with the labels that each got.

#28919 OCPBUGS-34949: test/extended: skip etcd leader change check on hypershift
  test/extended/etcd/leader_changes.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#28890 ETCD-611: update cert rotation tests
  pkg/testsuites/standard_suites.go
  test/extended/dr/cert_rotation.go
  test/extended/dr/common.go
  test/extended/dr/recovery.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, vendor-update, jira/valid-reference

#28920 NO-JIRA: fix: update skip logic for watchdog
  pkg/monitortestlibrary/allowedalerts/watchdog.go
Labels: approved, lgtm, jira/valid-reference

#28900 NO-JIRA: Always try to pull the the in-cluster test binary
  pkg/cmd/openshift-tests/run-upgrade/flags.go
  pkg/cmd/openshift-tests/run/flags.go
  pkg/test/ginkgo/cmd_runsuite.go
Labels: approved, lgtm, jira/valid-reference

#28917 OCPBUGS-36403: test/extended/util/openshift/clusterversionoperator/adminack: No nested framework.Fail
  test/extended/util/openshift/clusterversionoperator/adminack.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#28918 OCPBUGS-34902: Revert "NO-JIRA: test: skip crio test for rt runs"
  test/extended/cpu_partitioning/crio.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#28898 #28746 FIX [release-4.15] OCPBUGS-33023: update egressFWTestE2E image which contains ping binary
  test/extended/networking/egress_firewall.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#28899 #28745 FIX [release-4.14] OCPBUGS-33022: update egressFWTestE2E image which contains ping binary
  test/extended/networking/egress_firewall.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#28639 API-1802: watchevents: add cert rotation events
  pkg/monitortestlibrary/pathologicaleventlibrary/duplicated_event_patterns.go
  pkg/monitortests/testframework/watchevents/event.go
Labels: approved, lgtm, jira/valid-reference

#28930 OCPBUGS-36672: Shorten stabilization time for etcd profiles test
  test/extended/etcd/hardware_speed.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#28240 NO-JIRA: Fail on APIs removed in the next release
  pkg/monitortests/testframework/knownimagechecker/monitortest.go
  test/extended/apiserver/api_requests.go
  test/extended/cli/mustgather.go
  test/extended/etcd/etcd_storage_path.go
  test/extended/etcd/etcd_test_runner.go
  test/extended/networking/ipsec.go
  test/extended/util/clusterversion.go
  test/extended/util/oauthserver/oauthserver.go
  test/extended/util/openshift/clusterversionoperator/adminack.go
  test/extended/util/release.go
Labels: approved, lgtm, jira/valid-reference

#28936 STOR-1961: Fix vSphereDriverConfiguration tests
  test/extended/storage/driver_configuration.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#28916 NO-JIRA: egressfirewall: skip ping tests in case of hypershift kubevirt on Azure infra
  test/extended/kubevirt/migration.go
  test/extended/kubevirt/services.go
  test/extended/kubevirt/util.go
  test/extended/networking/egress_firewall.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#28852 OCPEDGE-1125: upkeep: add better logging for crio failures
  test/extended/cpu_partitioning/crio.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#28792 #28775 FIX [release-4.14] OCPBUGS-33367: monitor test fix to wait before connecting to a non-existent dns on PowerVS and IBMCloud platforms
  pkg/monitortests/network/disruptionserviceloadbalancer/monitortest.go
  test/extended/util/client.go
Labels: approved, lgtm, ok-to-test, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#28277 OCPBUGS-18865: add monitortest: in-cluster disruption monitors
  pkg/clioptions/iooptions/io_options.go
  pkg/cmd/openshift-tests/monitor/run/run_monitor_command.go
  pkg/cmd/openshift-tests/run-disruption/disruption.go
  pkg/defaultmonitortests/types.go
  pkg/disruption/ci/backend_sampler.go
  pkg/disruption/ci/factory.go
  pkg/disruption/ci/host_decoder.go
  pkg/monitortestframework/types.go
  pkg/monitortestlibrary/disruptionlibrary/collect.go
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/crb-monitor.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/crb-privileged.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/dep-internal-lb.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/dep-localhost.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/dep-service-network.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/namespace.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/role-monitor.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/serviceaccount.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/remote.go
  pkg/monitortests/kubeapiserver/disruptionnewapiserver/monitortest.go
  pkg/monitortests/network/disruptionpodnetwork/monitortest.go
  pkg/test/ginkgo/cmd_runsuite.go
  test/extended/operators/manifests/pod.yaml
  test/extended/util/disruption/controlplane/known_backends.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#28939 no-jira: e2e: check for deployer SA only when DeploymentConfig is enabled
  test/extended/util/client.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#28941 no-jira: e2e: check for deployer RB only when DeploymentConfig is enabled
  test/extended/util/client.go
Labels: approved, lgtm, jira/valid-reference

#28942 OCPBUGS-37411: Revert #28277 "OCPBUGS-18865: add monitortest: in-cluster disruption monitors"
  pkg/clioptions/iooptions/io_options.go
  pkg/cmd/openshift-tests/monitor/run/run_monitor_command.go
  pkg/cmd/openshift-tests/run-disruption/disruption.go
  pkg/defaultmonitortests/types.go
  pkg/disruption/ci/backend_sampler.go
  pkg/disruption/ci/factory.go
  pkg/disruption/ci/host_decoder.go
  pkg/monitortestframework/types.go
  pkg/monitortestlibrary/disruptionlibrary/collect.go
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/crb-monitor.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/crb-privileged.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/dep-internal-lb.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/dep-localhost.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/dep-service-network.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/namespace.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/role-monitor.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/serviceaccount.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/remote.go
  pkg/monitortests/kubeapiserver/disruptionnewapiserver/monitortest.go
  pkg/monitortests/network/disruptionpodnetwork/monitortest.go
  pkg/test/ginkgo/cmd_runsuite.go
  test/extended/operators/manifests/pod.yaml
  test/extended/util/disruption/controlplane/known_backends.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#28933 SDN-5133: Add udn test framework
  test/extended/networking/network_segmentation.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  zz_generated.manifests/test-reporting.yaml
Labels: approved, lgtm, vendor-update, jira/valid-reference

#28951 no-jira: e2e: mark tests as [apigroup:apps.openshift.io] dependent
  test/extended/cli/admin.go
  test/extended/cli/builds.go
  test/extended/templates/templateinstance_readiness.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, jira/valid-reference

#28952 [release-4.14] OCPBUGS-36800: Removes dependency on samples operator images
  test/extended/builds/contextdir.go
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/test-context-build.json
  test/extended/util/framework.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#28947 IR-471: Updating the test with skipper function
  test/extended/storage/helpers.go
  test/extended/storage/s3_configuration.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  zz_generated.manifests/test-reporting.yaml
Labels: approved, lgtm, jira/valid-reference

#28948 OCPEDGE-1181: bump(ocp/k8s): updating to pull in annotation fix for SNO conformance test
  go.mod
  go.sum
  vendor/k8s.io/kubernetes/openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  vendor/k8s.io/kubernetes/openshift-hack/e2e/annotate/rules.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, jira/valid-reference

#28953 OCPBUGS-35880: fix pod not returning success on 'Managed cluster should verify that nodes have no unexpected reboots'
  test/extended/machines/display_reboots_pod.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#28956 [release-4.15] OCPBUGS-37630: remove unused in-cluster monitoring code
  pkg/cmd/openshift-tests/monitor/run/run_monitor_command.go
  pkg/disruption/backend/sampler/manifests/crb-hostaccess.yaml
  pkg/disruption/backend/sampler/manifests/crb-monitor.yaml
  pkg/disruption/backend/sampler/manifests/ds-internal-lb.yaml
  pkg/disruption/backend/sampler/manifests/ds-localhost.yaml
  pkg/disruption/backend/sampler/manifests/ds-service-network.yaml
  pkg/disruption/backend/sampler/manifests/namespace.yaml
  pkg/disruption/backend/sampler/manifests/role-monitor.yaml
  pkg/disruption/backend/sampler/manifests/serviceaccount.yaml
  pkg/disruption/backend/sampler/remote.go
  pkg/disruption/ci/remote_sampler.go
  pkg/monitortests/kubeapiserver/disruptionnewapiserver/monitortest.go
  pkg/test/ginkgo/cmd_runsuite.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#28955 NO-ISSUE: Use external binary name on retry
  pkg/test/ginkgo/test_suite.go
Labels: approved, lgtm, jira/valid-reference

#28960 OCPBUGS-37675: Add a version command to openshift-tests
  cmd/openshift-tests/openshift-tests.go
  go.mod
  pkg/cmd/openshift-tests/images/images_command.go
  pkg/cmd/openshift-tests/render/test-report/render_test_report.go
  pkg/cmd/openshift-tests/version/version.go
  pkg/cmd/util.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#28964 SDN-4919: Skip network segmentation tests
  test/extended/networking/network_segmentation.go
Labels: approved, lgtm, jira/valid-reference
