Repository openshift/origin, pull requests merged in 2024-11, with the labels that each got.

#29229 SDN-5346: image, mirror kubevirt fedora guest image
  test/extended/util/image/image.go
  test/extended/util/image/zz_generated.txt
Labels: approved, lgtm, e2e-images-update, jira/valid-reference

#29180 NE-1815: Adapt router metrics tests for DCM support
  test/extended/router/metrics.go
Labels: approved, lgtm, jira/valid-reference

#29252 OPNET-606: on-prem: fix haproxy test to include openstack and vsphere
  pkg/monitortests/network/onpremhaproxy/monitortest.go
Labels: approved, lgtm, jira/valid-reference

#29260 NO-JIRA: Additional exceptions for ROSA CI
  pkg/monitortests/network/disruptionpodnetwork/monitortest.go
  test/extended/cpu_partitioning/pods.go
  test/extended/operators/daemon_set.go
  test/extended/pods/priorityclasses.go
  test/extended/prometheus/prometheus.go
Labels: approved, lgtm, jira/valid-reference

#29249 OPRUN-3579: Add happy-path operator-contoller test
  test/extended/olm/olmv1.go
  test/extended/testdata/bindata.go
  test/extended/testdata/olmv1/install-operator.yaml
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, jira/valid-reference

#29262 NO-ISSUE: skip boot image tests on single node tests
  test/extended/machine_config/boot_image_update_aws.go
  test/extended/machine_config/boot_image_update_gcp.go
  test/extended/machine_config/helpers.go
Labels: approved, lgtm, jira/valid-reference

#29190 NO-JIRA: Introduce version annotation test for Windows nodes
  test/extended/include.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/windows/OWNERS
  test/extended/windows/nodes.go
Labels: approved, lgtm, jira/valid-reference

#29266 NO-JIRA: Additional ROSA exceptions
  test/extended/operators/daemon_set.go
  test/extended/operators/resources.go
Labels: approved, lgtm, jira/valid-reference

#29271 TRT-1871: Revert #29266 "NO-JIRA: Additional ROSA exceptions"
  test/extended/operators/daemon_set.go
  test/extended/operators/resources.go
Labels: approved, lgtm, jira/valid-reference

#29273 TRT-1578: Add more exception for operator degraded cases
  pkg/monitortests/clusterversionoperator/legacycvomonitortests/operators.go
Labels: approved, lgtm, jira/valid-reference

#29277 NO-ISSUE: OLMv1: Remove progressing checks during API transition
  test/extended/olm/olmv1.go
Labels: approved, lgtm, jira/valid-reference

#29278 Revert "Reapply "OCPBUGS-18865: Reapply "Merge pull request #28944 from vrutkovs/in-cluster-fixes-v4"""
  pkg/clioptions/iooptions/io_options.go
  pkg/cmd/openshift-tests/dev/dev.go
  pkg/cmd/openshift-tests/monitor/run/run_monitor_command.go
  pkg/cmd/openshift-tests/run-disruption/disruption.go
  pkg/defaultmonitortests/types.go
  pkg/disruption/backend/disruption/interval.go
  pkg/disruption/ci/backend_sampler.go
  pkg/disruption/ci/factory.go
  pkg/disruption/ci/host_decoder.go
  pkg/monitor/monitorapi/disruption.go
  pkg/monitortestframework/types.go
  pkg/monitortestlibrary/disruptionlibrary/collect.go
  pkg/monitortestlibrary/disruptionlibrary/deployment.go
  pkg/monitortests/kubeapiserver/disruptionexternalapiserver/monitortest.go
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/clusterrole-monitor.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/crb-monitor.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/crb-privileged.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/dep-internal-lb.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/dep-localhost.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/dep-service-network.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/namespace.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/rb-monitor.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/role-monitor.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/serviceaccount.yaml
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/monitortest.go
  pkg/monitortests/kubeapiserver/disruptionlegacyapiservers/known_backends.go
  pkg/monitortests/kubeapiserver/disruptionlegacyapiservers/monitortest.go
  pkg/monitortests/kubeapiserver/disruptionnewapiserver/monitortest.go
  pkg/monitortests/network/disruptionpodnetwork/monitortest.go
  pkg/monitortests/network/legacynetworkmonitortests/disruption.go
  pkg/monitortests/network/legacynetworkmonitortests/monitortest.go
  pkg/test/ginkgo/cmd_runsuite.go
  test/extended/operators/manifests/pod.yaml
  test/extended/util/disruption/controlplane/known_backends.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#29281 NO-JIRA: More ROSA work for openshift-tests
  test/extended/apiserver/graceful_termination.go
  test/extended/operators/resources.go
Labels: approved, lgtm, jira/valid-reference

#29270 NO-JIRA: Newly created machine should belong to the same index and should be placed in the same availability zone as the deleted machine.
  test/extended/etcd/helpers/helpers.go
  test/extended/etcd/vertical_scaling.go
Labels: approved, lgtm, jira/valid-reference

#29269 OCPBUGS-44244: use node node in deleted machine phases
  pkg/monitortestlibrary/utility/utility.go
  pkg/monitortests/machines/watchmachines/machines.go
  pkg/monitortests/machines/watchmachines/monitortest.go
  pkg/monitortests/node/kubeletlogcollector/node.go
  pkg/monitortests/node/kubeletlogcollector/node_test.go
  pkg/monitortests/node/watchnodes/monitortest.go
  pkg/monitortests/node/watchnodes/node.go
  pkg/monitortests/node/watchnodes/node_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#29284 NO-JIRA: address `MetricsCollectionProfiles` failures on `metal` platform
  test/extended/prometheus/collection_profiles.go
Labels: approved, lgtm, jira/valid-reference

#29291 OCPBUGS-44381: ovn-k, udn crd e2e: Fix status report consumer assertion
  test/extended/networking/network_segmentation.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#29287 ovn-k, udn crd e2e: Fix status report consumer assertion
  test/extended/networking/network_segmentation.go
Labels: do-not-merge/work-in-progress

#29286 TRT-1761: kubelet disk pressure
  pkg/monitor/monitorapi/types.go
  pkg/monitortests/node/watchnodes/monitortest.go
  pkg/monitortests/node/watchnodes/node.go
Labels: approved, lgtm, jira/valid-reference

#29242 OPRUN-3570: Downstream testing of OpenShift Max Version property
  test/extended/olm/olmv1.go
  test/extended/testdata/bindata.go
  test/extended/testdata/olmv1/install-operator.yaml
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, jira/valid-reference

#29288 NO-JIRA: Re-add exceptions for OVN pods
  test/extended/operators/resources.go
Labels: approved, lgtm, jira/valid-reference

#29296 NO-JIRA: managed services: centralize definition of namespaces
  test/extended/operators/resources.go
  test/extended/pods/priorityclasses.go
  test/extended/util/managed_services.go
Labels: approved, lgtm, jira/valid-reference

#29285 NO-ISSUE: Disable olmv1 install test during API transision
  test/extended/olm/olmv1.go
Labels: approved, lgtm, jira/valid-reference

#29290 NO-ISSUE: Add Capability and FeatureGate checks to OLMv1 tests
  test/extended/olm/olmv1.go
  test/extended/testdata/bindata.go
  test/extended/testdata/olmv1/install-operator.yaml
  test/extended/util/annotate/generated/zz_generated.annotations.go
  zz_generated.manifests/test-reporting.yaml
Labels: approved, lgtm, jira/valid-reference

#29169 ETCD-657: add simple quorum restore test
  test/extended/dr/common.go
  test/extended/dr/recovery.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, jira/valid-reference

#29289 OCPBUGS-42532: Revert loosened policy test
  test/extended/cli/policy.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, jira/valid-bug, jira/valid-reference

#29303 Revert "NO-ISSUE: Add Capability and FeatureGate checks to OLMv1 tests"
  test/extended/olm/olmv1.go
  test/extended/testdata/bindata.go
  test/extended/testdata/olmv1/install-operator.yaml
  test/extended/util/annotate/generated/zz_generated.annotations.go
  zz_generated.manifests/test-reporting.yaml
Labels: approved, lgtm, jira/valid-reference

#29171 API-1789: tls: add /etc/kubernetes/kubeconfig to known CA bundles
  pkg/cmd/update-tls-artifacts/generate-owners/tlsmetadatainterfaces/helpers.go
  tls/autoregenerate-after-expiry/autoregenerate-after-expiry.json
  tls/autoregenerate-after-expiry/autoregenerate-after-expiry.md
  tls/descriptions/descriptions.json
  tls/descriptions/descriptions.md
  tls/ownership/ownership.json
  tls/ownership/ownership.md
  tls/violations/autoregenerate-after-expiry/autoregenerate-after-expiry-violations.json
  tls/violations/descriptions/descriptions-violations.json
Labels: approved, lgtm, jira/valid-reference

#29304 OCPBUGS-44662: Re-enable OLMv1 tests
  test/extended/olm/olmv1.go
  test/extended/testdata/bindata.go
  test/extended/testdata/olmv1/install-catalog.yaml
  test/extended/testdata/olmv1/install-operator.yaml
  test/extended/util/annotate/generated/zz_generated.annotations.go
  zz_generated.manifests/test-reporting.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#29280 CNV-41542: Remove obsolete storage capabilities report
  pkg/clioptions/clusterdiscovery/storagecaps.go
  pkg/cmd/openshift-tests/run/options.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#29313 OPRUN-3605: sig-olmv1: update all but one of the olmv1 tests to be skipped in disconnected testing
  test/extended/olm/olmv1.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  zz_generated.manifests/test-reporting.yaml
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#29314 NO-JIRA: test/extended: additional excludes for osd-gcp
  test/extended/cpu_partitioning/platform.go
  test/extended/cpu_partitioning/pods.go
  test/extended/operators/crd_must_be_stable.go
  test/extended/operators/qos.go
  test/extended/prometheus/prometheus.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#29316 OPRUN-3606: Add diagnostics to olmv1 tests
  test/extended/olm/olmv1.go
  test/extended/testdata/bindata.go
  test/extended/testdata/olmv1/install-operator.yaml
  test/extended/util/annotate/generated/zz_generated.annotations.go
  zz_generated.manifests/test-reporting.yaml
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#29135 OCPBUGS-42435: Enforce the required-scc monitor test and validate usage of non-standard OCP SCCs
  pkg/monitortests/authentication/requiredsccmonitortests/monitortest.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#29321 NO-JIRA: Revert "Enforce the required-scc monitor test and validate usage of non-standard OCP SCCs
  pkg/monitortests/authentication/requiredsccmonitortests/monitortest.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#29306 [release-4.17] OCPBUGS-44190: Fix UnexpectedNodeNotReady and UnexpectedNodeUnreachable
  pkg/monitortestlibrary/utility/utility.go
  pkg/monitortests/machines/watchmachines/machines.go
  pkg/monitortests/machines/watchmachines/monitortest.go
  pkg/monitortests/node/kubeletlogcollector/node.go
  pkg/monitortests/node/kubeletlogcollector/node_test.go
  pkg/monitortests/node/watchnodes/monitortest.go
  pkg/monitortests/node/watchnodes/node.go
  pkg/monitortests/node/watchnodes/node_test.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-low, jira/valid-reference

#29309 NO-JIRA: address malformed CMO configmap post-test
  test/extended/prometheus/collection_profiles.go
Labels: approved, lgtm, jira/valid-reference

#29318 TRT-1761: Allow the test for kubelet DiskPressure to fail job runs
  pkg/monitortests/node/watchnodes/monitortest.go
Labels: approved, lgtm, jira/valid-reference

#29308 NO-JIRA: watch CRDs
  pkg/resourcewatch/operator/starter.go
Labels: approved, lgtm, jira/valid-reference

#29325 NO-JIRA: add additional managed namespaces
  test/extended/util/managed_services.go
Labels: approved, lgtm, jira/valid-reference

#29330 TRT-1898: Revert "NO-JIRA: address malformed CMO configmap post-test"
  test/extended/prometheus/collection_profiles.go
Labels: approved, lgtm, jira/valid-reference
