Repository openshift/origin, pull requests merged in 2024-09, with the labels that each got.

#29045 WRKLDS-1449: Add images coming in k8s 1.31
  pkg/cmd/openshift-tests/images/images_command.go
  test/extended/util/image/zz_generated.txt
Labels: approved, lgtm, e2e-images-update, jira/valid-reference

#29007 [release-4.13] OCPBUGS-37921: Removes dependency on samples operator images
  test/extended/builds/contextdir.go
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/test-context-build.json
  test/extended/util/framework.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#29064 WRKLDS-1449: Add other missing images kube 1.31
  pkg/cmd/openshift-tests/images/images_command.go
  test/extended/util/image/zz_generated.txt
Labels: approved, lgtm, e2e-images-update, jira/valid-reference

#29061 TRT-1794: monitor for api disruption in early E2E tests
  pkg/monitor/monitorapi/types.go
  pkg/monitortests/kubeapiserver/legacykubeapiservermonitortests/early_e2e_disruption.go
  pkg/monitortests/kubeapiserver/legacykubeapiservermonitortests/monitortest.go
Labels: approved, lgtm, jira/valid-reference

#29068 NO-JIRA: Bound Machines
  pkg/defaultmonitortests/types.go
  pkg/monitor/monitorapi/construction.go
  pkg/monitor/monitorapi/types.go
  pkg/monitortestlibrary/monitoring_store.go
  pkg/monitortests/machines/watchmachines/machines.go
  pkg/monitortests/machines/watchmachines/monitortest.go
  pkg/monitortests/node/watchnodes/monitortest.go
  pkg/monitortests/node/watchpods/collection.go
Labels: approved, lgtm, jira/valid-reference

#29073 NO-JIRA: add resources to track apiservice outages
  pkg/resourcewatch/operator/starter.go
Labels: approved, lgtm, jira/valid-reference

#29076 track namespaces so we have easily choose sha when removal happened
  pkg/resourcewatch/operator/starter.go
Labels: approved

#29021 OCPBUGS-38674: add unexpected ready for monitor tests
  pkg/defaultmonitortests/types.go
  pkg/monitor/monitorapi/construction.go
  pkg/monitor/monitorapi/types.go
  pkg/monitortestlibrary/monitoring_store.go
  pkg/monitortests/machines/watchmachines/machines.go
  pkg/monitortests/machines/watchmachines/monitortest.go
  pkg/monitortests/node/watchnodes/monitortest.go
  pkg/monitortests/node/watchnodes/node.go
  pkg/monitortests/node/watchpods/collection.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#29038 SPLAT-1624: skip disruptionserviceloadbalancer for platform external with vSphere CCM
  pkg/monitortests/network/disruptionserviceloadbalancer/monitortest.go
Labels: approved, lgtm, jira/valid-reference

#29056 NO-JIRA: add exclusions to restart tests
  pkg/monitortests/node/legacynodemonitortests/exclusions.go
  pkg/monitortests/node/legacynodemonitortests/kubelet.go
  pkg/monitortests/node/legacynodemonitortests/monitortest.go
Labels: approved, lgtm, jira/valid-reference

#29088 OCPBUGS-39363: Skip the rails example test. It is unsupported and broken.
  test/extended/image_ecosystem/s2i_ruby.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#29083 OCPBUGS-41270: Update the NotFound case for CNI plugin to reflect changes
  pkg/monitortests/network/legacynetworkmonitortests/networking.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#29082 OCPBUGS-39373: Use a supported Perl version in the test template.
  test/extended/testdata/bindata.go
  test/extended/testdata/cluster/quickstarts/dancer-mysql.json
  test/extended/testdata/cmd/test/cmd/images.sh
  test/extended/testdata/cmd/test/cmd/testdata/image-streams/image-streams-centos7.json
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#29084 OCPBUGS-41682: OLM Extended Test 4.18
  test/extended/olm/olm.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/severity-important, jira/valid-reference

#29095 WRKLDS-1449: Update etcd test data for 1.31 release
  test/extended/etcd/etcd_storage_path.go
Labels: approved, lgtm, jira/valid-reference

#29094 NO-JIRA: try to track down why the lease acquiring sometimes fails
  pkg/monitortests/testframework/operatorloganalyzer/operator_lease_check.go
  pkg/monitortests/testframework/operatorloganalyzer/operator_log_scraper.go
Labels: approved, lgtm, jira/valid-reference

#28999 OCPBUGS-38388: Fail on FailedToLease events for kubelet log collector
  pkg/monitor/monitorapi/types.go
  pkg/monitortests/node/kubeletlogcollector/monitortest.go
  pkg/monitortests/node/kubeletlogcollector/node.go
  pkg/monitortests/node/kubeletlogcollector/node_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#29089 MON-4010: metrics API disruption check: do not fall back on prometheus-adapter as metrics-server is GA since 4.16
  pkg/monitortests/monitoring/disruptionmetricsapi/monitortest.go
Labels: approved, lgtm, jira/valid-reference

#29077 OCPBUGS-41550: fix: add check for image registry capability
  pkg/monitortests/network/disruptionpodnetwork/monitortest.go
  test/extended/cpu_partitioning/managed.go
  test/extended/pods/graceful-shutdown.go
  test/extended/util/client.go
  test/extended/util/framework.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#29105 Revert "OCPBUGS-39373: Use a supported Perl version in the test template."
  test/extended/testdata/bindata.go
  test/extended/testdata/cluster/quickstarts/dancer-mysql.json
  test/extended/testdata/cmd/test/cmd/images.sh
  test/extended/testdata/cmd/test/cmd/testdata/image-streams/image-streams-centos7.json
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#29087 NO-JIRA: improve excessive restart tests
  pkg/monitortests/node/legacynodemonitortests/exclusions.go
  pkg/monitortests/node/legacynodemonitortests/kubelet.go
Labels: approved, lgtm, jira/valid-reference

#29107 TRT-1823: Revert #29087 "NO-JIRA: improve excessive restart tests"
  pkg/monitortests/node/legacynodemonitortests/exclusions.go
  pkg/monitortests/node/legacynodemonitortests/kubelet.go
Labels: approved, lgtm, jira/valid-reference

#29069 API-1835: prevent excessive server-side-applies
  pkg/cmd/openshift-tests/monitor/summarize-audit-logs/cmd.go
  pkg/monitortests/kubeapiserver/auditloganalyzer/handle_excessive_applies.go
  pkg/monitortests/kubeapiserver/auditloganalyzer/handle_summarizer.go
  pkg/monitortests/kubeapiserver/auditloganalyzer/monitortest.go
  pkg/monitortests/kubeapiserver/auditloganalyzer/node_log.go
Labels: approved, lgtm, jira/valid-reference

#29111 TRT-1824: Revert #29069 "API-1835: prevent excessive server-side-applies"
  pkg/cmd/openshift-tests/monitor/summarize-audit-logs/cmd.go
  pkg/monitortests/kubeapiserver/auditloganalyzer/handle_excessive_applies.go
  pkg/monitortests/kubeapiserver/auditloganalyzer/handle_summarizer.go
  pkg/monitortests/kubeapiserver/auditloganalyzer/monitortest.go
  pkg/monitortests/kubeapiserver/auditloganalyzer/node_log.go
Labels: approved, lgtm, jira/valid-reference

#29108 NO-JIRA: revert restart tests and skip must gathers
  pkg/monitortests/node/legacynodemonitortests/exclusions.go
  pkg/monitortests/node/legacynodemonitortests/kubelet.go
Labels: approved, lgtm, jira/valid-reference

#29112 NO-JIRA: bringing back the server-side apply test
  pkg/cmd/openshift-tests/monitor/summarize-audit-logs/cmd.go
  pkg/defaultmonitortests/types.go
  pkg/monitortests/kubeapiserver/auditloganalyzer/handle_excessive_applies.go
  pkg/monitortests/kubeapiserver/auditloganalyzer/handle_summarizer.go
  pkg/monitortests/kubeapiserver/auditloganalyzer/monitortest.go
  pkg/monitortests/kubeapiserver/auditloganalyzer/node_log.go
  pkg/monitortests/testframework/watchnamespaces/monitortest.go
  pkg/monitortests/testframework/watchnamespaces/namespaces.go
Labels: approved, jira/valid-reference

#29115 NO-JIRA: add test that ensures our informer cache matches the live results
  pkg/monitortests/node/watchpods/cache_check.go
  pkg/monitortests/node/watchpods/collection.go
  pkg/monitortests/node/watchpods/monitortest.go
  pkg/monitortests/node/watchpods/pod_ip_controller.go
Labels: approved, lgtm, jira/valid-reference

#29109 ETCD-612: Changed the static pod rollout E2E test assertion checking for quorum dependant controllers degraded status
  test/extended/dr/static_pod_rollouts.go
Labels: approved, lgtm, jira/valid-reference

#29124 TRT-1809: refine early E2E disruption test
  pkg/monitortests/kubeapiserver/legacykubeapiservermonitortests/early_e2e_disruption.go
  pkg/monitortests/kubeapiserver/legacykubeapiservermonitortests/monitortest.go
Labels: approved, lgtm, jira/valid-reference

#29121 NO-JIRA: add passing test
  pkg/monitortests/node/legacynodemonitortests/kubelet.go
Labels: approved, lgtm, jira/valid-reference

#29062 [release-4.14] OCPBUGS-39137: Bump timeout for the pod-network-service endpoints check
  pkg/monitortests/network/disruptionpodnetwork/monitortest.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#29125 OCPBUGS-42316: exclude must gather and debug from platform force delete
  pkg/monitortestlibrary/platformidentification/types.go
  pkg/monitortests/node/legacynodemonitortests/kubelet.go
  pkg/monitortests/testframework/watchnamespaces/namespaces.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#29110 NO-JIRA: reduce node lease back off flames to 2
  pkg/monitortests/node/kubeletlogcollector/monitortest.go
  pkg/monitortests/node/kubeletlogcollector/node.go
  pkg/monitortests/node/kubeletlogcollector/node_test.go
Labels: approved, lgtm, jira/valid-reference

#29102 OCPBUGS-39004: Revendor openshift/kubernetes v0.0.0-20240912105924-ce117ff87249
  go.mod
  go.sum
  test/extended/util/image/zz_generated.txt
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sysctl/mustmatchpatterns.go
  vendor/k8s.io/apiserver/pkg/features/kube_features.go
  vendor/k8s.io/apiserver/pkg/server/dynamiccertificates/dynamic_cafile_content.go
  vendor/k8s.io/apiserver/pkg/server/patch_genericapiserver.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/etcd3retry/retry_etcdclient.go
  vendor/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3.go
  vendor/k8s.io/apiserver/pkg/storage/storagebackend/factory/factory.go
  vendor/k8s.io/apiserver/pkg/storage/storagebackend/factory/retry_etcdprobemonitor.go
  vendor/k8s.io/kubernetes/openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  vendor/k8s.io/kubernetes/pkg/controller/job/success_policy.go
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go
  vendor/k8s.io/kubernetes/pkg/scheduler/internal/queue/scheduling_queue.go
  vendor/k8s.io/kubernetes/pkg/securitycontext/util.go
  vendor/k8s.io/kubernetes/pkg/util/filesystem/defaultfs.go
  vendor/k8s.io/kubernetes/pkg/util/filesystem/util_unix.go
  vendor/k8s.io/kubernetes/pkg/util/filesystem/util_windows.go
  vendor/k8s.io/kubernetes/pkg/volume/git_repo/git_repo.go
  vendor/k8s.io/kubernetes/test/e2e/apimachinery/aggregator.go
  vendor/k8s.io/kubernetes/test/e2e/apimachinery/openapiv3.go
  vendor/k8s.io/kubernetes/test/e2e/apimachinery/validatingadmissionpolicy.go
  vendor/k8s.io/kubernetes/test/e2e/storage/volume_metrics.go
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, e2e-images-update, jira/valid-bug, jira/severity-low, jira/valid-reference

#29120 NO-JIRA: add restart exit code test again but do not fail yet
  pkg/monitortests/node/legacynodemonitortests/exclusions.go
  pkg/monitortests/node/legacynodemonitortests/exclusions_test.go
  pkg/monitortests/node/legacynodemonitortests/kubelet.go
  pkg/monitortests/node/legacynodemonitortests/monitortest.go
Labels: approved, lgtm, jira/valid-reference

#29126 OCPBUGS-42336: Fix image ecosystem tests 4.17
  test/extended/image_ecosystem/s2i_images.go
  test/extended/image_ecosystem/s2i_perl.go
  test/extended/image_ecosystem/s2i_ruby.go
  test/extended/image_ecosystem/sample_repos.go
  test/extended/testdata/bindata.go
  test/extended/testdata/image_ecosystem/perl-hotdeploy/perl.json
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/deployment.go
  test/extended/util/framework.go
Labels: approved, lgtm, cherry-pick-approved, staff-eng-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#29137 API-1835: add test to prevent invalid apply statements
  pkg/monitor/monitorapi/types.go
  pkg/monitortests/testframework/operatorloganalyzer/operator_log_scraper.go
Labels: approved, lgtm, jira/valid-reference

#29099 MCO-1304: Add boot image update e2e tests
  test/extended/include.go
  test/extended/machine_config/OWNERS
  test/extended/machine_config/boot_image_update_agnostic.go
  test/extended/machine_config/boot_image_update_aws.go
  test/extended/machine_config/boot_image_update_gcp.go
  test/extended/machine_config/helpers.go
  test/extended/testdata/bindata.go
  test/extended/testdata/machine_config/machineconfigurations/managedbootimages-all.yaml
  test/extended/testdata/machine_config/machineconfigurations/managedbootimages-none.yaml
  test/extended/testdata/machine_config/machineconfigurations/managedbootimages-partial.yaml
  test/extended/util/annotate/generated/zz_generated.annotations.go
  zz_generated.manifests/test-reporting.yaml
Labels: approved, lgtm, jira/valid-reference

#29098 ETCD-662: Add etcd-backup-server e2e test
  test/extended/etcd/etcd_backup_noconfig.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  zz_generated.manifests/test-reporting.yaml
Labels: approved, lgtm, tide/merge-method-squash, jira/valid-reference

#29141 WRKLDS-1492: Loosen output check in policy scc-subject-review, scc-review test
  test/extended/cli/policy.go
Labels: approved, lgtm, jira/valid-reference
