Repository openshift/origin, pull requests merged in 2024-02, with the labels that each got.

#28536 OCPNODE-2029: migrate crio metrics to https
  test/extended/prometheus/prometheus.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#28553 NO-JIRA: fix the static pod lifecycle failure test for more revisions
  pkg/monitortests/kubeapiserver/legacykubeapiservermonitortests/static_pod.go
  pkg/monitortests/kubeapiserver/legacykubeapiservermonitortests/static_pod_test.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#28543 TRT-1452: Separate excessive Back-off restarting tests via namespace
  pkg/monitortestlibrary/pathologicaleventlibrary/duplicated_events_special.go
  pkg/monitortestlibrary/pathologicaleventlibrary/duplicated_events_special_test.go
  pkg/monitortests/node/legacynodemonitortests/pathological_events.go
  pkg/monitortests/node/legacynodemonitortests/pathological_events_test.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#28560 OCPBUGS-23115: Test builds with subscription content
  test/extended/builds/subscription_content.go
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/subscription-content/build-imagestream.yaml
  test/extended/testdata/builds/subscription-content/buildconfig-subscription-content-rhel7.yaml
  test/extended/testdata/builds/subscription-content/buildconfig-subscription-content-rhel8.yaml
  test/extended/testdata/builds/subscription-content/buildconfig-subscription-content-rhel9.yaml
  test/extended/testdata/builds/subscription-content/secret-template.txt
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-low, jira/valid-reference

#28571 TRT-1476: Add monitortest for cloud function on gcp
  pkg/defaultmonitortests/types.go
  pkg/monitortests/testframework/disruptionexternalgcpcloudservicemonitoring/cloudmonitortest.go
Labels: approved, lgtm, jira/valid-reference

#28486 SPLAT-1427: fix/sig-net: ignoring edge when listing worker nodes
  test/extended/networking/tap.go
Labels: approved, lgtm, jira/valid-reference

#28570 NO-JIRA: enforce only stable CRD versions accessible by default
  test/extended/operators/crd_must_be_stable.go
Labels: approved, lgtm, jira/valid-reference

#28576 TRT-1491: Reorder interval groups to place most important/brief info higher up
  e2echart/e2e-chart-template.html
  e2echart/non-spyglass-e2e-chart-template.html
  pkg/monitortests/testframework/timelineserializer/rendering.go
  test/extended/testdata/bindata.go
Labels: approved, lgtm, jira/valid-reference

#28580 TRT-1445: Monitor test hangs during interrupt handling
  pkg/monitortestframework/impl.go
Labels: approved, lgtm, jira/valid-reference

#28514 NE-1444: test/extended/router: HAProxy 2.8 Compatibility Enhancements for h2spec tests
  test/extended/router/h2spec.go
Labels: approved, lgtm, jira/valid-reference

#28583 TRT-1477: update IP for new gcp LB
  pkg/monitortests/testframework/disruptionexternalgcpcloudservicemonitoring/cloudmonitortest.go
Labels: approved, lgtm, jira/valid-reference

#28586 TRT-1499: Revert #28571 gcp-network-liveness until gcp resources are whitelisted
  pkg/defaultmonitortests/types.go
  pkg/monitortests/testframework/disruptionexternalgcpcloudservicemonitoring/cloudmonitortest.go
Labels: approved, lgtm, jira/valid-reference

#28595 OCPBUGS-29493: fix: updated unit test to look for topology not node count
  test/extended/machines/machines.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#28594 TRT-1493: Re-introduce the GCP liveness endpoint test
  pkg/defaultmonitortests/types.go
  pkg/monitortests/testframework/disruptionexternalgcpcloudservicemonitoring/cloudmonitortest.go
Labels: approved, lgtm, jira/valid-reference

#28593 TRT-1501: Add debug logging for decoding cluster provider
  pkg/clioptions/clusterdiscovery/provider.go
Labels: approved, lgtm, jira/valid-reference

#28603 TRT-1522: Revert #28594 "TRT-1476: Re-introduce the GCP liveness endpoint test"
  pkg/defaultmonitortests/types.go
  pkg/monitortests/testframework/disruptionexternalgcpcloudservicemonitoring/cloudmonitortest.go
Labels: approved, lgtm, jira/valid-reference

#28607 NO-JIRA: Pass tail flag in adm node-logs to reduce log size
  test/extended/cli/admin.go
Labels: approved, lgtm, jira/valid-reference

#28604 TRT-1512: Add debug messages to debug openshift-tests hang
  pkg/monitortestframework/impl.go
Labels: approved, lgtm, jira/valid-reference

#28610 [release-4.15] TRT-1512: Add debug messages to debug openshift-tests hang
  pkg/monitortestframework/impl.go
Labels: approved, lgtm, cherry-pick-approved, staff-eng-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#28608 TRT-1476: Re-introduce the GCP liveness endpoint test
  pkg/defaultmonitortests/types.go
  pkg/monitortests/testframework/disruptionexternalgcpcloudservicemonitoring/cloudmonitortest.go
Labels: approved, lgtm, jira/valid-reference

#28602 OCPBUGS-29614: update control plane machine set test
  test/extended/machines/machines.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#28585 OCPBUGS-29858: Only extract node role from properly formatted node-role label
  pkg/monitortests/node/watchnodes/node.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#28592 TRT-1506: Restore the tests looking for excess single-second disruptions
  pkg/cmd/openshift-tests/dev/dev.go
  pkg/monitor/monitorapi/identification.go
  pkg/monitor/monitorapi/types.go
  pkg/monitortests/network/legacynetworkmonitortests/disruption.go
  pkg/monitortests/network/legacynetworkmonitortests/monitortest.go
Labels: approved, lgtm, jira/valid-reference

#28613 trt-1530: specify deployment id for unique log names
  pkg/cmd/openshift-tests/disruption/poll-service/poll_service_options.go
  pkg/cmd/openshift-tests/disruption/watch-endpointslice/watch_endpointslice_options.go
  pkg/monitortests/network/disruptionpodnetwork/host-network-to-host-network-poller-deployment.yaml
  pkg/monitortests/network/disruptionpodnetwork/host-network-to-pod-network-poller-deployment.yaml
  pkg/monitortests/network/disruptionpodnetwork/host-network-to-service-poller-deployment.yaml
  pkg/monitortests/network/disruptionpodnetwork/monitortest.go
  pkg/monitortests/network/disruptionpodnetwork/pod-network-to-host-network-poller-deployment.yaml
  pkg/monitortests/network/disruptionpodnetwork/pod-network-to-pod-network-poller-deployment.yaml
  pkg/monitortests/network/disruptionpodnetwork/pod-network-to-service-poller-deployment.yaml
Labels: approved, lgtm, jira/valid-reference

#28598 MULTIARCH-4160: Stop using the DetermineFromRelease function
  test/extended/networking/egressip_helpers.go
Labels: approved, lgtm, jira/valid-reference

#28631 NO-JIRA: Handle release info output streams separately
  test/extended/operators/images.go
Labels: approved, lgtm, jira/valid-reference
