Repository openshift/origin, pull requests merged in 2024-10, with the labels that each got.

#29138 NO-JIRA: upkeep: skip different node test on sno
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm, jira/valid-reference

#29132 API-1835: add test to ensure we dont' accidentally drop a condition during the …
  test/extended/operators/management_plane_operators.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, jira/valid-reference

#29150 NO-JIRA: Update edge enablement owners
  test/extended/kernel/OWNERS
Labels: approved, lgtm, jira/valid-reference

#29148 NO-JIRA: test for checking the healthz endpoints for the openshift-apiserver
  test/extended/apiserver/health_endpoints.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, jira/valid-reference

#29154 TRT-1843: Revert "add test to ensure we dont' accidentally drop a condition dur…
  test/extended/operators/management_plane_operators.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, jira/valid-reference

#29158 TRT-1844: Revert "Merge pull request #29148 from p0lyn0mial/api-healthz-endpoints"
  test/extended/apiserver/health_endpoints.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, jira/valid-reference

#29147 API-1835: don't allow platform users to make invalid requests
  pkg/monitortests/kubeapiserver/auditloganalyzer/handle_excessive_applies.go
  pkg/monitortests/kubeapiserver/auditloganalyzer/handle_invalid_requests.go
  pkg/monitortests/kubeapiserver/auditloganalyzer/monitortest.go
Labels: approved, lgtm, jira/valid-reference

#29152 NO-JIRA: fix: adding jeremy poulin to edge enablement owners files
  test/extended/kernel/OWNERS
Labels: approved, lgtm, jira/valid-reference

#29134 OCPBUGS-42237: bump ruby-3.0-ubi8 image to ruby-3.1-ubi8
  examples/quickstarts/rails-postgresql-persistent.json
  examples/quickstarts/rails-postgresql.json
  test/extended/builds/dockerfile.go
  test/extended/cli/setimage.go
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/build-secrets/test-s2i-build.json
  test/extended/testdata/builds/statusfail-badcontextdirs2i.yaml
  test/extended/testdata/builds/statusfail-fetchimagecontentdocker.yaml
  test/extended/testdata/builds/statusfail-fetchsourcedocker.yaml
  test/extended/testdata/builds/statusfail-fetchsources2i.yaml
  test/extended/testdata/builds/statusfail-genericreason.yaml
  test/extended/testdata/builds/statusfail-oomkilled.yaml
  test/extended/testdata/builds/test-build-proxy.yaml
  test/extended/testdata/builds/test-build.yaml
  test/extended/testdata/builds/test-env-build.json
  test/extended/testdata/builds/test-imagesource-buildconfig.yaml
  test/extended/testdata/cluster/quickstarts/rails-postgresql.json
  test/extended/testdata/cmd/test/cmd/images.sh
  test/extended/testdata/cmd/test/cmd/testdata/image-streams/image-streams-centos7.json
  test/extended/testdata/cmd/test/cmd/testdata/new-app/imagestream-ref.yaml
  test/extended/testdata/image/test-image.json
  test/extended/testdata/long_names/fixture.json
  test/extended/testdata/run_policy/parallel-bc.yaml
  test/extended/testdata/run_policy/serial-bc.yaml
  test/extended/testdata/run_policy/serial-latest-only-bc.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#29041 SDN-5202:Porting testing for netConfig and UDN and CIDR overlapping tests from upstream
  test/extended/networking/network_segmentation.go
  test/extended/networking/network_segmentation_endpointslice_mirror.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  zz_generated.manifests/test-reporting.yaml
Labels: approved, lgtm, jira/valid-reference

#29130 STOR-1823: Remove payload tests that use shared-resource CSI driver
  test/extended/builds/volumes.go
  test/extended/storage/inline.go
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/volumes/csi-docker-buildconfig.yaml
  test/extended/testdata/builds/volumes/csi-s2i-buildconfig.yaml
  test/extended/testdata/builds/volumes/csi-sharedresourcerole.yaml
  test/extended/testdata/builds/volumes/csi-sharedresourcerolebinding.yaml
  test/extended/testdata/builds/volumes/csi-sharedsecret.yaml
  test/extended/testdata/builds/volumes/csi-without-rr-docker-buildconfig.yaml
  test/extended/testdata/builds/volumes/csi-without-rr-s2i-buildconfig.yaml
  test/extended/testdata/storage/inline/csi-sharedresourcerole.yaml
  test/extended/testdata/storage/inline/csi-sharedresourcerolebinding.yaml
  test/extended/testdata/storage/inline/csi-sharedsecret.yaml
  test/extended/testdata/storage/inline/secret.yaml
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, jira/valid-reference

#29167 NO-JIRA: make exception for invalid MCO changes
  pkg/monitortests/kubeapiserver/auditloganalyzer/monitortest.go
  test/extended/ci/job_names.go
  test/extended/util/framework.go
Labels: approved, lgtm, jira/valid-reference

#29145 NO-JIRA: update recovery tests with rev bumping
  test/extended/dr/common.go
  test/extended/dr/recovery.go
Labels: approved, lgtm, jira/valid-reference

#29090 API-1789: tls artifacts: list ondisk locations alongside secret/configmaps
  pkg/certs/types.go
  pkg/cmd/update-tls-artifacts/generate-owners/tlsmetadata/ownership/requirement.go
  pkg/cmd/update-tls-artifacts/generate-owners/tlsmetadatainterfaces/annotation_requirement.go
  pkg/cmd/update-tls-artifacts/generate-owners/tlsmetadatainterfaces/helpers.go
  tls/autoregenerate-after-expiry/autoregenerate-after-expiry.json
  tls/autoregenerate-after-expiry/autoregenerate-after-expiry.md
  tls/descriptions/descriptions.json
  tls/descriptions/descriptions.md
  tls/ownership/ownership.json
  tls/ownership/ownership.md
  tls/violations/autoregenerate-after-expiry/autoregenerate-after-expiry-violations.json
  tls/violations/descriptions/descriptions-violations.json
Labels: approved, lgtm, jira/valid-reference

#29025 NO-JIRA: external binary registry
  pkg/test/ginkgo/cmd_runsuite.go
  pkg/test/ginkgo/external.go
Labels: approved, lgtm, jira/valid-reference

#29162 [release-4.17] OCPBUGS-42814: ruby:3.0-ubi8 => ruby:3.1-ubi8
  examples/quickstarts/rails-postgresql-persistent.json
  examples/quickstarts/rails-postgresql.json
  test/extended/builds/dockerfile.go
  test/extended/cli/setimage.go
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/build-secrets/test-s2i-build.json
  test/extended/testdata/builds/statusfail-badcontextdirs2i.yaml
  test/extended/testdata/builds/statusfail-fetchimagecontentdocker.yaml
  test/extended/testdata/builds/statusfail-fetchsourcedocker.yaml
  test/extended/testdata/builds/statusfail-fetchsources2i.yaml
  test/extended/testdata/builds/statusfail-genericreason.yaml
  test/extended/testdata/builds/statusfail-oomkilled.yaml
  test/extended/testdata/builds/test-build-proxy.yaml
  test/extended/testdata/builds/test-build.yaml
  test/extended/testdata/builds/test-env-build.json
  test/extended/testdata/builds/test-imagesource-buildconfig.yaml
  test/extended/testdata/cluster/quickstarts/rails-postgresql.json
  test/extended/testdata/cmd/test/cmd/images.sh
  test/extended/testdata/cmd/test/cmd/testdata/image-streams/image-streams-centos7.json
  test/extended/testdata/cmd/test/cmd/testdata/new-app/imagestream-ref.yaml
  test/extended/testdata/image/test-image.json
  test/extended/testdata/long_names/fixture.json
  test/extended/testdata/run_policy/parallel-bc.yaml
  test/extended/testdata/run_policy/serial-bc.yaml
  test/extended/testdata/run_policy/serial-latest-only-bc.yaml
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#29164 OCPEDGE-1265: removing rteval from the realtime test suite
  test/extended/kernel/kernel_rt_latency.go
  test/extended/kernel/tools.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, jira/valid-reference

#29173 TRT-1851: Revert "NO-JIRA: external binary registry"
  pkg/test/ginkgo/cmd_runsuite.go
  pkg/test/ginkgo/external.go
Labels: approved, lgtm, jira/valid-reference

#29086 ETCD-664: Add e2e test for scaling when CPMS is disabled
  test/extended/etcd/helpers/helpers.go
  test/extended/etcd/vertical_scaling.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, jira/valid-reference

#29179 NO-JIRA: Fix Network segmentation test for detecting timeout
  test/extended/networking/network_segmentation.go
Labels: approved, lgtm, jira/valid-reference

#29144 OCPEDGE-1276: fix: adding in a SNO time override for AWS Metal
  test/e2e/upgrade/upgrade.go
Labels: approved, lgtm, jira/valid-reference

#29160 OCPEDGE-1266: fix: adding oslat updates and outputting test results to the artifacts
  test/extended/kernel/common.go
  test/extended/kernel/tools.go
  test/extended/testdata/bindata.go
  test/extended/testdata/kernel/rt-tests-environment.yaml
Labels: approved, lgtm, jira/valid-reference

#29174 [release-4.17] OCPBUGS-39606: Add image registry capability check
  pkg/monitortests/network/disruptionpodnetwork/monitortest.go
  test/extended/cpu_partitioning/managed.go
  test/extended/pods/graceful-shutdown.go
  test/extended/util/client.go
  test/extended/util/framework.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#29183 OCPBUGS-43059: fix: sno issues with alerts and pathological events
  pkg/monitortestlibrary/allowedalerts/basic_alert.go
  pkg/monitortestlibrary/pathologicaleventlibrary/duplicated_event_patterns.go
  pkg/monitortestlibrary/pathologicaleventlibrary/duplicated_events_test.go
  pkg/monitortests/node/legacynodemonitortests/exclusions.go
  pkg/monitortests/node/legacynodemonitortests/monitortest.go
  pkg/monitortests/node/legacynodemonitortests/pathological_events.go
  pkg/monitortests/node/legacynodemonitortests/pathological_events_test.go
  test/e2e/upgrade/dns/dns.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#29188 WRKLDS-1449: Fix kubernetes-tests version annotation
  images/tests/Dockerfile.rhel
Labels: approved, lgtm, jira/valid-reference

#29163 NO-JIRA: prove json patch
  go.mod
  go.sum
  test/extended/apiserver/patch.go
  test/extended/testdata/apiserver/operator-kube-apiserver-cr.yaml
  test/extended/testdata/bindata.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  vendor/github.com/openshift/library-go/pkg/apiserver/jsonpatch/jsonpatch.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/canonicalize.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, jira/valid-reference

#29182 NO-JIRA: Enable external binary registry
  pkg/test/ginkgo/cmd_runsuite.go
  pkg/test/ginkgo/external.go
Labels: approved, lgtm, jira/valid-reference

#29191 NO-JIRA: a new test for the jsonpatch library
  go.mod
  go.sum
  test/extended/apiserver/patch.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  vendor/github.com/openshift/library-go/pkg/apiserver/jsonpatch/jsonpatch.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/informers.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, jira/valid-reference

#29161 NO-JIRA: test/extended/apiserver: test for checking the healthz endpoints for oauth-apiserver
  test/extended/apiserver/health_endpoints.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, jira/valid-reference

#29196 ETCD-687: Remove etcd-backup-server StaticPod approach e2e test
  test/extended/etcd/etcd_backup_noconfig.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  zz_generated.manifests/test-reporting.yaml
Labels: approved, lgtm, jira/valid-reference

#29198 NO-JIRA: fix exec issue on etcd dr suite
  test/extended/dr/common.go
Labels: approved, lgtm, jira/valid-reference

#29168 API-1835: Add a generation analyzer monitortest
  pkg/defaultmonitortests/types.go
  pkg/monitor/monitorapi/construction.go
  pkg/monitor/monitorapi/types.go
  pkg/monitortests/kubeapiserver/generationanalyzer/generation.go
  pkg/monitortests/kubeapiserver/generationanalyzer/monitortest.go
Labels: approved, lgtm, jira/valid-reference

#29181 [release-4.17] OCPBUGS-43576: Porting testing for netConfig and UDN and CIDR overlapping tests from upstream
  test/extended/networking/network_segmentation.go
  test/extended/networking/network_segmentation_endpointslice_mirror.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  zz_generated.manifests/test-reporting.yaml
Labels: approved, lgtm, cherry-pick-approved, staff-eng-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#29175 TRT-1575: Add more exceptions for operator degraded cases
  pkg/monitortests/clusterversionoperator/legacycvomonitortests/operators.go
Labels: approved, lgtm, jira/valid-reference

#29214 NO-JIRA: update-tls-artifacts: set owner to unknown if unset
  pkg/cmd/update-tls-artifacts/generate-owners/tlsmetadatainterfaces/annotation_requirement.go
  pkg/cmd/update-tls-artifacts/generate-owners/tlsmetadatainterfaces/helpers.go
  tls/autoregenerate-after-expiry/autoregenerate-after-expiry.md
  tls/descriptions/descriptions.md
Labels: approved, lgtm, jira/valid-reference

#29151 OCPBUGS-42610: filter out pod events during vsphere snapshot options tests
  pkg/monitortestlibrary/pathologicaleventlibrary/duplicated_event_patterns.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#29210 OCPBUGS-43512: New ManagedBootImages test appears to be failing too often
  test/extended/machine_config/boot_image_update_agnostic.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#29217 NO-JIRA: Allow extension binary extraction retries
  pkg/test/ginkgo/external.go
Labels: approved, lgtm, jira/valid-reference

#29220 SDN-4930: network_segmentation: allow multiple UDN status conditions
  test/extended/networking/network_segmentation.go
Labels: approved, lgtm, ¯\_(ツ)_/¯, jira/valid-reference

#29201 OCPBUGS-43483: auditloganalyzer: check audit log for requests arriving after shutdown
  pkg/monitortests/kubeapiserver/auditloganalyzer/handle_requests_during_graceful_shutdown.go
  pkg/monitortests/kubeapiserver/auditloganalyzer/monitortest.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#29225 OCPNODE-2668: fix unexpected not ready
  pkg/monitortests/node/watchnodes/monitortest.go
Labels: approved, lgtm, jira/valid-reference

#29216 NO-JIRA: managed services: skip JSON patch tests
  test/extended/apiserver/patch.go
  test/extended/pods/priorityclasses.go
  test/extended/util/framework.go
Labels: approved, lgtm, jira/valid-reference

#29218 NO-JIRA: Additional logging for extract image and binaries
  pkg/test/ginkgo/external.go
Labels: approved, lgtm, jira/valid-reference

#29219 MCO-1370: Add boot image configmap test to openshift/origin
  test/extended/machine_config/boot_image_update_agnostic.go
  test/extended/machine_config/boot_image_update_aws.go
  test/extended/machine_config/boot_image_update_gcp.go
  test/extended/machine_config/helpers.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  zz_generated.manifests/test-reporting.yaml
Labels: approved, lgtm, jira/valid-reference

#29230 NO-JIRA: managed services: add exception for known images check
  pkg/monitortests/testframework/knownimagechecker/monitortest.go
Labels: approved, lgtm, jira/valid-reference

#29143 OCPBUGS-42536: Trying to reduce the flakiness of the samples smoke tests
  test/extended/image_ecosystem/sample_repos.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#29149 OPNET-588: On-Prem test for apiserver reachability from the LB
  pkg/defaultmonitortests/types.go
  pkg/monitor/monitorapi/types.go
  pkg/monitortests/network/onpremhaproxy/monitortest.go
Labels: approved, lgtm, jira/valid-reference

#29189 OPRUN-3576: Add OLMv1 origin tests
  test/extended/olm/olmv1.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, jira/valid-reference

#29227 NO-JIRA: tls registry: don't store annotation values in violations
  pkg/cmd/update-tls-artifacts/generate-owners/tlsmetadata/ownership/requirement.go
  pkg/cmd/update-tls-artifacts/generate-owners/tlsmetadatainterfaces/annotation_requirement.go
  pkg/cmd/update-tls-artifacts/generate-owners/tlsmetadatainterfaces/helpers.go
  tls/violations/autoregenerate-after-expiry/autoregenerate-after-expiry-violations.json
  tls/violations/descriptions/descriptions-violations.json
Labels: approved, lgtm, vendor-update, jira/valid-reference

#29238 NO-JIRA: UserDefinedPrimaryNetworks: curl the KAPI IP through eth0
  test/extended/networking/network_segmentation.go
Labels: approved, lgtm, jira/valid-reference

#29240 SDN-4930: Set startup probe for UDN tests
  test/extended/networking/network_segmentation.go
Labels: approved, lgtm, jira/valid-reference

#29233 NO-JIRA: Additional exceptions for ROSA CI
  pkg/monitortestlibrary/pathologicaleventlibrary/duplicated_event_patterns.go
  pkg/monitortests/node/legacynodemonitortests/exclusions.go
  test/extended/operators/check_crd_status.go
Labels: approved, lgtm, jira/valid-reference

#29246 OPRUN-3580: Add OLMv1 ClusterCatalog test to origin
  test/extended/olm/olmv1.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, jira/valid-reference

#29243 SDN-4930: Don't modify pod routes in tests
  test/extended/networking/network_segmentation.go
Labels: approved, lgtm, jira/valid-reference

#29231 OCPBUGS-38713: Adjust createDNSPod() to support hypershift dual-stack test
  test/extended/dns/dns.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#29211 AUTH-539: Update OWNERS
  test/extended/authorization/OWNERS
Labels: approved, lgtm, jira/valid-reference
