Repository openshift/origin, pull requests merged in 2024-12, with the labels that each got.

#29323 OCPBUGS-44961: Fix "Enforce the required-scc monitor test and validate usage of non-standard OCP SCCs"
  pkg/monitortests/authentication/requiredsccmonitortests/monitortest.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#29300 TRT-1895: External binary caching and code clean-up
  pkg/test/externalbinary/README.md
  pkg/test/externalbinary/binary.go
  pkg/test/externalbinary/provider.go
  pkg/test/externalbinary/types.go
  pkg/test/externalbinary/util.go
  pkg/test/ginkgo/cmd_runsuite.go
  pkg/test/ginkgo/external.go
  pkg/test/ginkgo/test_suite.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#29336 NO-JIRA: managed services: add known image check for gcp
  pkg/monitortests/testframework/knownimagechecker/monitortest.go
Labels: approved, lgtm, jira/valid-reference

#29340 OCPBUGS-45363: Parse node logs also when encountered with standard html header
  pkg/monitortestlibrary/nodeaccess/node_log.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#29328 OCPBUGS-44808: reenable OLMv1 test for maxOpenShiftversion
  test/extended/olm/olmv1.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/valid-reference

#29329 OCPBUGS-44970: Excluding loki prod-bearer-token container from excessive restarts test in SNO
  pkg/monitortests/node/legacynodemonitortests/exclusions.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#29351 OCPBUGS-45838: managed services: add missing namespaces to list
  test/extended/cpu_partitioning/platform.go
  test/extended/util/managed_services.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#29352 [release-4.18] OCPBUGS-45853: managed services: add missing namespaces to list
  test/extended/cpu_partitioning/platform.go
  test/extended/util/managed_services.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#29311 OCPBUGS-42610: filter out pod events during vsphere snapshot options
  pkg/monitortestlibrary/pathologicaleventlibrary/duplicated_event_patterns.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#29176 OCPBUGS-42618: Replace RunHostCmd with Exec function to censor bearer token being ex…
  test/extended/prometheus/prometheus.go
  test/extended/router/metrics.go
  test/extended/util/client.go
  test/extended/util/prometheus/helpers.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#29356 OCPBUGS-45838: managed services: add more missing namespaces
  test/extended/util/managed_services.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#29357 OCPBUGS-45994: managed services: allow KubeDaemonSetMisScheduled alert
  test/extended/prometheus/prometheus.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#29320 trt-1892: check for pod security audit violations
  pkg/monitortests/kubeapiserver/auditloganalyzer/handle_audit_violation.go
  pkg/monitortests/kubeapiserver/auditloganalyzer/monitortest.go
Labels: approved, lgtm, jira/valid-reference

#29368 NO-ISSUE: Remove m1kola from owners
  test/extended/olm/OWNERS
Labels: approved, lgtm, jira/valid-reference

#29369 NO-JIRA: managed services: bump series limit
  test/extended/prometheus/prometheus.go
Labels: approved, lgtm, jira/valid-reference

#29362 CNTRLPLANE-1: Add incoming images k8s 1.32
  pkg/cmd/openshift-tests/images/images_command.go
  test/extended/util/image/zz_generated.txt
Labels: approved, lgtm, e2e-images-update, jira/valid-reference

#29365 STOR-2136: Remove CSI snapshot webhook conditions checks
  test/extended/operators/management_plane_operators.go
Labels: approved, lgtm, jira/valid-reference

#29376 CNTRLPLANE-1: Update etcd test data for 1.32 release
  test/extended/etcd/etcd_storage_path.go
Labels: approved, lgtm, jira/valid-reference

#29383 STOR-2136: Remove CSI snapshot webhook tests
  test/extended/storage/csi_snapshot_controller_operator.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, jira/valid-reference

#29195 SDN-5017: Add UDN Network Policy e2e tests
  test/extended/networking/multinetpolicy.go
  test/extended/networking/network_segmentation.go
  test/extended/networking/network_segmentation_policy.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  zz_generated.manifests/test-reporting.yaml
Labels: approved, lgtm, jira/valid-reference

#29348 SDN-5568: only provision workloads when network creation has started
  test/extended/networking/egressip_helpers.go
  test/extended/networking/livemigration.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  zz_generated.manifests/test-reporting.yaml
Labels: approved, lgtm, jira/valid-reference

#29354 TRT-1575: Use catchall card for operator degraded exceptions for major operators
  pkg/monitortests/clusterversionoperator/legacycvomonitortests/operators.go
Labels: approved, lgtm, jira/valid-reference

#29367 TRT-1803: Wait for operators to become stable before test
  pkg/clioptions/clusterinfo/wait_for_stable_cluster.go
  pkg/test/ginkgo/cmd_runsuite.go
Labels: approved, lgtm, jira/valid-reference

#29374 SDN-5566: virt, udn: primary UDN requires the net seg FG
  test/extended/networking/livemigration.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  zz_generated.manifests/test-reporting.yaml
Labels: approved, lgtm, jira/valid-reference

#29375 SDN-5567: virt: add GA placeholder test
  test/extended/networking/livemigration.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#28797 SDN-4168: Optimize timing for IPsec tests
  pkg/testsuites/standard_suites.go
  test/extended/networking/ipsec.go
  test/extended/networking/util.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/clusterversion.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#29346 SDN-5031: e2e,networking: add UDN open-default-ports annotation test.
  test/extended/networking/network_segmentation.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  zz_generated.manifests/test-reporting.yaml
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#29355 OCPBUGS-44257: Fixing build s2i ruby test data inline with latest ruby version(>=3.0)
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/s2i-environment-build-app/Gemfile
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only
