Repository openshift/origin, pull requests merged in 2025-08, with the labels that each got.

#30034 NO-JIRA: Revert "OCPBUGS-55238: spyglass: hide disruption events for localhost"
  e2echart/non-spyglass-e2e-chart-template.html
  pkg/disruption/backend/disruption/handler.go
  pkg/monitor/monitorapi/types.go
  test/extended/testdata/bindata.go
Labels: approved, lgtm, jira/valid-reference

#30006 OCPBUGS-59218: feat(azure): skip metrics collection for ARO HCP hypershift
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/monitortest.go
  test/extended/util/managed_services.go
  test/extended/util/managed_services_test.go
  test/extended/util/pods.go
  test/extended/util/pods_test.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#30029 OCPBUGS-56506: Don't check for remote node subnet BGP routes
  test/extended/networking/route_advertisements.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#30048 OCPBUGS-60066, OCPBUGS-60067: Tolerate various expected Upgradeable=False conditions
  test/extended/operators/operators.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#30036 OPRUN-3964: [olmv1] - Remove test [sig-olmv1][OCPFeatureGate:NewOLM] OLMv1 CRDs should be installed migrated to operator-controller repository/OTE
  test/extended/olm/olmv1.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  zz_generated.manifests/test-reporting.yaml
Labels: approved, lgtm, jira/valid-reference

#30009 CORENET-6203: Enable test for LGW L2
  test/extended/networking/route_advertisements.go
Labels: approved, lgtm, jira/valid-reference

#30053 OCPBUGS-60067, OCPBUGS-60066: Don't check for isNoUpgrade
  test/extended/operators/operators.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#29952 NO-JIRA: Get enabled featuregates from metrics endpoint
  pkg/clioptions/clusterdiscovery/cluster.go
Labels: approved, lgtm, jira/valid-reference

#30060 NO-JIRA: Update image mirroring instructions to avoid using external binary
  test/extended/util/image/README.md
Labels: approved, lgtm, e2e-images-update, jira/valid-reference

#30026 NO-JIRA: Update extended/networking OWNERS
  test/extended/networking/OWNERS
Labels: approved, lgtm, jira/valid-reference

#29831 OTA-1559: test/extended/cli/admin: Add 'oc adm upgrade recommend' smoke test
  go.mod
  test/extended/cli/adm_upgrade/recommend.go
  test/extended/cli/adm_upgrade/regexp.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, jira/valid-reference

#30070 OCPNODE-3004: ImageVolume: Increase timeout duration
  test/extended/node/image_volume.go
Labels: approved, lgtm, jira/valid-reference

#30062 OCPBUGS-57032: Add wait.Poll retry logic to checkUpgradeability with 30s timeout
  test/e2e/upgrade/upgrade.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#30008 OCPBUGS-59603: Fix vgs tests
  go.mod
  go.sum
  images/tests/Dockerfile.rhel
  test/extended/util/image/zz_generated.txt
  vendor/k8s.io/kubernetes/openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  vendor/k8s.io/kubernetes/openshift-hack/e2e/annotate/rules.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/admission/admissionenablement/register.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/admission/storage/performantsecuritypolicy/admission.go
  vendor/k8s.io/kubernetes/pkg/features/openshift_features.go
  vendor/k8s.io/kubernetes/pkg/kubelet/apis/podresources/server_v1.go
  vendor/k8s.io/kubernetes/pkg/kubelet/apis/podresources/types.go
  vendor/k8s.io/kubernetes/pkg/kubelet/images/image_gc_manager.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_container_linux.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_sandbox_linux.go
  vendor/k8s.io/kubernetes/pkg/registry/batch/job/strategy.go
  vendor/k8s.io/kubernetes/test/e2e/common/node/lifecycle_hook.go
  vendor/k8s.io/kubernetes/test/e2e/storage/testsuites/volume_group_snapshottable.go
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-snapshotter/volume-group-snapshots/csi-hostpath-plugin.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-snapshotter/volume-group-snapshots/run_group_snapshot_e2e.sh
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/gce-pd/controller_ss.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-plugin.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-snapshotter.yaml
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, e2e-images-update, jira/valid-bug, jira/valid-reference

#30031 OTA-1580: Monitortest framework test for oc adm upgrade status
  pkg/cmd/openshift-tests/monitor/run/run_monitor_command.go
  pkg/defaultmonitortests/types.go
  pkg/monitortests/cli/adm_upgrade/OWNERS
  pkg/monitortests/cli/adm_upgrade/status/monitortest.go
Labels: approved, lgtm, jira/valid-reference

#29968 [release-4.18] OCPBUGS-58461:Backport pr 29834 to release-4.18
  test/extended/images/dryrun.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#30022 OCPEDGE-1969: add recovery tests for TNA
  test/extended/two_node/arbiter_topology.go
  test/extended/two_node/common.go
  test/extended/two_node/tna_recovery.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  zz_generated.manifests/test-reporting.yaml
Labels: approved, lgtm, jira/valid-reference

#30072 OPRUN-4055: [OLMv1] Remove olmv1.go tests since those has been executed by OTE
  test/extended/olm/olmv1.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  zz_generated.manifests/test-reporting.yaml
Labels: approved, lgtm, jira/valid-reference

#30071 OCPNODE-3520: UserNamespaces: Increase build timeout duration
  test/extended/util/framework.go
Labels: approved, lgtm, jira/valid-reference

#30068 OCPBUGS-58037: increase timeout of image extract test
  test/extended/images/extract.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#30058 NO-JIRA: [TNF] add Two Node Fencing exception to accept less than two etcd endpoints
  pkg/monitortestlibrary/pathologicaleventlibrary/duplicated_event_patterns.go
Labels: approved, lgtm, jira/valid-reference

#30109 OTA-1580: Further tests for `oc adm upgrade status`
  pkg/monitortests/cli/adm_upgrade/status/controlplane.go
  pkg/monitortests/cli/adm_upgrade/status/controlplane_test.go
  pkg/monitortests/cli/adm_upgrade/status/health.go
  pkg/monitortests/cli/adm_upgrade/status/health_test.go
  pkg/monitortests/cli/adm_upgrade/status/monitortest.go
  pkg/monitortests/cli/adm_upgrade/status/monitortest_test.go
  pkg/monitortests/cli/adm_upgrade/status/outputmodel.go
  pkg/monitortests/cli/adm_upgrade/status/outputmodel_test.go
  pkg/monitortests/cli/adm_upgrade/status/updatelifecycle.go
  pkg/monitortests/cli/adm_upgrade/status/updatelifecycle_test.go
  pkg/monitortests/cli/adm_upgrade/status/workers.go
  pkg/monitortests/cli/adm_upgrade/status/workers_test.go
Labels: approved, lgtm, jira/valid-reference

#30103 WIP: OTA-1580: [1/x] Tweaks
  pkg/monitortests/cli/adm_upgrade/status/monitortest.go
Labels: approved, do-not-merge/work-in-progress, jira/valid-reference

#30114 OCPBUGS-60375: Fix perl hotdeploy test
  test/extended/testdata/bindata.go
  test/extended/testdata/image_ecosystem/perl-hotdeploy/perl.json
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#29986 OCPEDGE-1755: Add TNF E2E tests for ungraceful node shutdown
  test/e2e/upgrade/monitor.go
  test/extended/two_node/tnf_recovery.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/nodes.go
  zz_generated.manifests/test-reporting.yaml
Labels: approved, lgtm, jira/valid-reference

#30118 OCPBUGS-60530: Log full stack traces for panics in monitortest cleanup
  pkg/monitortestframework/panic.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#30043 OCPBUGS-60429: Load our MCO's OTE binary
  pkg/test/extensions/binary.go
  pkg/testsuites/standard_suites.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#30116 OCPBUGS-59526: TLS registry update
  go.mod
  go.sum
  test/extended/operators/certs.go
  tls/autoregenerate-after-expiry/autoregenerate-after-expiry.json
  tls/autoregenerate-after-expiry/autoregenerate-after-expiry.md
  tls/descriptions/descriptions.json
  tls/descriptions/descriptions.md
  tls/ownership/ownership.json
  tls/ownership/ownership.md
  tls/raw-data/raw-tls-artifacts-ha-amd64-aws-ovn-default.json
  tls/raw-data/raw-tls-artifacts-ha-amd64-aws-ovn-techpreviewnoupgrade.json
  tls/raw-data/raw-tls-artifacts-ha-amd64-azure-ovn-default.json
  tls/raw-data/raw-tls-artifacts-ha-amd64-azure-ovn-techpreviewnoupgrade.json
  tls/raw-data/raw-tls-artifacts-ha-amd64-gcp-ovn-default.json
  tls/raw-data/raw-tls-artifacts-ha-amd64-gcp-ovn-techpreviewnoupgrade.json
  tls/raw-data/raw-tls-artifacts-ha-amd64-metal-ovn-default.json
  tls/raw-data/raw-tls-artifacts-ha-amd64-metal-ovn-techpreviewnoupgrade.json
  tls/raw-data/raw-tls-artifacts-ha-amd64-openstack-ovn-default.json
  tls/raw-data/raw-tls-artifacts-ha-amd64-vsphere-ovn-default.json
  tls/raw-data/raw-tls-artifacts-ha-amd64-vsphere-ovn-techpreviewnoupgrade.json
  tls/raw-data/raw-tls-artifacts-single-amd64-aws-ovn-default.json
  tls/raw-data/raw-tls-artifacts-single-amd64-aws-ovn-techpreviewnoupgrade.json
  tls/refresh-period/refresh-period.json
  tls/refresh-period/refresh-period.md
  tls/testcase/testcase.json
  tls/testcase/testcase.md
  tls/violations/autoregenerate-after-expiry/autoregenerate-after-expiry-violations.json
  tls/violations/descriptions/descriptions-violations.json
  tls/violations/ownership/ownership-violations.json
  tls/violations/refresh-period/refresh-period-violations.json
  tls/violations/testcase/testcase-violations.json
  vendor/github.com/openshift/library-go/pkg/certs/cert-inspection/certgraphanalysis/metadata_options.go
  vendor/github.com/openshift/library-go/pkg/certs/pem.go
  vendor/github.com/openshift/library-go/pkg/certs/util.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/base_controller.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/controller_context.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/eventfilters.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/factory.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/interfaces.go
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/OWNERS
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/annotations.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/config.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/label.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/metadata.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/management/management_state.go
  vendor/github.com/robfig/cron/.gitignore
  vendor/github.com/robfig/cron/.travis.yml
  vendor/github.com/robfig/cron/LICENSE
  vendor/github.com/robfig/cron/README.md
  vendor/github.com/robfig/cron/constantdelay.go
  vendor/github.com/robfig/cron/cron.go
  vendor/github.com/robfig/cron/doc.go
  vendor/github.com/robfig/cron/parser.go
  vendor/github.com/robfig/cron/spec.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, jira/valid-bug, jira/valid-reference

#30112 NO-JIRA: fix: update arbiter test
  test/extended/two_node/arbiter_topology.go
Labels: approved, lgtm, jira/valid-reference

#30127 Revert "TRT-2197: use fixed seed for test ordering"
  pkg/test/ginkgo/cmd_runsuite.go
Labels: approved, lgtm, jira/valid-reference

#30132 OTA-1581: Skip `UpgradeStatus` test on HyperShift
  test/extended/cli/adm_upgrade/status.go
Labels: approved, lgtm, jira/valid-reference

#30133 OCPBUGS-60550: Increase curl timeout from 3s to 5s for egress firewall DNS rule test
  test/extended/networking/egress_firewall.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#30140 OCPBUGS-57477: Allow three long term flaky k8s tests to retry
  pkg/test/ginkgo/cmd_runsuite.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#30143 OCPBUGS-52968: Drop the etcd should not log excessive took too long messages test
  pkg/monitortests/etcd/legacyetcdmonitortests/etcd.go
  pkg/monitortests/etcd/legacyetcdmonitortests/monitortest.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#30122 OCPNODE-3004: Run ImageVolume tests in all clusters.
  test/extended/node/image_volume.go
Labels: approved, lgtm, jira/valid-reference

#30134 SREP-1622: Fix endpoint admission test namespace creation for ROSA
  test/extended/networking/endpoint_admission.go
Labels: approved, lgtm, jira/valid-reference

#30088 [release-4.19] NO-JIRA: Update extended/networking OWNERS
  test/extended/networking/OWNERS
Labels: approved, lgtm, jira/valid-reference

#30089 [release-4.18] NO-JIRA: Update extended/networking OWNERS
  test/extended/networking/OWNERS
Labels: approved, lgtm, jira/valid-reference

#30074 OPRUN-4056: [OLMv1] Remove Preflight checks since those were migrated to OTE
  test/extended/olm/olmv1-preflight.go
  test/extended/testdata/bindata.go
  test/extended/testdata/olmv1/install-pipeline-operator-0.yaml
  test/extended/testdata/olmv1/install-pipeline-operator-1.yaml
  test/extended/testdata/olmv1/install-pipeline-operator-2.yaml
  test/extended/testdata/olmv1/install-pipeline-operator-3.yaml
  test/extended/testdata/olmv1/install-pipeline-operator-4.yaml
  test/extended/testdata/olmv1/install-pipeline-operator-5.yaml
  test/extended/testdata/olmv1/install-pipeline-operator-6.yaml
  test/extended/util/annotate/generated/zz_generated.annotations.go
  zz_generated.manifests/test-reporting.yaml
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#30144 OCPBUGS-60244: Wait 30s after the upgrade is complete to validate workloads
  test/e2e/upgrade/upgrade.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#30174 CNTRLPLANE-945: monitor: auditloganalyzer: skip watch channels processing when cluster stability is explicitly marked as `Disruptive`
  pkg/defaultmonitortests/types.go
  pkg/monitortests/kubeapiserver/auditloganalyzer/monitortest.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#30146 NO-JIRA: Stop setting feature gate conditional
  pkg/monitortests/cli/adm_upgrade/status/monitortest.go
  test/extended/cli/adm_upgrade/status.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#30148 CNTRLPLANE-945: oidc/keycloak: make keycloak client use environment proxy for HTTP requests
  test/extended/authentication/keycloak_client.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#30173 OPRUN-4089: Remove OLMv1 Tests remaning since all is migrated to OTE/operator-controller repo
  test/extended/olm/olmv1-catalogd.go
  test/extended/olm/olmv1-singleownnamespace.go
  test/extended/olm/olmv1.go
  test/extended/testdata/bindata.go
  test/extended/testdata/olmv1/install-catalog.yaml
  test/extended/testdata/olmv1/install-openshift-pipelines-operator-ownns.yaml
  test/extended/testdata/olmv1/install-operator.yaml
  test/extended/testdata/olmv1/install-pipeline-operator-base.yaml
  test/extended/testdata/olmv1/install-quay-operator-ownns.yaml
  test/extended/testdata/olmv1/install-quay-operator-singlens.yaml
  test/extended/util/annotate/generated/zz_generated.annotations.go
  zz_generated.manifests/test-reporting.yaml
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#30166 TRT-2268: Add support for OTE test lifecycles
  pkg/test/ginkgo/cmd_runsuite.go
  pkg/testsuites/standard_suites.go
  test/extended/extension/extension.go
  test/extended/include.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#30190 trt-2257: annotate zstd as sig-builds
  pkg/test/ginkgo/cmd_runsuite.go
  test/extended/node/zstd_chunked.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#30075 OCPBUGS-57496: Account for system:hosted-cluster-config service account in HyperShift
  test/extended/authorization/authorization.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#30120 CNTRLPLANE-1257: Enable OTE for apiserver Operators and servers
  pkg/test/extensions/binary.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only
