Repository openshift/origin, pull requests merged in 2025-05, with the labels that each got.

#29744 OCPBUGS-55510: Update node selection in MCN scope test for two-node Openshift
  test/extended/machine_config/helpers.go
  test/extended/machine_config/machine_config_node.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference, acknowledge-critical-fixes-only

#29742 OKD-243: Skip GatewayAPIController tests for OKD
  test/extended/router/gatewayapicontroller.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#29707 OCPBUGS-55265: Bump 1.32.4
  go.mod
  go.sum
  images/tests/Dockerfile.rhel
  vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_handler.go
  vendor/k8s.io/apiextensions-apiserver/pkg/registry/customresource/etcd.go
  vendor/k8s.io/apiserver/pkg/cel/library/cidr.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/watcher.go
  vendor/k8s.io/kubernetes/openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  vendor/k8s.io/kubernetes/openshift-hack/e2e/annotate/rules.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/admission/customresourcevalidation/apiserver/validate_apiserver.go
  vendor/k8s.io/kubernetes/pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go
  vendor/k8s.io/kubernetes/test/e2e/kubectl/portforward.go
  vendor/k8s.io/kubernetes/test/e2e/storage/csimock/csi_kubelet_restart.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#29652 OCPNODE-2999: Add SigstoreImageVerification e2e tests
  pkg/monitortestlibrary/pathologicaleventlibrary/duplicated_event_patterns.go
  test/extended/imagepolicy/imagepolicy.go
  test/extended/include.go
  test/extended/machine_config/helpers.go
  test/extended/testdata/bindata.go
  test/extended/testdata/imagepolicy/invalid-public-key-cluster-image-policy.yaml
  test/extended/testdata/imagepolicy/invalid-public-key-image-policy.yaml
  test/extended/testdata/imagepolicy/public-key-rekor-cluster-image-policy.yaml
  test/extended/testdata/imagepolicy/public-key-rekor-image-policy.yaml
  test/extended/util/annotate/generated/zz_generated.annotations.go
  zz_generated.manifests/test-reporting.yaml
Labels: approved, lgtm, jira/valid-reference

#29763 OCPBUGS-55785: bump limits
  pkg/monitortests/kubeapiserver/auditloganalyzer/handle_operator_watch_count_tracking.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#29699 CNTRLPLANE-371: Update etcd test data for k8s 1.33 release
  test/extended/etcd/etcd_storage_path.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#29766 NO-ISSUE: OLMv1: Preflight: Relax checking of error message
  test/extended/olm/olmv1-preflight.go
Labels: approved, lgtm, jira/valid-reference

#29765 OCPBUGS-55267: Update to Kubernetes v1.31.8
  go.mod
  go.sum
  images/tests/Dockerfile.rhel
  vendor/k8s.io/apiserver/pkg/storage/etcd3/watcher.go
  vendor/k8s.io/kubernetes/openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  vendor/k8s.io/kubernetes/openshift-hack/e2e/annotate/rules.go
  vendor/k8s.io/kubernetes/pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go
  vendor/k8s.io/kubernetes/test/e2e/storage/csimock/csi_kubelet_restart.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#29747 OCPBUGS-55902: pkg/monitortestlibrary/allowedalerts: Ignore KubeJobFailingSRE for now
  pkg/monitortestlibrary/allowedalerts/types.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#29753 NO-JIRA: faultyloadbalancer test: pass instead of skip
  pkg/monitortests/kubeapiserver/faultyloadbalancer/monitortest.go
Labels: approved, lgtm, jira/valid-reference

#29594 OCPNODE-2315: Add nested container test
  pkg/testsuites/standard_suites.go
  test/extended/include.go
  test/extended/node/nested_container.go
  test/extended/testdata/bindata.go
  test/extended/testdata/node/nested_container/Dockerfile
  test/extended/testdata/node/nested_container/containers.conf
  test/extended/testdata/node/nested_container/run_tests.sh
  test/extended/testdata/node/nested_container/skip_tests.sh
  test/extended/util/annotate/generated/zz_generated.annotations.go
  zz_generated.manifests/test-reporting.yaml
Labels: approved, lgtm, jira/valid-reference

#29727 OCPBUGS-55910, CORENET-5875, CORENET-5876: Add EgressIP and L2 UDN route advertisements tests
  test/extended/networking/egressip.go
  test/extended/networking/egressip_helpers.go
  test/extended/networking/route_advertisements.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  zz_generated.manifests/test-reporting.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#29772 OCPBUGS-55945: Bump main 1.32.4
  go.mod
  go.sum
  images/tests/Dockerfile.rhel
  vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_handler.go
  vendor/k8s.io/apiextensions-apiserver/pkg/registry/customresource/etcd.go
  vendor/k8s.io/apiserver/pkg/cel/library/cidr.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/watcher.go
  vendor/k8s.io/kubernetes/openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  vendor/k8s.io/kubernetes/openshift-hack/e2e/annotate/rules.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/admission/customresourcevalidation/apiserver/validate_apiserver.go
  vendor/k8s.io/kubernetes/pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go
  vendor/k8s.io/kubernetes/pkg/volume/util/operationexecutor/node_expander.go
  vendor/k8s.io/kubernetes/pkg/volume/util/operationexecutor/operation_generator.go
  vendor/k8s.io/kubernetes/pkg/volume/util/resize_util.go
  vendor/k8s.io/kubernetes/test/e2e/kubectl/portforward.go
  vendor/k8s.io/kubernetes/test/e2e/storage/csimock/csi_kubelet_restart.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, jira/valid-bug, jira/valid-reference

#29756 OCPBUGS-55712: (olmv1 tests) Use exponential backoffs for verifyAPIEndpoints
  test/extended/olm/olmv1.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#29773 CNTRLPLANE-371: Update etcd test data for k8s 1.33 release (missing data)
  test/extended/etcd/etcd_storage_path.go
Labels: approved, lgtm, jira/valid-reference

#29779 Revert "OCPNODE-2315: Add nested container test"
  pkg/testsuites/standard_suites.go
  test/extended/include.go
  test/extended/node/nested_container.go
  test/extended/testdata/bindata.go
  test/extended/testdata/node/nested_container/Dockerfile
  test/extended/testdata/node/nested_container/containers.conf
  test/extended/testdata/node/nested_container/run_tests.sh
  test/extended/testdata/node/nested_container/skip_tests.sh
  test/extended/util/annotate/generated/zz_generated.annotations.go
  zz_generated.manifests/test-reporting.yaml
Labels: approved, lgtm, jira/valid-reference

#29770 OCPBUGS-55969: (olmv1 tests) Increase timeout for verifyAPIEndpoints
  test/extended/olm/olmv1.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#29775 TRT-2106: Fix race in MCN test cleanup
  test/extended/machine_config/machine_config_node.go
Labels: approved, lgtm, jira/valid-reference

#29575 NO-JIRA: Fix bearer token exposure in exit condition as well
  test/extended/util/client.go
  test/extended/util/prometheus/helpers.go
Labels: approved, lgtm, jira/valid-reference

#29768 OCPBUGS-55994: Do not set the MTU when using NetworkAttachementDefinition
  test/extended/networking/network_segmentation.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#29781 OCPNODE-2315: Add nested container test
  pkg/testsuites/standard_suites.go
  test/extended/include.go
  test/extended/node/nested_container.go
  test/extended/testdata/bindata.go
  test/extended/testdata/node/nested_container/Dockerfile
  test/extended/testdata/node/nested_container/containers.conf
  test/extended/testdata/node/nested_container/run_tests.sh
  test/extended/testdata/node/nested_container/skip_tests.sh
  test/extended/util/annotate/generated/zz_generated.annotations.go
  zz_generated.manifests/test-reporting.yaml
Labels: approved, lgtm, jira/valid-reference

#29737 [release-4.17] OCPBUGS-55451: support provider type external
  pkg/clioptions/clusterdiscovery/provider.go
  test/extended/util/external/provider.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#29785 OCPBUGS-55384: OCPBUGS-55968: Fix PIS tests on SNO & Enable applicable MCN & PIS tests on SNO
  test/extended/machine_config/helpers.go
  test/extended/machine_config/machine_config_node.go
  test/extended/machine_config/pinnedimages.go
  test/extended/testdata/bindata.go
  test/extended/testdata/machine_config/pinnedimage/masterInvalidPis.yaml
  test/extended/testdata/machine_config/pinnedimage/masterPis.yaml
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#29760 NO-JIRA: support skipping [OCP]FeatureGate tests
  pkg/clioptions/suiteselection/feature_filter.go
Labels: approved, lgtm, jira/valid-reference

#29761 NO-JIRA: increase api client timeout to match those allowed by kube-apiserver
  pkg/monitor/backenddisruption/disruption_backend_sampler.go
Labels: approved, lgtm, jira/valid-reference

#29786 NO-JIRA: update networking owners
  test/extended/networking/OWNERS
Labels: approved, lgtm, jira/valid-reference

#29694 OCPEDGE-1678: Fix failed etcd test on arbiter ci run
  test/extended/etcd/invariants.go
Labels: approved, lgtm, jira/valid-reference

#29669 CORENET-5854: networking: add VRF-Lite test cases
  test/extended/networking/egressip.go
  test/extended/networking/egressip_helpers.go
  test/extended/networking/route_advertisements.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/nodes.go
  zz_generated.manifests/test-reporting.yaml
Labels: approved, lgtm, jira/valid-reference

#29723 Revert "Revert "TRT-2049: check for any watch requests""
  pkg/monitortests/kubeapiserver/auditloganalyzer/handle_operator_watch_count_tracking.go
Labels: approved, lgtm, jira/valid-reference

#29697 OCPBUGS-55211: use regular user to create httproute
  test/extended/router/gatewayapicontroller.go
  test/extended/util/client.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#29796 NO-JIRA: Revert: NO-JIRA: support skipping [OCP]FeatureGate…
  pkg/clioptions/suiteselection/feature_filter.go
Labels: approved, lgtm, jira/valid-reference

#29759 CORS-3989: set proxy for http transport in router and imageregistry cases
  test/extended/images/redirect.go
  test/extended/router/external_certificate.go
Labels: approved, lgtm, jira/valid-reference

#29738 [release-4.16] OCPBUGS-55476: support provider type external
  pkg/clioptions/clusterdiscovery/provider.go
  test/extended/util/external/provider.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#29784 OCPBUGS-55317: Skip GatewayAPIController tests on clusters without OLM capabilities
  test/extended/router/gatewayapicontroller.go
  test/extended/util/framework.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#29637 TRT-2061: throttle monitor startup refactor
  pkg/monitor/monitor.go
  pkg/monitortestframework/impl.go
  pkg/monitortestframework/panic.go
  pkg/monitortestframework/types.go
  pkg/monitortests/authentication/legacyauthenticationmonitortests/monitortest.go
  pkg/monitortests/authentication/requiredsccmonitortests/monitortest.go
  pkg/monitortests/cloud/azure/metrics/monitortest.go
  pkg/monitortests/clusterversionoperator/legacycvomonitortests/monitortest.go
  pkg/monitortests/clusterversionoperator/operatorstateanalyzer/monitortest.go
  pkg/monitortests/clusterversionoperator/terminationmessagepolicy/monitortest.go
  pkg/monitortests/etcd/etcdloganalyzer/monitortest.go
  pkg/monitortests/etcd/legacyetcdmonitortests/monitortest.go
  pkg/monitortests/imageregistry/disruptionimageregistry/monitortest.go
  pkg/monitortests/kubeapiserver/apiservergracefulrestart/monitortest.go
  pkg/monitortests/kubeapiserver/apiunreachablefromclientmetrics/monitortest.go
  pkg/monitortests/kubeapiserver/auditloganalyzer/monitortest.go
  pkg/monitortests/kubeapiserver/disruptionexternalapiserver/monitortest.go
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/monitortest.go
  pkg/monitortests/kubeapiserver/disruptionnewapiserver/monitortest.go
  pkg/monitortests/kubeapiserver/faultyloadbalancer/monitortest.go
  pkg/monitortests/kubeapiserver/generationanalyzer/monitortest.go
  pkg/monitortests/kubeapiserver/legacykubeapiservermonitortests/monitortest.go
  pkg/monitortests/kubeapiserver/legacykubeapiservermonitortests/resource_growth_invariant.go
  pkg/monitortests/kubeapiserver/staticpodinstall/monitortest.go
  pkg/monitortests/machines/watchmachines/monitortest.go
  pkg/monitortests/monitoring/disruptionmetricsapi/monitortest.go
  pkg/monitortests/monitoring/statefulsetsrecreation/monitortest.go
  pkg/monitortests/network/disruptioningress/monitortest.go
  pkg/monitortests/network/disruptionpodnetwork/monitortest.go
  pkg/monitortests/network/disruptionserviceloadbalancer/monitortest.go
  pkg/monitortests/network/legacynetworkmonitortests/monitortest.go
  pkg/monitortests/network/onpremhaproxy/monitortest.go
  pkg/monitortests/node/kubeletlogcollector/monitortest.go
  pkg/monitortests/node/legacynodemonitortests/monitortest.go
  pkg/monitortests/node/nodestateanalyzer/monitortest.go
  pkg/monitortests/node/watchnodes/monitortest.go
  pkg/monitortests/node/watchpods/monitortest.go
  pkg/monitortests/storage/legacystoragemonitortests/monitortest.go
  pkg/monitortests/testframework/additionaleventscollector/monitortest.go
  pkg/monitortests/testframework/alertanalyzer/monitortest.go
  pkg/monitortests/testframework/clusterinfoserializer/monitortest.go
  pkg/monitortests/testframework/disruptionexternalawscloudservicemonitoring/cloudmonitortest.go
  pkg/monitortests/testframework/disruptionexternalazurecloudservicemonitoring/cloudmonitortest.go
  pkg/monitortests/testframework/disruptionexternalgcpcloudservicemonitoring/cloudmonitortest.go
  pkg/monitortests/testframework/disruptionexternalservicemonitoring/monitortest.go
  pkg/monitortests/testframework/disruptionserializer/monitortest.go
  pkg/monitortests/testframework/e2etestanalyzer/monitortest.go
  pkg/monitortests/testframework/intervalserializer/monitortest.go
  pkg/monitortests/testframework/knownimagechecker/monitortest.go
  pkg/monitortests/testframework/legacytestframeworkmonitortests/monitortest.go
  pkg/monitortests/testframework/metricsendpointdown/monitortest.go
  pkg/monitortests/testframework/operatorloganalyzer/operator_lease_check.go
  pkg/monitortests/testframework/operatorloganalyzer/operator_log_scraper.go
  pkg/monitortests/testframework/pathologicaleventanalyzer/monitortest.go
  pkg/monitortests/testframework/timelineserializer/monitortest.go
  pkg/monitortests/testframework/trackedresourcesserializer/monitortest.go
  pkg/monitortests/testframework/watchclusteroperators/monitortest.go
  pkg/monitortests/testframework/watchevents/monitortest.go
  pkg/monitortests/testframework/watchnamespaces/monitortest.go
Labels: approved, lgtm, jira/valid-reference

#29733 NO-JIRA: Report back source for openshift-tests-extension
  pkg/test/extensions/binary.go
  pkg/test/extensions/types.go
Labels: approved, lgtm, jira/valid-reference

#29684 MCO-1615: Mco node degraded mcn condition
  test/extended/machine_config/helpers.go
  test/extended/machine_config/machine_config_node.go
Labels: approved, lgtm, jira/valid-reference

#29803 NO-JIRA: Fix egressIP advertisements tests flake
  test/extended/networking/route_advertisements.go
Labels: approved, lgtm, jira/valid-reference

#29816 NO-JIRA: ovnk, virt: Filter out ipv6 LLA
  test/extended/networking/livemigration.go
Labels: approved, lgtm, jira/valid-reference

#29820 OCPBUGS-56047: OLMv1: Update test bundles [main/release-4.20]
  test/extended/olm/olmv1.go
  test/extended/testdata/bindata.go
  test/extended/testdata/olmv1/install-pipeline-operator-base.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#29713 OCPNODE-3138: Add zstd:chunked image test
  test/extended/node/zstd_chunked.go
  test/extended/testdata/bindata.go
  test/extended/testdata/node/zstd-chunked/Dockerfile
  test/extended/testdata/node/zstd-chunked/Dockerfile.sample
  test/extended/testdata/node/zstd-chunked/build.sh
  test/extended/testdata/node/zstd-chunked/test-custom-build.yaml
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/annotate/rules.go
Labels: approved, lgtm, e2e-images-update, jira/valid-reference

#29787 NO-JIRA: TLS registry update
  tls/autoregenerate-after-expiry/autoregenerate-after-expiry.json
  tls/autoregenerate-after-expiry/autoregenerate-after-expiry.md
  tls/descriptions/descriptions.json
  tls/descriptions/descriptions.md
  tls/ownership/ownership.json
  tls/ownership/ownership.md
  tls/raw-data/raw-tls-artifacts-ha-amd64-aws-ovn-default.json
  tls/raw-data/raw-tls-artifacts-ha-amd64-aws-ovn-techpreviewnoupgrade.json
  tls/raw-data/raw-tls-artifacts-ha-amd64-azure-ovn-default.json
  tls/raw-data/raw-tls-artifacts-ha-amd64-azure-ovn-techpreviewnoupgrade.json
  tls/raw-data/raw-tls-artifacts-ha-amd64-gcp-ovn-default.json
  tls/raw-data/raw-tls-artifacts-ha-amd64-gcp-ovn-techpreviewnoupgrade.json
  tls/raw-data/raw-tls-artifacts-ha-amd64-metal-ovn-default.json
  tls/raw-data/raw-tls-artifacts-ha-amd64-metal-ovn-techpreviewnoupgrade.json
  tls/raw-data/raw-tls-artifacts-ha-amd64-openstack-ovn-default.json
  tls/raw-data/raw-tls-artifacts-ha-amd64-vsphere-ovn-default.json
  tls/raw-data/raw-tls-artifacts-ha-amd64-vsphere-ovn-techpreviewnoupgrade.json
  tls/raw-data/raw-tls-artifacts-single-amd64-aws-ovn-default.json
  tls/raw-data/raw-tls-artifacts-single-amd64-aws-ovn-techpreviewnoupgrade.json
  tls/violations/autoregenerate-after-expiry/autoregenerate-after-expiry-violations.json
  tls/violations/descriptions/descriptions-violations.json
  tls/violations/ownership/ownership-violations.json
Labels: approved, lgtm, jira/valid-reference

#29745 OCPBUGS-55394: Handle Metal CI test cases for PIS
  test/extended/machine_config/helpers.go
  test/extended/machine_config/pinnedimages.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#29806 NE-2031: Enhancing the gateway controller test cases with two more function
  go.mod
  go.sum
  test/extended/router/gatewayapicontroller.go
  test/extended/util/client.go
  vendor/github.com/openshift/api/.golangci.yaml
  vendor/github.com/openshift/api/README.md
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/features.md
  vendor/github.com/openshift/api/features/features.go
  vendor/github.com/openshift/api/machineconfiguration/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/operatoringress/v1/Makefile
  vendor/github.com/openshift/api/operatoringress/v1/doc.go
  vendor/github.com/openshift/api/operatoringress/v1/register.go
  vendor/github.com/openshift/api/operatoringress/v1/types.go
  vendor/github.com/openshift/api/operatoringress/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operatoringress/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/operatoringress/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/client-go/operatoringress/applyconfigurations/internal/internal.go
  vendor/github.com/openshift/client-go/operatoringress/applyconfigurations/operatoringress/v1/dnsrecord.go
  vendor/github.com/openshift/client-go/operatoringress/applyconfigurations/operatoringress/v1/dnsrecordspec.go
  vendor/github.com/openshift/client-go/operatoringress/applyconfigurations/operatoringress/v1/dnsrecordstatus.go
  vendor/github.com/openshift/client-go/operatoringress/applyconfigurations/operatoringress/v1/dnszonecondition.go
  vendor/github.com/openshift/client-go/operatoringress/applyconfigurations/operatoringress/v1/dnszonestatus.go
  vendor/github.com/openshift/client-go/operatoringress/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/operatoringress/clientset/versioned/scheme/doc.go
  vendor/github.com/openshift/client-go/operatoringress/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/operatoringress/clientset/versioned/typed/operatoringress/v1/dnsrecord.go
  vendor/github.com/openshift/client-go/operatoringress/clientset/versioned/typed/operatoringress/v1/doc.go
  vendor/github.com/openshift/client-go/operatoringress/clientset/versioned/typed/operatoringress/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/operatoringress/clientset/versioned/typed/operatoringress/v1/operatoringress_client.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, jira/valid-reference

#29800 MCO-1652: Add new MCO disruptive suite
  pkg/testsuites/standard_suites.go
Labels: approved, lgtm, jira/valid-reference

#29807 OCPBUGS-56381: feat: update test to account for two node fencing
  test/extended/baremetal/hosts.go
  test/extended/util/framework.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#29855 NO-JIRA: router: Rename MarshalPrivateKeyToDERFormat to MarshalPrivateKeyToPEMString
  test/extended/router/certgen/certgen.go
  test/extended/router/external_certificate.go
  test/extended/router/grpc-interop.go
  test/extended/router/http2.go
Labels: approved, lgtm, jira/valid-reference

#29836 OCPBUGS-56045: OLMv1: Update test bundles [release-4.19]
  test/extended/olm/olmv1.go
  test/extended/testdata/bindata.go
  test/extended/testdata/olmv1/install-pipeline-operator-base.yaml
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#29764 OCPBUGS-55721, OCPBUGS-55832: Fix `RouteExternalCertificate` tests for few other on-prem jobs
  pkg/monitortestlibrary/platformidentification/types.go
  test/extended/router/external_certificate.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#29853 NO-JIRA: OVNK BGP: workaround OCPBUGS-56488
  test/extended/networking/route_advertisements.go
  test/extended/networking/util.go
Labels: approved, lgtm, jira/valid-reference

#29725 OCPBUGS-55277: backport watch count tracking fixes to 4.18
  pkg/defaultmonitortests/types.go
  pkg/monitortests/kubeapiserver/auditloganalyzer/handle_count_tracking.go
  pkg/monitortests/kubeapiserver/auditloganalyzer/handle_excessive_applies.go
  pkg/monitortests/kubeapiserver/auditloganalyzer/handle_invalid_requests.go
  pkg/monitortests/kubeapiserver/auditloganalyzer/handle_operator_watch_count_tracking.go
  pkg/monitortests/kubeapiserver/auditloganalyzer/handle_operator_watch_count_tracking_test.go
  pkg/monitortests/kubeapiserver/auditloganalyzer/handle_requests_during_graceful_shutdown.go
  pkg/monitortests/kubeapiserver/auditloganalyzer/handle_summarizer.go
  pkg/monitortests/kubeapiserver/auditloganalyzer/monitortest.go
  pkg/monitortests/kubeapiserver/auditloganalyzer/node_log.go
  pkg/monitortests/testframework/watchrequestcountscollector/monitortest.go
  test/extended/apiserver/api_requests.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#29856 [release-4.15] NO-JIRA: Sync OWNERS from main branch
  OWNERS
  OWNERS_ALIASES
  pkg/OWNERS
  test/OWNERS
Labels: approved, lgtm, jira/valid-reference

#29864 Add oceanc80 to olm owners
  test/extended/olm/OWNERS
Labels: approved, lgtm

#29875 OCPBUGS-56437: Update to kubernetes 1.32.5
  go.mod
  go.sum
  images/tests/Dockerfile.rhel
  test/extended/util/image/zz_generated.txt
  vendor/k8s.io/kubernetes/pkg/volume/util/operationexecutor/node_expander.go
  vendor/k8s.io/kubernetes/pkg/volume/util/operationexecutor/operation_generator.go
  vendor/k8s.io/kubernetes/pkg/volume/util/resize_util.go
  vendor/k8s.io/kubernetes/test/e2e/storage/testsuites/multivolume.go
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backport-risk-assessed, e2e-images-update, jira/valid-bug, jira/valid-reference

#29869 OCPBUGS-55830: Only update boot disks during GCP boot image updates tests
  test/extended/machine_config/helpers.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#29739 [release-4.15] OCPBUGS-55477: support provider type external
  pkg/clioptions/clusterdiscovery/provider.go
  test/extended/util/external/provider.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#29827 SPLAT-2231: Updated tests to work with hybrid environments
  test/extended/machines/cluster.go
  test/extended/machines/machines.go
Labels: approved, lgtm, jira/valid-reference

#29876 OCPBUGS-56933: fix deployment rollout wait to wait for desired replicas
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/monitortest.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference
