Repository openshift/origin, pull requests merged in 2025-07, with the labels that each got.

#29833 OCPEDGE-1481: Initial tests for Two Nodes OCP with Fencing (TNF) cluster
  go.mod
  pkg/testsuites/standard_suites.go
  test/extended/two_node/arbiter_topology.go
  test/extended/two_node/common.go
  test/extended/two_node/tnf_recovery.go
  test/extended/two_node/tnf_topology.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  zz_generated.manifests/test-reporting.yaml
Labels: approved, lgtm, tide/merge-method-squash, jira/valid-reference

#29946 trt-2163: return error
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/monitortest.go
Labels: approved, lgtm, jira/valid-reference

#29903 OCPBUGS-57206: Backport pr 29834 to release-4.19
  test/extended/images/dryrun.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#29956 NO-JIRA: test/extended/operators: skip wildcard certificate
  test/extended/operators/certs.go
Labels: approved, lgtm, jira/valid-reference

#29971 TRT-2097: Fix a few things in suite selection
  pkg/test/extensions/binary.go
  pkg/testsuites/standard_suites.go
Labels: approved, lgtm, jira/valid-reference

#29972 OCPBUGS-58895: bump watch count limits
  pkg/monitortests/kubeapiserver/auditloganalyzer/handle_operator_watch_count_tracking.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#29979 OCPBUGS-59157: Ensure CSI tests are defined before OTE initialization
  pkg/clioptions/clusterdiscovery/csi.go
  pkg/clioptions/clusterdiscovery/provider.go
  pkg/test/extensions/binary.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#29962 MCO-1797: Fix transient errors while checking status of PIS
  test/extended/machine_config/pinnedimages.go
Labels: approved, lgtm, jira/valid-reference

#29941 OCPBUGS-57887: Update to Kubernetes v1.31.10
  go.mod
  go.sum
  images/tests/Dockerfile.rhel
  test/extended/util/image/zz_generated.txt
  vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_handler.go
  vendor/k8s.io/apiextensions-apiserver/pkg/registry/customresource/etcd.go
  vendor/k8s.io/apiserver/pkg/server/options/serving_with_loopback.go
  vendor/k8s.io/client-go/util/cert/cert.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_getters.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_pods.go
  vendor/k8s.io/kubernetes/pkg/kubelet/userns/types.go
  vendor/k8s.io/kubernetes/pkg/kubelet/userns/userns_manager.go
  vendor/k8s.io/kubernetes/pkg/kubelet/userns/userns_manager_windows.go
  vendor/k8s.io/kubernetes/pkg/util/kernel/constants.go
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, e2e-images-update, jira/valid-bug, jira/valid-reference

#29953 NO-JIRA: OWNERS_ALIASES: Update OTA members / team lead
  OWNERS_ALIASES
Labels: approved, lgtm, jira/valid-reference

#29993 Revert "CNF-17748: Add a comparing between static entry test"
  go.mod
  test/extended/networking/commatrix.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, jira/valid-reference

#29989 OCPBUGS-59391: [release-4.19]: OVNK BGP: Sync ovn-kubernetes bgp e2e tests
  test/extended/networking/egressip.go
  test/extended/networking/egressip_helpers.go
  test/extended/networking/route_advertisements.go
  test/extended/networking/util.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/nodes.go
  zz_generated.manifests/test-reporting.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#29964 Revert "Revert "trt-2163: return error""
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/monitortest.go
Labels: approved, lgtm, jira/valid-reference

#29970 OCPBUGS-58354: disruptioninclusterapiserver: bump timeout to 10 mins
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/monitortest.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#29974 MON-4288: register CMO tests extension
  pkg/test/extensions/binary.go
Labels: approved, lgtm, jira/valid-reference

#29978 OCPBUGS-59159: Adjust DNS success rate to 98.0% for SNO upgrade test.
  test/e2e/upgrade/dns/dns.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#29981 OCPBUGS-59203: OCPBUGS-57524: Improve MCN test stability
  test/extended/machine_config/helpers.go
  test/extended/machine_config/machine_config_node.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  zz_generated.manifests/test-reporting.yaml
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#30000 Revert "Revert "Revert "trt-2163: return error"""
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/monitortest.go
Labels: approved, lgtm, jira/valid-reference

#29994 NO-JIRA: oc idle: Increase timeout of endpointslice status check
  test/extended/cli/idle.go
Labels: approved, lgtm, jira/valid-reference

#30002 NO-JIRA: fix: nil pointer reference in pod count
  test/extended/two_node/arbiter_topology.go
Labels: approved, lgtm, jira/valid-reference

#29954 OTA-1580: Add basic test for `oc adm upgrade status` CLI
  test/extended/cli/adm_upgrade/OWNERS
  test/extended/cli/adm_upgrade/status.go
  test/extended/include.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/client.go
  zz_generated.manifests/test-reporting.yaml
Labels: approved, lgtm, jira/valid-reference

#29279 API-1802: chart template: show cert rotation events
  e2echart/non-spyglass-e2e-chart-template.html
  pkg/monitortestlibrary/pathologicaleventlibrary/duplicated_event_patterns.go
  pkg/monitortests/testframework/watchevents/event.go
  test/extended/testdata/bindata.go
Labels: approved, lgtm, jira/valid-reference

#30017 OCPBUGS-59750: Move the legacy container failures
  pkg/defaultmonitortests/types.go
  pkg/monitortests/kubelet/containerfailures/container_failures.go
  pkg/monitortests/kubelet/containerfailures/exclusions.go
  pkg/monitortests/kubelet/containerfailures/exclusions_test.go
  pkg/monitortests/node/legacynodemonitortests/kubelet.go
  pkg/monitortests/node/legacynodemonitortests/monitortest.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#30015 OCPNODE-3004: Add ImageVolume e2e tests
  test/extended/node/image_volume.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  zz_generated.manifests/test-reporting.yaml
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#29917 CNTRLPLANE-945: Add tests for ExternalOIDC and ExternalOIDCWithUIDAndExtraClaimMappings features
  pkg/testsuites/standard_suites.go
  test/extended/authentication/keycloak_client.go
  test/extended/authentication/keycloak_helpers.go
  test/extended/authentication/oidc.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/client.go
  vendor/github.com/openshift/library-go/pkg/operator/condition/condition.go
  vendor/modules.txt
  zz_generated.manifests/test-reporting.yaml
Labels: approved, lgtm, vendor-update, jira/valid-reference

#29973 OCPNODE-3454: OCPFeatureGate:SigstoreImageVerification update test on v1 (Cluster)ImagePolicy
  pkg/monitortestlibrary/pathologicaleventlibrary/duplicated_event_patterns.go
  test/extended/imagepolicy/imagepolicy.go
Labels: approved, lgtm, vendor-update, jira/valid-reference

#30027 OCPNODE-3004: Accept ErrImagePull for non-existent image volume test.
  test/extended/node/image_volume.go
Labels: approved, lgtm, jira/valid-reference

#30007 TRT-2163: incluster disruption images
  pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/monitortest.go
  pkg/monitortests/network/disruptionpodnetwork/monitortest.go
  pkg/monitortests/network/disruptionpodnetwork/utils.go
  pkg/test/extensions/binary.go
  pkg/test/extensions/provider.go
  pkg/test/extensions/util.go
  test/extended/util/payload/payload.go
Labels: approved, lgtm, jira/valid-reference

#30039 TRT-2224: Fix edge case where failures are not counted
  pkg/test/ginkgo/cmd_runsuite.go
Labels: approved, lgtm, jira/valid-reference
