Repository openshift/origin, pull requests merged in 2025-02, with the labels that each got.

#29517 SDN-4930: Increases timeouts for live migration
  test/extended/networking/livemigration.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#29504 OCPBUGS-49740, SDN-5625: Backport net seg feat gate into udn virt tests
  test/extended/networking/livemigration.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  zz_generated.manifests/test-reporting.yaml
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#29525 OCPBUGS-45893: Allows for backwards compatibility with upcoming network name change
  test/extended/networking/network_segmentation.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#29524 MULTIARCH-5318: Add tests for ImageStreamImportMode feature gate
  go.mod
  go.sum
  test/e2e/upgrade/upgrade.go
  test/extended/images/tagimportmode.go
  test/extended/networking/cnimigration.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/framework.go
  test/extended/util/operator/settle.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_node.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1alpha1/types_cluster_image_policy.go
  vendor/github.com/openshift/api/config/v1alpha1/types_image_policy.go
  vendor/github.com/openshift/api/config/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/console/v1/types_console_plugin.go
  vendor/github.com/openshift/api/console/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/console/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/console/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/envtest-releases.yaml
  vendor/github.com/openshift/api/features.md
  vendor/github.com/openshift/api/features/features.go
  vendor/github.com/openshift/api/features/legacyfeaturegates.go
  vendor/github.com/openshift/api/features/util.go
  vendor/github.com/openshift/api/kubecontrolplane/v1/types.go
  vendor/github.com/openshift/api/kubecontrolplane/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machineconfiguration/v1/types.go
  vendor/github.com/openshift/api/machineconfiguration/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/operator/v1/register.go
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_olm.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
  zz_generated.manifests/test-reporting.yaml
Labels: approved, lgtm, vendor-update, jira/valid-reference, acknowledge-critical-fixes-only

#29414 NO-JIRA: Add test case for checking EgressFirewall DNS names in caps
  test/extended/networking/egress_firewall.go
  test/extended/testdata/bindata.go
  test/extended/testdata/egress-firewall/ovnk-egressfirewall-test.yaml
  test/extended/testdata/egress-firewall/ovnk-egressfirewall-wildcard-test.yaml
  test/extended/testdata/egress-firewall/sdn-egressnetworkpolicy-test.yaml
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#29533 CNTRLPLANE-195: add a test that flakes if etcd cluster is leaderless more than 5 seconds
  pkg/monitortests/etcd/etcdloganalyzer/monitortest.go
Labels: approved, lgtm, tide/merge-method-squash, jira/valid-reference, acknowledge-critical-fixes-only

#29540 TRT-2006: Revert "NO-JIRA: Add test case for checking EgressFirewall DNS names in caps"
  test/extended/networking/egress_firewall.go
  test/extended/testdata/bindata.go
  test/extended/testdata/egress-firewall/ovnk-egressfirewall-test.yaml
  test/extended/testdata/egress-firewall/ovnk-egressfirewall-wildcard-test.yaml
  test/extended/testdata/egress-firewall/sdn-egressnetworkpolicy-test.yaml
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#29538 CNTRLPLANE-1: Bump to latest downstream version of ginkgo
  go.mod
  go.sum
  vendor/github.com/onsi/ginkgo/v2/CHANGELOG.md
  vendor/github.com/onsi/ginkgo/v2/Makefile
  vendor/github.com/onsi/ginkgo/v2/OWNERS
  vendor/github.com/onsi/ginkgo/v2/core_dsl_patch.go
  vendor/github.com/onsi/ginkgo/v2/formatter/formatter.go
  vendor/github.com/onsi/ginkgo/v2/ginkgo/build/build_command.go
  vendor/github.com/onsi/ginkgo/v2/ginkgo/internal/compile.go
  vendor/github.com/onsi/ginkgo/v2/internal/spec_patch.go
  vendor/github.com/onsi/ginkgo/v2/types/config.go
  vendor/github.com/onsi/ginkgo/v2/types/types.go
  vendor/github.com/onsi/ginkgo/v2/types/types_patch.go
  vendor/github.com/onsi/ginkgo/v2/types/version.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, jira/valid-reference, acknowledge-critical-fixes-only

#29543 Revert "NO-JIRA: use quay.io/openshift/origin-cli:latest directly"
  test/extended/testdata/bindata.go
  test/extended/testdata/signer-buildconfig.yaml
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#29490 OCPBUGS-49600: Display etcd bootstrap event on timeline
  e2echart/e2e-chart-template.html
  pkg/monitor/monitorapi/types.go
  pkg/monitortests/testframework/operatorloganalyzer/operator_log_scraper.go
  test/extended/testdata/bindata.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#29506 TRT-1853: Pass applicable environment flags to the external binary
  pkg/clioptions/clusterdiscovery/cluster.go
  pkg/test/extensions/binary.go
  pkg/test/extensions/types.go
  pkg/test/ginkgo/cmd_runsuite.go
Labels: approved, lgtm, tide/merge-method-squash, jira/valid-reference, acknowledge-critical-fixes-only

#29551 OCPBUGS-48749: Add/remove team members to the OWNERS file for Builds
  test/extended/builds/OWNERS
  test/extended/testdata/builds/OWNERS
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#29450 TRT-1286: List images from external binaries
  go.mod
  hack/update-generated.sh
  pkg/cmd/openshift-tests/images/images_command.go
  pkg/test/extensions/binary.go
Labels: approved, lgtm, vendor-update, e2e-images-update, jira/valid-reference, acknowledge-critical-fixes-only

#29326 OCPBUGS-26601: Re-enable AWS for router HTTP/2 test
  test/extended/router/h2spec.go
  test/extended/router/http2.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#29549 CNTRLPLANE-1: Update to Kubernetes v1.32.2
  go.mod
  go.sum
  images/tests/Dockerfile.rhel
  test/extended/util/image/zz_generated.txt
  vendor/k8s.io/apiserver/pkg/server/config.go
  vendor/k8s.io/apiserver/pkg/server/options/etcd.go
  vendor/k8s.io/apiserver/pkg/server/patch_genericapiserver.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/etcd3retry/retry_etcdclient.go
  vendor/k8s.io/apiserver/pkg/storage/storagebackend/factory/retry_etcdprobemonitor.go
  vendor/k8s.io/kubelet/pkg/apis/well_known_openshift_labels.go
  vendor/k8s.io/kubernetes/openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  vendor/k8s.io/kubernetes/openshift-hack/e2e/annotate/rules.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/filters/apirequestcount/apiaccess_count_controller.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/filters/apirequestcount/deprecated.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/filters/apirequestcount_filter.go
  vendor/k8s.io/kubernetes/pkg/features/versioned_kube_features.go
  vendor/k8s.io/kubernetes/pkg/kubelet/server/server.go
  vendor/k8s.io/kubernetes/pkg/util/kernel/constants.go
  vendor/k8s.io/kubernetes/test/e2e/apimachinery/health_handlers.go
  vendor/k8s.io/kubernetes/test/e2e/storage/csimock/csi_volume_expansion.go
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/gce-pd/controller_ss.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-plugin.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-attacher.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-resizer.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-snapshotter.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-proxy.yaml
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, e2e-images-update, jira/valid-reference

#29557 NO-JIRA: Allow overriding extension binary to local path
  pkg/test/extensions/README.md
  pkg/test/extensions/binary.go
  pkg/test/extensions/provider.go
  pkg/test/extensions/provider_test.go
Labels: approved, lgtm, jira/valid-reference

#29560 OCPBUGS-50587: Rely on unstructured for update status instead of type conversion
  test/extended/apiserver/patch.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#29569 WRKLDS-1653: update pathological ScalingReplicaSet event exception
  pkg/monitortestlibrary/pathologicaleventlibrary/duplicated_event_patterns.go
Labels: approved, lgtm, jira/valid-reference
