Repository openshift/origin, pull requests merged in 2025-06, with the labels that each got.

#29867 OCPBUGS-54412: Do not retry extension-sourced tests
  pkg/test/ginkgo/cmd_runsuite.go
  pkg/test/ginkgo/test_suite.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#29874 OCPBUGS-56037: Stabilize custom MCP cleanup on MCN tests
  test/extended/machine_config/helpers.go
  test/extended/machine_config/machine_config_node.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#29887 TRT-1854: set network for MicroShift to OVNKubernetes
  pkg/clioptions/clusterdiscovery/provider.go
Labels: approved, lgtm, jira/valid-reference

#29832 OCPBUGS-56512: updates ruby to version 3.3
  examples/quickstarts/rails-postgresql-persistent.json
  examples/quickstarts/rails-postgresql.json
  test/extended/builds/dockerfile.go
  test/extended/cli/setimage.go
  test/extended/image_ecosystem/s2i_images.go
  test/extended/testdata/bindata.go
  test/extended/testdata/builds/build-secrets/test-s2i-build.json
  test/extended/testdata/builds/statusfail-badcontextdirs2i.yaml
  test/extended/testdata/builds/statusfail-fetchimagecontentdocker.yaml
  test/extended/testdata/builds/statusfail-fetchsourcedocker.yaml
  test/extended/testdata/builds/statusfail-fetchsources2i.yaml
  test/extended/testdata/builds/statusfail-genericreason.yaml
  test/extended/testdata/builds/statusfail-oomkilled.yaml
  test/extended/testdata/builds/test-build-proxy.yaml
  test/extended/testdata/builds/test-build.yaml
  test/extended/testdata/builds/test-env-build.json
  test/extended/testdata/builds/test-imagesource-buildconfig.yaml
  test/extended/testdata/cluster/quickstarts/rails-postgresql.json
  test/extended/testdata/cmd/test/cmd/images.sh
  test/extended/testdata/cmd/test/cmd/testdata/image-streams/image-streams-centos7.json
  test/extended/testdata/cmd/test/cmd/testdata/new-app/imagestream-ref.yaml
  test/extended/testdata/image/test-image.json
  test/extended/testdata/long_names/fixture.json
  test/extended/testdata/run_policy/parallel-bc.yaml
  test/extended/testdata/run_policy/serial-bc.yaml
  test/extended/testdata/run_policy/serial-latest-only-bc.yaml
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#29776 MCO-1652: Add MCO disruptive suite
  test/extended/machine_config/boot_image_update_aws.go
  test/extended/machine_config/boot_image_update_gcp.go
  test/extended/machine_config/machine_config_node.go
  test/extended/machine_config/pinnedimages.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  zz_generated.manifests/test-reporting.yaml
Labels: approved, lgtm, jira/valid-reference

#29898 OCPBUGS-50701: Add test case for checking EgressFirewall DNS names in caps
  test/extended/networking/egress_firewall.go
  test/extended/testdata/bindata.go
  test/extended/testdata/egress-firewall/ovnk-egressfirewall-test.yaml
  test/extended/testdata/egress-firewall/ovnk-egressfirewall-wildcard-test.yaml
  test/extended/testdata/egress-firewall/sdn-egressnetworkpolicy-test.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#29871 OCPBUGS-56438: Update to Kubernetes v1.31.9
  go.mod
  go.sum
  images/tests/Dockerfile.rhel
  vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/nodevolumelimits/csi.go
  vendor/k8s.io/kubernetes/pkg/volume/util/operationexecutor/node_expander.go
  vendor/k8s.io/kubernetes/pkg/volume/util/operationexecutor/operation_generator.go
  vendor/k8s.io/kubernetes/pkg/volume/util/resize_util.go
  vendor/k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go
  vendor/k8s.io/kubernetes/test/e2e/storage/testsuites/multivolume.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#29808 MULTIARCH-5391: Add new featuregate test to check if desired.Architecture is set as intended
  test/extended/clusterversion/OWNERS
  test/extended/clusterversion/clusterversion.go
  test/extended/include.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  zz_generated.manifests/test-reporting.yaml
Labels: approved, lgtm, jira/valid-reference

#29916 OCPBUGS-57421: Add sustaining engineers to owners on image ecosystem
  test/extended/image_ecosystem/OWNERS
Labels: approved, lgtm, jira/valid-bug, jira/severity-low, jira/valid-reference

#29925 TRT-2165: Include select pending alert intervals in spyglass
  pkg/monitortests/testframework/timelineserializer/rendering.go
Labels: approved, lgtm, jira/valid-reference

#29902 [release-4.19] OCPBUGS-57217: Stabilize custom MCP cleanup on MCN tests
  test/extended/machine_config/helpers.go
  test/extended/machine_config/machine_config_node.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#29914 OCPBUGS-57397: properties should wrap around property
  pkg/test/ginkgo/junitapi/types.go
  tools/junitreport/pkg/api/types.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#29919 OCPBUGS-57426: Boot image controller should correctly handle marketplace boot images
  test/extended/machine_config/helpers.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/severity-critical, jira/valid-reference

#29828 NO-JIRA: We should always run tests where we have no opinion on their gate
  pkg/clioptions/suiteselection/feature_filter.go
Labels: approved, lgtm, jira/valid-reference

#29563 CORENET-5668: Update IPsec e2e test to validate NAT-T encapsulation option
  pkg/testsuites/standard_suites.go
  test/extended/networking/egressip_helpers.go
  test/extended/networking/internal_ports.go
  test/extended/networking/ipsec.go
  test/extended/networking/util.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, vendor-update, jira/valid-reference

#29939 OCPEDGE-1947: fix: resolve timeout problems during some arbiter tests
  test/extended/two_node/arbiter_topology.go
Labels: approved, lgtm, jira/valid-reference
