Repository openshift/origin, pull requests merged in 2025-09, with the labels that each got.

#30184 CNTRLPLANE-945: improve logging, add startup probe to Keycloak Deployment
  test/extended/authentication/keycloak_helpers.go
  test/extended/authentication/oidc.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only, verified

#30207 OCPBUGS-61229: images/tests: Remove rteval
  images/tests/Dockerfile.rhel
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, verified

#29386 CORENET-5329: revert primary udn test workaround from virt tests
  test/extended/networking/livemigration.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only, verified, verified-later

#30113 OCPBUGS-61063: test/extended/cli/adm_upgrade/recommend: Enable precheck and accept
  test/extended/cli/adm_upgrade/recommend.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, verified

#30220 CNF-18661: update the commatrix vendor version to contain new changes
  go.mod
  go.sum
  vendor/github.com/openshift-kni/commatrix/pkg/client/client.go
  vendor/github.com/openshift-kni/commatrix/pkg/consts/consts.go
  vendor/github.com/openshift-kni/commatrix/pkg/types/static-custom-entries.go
  vendor/github.com/openshift-kni/commatrix/pkg/utils/utils.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, jira/valid-reference, verified

#30227 OCPBUGS-60507: Bump to latest openshift/kubernetes (v1.33.4)
  go.mod
  go.sum
  images/tests/Dockerfile.rhel
  test/extended/util/image/zz_generated.txt
  vendor/k8s.io/apiserver/pkg/admission/audit.go
  vendor/k8s.io/apiserver/pkg/audit/context.go
  vendor/k8s.io/apiserver/pkg/audit/request.go
  vendor/k8s.io/apiserver/pkg/authentication/token/cache/cached_token_authenticator.go
  vendor/k8s.io/apiserver/pkg/cel/common/schemas.go
  vendor/k8s.io/apiserver/pkg/endpoints/filters/audit.go
  vendor/k8s.io/apiserver/pkg/endpoints/filters/authn_audit.go
  vendor/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go
  vendor/k8s.io/apiserver/pkg/endpoints/filters/request_deadline.go
  vendor/k8s.io/apiserver/pkg/storage/cacher/delegator.go
  vendor/k8s.io/apiserver/pkg/util/webhook/webhook.go
  vendor/k8s.io/component-helpers/resource/helpers.go
  vendor/k8s.io/kubernetes/openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/admission/storage/performantsecuritypolicy/admission.go
  vendor/k8s.io/kubernetes/pkg/kubelet/allocation/allocation_manager.go
  vendor/k8s.io/kubernetes/pkg/kubelet/allocation/state/state.go
  vendor/k8s.io/kubernetes/pkg/kubelet/allocation/state/state_checkpoint.go
  vendor/k8s.io/kubernetes/pkg/kubelet/allocation/state/state_mem.go
  vendor/k8s.io/kubernetes/plugin/pkg/admission/noderestriction/admission.go
  vendor/k8s.io/kubernetes/test/e2e/network/service_cidrs.go
  vendor/k8s.io/kubernetes/test/e2e/storage/csimock/base.go
  vendor/k8s.io/kubernetes/test/e2e/storage/csimock/csi_selinux_mount.go
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/k8s.io/utils/net/multi_listen.go
  vendor/modules.txt
  zz_generated.manifests/test-reporting.yaml
Labels: approved, lgtm, vendor-update, e2e-images-update, jira/valid-bug, jira/valid-reference, verified

#30160 OTA-1559: test/extended/cli/adm_upgrade/recommend: TestRiskA PromQL use max_over_time
  test/extended/cli/adm_upgrade/recommend.go
Labels: approved, lgtm, jira/valid-reference, verified

#30247 NO-JIRA: Deflake oc observe test by using explicit port number
  test/extended/cli/observe.go
Labels: approved, lgtm, jira/valid-reference, verified

#30248 NO-JIRA: Increase request-timeout to deflake test
  test/extended/cli/timeout.go
Labels: approved, lgtm, jira/valid-reference, verified

#30093 OCPNODE-3557: oc debug managed by label is checked by e2e test
  test/extended/cli/debug.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, tide/merge-method-squash, jira/valid-reference, acknowledge-critical-fixes-only, verified

#30054 MON-4290: add test for must-gather gather_metrics
  test/extended/cli/mustgather.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only, verified

#30211 TRT-2275: introduce cluster e2e-analysis sub command for openshift-tests
  cmd/openshift-tests/openshift-tests.go
  pkg/cmd/openshift-tests/e2e-analysis/command.go
  pkg/e2eanalysis/e2e_analysis.go
  pkg/e2eanalysis/e2e_analysis_test.go
Labels: approved, lgtm, jira/valid-reference, verified

#30252 OCPEDGE-2090: Add validation tests for tnf topology effects
  pkg/testsuites/standard_suites.go
  test/extended/two_node/tnf_topology.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  zz_generated.manifests/test-reporting.yaml
Labels: approved, lgtm, jira/valid-reference, verified

#30242 OCPSTRAT-2371: Update etcd test data for k8s 1.34 release
  test/extended/etcd/etcd_storage_path.go
Labels: approved, lgtm, jira/valid-reference, verified

#30261 NO-JIRA: Allow systemd-coredump test to fail
  pkg/monitortests/node/kubeletlogcollector/monitortest.go
Labels: approved, lgtm, jira/valid-reference, verified

#30265 OCPBUGS-61855: CRD Apply Alert Allowance
  pkg/alerts/allowed_conformance.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, verified, verified-later

#29815 [release-4.19] OCPBUGS-56213: Skip GatewayAPIController tests on clusters without OLM capabilities
  test/extended/router/gatewayapicontroller.go
  test/extended/util/framework.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/severity-critical, jira/valid-reference, verified

#30224 OCPBUGS-61398: fix(test): prevent nil pointer dereference in ginkgo test runner
  pkg/test/ginkgo/status.go
  pkg/test/ginkgo/test_runner.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, verified

#30271 CNF-18661: Update vendor with communication matrix bug fixes on 4.20
  go.mod
  go.sum
  vendor/github.com/openshift-kni/commatrix/pkg/client/client.go
  vendor/github.com/openshift-kni/commatrix/pkg/commatrix-creator/commatrix.go
  vendor/github.com/openshift-kni/commatrix/pkg/consts/consts.go
  vendor/github.com/openshift-kni/commatrix/pkg/endpointslices/endpointslices.go
  vendor/github.com/openshift-kni/commatrix/pkg/types/static-custom-entries.go
  vendor/github.com/openshift-kni/commatrix/pkg/utils/utils.go
  vendor/github.com/openshift-kni/commatrix/test/pkg/cluster/cluster.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, jira/valid-bug, jira/valid-reference, verified

#30110 OCPEDGE-1483: Add TNF E2E tests for network failure
  test/extended/two_node/tnf_recovery.go
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/nodes.go
  zz_generated.manifests/test-reporting.yaml
Labels: approved, lgtm, jira/valid-reference, verified

#29085 CORENET-6418: drop openshift-sdn tests
  go.mod
  go.sum
  test/extended/cli/explain.go
  test/extended/networking/cnimigration.go
  test/extended/networking/egress_firewall.go
  test/extended/networking/egressip.go
  test/extended/networking/egressip_helpers.go
  test/extended/networking/isolation.go
  test/extended/networking/multicast.go
  test/extended/networking/route_advertisements.go
  test/extended/networking/services.go
  test/extended/networking/util.go
  test/extended/prometheus/prometheus.go
  test/extended/testdata/bindata.go
  test/extended/testdata/egress-firewall/sdn-egressnetworkpolicy-test.yaml
  test/extended/util/annotate/generated/zz_generated.annotations.go
  test/extended/util/image/image.go
  test/extended/util/image/zz_generated.txt
  vendor/github.com/openshift/cluster-network-operator/LICENSE
  vendor/github.com/openshift/cluster-network-operator/pkg/names/names.go
  vendor/github.com/openshift/library-go/pkg/network/networkutils/networkutils.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, e2e-images-update, jira/valid-reference, verified

#30226 trt-2246: lower parallelism based on worker nodes
  pkg/test/ginkgo/cmd_runsuite.go
  pkg/test/ginkgo/test_suite.go
  pkg/testsuites/standard_suites.go
Labels: approved, lgtm, jira/valid-reference, verified

#30282 OTA-1626: Fail CI if alert/ClusterOperatorDegraded is fired
  pkg/monitortestlibrary/allowedalerts/all.go
Labels: approved, lgtm, jira/valid-reference, verified

#30285 OCPQE-30698:enable OTE for olmv0
  pkg/test/extensions/binary.go
Labels: approved, lgtm, jira/valid-reference, verified

#30289 OCPBUGS-61398: fix(ginkgo): avoid nil deref and harden env var setup
  pkg/test/ginkgo/status.go
  pkg/test/ginkgo/test_runner.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, verified

#30302 OCPBUGS-62227: bump telemetry series limit to 1000
  test/extended/prometheus/prometheus.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference, verified

#30288 MCO-1875: Bump timeout for vSphereBootimageUpdate tests
  test/extended/machine_config/helpers.go
Labels: approved, lgtm, jira/valid-reference, verified, verified-later

#30308 NO-JIRA: Add olm into the known operator set
  pkg/monitortestlibrary/platformidentification/operator_mapping.go
Labels: approved, lgtm, jira/valid-reference, verified

#30313 Revert "NO-JIRA: Add olm into the known operator set"
  pkg/monitortestlibrary/platformidentification/operator_mapping.go
Labels: approved, lgtm, jira/valid-reference, verified
